cmd/lotus-worker/main.go
Listen for interrupt signals in GetStorageMinerAPI loop, allowing for graceful shutdown in case the worker is brought up before the lotus-miner process is running.
**Before:**
```
lotus-worker run
2023-10-03T04:19:52.209-0400    INFO    main    lotus-worker/main.go:296        Starting lotus worker
Connecting to miner API... (RPC client error: sendRequest failed: Post "http://10.2.2.22:2345/rpc/v0": context canceled)
Connecting to miner API... (RPC client error: sendRequest failed: Post "http://10.2.2.22:2345/rpc/v0": context canceled)
Connecting to miner API... (RPC client error: sendRequest failed: Post "http://10.2.2.22:2345/rpc/v0": context canceled)^C^C^C
Connecting to miner API... (RPC client error: sendRequest failed: Post "http://10.2.2.22:2345/rpc/v0": context canceled)^C
``` …
=> fix: worker: listen for interrupt signals in GetStorageMinerAPI loop

CHANGELOG.md, chain/messagepool/messagepool.go, metrics/metrics.go
Partially #10547.  Also nice to have when investigating things like MpoolSelect times, syncing, etc, and its potential correlations with size of the Mpool.
Recording the amount of pending messages in the mpool. The metric is updated after messages are removed from the pool (which happens on HeadChange or pruneMessage).
Testing: in `localhost:1234/debug/metrics`, you now have:
```
lotus_mpool_message_count 180
```
=> feat: metric: export Mpool message count

node/impl/full/eth.go, node/impl/full/eth_test.go, node/impl/full/eth_trace.go, node/impl/full/eth_utils.go
When generating eth traces, we encode "native" message inputs/outputs to "solidity ABI" by formatting the inputs/outputs the same way we do in FEVM's "handle_native_method". However, we had quite a few bugs with the implementation:
1. We were right-aligning 64bit values in 256bit words, instead of left-aligning (as we should given that these values are big-endian).
2. The return-value encoding wasn't correctly handling lengths.
This patch:
1. Fixes those bugs.
2. Deduplicates the logic (we're doing _basically_ the same thing in both cases).
3. Removes all error paths (these functions can't fail).
- `PR type`: fix, feat, build, chore, ci, docs, perf, refactor, …
=> fix: eth: correctly encode and simplify native input/output encoding

CHANGELOG.md, node/impl/storminer.go, storage/pipeline/sealing.go
https://github.com/filecoin-project/boost/issues/1733
https://github.com/filecoin-project/boost/issues/1747
(**summary of these issues is available in `Additional Info` below**)
Based on the discussions in the two issues mentioned above, and initial issue by @ze42 and @cryptowhizzard, I propose to retrieve the information from the stats (prometheus) rather than from the API. 
This PR was quickly discussed by @s0nik42 with @magik6k, and here is a list of changes mades:
- Create a method in `Sealing` called `SectorsSummary` in order to return the stats by states available in `SectorStats`
- Update the SectorsSummary method in StorageMinerAPI, to use the previous method. This allows to return the result more quickly (already updated with each state modification), and to avoid recalculating …
=> feat: sealing: load SectorsSummary from sealing SectorStats instead of calling API each time

chain/consensus/filcns/upgrades.go
As [discussed on slack](https://filecoinproject.slack.com/archives/CP50PPW2X/p1699390747053129?thread_ts=1699365130.155229&cid=CP50PPW2X). Current estimated premigration time for nv21 is 20 minutes - and setting the premigration to 90 minutes before the upgrade epoch should give ample of time for the migration to finish.
Move premigration to 90 minutes before the upgrade epoch.
- Needs backport to `release/v1.24.0` before cutting final release
- Needs backport to `release/v1.25.0` before cutting final release
- `area`, e.g. api, chain, state, market, mempool, multisig, …
=> fix: migration: set premigration to 90 minutes

chain/consensus/filcns/upgrades.go, chain/stmgr/forks.go, chain/vm/fvm.go, miner/miner.go, node/impl/full/sync.go
The calibrationnet is currently in an inconsistent state, where there are miner actor CIDs that are not present in the system actor state. We need to backfix the `upgradeActorsV12Fix` to ALSO migrate the system actor state, this will leave us in a correct state.
- Correctly migrate the system actor state at the v12 "fix"
- Ask users / miners to rollback history and reperform the migration.
=> fix: nv21fix migration: correctly upgrade system actor

chain/consensus/filcns/upgrades.go
Backports #11395 to release/v1.24.0.
Move premigration to 90 minutes before upgrade epoch.
=> chore: backport #11395 to release/v1.24.0

cmd/lotus-provider/run.go, lib/harmony/harmonydb/sql/20230823.sql, provider/builder.go, provider/lpwindow/compute_do.go, provider/lpwindow/recover_task.go, provider/lpwindow/submit_task.go
Part of https://github.com/filecoin-project/lotus/issues/11113
=> feat: wdpost: Declare-recovered task

chain/consensus/filcns/upgrades.go, chain/stmgr/forks.go, chain/vm/fvm.go, miner/miner.go, node/impl/full/sync.go
This hotfix has landed in the 1.24.0 and 1.25.0 branches, but is needed in master to sync calibnet. The plan was to just wait those release branches get merged to master, but given the uncertainty around nv21, let's forward-port this so we can sync calibnet on master again.
Forward-port calibnet hotfix patch.
=> chore: forward-port calibnet hotfix to master

cmd/lotus-miner/actor.go, documentation/en/cli-lotus-miner.md
chore: backport #11408 to release/v1.25.0
=> chore: backport #11408 to release/v1.25.0

cmd/lotus-miner/actor.go, documentation/en/cli-lotus-miner.md
This PRs mergeability depends on the resolution of the [nv21 decision matrix for the FIP0070 bug](https://filecoin.notion.site/nv21-decision-matrix-for-FIP0070-bug-a39174216ee1479eab9a55b2f23da520).
Specifically, it should only be merged if `Option 2: Descope FIP-0070 from nv21`  is chosen as the preferred course of action. If Option 2 is preferred, it should also be backported to the `release/v1.24.0` and `release/v1.25.0` branches.
Remove the `lotus-miner actors move-partitions` command.
- `area`, e.g. api, chain, state, market, mempool, multisig, networking, paych, proving, …
=> chore: cli: Revert move-partitions cmd

go.mod, go.sum
Drops FIP-0070 related code, and pulls in an invariants improvement.
=> chore: deps: update to go-state-types v0.12.7

node/impl/full/eth.go
We added this check as a self-test to make sure that the message indices in our trace matched up with those in the block. Unfortunately, this only works for blocks on the main-chain, and breaks tracing of uncle blocks (and tracing of head).
=> fix: eth: remove trace sanity check

CHANGELOG.md, chain/types/ethtypes/eth_transactions.go, itests/eth_hash_lookup_test.go, node/impl/full/eth.go, node/impl/full/eth_event.go, node/impl/full/eth_trace.go, node/impl/full/eth_utils.go, node/impl/full/txhashmanager.go
Part of #11355
We need to always use the state-tree from the tipset _after_ the message executed (i.e., the state-tree produced by executing the tipset). If we use any other state-tree, we might not find the address we're trying to resolve.
This change also has some implication for pending messages: there's no guarantee we'll be able to generate a 0x-style address for a pending native message. So, instead of trying, I've removed support for pending native messages from the Eth API. Messages from EthAccounts will still work, and native messages will still show up in blocks/traces, they just won't show up as "pending". Which should affect exactly nobody.
I'm also taking this opportunity to cleanup some edge-cases:
1. Pass contexts where appropriate.
2. Remove all state access from …
=> fix: eth: use the correct state-tree when resolving addresses

CHANGELOG.md, itests/eth_hash_lookup_test.go, itests/eth_transactions_test.go, itests/fevm_address_test.go, itests/kit/evm.go, node/impl/full/eth_utils.go
Part of #11355
When translating "native" messages to Ethereum transactions, correctly handle parameters:
1. If the message looks like a valid "create external", treat it as a contract creation.
2. If it looks like a valid EVM invocation, decode it as such.
3. Otherwise, ABI-encode the parameters to make them look like a "handle_filecoin_method" call. This will help chain explorers recognize these messages.
Testing TODO:
=> feat: eth: encode eth tx input as solidity ABI

build/bootstrap/mainnet.pi
These nodes have been offline for many moons.
=> Remove dead bootstrap nodes from mainnet.pi

cmd/lotus-bench/simple.go
The latest proofs-release expects the seed-value to be a non zero value. In the lotus-bench we currently had set this to all zeros, which causes the Commit2 bench to fail with:
```
./lotus-bench simple commit2 /home/misty/benchdir/c1.json
2023-11-16T17:51:54.256 DEBUG filcrypto::util::types > seal_commit_phase2: start
2023-11-16T17:51:54.257 INFO filecoin_proofs::api::seal > seal_commit_phase2:start: SectorId(1)
2023-11-16T17:51:54.257 DEBUG filcrypto::util::types > seal_commit_phase2: end
2023-11-16T17:51:54.257Z	WARN	lotus-bench	lotus-bench/main.go:129	Invalid porep challenge seed
```
(Ref: https://github.com/filecoin-project/lotus/pull/11185#issuecomment-1814960653)
This PR sets the ticket and seed value to a non zero value.
```
./lotus-bench simple commit2 --synthetic=true …
```
=> fix: bench: Set ticket and seed to a non-all zero value

build/bootstrap/calibnet.pi, build/bootstrap/mainnet.pi
Added new bootstrap Glif nodes (space07, calibration-archive)
=> add glif bootstrap node on calibration

scripts/supraseal-pc2.sh
Add the SupraSeal-PC2 script made by @vmx 🙏 to the `/scripts` folder in Lotus, to make building the SupraSeal-PC2 binary easier and without needing SPDK checkout.
Running the script on a machine with the proper pre-requisites (which will be in the Lotus documentation)
```
cd scripts/
./supraseal-pc2.sh
Cloning into 'supra_seal'...
remote: Enumerating objects: 772, done.
remote: Counting objects: 100% (299/299), done.
remote: Compressing objects: 100% (139/139), done.
----
+ cc -O2 -fno-builtin -fPIC -Wall -Wextra -Werror -march=native -D__ADX__ -mno-avx -c ./src/server.c
+ cc -O2 -fno-builtin -fPIC -Wall -Wextra -Werror -march=native -D__ADX__ -mno-avx -c ./build/assembly.S
+ ar rc libblst.a assembly.o server.o
```
Which will give you the supra_seal folder with the pc2-binary ready for …
=> feat: build: Add SupraSeal-PC2 binary script

build/builtin_actors_gen.go
Update actors to the final v12 release. This doesn't change any of the CIDs as the code is the same.
=> chore: actors: update v12 to the final release

chain/store/index_test.go, chain/store/snapshot.go, chain/store/store_test.go, cmd/lotus-bench/import.go, cmd/lotus-shed/genesis-verify.go, cmd/lotus/daemon.go
This cherrypicks https://github.com/filecoin-project/lotus/pull/10821/commits/921a3a02d47abaabd97096f8647bbc3f7a07e2ae from https://github.com/filecoin-project/lotus/pull/10821
* Snapshot cars are written from chain top to bottom
* We know what the top block header is because that's the car root
* We know that the links in that block header will lead us to the correct parent
* So when we see parents of the last seen block, we record those
* Snapshots contain all block headers to genesis, so if we repeat this process for the whole import we never have to read a single block to find the genesis block
* This way we can instantly set the correct genesis after snapshot import without having to walk there, saving roughly 17 000 000  useless reads from chainstore
* (This is what causes the hand …
=> feat: chain import: don't walk to genesis - 2-3x faster snapshot import

CHANGELOG.md, itests/sector_pledge_test.go, storage/pipeline/stats.go
Fixes a small regression from https://github.com/filecoin-project/lotus/pull/11353
Before this fix `lotus-miner info` would show zero counts for states through which at least one sector has passed since starting the miner process:
```
Sectors:
Total: 8268
Proving: 3194
Available: 165
WaitDeals: 0
AddPiece: 1
: 0
Packing: 0
GetTicket: 0
PreCommit1: 11
Committing: 0
CommitFinalize: 0
SubmitCommit: 0
CommitWait: 1
FinalizeSector: 0
Removed: 4896
```
After this PR:
```
Sectors:
Total: 8269
Proving: 3194
Available: 165
AddPiece: 1
Packing: 1
PreCommit1: 11
CommitWait: 1
Removed: 4896
```
- `PR type`: fix, feat, build, chore, ci, docs, perf, refactor, revert, style, …
=> fix: miner info: Show correct sector state counts

provider/lpwinning/winning_task.go
Part of https://github.com/filecoin-project/lotus/issues/11383, probably the final thing
In the winning PoSt adder there is now a check which will prevent mining attempts which don't include blocks we have mined ourselves previously in the base
* Untested, would be good to see if this actually works on a devnet
=> lpwinning: Check inclusion of self-mined blocks in base

cmd/lotus-bench/simple.go
Need this to generate static info for winningPoSt warmup in lotus-provider
=> feat: bench: flag to output GenerateWinningPoStWithVanilla params

node/modules/chain.go
Make failure to load the chain state fatal. Otherwise, we get strange panics later.
=> fix: chain: make failure to load the chain state fatal

build/isnearupgrade.go
Only consider an epoch near an upgrade if the upgrade is enabled (the upgrade epoch is >= 0). This isn't a huge deal, but we'd otherwise consider the first finality epochs (or so) to be "near" any disabled upgrade.
=> fix: build: an epoch is near an upgrade iff the upgrade is enabled

lib/harmony/harmonydb/sql/20230712.sql
=> path index: dbindex: Fix sector_location schema

cmd/lotus-shed/invariants.go
This command currently:
- doesn't work with splitstore
Support splitstore
=> fix: shed: make invariants checker work with splitstore

provider/lpmessage/sender.go
=> fix: lotus-provider: lotus-provider msg sending

provider/lpmessage/sender.go
Backport #11485 to the `release/v1.25.1` branch
=> chore: fix: sql Scan cannot write to an object

provider/lpmessage/sender.go
lotus-provider sql fix in message send. 
=> fix: sql Scan cannot write to an object

cmd/lotus-provider/run.go
Display the addresses in lotus-providers `This lotus_provider instance handles` log.
**Before:**
` This lotus_provider instance handles {"miner_addresses": ["{}"], "tasks": ["SendMessage", "WdPost", "WdPostSubmit", "WdPostRecoverDeclare"]}`
**After:**
` This lotus_provider instance handles {"miner_addresses": ["t01000"], "tasks": ["SendMessage", "WdPost", "WdPostSubmit", "WdPostRecoverDeclare"]}`
=> fix: lotus-provider: show addresses in log

lib/harmony/harmonytask/harmonytask.go, provider/lpmessage/sender.go, provider/lpwindow/recover_task.go
Fixes the issue fixed by https://github.com/filecoin-project/lotus/pull/11492
=> fix: lotus-provider: Wait for the correct taskID

lib/harmony/harmonytask/harmonytask.go, lib/harmony/harmonytask/task_type_handler.go
On restart harmony would fail to reclaim tasks claimed because the owner_id was already non-null. With this change we just take ownership of all tasks which are recovered
```
2023-12-07T11:26:05.521+0100	DEBUG	harmonydb	harmonydb/harmonydb.go:133	SQL run	{"query": "\n\t\t\tWITH upsert AS (\n\t\t\t\tUPDATE harmony_machines\n\t\t\t\tSET cpu = $2, ram = $3, gpu = $4, last_contact = CURRENT_TIMESTAMP\n\t\t\t\tWHERE host_and_port = $1\n\t\t\t\tRETURNING id\n\t\t\t),\n\t\t\tinserted AS (\n\t\t\t\tINSERT INTO harmony_machines (host_and_port, cpu, ram, gpu, last_contact)\n\t\t\t\tSELECT $1, $2, $3, $4, CURRENT_TIMESTAMP\n\t\t\t\tWHERE NOT EXISTS (SELECT id FROM upsert)\n\t\t\t\tRETURNING id\n\t\t\t)\n\t\t\tSELECT id FROM upsert\n\t\t\tUNION ALL\n\t\t\tSELECT id FROM inserted;\n\t\t", "err": null, …
```
=> harmony: Fix task reclaim on restart

chain/exchange/cbor_gen.go, chain/exchange/client.go, chain/exchange/protocol.go, chain/exchange/protocol_encoding.go, gen/main.go
Sync issues.
Allow up to 10k messages per block.
Also explicitly limit how many bytes we're willing to read in one go such that we're capable of reading a worst-case tipset (like, really, never going to happen worst-case). Previously, this wasn't an issue. However, we've bumped the max number of messages from 8,192 to 150,000 and need to limit allocations somewhere else.
=> fix: exchange: allow up to 10k messages per block

chain/exchange/protocol_encoding.go
It's not a const for the testground build, and needs to be an int 99% of the time. So we might as well just cast here.
=> fix: exchange: explicitly cast the block message limit const

cmd/lotus-provider/proving.go
Fixes a minor issue in the logging output of the wdPostTaskCmd action in the proving.go file. Previously, the log output for the result was not formatted correctly, leading to extraneous output in the logs. 
**Before you would get `Result:%!(EXTRA string=`**
```
lotus-provider --db-host=localhost test window-post task
repopath ~/.lotusprovider
Inserted task 1701. Waiting for success 2023-12-07T11:30:24.502+0100	INFO	mainlotus-provider/proving.go:120	Result:%!(EXTRA string={
"deadline": 0,
"partition": 0,
"proof_params": "hQCBggBAgYIKWMCnQ1eJeQ3JcqgJkwuRW/9zOOvQD3T0gFiGwuZoGgWC0Zp+/b40HKVC932VjaybzVmr8rAVDOZSLLqWTOl1CdpSCp4LGSiv5dMBo8G3GsMCqVM8LsM7KSjNMZiqefOgtBQQPJ3U5DYdpHLeZPsugeicQuayvHE6oJpwBzY7z4f58TYJIS3f5AQl77tsYilbtvmi7tGbUTUSbPskY8kgi8u6XI9+/IjsV6U/B9FcDhFiegcuH+MH1/Rde9K4GunCF/MAQ …
```
=> fix: lotus-provider: Fix log output format in wdPostTaskCmd

Makefile, api/docgen/docgen.go, documentation/en/api-v0-methods-provider.md
Ensure 'make gen' & 'make docsgen' produce a Provider API and CLI interface docs.
=> lp docsgen

cmd/lotus-provider/proving.go, lib/harmony/harmonydb/harmonydb.go, lib/harmony/harmonydb/userfuncs.go, lib/harmony/harmonytask/task_type_handler.go, storage/paths/db_index.go
1. Retry txns that have a serialization error. It's recoverable.
2. Disallow incorrectly coded Transactional code by detecting it at runtime.
=> fix: lotus-provider: Serialization fix

node/impl/full/eth_utils.go
Decode messages as contract deployments if and only if the "to" address is the EAM.
Previously, we weren't checking the "to" address. I've also re-ordered the operations in this function to make it easier to reason about them. It'll have a slight runtime cost (we _always_ ABI-encode the parameters, then throw away the result if it turns out we're actually dealing with an Ethereum transaction), but it's _much_ simpler.
=> fix: eth: decode as actor creation iff "to" is the EAM

Makefile, api/docgen/docgen.go, cmd/lotus-provider/migrate.go, cmd/lotus-provider/proving.go, cmd/lotus-provider/run.go, documentation/en/api-v0-methods-provider.md, lib/harmony/harmonytask/harmonytask.go, lib/harmony/harmonytask/task_type_handler.go, provider/lpmessage/sender.go, provider/lpwindow/recover_task.go
Backports lotus-provider bugs caught in testing of v1.25.2-rc1 into the release/v1.25.2 branch. The backports are:
- https://github.com/filecoin-project/lotus/pull/11490
- https://github.com/filecoin-project/lotus/pull/11493
- https://github.com/filecoin-project/lotus/pull/11498
- https://github.com/filecoin-project/lotus/pull/11504
- https://github.com/filecoin-project/lotus/pull/11488
- https://github.com/filecoin-project/lotus/pull/11486
=> backports: lotus-provider: fixes caught in rc1-testing

documentation/en/cli-lotus-miner.md, documentation/en/cli-lotus-provider.md, documentation/en/cli-lotus.md, scripts/generate-lotus-cli.py
Modify the generate-lotus-cli.py script to generate documentation for the primary sub-commands, ignoring any aliases. Previously the script would fail to generate CLI-documentation for commands with aliases, so we only would get an empty output: https://github.com/filecoin-project/lotus/blob/master/documentation/en/cli-lotus.md#lotus-state-sector-sector-info
Also add lotus-provider to the CLI-documentation generation script.
=> fix: docs: Modify generate-lotus-cli.py to ignoring aliases.

chain/sync.go
Towards https://github.com/filecoin-project/lotus/issues/11530#issuecomment-1858361838
Logging and analysis have shown that nearly 100% of calls to syncFork are for a very specific case: when `incoming.Parents() ⊂ known`. Currently, we fetch 900 tipsets in this case. We _actually_ need to fetch ZERO.
Check if there are any common blocks between `known` and `incoming.Parents()`. If there are, we simply need to return [incoming.Parents, incoming]. We _know_ we already have `incoming`, so we just need `incoming.Parents`. We now check our local store to fetch `incoming.Parents` (which according to experiments we almost always do), and if we don't we fallback onto the network requesting the ONE tipset.
- example: ` fix: mempool: …
=> feat: syncer: optimize syncFork for one-epoch forks

chain/sync.go
Both @TippyFlitsUK and I ran into failures on [this line](https://github.com/filecoin-project/lotus/blob/7f684ec84008c6996bb2c6f39ce444ca4623c278/chain/exchange/client.go#L278) when running latest master. This is due to a bug in #11533, which causes us to return one EXTRA tipset in the return. This return then gets folded into the `blockSet`, which includes the `incoming` tipset already, leading to us having a non-continuous "chain".
Only return `incomingParents` in this case.
Please don't merge until I've done some additional testing.
- `area`, e.g. api, chain, state, market, …
=> fix: sync: do not include incoming in return of syncFork

lib/harmony/harmonytask/task_type_handler.go, provider/lpwinning/winning_task.go
This PR fixes a small bug where occasionally in epochs where we didn't win a block we would, for whatever reason, fail to persist that we didn't won on a given mining base, but still would mark the task as successfully executed.
This could lead to an edge-case where if we could win in the next epoch mining on the same base, we wouldn't try, because that could trigger a slashing condition
=> lpwinning: Don't say a task is done when persistNoWin fails

chain/sync.go, storage/sealer/worker_local.go
Backports:
- https://github.com/filecoin-project/lotus/pull/11533
- https://github.com/filecoin-project/lotus/pull/11541
The above fixes syncing issues that some users observed around the network upgrade.
- https://github.com/filecoin-project/lotus/pull/11550
Fixing a issue where PoSts-workers was unable to compute windowPoSts.
=> chore: backports to `release/v1.25.2`

chain/types/ethtypes/eth_types.go, chain/types/ethtypes/eth_types_test.go
-------
Alternative to https://github.com/filecoin-project/lotus/pull/11471
> The correct name for this field is 'input' according to the Ethereum specs [0].
> However, for the longest time, clients have been using 'data' and servers have been
> lenient to accept both, preferring 'input' over 'data' when both appear.
>
> Our lack of support for 'input' had gone unnoticed until go-ethereum decided
> to adjust their ethclient implementation to issue eth_call and eth_estimateGas
> requests with the 'input' field instead of 'data' [1]. This suddenly broke apps
> using this client against Lotus' Eth API.
>
> [0]: https://github.com/ethereum/execution-apis/blob/main/src/schemas/transaction.yaml#L33-L35
> [1]: ethereum/go-ethereum#28078
Before you mark the PR ready for review, please make sure …
=> fix: Eth API: accept input data in call arguments under field 'input'

chain/exchange/client.go, chain/exchange/interfaces.go
Fixes #11529 
Change `GetBlocks` to always return `count` tipsets, unless we hit genesis. Partial responses are treated as correct, but the exchanger will still request more tipsets (instead of returning fewer than requested tipsets to the caller).
=> feat: exchange: change GetBlocks to always fetch the requested number of tipsets

CHANGELOG.md, chain/exchange/client.go, chain/exchange/interfaces.go
Updating the changelog with latests backports, which includes docker build fix, sync fix and deps bump.
=> chore: release: update changelog with latests backports

CHANGELOG.md
Closes https://github.com/filecoin-project/lotus/issues/11476
Last step of the release-flow for v1.25.2, merging the releases branch into master with conflicts resolved.
=> chore: releases: merge releases branch to master

cmd/lotus/daemon.go
See https://github.com/filecoin-project/lotus/pull/11579/files#r1453900324
1. Let the user specify `--remove-existing-chain=false` to avoid the prompt and fail if there's an existing chain.
2. Only prompt when interactive. Otherwise, _don't_ remove the chain by-default.
=> fix: daemon: avoid prompting to remove chain when noninteractive

Dockerfile, scripts/docker-lotus-entrypoint.sh
- Updates Dockerfile to default to a working snapshot endpoint
```bash
curl -I https://snapshots.mainnet.filops.net/minimal/latest
HTTP/1.1 503 Service Unavailable: Back-end server is at capacity
Connection: keep-alive
```
```bash
curl -I https://forest-archive.chainsafe.dev/latest/mainnet/
HTTP/2 302
...
```
- Since 1.25.2, entrypoint script requires `yes` to import the snapshot
=> fix: docker: Dockerfile import snapshot

chain/beacon/beacon.go, chain/beacon/drand/drand.go, chain/sync.go
This is a refactor of some of the beacon logic in preparation of FIP-0063, although this doesn't actually implement any logic towards that. 
We currently assume that the beacon entries included in blocks must make a contiguous chain (no skipped rounds). This is currently needed, because we're using chained randomness.
This PR doesn't lead to any change in behaviour, but changes the logic to instead rely on expected _rounds_. We expect a certain _round_ for every epoch, and include the beacon entry corresponding to that round in our blocks.
This makes the logic easier to extend when we switch to unchained randomness with a different period than Filecoin.
- `PR …
=> feat: drand: refactor round verification

chain/checkpoint.go, chain/store/checkpoint_test.go, chain/store/store.go
-------
F3
We can now atomically switch chains when checkpointing. Previously, we'd call `SetHead` followed by `SetCheckpoint`. Unfortunately, that's not atomic and the "head" could have reverted before we called `SetCheckpoint` (causing the latter to fail).
Now, we just call `SetCheckpoint` and let `SetCheckpoint` adjust our head. This changes the behavior of `ChainStore.SetCheckpoint`, but `Syncer.SyncCheckpoint` is the only caller anyways.
=> fix: sync: atomically switch chains when checkpointing

chain/stmgr/execute.go, node/impl/full/eth.go, node/impl/full/eth_utils.go
fixes #11335
This will re-execute tipsets to forcibly re-compute and store events when they're missing. This is effectively lazy backfilling of events.
NOTE: This _won't_ backfill the index itself, it'll just give us the events.
=> fix: eth: re-execute tipsets on missing events

chain/types/actor_event.go, chain/types/actor_event_test.go, itests/direct_data_onboard_test.go, node/impl/full/actor_event.go
Proposal is easier as a PR than as inline comments cause I had it open.
=> Minor tweaks to events types

chain/consensus/filcns/filecoin.go
Minor annoyance, there's no space after the text and the timestamp, also it should use `now` rather than recalc current unixtime.
=> Clean up warning message

itests/direct_data_onboard_test.go
From CI failure in https://github.com/filecoin-project/lotus/pull/11626
I think it's possible to get the same tipset for a height, somehow; or maybe it's too early to be getting the final tipset for the head's height? I'd like an explanation for this if someone has it.
=> Avoid duplicate messages when looking for receipts

chain/stmgr/forks.go
Remove migration cache skip hack from the StateManager.
We did this to avoid using cached migrations in the borked watermelon upgrade on calibrationnet, but we don't need to keep this in the code (even for users syncing from scratch).
=> fix: state: remove watermelon migration hack

build/params_calibnet.go, build/params_mainnet.go
Due to https://github.com/filecoin-project/core-devs/issues/166#issue-2138199398, we need to update epoch heights for nv22. Alignment on the exact epoch heights [are happening here.](https://filecoinproject.slack.com/archives/C05P37R9KQD/p1708505043403639)
=> chore: Update epoch heights for nv22

build/bootstrap/calibnet.pi, build/bootstrap/mainnet.pi
This pull request introduces changes related to adding Forest bootnodes in the Calibnet and Mainnet networks.
The motivation behind these changes is to enhance network reliability and decentralization by providing robust bootnodes for Forest nodes to connect to during network initialization.
Changes introduced in this pull request include:
Addition of 3 Forest bootnodes for Calibnet network.
Addition of 3 Forest bootnodes for Mainnet network.
=> new: add forest bootstrap nodes

build/bootstrap/calibnet.pi, build/bootstrap/mainnet.pi
Backports #11636 to the feat/nv22 branch
=> chore: backport #11636 to feat/nv22 branch

build/bootstrap/mainnet.pi
Do not merge without confirmation from fil-infra please.
Remove the PL operated bootstrap nodes from mainnet.pi.
Since the list is vendored in to lotus, we'll be shutting them down before
merging this change in order to ensure we can quickly recover in case something
goes catastrophically wrong. We'll then merge this change for future updates
=> Remove PL operated bootstrap nodes from mainnet.pi

Makefile
Is there a better way of doing this currently that I'm not seeing? I can see in the CircleCI config that we're explicitly listing packages and grouping them to be run on different machines.
=> Add `unittests` make target

provider/lpwinning/winning_task.go
When calculating the time after propagation delay for a given epoch we weren't adding the propagation delay. Now we are.
(this does not affect lotus-miner in any way, separate code)
=> fix: lpwinning: Fix MiningBase.afterPropDelay

api/api_lp.go, api/proxy_gen.go, build/openrpc/full.json, build/openrpc/gateway.json, build/openrpc/miner.json, build/openrpc/worker.json, cmd/lotus-provider/storage.go, documentation/en/api-v0-methods-provider.md
This PR adds a simple `storage find` command, similar to the one in lotus-miner, but with multi-miner support
```
$ ./lotus-provider cli storage find f02620 10
In 74e1d667-7bc9-49bc-a9a6-0c30afd8684c (cache, sealed, unsealed)
Sealing: false; Storage: true
Remote
URL: http://10.99.16.6:12300/remote/unsealed/s-t02620-10
```
=> feat: lotus-provider: storage find command

build/drand.go
Not sure what the history is but this host isn't resolvable.
Found this confirmation that it doesn't exist anymore: https://github.com/filecoin-project/lotus/issues/3256#issuecomment-678817335
=> Remove singapore drand testnet host from config

chain/stmgr/forks.go, go.mod, go.sum
This wires up the nv22 migration from https://github.com/filecoin-project/go-state-types/pull/246.
- Update GST
- do NOT update the cache when running the real migration, since the nv22 migration isn't reorg-resistant
=> chore: deps: update to go-state-types v13.0.0-rc.1

provider/lpseal/poller_commit_msg.go, provider/lpseal/poller_precommit_msg.go
Without setting the "this task has already run" flag to false the poller would never re-schedule any retry send tasks.
=> lpseal: Fix message retry

provider/lpffi/sdr_funcs.go, provider/lpffi/task_storage.go, provider/lpseal/task_sdr.go
This is a rewrite of https://github.com/filecoin-project/lotus/pull/11643 on top of harmonystorage
=> feat: lpseal: SDR Storage revervations

Makefile
There's currently a mismatch between `build` and `install` in that `install` always tries to install `lotus-provider` and will error if it's not built, but `build` doesn't build it for you; so a `make clean && make build && sudo make install` will always fail.
This adds `lotus-provider` to `build`, but the alternative is to remove `lotus-provider` from `install`. That option may be more appropriate since it's still under development?
=> Add lotus-provider to build to match install

build/drand.go, build/params_2k.go, chain/beacon/beacon.go, chain/beacon/drand/drand.go, chain/beacon/drand/drand_test.go, chain/beacon/mock.go, node/modules/dtypes/beacon.go
Backports #11632 to the `release/v1.26.0` branch.
=> chore: backport #11632 to release/v1.26.0

chain/consensus/filcns/upgrades.go, go.mod, go.sum
Bumps GST to v13.0.0-rc2, which also includes https://github.com/filecoin-project/go-state-types/pull/252 to unblock cross implementation Butterfly-network testing
=> chore: deps: update to go-state-types v13.0.0-rc.2

cli/filplus.go
Fixes https://github.com/filecoin-project/lotus/issues/11669
Addition column called "Expiration" equivalent to Claim.TermMax + claim.TermStart
=> feat: CLI: add expiration to claim list

.github/workflows/builtin-actor-tests.yml, build/builtin_actors_gen_test.go
#11683 
Add tests that assert the embedded built-in actors metadata is correct:
* the corresponding CAR file is present in built-in actors released
assets as a CAR file.
* the corresponding tar.zst is locally present and matches the expected
SHA-256 digest 
* manifest CID is the only root CID in the corresponding CAR file.
* actor CIDs are present in the corresponding CAR file.
Configure a dedicated CI workflow to only run the tests on:
* `release/*` branches,
* modification to `build/builtin_actors_gen.go`,
* or embedded ZST files.
Note: only the latest network version seem to have `BundleGitTag`. Tests depend on this value to fetch the right CAR file. 
- `PR …
=> test: build: Add tests to sanity check embedded built-in actors metadata

chain/beacon/beacon.go
@rvagg reported an inability to sync epoch 510 on calibnet, the UpgradeSkyrHeight (nv16). This is because that upgrade included a "bump" in drand, that required 2 rounds to be included at that epoch. For more see #2170 and #8606.
The implementation of FIP-0073 introduced a new check that block headers only include precisely those rounds as matching the block epochs. This check works correctly for all epochs EXCEPT the UpgradeSkyrHeight, but is only _needed_ for nv22 and after when we have unchained randomness.
Apply the new check only if the source of randomness is unchained (effectively saying nv22 and after only).
- `PR type`: fix, feat, build, chore, ci, …
=> fix: beacon: validate drand change at nv16 correctly

cmd/lotus-miner/proving.go
Print the open time of the deadline.
The adjusted results are printed as follows.
```
./lotus-miner proving  deadlines 
Miner: t01000
deadline  open      partitions  sectors (faults)  proven partitions
0         17:00:22  1           2 (0)             0
1         17:30:22  0           0 (0)             0
2         18:00:22  0           0 (0)             0
3         18:30:22  0           0 (0)             0
4         19:00:22  0           0 (0)             0
5         19:30:22  0           0 (0)             0
6         20:00:22  0           0 (0)             0
7         20:30:22  0           0 (0)             0
8         21:00:22  0           0 (0)             0
9         21:30:22  0           0 (0)             0
10        22:00:22  0           0 (0)             0
11        22:30:22  0 …
```
=> opt(cli): ouput deadline open time

.circleci/config.yml, itests/direct_data_onboard_test.go, itests/direct_data_onboard_verified_test.go, itests/sector_terminate_test.go
A few things going on here:
1. Refactored the big DDO verified data test since it's doing so much and getting a bit out of hand; hopefully it's a little cleaner now with some logic extracted to functions
2. Moved that test to its own file, its size feels like it warrants it, and it's largely events focused rather than being about verified DDO tbqh
3. Adding additional testing of other FIP0083 events as I can manage it. Some are a bit difficult to trigger so I may not get all the pokemons.
=> test(actor events): expanded testing

chain/beacon/drand/drand.go, node/modules/dtypes/beacon.go
just inline docs, to help the next confused person
=> docs(drand): document the meaning of "IsChained"

node/impl/full/eth.go
When calling **eth_feeHistory**, it takes input a rewardPercentile array. Currently, there isn't any restriction on the length of the array, can result in high computation and potentially leading to OOM issues in RPC nodes. The fix is to set a hard limit of the array to 100. 
Changing the length of RewardPercentiles Array to upto 100.
=> fix: api: Length check the array sent to RPC.

CHANGELOG.md, documentation/en/default-lotus-config.toml, itests/kit/node_opts.go, node/builder_chain.go, node/config/cfgdocgen/gen.go, node/config/def.go, node/config/doc_gen.go, node/config/load.go, node/config/load_test.go, node/config/types.go, node/modules/actorevent.go
Closes: https://github.com/filecoin-project/lotus/issues/11679
The `Fevm.Events` config options don't make sense under `Fevm`, particularly now that they are for "actors" in general. @jennijuju and I thought that getting them moved to the new top-level `Events` in v1.26.0 is going to be the least painful option because the number of users who currently touch those options is restricted to a small number that are using the eth APIs. But now, with the new actor events APIs, the circle of users who may be touching these will increase. So best act now before we have more people with these config options set in the wrong place.
Although, I've implemented a **soft** deprecation here. Your old config will still continue to work but you'll get a stderr warning about it and how it will be removed …
=> feat(config): move Fevm.Events->Events, implement soft deprecation

node/builder_chain.go
We should enable the storage of Actor events even if 'EnableETHRPC' is set to false. Just tested this on a calibnet node and things look good now.
=> Enable event storage config for Actor events as well

.circleci/config.yml, .circleci/template.yml, itests/kit/ensemble_opts.go, itests/sector_pledge_test.go, storage/pipeline/commit_batch.go
Debugging issue reported in https://filecoinproject.slack.com/archives/CP50PPW2X/p1710213103743319
The `10-agg` test fails with
```
2024-03-12T10:10:07.393+0100	ERROR	sectors	pipeline/commit_batch.go:453	simulating CommitBatch message failed (868a820680820a80820580820380820480820980820280820780820b8082088080593754df7c23dfe5009578d1c9efcb98476e4ca2c0d337abc37a6e9b176fc22db7c20bf7857bb88b80d71a1e5dbb5af98e23041c0f9cf720b84ddb219890b9844d4629f17fca6db9513d58f15ee2e807365f0fe98e28a502b95d8e6d271a02b70ca5154b4732ec074d024c1079349e84f8872fdab397eed77572d55bde42f652f38c4681db5e340df5c3a4d4e2bfd0e21c550897697038f056e85784a9f4b61b819e8bf1fbc80b2bb03eef7418a81b9cfb19f6b4f8b2681c3a0497e86167144fc0b20de68b485ef425abc21f2665a7a2fcf50bf757687d8d74c41fadbfe07e956f6eff71f64067ae546c7733bdbfa060fbf4096a03c …
```
=> sealing pipeline: Fix failing ProveCommit3 aggregate

storage/pipeline/commit_batch.go, storage/pipeline/fsm.go, storage/pipeline/fsm_test.go, storage/pipeline/sector_state.go, storage/pipeline/states_sealing.go
* Deprecate old commit path which didn't use DDO-compatible methods
* Make commit batcher work in non-batch mode when configured like so
=> fix: commit batch: Always go through commit batcher

build/bootstrap/calibnet.pi
Remove the calibration bootstrappers which has been spun down.
=> chore: remove calibnet bootstrappers

storage/pipeline/fsm.go, storage/pipeline/input.go, storage/pipeline/types.go
Fixes https://github.com/filecoin-project/lotus/issues/11706
* Don't use padding pieces (which have no deal info) for calculating deal end epoch in WaitDeals
* Make the pieceinfo methods safer
* Catch panics in the sealing pipeline
=> sealing pipeline: Fix panic on padding pieces in WaitDeals

node/modules/actorevent.go
Picked up an RPC panic in testing. Now that `EventFilterManager` is received as an interface, setting it to `nil` isn't enough for the `== nil` checks inside `ActorEventHandler`.
=> fix(events): properly disable actor events API via cfg

.circleci/config.yml, .circleci/template.yml, itests/kit/ensemble_opts.go, itests/sector_pledge_test.go, node/builder_chain.go, storage/pipeline/commit_batch.go, storage/pipeline/fsm.go, storage/pipeline/fsm_test.go, storage/pipeline/input.go, storage/pipeline/sector_state.go, storage/pipeline/states_sealing.go, storage/pipeline/types.go
PR backports fixes encountered during testing of v1.26.0-rc2 to the `release/v1.26.0`.
Backports:
- https://github.com/filecoin-project/lotus/pull/11712
- https://github.com/filecoin-project/lotus/pull/11704
- https://github.com/filecoin-project/lotus/pull/11708
- https://github.com/filecoin-project/lotus/pull/11710
- https://github.com/filecoin-project/lotus/pull/11709
=> Chore: Backports to the `release/v1.26.0` branch

chain/stmgr/forks.go, chain/stmgr/stmgr.go
@rjan90 reported that a node he was running on butterflynet failed the migration after reimporting from a snapshot taken before the migration.
This is because his node had _cached_ the result of the migration, but didn't check whether it actually had the migrated result in its blockstore, and so hit not found errors.
Check whether we actually have the cached result before relying on it to short-circuit the migration. If we don't, delete the cached result and run the migration as normal.
- `area`, e.g. api, chain, state, market, mempool, multisig, networking, paych, proving, …
=> fix: stmgr: do not use cached migration results if absent from the blockstore

chain/events/filter/index.go
* #11594 
TL;DR: no net functionality change but a more conservative DDL execution for existing event index schema migrations.
This enhancement optimizes the schema migration process for the event index by preventing the redundant execution of Data Definition Language (DDL) statements that define the event schema. Traditionally, these DDL statements were grouped into a single slice, reflecting the most current version of the event index schema. With each migration, this slice was updated to the latest schema iteration, executing all statements in bulk. Initially, this method sufficed as migrations were focused on adding indices to existing table columns.
However, as the database schema evolves to meet new requirements, such as the forthcoming migrations that involve changes to table …
=> chore: events: Prevent DDL re-execution during event index schema migrations

gateway/proxy_fil.go
TIL about this limiting (from #11700), this seems appropriate to do for the new events calls.
=> fix(events,gateway): check that filter.FromHeight isn't too far back for gateway calls

CHANGELOG.md, api/api_full.go, api/api_gateway.go, api/mocks/mock_full.go, api/proxy_gen.go, build/openrpc/full.json, build/openrpc/gateway.json, documentation/en/api-v1-unstable-methods.md, gateway/node.go, gateway/proxy_fil.go, itests/direct_data_onboard_test.go, itests/direct_data_onboard_verified_test.go, itests/sector_terminate_test.go, node/impl/full/actor_events.go, node/impl/full/actor_events_test.go, node/impl/full/dummy.go
This is done with the intention to add new {Get,Subscribe}ActorEvents in a future release (i.e. soon!) with both decoded values (dag-json represented) and simplified (no flags or codec). But because this comes with some trade-offs wrt fidelity of information (e.g. likely needing to drop events with badly encoded values, and not retaining original codec), we need to also have a Raw form of these APIs for consumers that want to take on the burden of consuming them as they are.
The changes being proposed in https://github.com/filecoin-project/lotus/pull/11707 roughly outline the functionality of the new methods, but further work needs to be done on the return types and argument types. Rather than attempt to rush that for a v1.26.0 release, **I'm proposing that we make this rename change for …
=> feat(events): add "Raw" suffix to {Get,Subscribe}ActorEvents

curiosrc/web/hapi/simpleinfo.go, curiosrc/web/hapi/watch_actor.go, curiosrc/web/hapi/web/actor_summary.gohtml, curiosrc/web/hapi/web/cluster_machines.gohtml, curiosrc/web/static/index.html, lib/harmony/harmonydb/sql/20240317-tasksummary-index.sql, lib/harmony/harmonydb/sql/20240317-web-summary-index.sql
3 incremental improvements to Curio webui, implemented because I had a hard time seeing the high-level state of my setup
* Add a task summary of tasks executed in past 24h to machine summary
* Really useful to see how machines are performing, gives a nice view of anomalies
* Add really basic wallet infos to actor info
* Add recent win stats to actor info
=> curio web: Task summaries in Cluster machines category

node/impl/full/eth_events.go
Codec != Raw likely means built-in actor events, which we can safely skip, so avoid filling up logs with warnings for every built-in actor event that comes past this point.
Fixes: https://github.com/filecoin-project/lotus/issues/11718
Don't log anything at all. I originally proposed downgrading to a debug bit I don't think there's much point once we're here because it'll be so common and not unexpected.
=> fix(events): don't log.Warn for EVM events with non-Raw codec

go.mod, go.sum
Backports #11732 , updating to go-state-types 0.13.0-rc3
=> chore: deps: update GST to v0.13.0-rc3 (#11732)

node/impl/full/eth_events.go
fixes #11117
In the Eth JSON-RPC API, skip events where we don't have the associated message. This can happen if, e.g., we run a splitstore garbage collection. We _could_ have tried to lookup the message in the message index (as suggested by the submitter), but I'm concerned we'll end up with inconsistent information in that case.
TL;DR: Avoid returning incorrect information.
The full fix is to prune the indices when pruning the splitstore: https://github.com/filecoin-project/lotus/issues/11681
- `area`, e.g. api, chain, state, market, mempool, multisig, networking, paych, …
=> fix: api: skip evm events where we no longer have the associated txn

chain/types/ethtypes/eth_types.go, itests/eth_block_hash_test.go, node/impl/full/eth_utils.go
fixes #11721
The gas limit is proportional to the number of blocks.
=> fix: api: return the correct block gas limit in the EthAPI

.github/actions/install-go/action.yml, .github/actions/install-ubuntu-deps/action.yml, .github/workflows/check.yml
https://github.com/filecoin-project/lotus/issues/11734
This PR creates a new GitHub Actions workflow (`check.yml`) that performs the following jobs previously handled exclusively by CircleCI:
- docs-check
- gen-check
- gofmt
- lint-all
- mod-tidy-check
You can find an example run of the workflow at: https://github.com/filecoin-project/lotus/actions/runs/8362592926
Unlike the CircleCI check jobs, the ones from the newly added workflow do not have to wait for the build (`make lotus deps`) to finish. Instead, the check jobs call `make lotus` and `make deps` as needed. This results in some work duplication but reduces the overall workflow runtime by ~3 minutes.
We did not use a configuration matrix in the newly added workflow because, in our opinion, separate jobs provide better clarity here. …
=> ci: ci: create gh workflow that runs go checks

curiosrc/ffi/sdr_funcs.go, itests/sector_import_simple_test.go, storage/paths/local.go, storage/sealer/storiface/filetype.go
For now on top of https://github.com/filecoin-project/lotus/pull/11664, will rebase to master once that has landed.
This PR fixes an edge-case in Curio finalize where somehow first try may not fully execute all steps, and on retry we'd already see some data moved. Observed on my SP setup, also confirmed the fix works.
=> fix: curio seal: Fix partial Finalize retry

.github/workflows/test.yml
This PR addresses the following review comment:
- https://github.com/filecoin-project/lotus/pull/11762#discussion_r1534500209
- https://github.com/filecoin-project/lotus/pull/11762#issuecomment-2013416368
It makes sure we use cached outputs of `make deps` and that the parameters cache is versioned based on the `parameters.json` file.
=> ci: fetch all filecoin-ffi dependencies

curiosrc/web/hapi/routes.go, curiosrc/web/hapi/simpleinfo.go, curiosrc/web/hapi/web/cluster_machines.gohtml, curiosrc/web/hapi/web/cluster_tasks.gohtml, curiosrc/web/hapi/web/node_info.gohtml, curiosrc/web/hapi/web/root.gohtml, curiosrc/web/srv.go, curiosrc/web/static/index.html, curiosrc/web/static/main.css, curiosrc/web/static/pipeline_porep.html, lib/harmony/harmonytask/harmonytask.go
This PR adds a "Node Info" page to the webui, adding a feature which never existed in lotus - per node storage stats view!
=> curio web: node info page

.github/actions/install-go/action.yml, .github/actions/install-ubuntu-deps/action.yml, .github/actions/start-yugabytedb/action.yml, .github/workflows/test.yml
https://github.com/filecoin-project/lotus/issues/11734
This PR creates a new GitHub Actions workflow (`check.yml`) that performs the following jobs previously handled exclusively by CircleCI:
- test
- test-conformance
- test-itest-*
- test-unit-*
You can find an example run of the workflow at: https://github.com/filecoin-project/lotus/actions/runs/8376141826?pr=11762
Unlike the CircleCI test jobs, the ones from the newly added workflow do not have to wait for the build (`make lotus deps`) to finish. Instead, the test jobs call `make deps` as needed (we didn't find an instance where `make lotus` was needed). This results in some work duplication but reduces the overall workflow runtime by ~3 minutes.
We did use a configuration matrix in the newly added workflow because the number of jobs …
=> ci: ci: create gh workflow that runs go tests

curiosrc/ffi/sdr_funcs.go, curiosrc/ffi/task_storage.go, curiosrc/seal/task_trees.go, itests/path_type_filters_test.go, storage/paths/interface.go, storage/paths/local.go, storage/paths/mocks/store.go, storage/paths/remote.go, storage/sealer/storiface/filetype.go, storage/sealer/storiface/paths.go
On top of https://github.com/filecoin-project/lotus/pull/11730 because that PR has related fixes needed for this PR to work.
This PR fixes failing test-itest-path_type_filters on master
TODO:
=> feat: curio: Storage reservations when fetching

curiosrc/seal/task_submit_precommit.go
Mark sectors with expired tickets as failed. The (not yet written) code in the poller will figure out what to do next with the sector (which will probably be "remove it") - which is much better than getting it into an infinite retry loop which will forever  fail to send the message with the following error:
```
2024-03-25T12:16:07.330+0100	ERROR	harmonytask	harmonytask/task_type_handler.go:178	Do() returned error	{"type": "PreCommitSubmit", "id": "934107", "error": "sending message: GasEstimateMessageGas error: message execution failed: exit 16, reason: message failed with backtrace:\n00: f02620 (method 28) -- seal challenge epoch 3748434 too old, must be after 3764852 (16)\n (RetCode=16)", "errorVerbose": "sending message:\n    github.com/filecoin-project/lotus/curiosrc/seal.(*SubmitPreco …
```
=> fix: curio seal: Check ticket age before sending PreCommit message

lib/harmony/harmonydb/sql/20231217-sdr-pipeline.sql, lib/harmony/harmonydb/sql/20240402-sdr-pipeline-ddo-deal-info.sql
Initial part of ddo support needed for https://github.com/filecoin-project/lotus/issues/11754
This just modifies the sealing pipeline sql schema so that a future migration won't be needed when full DDO support is added.
=> feat: curio: Add schemas for DDO deal support

curiosrc/builder.go, documentation/en/default-curio-config.toml, node/config/def.go, node/config/doc_gen.go, node/config/types.go
This PR removes some fields from Curio Proving config section that were only relevant to lotus-miner
=> chore: curio: Cleanup proving config

.github/actions/install-system-dependencies/action.yml
https://github.com/filecoin-project/lotus/issues/11734#issuecomment-2033165180
I propose to list processes before calling apt-get to enable debugging the issue raised in https://github.com/filecoin-project/lotus/issues/11734#issuecomment-2033165180.
=> ci: ci: list processes before calling apt-get to enable debugging

curiosrc/ffi/sdr_funcs.go
=> feat: curio: enable 8MiB sectors on Curio

cmd/curio/storage.go, curiosrc/ffi/piece_funcs.go, curiosrc/ffi/sdr_funcs.go, curiosrc/piece/task_park_piece.go, curiosrc/seal/task_movestorage.go, curiosrc/seal/task_trees.go, storage/paths/interface.go, storage/paths/local.go, storage/paths/mocks/store.go, storage/paths/remote.go
* Plumb storage reservation logic into MoveStorage
* Add Storage to the MoveStorage task
Todo:
=> feat: curio: Storage reservations in MoveStorage

itests/eth_block_hash_test.go, itests/kit/blockminer.go
Increase the chances of having multiple blocks at the same height by aligning block times across test miners. Also, make the block hash test faster.
=> test: eth: deflake EthBlockHashesCorrect_MultiBlockTipset

curiosrc/ffi/sdr_funcs.go, curiosrc/proof/treed_build.go, storage/sealer/proofpaths/cachefiles.go
The tree tasks should cleanup after failed execution. This is especially useful when the error was caused by running out of disk space for whatever reason (which shouldn't ever happen, at least if the storage reservation mechanism wasn't buggy (fixed in another PR))
=> feat: curio: Cleanup files after failed TreeDRC

curiosrc/seal/task_trees.go, storage/paths/local.go
Previously `Reserve` would instruct `stat` to include any sector files already on disk to lower what it consider as reserved, which in turn would lower Available storage less - The issue is that the new reservation isn't reflected in p.reserved at the time when stat is called, which means that usually we'd hit the `if stat.Reserved < 0 {.. stat.Reserved = 0` condition, making the accounting inaccurate.
This PR makes stat just return how much data is on-disk for the new reservation, and shifts the accounting to the Reserve function.
- `area`, e.g. api, chain, state, market, …
=> fix: paths/local: Fix on-disk storage accounting in new reservations

storage/pipeline/piece/piece_info.go, storage/pipeline/precommit_policy_test.go
Fixes https://github.com/filecoin-project/lotus/issues/11821
Slack discussion: https://filecoinproject.slack.com/archives/CPFTWMY7N/p1711693422625719
=> fix: piece: Don't return StartEport in PieceDealInfo.EndEpoch

chain/events/filter/index.go, itests/direct_data_onboard_test.go, itests/direct_data_onboard_verified_test.go, itests/sector_terminate_test.go
Fixes: https://github.com/filecoin-project/lotus/issues/11823
Replaces: https://github.com/filecoin-project/lotus/pull/11829
I went down the `rowid` rabbit hole that @Stebalien mentioned in #11823, in https://www.sqlite.org/lang_createtable.html#rowid:
> The rowid value can be accessed using one of the special case-independent names "rowid", "oid", or "_rowid_" in place of a column name.
So, it's there already, let's use it! This requires no migration, and just sorts on the way out. The example message I had in #11823 now looks like this from `GetActorEventsRaw`:
```json
"entries": [
{
"Flags": 3,
"Key": "$type",
"Codec": 81,
"Value": "bnNlY3Rvci11cGRhdGVk"
},
{
"Flags": 3,
"Key": "sector",
"Codec": 81,
"Value": "GScT"
},
{
"Flags": 3,
"Key": "unsealed-cid",
"Codec": 81,
"Value": …
```
=> fix(events): order entries by insertion order when selecting

chain/stmgr/forks_test.go
Fixes #11824 
The `TestForkPreMigration`-test would hang indefinitely if the LOTUS_DISABLE_PRE_MIGRATIONS=1 environment variable was set. 
Temporarily unsets the LOTUS_DISABLE_PRE_MIGRATIONS environment variable before running the test, and restore it afterward.
=> fix: test: TestForkPreMigration hanging when env-var is set

lib/harmony/harmonytask/task_type_handler.go
Before this fix if considerWork was called with a bunch of tasks, and the one selected first by CanAccept was consistently failing to claim storage, we'd get stuck never trying to claim other tasks. Combined with the bug in storage reservations (https://github.com/filecoin-project/lotus/pull/11825) this could lead to pile-ups which would make everything clog up, and no tasks would get executed.
=> fix: harmony: Try other tasks when storage claim fails

cli/spcli/sectors.go, cmd/lotus-miner/sectors.go
Fixes https://github.com/filecoin-project/lotus/issues/11833
* Be DDO-aware in `lotus-miner sectors list`
* Also add DDO-related output to `lotus-miner sectors status`
=> fix: lmcli: make 'sectors list' DDO-aware

.github/workflows/build.yml, .github/workflows/check.yml, .github/workflows/docker.yml, .github/workflows/release.yml, .github/workflows/test.yml
https://github.com/filecoin-project/lotus/issues/11734#issuecomment-2034816466
This PR proposes that we cancel in progress runs on GitHub Actions workflows only when they are scheduled on PRs. In particular, they should not be cancelled on pushes to the master branch.
=> ci: ci: cancel in progress runs on pull requests only

storage/pipeline/states_replica_update.go, storage/pipeline/states_sealing.go
This is https://github.com/filecoin-project/lotus/pull/11813 except with a network version check, and only applied to snapdeals
=> fix: sealing: Use PRU3 After Nv22

cli/filplus.go
https://github.com/filecoin-project/lotus/issues/11810
=> fix: cli: Datacap should only be checked if user agrees to spend it

build/params_mainnet.go
This is a bit too late for 1.26.0 and 1.26.1 but it at least gives mitigation if there was some reason to use this env var to disable proper nv22 upgrade.
=> fix(build): disable phoenix drand upgrade if LOTUS_DISABLE_DRAGON

itests/eth_block_hash_test.go
I shrunk this down to 10 when I last deflaked this test, but I was too optimistic. I'm bringing this back up to 50.
See https://gist.github.com/Stebalien/701039637361b3b9cb328d7c2d61beda
Fixes failure found in https://github.com/filecoin-project/lotus/pull/11858
=> test: eth: wait longer for chain to settle in block hash test

itests/eth_filter_test.go, node/impl/full/eth_events.go
Closes #11807 
Subsumes #https://github.com/filecoin-project/lotus/pull/11816
Eth subscribe tipsets API should only return tipsets that have been executed.
We do this by only returning the parent tipset of the latest tipset received by ETH Subscribe from it's TipSetFilter subscription.
=> fix : ETH RPC API: eth subscribe tipsets API should only return tipsets that have been executed

node/modules/actorevent.go
From @TippyFlitsUK, likely a result of running something off `master` and then "upgrading" to 1.26.2 which doesn't have version 3. We'll just make this more informative.
```
024-04-09T00:20:38.736Z	INFO	messagepool	messagepool/messagepool.go:446	mpool ready
ERROR: initializing node: starting node: could not build arguments for function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:28): failed to build full.EthEventAPI: could not build arguments for function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:28): failed to build *filter.EventFilterManager: received non-nil error from function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:28): invalid database version: got 3, expected 2
```
=> fix(events): properly decorate events db errors

cli/disputer.go
Avoid disputing WindowedPoSt messages when the target Miner has no balance to pay rewards
fixes #11715
In https://github.com/filecoin-project/lotus/issues/11703, a user came across an edge case where an SP:
1. Submitted a bad PoSt.
2. Terminated their sectors.
3. Withdrew all funds (after paying all fees).
This left the SP's miner actor with a bad proof but without any funds to pay for disputes. On the other hand, given that the sectors have been terminated and termination fees were already paid we don't really care about fining the SP for the bad proofs anyways.
But... we still don't want to submit dispute messages in this case because doing so isn't free and doesn't really serve a purpose.
So add a check to fetch miner wallet balance and only send disputing messages if balance is non …
=> refactor: cli: Avoid disputing WindowedPoSt messages when the target miner has no balance to pay rewards

cmd/sptool/sector.go, documentation/en/cli-sptool.md
https://github.com/filecoin-project/lotus/pull/11788/commits/280c9ac75ef09a978e7cde0b02e5fce1411de914 moved terminate from lotus-shed to the spcli package, but didn't add it to sptool
=> fix: spcli: add reference to the terminate command

curiosrc/web/hapi/robust_rpc.go, curiosrc/web/hapi/routes.go, curiosrc/web/hapi/simpleinfo.go, curiosrc/web/hapi/simpleinfo_pipeline_porep.go, curiosrc/web/hapi/web/pipeline_porep_sectors.gohtml, curiosrc/web/static/main.css, curiosrc/web/static/pipeline_porep.html, storage/paths/db_index.go
This PR adds an individual sector info page
Screenshot:
=> feat: curioweb: Sector info page

curiosrc/ffi/piece_funcs.go, curiosrc/ffi/sdr_funcs.go, storage/paths/local.go
This PR makes it so that after each porep pipeline step tasks will ensure that only the latest version of sector files remain in storage. This should make future retry logic much easier to implement - e.g. retrying SDR will now just be setting after_sdr/after_tree.. fields for a given sector to false.
=> feat: curio: Cleanup data copies after seal ops

curiosrc/market/lmrpc/lmrpc.go, documentation/en/default-curio-config.toml, node/config/def.go, node/config/doc_gen.go, node/config/types.go
Part of curio beta work - https://github.com/filecoin-project/lotus/issues/11754
=> feat: curio/lmrpc: Ingest backpressure

cli/filplus.go, documentation/en/cli-lotus.md
`lotus list-claims` can output in json format, however the `--json` flag is missing.
=> fix: cli: json flag

cmd/curio/run.go, curiosrc/market/lmrpc/lmrpc.go
This PR makes the boost adapters start correctly.
`rpc.ListenAndServe` is blocking and make the boost adapter code unreachable.
=> fix: curio: Start BoostAdapters before blocking rpc serve

curiosrc/seal/task_submit_precommit.go
Add a missing expired-deal-start-epoch check to the SubmitPrecommit task. Marks the sector as failed, which will later get it GCed from storage.
=> fix: curio: Check deal start epoch passed in PrecommitSubmit

curiosrc/ffi/sdr_funcs.go, curiosrc/ffi/task_storage.go, storage/paths/local.go
More debugging of accounting issues in the storage reservation mechanism in Curio.
* This PR adds a lot more debug logging to storage reservation code
* Fixes a bug in curio task storage where in some cases we'd release storage multiple times
* Fixed with sync.once as other ways of fixing it would be either very complicated or would trade robustness in favour of sometimes maybe not releasing storage
* Also a small drive-by fix which drops existing SDR layers on sdr restart - seems like this was one of the causes of corrupted sectors
Currently testing on my mainnet setup, seems to work very well so far
- `PR type`: fix, feat, build, chore, ci, docs, perf, …
=> fix: local storage reservations fixes

lib/harmony/harmonytask/harmonytask.go, storage/paths/db_index.go
`null` check against a varchar column can result in false negatives. 
```
yugabyte=# SELECT * FROM curio.storage_path WHERE available >= 118279372 and NOW()-(50000000000 * INTERVAL '1 second') < last_heartbeat and heartbeat_err is null and ((true and can_seal = TRUE) or (false and can_store = TRUE)) order by (available::numeric * weight) desc;
storage_id | urls | weight | max_storage | can_seal | can_store | groups | allow_to | allow_types | deny_types | capacity | available | fs_available | reserved | used | last_heartbeat | heartbeat_err | allow_miners | deny_miners 
------------+------+--------+-------------+----------+-----------+--------+----------+-------------+------------+----------+-----------+--------------+----------+------+----------------+---------------+--------------+------- …
```
=> fix: curio: fix incorrect null check for varchar column

itests/harmonytask_test.go, lib/harmony/harmonytask/harmonytask.go, lib/harmony/harmonytask/task_type_handler.go
A helper for correct handling of different syncs for potential new harmony tasks. This will allow tasks to be created on demand of available resources so that both batching and non-batching processes can consume from the same inflow. 
Pipelines' first steps can implement TaskDefinition.IAmBored to scrounge up more work when they have the capacity to work it. 
Mid-pipeline stages can look at later failed stages for advanced recovery.
=> harmonytask feature: find clean-up work when underutilized. 

cmd/curio/tasks/tasks.go, curiosrc/gc/storage_endpoint_gc.go, lib/harmony/harmonydb/sql/20240416-harmony_singleton_task.sql, lib/harmony/harmonydb/sql/20240416-sector_index_gc.sql, lib/harmony/harmonydb/sql/20240417-sector_index_gc.sql, lib/harmony/harmonydb/userfuncs.go, lib/harmony/harmonytask/singleton_task.go, lib/passcall/every.go, storage/paths/remote.go
* Add a harmonytask helper for defining "singleton" tasks - tasks which run as at most one instance across the whole cluster
* This construction also helps with scheduled tasks which only run every so often without requiring a separate table for each task - which will be handy for other periodic cleanup tasks.
* Implement a storage path endpoint cleanup task
* This task scans the sector index pinging all endpoints, and removes the ones which appear to be dead for a long time
* (lotus-miner never had that, but because the index there was in-memory, cleanup was done by restarting the process..)
* Curio needs this because the index is now in the database, and after migrating from lotus-miner there are guaranteed to be stale endpoints in the sector DBIndex. The remote storage code can cope …
=> feat: curio: storage index gc task

documentation/en/cli-curio.md
Master is currently broken because of a skipped `make docsgen-cli` in a recent commit.
=> fix: master CI: make docsgen-cli

curiosrc/gc/storage_endpoint_gc.go, go.mod, go.sum, lib/harmony/harmonydb/harmonydb.go, lib/harmony/harmonydb/userfuncs.go
This enables load balancing and failover in a Yugabyte-standard way. 
Use yugabyte's pgx/v5 instead of the default pgx.
Note: Get() was removed as it is duplicates functionality available with less code. 
=> feat: curio: Use Yugabyte's PGX driver

storage/pipeline/commit_batch.go, storage/pipeline/mocks/mock_commit_batcher.go
Fixes https://github.com/filecoin-project/lotus/issues/11837
=> fix: sealing: add allocation check before sending commit message

.github/workflows/sorted-pr-checks.yml
https://github.com/filecoin-project/lotus/issues/11734
I propose to introduce a workflow that is going to post a nicely formatted list of completed checks on a PR once all the GitHub Actions workflow runs finish for the PR in question. 
The issue with GitHub PR Checks was originally reported here - https://filecoinproject.slack.com/archives/CP50PPW2X/p1711707107172389
Unfortunately, it is unlikely to be resolved by GitHub any time soon - https://github.com/orgs/community/discussions/7885
We developed an alternative solution to the problem that relies on posting a sticky comment to a PR which a sorted/grouped list of checks after all the GitHub Actions workflows are finished - https://github.com/ipdxco/sorted-pr-checks
Please note that the comment only includes information about GitHub …
=> ci: ci: create gh workflow that updates sorted pr checks

curiosrc/market/lmrpc/lmrpc.go, lib/harmony/harmonytask/singleton_task.go, storage/paths/db_index.go
* Undo the change from https://github.com/filecoin-project/lotus/pull/11881
* `heartbeat_err` is a nullable varchar, and afaict it's completely ignored in the db_index (it's not ever set anywhere); The string based check was definitely broken for me
* Also update pgx imports to the yugabyte one so that ErrNoRows checks work correctly
=> fix: curio: Update pgx imports, fix db_storage alloc

chain/consensus/common.go, chain/state/statetree.go, chain/stmgr/actors.go, chain/stmgr/rpc/rpcstatemanager.go, chain/stmgr/searchwait.go, chain/stmgr/stmgr.go, chain/store/messages.go, chain/vm/runtime.go, chain/vm/vm.go, itests/migration_test.go, node/impl/full/eth_utils.go, node/impl/full/state.go
* #11594 
The naming of `LookupID` can cause confusion when resolving actor IDs vs
ID addresses. To avoid this:
* Refactor `StateTree` `LookupID` to `LookupIDAddress`, because it returns ID address.
* Refactor `StateManager` `LookupID` to `LookupIDAddress` because it also returns ID address via a chain call to `StateTree`.
* Introduce a new API `StateManager` dedicated to resolving address to actor ID, called `LookupID` which returns `abi.ActorID`.
For context, see:
* https://github.com/filecoin-project/lotus/pull/11723#discussion_r1534728607
- `area`, e.g. api, chain, state, …
=> Refactor `LookupID*` APIs in `StateManager` and `StateTree`

cmd/lotus-shed/invariants.go
Adds v13 support to invariants-checker
=> fix: lotus-shed: Add v13 support to invariant-checker

documentation/misc/Building_a_network_skeleton.md
Adding a tutorial for how to create a network upgrade skeleton.
=> chore: docs: nv-skeleton documentation

api/api_curio.go, api/proxy_gen.go, api/v0api/proxy_gen.go, build/openrpc/full.json, build/openrpc/gateway.json, build/openrpc/miner.json, build/openrpc/worker.json, cmd/curio/rpc/rpc.go, cmd/curio/storage.go, documentation/en/api-v0-methods-curio.md
Add a `StorageInit` method to CurioAPI to support attach storage on remote nodes.
In previous versions, if we initialize storage on a remote node, it would not work properly due to the fact that checking and creating the sectorstore.json file are local operations.
Now we can use `curio cli storage attach --init --seal /path` to select a remote node and attach it.
=> feat: add StorageInit api

cli/filplus.go
I have no idea why this change happened, but from a user usage perspective it must have been wrong, so I changed it back to the way it was.
`tablewriter.Col` -> `tablewriter.NewLineCol` ❌
=> fix: cli: Replace tablewriter.NewLineCol with tablewriter.Col in ListAllocations and ListClaimsCmd

chain/events/filter/event.go
We use `currentHeight` to figure out where we are to know whether we need to backfill a filter or not. Unfortunately, we collect this from `Apply()` so if you install a filter _prior_ to processing a message, we can't know where we are and what we should do about it.
The current behaviour is that it will fail the `minHeight < currentHeight` test further down in this file, not perform a pre-fill, and we end up with an empty filter (initially). So any calls to `GetActorEventsRaw` or `SubscribeActorEventsRaw` wanting backfill will not get any of it and will return a `null` to the user. But, this behaviour is the same as "there are no events in this range", so the user has no way of differentiating between "node is starting" and "no events".
This new behaviour will send an error in response …
=> fix(events): check for sync-in-progress

chain/events/filter/index.go
Introduces a v4 migration that just adjusts indexes.
Copies some improvements from https://github.com/filecoin-project/lotus/pull/11723
Closes: https://github.com/filecoin-project/lotus/issues/11909
/cc @i-norden
=> feat(events): adjust indexes in event index db to match query patterns

chain/events/filter/index.go
Very embarrassing, second fix to my original v4 PR.
Found while debugging https://github.com/filecoin-project/lotus/pull/11723. `master` should work fine but it'll repeat the v4 migration on startup which will be a noop, so shouldn't be fatal. But When https://github.com/filecoin-project/lotus/pull/11723 is applied, it always tries to do v4 and then v5, and v5 isn't a noop when run again, so it fails.
=> fix(events): register events index db migration v4

CHANGELOG.md, build/openrpc/full.json, build/openrpc/gateway.json, build/openrpc/miner.json, build/openrpc/worker.json, build/version.go, documentation/en/cli-curio.md, documentation/en/cli-lotus-miner.md, documentation/en/cli-lotus-worker.md, documentation/en/cli-lotus.md, documentation/en/cli-sptool.md
- Update the build version, and clean up the changelog, highlighting features, etc.
=> build: release: v1.27.0-rc1

curiosrc/web/hapi/simpleinfo.go, curiosrc/web/hapi/web/sector_info.gohtml, lib/harmony/harmonydb/sql/20240501-harmony-indexes.sql
Needed to debug some issues on my cluster
=> feat: curioweb: Show piece info on the sector page

.github/workflows/test.yml
https://github.com/filecoin-project/lotus/pull/11897
Use `filecoin-ffi` head commit hash as a cache key for `make deps` outputs cache.
Previously, we were only taking into account `install-filcrypto` script and `rustc-target-features-optimized.json`, but we also have to account for changes in the `rust` directory. At this point, it's easier to use the hash of the entire repo into consideration.
=> fix: ci: use filecoin-ffi hash to cache make deps outputs

documentation/misc/Building_a_network_skeleton.md
Updating the skeleton guide so its easier to follow, adding a couple of missing steps. Also trying to make it easier for maintainers to review in steps where there is a lot of automatically generate code.
=> chore: docs: Update skeleton guide

go.mod, go.sum
=> chore: deps: Bump libp2p

cmd/curio/guidedsetup/guidedsetup.go, cmd/curio/guidedsetup/shared.go, cmd/curio/migrate.go, cmd/curio/pipeline.go, curiosrc/market/deal_ingest.go, curiosrc/seal/task_submit_commit.go, lib/harmony/harmonydb/sql/20231217-sdr-pipeline.sql, lib/harmony/harmonydb/sql/20240425-sector_meta.sql
* Add 2 new tables for sector metadata to the DB
* Add migration logic for those invoked in guided-setup and optionally as a curio cli command
* Add logic which populates the table from seal pipeline at the end of the commit-msg task.
TODO: 
=> feat: curio: Keep more sector metadata in the DB long-term

curiosrc/market/lmrpc/lmrpc.go
=> fix: curio/lmrpc: Check ParkPiece success before creating sectors

Dockerfile.curio, cmd/curio/deps/deps.go, cmd/curio/guidedsetup/guidedsetup.go, cmd/curio/internal/translations/catalog.go, cmd/curio/internal/translations/locales/en/out.gotext.json, cmd/curio/internal/translations/locales/ko/messages.gotext.json, cmd/curio/internal/translations/locales/zh/messages.gotext.json, cmd/curio/tasks/tasks.go, curiosrc/alertmanager/alerts.go, curiosrc/alertmanager/task_alert.go, documentation/en/default-curio-config.toml, node/config/def.go, node/config/doc_gen.go, node/config/types.go
This PRs adds a new singleton task for alerting.
The alerting task can create an incident for a previously configured service.
User should get critical alerts via SMS, email and call. 
A new page about alerting is required in Curio docs. We also need to create a section on how to sign up and configure PagerDuty.
=> feat: curio: alertManager

chain/types/ethtypes/eth_1559_transactions.go, chain/types/ethtypes/eth_legacy_155_transactions.go, chain/types/ethtypes/eth_legacy_155_transactions_test.go, chain/types/ethtypes/eth_legacy_homestead_transactions.go, chain/types/ethtypes/eth_legacy_homestead_transactions_test.go, chain/types/ethtypes/eth_transactions.go, itests/eth_legacy_transactions_test.go, itests/kit/evm.go, node/impl/full/eth.go, node/impl/full/eth_utils.go
For https://github.com/filecoin-project/lotus/issues/11859 (for the EIP-155 transactions support)
FIP at https://github.com/filecoin-project/FIPs/pull/995
This PR enables support for EIP-155 transactions with chain replay protection in Filecoin.
=> feat: ETH compatibility in Filecoin : Support EIP-155 Ethereum transactions in Filecoin

build/params_2k.go, build/params_butterfly.go, build/params_calibnet.go, build/params_interop.go, build/params_mainnet.go, build/params_testground.go
It was noted by [Hubert](https://filecoinproject.slack.com/archives/CP50PPW2X/p1715340266433729) that `Filecoin.StateGetNetworkParams` returns the wrong `SupportedProofTypes`:
Example:
```
curl -X POST 'http://127.0.0.1:1234/rpc/v0' \
>     -H 'Content-Type: application/json' \
>     --data '{"jsonrpc":"2.0","id":1,"method":"Filecoin.StateGetNetworkParams","params":[]}'
{"jsonrpc":"2.0","result":{"NetworkName":"mainnet","BlockDelaySecs":30,"ConsensusMinerMinPower":"10995116277760","SupportedProofTypes":[3,4],"PreCommitChallengeDelay":150,"
------
UpgradeWatermelonHeight":3469380,"UpgradeDragonHeight":3855360,"UpgradePhoenixHeight":3855480},"Eip155ChainID":314},"id":1}
```
Update the `SupportedProofsTypes` in `build/params_*` to the correct set of ProofTypes supported in the different …
=> fix: params: Update SupportedProofTypes to the correct ones

.circleci/config.yml, chain/stmgr/supply.go, itests/supply_test.go
Closes #11921 
Drop builtin market calculation from locked balance calculation after nv23
=> feat:state:Ignore market balance after nv23

build/params_2k.go, build/params_butterfly.go, build/params_calibnet.go, build/params_interop.go, build/params_mainnet.go, build/params_testground.go
#11988 was introduces earlier today, to update `SupportedProofTypes` in `Filecoin.StateGetNetworkParams` to return the correct ProofsTypes.
But this [change caused panics in tooling](https://filecoinproject.slack.com/archives/CP50PPW2X/p1715622977236679) used for spinning up devnets, and its not clear to me how to fix those, and if there are other connections in the above changes to the Lotus-Miner. For now it seems best to revert this PR, until we have a clearer view of how these pieces are connected.
Revert #11988. 
- `area`, e.g. api, chain, state, market, mempool, multisig, …
=> chore: revert "Update SupportedProofTypes (#11988)"

.github/workflows/sorted-pr-checks.yml
https://github.com/filecoin-project/lotus/pull/323#issuecomment-2068979790
Do not comment when the workflow_run that triggered the sorted PR checks workflow was itself triggered by events other than the pull request event.
The check for `github.event.workflow_run.pull_requests[0]` is not sufficient because there are PRs with lotus:master as head (e.g. https://github.com/DIGIIX-Ltd/lotus/pull/323).
I disabled the workflow until this is merged.
=> ci: ci: fix when sorted pr checks workflow is executed

chain/actors/builtin/miner/state.go.template, chain/actors/builtin/miner/v12.go, chain/actors/builtin/miner/v13.go, chain/actors/builtin/miner/v14.go
Fixes: https://github.com/filecoin-project/lotus/issues/11962
~~not sure if v12 is worth updating here, included just in case—is it worth it?~~ whoops, codegen, I've done it for all possible, which is v12 and v13.
=> fix: copy Flags field from SectorOnChainInfo

curiosrc/piece/task_cleanup_piece.go, curiosrc/piece/task_park_piece.go, curiosrc/seal/task_finalize.go, curiosrc/seal/task_movestorage.go, curiosrc/seal/task_porep.go, curiosrc/seal/task_sdr.go, curiosrc/seal/task_submit_commit.go, curiosrc/seal/task_submit_precommit.go, curiosrc/seal/task_treed.go, curiosrc/seal/task_treerc.go, lib/harmony/harmonydb/sql/20231217-sdr-pipeline.sql, lib/harmony/harmonydb/sql/20240228-piece-park.sql, lib/harmony/harmonydb/sql/20240507-sdr-pipeline-fk-drop.sql
Much simpler approach to https://github.com/filecoin-project/lotus/pull/11959
Not handled in poller yet, tho any handling strategy will likely be "just wait for user action" initially until we develop smarter repair logic.
=> fix: curio: Drop FKs from pipeline to fix retry loops

curiosrc/ffi/task_storage.go, lib/harmony/harmonytask/task_type_handler.go, lib/harmony/resources/resources.go
Appears to be a regression after https://github.com/filecoin-project/lotus/pull/11973
=> fix: curio taskstorage: Don't try to free reservations by nulled TaskID

.github/actions/start-yugabytedb/action.yml, lib/harmony/harmonydb/sql/20240522-ts-to-timestampz.sql
It appears that pgx doesn't pay attention to time.Time timezone field, and fails to convert the time value to whatever Timezone the backing postgres (yb) is configured to run; At the same time our schema uses the `timestamp [without time zone]` type all over the place, and that type accounts for time is units of seconds starting at postgres epoch as defined in the databases local timezone.
To make postgres store time in terms of seconds since postgres epoch in UTC we need to switch to `timestampz` (iiuc same type as `TIMESTAMP WITH TIME ZONE`), or alternatively do `SET TIME ZONE 'UTC'` on all connections - tho that option is much less robust imo (falls apart when external application connects to the database which will then think that it is in a different TZ).
Before you mark the PR ready …
=> fix: harmonydb: Use timestampz instead of timestamp across the schema

node/hello/hello.go
We should already be connected to this peer and we're only fetching this tipset opportunistically. If we've already disconnected from them, move on.
=> fix: hello: avoid dialing when fetching hello tipset

go.mod, go.sum
This PR updates go-jsonrpc to v0.4.0: https://github.com/filecoin-project/go-jsonrpc/releases/tag/v0.4.0
=> chore: update go-jsonrpc to v0.4.0

build/builtin_actors.go, build/builtin_actors_gen_test.go, go.mod, go.sum
Without this change the following test fails:
`CGO_ENABLED=0 go test -count=1 ./chain/types_test.go`
Without this fix importing the chain types into a fully-static executable is not possible.
I am not adding a test, as that should be done within the CI harness somehow (there is no way to force-disable compile-time flags from a test itself). Someone more familiar with how tests are run on a macro-level (@rvagg ?) should add a one-liner somewhere so things do not regress in the future.
=> chore : CoreTypes : Remove stray C dependency

.github/workflows/test.yml, curiosrc/seal/task_treerc.go, itests/curio_test.go, lib/ffiselect/ffiselect.go, lib/ffiselect/testffi.go, lib/harmony/harmonydb/harmonydb.go
=> fix: itests: Fix flaky curio itest

go.mod
We don't want to upgrade the go version in the Curio docker build and so let's not upgrade the go version for now. It got accidentally updated in https://github.com/filecoin-project/lotus/commit/6302607650f9191bcc471547c595d712875b2f0f.
=> chore: go mod: revert go version change as it breaks Docker build

.github/workflows/check.yml, CHANGELOG.md
Backport #12054 to `release/v1.27.0` branch to make the lint-checker happy, so that we can get all the checks 🟢
=> chore: backport #12054 to release/v1.27.0 branch

.github/workflows/build.yml, .github/workflows/builtin-actor-tests.yml, .github/workflows/check.yml, .github/workflows/docker.yml, .github/workflows/release.yml, .github/workflows/sorted-pr-checks.yml, .github/workflows/stale.yml, .github/workflows/sync-master-main.yaml, .github/workflows/test.yml
n/a
Request contents read permissions explicitly in GitHub Actions.
This permissions are granted implicitly in public repositories (like lotus), but need to be requested explicitly in private repositories (like lotus-priv). This change will allow us to finish the migration of lotus-priv to GHA.
=> chore: ci: request contents read permissions explicitly in gha

.github/workflows/release.yml
https://github.com/filecoin-project/lotus/actions/runs/9269923862/job/25502214825 failed to push to https://github.com/filecoin-project/homebrew-lotus
Use a custom GITHUB_TOKEN for the goreleaser step of the release.
=> fix: ci: use custom GITHUB_TOKEN for GoReleaser

.github/workflows/docker.yml
https://ipdx-workspace.slack.com/archives/CP50PPW2X/p1716967567670129
When the workflow is triggered manually, infer the `sha` and `ref` to use for generating Docker metadata from the git checkout instead of relying on the `github` context (which points to the git info of the version of the workflow we're using).
We didn't release the tag before because the tag release was tied to the tag push trigger only. I have now run the workflow again (from this branch) and verified the tag is being correctly pushed:
- https://github.com/filecoin-project/lotus/actions/runs/9283617669/job/25544197664
- e.g. https://hub.docker.com/layers/filecoin/lotus-all-in-one/v1.27.0/images/sha256-975685469d3785934d767d97c3a4a7275a273fdd1fe0a73ebdc51e7a9bf032bd?context=explore
Before you mark the PR ready for …
=> fix: ci: publish correct docker tags on workflow dispatch

api/docgen-openrpc/openrpc.go, build/panic_reporter.go, build/version.go, chain/beacon/drand/drand.go, cmd/lotus-bench/main.go, cmd/lotus-fountain/main.go, cmd/lotus-gateway/main.go, cmd/lotus-health/main.go, cmd/lotus-miner/main.go, cmd/lotus-miner/run.go, cmd/lotus-pcr/main.go, cmd/lotus-seed/main.go, cmd/lotus-shed/main.go, cmd/lotus-stats/main.go, cmd/lotus-wallet/main.go, cmd/lotus-worker/main.go, cmd/lotus/daemon.go, cmd/lotus/main.go, itests/api_test.go, node/builder.go, node/builder_chain.go, node/builder_miner.go, node/impl/common/common.go, node/impl/full/eth.go, node/modules/lp2p/host.go
_Proposal asking for feedback._
This removes `build.BuildVersion` and `build.UserVersion()` and replaces them with `build.NodeBuildVersion`, `build.MinerBuildVersion` and `build.NodeUserVersion()`, `build.MinerUserVersion()` so they can be incremented separately.
Why? Because as per https://github.com/filecoin-project/lotus/issues/12010 we would like to be able to release them separately. This has two problems:
1. Once we fix the version number in here without a `-dev` and tag it, you can build both miner and node with that version string and it looks official. But, we may be prepared to release one and not the other (node vs miner) and may consider one of them not release-ready so not deserving of an official release.
2. We would like to automate the build and release process such that …
=> feat!: build: separate miner and node version strings

storage/sealer/worker_local.go
This PR fixes multiple issues in GenerateWindowPoStAdv
* Data race assigning ctx to a shared value
* Fairly severe data race when a ladder of contexts are cancelled from multiple goroutines
* That data race could make some goroutines hang, leading to slow or missed PoSts, also leading to incorrectly skipped sectors
This issue led to incorrect PoSts being produced in Curio. This was not a huge deal in lotus-miner thanks to multiple layers of checks and retires, just caused slower PoSts.
Afaict this bug is here since 2022.
- `area`, e.g. api, chain, state, market, mempool, …
=> fix: storage: Fix a race in GenerateWindowPoStAdv

itests/kit/blockminer.go, itests/kit/node_unmanaged.go, itests/manual_onboarding_test.go
@aarshkshah1992 this is on top of the unmanaged miner work in #12017, There's 2 things in here:
1. `MineBlocksMustPost` is now able to watch for posts from more than just itself. So when we add UnmanagedMiners we can add them to the list of miners it checks posts for. It just looks for whichever is the earliest deadline end and then makes sure there is a post in there for the sectors (most will have zero sectors).
2. Make the UnmanagedMiners continue to post until context cancel, so we won't run into trouble with them missing post. This also means I've changed the channel return struct to have a bool for first-post. It only sends on the channel if it's first post _or_ there's an error. It also means that an error may not go noticed by the main test function but I think that might be OK …
=> feat: test: MineBlocksMustPost can watch for >1 miners

chain/events/filter/index.go, cmd/lotus-shed/indexes.go
From experience running this:
1. Add a warning about running this against a node that's actively collecting events, you'll have trouble
2. Use `IMMEDIATE` transactions so we know as soon as we start a transaction whether we can get an exclusive lock for a write or not so we can error more easily.
3. Add an optional temporary index for our query which significantly speeds up this process (a _lot_).
4. Run an optional vacuum after we're done.
=> feat: cli,events: speed up backfill with temporary index

itests/kit/node_unmanaged.go, itests/manual_onboarding_test.go
Implements a test for Snap Deals (by upgrading an active CC sector with actual pieces and then using DDO for sector upgrade) with real proofs.
=> Implement snap deals test for manual sector onboarding

.github/workflows/check.yml, chain/types/fil.go, cli/helper.go, cli/info.go, cli/multisig.go, cli/net.go, cli/paych.go, cli/send.go, cli/sending_ui.go, cli/spcli/actor.go, cmd/lotus-bench/cli.go, cmd/lotus-bench/reporter.go, cmd/lotus-bench/rpc.go, cmd/lotus-shed/actor.go, cmd/lotus-shed/miner-multisig.go, cmd/lotus-sim/info.go, cmd/lotus-sim/info_capacity.go, cmd/lotus-sim/info_state.go, cmd/lotus-sim/info_wdpost.go, cmd/lotus-sim/list.go, cmd/lotus-sim/profile.go, cmd/lotus-sim/run.go, cmd/lotus-sim/upgrade.go, cmd/lotus-sim/util.go, node/config/load.go
Another attempt at bumping the linter.
In 1.59, they removed a blanket `Ignore: "fmt:.*",` and instead now rely on a more targeted ignore set of rules based on the types that `fmt.Fprint*()` prints into. The main reason this bites us hard here is because when we print from `urfave/cli` `Command` runners, we use the built-in context `AppWriter` and `ErrWriter`. `AppWriter` is _usually_ `os.Stdout` which is not excluded in the new rules, `ErrWriter` is _usually_ `os.Stderr` but it could also be something else and the new rules can't differentiate and neither can we.
I'm fine with the more targeted ruleset. It means having to opt-in to ignores if you have good reason to. Mostly I've gone with `_, _ = ` ignores, but there's a few places of blocks of `fmt.Fprintf` lines where I've gone with …
=> src: lint: bump golangci-lint to 1.59, address unchecked fmt.Fprint*

chain/events/filter/index.go
* fix two unclosed multi-row queries
* tune options to limit wal growth
Ref: https://github.com/filecoin-project/lotus/issues/12089
--
~This is a draft for now while I test it out. I've manually truncated my current, massive wal file (`sqlite3 /path/to/sqlite/events.db` followed by `PRAGMA wal_checkpoint(TRUNCATE);`) so I'm starting from zero again and will watch its behaviour with this and report back.~
=> fix: events: sqlite db improvements

README.md
https://ipdx-workspace.slack.com/archives/CP50PPW2X/p1718485685713539
Remove the unused badge.
=> chore: docs: remove unused badge from the README

documentation/misc/Building_a_network_skeleton.md
Making some updates/changes while reading through Building_a_network_skeleton.md
Go-State-Types Checklist updates
=> docs:Building_a_network_skeleton.md cleanups

api/types.go, build/openrpc/full.json, build/params_2k.go, build/params_butterfly.go, build/params_calibnet.go, build/params_interop.go, build/params_mainnet.go, build/params_testground.go, chain/consensus/filcns/upgrades.go, documentation/en/api-v0-methods.md, documentation/en/api-v1-unstable-methods.md, node/impl/full/state.go
This PR updates the codename for NetworkVersion23 to reflect that Waffle has been choosen for the codename of NV23: https://metropolis.vote/dashboard/c/6pnapz4axv.
Slack-thread asking for clarification here: https://filecoinproject.slack.com/archives/CEHTVSEG6/p1718632500744349?thread_ts=1717005618.376869&cid=CEHTVSEG6
=> chore: upgrade: Update codename for NV23

.github/workflows/test.yml
There's a bunch of itests that were removed as part of https://github.com/filecoin-project/lotus/pull/11999 that we also need to remove from the CI workflow.
=> chore: market tests: remove non-existent market tests from CI workflow

.goreleaser.yaml
Fixes: https://github.com/filecoin-project/lotus/issues/12120
```
$ goreleaser check
• by using this software you agree with its EULA, available at https://goreleaser.com/eula
• running goreleaser v2.0.1-pro
• checking                                 path=.goreleaser.yaml
• 1 configuration file(s) validated
• thanks for using goreleaser-pro!
```
=> fix: release: update goreleaser config file

chain/events/filter/index.go, chain/events/filter/index_test.go, node/impl/full/eth.go
Closes https://github.com/filecoin-project/lotus/issues/11640 and #12078
=> fix: events index: record processed epochs and tipsets for events and eth_get_log blocks till requested tipset has been indexed

chain/types/ethtypes/eth_types.go, gateway/proxy_eth.go, itests/eth_api_test.go, node/impl/full/eth_utils.go
https://github.com/filecoin-project/lotus/issues/12083
```
$ curl  -s -X POST localhost:1234/rpc/v1   -H "Content-Type: application/json"   -d '{
"jsonrpc":"2.0",
"method":"eth_getBlockByNumber",
"params":["safe", true],
"id":1
}'  | jq -r '.result.number' | xargs printf "%d\n"
1714033
$ curl  -s -X POST localhost:1234/rpc/v1   -H "Content-Type: application/json"   -d '{
"jsonrpc":"2.0",
"method":"eth_getBlockByNumber",
"params":["latest", true],
"id":1
}'  | jq -r '.result.number' | xargs printf "%d\n"
1714063
```
- `area`, e.g. api, chain, state, mempool, multisig, …
=> feat: support "safe" param for eth_getBlockByNumber for 30 blocks

.github/workflows/test.yml, itests/kit/blockminer.go, itests/kit/node_unmanaged.go
Fixes: https://github.com/filecoin-project/lotus/issues/12091 (I think)
Pulled out of #12105 where I was forced to figure it out and fix it.
=> fix: itest: fix wdpost proving epoch calculation

build/bootstrap/mainnet.pi
Removed the likely discontinued node based on discussion in https://filecoinproject.slack.com/archives/C039RBG3RPC/p1715255422205499
The owner did not reply according to @Fatman13 and the node is unreachable (https://probelab.io/bootstrappers/filecoin) since at least beginning of May.
=> fix: bootstrap: remove discontinued bootstrap node

build/params_interop.go
Fixed the problem that `UpgradePhoenixHeight` is larger than `UpgradeWaffleHeight` in interop.
=> fix: Update UpgradePhoenixHeight to -26 in interop

.github/workflows/test.yml
n/a
Relax the check that controls the self-hosted runners usage to pass through whenever the workflow runs in any repo inside filecoin-project org.
n/a
=> chore: ci: use self-hosted runners in the original repo or any fork inside the filecoin-project org

.github/workflows/sorted-pr-checks.yml
n/a
1. Use `workflow_run.head_repository` + `workflow_run.head_branch` in the concurrency group name instead of `workflow_run.id`. This way, the concurrency group should work across all the workflows associated with a single PR.
2. Do not `cancel_in_progress` workflow runs of the sorted PR checks workflow. This should minimise the number of notifications users receive about cancelled workflows.
=> fix: ci: update concurrency group settings of the sorted pr checks workflow

itests/fevm_test.go
Plus some code improvement refactoring while I was in there (and mildly frustrated). Apologies for the larger-than-necessary diff, it's mostly refactoring the tests to reuse code and make a bit nicer.
This pull request is on top of https://github.com/filecoin-project/lotus/pull/12132 which has a dev actors bundle (minus niporep).
Background for this fix, [from Slack](https://filecoinproject.slack.com/archives/C029MT4PQB1/p1718764465194299), @Stebalien said:
> This changes every time we build a new actors bundle (we have it fail the tests so we can watch for large regressions).
I've cherry-picked this out of #12105 where I had to figure out what the new values should be. They're not much different to current, just increased by ~5 in each case.
=> fix: fevm: update tests for latest actors bundle

chain/actors/builtin/miner/utils.go, chain/gen/genesis/miners.go, cmd/lotus-bench/bench-sectors.sh, cmd/lotus-bench/main.go, cmd/lotus-bench/simple.go, cmd/lotus-seed/main.go, itests/kit/ensemble.go, itests/kit/node_opts.go, itests/migration_test.go
* Introduce a `SealProofVariant` type with standard, synthetic and non-interactive forms so we can do simpler switching between the variants
* Wire up ni-porep to lotus-bench `simple` and add a configurable bash script that can run through the whole sealing process
=> SealProofVariant and lotus-bench NI-PoRep additions

itests/kit/node_unmanaged.go, itests/manual_onboarding_test.go
Currently stacked on top of #12130 which should be merged first.
This is from niporep work, extracted directly out of #12105 and includes some necessary bits from there but there are also some generally useful fixes and improvements. One thing I'm working toward is multi-sector aggregates which I haven't _quite_ got to but this refactoring makes it possible. Getting this out of #12105 makes that PR much simpler to deal with.
=> chore: test: refactor, fix and improve unmanaged miner

CHANGELOG.md
Similar to the one we added for 1.27.1, but we have yet another migration worth mentioning.
=> chore: docs: add changelog upgrade warning for events db migration

itests/kit/node_unmanaged.go
Flaky noticed here: https://github.com/filecoin-project/lotus/actions/runs/9673748140/job/26688221640
I'm pretty sure this is it - miner isn't enrolled in cron, `di.CurrentEpoch - di.PeriodStart` is negative, our deadline index is a uint64 overflow to some massive number which doesn't match what we want so it's always false.
There's 2 other places in the code I've done this same calculation but this one is missing the abs().
=> fix: niporep: unflake provecommit failure for niporep

go.mod, go.sum
Update `go-state-types` to RC3.
=> chore: go-state-types: update to RC3

build/openrpc/full.json, build/openrpc/gateway.json, chain/consensus/common.go, chain/consensus/filcns/upgrades.go, chain/gen/genesis/genesis.go, chain/gen/genesis/genesis_eth.go, chain/types/actor.go, chain/types/cbor_gen.go, chain/vm/mkactor.go, chain/vm/vm.go, cli/evm.go, cli/state.go, cmd/lotus-shed/indexes.go, documentation/en/api-v0-methods.md, documentation/en/api-v1-unstable-methods.md, itests/eth_filter_test.go, itests/fevm_test.go, itests/migration_test.go, node/impl/full/eth_trace.go, node/impl/full/eth_utils.go, node/modules/actorevent.go
Per the [FIP][1], the top-level actor address field should only be used for delegated addresses. Unfortunately, the FIP's design was [changed][2] but neither lotus genesis code nor the field name were updated to reflect this. Fortunately, all the migration code (on mainnet, at least), has correctly left this field unset/unchanged (except for actors with `f4` addresses).
[1]: https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0048.md#new-lookup_delegated_address-syscall-and-state-changes
[2]: https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0048.md#recording-other-addresses-in-the-actorstate-root
1. Rename `Actor5.Address` to `Actor5.DelegatedAddress`.
2. Only set it when it's an `f4` address.
- …
=> fix: state: rename Actor.Address and only use it for `f4` addresses

build/openrpc/full.json, build/openrpc/gateway.json, chain/consensus/common.go, chain/consensus/filcns/upgrades.go, chain/gen/genesis/genesis.go, chain/gen/genesis/genesis_eth.go, chain/types/actor.go, chain/types/cbor_gen.go, chain/vm/mkactor.go, chain/vm/vm.go, cli/evm.go, cli/state.go, cmd/lotus-shed/indexes.go, documentation/en/api-v0-methods.md, documentation/en/api-v1-unstable-methods.md, go.mod, go.sum, itests/eth_filter_test.go, itests/fevm_test.go, itests/kit/node_unmanaged.go, itests/migration_test.go, node/impl/full/eth_trace.go, node/impl/full/eth_utils.go, node/modules/actorevent.go
Backports the following PRs from master:
https://github.com/filecoin-project/lotus/pull/12150
https://github.com/filecoin-project/lotus/pull/12154
https://github.com/filecoin-project/lotus/pull/12155
https://github.com/filecoin-project/lotus/pull/12156
=> chore: NV23 backport: one more round of backports from master

go.mod, go.sum
Update `go-state-types` to fix the calibnet and butterfly net faucet issue post NV23 FIP-0085 migration.
=> chore: go state types: update deps

CHANGELOG.md, build/openrpc/full.json, build/openrpc/gateway.json, build/openrpc/miner.json, build/openrpc/worker.json, build/version.go, documentation/en/cli-lotus-miner.md, documentation/en/cli-lotus-worker.md, documentation/en/cli-lotus.md
=> chore: release: Lotus v1.28.0-rc1

itests/mempool_test.go, node/impl/full/mpool.go, node/impl/full/mpool_test.go
If the "to" address of an outgoing message is a _delegated_ address, verify that it maps to a valid Ethereum address. This isn't a consensus critical change, but it'll help prevent client-side address conversion libraries from directing messages into oblivion (e.g., by mis-translating `0xff0000....` addresses into `f410f...` addresses instead of `f0...` addresses.
Notes:
- We cannot filter these addresses inside pubsub (without a network upgrade) without risking the stability of the pubsub network (all nodes need to agree on which messages are valid and which messages aren't; censorship is treated as an attack).
- We've discussed making it impossible to send funds to "invalid" f4 addresses within the protocol itself, but that has other implications and is a more complicated debate (it …
=> feat: api: sanity check the "to" address of outgoing messages

documentation/misc/RELEASE_ISSUE_TEMPLATE.md, documentation/misc/Update_Dependencies_Lotus.md
Add a document detialing how to update the most common dependencies in Lotus.
=> chore: docs: Add initial `Update_Dependencies_Lotus.md`

build/params_2k.go, build/params_butterfly.go, build/params_interop.go
Since `GenesisNetworkVersion?` is set to network.Version22, and the upgrade `UpgradePhoenixHeight = abi.ChainEpoch(-25)` - we are never triggering the switch Quicknet in 2k-networks and butterfly-networks.
This ensure that we start using Quicknet from start.
=> fix: build: Ensure Quicknet is used when spinning up 2k/butterfly networks

build/params_calibnet.go
bootstrap f3 at 100 epoch after nv23 is activated.
enable f3 by default for calib nodes for [passive testing](https://docs.google.com/document/d/14hMFN95_AsByBh7iMc4r_czUgg8tfjHQ1gTsmmHZ8jI/edit) purpose
=> feat: calib: enable f3 by default

build/params_2k.go, build/params_butterfly.go, build/params_calibnet.go, build/params_interop.go, build/params_mainnet.go, build/params_shared_funcs.go, chain/lf3/f3.go, node/builder_chain.go, node/builder_miner.go, node/modules/lp2p/pubsub.go
Closes https://github.com/filecoin-project/go-f3/issues/388 
This PR:
* Does not run F3 if the `DISABLE_F3` env variable is set.
* Stops F3 in runtime if the `DISABLE_F3` env var is set. The process is currently polling this env variable every 5 minutes, we can poll more often if needed.
To test it you can run Lotus normally with F3 enabled and then set `DISABLE_F3 = 1  on your environment, this should output a log saying that F3 has been disabled.
=> feat:ec:f3: add env var to disable F3

build/params_2k.go, build/params_butterfly.go, build/params_calibnet.go, build/params_interop.go, build/params_mainnet.go, chain/lf3/ec.go, chain/lf3/f3.go, chain/lf3/manifest.go, go.mod, go.sum, node/builder_chain.go, node/modules/lp2p/pubsub.go
Closes https://github.com/filecoin-project/go-f3/issues/370
This PR integrates support for F3's dynamic manifest. Through the dynamic manifest, a manifest server is able to trigger configuration changes over F3 remotely. The F3 node listens to new manifests, and when a new manifest is received: 
* It tearsdown and setup a new pubsub topic for the new F3 configuration.
* It rebootstraps or applies the reconfiguration (depending on the parameters of the manifest).
* It resumes the normal operation of F3.
Depends on https://github.com/filecoin-project/go-f3/pull/391
- `area`, e.g. …
=> feat:ec: integrate F3 dynamic manifest

build/params_2k.go, build/params_butterfly.go, build/params_calibnet.go, build/params_interop.go, build/params_mainnet.go, chain/lf3/ec.go, chain/lf3/f3.go, chain/lf3/manifest.go, go.mod, go.sum, node/builder_chain.go, node/modules/lp2p/pubsub.go
=> feat:ec: integrate F3 dynamic manifest 

CHANGELOG.md, build/openrpc/full.json, build/openrpc/gateway.json, build/openrpc/miner.json, build/openrpc/worker.json, build/version.go, documentation/en/cli-lotus-miner.md, documentation/en/cli-lotus-worker.md, documentation/en/cli-lotus.md
diff with v1.28.0-rc2 
- #12185
Orjan was very quick at clicking!! This change introduces the manifest for the "control" nodes for F3 passive testing. This change shouldnt have any impact on actual production nodes.
=> build: release: v1.28.0-rc3

cli/compstate.html.template, cli/compstatemsg.html.template, cli/state.go
Splitting long content template into file is more friendly for reading, also for IDE rendering
=> chore: cli: use `embed` pkg to split long template content to file

go.mod, go.sum
CVE-2024-27304 was fixed in 5.5.4
=> chore: deps: upgrade to jackc/pgx@v5.6.0

.github/pull_request_template.md, .github/workflows/changelog.yml
Closes #12069 
This PR adds a CI workflow that checks whether the PR contains CHANGELOG.md modifications.
The check can be skipped by adding [skip changelog] to the PR title or labeling the PR with skip/changelog. These instructions are included in the PR template and the workflow failure message.
The checks succeed if CHANGELOG.md is modified and fail otherwise.
=> ci: add changelog check workflow

itests/kit/evm.go
Fixes the flaky `TestLegacyContractInvocation` test in eth_legacy_tx_test. The message indexing in the eth tx db happens async to submitting the transactions and so we need to wait for the submitted tx to be indexed before we can read it from the tx db.
=> [skip changelog]: fix: flaky eth_legacy_tx_test: wait for async msg indexing

itests/kit/ensemble.go, itests/kit/node_unmanaged.go, itests/manual_onboarding_test.go, itests/niporep_manual_test.go
* Test various multi-sector cases with niporep
* UnmanagedMiner can now onboard multiple sectors for one miner and manage PoSt for all of them
This has tests for both real and mock proofs with NI-PoRep, it includes testing 1 and more (up to max 65) sectors in mock proofs, including cases where there are expected sector failures but activation can still continue. They also proceed to confirm Window PoSt on all the sectors and that the miner gets the appropriate power for them all. Then they continue to snap a deal into one of the onboarded sectors (and because of the new PoSt handling, the new snapped sector can be successfully PoSted if need be--although there's no need here beyond just possible accident of snapping and then needing to PoSt before the test ends).
Lots of refactoring in …
=> feat: niporep: multi-sector onboarding through UnmanagedMiner

.github/workflows/test.yml, CHANGELOG.md, build/bootstrap/calibnet.pi, build/bootstrap/mainnet.pi, build/openrpc/full.json, build/openrpc/gateway.json, build/openrpc/miner.json, build/openrpc/worker.json, build/version.go, chain/events/filter/index.go, chain/events/filter/index_test.go, chain/types/ethtypes/eth_types.go, documentation/en/cli-lotus.md, gateway/proxy_eth.go, go.mod, itests/eth_api_test.go, itests/mempool_test.go, node/impl/full/eth.go, node/impl/full/eth_utils.go, node/impl/full/mpool.go, node/impl/full/mpool_test.go
Ref: https://github.com/filecoin-project/lotus/issues/12157
Currently:
* c87e2f2a64b6df3176f7a0ee208b8879418d7ca6 from https://github.com/filecoin-project/lotus/pull/12080
* 069ffce4ef32f885dd0b668c6129a5cfd25a0b5e from https://github.com/filecoin-project/lotus/pull/12135
* 8bc490665e https://github.com/filecoin-project/lotus/pull/12094
* 893ce8e98d https://github.com/filecoin-project/lotus/pull/12103
* 6408709018 https://github.com/filecoin-project/lotus/pull/12110
* 7141847927 https://github.com/filecoin-project/lotus/pull/12133
* 6f821c3285 https://github.com/filecoin-project/lotus/pull/12099
=> v1.27.2 changes

.github/pull_request_template.md
chore: docs: Update label for `skip/changelog` in the PR-template
- Add the label `skip-changelog` to the PR
=> chore: docs: Update label to `skip/changelog` in the PR-template

CHANGELOG.md, chain/types/ethtypes/eth_types.go, itests/eth_filter_test.go, node/impl/full/eth_utils.go
This fixes a  bug in the Bloom Filter for events that is part of ETH Tx receipts.  The issue is that all receipts reference the same underlying backing empty array for it's events bloom filter during initialisation. However, modification to the bloom filter then also modifies the backing array... which is then used to initialise other bloom filters.
**_This also fixes the eth_filters flaky itest._**
=> fix: Eth Tx Events Bloom Filter: fix slice modification bug and flaky test

chain/events/filter/index.go, chain/events/filter/index_test.go, node/impl/full/eth.go
Temporary patch for the v1.28 release to fix some of the issues mentioned in https://github.com/filecoin-project/lotus/issues/12205.
- Event Index is not aware of null blocks because it is never invoked for null blocks. 
- If user does not explicitly specify "latest", eth_getlogs should inly block will "latest"-1 as the events for the "latest" block will only be available after the block is executed (deferred execution).
The right thing to do here is revisit how all the ETH RPC APIs deal with the "latest" flag and ensure they are "deferred execution-safe". We also need to make the Event Index aware of null blocks(or atleast have a way to ensure that a given height resulted in a null block and so it has already "processed" the events for that height). Let's prioritise this as part of our …
=> fix: ETH getLogs: fix slowness at head and ignore null blocks

chain/events/filter/index.go, chain/events/filter/index_test.go, node/impl/full/eth.go
Backports https://github.com/filecoin-project/lotus/pull/12207 to NV23.
=> chore: v1.28.0: backport get logs fixes

CHANGELOG.md, build/openrpc/full.json, build/openrpc/gateway.json, build/openrpc/miner.json, build/openrpc/worker.json, build/params_butterfly.go, build/params_calibnet.go, build/params_interop.go, build/version.go, documentation/en/cli-lotus-miner.md, documentation/en/cli-lotus-worker.md, documentation/en/cli-lotus.md
During the prep of shipping Lotus v1.28.0-rc2/rc3/rc4 we added the Calibration network upgrade epoch, but we did not land this change in master.
- Merge `release/v1.28.0` branch back into master.
- Update version to v1.28.1-dev in master.
- Add …
=> chore: merge `release/v1.28.0` / v1.28.0-rc4 back to master

CHANGELOG.md, node/impl/full/eth_trace.go
Closes https://github.com/filecoin-project/lotus/issues/12209.
Fixes a panic the ETH TRACE API.
=> fix: Eth Trace Block: nil access panic

itests/kit/node_unmanaged.go
Ref: https://github.com/filecoin-project/lotus/issues/12001
Ref: https://github.com/filecoin-project/lotus/actions/runs/9887807887/job/27310358031?pr=12207
=> fix: test: use parents instead of height-1 to calculate sector activation epoch

chain/lf3/f3.go
https://github.com/filecoin-project/lotus/issues/12215
Reduce the log level for `miner with id...` to DEBUG, since in normal operation of F3 at least 5 messages are sent per epoch. In an event of rebroadcast the number of messages broadcasted could surpass 10. Hence, the `DEBUG` log level.
None.
- If the change does not require …
=> fix: bug: Reduce log level in F3 message sending to Debug

node/impl/full/eth.go
Fixes: https://github.com/filecoin-project/lotus/issues/12218
See #12218 for gory details on why this is necessary. This should fix any case where someone does an eth `sendRawTransaction` and it's not immediately available via other APIs that expect to be able to translate the eth tx hash to a Filecoin message CID (internally or via `EthGetMessageCidByTransactionHash` or `EthGetTransactionHashByCid`).
=> fix: eth: make tx hash immediately available in lookup db after submission

chain/ethhashlookup/eth_transaction_hash_lookup.go, chain/events/filter/index.go, chain/events/filter/index_migrations.go, chain/index/msgindex.go, chain/index/msgindex_test.go, cmd/lotus/daemon.go, itests/msgindex_test.go, lib/sqlite/sqlite.go, lib/sqlite/sqlite_test.go, node/modules/actorevent.go, node/modules/ethmodule.go, node/modules/msgindex.go
All of the versioning and migration logic is shared between the 3 sqlite databases we use the other two have the same pending-query problem as was resolved for _meta in https://github.com/filecoin-project/lotus/pull/12090, so that's addressed here by making it common.
* Use the same `PRAGMA` set across all 3 - this may need to change in future but we can configure that later when we need it.
* Same `_meta` versioning and migration logic. Do it all in a migration loop where each migration is wrapped in a transaction, logging and error handling and the calling instance is responsible for feeding in functions that can perform a migration. Versioning and `_meta` is entirely hidden from the calling instance.
* Two minor breaking changes in here:
1. `ethhashlookup.NewTransactionHashLookup` now …
=> feat: sqlite: extract common init and migration utilities

.github/workflows/release.yml, build/openrpc/full.json, build/openrpc/gateway.json, build/openrpc/miner.json, build/openrpc/worker.json, build/version.go, documentation/en/cli-lotus.md
Let's try out the auto-release builder again.
=> lotus v1.27.2-rc2

CHANGELOG.md, chain/lf3/ec.go, chain/lf3/manifest.go, go.mod, go.sum
#12236
Upgrade to the latest go F3, with fix to default cert exchange config in local devnet.
None
=> chore: f3: Upgrade to latest go-f3 `v0.0.4`

chain/ethhashlookup/eth_transaction_hash_lookup.go
Closes: https://github.com/filecoin-project/lotus/issues/12171
Prompted because I'm noticing that my WAL for both calibnet and mainnet nodes is ~32M, even with my calibnet node running master which has https://github.com/filecoin-project/lotus/pull/12098 which should result in it being compacted earlier than that (suggests that queries may be remaining open?).
The main thing that stands out in this file is the use of the preparedstatement that's prepared each time it's used, and not closed. So that's what's probably retaining memory and perhaps it's also responsible for the WAL size (I'm not sure how though tbh).
This refactor makes all queries use preparedstatements that persist for the lifecycle of the index, so we get the efficiency gains from that.
=> fix: ethhashlookup: clean-up query management and lifecycle

CHANGELOG.md, itests/api_test.go, node/modules/storageminer.go, storage/pipeline/precommit_batch.go, storage/pipeline/sealing.go
1) Fixes flakiness in `testNonGenesisMiner` in `api_test` by de-racing the closing of the miner repo and the sealer reading it in a go-routine. If the go-routine gets scheduled after the miner repo is closed in the test, this causes a panic which fails the test. The right thing to do here is for the sealer to read the repo when it is instantiated and pass the config to the go-routine.
2) Adds some logging to the `testOutOfGasError` itest to see what's going on when it fails (very very rare).
=> fix: api itest panic

itests/wdpost_dispute_test.go
Fixes the flaky wdPost dispute itest.
See https://github.com/filecoin-project/lotus/actions/runs/9468130894/job/26083829500 for an example failed run.
=> fix: flaky wdPost dispute itest

.github/workflows/build-pulse.yml
https://github.com/filecoin-project/lotus/issues/12127
Create a workflow that uploads junit XML reports that the Test workflow produces to BuildPulse.
This PR depends on setting up the following repository variables:
- BUIDPULSE_ACCOUNT_ID
- BUILDPULSE_REPOSITORY_ID
- BUILDPULSE_ACCESS_KEY_ID
And the following repository secrets:
- BUILDPULSE_SECRET_ACCESS_KEY
- If the PR affects users (e.g., new feature, bug fix, system requirements change), update the CHANGELOG.md and add …
=> feat: ci: upload junit xml reports to buildpulse

go.mod, go.sum
Includes fix for another possible minor leak: https://github.com/libp2p/go-libp2p/releases/tag/v0.35.4
=> chore: libp2p: update to v0.35.4

chain/store/store.go, chain/store/weight_test.go
@rjan90 and @jennijuju reported seeing this log a lot, which prompted an investigation of the logic. This code does not implement [FIP-0023](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0023.md) correctly. Specifically, if we have the following mintickets:
```
ts1: 1, 2
ts2: 0,3
```
This code will incorrectly return ts1 as the "smaller" tipset, even though the tie should have been broken in favour of ts2 based on `1 > 0`.
Fix this bug, we should return in favour of ts2 if its ticket is smaller. Add test.
- `area`, e.g. api, chain, state, mempool, multisig, …
=> fix(store): correctly break weight ties based on smaller ticket

cmd/lotus-miner/sectors.go
Currently, all sectors are removed in a for loop if expired sectors are marked for removal. This PR, creates a batch of 5 sectors and waits 2 seconds between batched. It should help alleviate the pressure on storage subsystem and avoid crashes.
- Add …
=> fix: lotus-miner: batch expired sector removal in lotus-miner

chain/events/filter/index.go, chain/events/filter/index_test.go
This is a stacked PR ontop of #12261; I'm doing it separately because it moves a bunch of things around that are a bit of a distraction in #12261 and I think it's probably easier to see and review as a separate commit.
This is all about running `EXPLAIN QUERY PLAN` on all selects and updates in the events db and ensuring that an acceptable index is used as the first step in the execution. We want to either narrow down by height or tipset and we have a few indexes that do this across two tables.
This should lock in the perf gains in #12261 such that any future tinkering with the indexes will fail this test and cause the author to consider carefully whether the change is appropriate.
=> test: events: test sqlite indexes used in query plan of all selects and updates

CHANGELOG.md, chain/events/filter/index.go, chain/events/filter/index_migrations.go, chain/events/filter/index_test.go
_Edit:_ If you want to take advantage of the performance gains from this change without upgrading to a version of Lotus that includes this fix, you can do it manually for yourself in a safe way that will still work when you eventually do upgrade Lotus to include this fix.
With `sqlite3` installed, substituting the correct path for `/path/to/lotus/repo`, run:
```
sqlite3 /path/to/lotus/repo/sqlite/events.db '
DROP INDEX IF EXISTS event_emitter_addr;
DROP INDEX IF EXISTS event_reverted;
DROP INDEX IF EXISTS event_entry_indexed_key;
DROP INDEX IF EXISTS event_entry_codec_value;'
```
---
Fixes: https://github.com/filecoin-project/lotus/issues/12255
SQLite was found to be avoiding the intended initial indexes for some types of complex queries and opting for minor indexes which don't narrow …
=> fix: events: address sqlite index selection performance regressions

build/buildconstants/drand.go, build/drand.go
https://github.com/filecoin-project/lotus/pull/10476
- Remove the network-portion of `mainnet` just like it was done for `incentinet` in https://github.com/filecoin-project/lotus/pull/10476. This will stop network clients being built for the unused network and will resolve spurious errors like:
```
{"level":"info","ts":"2024-07-09T15:36:34.379+1000","logger":"drand","caller":"client/optimizing.go:194","msg":"","optimizing_client":"endpoint down when speed tested","client":"HT
TP(\"https://api.drand.secureweb3.com:6875/\").(+verifier)","err":"decoding response: EOF"}
``` 
- [As per ](https://filecoinproject.slack.com/archives/C047Z15JNEA/p1721656072094789?thread_ts=1720504044.538999&cid=C047Z15JNEA) @AnomalRoil remove unused `devnet` config
=> [skip changelog] chore: drand: cleanup legacy and unused configs

.github/workflows/build-pulse.yml
The artifacts are extracted into subdirectories. This change ensures buildpulse action can find them.
=> fix: ci: use properly globed path for buildpulse

CHANGELOG.md, chain/lf3/f3.go, go.mod, go.sum
None.
Register otel collector bridging to the default prometheus registry so that F3 metrics (which use the newer otel APIs for metrics) get included in Lotus metrics.
None.
- Add the label `skip/changelog` to …
=> metrics: f3: Set up otel metrics reporting to prometheus

CHANGELOG.md, api/api_full.go, api/mocks/mock_full.go, api/proxy_gen.go, build/bootstrap/butterflynet.pi, build/buildconstants/params_2k.go, build/buildconstants/params_butterfly.go, build/openrpc/full.json, build/openrpc/gateway.json, build/openrpc/miner.json, build/openrpc/worker.json, chain/lf3/f3.go, chain/lf3/manifest.go, documentation/en/api-v1-unstable-methods.md, go.mod, go.sum, node/impl/full/f3.go
None.
Upgrade to the latest version of go-f3 with initial power table storage with far enough lookback, and dynamic manifest persistence.
***Note: Pending concrete release tag in go-f3.***
None.
- Add the …
=> chore: f3: Upgrade to go-f3 `v0.0.5`

build/buildconstants/params_shared_vals.go, build/params_shared_vals.go, chain/messagepool/messagepool.go
Makes testground build again, namely:
`for d in ./cmd/lotus*; do go build -tags testground -o /dev/null $d || break ; done`
Missed due to https://github.com/filecoin-project/lotus/issues/12239
=> [skip changelog] chore: types: fix type mismatches missed in #12246

documentation/misc/Building_a_network_skeleton.md
- As per comment in https://github.com/filecoin-project/lotus/pull/12172#issuecomment-2242812486, adding steps needed for adding nvXX support in the migrations/invariants commands.
- Update Building_a_network_skeleton.md with the steps needed for adding support for nvXX in lotus-shed cmd´s
- If the change does not require a …
=> Docs: Update Building_a_network_skeleton.md

node/modules/lp2p/host.go
https://github.com/ChainSafe/forest/issues/4576
https://github.com/ChainSafe/forest/pull/4580
https://github.com/ChainSafe/forest/pull/4581
We're setting up local and CI regression tests for Forest bootstrap node to make sure the Kademlia setup works for Lotus. In both test scenarios the bootstrap node has no public IP, and we need to disable the DHT PublicRoutingTableFilter in Lotus. This PR introduces environment variables for doing that.
(Skipping changelog as this is more of a developer-facing feature)
- `area`, e.g. api, chain, state, mempool, multisig, networking, paych, …
=> [skip changelog]feat: p2p: environment variables for disabling DHT query filter and routing table filter

CHANGELOG.md, build/bootstrap/butterflynet.pi, build/openrpc/full.json, build/openrpc/gateway.json, build/openrpc/miner.json, build/openrpc/worker.json, build/version.go, chain/lf3/ec.go, documentation/en/api-v1-unstable-methods.md, documentation/en/cli-lotus-miner.md, documentation/en/cli-lotus-worker.md, documentation/en/cli-lotus.md, go.mod, go.sum
Replacement of #12306 but with current master; let's get this done before anything else moves into master so we can just have the one merge commit and nothing else.
It's a bit different to #12306, but the differences are mostly non-overlapping with `master`, i.e. this is basically master but with what's in #12306 overlaid.
```
$ git diff --stat origin/jen/v1.28.1releasetomaster
.github/workflows/docker.yml                 |  28 ++++++++++---------
.github/workflows/release.yml                | 360 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++---------------------------------------------------------
.gitignore                                   |   6 ++++ …
```
=> Merge 1.28.2 to master

node/builder_chain.go
filter.EventFilterManager starts a chain observer which isn't needed if it's not going to be consumed by events subsystems.
=> fix: events: don't initialise events helpers when not needed

CHANGELOG.md, cli/send.go, cli/send_test.go
This fixes the Lotus send CLI to work with ETH address recipients (both `0xff...` corresponding to Filecoin `f0` addresses and `0xabcd` corresponding to Filecoin `f410f` addresses).
Have tested this locally on a local devnet.
```
./lotus send --from-eth-addr 0x4582e0a8f02f45dfb6cca081b1cb82fcf0508c34 0xff000000000000000000000000000000000003ed 10
f4 addr:  t410fiwbobkhqf5c57nwmuca3ds4c7tyfbdbun3hxwmi
Sending message from: t410fiwbobkhqf5c57nwmuca3ds4c7tyfbdbun3hxwmi
Sending message to: t01005
Using Method: 3844450837
bafy2bzacec3lcrfevp4wsuya65t2nien2cjselbmqd3cnr2w32hukbwxg57zy
```
```
./lotus send 0xff000000000000000000000000000000000003ed 10
Sending message from: t3uhfeeespjbuhde6vfxvgyuhoj4danwv3fdsk3m3t46p2kpegm76jpvukgnlb2w7aucldnmq2j4un3nlxs73a
Sending message to: t01005
Using …
```
=> feat: Lotus Send CLI: Lotus send should work with ETH address receipients

blockstore/badger/blockstore.go
Two standalone fixes around GC - a forgotten `flush()` and lack of `ctx` propagation.
The refator separating the iteration into its own function allows "walking the store with a function", moving a lot of the complexity a step down, leaving [just the logic in place for easier read](https://github.com/filecoin-project/lotus/blob/d6fe66d8280a7c/blockstore/badger/blockstore.go#L393-L416).
cc @ZenGround0 to review, as this used to be their domain
=> [skip changelog] chore: blockstore_gc: minor cleanups

node/impl/full/eth.go
Fixing a copypasta bug in original, the TipSetFilterManager is used for block filters, EventFilterManager is for events.
=> fix: events: remove filter if we fail to add it to the FilterStore

node/bundle/bundle.go
While examining [a fullsync log](https://github.com/filecoin-project/lotus/pull/12272#issuecomment-2244366061) noticed that the actor bundle loader prints directly to STDOUT. Grepping briefly through the codebase uncovered only 2 spots like that, so fix them both.
=> [skip changelog] chore: logging: switch runtime Print() spots to use the logger

cli/send.go
=> fix: send cli: only override method if recipient is a "0x" address

chain/market/fundmanager.go, cli/evm.go, cmd/lotus-shed/migrations.go, documentation/en/cli-lotus.md, storage/pipeline/fsm_test.go, storage/pipeline/input.go, storage/pipeline/upgrade_queue.go
=> chore: fix some comments

CHANGELOG.md, cmd/lotus-shed/indexes.go
Fixes: #12334 
store processed tipset in `event-seen` table after backfilling the events in `lotus-shed backfill-event`
=> fix: lotus-shed: store processed tipset after backfilling events

.github/workflows/build-pulse.yml
This will fix uploads originating from push events.
=> chore: ci: prefix ref passed to build pulse with refs/heads/

CHANGELOG.md, cmd/lotus-shed/indexes.go
Works read-only so can be done on a live events db. Only checks for problems that backfill could (_should be able to_) address.
cc @akaladarshi
=> feat: events: add `lotus-shed indexes inspect-events` health-check

CHANGELOG.md, chain/actors/builtin/builtin.go, chain/actors/builtin/builtin.go.template, chain/stmgr/supply.go
while datacap actor is not expected to be receiving funds, however, it did https://filfox.info/en/message/bafy2bzacebszh56u7lqkooszlmoszfumiq4zztgavsbgnxs2t7cmimpp656cs?t=1 . which is uncovered for circulating supply APIs internal accounting.
=> fix: api: add datacap balance to circ supply

documentation/misc/Building_a_network_skeleton.md
Updating the instructions for integrating the network skeleton into Lotus. Instead of manually modifying the go.mod file to use a local clone of go-state-types, the updated instructions now direct to the "Update Dependencies Lotus" tutorial for steps on updating dependencies that has been released
- If the change does not …
=> chore: docs: Update step in skeleton guide

.github/pull_request_template.md, .github/workflows/changelog.yml, .github/workflows/pr-title-check.yml, CONTRIBUTING.md
This starts on https://github.com/filecoin-project/lotus/issues/12360 as part of landing https://github.com/filecoin-project/lotus/pull/12340
=> docs: seed CONTRIBUTING.md with pr title and changelog expectations

CHANGELOG.md, cmd/lotus-gateway/main.go, documentation/en/default-lotus-config.toml, gateway/handler.go, gateway/handler_test.go, gateway/node.go, gateway/node_test.go, gateway/proxy_eth.go, gateway/proxy_fil.go, go.mod, go.sum, itests/gateway_test.go, node/config/def.go, node/config/doc_gen.go, node/config/types.go
Ref: https://github.com/filecoin-project/go-jsonrpc/pull/118
Ref: https://github.com/filecoin-project/lotus/issues/11589
Ref: https://github.com/filecoin-project/lotus/issues/11153
---
API changes and breakage:
* Plain HTTP connections now can't use stateful ethereum APIs (they couldn't really before, but they allowed addition of filters and subs in a dangerous way), you have to be using WebSockets
* `gateway.NewNode` now only takes 1 argument (the api) and a list of options to override defaults
* `gateway.NewRateLimiterHandler` and `gateway.NewConnectionRateLimiterHandler` have been replaced with `gateway.NewRateLimitHandler`.
* The handlers returned by both `gateway.NewRateLimitHandler` and the primary `gateway.Handler` return an `http.Handler` augmented with a `Shutdown(ctx)` method to …
=> feat!: gateway: fix rate limiting, better stateful handling

chain/consensus/filcns/filecoin.go
This was likely a mistake in the implementation, instead of using the verifier attached to the instance it reached directly into ffi.
The only place, other than the DI builder that we make a new `FilecoinEC` is where we just use it to `CreateBlock`, where we don't insert a verifier, but this doesn't touch this pathway. https://github.com/filecoin-project/lotus/blob/ee00791d9b49278b42ae4f3eb1bf85852da32ca8/chain/gen/gen.go#L511
`VerifyBlock` does go here but we're only doing that in the syncer and it's setup by DI properly.
The only other explanation I have for this, if not a mistake, is that it was done for testing purposes but I can't see anything failing.
=> fix: chain: use instance-local verifier to VerifyWinningPoSt

CHANGELOG.md, documentation/en/default-lotus-config.toml, itests/eth_api_test.go, itests/kit/node_opts.go, node/config/def.go, node/config/doc_gen.go, node/config/types.go, node/impl/full/eth.go, node/modules/ethmodule.go
Closes https://github.com/filecoin-project/lotus/issues/10520.
Part of https://github.com/filecoin-project/lotus/issues/12293.
=> feat: ETH RPC: Use Block Cache for `EthGetBlockByHash`

.github/pull_request_template.md, .github/workflows/changelog.yml, .github/workflows/pr-title-check.yml, CONTRIBUTING.md
Closes: #12148
- A GitHub Actions workflow to automatically check and enforce a consistent format for PR titles
- Started work on `CONTRIBUTING.md` doc that consolidates contributing expectations in one place. https://github.com/filecoin-project/lotus/issues/12360
- If the change does not require a CHANGELOG.md entry, do one of …
=> feat(ci): add PR title check workflow

LOTUS_RELEASE_FLOW.md
This was done as additional content to potentially add for https://github.com/filecoin-project/lotus/pull/12322 .  It includes content I saw in https://github.com/filecoin-project/lotus/discussions/12020 and https://github.com/filecoin-project/lotus/issues/12072 that wasn't previously included.
=> docs: update LOTUS_RELEASE_FLOW with recent FAQs and branch/tag strategy items

.github/workflows/pr-title-check.yml
Encountered this workflow-failure when looking at merging: https://github.com/filecoin-project/lotus/pull/12354#issuecomment-2277613048
- Use `pull_request_target` event trigger in `pr-title-check-yml` in order to support checking PRs from forks.
Creating this PR from my Lotus-fork to confirm that it now succeeds
=> fix(ci): support checking forks in PR-title check workflow

.github/workflows/changelog.yml, .github/workflows/pr-title-check.yml
Linking to https://github.com/filecoin-project/lotus/blob/master/CONTRIBUTING.md#pr-title-conventions instead of README.
I used the wrong URLs in https://github.com/filecoin-project/lotus/pull/12361
=> docs: pr title check fix to link to right doc

documentation/misc/RELEASE_ISSUE_TEMPLATE.md
This takes release issue changes and observations from https://github.com/filecoin-project/lotus/issues/12109 with also having an eye towards the upcoming release process changes per https://github.com/filecoin-project/lotus/issues/12072 .
The general goals here are:
1. Have a checkbox step for each step a releae engineer should take.
2. Reduce duplication in the template itself.  Where content should be duplicated, there is a comment for the issue creator to handle the copy/pasting.
- `area`, e.g. api, chain, state, mempool, multisig, networking, paych, proving, sealing, …
=> docs: release template: update based on 1.28 learnings

CONTRIBUTING.md
This is followup to https://github.com/filecoin-project/lotus/pull/12366#discussion_r1711780636
=> docs: updating CONTRIBUTING.md with table of contents and TOC guidance

.github/workflows/stale.yml
1. Remove the cutesy language, it's kind of insulting. Happy to revert this change if people feel strongly, but I _really_ don't like it when companies do this kind of thing.
2. Extend the close delay for both PRs and issues to 72 hours. We don't really need a response within a day and requiring a response within a day is pretty demanding.
=> ci: improve stalebot behavior/language

CONTRIBUTING.md, LOTUS_RELEASE_FLOW.md
#12072
Update the LOTUS_RELEASE_FLOW document to account for the new release flow.
=> docs: update LOTUS_RELEASE_FLOW.MD document

build/version.go, documentation/en/cli-lotus-miner.md, documentation/en/cli-lotus-worker.md
#12379 
As part of the release checklist, bump the `MinerBuildVersion` in master.
~~- [ ] New features have usage guidelines and / or documentation updates in~~
~~- [ ] [Lotus Documentation](https://lotus.filecoin.io)~~
~~- [ ] [Discussion Tutorials](https://github.com/filecoin-project/lotus/discussions/categories/tutorials)~~
~~- [ ] Tests exist for new functionality or change in behavior~~
=> chore: bump `MinerBuildVersion` in master to v1.28.3-dev

CHANGELOG.md, chain/lf3/manifest.go, go.mod, go.sum
This updates go-f3 from v0.0.7 to v0.1.0, bringing a few new features and many optimizations.
=> feat(f3): update from v0.0.7 to v0.1.0

CHANGELOG.md, go.mod, go.sum
Includes:
- fix for excessive bandwidth usage
- significant performance improvements
- minor F3 consensus fixes
=> feat: f3: update go-f3 to 0.2.0

README.md
https://github.com/filecoin-project/lotus/issues/12374
Removing refrences to the deprecated `releases` branch.
=> docs: update references to releases branch

CHANGELOG.md, build/openrpc/full.json, build/openrpc/gateway.json, build/openrpc/miner.json, build/openrpc/worker.json, build/version.go, documentation/en/cli-lotus-miner.md, documentation/en/cli-lotus-worker.md, documentation/en/cli-lotus.md, go.mod, go.sum, itests/api_test.go, node/modules/storageminer.go, storage/pipeline/commit_batch.go, storage/pipeline/mocks/mock_commit_batcher.go, storage/pipeline/pledge.go, storage/pipeline/precommit_batch.go, storage/pipeline/sealing.go, storage/pipeline/states_replica_update.go, storage/pipeline/states_sealing.go
https://github.com/filecoin-project/lotus/issues/12379
This patch includes:
=> build: release: v1.28.2

.github/workflows/changelog.yml, .github/workflows/pr-title-check.yml
I was just noticing in https://github.com/filecoin-project/lotus/pull/12388 how unnecessary the GHA spam is for a Draft, so this should prevent that until you mark as ready-for-review, I think.
=> fix(ci): don't PR or changelog check for draft PRs

CHANGELOG.md, build/openrpc/full.json, build/openrpc/gateway.json, build/openrpc/miner.json, build/openrpc/worker.json, build/version.go, documentation/en/cli-lotus.md
#12379
PR against master branch with a merge of the release/v1.28.2 branch
=> chore: post release steps for #12379 (v1.28.2 miner and node patch release)

CHANGELOG.md, chain/lf3/f3.go, go.mod, metrics/otel_bridge.go, node/modules/lp2p/host.go, node/modules/lp2p/metrics.go, node/modules/lp2p/transport.go
Alternative to #12401
Resolves filecoin-project/go-f3#575
Exposes bandwidth metrics via opentelemetry. We do this via an async callback to avoid allocating/reporting metrics on any hot-paths. I'm using open telemetry as we've already setup a bridge for F3 and opencensus is deprecated in favor of open telemetry (so we're going to slowly move over anyways).
=> feat(libp2p): expose libp2p bandwidth metrics

CHANGELOG.md, build/openrpc/full.json, build/openrpc/gateway.json, build/openrpc/miner.json, build/openrpc/worker.json, build/version.go, documentation/en/cli-lotus.md
#12343
Update the Lotus Node version string in master to v1.29.1-dev
=> build: update Lotus Node version to v1.29.1-dev in master

CHANGELOG.md, build/openrpc/full.json, build/openrpc/gateway.json, build/openrpc/miner.json, build/openrpc/worker.json, build/version.go, documentation/en/cli-lotus.md
https://github.com/filecoin-project/lotus/issues/12343
Prep v1.29.0 stable release 
=> build: release Lotus node v1.29.0

CHANGELOG.md, api/api_full.go, api/mocks/mock_full.go, api/proxy_gen.go, build/openrpc/full.json, build/openrpc/gateway.json, build/openrpc/miner.json, build/openrpc/worker.json, chain/messagepool/messagepool.go, documentation/en/api-v1-unstable-methods.md, gateway/node.go, gateway/proxy_eth.go, itests/eth_transactions_test.go, itests/mempool_test.go, node/builder_chain.go, node/impl/full/dummy.go, node/impl/full/eth.go, node/impl/full/txhashmanager.go, node/modules/ethmodule.go
Also improves the test coverage for `MpoolPush*` variants.
=> feat(eth): add EthSendRawTransactionUntrusted, use via gateway eth_sendRawTransaction

.github/workflows/test.yml
Uses https://github.com/filecoin-project/filecoin-ffi/pull/480
Needs a release tag though I think. Will leave that up to you @rjan90
=> chore(deps): use new FFI_PORTABLE flag for filecoin-ffi builds

LOTUS_RELEASE_FLOW.md
Reported in https://filecoinproject.slack.com/archives/CP50PPW2X/p1726016827303709
Output now:
```
git tag -l 'v*' | grep -v "-" | sort -V -r | head -n 10
v1.29.0
v1.28.2
v1.28.1
v1.28.0
v1.27.2
v1.27.1
v1.27.0
v1.26.3
v1.26.2
v1.26.1
```
=> docs: fix command for getting latest release tag in LOTUS_RELEASE_FLOW

build/bootstrap/butterflynet.pi
https://github.com/filecoin-project/lotus-infra/issues/1598
Further to work done on the butterflynet infrastructure improvements, a dnsaddr link is created with up-to-date bootstrap node addresses whenever butterflynet is reset/spawn up. This means we no longer need to update the bootstrap addresses in lotus. Instead, we can simply use `/dnsaddr/bootstrap.butterfly.fildev.network`.
See:
- https://github.com/libp2p/specs/blob/master/addressing/README.md#dnsaddr-links
=> feat: use dnsaddr for butterflynet bootstrap addresses

chain/types/ethtypes/eth_types.go, chain/types/ethtypes/eth_types_test.go, itests/eth_hash_lookup_test.go
Very minor, but it bothers me each time I have to look at it so I may as well fix it.
`BenchmarkEthHashFromCid-32       5629081               216.2 ns/op`
vs
`BenchmarkEthHashFromCid-32      29226618                41.58 ns/op`
=> chore(eth): minor optimisation in EthHashFromCid

documentation/misc/RELEASE_ISSUE_TEMPLATE.md
The goal is to get rid of posts like https://github.com/filecoin-project/lotus/discussions/12187 because we're just linking to other sources of truth.
This allows the removal of the "Lotus announcement upgrade" rows in the network upgrade template: https://docs.google.com/document/d/1KKJj2COb0vIqAQh-4F7fflJjxiTgGrU9oT9B461nsgg/edit
=> docs: update release issue template with pointers to network upgrade info

chain/index/events.go, chain/index/indexer.go, chain/index/interface.go, node/modules/chainindex.go
For https://github.com/filecoin-project/lotus/issues/12453.
If we're unable to find events for a given receipt, we recompute the tipset to generate events and re-read the events true to enable auto-repair for events. This will work during reconciliation as well.
=> feat: recompute tipset to generate missing events if event indexing is enabled

CHANGELOG.md, go.mod, go.sum
fix https://github.com/filecoin-project/lotus/issues/12467 for master
=> deps: bls: downgrade bls library

build/openrpc/full.json, chain/index/api.go, chain/index/ddls.go, chain/index/gc.go, chain/index/indexer.go, chain/index/read.go, chain/index/reconcile.go, chain/types/index.go, itests/eth_filter_test.go
This PR is part of ChainIndexer tooling [PR](https://github.com/filecoin-project/lotus/pull/12450):
- It addresses the TODO's and comments
=> feat: chain indexer todos [skip changelog]

documentation/misc/RELEASE_ISSUE_TEMPLATE.md
This is for doing release process followups after executing https://github.com/filecoin-project/lotus/issues/12470
=> docs(release): v1.29.1 release template improvements

CHANGELOG.md, cmd/lotus-shed/indexes.go
This PR is a part of: https://github.com/filecoin-project/lotus/pull/12450
PR changes:
- Adds `lotus-shed indexes validate-chainindex` to inspect and backfill the chain indexer through `ChainValidateIndex` API.
=> feat: lotus-shed tooling for chain indexer

CHANGELOG.md, build/buildconstants/params_2k.go, build/buildconstants/params_butterfly.go, build/buildconstants/params_calibnet.go, build/buildconstants/params_interop.go, build/buildconstants/params_mainnet.go, build/buildconstants/params_testground.go, build/openrpc/full.json, chain/lf3/ec.go, chain/lf3/f3.go, chain/types/tipset_key.go, go.mod, go.sum, node/builder_chain.go
* Part of https://github.com/filecoin-project/go-f3/issues/603
* Depends on https://github.com/filecoin-project/go-f3/pull/642
Once a decision is received from F3, checkpoint it in chain-store. As part of checkpointing, refactor the F3 tipset wrapper to reduce type casting.
=> feat(f3): checkpoint tipsets that are finalized by F3

go.mod
* Fixes https://github.com/filecoin-project/lotus/issues/12472#issuecomment-2356977434
Now that F3 is upgraded remove explicit kilic replace directive.
=> chore: remove kilic replace directive

chain/index/ddls.go, chain/index/events.go, chain/index/gc.go, chain/index/reconcile.go
For https://github.com/filecoin-project/lotus/issues/12453
Some minor improvements to the query logic in the `ChainIndexer`.
=> feat: ChainIndexer: improve sqllite query handling

CHANGELOG.md
Followup from shipping the v1.28.2 and v1.29.1 patch releases.
- Cherry-pick the relevant commits that landed changelog entries v1.28.2 and the v1.29.1 releases.
- Cleanup changelog entries in Unreleased section that was included in the v1.28.2 and v1.29.1 releases.
=> chore(release): cherry-pick v1.28.2 and v1.29.1 changelog back to master

.github/workflows/check.yml
* Fixes #12498
`docsgen` make target is already a dependency of `gen` which has a CI check. We do not need to check `docsgen` separately for conformance.
=> chore: remove duplicate `docsgen` CI check

api/api_full.go, api/docgen/docgen.go, api/mocks/mock_full.go, api/proxy_gen.go, build/buildconstants/params_2k.go, build/buildconstants/params_butterfly.go, build/buildconstants/params_calibnet.go, build/buildconstants/params_interop.go, build/buildconstants/params_mainnet.go, build/buildconstants/params_testground.go, build/buildconstants/shared_funcs.go, build/openrpc/full.json, build/openrpc/gateway.json, build/openrpc/miner.json, build/openrpc/worker.json, chain/lf3/config.go, chain/lf3/f3.go, chain/lf3/manifest.go, documentation/en/api-v1-unstable-methods.md, itests/f3_test.go, itests/kit/node_opts.go, node/builder_chain.go, node/impl/full/f3.go, node/modules/lp2p/pubsub.go
Replaces #12204
Add integration tests for F3. This also changes the pubsub configuration logic such that the tests can be configured without changing global build variables.
=> test(f3): f3 integration tests

CHANGELOG.md, api/api_full.go, api/api_gateway.go, api/eth_aliases.go, api/mocks/mock_full.go, api/proxy_gen.go, build/openrpc/full.json, build/openrpc/gateway.json, build/openrpc/miner.json, build/openrpc/worker.json, chain/events/filter/event.go, documentation/en/api-v1-unstable-methods.md, gateway/node.go, gateway/proxy_eth.go, itests/eth_conformance_test.go, itests/eth_deploy_test.go, itests/eth_filter_test.go, itests/fevm_test.go, itests/specs/eth_openrpc.json, node/impl/full/dummy.go, node/impl/full/eth.go, node/impl/full/eth_utils.go
Fixes #12429  
Implimented `eth_getBlockReceipts` method which accepts a block number and returns all the transaction receipts for it
[QuickNode](https://www.quicknode.com/docs/ethereum/eth_getBlockReceipts)
[Infura](https://docs.infura.io/api/networks/blast/json-rpc-methods/eth_getblockreceipts)
=> feat: add support for eth_getBlockReceipts

.github/workflows/check.yml, Makefile
* https://github.com/filecoin-project/lotus/pull/11695
Lotus imports fixing was optimised to run as a go script for a faster turnaround. The changes here remove the leftover direct calls to `goimports` such that all imports are now fixed with the same script. This removes the need for installing `goimports` during CI workflows or in local development environment.
=> chore: remove build dependency to `goimports` cli

.github/actions/make-deps/action.yml, .github/workflows/check.yml
Over 90% of time running CI check gen is spent on `make deps`. Define a composite GitHub Action that caches the ffi dependencies and makes this reusable across other actions.
Note that the changes remove `make lotus` from the gen-check CI workflow since it is not required for `make gen` to execute.
=> chore: cache `make deps` when running CI checks

CHANGELOG.md, build/buildconstants/params_2k.go, build/buildconstants/params_butterfly.go, build/buildconstants/params_calibnet.go, build/buildconstants/params_interop.go, build/buildconstants/params_mainnet.go, build/buildconstants/params_shared_vals.go, build/buildconstants/params_testground.go, chain/lf3/config.go, itests/kit/node_opts.go, node/builder_chain.go
https://github.com/filecoin-project/go-f3/issues/596
This PR adds a build parameter specifying the initial power table cid.
This will be used post-bootstrap to hard-code the initial F3's initial power table CID. This will remain unset until F3 successfully bootstraps after which it'll be set to the CID of the committee used to create the first finality certificate.
Additionally, if and only if this CID is not already hard-coded, it can be specified by setting the `F3_INITIAL_POWERTABLE_CID` environment variable. That way users can specify it after the F3 bootstrap epoch without upgrading.
=> feat(f3): add a build parameter specifying F3's initial power table cid

CHANGELOG.md, go.mod, go.sum
chore: bump go-libp2p to v0.35.5
=> chore: bump go-libp2p to v0.35.5

cmd/lotus-shed/market.go
Doesn't work with current network version, slight variation in types since nv23. I was just looking at cron state and discovered the breakage.
=> chore: update market types for `lotus-shed market`

lib/sqlite/sqlite.go
Closes https://github.com/filecoin-project/lotus/issues/12489.
Related to https://github.com/filecoin-project/lotus/issues/12453.
=> feat: use sqliite defaults for page size and wal checkpointing in the ChainIndexer

itests/eth_deploy_test.go, itests/fevm_test.go, node/impl/full/eth.go, node/impl/full/eth_utils.go
Ref: https://github.com/filecoin-project/lotus/pull/12505
=> fix(eth): proper gas calculation for eth_getBlockReceipts

CHANGELOG.md, api/api_full.go, api/api_gateway.go, api/eth_aliases.go, api/mocks/mock_full.go, api/proxy_gen.go, build/openrpc/full.json, build/openrpc/gateway.json, build/openrpc/miner.json, build/openrpc/worker.json, chain/events/filter/event.go, documentation/en/api-v1-unstable-methods.md, gateway/node.go, gateway/proxy_eth.go, itests/eth_conformance_test.go, itests/eth_deploy_test.go, itests/eth_filter_test.go, itests/fevm_test.go, itests/specs/eth_openrpc.json, node/impl/full/dummy.go, node/impl/full/eth.go, node/impl/full/eth_utils.go
Closes https://github.com/filecoin-project/lotus/issues/12429.
This is a port over of the work done by @virajbhartiya at https://github.com/filecoin-project/lotus/pull/12478.
Just adding in the last bit and taking it to completion here as we need it for the upcoming Lotus release.
=> feat: eth_getBlockReceipts API implementation

CHANGELOG.md, api/api_full.go, build/openrpc/full.json, chain/beacon/mock.go, chain/gen/genesis/miners.go, chain/rand/rand.go, chain/stmgr/stmgr.go, chain/store/store.go, conformance/rand_fixed.go, conformance/rand_record.go, conformance/rand_replay.go, documentation/en/api-v1-unstable-methods.md, node/impl/full/state.go, node/impl/full/state_test.go
Fixes: https://github.com/filecoin-project/lotus/issues/12414
Previously StateGetBeaconEntry would always try and use a drand beacon to get the appropriate round. But as drand has shut down old beacons and we've removed client details from Lotus, it has stopped working for historical beacons.
This fix restores historical beacon entries by using the on-chain lookup, however it now follows the rules used by StateGetRandomnessFromBeacon and the get_beacon_randomness syscall which has some quirks with null rounds prior to nv14. See https://github.com/filecoin-project/lotus/issues/12414#issuecomment-2320034935 for specifics.
StateGetBeaconEntry still blocks for future epochs and uses live drand beacon clients to wait for and fetch rounds as they are available.
---
Notes for review: the …
=> fix(drand): `StateGetBeaconEntry` uses chain beacons for historical epochs

CHANGELOG.md, build/bootstrap/calibnet.pi
- add calibnet archival bootnode endpoint
=> chore(chainsafe): add calibnet archival bootnode endpoint

chain/lf3/f3.go
https://github.com/filecoin-project/lotus/pull/12522#issuecomment-2379844204
The lifecycle logic got updated along the way but neither the docs nor the logic in lotus got updated to match. This patch correctly stops F3 on exit (and waits for it to shutdown completely).
Also see https://github.com/filecoin-project/go-f3/pull/672
=> fix(f3): correctly start/stop f3

itests/f3_test.go, itests/kit/node_opts.go
Failed test run https://github.com/filecoin-project/lotus/actions/runs/11046427121/job/30685760550?pr=12505
1. Reduce GPBFT delta to blockdelay/5 to match the expected mainnet config and avoid timing out tests.
2. Make waiting for rebootstrap work in the presence of null tipsets.
=> test(f3): fix test flakes

CHANGELOG.md, itests/fevm_test.go, node/impl/full/eth.go
Fixes #10357 
1. Added a condition to check for the "pending" block parameter.
2. Implemented mempool nonce retrieval for "pending" blocks.
3. Included error handling for the mempool query.
4. Ensured the mempool is only accessed when necessary (i.e., for "pending" blocks).
=> feat(eth): fix EthGetTransactionCount for pending block parameter

go.mod, go.sum
Just released. https://github.com/ipfs/go-ipld-cbor/releases/tag/v0.2.0
There's a fix for `BasicIpldStore` in here that may touch us, I'm interested to see if it has any impact: https://github.com/ipfs/go-ipld-cbor/pull/96
=> chore(deps): upgrade go-ipld-cbor

itests/eth_transactions_test.go
Flaky reported multiple times in https://github.com/filecoin-project/lotus/issues/12001 and we need some hints on why it's showing up as 4 traces instead of 3 sometimes.
Also fix the assertions while I'm in there.
=> chore(eth): add some debugging to TestTraceFilter

chain/types/ethtypes/eth_types.go, chain/types/ethtypes/eth_types_test.go, itests/fevm_test.go
Closes https://github.com/filecoin-project/lotus/issues/12530 AND https://github.com/filecoin-project/lotus/issues/12536.
Tested on a local node as well:
```
curl --location --request POST 'http://localhost:1234/rpc/v1' --header 'Content-Type: application/json' --data-raw '{ "jsonrpc":"2.0","method":"eth_getBlockReceipts","params":["0xc6b5584814d4872c4050c725fa2bdc2b1d23e8d63ae10db6ce7e6aeef5f4623d"],"id":1}'
{"id":1,"jsonrpc":"2.0","result":[]}
```
```
curl --location --request POST 'http://localhost:1234/rpc/v1' --header 'Content-Type: application/json' --data-raw '{ "jsonrpc":"2.0","method":"eth_getBlockReceipts","params":["0xdc7c0197634c7c03adf6c3b44559009bc81278269183e97be4974b65c6425ccf"],"id":1}'
{"error":{"code":1,"message":"failed to get tipset: cannot get tipset by hash: cannot …
```
=> fix: eth_getBlockReceipts should work similarly as geth

CHANGELOG.md, go.mod, go.sum
Update go-multiaddr-dns to v0.4.0
=> chore: bump go-multiaddr-dns to v0.4.0

cmd/lotus/daemon.go, lib/httpreader/resumable.go
While testing snapshot imports from a cold-start
```
lotus daemon --remove-existing-chain=true --import-snapshot https://forest-archive.chainsafe.dev/latest/calibnet
```
I encountered the process aborting with an unexpected
```
...
2024-10-02T12:10:57.487+0200	INFO	badgerbs	v2@v2.2007.4/levels.go:1010	[Compactor: 0] Compaction for level: 1 DONE
4.38 GiB / 4.38 GiB [----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------] 100.00% 24.52 MiB p/s 3m3s
2024-10-02T12:11:09.056+0200	WARN	chainstore	store/store.go:670	reorgWorker quit
2024-10-02T12:11:09.058+0200	INFO …
```
=> fix: daemon: ensure imports are unaffected by remote-EOF

CHANGELOG.md
https://github.com/filecoin-project/lotus/issues/12464
Cherry-pick the v1.29.2 changelog back to master, and remove entries from unreleased section that was published in the v1.29.2 release.
=> chore(release): cherry-pick v1.29.2 changelog back to master

CHANGELOG.md, itests/fevm_test.go, node/impl/full/eth.go
#12543
Update `TestEthGetTransactionCount` to test for `earliest`, `pending`, and `finalized` and refactor `EthGetTransactionCount` to return an empty block for `earliest`.
=> feat: update EthGetTransactionCount test for earliest, latest, and `pending` block parameters

CONTRIBUTING.md, documentation/misc/Builtin-actors_Development.md
Ref: https://github.com/filecoin-project/builtin-actors/issues/1567
@rjan90 @BigLep I started banging this out as I was closing out 0081 and preparing a fresh branch based on these instructions for @snissn to get him started on MCOPY. I'll finish off the "Builtin-actors-only changes" section tomorrow, along with the MCOPY starter branch, unless something else more urgent comes up. The other sections can remain TODO until later, although the state migration one probably isn't too hard, now that I've done it for 0081; but it can be done separately.
=> docs(actors): builtin-actors development docs

chain/lf3/config.go, chain/lf3/manifest.go, go.mod, go.sum, itests/f3_test.go, itests/kit/node_opts.go, node/builder_chain.go, node/modules/lp2p/pubsub.go
fixes [#596](https://github.com/filecoin-project/go-f3/issues/596)
This patch:
1. Bootstraps F3 when we hit the `F3BootstrapEpoch` (when non-negative).
2. Refuses any/all dynamic manifests once we get within one finality of said epoch.
3. Sets the F3 network name for mainnet to "filecoin".
=> feat(f3): prepare for f3 bootstrap

CHANGELOG.md, cmd/lotus-shed/indexes.go
This was left undone as part of the original fix for unique event indexes and shows up as a bug (e.g. "duplicate logIndex" for ETH APIs) where backfilling is involved.
I think this might also be implicated in the duplicate-events bugs we are seeing because we use the index in the "exists" check.
Ref: https://github.com/filecoin-project/lotus/pull/11952
Ref: https://github.com/filecoin-project/lotus/issues/12549
=> fix(events): event index unique for tipset during backfill

cmd/lotus-shed/migrations.go
When running the invariant check after running a bench migration (`./lotus-shed migrate-state --check-invariants=true ..`) it failed with:
```
main.checkNv24Invariants
/home/filoz/lotus/cmd/lotus-shed/migrations.go:649
- unexpected actor code CID bafk2bzaceabq3zagn4ee2wbagarxf7xgbrqgqgm55xydanxik2bifztqgynts for address t094151:
```
This is because the `checkNv24Invariants` was wrongly set to Version 14 actors.
This PR updates `actors.GetActorCodeIDs` to Version 15 in the `checkNv24Invariants` function.
=> fix: update actor code ID in lotus-shed invariant check

build/buildconstants/params_2k.go, build/buildconstants/params_2k_test.go, build/buildconstants/params_butterfly_test.go, build/buildconstants/params_calibnet_test.go, build/buildconstants/params_interop_test.go, build/buildconstants/params_mainnet_test.go, build/buildconstants/params_testground.go, build/buildconstants/params_testground_test.go
* https://github.com/filecoin-project/go-address/commit/e08728680fb
Default `address.CurrentNetwork` was changed in an upstream dependency. Update the build constants for non-mainnet to explicitly set it to `Testnet`.
Add tests to assert it.
=> fix: set address current network for non-mainnet since default is changed

build/buildconstants/params_calibnet.go
Set the Calibration nv24 upgrade epoch and the F3BootstrapEpoch, as outlined by: https://github.com/filecoin-project/community/discussions/74#discussioncomment-10881951
=> chore: set Calibration upgrade epoch for nv24

CHANGELOG.md, itests/f3_test.go, node/modules/storageminer.go
Due to a bug in the `awaitLeaseExpiry`, we would retry immediately, which then would cause a hot loop.
Fix the bug and add a bit of hot-loop protection.
=> fix(f3): fix hot loop in F3 participation

node/modules/storageminer.go
1. Change Restarting -> Renewing. Restarting sounds like something is going wrong.
2. Fix spelling of rechecking.
=> fix(f3): improve log messages

api/api_full.go, chain/lf3/participation_lease.go, node/modules/storageminer.go
1. Add a `ToInstance()` to the lease so we can stop repeating code.
2. Use it to correctly log the number of remaining instances.
=> fix(f3): log the correct number of instances remaining

chain/lf3/participation_lease.go
Log whenever we start/stop participating for a storage miner in F3. Given that we use overlapping leases, we expect that we'll start participating for a miner on start then continue to participate over time.
This could get a bit noisy for setups that constantly switch between different lotus nodes but there's not much I can do about that and this will really help with debugging.
=> feat(f3): log when gaining/losing participation leases

chain/events/filter/event.go, node/impl/full/actor_events.go, node/impl/full/actor_events_test.go, node/impl/full/eth.go
After reviewing https://github.com/filecoin-project/lotus/pull/12585 I realised the remaining problem was this:
* subscribe-type calls always wants future reverts but only historical reverts when a tipset is specified
* get-type calls only want reverts when a tipset is specified
But we only have one "excludeReverted" argument to `Install()`. My first go at this was changing that argument to `subscribe` and using that to differentiate the behaviour and doing the `tipsetKeyCid == cid.Undef` check just for `prefillFilter`. But then I realised that for the non-subscribe calls we only ever install+remove the filter immediately, so the logic is kind of unnecessary if we just introduce a second method to deal with that case.
So now we have a `Fill()` in addition to an `Install()`, with the …
=> fix(events): handle subscribe and get/fill cases separately

CHANGELOG.md, chain/events/filter/event.go, node/impl/full/actor_events.go, node/impl/full/actor_events_test.go, node/impl/full/eth.go
For https://github.com/filecoin-project/lotus/issues/12584.
-Event APIs should only returns reverted events if client has queries by block hash rather than epoch.
- The Subscribe API should always return reverted events for an accurate observation of real time changes.
=> feat: improve semantics for returning reverted events to event API users

node/modules/storageminer.go
In _theory_ a lotus node can return no manifest from `F3Manifest`. I don't think that happens in practice but we should handle the case and start over at the top (try to get another lease). If we really have no manifest, lotus will tell us that F3 isn't ready yet and we'll backoff for a bit.
=> fix(f3): handle a case where we might receive no manifest

node/modules/storageminer.go
I expect this may help with some of the flaky tests as those may have been timing out because we weren't renewing the lease fast enough.
https://github.com/filecoin-project/lotus/issues/12519
1. Instead of hard-coding the renewal to be within 2 instances of the end of the lease, specify the renewal to be within 1/2th of the end of the lease, rounded up (towards the end of the lease).
2. Instead of hard-coding the lease check interval to be 10s (problematic for tests where the block time is 100ms), set it to be the minimum amount of time we expect to have to wait for the remaining
instances to complete.
I've configured a hard-coded minimum of renewing the lease once every 100ms in case a manifest doesn't have a configured catch-up alignment interval, but I don't expect us to hit that in …
=> feat(f3): remove lease-check interval constants

chain/lf3/f3.go, chain/lf3/participation_lease.go
Send the last gpbft message for each new participant.
Otherwise, we can get into a situation where everyone is waiting for the next round to participate, but we'll never get there because not enough participants acted in the current round.
=> fix(f3): send the last gpbft message for each new participant

chain/events/filter/event.go
Patches a bug introduced earlier in https://github.com/filecoin-project/lotus/pull/12586.
=> fix: bug in exclude reverted logic for eth_getLogs

build/buildconstants/params_mainnet.go
Default address.CurrentNetwork was changed to mainnet. As a result if `LOTUS_USE_TEST_ADDRESSES` is set we need to explicitly use testnet address.
=> fix: fix address network override via env var

chain/lf3/participation.go, itests/f3_test.go, node/modules/storageminer.go
Refactor the F3 participation module for easier testing:
1. Move it next to all the F3 code.
2. Make it look more like a "service" so I won't have to duplicate the
start/stop code in the itests.
3. Rename participator to participant. Not perfect, but it's a word.
4. Make all the constants public.
5. Only depend on the parts of the API we need (will help with unit testing).
=> feat(f3): refactor the F3 participation module for easier testing

chain/lf3/participation.go
Don't return an error on stop if our context was canceled. Otherwise, the node's `stop` function returns an error and the splitstore and window post dispute tests randomly fail.
=> fix(f3): don't return an error on stop if our context was canceled

CHANGELOG.md, cmd/lotus-shed/sectors.go
The `termination-estimate` CLI command fails to function correctly under specific conditions:
- When the owner address is a delegated address (F4 address), the existing code cannot send the Termination State Call.
- This results in the `termination-estimate` command not working for miners with delegated owner addresses.
- Added a check to determine if the owner's address is delegated.
- If the owner's address is delegated, the code now uses the worker address to make the State Call.
- This modification allows the `termination-estimate` command to function correctly for miners with delegated owner addresses.
- Scenario: Miner's owner address is not delegated
- Miner Address: f01083914
- Account overview (From filfox)
- Output of command `lotus state active-sectors f01083914` (Last 5 …
=> refactor(shed): improve termination-estimate CLI for delegated owner addresses

node/impl/full/state.go
Regression introduced by refactoring in https://github.com/filecoin-project/lotus/pull/12384 where the NV16 special case was missed and the full sector weight calculation was applied. The lack of this special case essentially reverts FIP-0034 for this API, but not for actors which would have a different PCD calculation.
--
Not doing a CHANGELOG for this one because #12384 hasn't got to a final release yet.
Also haven't included a test here, even though I'd love to, because I don't have time to figure out how on earth to pull that off. But thanks to @LesnyRumcajs for pointing out the bug due to the Forest compatibility tests where this request:
```
curl -s -X POST -H "Content-Type: application/json" --data '{"method":"Filecoin.StateMinerPreCommitDepositForPower","params":["f0138097",{"DealI …
```
=> fix(miner): fix new bug in StateMinerPreCommitDepositForPower calculation

CHANGELOG.md, cli/chain.go, documentation/en/cli-lotus.md
A simpler version of what's currently possible with:
lotus chain list --format '<height>' --count 1
=> feat(cli): lotus chain head --height to print epoch number

documentation/en/default-lotus-config.toml, node/config/def.go, node/config/doc_gen.go, node/config/types.go, node/modules/actorevent.go
This one's always felt awkward to me and IMO is confusing to describe, so let's just remove it while we're simplifying options.
=> chore(events): remove unnecessary DisableRealTimeFilterAPI

cmd/lotus-shed/chain_index.go
Comes from working through what a cron job would look like to do this regularly
* `--quiet`
* non-zero exit code on failures
* some cleanups targeting --help output
=> feat(cli): add --quiet to chainindex validate-backfill + cleanups

CHANGELOG.md, cmd/lotus-shed/indexes.go
Instead of relying just on entry counts, compare the regenerated AMT root using just what we have in the db with the message receipt event root. This should tell us precisely that we have what we should or not.
Ref: https://github.com/filecoin-project/lotus/issues/12570
--
I mainly just wanted to see if this was practical for the discussion in #12570, and it seems to be. The only problem is address lookup. Some of my tipsets don't resolve f410 addresses. I get back 1,500 tipsets, to epoch 4339494 and get a `actor not found` error so I'm not sure what to do about that. I've turned that into a "problem" rather than an error and left a TODO to figure out if it can be resolved. I assumed that we could get this mapping at the tipset, but I obviously don't understand something about addresses. …
=> feat(events): compare-amt option for lotus-shed indexes inspect-events

CHANGELOG.md, api/api_full.go, api/mocks/mock_full.go, api/proxy_gen.go, build/openrpc/full.json, build/openrpc/gateway.json, build/openrpc/miner.json, build/openrpc/worker.json, chain/lf3/f3.go, chain/lf3/participation_lease.go, chain/lf3/participation_lease_test.go, documentation/en/api-v1-unstable-methods.md, itests/f3_test.go, node/impl/full/f3.go
Part of #12607 
Implement Lotus API to list the current miner IDs that are participating.
=> feat: implement F3 list participants API

.github/workflows/pr-title-check.yml
These are 3 I've been caught by, I think they're reasonable. Sometimes I want to start with an upper-case because I'm describing a type name, e.g. ChainIndexer, but we also want to discourage general upper-case for prose, so these also help that situation, you can quote it.
=> chore(ci): allow ', ", ` characters to prefix commit description

chain/index/events.go
Can't backfill from snapshot without doing this earlier, snapshots don't have receipts either.
=> fix(chainindex): recompute tipset when we find no receipts

chain/index/api.go, cmd/lotus-shed/chain_index.go
For https://github.com/filecoin-project/lotus/pull/12421#discussion_r1805860944 AND https://filecoinproject.slack.com/archives/CP50PPW2X/p1729486344066509?thread_ts=1729485320.287299&cid=CP50PPW2X
**_Tested it on a calibnet node:_**
=> fix(chainindexer): backfilling should halt when chain state data is missing and not backfill parents

build/params_shared_funcs.go
Accept any of "", "0", "false", "no" as negative value for `LOTUS_DISABLE_F3` in which case F3 should remain enabled.
=> fix: handle negative value for `LOTUS_DISABLE_F3` env var gracefully

build/buildconstants/params_2k.go, build/buildconstants/params_butterfly.go, build/buildconstants/params_calibnet.go, build/buildconstants/params_interop.go, build/buildconstants/params_mainnet.go, build/buildconstants/params_testground.go
* Relates to: https://github.com/filecoin-project/lotus/pull/12547
Upgrade to `go-f3` `v0.4.0` removed the option to disable checkpointing by F3. As a result this build parameter no longer has any effect. Remove it.
=> chore: remove redundant `F3Consensus` build parameter

CHANGELOG.md, cli/clicommands/cmd.go, cli/f3.go, documentation/en/cli-lotus.md
* Part of #12607
Implement `lotus f3` CLI sub commands:
* `manifest` to dump the current F3 manifest in either JSON or text.
* `list-miners` to list the current F3 participants.
* `status` to print summary status of F3.
=> feat: implement Lotus F3 CLI commands for general diagnostics

chain/lf3/f3.go, cli/f3.go, node/impl/full/f3.go
This will make it easier to tell users how to set/verify `F3_INITIAL_POWERTABLE_CID`.
Display the initial power table CID in the `lotus f3 manifest` command output, and make sure it's set if available.
=> feat(f3): display the initial power table CID in the F3 manifest

node/impl/full/gas.go
Noticing this being unnecessarily noisy when running some fevm contact integration tests that make use of gas inspection. Maybe it was interesting once upon a time, but it seems like it's debug-worthy to me.
=> chore(logging): downgrade GasEstimateMessageGas info log to debug

chain/index/api.go, chain/index/api_test.go, chain/index/ddls.go, chain/index/ddls_test.go, chain/index/indexer.go
Closes https://github.com/filecoin-project/lotus/issues/12570 AND https://github.com/filecoin-project/lotus/issues/12594.
=> feat(chainindex): compare events AMT root between Index and chain state for validation

chain/lf3/participation.go, chain/lf3/participation_test.go
Try again when we fail to fetch the manifest (reported via Antithesis). Continuing with the function here will lead to a panic. This can happen, e.g., if the lotus node stops and/or returns an error while the participant is waiting for its lease to expire.
=> fix(f3): try again when we fail to fetch the manifest

documentation/misc/Building_a_network_skeleton.md
Updates Docs to include the reference to the PRs to the latest network skeleton upgrade (24). 
cc @rjan90
Also there were two Filecoin-FFI section, so I removed one of those, lmk if I'm wrong.
=> chore: update network skeleton docs

api/api_errors.go, itests/f3_test.go
* Fixes #12630
Fix the issue by instantiating pointers to sentinel F3 error values and assert that errors indeed pass through via an integration test.
=> fix: fix F3 JSON RPC error pass through across API boundary

CHANGELOG.md, cli/f3.go, cli/templates/f3_finality_cert.go.tmpl, cli/templates/f3_manifest.go.tmpl, documentation/en/cli-lotus.md
* Part of #12607
Implement `lotus f3` CLI sub commands to:
* Get a specific finality certificate, either latest or by instance ID.
* List a range of finality certificates
=> feat: implement Lotus F3 CLI finality cert get and list

CHANGELOG.md, chain/lf3/participation.go, chain/lf3/participation_lease.go, chain/lf3/participation_lease_test.go, chain/lf3/participation_test.go
https://github.com/filecoin-project/go-f3/issues/719
Previously, the flow was:
1. Get ticket.
2. Participate.
3. Repeatedly poll progress.
The new flow is:
1. Get ticket.
2. Repeatedly participate, using the returned lease as an indicator of progress.
That way, if the lotus node reboots we'll eventually re-tell them about the lease.
I _think_ this works, but I still need to go through it again and do more testing. I also really want to simplify our error handling a bit here.
We'll also be able to simplify this even more once we can get rid of the dynamic manifest stuff.
=> fix(f3): poll the lease by repeatedly participating instead of checking progress

itests/eth_conformance_test.go
https://github.com/filecoin-project/lotus/pull/12618
Fix execution/inclusion off-by-one in the eth conformance tests.
StateSearchMsg returns the tipset in which the message was executed to make it easier to get receipts, the state root, etc. But the ETH API cares about the inclusion tipset.
=> test(eth): fix execution/inclusion off-by-one

CHANGELOG.md, api/api_full.go, api/api_gateway.go, api/mocks/mock_full.go, api/proxy_gen.go, build/openrpc/full.json, build/openrpc/gateway.json, gateway/node.go, gateway/proxy_eth.go, itests/eth_api_test.go, itests/eth_block_hash_test.go, itests/eth_deploy_test.go, itests/eth_transactions_test.go, itests/fevm_test.go, node/impl/full/dummy.go, node/impl/full/eth.go
This reverts commit c6745545041939b97962e376ee2593609bb3d5b5.
Discussion in https://github.com/filecoin-project/lotus/issues/12633 about the subtleties of dealing with this problem - returning nil or an error. This could be an unfixable wac-a-mole, but the fact that we had a complaint pretty quickly on an RC for just this API shows that we need to tread more cautiously.
=> Revert "feat: fix GetBlock for null rounds by returning nil (#12529)"

build/buildconstants/params_calibnet.go
From archioz:
```
> lotus f3 manifest
Manifest:
Protocol Version:     4
Paused:               false
Initial Instance:     0
Initial Power Table:  bafy2bzaceab236vmmb3n4q4tkvua2n4dphcbzzxerxuey3mot4g3cov5j3r2c
Bootstrap Epoch:      2081674
Network Name:         calibrationnet
Ignore EC Power:      false
Committee Lookback:   10
Catch Up Alignment:   15s
```
=> chore(f3): set F3InitialPowerTableCID in calibnet

chain/store/store.go
fixes https://github.com/filecoin-project/go-f3/issues/717
1. Optimize finding ancestors.
2. Allow setting checkpoints arbitrarily far in the past.
3. Forbid setting checkpoints, even future/current checkpoints, that would revert more than 900
epochs of the current chain.
=> feat(chain): rework checkpoint logic to better handle finality

cli/templates/f3_manifest.go.tmpl
(Came across this while implementing https://github.com/ChainSafe/forest/pull/4937)
`RebroadcastBackoffExponent` seems to be dropped in `lotus f3 manifest` output. 
Print `GPBFT Rebroadcast Backoff Exponent: 1.3` line in `lotus f3 manifest` output
Output with the change
```
➜  lotus git:(master) ✗ ./lotus f3 manifest
Manifest:
Protocol Version:     4
Paused:               false
Initial Instance:     0
Initial Power Table:  bafy2bzaceab236vmmb3n4q4tkvua2n4dphcbzzxerxuey3mot4g3cov5j3r2c
Bootstrap Epoch:      2081674
Network Name:         calibrationnet
Ignore EC Power:      false
Committee Lookback:   10
Catch Up Alignment:   15s
GPBFT Delta:                        6s
GPBFT Delta BackOff Exponent:       2
GPBFT Max Lookahead Rounds:         5
GPBFT Rebroadcast Backoff Base:     6s
GPBFT …
```
=> [skip changelog] fix(cli): print RebroadcastBackoffExponent in lotus f3 manifest

chain/gen/gen.go, chain/store/checkpoint_test.go
tests for #12650
Test checkpoints beyond finality. Specifically, ensure:
1. We can checkpoint before finality.
2. We cannot fork more than finality epochs.
I had to add a bit of a hack to the chain-gen logic to optionally prevent time (state) from moving forwards. Otherwise, we'd lose all power and actually providing window posts was going to be too much trouble.
=> test(chain): test forking before/after finality

chain/index/api.go, chain/index/helpers.go, chain/index/indexer.go
Retry transaction if database connection is lost.
=> fix(chainindex): retry transaction if database connection is lost

go.mod, go.sum
https://github.com/filecoin-project/lotus/pull/12602#discussion_r1801660075
Update poseidon to the released version. Same commit but it has now been tagged.
=> chore(deps): update poseidon to the released version

cmd/lotus-miner/init.go
=> fix(miner): use the "from" address as the sender if it is set 

build/buildconstants/params_mainnet.go
- Sets UpgradeTuktukHeight to epoch 4461240. This should be equivalent to:
- 23:00 in London
- 15:00 in Los Angeles
- 07:00 in Beijing (NB: 2024-11-21 in CST)
- Sets F3BootstrapEpoch to epoch 4501560. This should be equivalent to:
- 23:00 in London
- 15:00 in Los Angeles
- 07:00 in Beijing (NB: 2024-12-05 in CST)
Slack conversation: [link](https://filecoinproject.slack.com/archives/C05P37R9KQD/p1730128669893169)
=> chore: set Mainnet upgrade epoch for NV24

CHANGELOG.md, api/api_errors.go, itests/eth_fee_history_test.go, itests/fevm_test.go, node/impl/full/eth.go, node/impl/full/eth_utils.go
Fixes [#12633](https://github.com/filecoin-project/lotus/issues/12633)
=> feat: return an error for null rounds from RPC methods

CHANGELOG.md, cli/util/api.go, itests/merged_api_test.go
We apparently have a way to specify that all "related" requests should go to the same node. However:
1. It didn't work at all. All future requests would go to the first successful node from the first request. Because that's how stack variables work.
2. It was racy if the context was re-used concurrently. But only the first time, see point 1.
Use an atomic, get rid of a few of the odd decisions, and write a test.
=> fix(api): make stick sessions actually work and make them non-racy

chain/lf3/participation_lease.go, chain/lf3/participation_lease_test.go
Otherwise the early renew logic will never trigger.
=> fix(f3): when returning a partially used lease, trim its ValidityTerm

cli/f3.go, documentation/en/cli-lotus.md
Addresses https://github.com/filecoin-project/lotus/pull/12627#discussion_r1815426539
* When no range is given, default limit to 10
* Otherwise default to unlimited.
This is better than the current default of always unlimited because:
* there are a lot of certs, and
* when range is given the chances are the user wants all of them.
=> chore: conditionally change the limit of F3 certs listed via CLI

CHANGELOG.md, chain/index/events.go
(This PR is against https://github.com/filecoin-project/lotus/pull/12421 until it's merged)
In ChainIndexer and the existing master version of this same code, we do an `ORDER BY` when querying for events but then we do a `slices.Sort` on the output, only sorting by epoch.
1. The sort is not stable, so it can end up with events jumbled up even if the epoch is properly sorted
2. We're not making use of the `ORDER BY`, in fact we do the reverse of what we ask for, so we should just do it there
3. The existing `ORDER BY` relies on insertion order (`_rowid_`) of the event entries, which should mostly be fine (aside from reverts perhaps), but we have `event_index` that we use for `logIndex` on Eth output and we're not making use of that or properly ordering by it.
Here's a list of eth events …
=> fix(events): order events consistently when querying

build/params_shared_funcs.go, chain/lf3/manifest.go
using `LOTUS_DISABLE_F3_PASSIVE_TESTING=1`
=> feat(f3): allow to disable f3 passive testing

.github/workflows/build.yml, .github/workflows/check.yml, .github/workflows/docker.yml, .github/workflows/release.yml, .github/workflows/test.yml
By default the github checkout action fetches with depth 0 and no tags. By explicitly specifying depth 0, we'll get the tags. No, specifying `fetch-tags` doesn't work because that only applies to the root repo, not the submodules.
We need submoule tags to be able to fetch the pre-built FFI.
=> fix(ci): fetch tags

.github/workflows/build.yml, .github/workflows/check.yml, .github/workflows/docker.yml, .github/workflows/release.yml, .github/workflows/test.yml, CHANGELOG.md, build/openrpc/full.json, build/openrpc/gateway.json, build/openrpc/miner.json, build/openrpc/worker.json, build/version.go, documentation/en/cli-lotus-miner.md, documentation/en/cli-lotus-worker.md, documentation/en/cli-lotus.md
Update changelog and versions for v1.30.0.
Opened the same changes https://github.com/filecoin-project/lotus/pull/12677, but for some reason that never created the draft releases automatically
=> build: release Lotus node|miner v1.30.0 

cli/clicommands/cmd.go, cli/index.go, cmd/lotus-shed/main.go, documentation/en/cli-lotus.md
Closes #12654 
Shift the chainindex command from lotus-shed into lotus-cli
=> feat(cli): shift chainindex validate-backfill command

api/api_errors.go, itests/fevm_test.go, node/impl/full/eth.go, node/impl/full/eth_utils.go
decode the cbor return value for reverts and present that, as is expected by Ethereum tooling
=> fix(eth): present revert "data" as plain bytes

CHANGELOG.md, cmd/lotus-shed/datastore.go, cmd/lotus-shed/shedgen/cbor_gen.go, cmd/lotus-shed/shedgen/datastore.go, gen/main.go
Needed to fix the powerstore on calibnet.
Add commands for importing/exporting datastore snapshots. This makes it possible to import/export arbitrary datastore snapshots.
=> feat(shed): add commands for importing/exporting datastore snapshots

chain/store/snapshot.go, go.mod
We're using uber's atomic instead of the builtin one in our snapshot logic. We probably used uber's by mistake. It comes into our dependency tree via go-ipld-blockstore and will leave via https://github.com/filecoin-project/filecoin-ffi/pull/497.
Switch to the builtin atomic package.
=> chore(deps): switch to the stdlib atomic package in snapshot code

CHANGELOG.md, miner/miner.go
Orginal PR https://github.com/filecoin-project/lotus/pull/12659 
This PR extracts only miner changes as #12659 also makes changes in sync which require more
development and testing.
=> fix(miner): ignore lastWork when selecting the best mining candidate

cmd/lotus-shed/datastore.go
* Use consistent pattern to pick `namespace`: the cleaned datastore key vs. direct user input. This way `metadata` for example would work consistently. Otherwise, `clear`, `export` and `import` wont work unless `/metadata` is specified.
* Fix minor bug on number of arguments required for `clear` command.
=> fix: fix minor bugs in lotus shed datastore subcommand

chain/lf3/participation.go
* Fixes #12688
To reduce log verbosity change the log level for message indicating that F3 is not ready for participation yet. Because, the participation logic will reattempt after some backoff and these logs may at times become too verbose.
=> chore: use DEBUG level log when F3 is not ready for participation

itests/eth_api_test.go
Noticed as flaky: https://github.com/filecoin-project/lotus/actions/runs/11851664737/job/33028556808 - that one's likely to do with null round accounting (lack thereof) but there's also the stable `head` problem that's not accounted for with the `"safe"` and `"finalized"` forms in this test.
=> fix(test): unflake TestEthBlockNumberAliases

CHANGELOG.md, itests/eth_transactions_test.go, node/impl/full/eth.go
This is a flaky test, occasionally a null round slips in during one of the calls to `EthTraceFilter` and it fails during tipset lookup, but it should just skip over it.
The test now fails reliably without the change in eth.go.
=> fix(eth): make trace_filter resilient to null rounds

documentation/en/default-lotus-config.toml, node/builder_chain.go, node/config/doc_gen.go, node/config/types.go
Feedback already suggesting that our lack of automagic config switching is leading to some confusion. I'd still rather avoid automatically turning on ChainIndexer in these cases so we'll try with more clear error messages and see if we continue to get reports.
=> docs(indexer): more clarity for ChainIndexer configuration setup

CHANGELOG.md, cli/f3.go, documentation/en/cli-lotus.md
Implement utility CLIs to:
* get the power table used by F3 at a given instance ID.
* get total proportional power of a list of actors at a given instance ID.
These utilities allow us to debug the exact participation power for an instance without having to manually calculate it or estimate it from the latest power.
=> feat: implement F3 CLI to list power table and proportional power at instance

CHANGELOG.md, chain/events/filter/event.go, chain/events/filter/event_test.go, node/modules/actorevent.go
Blocked until #12421 is merged and we can do this against master.
I started writing up a `good-first-issue` ticket for this but it eneded up being easier to write the code than describe what needed doing.
1. Cache address look-ups for the given tipset across filters
2. Run the filters in an errgroup
3. Removed the `bool` return argument and just use `address.Undef`, I believe there's no case where this is an acceptable value
Filters can be installed via `eth_newFilter`, `eth_subscribe` and `SubscribeActorEventsRaw`. All filters installed have `CollectEvents` run on them for each new tipset and revert. So this can get expensive if you're an RPC provider who allows users to install these things and watch for live events.
=> chore(events): improve perf for parallel event filter matching

CHANGELOG.md, chain/index/events.go, chain/index/events_test.go, chain/index/interface.go, node/impl/full/eth.go
#12636 
- Adds raw codec while filtering ethereum logs
- Error out if we hit max result 
=> fix: add max results error and default raw codec for eth_getLogs

CHANGELOG.md, chain/actors/builtin/builtin.go, chain/actors/builtin/builtin.go.template, chain/actors/builtin/market/actor.go.template, chain/actors/builtin/market/market.go, chain/actors/builtin/market/state.go.template, chain/actors/builtin/market/v0.go, chain/actors/builtin/market/v10.go, chain/actors/builtin/market/v11.go, chain/actors/builtin/market/v12.go, chain/actors/builtin/market/v13.go, chain/actors/builtin/market/v14.go, chain/actors/builtin/market/v15.go, chain/actors/builtin/market/v2.go, chain/actors/builtin/market/v3.go, chain/actors/builtin/market/v4.go, chain/actors/builtin/market/v5.go, chain/actors/builtin/market/v6.go, chain/actors/builtin/market/v7.go, chain/actors/builtin/market/v8.go, chain/actors/builtin/market/v9.go, chain/gen/genesis/miners.go, itests/migration_test.go, node/impl/full/state.go
Updates go-state-types and incorporates https://github.com/filecoin-project/go-state-types/pull/308 which removes "deal weight" entirely from QAP calculation since it's unnecessary. So, we inherit a signature change here for `QAPowerForWeight` which drops the deal weight argument.
This is on top of https://github.com/filecoin-project/lotus/pull/12384 because it touches pledge calculation too. I'll leave this as draft until that merges. We also don't have a tagged gst with this change, and it might be best to leave this commit until @rjan90 cuts a second prerelease and pulls that in for nv24.
=> chore(deps): update go-state-types, adapt to QAP API changes

CHANGELOG.md, chain/index/read.go, chain/index/read_test.go
Closes #12674
GetMsgInfo returns an ErrNotFound when there are no rows.
=> fix: getMsgInfo returns an ErrNotFound when there are no rows

cmd/lotus-shed/sectors.go, cmd/lotus-shed/state-stats.go
Most of the fields in SectorOnChainInfo for _all_ of the records on chain (using the power actor to list miners and then listing all of their sectors). No filtering so far, output as CSV. Currently doesn't print the two CIDs. This came up as part of the FIP-0096 (or whatever number this will get https://github.com/filecoin-project/FIPs/pull/1079) discussions looking at termination fees and I wanted to collect some data for it.
=> feat(shed): lotus-shed sectors dump-sectors

itests/eth_block_hash_test.go
Weird flaky @ https://github.com/filecoin-project/lotus/actions/runs/11946318402/job/33300471579?pr=12680 - The calculated gas limit doesn't match the block's gas limit. I mainly wanted to add a little bit of output for that assertion but found some other minor cleanups while in there.
=> chore(test): minor cleanup and debugging output for TestEthBlockHashesCorrect_MultiBlockTipset

cmd/lotus-shed/balances.go, itests/migration_test.go
```
lotus-shed audits fip0081-pledge
```
```
Calculating at epoch 4462564
Sector Size | Verified % | Duration  | Actual                   | Pre-FIP-0081             | Difference
---------------------------------------------------------------------------------------------------------
2KiB        |  100%      | 1 year(s) | 0.000000082694866747 FIL | 0.000000082694866747 FIL | 0
2KiB        |   50%      | 1 year(s) | 0.000000045482176711 FIL | 0.000000045482176711 FIL | 0
2KiB        |    0%      | 1 year(s) | 0.000000008269486673 FIL | 0.000000008269486673 FIL | 0
2KiB        |  100%      | 3 year(s) | 0.000000082694866747 FIL | 0.000000082694866747 FIL | 0
2KiB        |   50%      | 3 year(s) | 0.000000045482176711 FIL | 0.000000045482176711 FIL | 0
2KiB        |    0%      | 3 year(s) | …
```
=> feat(shed): check command for FIP-0081 pledge calculation

cli/f3.go
* #12698
In Lotus F3 cli Only check the expected power table CID when it is present.
=> fix: skip checking the initial power table CID if undefined

CHANGELOG.md, cmd/lotus-miner/sectors.go
They probably exist but I couldn't find them
Fix sectors display to calculate verified power against correct power base epoch.  This way we don't divide by an incorrect denominator and scare SPs into thinking extensions will dilute their power (i.e. lets not let the whole point of FIP 0045 go to waste)
slack thread here: https://filecoinproject.slack.com/archives/C015KQQLQQ1/p1728479245409819
=> fix(miner): fix scary verified power miscalculation upon extension

cli/f3.go
Use numerical format to print actor IDs not found. Otherwise, `%q` will print special character.
=> fix: use numerical formatting when printing F3 CLI error message

CHANGELOG.md, chain/sync.go, chain/sync_test.go
Resolves a bug in sync by preventing checkpoint expansion.
=> fix(sync): do not allow to expand checkpointed tipsets

cmd/release/main.go, documentation/misc/RELEASE_ISSUE_TEMPLATE.md, go.mod, go.sum
This is followup to https://github.com/filecoin-project/lotus/pull/12741 after using the script to create the Lotus release issue for v1.32.0 for Node and Miner.  
The following changes were made:
1. `create-on-github` flag that when not set prints out formatted output to STDOUT.  This was really useful for development and debugging.
2. Simplified rc1 and stable release date to just take a single string that conforms to a likely pattern.  I found the template table with precision/confidence was too much as well as specifying all the options before.
3. `repo` option so can create an issue outside of `filecoin-project/lotus`.  This was useful for development/debugging.
4. For each CLI argument, I'm reading in the value and validating/processing it before moving to the next.
5. Introduced …
=> ci: automate release issue creation from v1.32.0 learnings

CHANGELOG.md, build/openrpc/full.json, build/openrpc/gateway.json, build/openrpc/miner.json, build/openrpc/worker.json, build/version.go, documentation/en/cli-lotus-miner.md, documentation/en/cli-lotus-worker.md, documentation/en/cli-lotus.md
Ref: https://github.com/filecoin-project/lotus/issues/12750
=> build: update Lotus Node and Miner version to v1.32.1-dev in master

.github/workflows/create-release-issue.yml, cmd/release/README.md, cmd/release/main.go, documentation/misc/RELEASE_ISSUE_TEMPLATE.md, go.mod, go.sum
Resolves #12477
This PR implements the release issue creation automation.
Firstly, it turns the `RELEASE_ISSUE_TEMPLATE.md` into a Go template. This allowed us to use variable substitution and conditional blocks, which were the prerequisites for release issue rendering. We used variable substitution inline. We hid the conditional block starts/ends in HTML comment tags (``). We kept the modifications to a minimum and ensured that the template could still be copied manually and updated using almost the same steps as before.
Secondly, we added a new command - `create-issue` - to the `cmd/release` tool. The command accepts a number of flags, values of which are then used to render the issue template. Before creating a new issue, the command checks whether if it already exists. It requires …
=> ci: automate release issue creation

itests/eth_transactions_test.go
Failure @ https://github.com/filecoin-project/lotus/actions/runs/12173008490/job/33952695031#step:9:4808
Two applies with the same height, I assume this is a reorg at head; although that seems a bit sus since I think we're only supposed to have one miner here. 🤷 the point of the test is to get 2 beyond head and ChainNotify was just a way of ticking that over.
=> chore(test): unflake TestTraceFilter

chain/sync.go, chain/sync_test.go
Resolves flake in `TestSyncCheckpointHead`
Not certain why this was flaky, it would mean that sometimes the forking
tipset would not hit this case.
Resolves: #12758
=> fix(sync): mark blocks which diverge from checkpoint as bad

cli/chain.go, cli/multisig.go
fix lowercase initials and typos
=> docs: fix lowercase initials and typos

go.mod, go.sum
See: https://github.com/filecoin-project/go-f3/security/dependabot/12
Resolve CVE-2024-45337 by upgrading to the latest golang crypto.
=> chore: update to golang crypto `0.31.0`

CHANGELOG.md, api/api_gateway.go, api/proxy_gen.go, build/openrpc/full.json, build/openrpc/gateway.json, build/openrpc/miner.json, build/openrpc/worker.json, gateway/node.go, gateway/proxy_fil.go, itests/gateway_test.go, itests/kit/node_opts.go
Only applies a rate limiting cost of "basic" which is 1 token because I believe these are pretty efficient calls.
Doesn't apply a lookback time limit, you can fetch any arbitrary instance's certificate from a public gateway. go-f3's "certstore" is keyed by instance ID which is what's being queried here.
=> feat(gateway): add F3GetCertificate & F3GetLatestCertificate to gateway

build/buildconstants/params_calibnet.go
https://github.com/filecoin-project/lotus/issues/12750
See discussion post here: https://github.com/filecoin-project/community/discussions/74#discussioncomment-11549619
=> chore: unset nv25 upgrade height on Calibnet

CHANGELOG.md, build/openrpc/full.json, build/openrpc/gateway.json, build/openrpc/miner.json, build/openrpc/worker.json, build/version.go, documentation/en/cli-lotus-miner.md, documentation/en/cli-lotus-worker.md, documentation/en/cli-lotus.md
https://github.com/filecoin-project/lotus/issues/12750
- Prep for publishing Lotus v1.32.0-rc2 
=> build: release Lotus Node and Miner v1.32.0-rc2

cli/chain.go, cli/spcli/actor.go, cmd/lotus-shed/actor.go, cmd/lotus-shed/keyinfo.go, cmd/lotus-shed/math.go, tools/stats/influx/influx.go, tools/stats/ipldstore/ipldstore.go
Discussion in #12781 made me check how many instances of bad capitalisation we have left in the repo, and it's not very many so I decided to fix these. I'm just limiting myself to those fixes, not the misuse of `fmt.Errorf` or the xerrors/errors inconsistencies.
golangci-lint is supposed to catch these for us, but I think it's deprecated its checking of xerrors messages, simply reporting those as deprecated instead and we explicitly ignore that deprecation error, so we're left without checking.
I think it might be worthwhile also putting actual staticcheck in the mix, not just the golangci-lint staticcheck module which is different, but there's a lot more errors to fix that it throws up before we do that. Something to chip away at.
=> fix: bad error message capitalisation

cmd/lotus-shed/f3.go
Ref: https://github.com/filecoin-project/lotus/pull/12723
This is my bad, I made a suggestion to change `"N"` to `"n"` in the cmd args list but not the usage of it. @Kubuxu which way do you want to go with this? Are you happy to switch all to`"n"`?
=> fix(shed): lotus-shed f3 certs command -n arg not -N

api/api_errors.go, chain/lf3/f3.go, itests/f3_test.go, node/impl/full/f3.go
Closes: https://github.com/filecoin-project/lotus/issues/12772
* Added an itest to test all of the F3 API method returns when both explicitly disabled F3 and F3 not properly started
* Fixed the `GetManifest` panic
* Made error messages more consistent (go-f3 has error messages that start with `"F3` but we have some `"f3`)
* `GetManifest` now copies the `"no known network manifest"` error message that `GetF3PowerTable` returns (from inside go-f3) during the not-running state
* `client.F3GetOrRenewParticipationTicket` now returns `nil` as the zero value of `api.F3ParticipationTicket` which is a slice, like the inner `lf3/leaser.getOrRenewParticipationTicket` returns, so we don't get `nil` in one case and `[]` in another
One minor special case is `F3GetECPowerTable` returns a sensible value …
=> fix(f3): test API during inactive-F3 modes and make consistent and safe

chain/actors/builtin/market/actor.go.template, chain/actors/builtin/market/market.go
I'm not sure this is even needed. I also don't know if `SectorNumber` should be considered here, it wasn't on the original form and I only added it because that would seem to be appropriate for completeness.
My short git detective walk suggests the `emptyDealState#Equals` method contents was deduped with `DealStatesEqual` as part of the DDO work in https://github.com/filecoin-project/lotus/pull/11226, but the wrong way around, ooops. So I'm flipping it back, but also adding `SectorNumber` because that would seem more correct 🤷‍♂️ ; depends on how this is used.
There's one use in [`StatePredicates#DealStateChangedForIDs`](https://github.com/filecoin-project/lotus/blob/4317d1aca71df1b87c8f6dc6813aa43ab24e6954/chain/events/state/predicates.go#L245-L246) but I can't see that being used …
=> fix: make DealStatesEqual work properly

CHANGELOG.md, build/bootstrap/mainnet.pi
Add one of my spare nodes as bootstrap. I don't use it for anything else, so it might as well do some work for the network.
I might add a few more depending on how much load this node sees.
Note that this is a single node with 3 multiaddrs. The bootstrap logic is smart enough to dedupe this into a single peerinfo.
=> chore(bootstrap): magik bootstrap nodes

.github/workflows/dependency-check.yml, go.mod
This is on top of https://github.com/filecoin-project/lotus/pull/12740, I'm experimenting with using `go list -versions` to inspect `v0.0.0` dependencies (as per discussion with @BigLep). We should be able to say "you're using an untagged version, but it has a version, that's naughty.
=> feat(ci): go list check versions available for untagged dependencies

CHANGELOG.md, scripts/deploy-node.sh
=> fix: lotus spelling error.

chain/sub/incoming.go, cli/info.go, cmd/lotus-miner/info.go, cmd/lotus-miner/proving.go, cmd/lotus-miner/sealing.go, cmd/lotus-miner/storage.go, miner/warmup.go, storage/paths/fetch.go, storage/paths/local.go, storage/paths/localstorage_cached.go, storage/sealer/fsutil/filesize_unix.go, storage/wdpost/wdpost_run.go, tools/stats/points/collect.go
=> chore: use time.Since instead of time.Now().Sub

documentation/changelog/CHANGELOG_1.2x.md
fixed 2 markdown syntax or links to make it work.
=> chore: fixed 2 markdown syntax or links

cmd/lotus-shed/cron-count.go
None
lotus-shed cron queue utility to see which miners have an entry in the power actor cron queue.
This is important information because it allows us to debug the potential for disastorous frozen cron code paths. 
I did this to debug this thread: https://filecoinproject.slack.com/archives/CPFTWMY7N/p1736752473709029 
=> feat(shed): cron queue inspection util

CHANGELOG.md, build/openrpc/full.json, build/openrpc/gateway.json, build/openrpc/miner.json, build/openrpc/worker.json, build/version.go, documentation/en/cli-lotus.md
#12827
- Prep Lotus Node v1.31.1-rc1 release
=> build: release Lotus Node v1.31.1-rc1

cli/f3.go
When calculating proportional F3 participation power for a given actor IDs instead of failing when an actor isn't found, collect the non-existing ones and report them. This makes up a better UX when debugging F3 in cases where actors don't exist in the F3 power table.
=> feat: handle non-existing actors gracefully in F3 power proportion CLI

CHANGELOG.md, build/openrpc/full.json, build/openrpc/gateway.json, build/openrpc/miner.json, build/openrpc/worker.json, build/version.go, documentation/en/cli-lotus.md
Ref: https://github.com/filecoin-project/lotus/issues/12827
- Prep Lotus Node v1.31.1 release
=> build: release Lotus Node v1.31.1

CHANGELOG.md
https://github.com/filecoin-project/lotus/issues/12827
Cherry-pick v1.31.1 changelog back to master
=> chore(release): cherry-pick v1.31.1 changelog back to master

documentation/misc/RELEASE_ISSUE_TEMPLATE.md
#12480 and #12344, https://github.com/filecoin-project/lotus/issues/12827
Accumulating release template improvements from shipping the v1.30.0, v1.31.0 and v1.31.1 release
=> docs(release): v1.30.0, v1.31.0 and v1.31.1 release template improvements

CHANGELOG.md, cli/lotus/daemon.go, go.mod, go.sum
* #12852
The benchmarking performed as part of #12852 shows that the pure-go implementation of zstd decoder is fast-enough for snapshot import.
Switch to it motivated by the desire to reduce CGO dependencies across Lotus.
Fixes #12852
=> chore: switch to pure-go zstd decoder for snapshot imports

api/docgen-openrpc/cmd/docgen_openrpc.go, api/docgen-openrpc/openrpc.go
api/docgen-openrpc/cmd/docgen_openrpc.go
**anyways - anyway**
api/docgen-openrpc/openrpc.go
**schemea - schema**
=> fix(docs): minor spelling corrections

CHANGELOG.md, chain/index/ddls.go, chain/index/events.go, chain/index/events_test.go
This is a continuation of @akaladarshi's excellent work in #12728, finishing it up and making it mergeable. Original commit squashed from that PR is retained here, with just a small extra one by me added on top.
=> feat(eth): check events are indexed within in requested range

.github/workflows/stale-branches
Add a workflow that marks stale branches and deletes stale branches:
- Branches are marked as stale after 180 days without no commits.
- Branch that have been inactive for 360 days is deleted.
- Has no protection rules.
- Exclude any branch that starts with 'release/miner' as these have no branch protection rules ([ref](https://github.com/filecoin-project/lotus/branches/all?query=release%2Fminer))
- Is not the default branch
=> feat(ci): add stale branch workflow

cli/helper.go
Prior code only conditionally logged the output when `LOTUS_DEV` env var was present. This doesn't make sense for a number of reasons:
* In case of an error starting up `lotus daemon` via systemctl for example the logs would miss the error. One then has to search through system journal to see what happened.
* There are no other places that I can find where `LOTUS_DEV` env var is used. The commit that introduced this condition is very old with no clear commit message to shed light into the rationale.
For the first reason alone, the changes here remove that condition, and log the message when the logging output is not standard err or out. This way we at least cover the case where lotus is run in a production environment and would avoid partial logging of errors.
Before you mark the PR ready …
=> chore: log failure to run CLI command

cmd/lotus-shed/main.go
Open to suggestions on more idiomatic ways to expose this if you have any. We have some long-running commands in lotus-shed (like `migrate-state`) that are handy to be able to profile while running.
=> feat(shed): optional --pprofport

CONTRIBUTING.md
This was done in response to discussion on #fil-lotus-dev: https://filecoinproject.slack.com/archives/CP50PPW2X/p1738873972951379
=> docs: point to regex and tools for conventional commits

CHANGELOG.md, api/api_gateway.go, api/proxy_gen.go, api/types.go, build/buildconstants/params_2k.go, build/buildconstants/params_butterfly.go, build/buildconstants/params_calibnet.go, build/buildconstants/params_interop.go, build/buildconstants/params_mainnet.go, build/buildconstants/params_shared_vals.go, build/buildconstants/params_testground.go, build/openrpc/full.json, build/openrpc/gateway.json, build/openrpc/miner.json, build/openrpc/worker.json, build/parameters.go, documentation/en/api-v0-methods.md, documentation/en/api-v1-unstable-methods.md, gateway/node.go, gateway/proxy_fil.go, node/impl/full/state.go
Resolves: #12873, #12862, #11996
- Remove `SupportedProofTypes` from `StateGetNetworkParams`. This field has been overlooked multiple times during proof type updates and doesn't match the FVM's actual supported proofs
- Expose StateGetNetworkParams in Lotus Gateway API  
**Before:**
```
curl --silent -X POST -H "Content-Type: application/json" \
>              --data '{"jsonrpc":"2.0","id":2,"method":"Filecoin.StateGetNetworkParams","param":"null"}' \
>              "http://127.0.0.1:34421/rpc/v0"
{"id":2,"jsonrpc":"2.0","result":{"NetworkName":"mainnet","BlockDelaySecs":30,"ConsensusMinerMinPower":"10995116277760","SupportedProofTypes":[3,4],"PreCommitChallengeDelay":150,"ForkUpgradeParams":{"UpgradeSmokeHeight":51000,"UpgradeBreezeHeight":41280,"UpgradeIgnitionHeight":94000,"UpgradeLifto …
```
=> feat(api)!: expose `StateGetNetworkParams` in Lotus Gateway API and remove `SupportedProofTypes`

blockstore/api.go
I've been relying on `NewAPIBlockstore` a lot lately for lotus-shed commands, miscellaneous things to inspect state mainly, where I don't want to stop my node to mount it as the blockstore. But realised that a lot of the fetches are for the same small blocks because we have a lot of things like THE empty partition, THE empty deadline, THE empty HAMT. It turns out that putting a simple LRU in there makes it so much faster to do simple iteration and checking when you're hitting these things.
This is mainly used in lotus-shed, but it has a few uses in the `lotus` command, specifically for some things under `lotus filplus`, `lotus miner info` and `lotus multisig`. The `spcli` commands also use this a little.
=> chore(blockstore): add an LRU cache to the API blockstore wrapper

itests/gateway_test.go
I'll drop some notes in https://github.com/filecoin-project/lotus/issues/12566 further to the comment I'm leaving in here. It's been flaky too long and hasn't been prioritised to be fixed.
=> chore(test): skip unfixed flaky gateway limits test

CHANGELOG.md, build/genesis.go, build/genesis_test.go, cli/lotus/daemon.go, documentation/en/cli-lotus.md
When `--genesis` path is set, automatically detect if the genesis file is ZSTD compressed and decompress it.
=> feat: automatically detect if genesis CAR is compressed

Dockerfile
The actual environment variable that sets the proof params fetch path is `FIL_PROOFS_PARAMETER_CACHE` according to `go-paramfetch` implementation. See:
* https://github.com/filecoin-project/go-paramfetch/blob/62ad5888f87076c9589d2b63af904b1f89a91b86/paramfetch.go#L31
Fix it in `Dockerfile` to avoid redundant download of params if the wrong env var is set.
=> chore: use the correct environment variable for proof params path

build/buildconstants/params_butterfly.go
To be able to test F3 on butterflynet without having to build a bespoke image of lotus or reset the butterflynet change the F3 bootstrap epoch to -1. This disables the autofusing of static manifest.
=> chore: disable F3 manifest autofusing on butterflynet for testing purposes

chain/gen/slashfilter/slashsvc/slashservice.go
#12906 
Reduces log level for `ipld: could not find` logs to DEBUG.
=> fix(slashsvc): reduce `block not found` error logs

.github/workflows/docker.yml
In addition to existing networks, also publish docker images for 2k network.
=> chore: publish 2k docker images

.github/workflows/test.yml, cmd/ci/README.md, cmd/ci/main.go
Resolves #12860
Start running `unit-*` jobs on arm64 machines in addition to x86_64 ones. 
In order to accommodate this change, I moved the test discovery code to a dedicated Go CLI. The important change in the structure of metadata is that now each test group can be associated with many target runners.
What's more, I split the test group discovery into part 1 which lists all the test groups, and part 2 which returns the metadata (e.g. runner information, etc.) for a given test group name. Thanks to this the outputs of the discovery job can be smaller and we minimise the risk of hitting the maximum output size limit.
=> feat(ci): run unit test jobs on arm64 machines additionally

build/bootstrap.go
Do not parse bootstrapper addresses if it's overridden via `LOTUS_P2P_BOOTSTRAPPERS` with empty value.
=> chore: skip bootstrap address override if `LOTUS_P2P_BOOTSTRAPPERS` is empty

cmd/lotus-seed/genesis.go
Allow the balance to be specified in `lotus-seed genesis add-miner` via `--balance` flag.
=> chore: parameterise balance in `lotus-seed genesis add-miner`

go.mod, go.sum
Upgrade to the latest `go-f3` to pull in the bug fixes and GPBFT topic name change.
=> chore: upgrade to go-f3 `v0.8.2`

build/testing_flags.go, build/testing_flags_debug.go
Prior to changes here, `InsecurePoStValidation` in `debug` was a noop.
=> fix: fix broken `InsecurePoStValidation` build constant

cmd/lotus-seed/genesis.go
Add the ability to specify the genesis timestamp in `lotus-seed genesis new` command in RFC-3339 format.
=> feat: allow genesis timestamp to be specified in `lotus-seed genesis new`

chain/lf3/participation.go
Move log level in case of error to `DEBUG` entirely. The chances are when there's an issue with F3 participation `DEBUG` level logging is needed to understand why anyway.
=> chore: reduce participation log verbosity when F3 isn't ready

chain/types/bigint.go
Delegates most calls to go-state-types and treats "nil" as "zero" (we encode nil as zero, so we might as well treat it as such when doing math).
@rvagg just in case we want to do it this way.
=> fix: delegate integer operations to go-state-types

node/modules/lp2p/pubsub.go
The code would only allow the main network pubsub topic if the static manifest were specified.
Not sure how that slipped through my manual tests. I think I was testing it with the code that was overriding static manifest with contract one, and only later I made the two options exclusive.
=> fix: f3: topic filter with no static manifest

CHANGELOG.md, api/cbor_gen.go, cmd/lotus-shed/shedgen/cbor_gen.go, go.mod, go.sum, paychmgr/cbor_gen.go, storage/pipeline/cbor_gen.go, storage/pipeline/piece/cbor_gen.go, storage/sealer/cbor_gen.go, storage/sealer/storiface/cbor_gen.go
~On top of #12935 and it needs https://github.com/filecoin-project/go-state-types/pull/360 to be merged and released.~
_(Edit: #12935 is merged, this updates go-state-types which we need a tag for @ https://github.com/filecoin-project/go-state-types/pull/364)_
This is a breaking change in go-state-types, but its subtle and as far as we can tell this should only have a positive impact of avoiding potential panics when operating on an empty `go-state-types/big.Int`.
=> chore: update go-state-types with empty big.Int{} handling

cli/util/api.go
fix: prevent panic in FullNodeProxy with empty node list
Fixes #12931
- Add check in FullNodeProxy to prevent panic when called with an empty node list
=> fix: prevent panic in `FullNodeProxy` with empty node list

CHANGELOG.md, api/api_common.go, build/buildconstants/params.go, build/openrpc/gateway.json, documentation/en/api-v0-methods-miner.md, documentation/en/api-v0-methods.md, documentation/en/api-v1-unstable-methods.md, node/impl/common/common.go, node/modules/lp2p/host.go
Closes https://github.com/filecoin-project/lotus/issues/12904
Added `Agent` to the `Filecoin.Version`. Depending on the client's deserialization capabilities, this is a potentially breaking change.
=> feat: add Agent to `Filecoin.Version` !

build/buildconstants/params_calibnet.go
Timing confirmed by implementers: https://filecoinproject.slack.com/archives/C05P37R9KQD/p1741938432377989
Set nv25 calibnet upgrade epoch to `2520574`, which corresponds to:
- Los Angeles: 2025-03-25T16:00:00Z
- London time: 2025-03-25T23:00:00Z
- UTC: 2025-03-25T23:00:00Z
- Bejing time: 2025-03-26T07:00:00Z
=> chore: set nv25 calibnet upgrade epoch

CHANGELOG.md, chain/actors/policy/policy.go, chain/actors/policy/policy.go.template, cli/spcli/sectors.go, cmd/lotus-sim/simulation/stages/precommit_stage.go, documentation/en/default-lotus-miner-config.toml, node/config/def.go, node/config/doc_gen.go, node/config/types.go, storage/pipeline/commit_batch.go, storage/pipeline/precommit_batch.go, storage/pipeline/sealiface/config.go, storage/pipeline/terminate_batch.go, storage/wdpost/wdpost_run.go
close #12902
Removed BatchPreCommitAboveBaseFee, AggregateAboveBaseFee, and the related checks.
The MinCommitBatch is actually constrained by the SNARK circuits, so it will remain at 4 without change:
- You need 4 or more sectors to ensure that the verification time for aggregated proofs is smaller than for batched proofs.
- You need 13 sectors or more to ensure that the aggregated proof size is smaller than the batched proof size.
The MaxCommitBatch limit comes from the original ([FIP-0013](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0013.md#scale-and-limits-1)), and it seems there's not much incentive to modify it, so these two parameters will remain unchanged.
=> feat(miner): remove batch balancer-related functionality

build/buildconstants/params_calibnet.go
Based on conversation here: https://filecoinproject.slack.com/archives/C05P37R9KQD/p1742323806618049
Update Calibration Teep height to epoch `2523454` corresponding to `2025-03-26T23:00:00Z`
=> chore: update Calibration Teep height

CHANGELOG.md, build/openrpc/full.json, build/openrpc/gateway.json, build/openrpc/miner.json, build/openrpc/worker.json, build/version.go, documentation/en/cli-lotus-miner.md, documentation/en/cli-lotus-worker.md, documentation/en/cli-lotus.md
https://github.com/filecoin-project/lotus/issues/12750
Prep Lotus v1.32.0-rc3
=> build: release Lotus Node and Miner v1.32.0-rc3

chain/actors/builtin/miner/actor.go.template, chain/actors/builtin/miner/miner.go, chain/actors/builtin/power/actor.go.template, chain/actors/builtin/power/power.go, chain/actors/policy/policy.go, chain/actors/policy/policy.go.template, go.mod, go.sum, itests/sector_terminate_test.go
Ref: https://github.com/filecoin-project/go-state-types/pull/376
Ref: https://github.com/filecoin-project/builtin-actors/pull/1639
I've added some extras in our state types abstractions here, I'd like to add more and reduce (ideally remove) the direct uses of go-state-types versioned actor types we have through the codebase. (See https://github.com/filecoin-project/lotus/pull/12960 for some of how annoying this is). My goal in the itest was to not refer to go-state-types at all while testing all of those additions. We should be able to approach almost all other uses of those types throughout the code in the same way, but we're pretty sloppy.
Also removed some batch balancer stuff.
=> feat: integrate & test FIP-0098 additions

go.mod, go.sum, itests/daily_fees_test.go
Was supposed to be done in https://github.com/filecoin-project/lotus/pull/12968
=> chore(deps): bump go-state-types to v0.16.0-rc8

cmd/lotus-shed/miner.go
Encountered when running some lotus-shed command on the Butterfly-network which has upgraded to nv25/v16-actors.
Update miner actor references from v15 to v16 in the `lotus-shed miner` cmd to maintain compatibility with the latest actor version.
=> chore(shed): update miner actor from v15 to v16 in `lotus-shed miner` cmd

CHANGELOG.md, node/impl/eth/transaction.go, node/impl/eth/utils.go
Both will benefit from the same cache and be impacted by EthBlkCacheSize
Ref: https://github.com/filecoin-project/lotus/issues/12977
_(Also some minor fixups in here to rename some vars to what they should have been, when I refactored this originally most interfaces were "providers", hence the `p` in the names.)_
=> chore(eth): make EthGetBlockByNumber & EthGetBlockByHash share cache code

CHANGELOG.md, chain/actors/builtin/market/actor.go.template, chain/actors/builtin/market/market.go, chain/actors/builtin/market/state.go.template, chain/actors/builtin/market/v0.go, chain/actors/builtin/market/v10.go, chain/actors/builtin/market/v11.go, chain/actors/builtin/market/v12.go, chain/actors/builtin/market/v13.go, chain/actors/builtin/market/v14.go, chain/actors/builtin/market/v15.go, chain/actors/builtin/market/v16.go, chain/actors/builtin/market/v2.go, chain/actors/builtin/market/v3.go, chain/actors/builtin/market/v4.go, chain/actors/builtin/market/v5.go, chain/actors/builtin/market/v6.go, chain/actors/builtin/market/v7.go, chain/actors/builtin/market/v8.go, chain/actors/builtin/market/v9.go, go.mod, go.sum, itests/direct_data_onboard_test.go
Closes: https://github.com/filecoin-project/lotus/issues/11997
See the itest for how this is used.
~_Depends on https://github.com/filecoin-project/go-state-types/pull/378_~
=> feat: expose market ProviderSectors access on state-types abstraction

cmd/lotus-shed/main.go, cmd/lotus-shed/miner-fees.go, cmd/lotus-shed/miner.go
Extension to https://github.com/filecoin-project/lotus/pull/12980 that looks for fee payment.
<details>
<summary>Output from butterflynet f01009</summary>
Current head is somewhere past 19126, we're within deadline 35 here so the latest cron is deadline 34, before that is historical, after that is even more historical.
```
Deadline 0:
Sector 92 daily fee: <legacy>
Sector 93 daily fee: <legacy>
✓ Deadline daily fee: 0, power: 1073741824 (sector fee sum: 0, expiration fee deduction sum: 0)
Deadline 1:
Sector 94 daily fee: <legacy>
Sector 95 daily fee: <legacy>
✓ Deadline daily fee: 0, power: 1073741824 (sector fee sum: 0, expiration fee deduction sum: 0)
Deadline 2:
Sector 5 daily fee: <legacy>
Sector 96 daily fee: <legacy>
Sector 97 daily fee: <legacy>
✓ Deadline daily fee: 0, power: …
```
=> feat(shed): inspect miner fee payment at each deadline cron

scripts/fiximports/main.go
fiximports has been driving me a little insane lately. For some reason it's started taking up to ~40s each execution and I can't figure out why. I tried switched from running go from a snap to just installing it from a package, I tried clearing my go build cache, I tried removing all the x/tools sources I had. Maybe I made a difference somewhere in there, but I'm still ~20s.
When measuring, the time cost is all in `imports.Process`, so something in there isn't having a happy time.
After a couple of iterations of trying to fix it I've landed on the following approach which gives me the best results:
1. Find all of the files we need to process
2. Read all file contents in (+ do the quick imports newline squash)
3. For each mutation of `imports.LocalPrefix`, process all files in parallel—so …
=> chore: make fiximports run in parallel

cmd/lotus-shed/miner.go
I threw this together just cause I wanted some quick stats but it's a pattern I've had to do a couple of times so having this in shed might make for a good example.
=> feat(shed): lotus-shed miner list-balances

Makefile
Closes: https://github.com/filecoin-project/lotus/issues/12767
Alternative attempt to https://github.com/filecoin-project/lotus/pull/12969 that doesn't involve a senti
`make calibnet` builds everything you need for a full devnet package, you would now do `make calibnet-lotus`, `make calibnet-lotus-gateway` etc. to build individual binaries.
=> feat(build): add calibnet-* etc. targets for per-network builds

chain/types/tipset.go
There is a [new function](https://pkg.go.dev/slices@go1.21.1#Equal) added in the go1.21 standard library, which can make the code more concise and easy to read.
=> refactor: use slices.Equal to simplify code

build/buildconstants/params_2k.go
Made `TockFix` epoch configurable for 2k network to work correctly with custom schedules, otherwise a [patch](https://github.com/ChainSafe/forest/pull/5515/files#diff-4b2ec166839d46813912b1a5cac7e04705790ccf03bf218eb2d593bc2da4e19e) is required on Forest side. 
=> chore: make `TockFix` epoch for 2k network configurable [skip changelog]

build/buildconstants/params_mainnet.go
Reference: https://github.com/filecoin-project/community/discussions/74?sort=new#discussioncomment-12720764
Update new Mainnet nv25 date to `epoch 4878840` corresponding to `2025-04-14T23:00:00Z`
=> chore: update new Mainnet nv25 date to 2025-04-14T23:00:00Z

CHANGELOG.md, build/openrpc/v2/full.json, chain/consensus/compute_state.go, documentation/en/api-v2-unstable-methods.md, metrics/metrics.go
I want to capture some gas values from message execution, but I'm also concerned about the quantisation of our timing metrics, particularly in the 1s - 2s range, I think it leads to weird graphs where our "total" `ApplyBlocks` time snaps to 1.99s and then bounces between some lower quantisation levels, when it should be the sum of the other 3 metrics collected within `ApplyBlocks` (early, messages and cron), but the sum of those 3 is never close to total.
I have this running at the moment and will report back with a new screenshot also with gas when I've collected enough.
=> feat(metrics): capture gas metrics from ApplyBlocks, tweak time buckets

itests/api_v2_test.go
Use a height that is sufficiently behind the target height to avoid race conditions in WaitTillChain that could result in tests running earlier than state change is reflected across the system.
Observed in:
* https://github.com/filecoin-project/lotus/actions/runs/14401881056/job/40389322945?pr=13026
=> chore: avoid test flakiness in v2 API tests caused by `WaitTillChain`

.gitattributes
So they are by default non-expanded in the diff
=> chore: mark generated openrpc and docs as generated

chain/consensus/compute_state.go, metrics/metrics.go
I'm belatedly realising after using #13030 that it's going to be more helpful to have a separate "total" metric rather than summing the components because of the loss of information in the bucketing.
=> feat(metrics): capture total gas metric from ApplyBlocks

cmd/lotus-shed/miner-fees.go
original code assumed a static state, but that's just not how mainnet works; we need to account for constantly onboarding sectors and ensure we're not counting fees for sectors that we don't expect to have been paid yet because they won't have been proven
=> fix(shed): account for new sectors that haven't been proven yet

chain/lf3/participation.go
Reduce logging to Debug as this is printed every 5 instances or so.
=> chore: reduce log level for F3 participation lease renewal

CHANGELOG.md, itests/api_v2_test.go, node/impl/full/chain_v2.go
In Lotus v2 APIs, in an event where F3 finalized tipset is too far behind EC, > 900 epochs return EC finalized tipset.
Part of: https://github.com/filecoin-project/lotus/issues/13062
=> feat: fall back to EC if F3 finalized tipeset is older than 900 epochs

.github/workflows/dependency-check.yml
Bumps checkout to v4 for future-proofing against Node 20 runner updates. Workflows compile the same.
=> ci: migrate workflows to checkout v4

CHANGELOG.md, build/buildconstants/params_mainnet.go
As reported by two of our nodes in `lotus f3 status`.
Set initial power table to `bafy2bzacecklgxd2eksmodvhgurqvorkg3wamgqkrunir3al2gchv2cikgmbu`.
EDIT: add first line
=> feat(f3): set initial power table for mainnet

CHANGELOG.md, build/openrpc/full.json, build/openrpc/gateway.json, build/openrpc/miner.json, build/openrpc/worker.json, build/version.go, documentation/en/cli-lotus-miner.md, documentation/en/cli-lotus-worker.md, documentation/en/cli-lotus.md
https://github.com/filecoin-project/lotus/issues/12970
Release v1.32.3:
- Update version string
- Add changelog
=> build: release Lotus Node v1.32.3

CHANGELOG.md
Closes: https://github.com/filecoin-project/lotus/issues/12970
Cherry-pick v1.32.3 changelog back to master
=> chore(release): cherry-pick v1.32.3 changelog back to master

cmd/lotus-fountain/site/robots.txt, cmd/lotus-fountain/site/sitemap.xml
#13057 
1. Added robots.txt:
•  Allows all web crawlers to access the site (User-agent: *)
•  Permits access to all pages (Allow: /)
•  Points to the sitemap location at https://faucet.calibnet.chainsafe-fil.io/sitemap.xml
2. Added sitemap.xml:
•  Contains three URLs for the Calibnet faucet site:
◦  Main page (/) with priority 1.0
◦  Funds page (/funds) with priority 0.8
◦  Datacap page (/datacap) with priority 0.8
•  All pages are set to update monthly (changefreq)
•  The sitemap follows the standard sitemap.org schema
=> chore(fountain): add sitemap and robots files

CHANGELOG.md, chain/lf3/ec.go, chain/lf3/f3.go
* feat(f3): add simple power cache
* fix cache
* Introduce concurrency limiter to powertable getting
* Update chain/lf3/ec.go
* don't export names
* Update CHANGELOG.md
* Organise imports
---------
=> fix(f3): introduce rate limit to computing F3 power tables (#13085)

CHANGELOG.md, build/openrpc/full.json, build/openrpc/gateway.json, build/openrpc/miner.json, build/openrpc/v2/full.json, build/openrpc/v2/gateway.json, build/openrpc/worker.json, build/version.go, documentation/en/api-experimental-user-facing-v2-docs/api-v2-experimental.md, documentation/en/cli-lotus.md
https://github.com/filecoin-project/lotus/issues/13004
Release Lotus Node v1.33.0-rc1
=> build: release Lotus Node v1.33.0-rc1

chain/state/statetree.go
This code path is being hit much more often now that F3 is enabled. To reduce noise in logs change the log level for this error to DEBUG.
Fixes: https://github.com/filecoin-project/lotus/issues/13083
=> chore: reduce the verbosity of state tree load failure to debug in `StateTree`

chain/exchange/client.go, node/hello/hello.go
Failure to fetch tipset during hello is not really an error and is repeatedly logged. Reduce noise by changing log level to `DEBUG`.
Additionally, it also reduces the log level for client request service, to avoid repeated `WARN` logs since logging is done in a loop.
See: https://github.com/filecoin-project/lotus/pull/11543#issuecomment-2094110694
=> chore: reduce log level for failure to `fetch tipset during hello`

cmd/lotus-fountain/main.go
Issue #13063 
This PR adds rate limit details to "Too many requests: Wallet limit" error message because it lacks clarity. [See UXIT dogfooding report.](https://filecoin.notion.site/Lotus-Fountain-Faucet-Report-19d7631f28258082a636f96df8b5d7fc)
Added rate limit details - "You can request tFIL every 2 hours". 
=> style: add rate limit details

chain/lf3/ec.go
Previously, we limited ourselves to loading 4 power tables at once, but would happily load one power table 4 times. Now, we do the same but ALSO avoid using all 4 jobs to load the same power table.
IMO, we should consider increasing this from 4.
=> feat(f3): load the power table once per tipset

cmd/lotus-fountain/site/datacap.html, cmd/lotus-fountain/site/faucet-components.css, cmd/lotus-fountain/site/funds.html
There's a bug in [#13056](https://github.com/filecoin-project/lotus/pull/13056/files) that affected styling on the `/funds` and `/datacap` routes by removing styles that were still in use. 🫠
I've restored the original styling by:
- Creating a dedicated file for these styles
- Importing this file specifically in the affected `/funds` and `/datacap` components
- Planning a proper styling standardization in upcoming PRs to prevent similar issues
=> fix(faucet): add removed styles that are still in use

CHANGELOG.md, build/openrpc/full.json, build/openrpc/gateway.json, build/openrpc/miner.json, build/openrpc/v2/full.json, build/openrpc/v2/gateway.json, build/openrpc/worker.json, build/version.go, documentation/en/cli-lotus.md
https://github.com/filecoin-project/lotus/issues/13004
Release v1.33.0
=> build: release Lotus Node v1.33.0

cmd/lotus-shed/miner-fees.go, cmd/lotus-shed/miner.go
```
USAGE:
lotus-shed miner fees-inspect [--tipset <tipset>] [--count <count>]
DESCRIPTION:
Inspect miner fees in the given tipset and its parents. The output is a CSV with the following columns:
Epoch, Burn, Fees, Penalties, Expected, Miners ...
Where:
- Epoch: the epoch of the tipset
- Burn: the total amount of attoFIL burned by miners in this tipset
- Fees: the total amount of expected proof fees paid by miners in this tipset
- Penalties: the total amount of penalties expected to be paid by miners in this tipset
- Expected: whether the sum of fees and penalties equals the burn amount (✓ or ✗), a discrepancy here likely results from burnt precommit deposits or miners who can't pay fees, neither of which are not calculated here
- Miners: the list of miners that burned or were expected to …
```
=> feat(shed): lotus-shed miner fees-inspect to inspect cron burn per epoch

cmd/lotus-shed/find-msg.go, cmd/lotus-shed/main.go
Search back through the chain to find messages of a particular type and print them out. Also includes the ability to add special cases for more information, currently just PCS3 which will also print out the number of sectors and the proof type.
This has been sitting in my local repo and I've been hardwiring values but I keep on having to use it so I made it more generic and will check it in.
@rjan90 this is one of the recent uses I've had for this tool so we can look at batch vs aggregate onboarding:
```
$ lotus-shed find-msg --tipset @4950273 --count 2 storageminer:ProveCommitSectors3
Epoch, MsgCid, From, To, Method, Sectors, Type
4950273, bafy2bzacebofnwjazb2nksoxmj7yn5whfhxtub7thlf3pfllnfetejkgqmpwi, f3xedke4ro7xhaovd3vk5gov7ezmrdc3k6pp2qa2svcwmd5qmhio2tlp7e6omv36hhi4ihjs22ryowdklqc6lq, …
```
=> feat(shed): lotus-shed find-msg --count X actor:Method

CHANGELOG.md, cli/lotus/daemon.go, itests/kit/node_opts.go, node/builder_chain.go, node/impl/eth/tipsetresolver.go, node/impl/full/f3.go, node/modules/eth.go
Disable F3 module when lotus is run with `--lite` commend since in that mode the daemon is simply a reverse proxy of a full node.
Fixes #13122
=> chore: disable F3 participation via gateway

CHANGELOG.md, build/buildconstants/f3manifest_mainnet.json
The GMessage buffer size is a non-consensus breaking parameter. It's a headroom beyond which pubsub will start dropping messages before they are seen by the F3 message processing logic.
During passive testing of F3 on mainnet we increased this buffer from its default value of 128 twice. We still observe reports by SPs that indicate the increased value may still not be enough for all cases. Increasing the buffer size is a low-risk parameter to adjust since the increase in memory consumption is negligible.
The root cause of the need for larger buffer size is slow state read in Lotus which consequently slows the serialised flow of message processing in F3. Work is under way to improve the efficiency of Lotus state fetch call that should reduce the reliance on larger buffers. But considering …
=> chore: increase the F3 GMessage buffer size to 1024

build/bootstrap/calibnet.pi, build/bootstrap/mainnet.pi
Fixed mainnet bootstrap node connectivity (had to change the domain name to not affect regular nodes that use the same name), changed calibnet bootstrap node domain name for consistency. `/dns/calibration.node.glif.io/tcp/1237/p2p/12D3KooWQPYouEAsUQKzvFUA9sQ8tz4rfpqtTzh2eL6USd9bwg7x` still works for compatibility.
=> chore(bootstraps): change Glif Nodes bootstraps domain names

Dockerfile
Hey team—noticed a dead link, replaced it with a working URL
https://github.com/rust-lang/docker-rust/blob/master/1.63.0/buster/Dockerfile - old link
https://github.com/filecoin-project/lotus/blob/master/Dockerfile#L63 - new link
=> build(dockerfile): replace dead upstream Rust Dockerfile link

cmd/release/main.go, documentation/misc/RELEASE_ISSUE_TEMPLATE.md
In support of https://github.com/filecoin-project/lotus/issues/13004
=> docs(release): v1.33.0 release template improvements

cmd/lotus-fountain/site/datacap.html, cmd/lotus-fountain/site/funds.html, cmd/lotus-fountain/site/index.html
This PR implements structured data markup using [Schema.org](https://schema.org/) vocabulary across the Lotus Faucet website pages to improve search engine visibility.
1. Added [Organization schema](https://schema.org/docs/schemas.html) to all pages (index, funds, and datacap) to establish consistent entity information
2. Includes key organization details:
•  Name: "Filecoin Lotus Calibration Faucet"
•  URL: https://faucet.calibnet.chainsafe-fil.io/
•  Logo: Filecoin logo reference
•  Description: Clear explanation of the faucet's purpose
•  Social/Related links through sameAs property (GitHub, ChainSafe, Filecoin, Slack)
WebPage Schema
1. Added specific WebPage schemas to individual pages (funds.html and datacap.html)
2. Each page includes:
•  Unique page name and description
•  URL …
=> feat: Add Schema.org Structured Data to Enhance SEO and Search Visibility of Faucet

itests/kit/node_unmanaged.go
Fixes: https://github.com/filecoin-project/lotus/issues/13098
=> fix(test): make immutable deadline check more conservative

documentation/en/create-miner.md
Replaced the outdated reference to architecture-2.md with the correct path to architecture/architecture.md in the documentation/en/create-miner.md file. This resolves a broken link error and ensures users are directed to the current Lotus architecture documentation. No other content was changed.
=> chore: fix broken architecture link in create-miner documentation

.github/workflows/release.yml
This ensures we can inspect what endpoint was used to publish a release.
This doesn't fix any issues. It will only be helpful in debugging.
=> ci: show the endpoint used to publish a release

CHANGELOG.md, cli/spcli/actor.go
Ref: https://github.com/filecoin-project/lotus/issues/13141
=> fix(spcli): send SettleDealPayments msg to f05 for `lotus-miner actor settle-deal`

CHANGELOG.md, chain/actors/builtin/miner/actor.go.template, chain/actors/builtin/miner/miner.go, cmd/lotus-shed/miner-fees.go, cmd/lotus-shed/miner.go
And `lotus-shed miner expected-reward` CLI command
Ref: https://github.com/filecoin-project/lotus/issues/13137
=> feat: `ExpectedRewardForPower` builtin utility function

CHANGELOG.md, cmd/lotus-gateway/main.go, gateway/handler.go
Allows remote access from a browser sandbox if exposed.
I needed this for some browser dev work to talk to my local node, and I have it running now and it's 👌.
Closes: #6402
=> feat(gateway): add CORS headers if --cors is provided

CHANGELOG.md, cli/spcli/actor.go, documentation/en/cli-lotus-miner.md
=> feat(spcli): make settle-deal optionally take deal id ranges

CHANGELOG.md
Hey team! Found and fixed errors 
`enviroment` - `environment`
=> fix error enviroment to environment in CHANGELOG.md

CHANGELOG.md, cli/state.go, documentation/en/cli-lotus.md
- Add option to show partitions and deadlines.
- Print output in CSV
In the future, I suggest merging the `lotus state sectors` and `lotus state active-sectors`. By default, they will be set to active. Use the flag `--show-all` to view all sectors.
=> feat(cli): lotus state active-sectors --show-partitions + CSV

cmd/ci/main.go
Mark API v2 and eth API f3 tests as one needing params.
This is a follow-up to a discussion we had in Slack.
=> ci: mark api v2 and eth api f3 tests as needing params

documentation/en/architecture/architecture.md
No related issues. This PR fixes the source code link for the `./lotus daemon` command in the documentation, making it easier for developers to find the correct file.
- Fixed the source code link in `documentation/en/architecture/architecture.md` for the `./lotus daemon` command, updating the path from `cmd/lotus/daemon.go` to `cli/lotus/daemon.go`.
- Reference: [Lotus GitHub Repository](https://github.com/filecoin-project/lotus)
- The updated link now points to the actual `daemon.go` file, improving documentation accuracy and usability.
=> docs: update broken link

CHANGELOG.md, chain/lf3/f3.go, node/builder_chain.go, node/modules/dtypes/storage.go, node/modules/storage.go, node/repo/fsrepo_ds.go
Migrate the f3 datastore from being namespaced in the metadata metadata
datastore to having its own dedicated datastore.
Depends on https://github.com/filecoin-project/lotus/pull/13144
=> feat(f3): migrate f3 datastore to separate datastore

node/impl/full/chain_v2.go
Fix an edge case where if the head epoch is below the chain finality policy (defaulting to 900) EC finalized head height would become negative.
Fixes: #13167
=> fix: assert that EC finalized tipset height is never negative in v2 APIs

node/repo/fsrepo.go, node/repo/memrepo.go
Spotted and fixed a few wording hiccups:
node/repo/fsrepo.go // node/repo/memrepo.go
`coresponding` - `corresponding`
=> fix(doc): minor spelling fixes

chain/events/events_called.go, cmd/lotus-pcr/main.go, cmd/lotus-shed/diff.go, documentation/en/api-experimental-user-facing-v2-docs/CLAUDE.md
fix some minor issues in the comments
=> chore: fix some minor issues in the comments

CHANGELOG.md, documentation/en/default-lotus-config.toml, itests/paych_api_test.go, itests/paych_cli_test.go, node/builder_chain.go, node/config/def.go, node/config/doc_gen.go, node/config/types.go, node/impl/paych/paych.go, node/modules/paych.go, paychmgr/manager.go
This change introduces a new configuration option EnablePaymentChannelManager to control whether the payment channel manager is started on node startup.
- Added EnablePaymentChannelManager boolean field to FullNode config struct
- Set default value to false (disabled by default) since payment channels get minimal use on mainnet
- Added conditional wiring in node/builder_chain.go to only start payment channel manager when config option is enabled
- Updated config documentation with clear description of the option
This saves resources for light nodes and most full nodes that don't use payment channel functionality, while still allowing users to enable it when needed by setting EnablePaymentChannelManager: true in their config.
https://github.com/filecoin-project/lotus/issues/12718
- …
=> feat(paych): add EnablePaymentChannelManager config option

blockstore/autobatch.go, lib/backupds/cbor.go, lib/sqlite/sqlite.go, lib/ulimit/ulimit.go, node/modules/core.go
=> chore(docs): minor typo fixes

cmd/lotus-fountain/site/index.html
Replaced the outdated Filecoin Plus documentation link (https://docs.filecoin.io/basics/filecoin-plus) with the current and correct URL (https://docs.filecoin.io/basics/how-storage-works/filecoin-plus) in cmd/lotus-fountain/site/index.html to ensure users are directed to the latest information.
=> docs: update Filecoin Plus documentation link to the current URL

CHANGELOG.md, cli/spcli/sectors.go, documentation/en/cli-lotus-miner.md
https://github.com/filecoin-project/lotus/issues/11927
=> fix(cli): make lotus-miner sectors extend command resilient to higher gas

storage/sealer/fr32/readers.go, storage/sealer/fr32/readers_test.go
Fixes https://github.com/filecoin-project/lotus/issues/9324
The fr32 unpad reader currently requires that the output is power-of-two-unpadded size, which is an extremely sketchy assumption and seems to cause lots of pain in retrievals.
There is already quite a lot of code in piece-provider which ensures that reads are initialized at correct offsets (multiple of 127-unpadded-bytes), but the read sizes are only ensured by the fact that the output reader is wrapped in a bufio.Reader, which won't always buffer writes with the required size, leading to hard to debug panics.
This PR aims to make the UnpadReader behave more like any normal reader, removing a giant footgun in the retrieval code.
I realize that this code should probably eventually be external to lotus, but right now both boost and …
=> fix(miner): make UnpadReader be a correct Reader

documentation/en/default-lotus-config.toml, node/config/doc_gen.go, node/config/load.go, node/config/load_test.go, node/config/types.go, node/impl/full/state.go
=> chore(docs): fix some typos in comment

cmd/lotus-bench/rpc.go, cmd/lotus-shed/state-stats.go, cmd/tvx/state.go
fix some minor issues in comments
=> chore(docs): minor spelling mistakes in comments

cmd/lotus-shed/f3.go, cmd/lotus-shed/fevmanalytics.go, cmd/lotus-shed/keyinfo.go, paychmgr/simple.go
fix some minor issues in comments
=> chore(docs): fix some minor issues in comments

CHANGELOG.md, blockstore/instrumented.go, blockstore/metrics.go, chain/sub/incoming.go, documentation/en/architecture/architecture.md, metrics/metrics.go, node/modules/chain.go
Only enabled with LOTUS_ENABLE_MESSAGE_FETCH_INSTRUMENTATION=1 due to minor additional blockstore index usage.
Looks a little like this during normal operation:
It's difficult to show this from Prometheus well but bitswap usage seems to be fairly rare, we're able to get most messages from pubsub. The occasional fetches make it look like it hovers a bit above 95% but it's very patchy.
The timings aren't quite as interesting as hoped due to the infrequency but they do show some interesting things about the local blockstore, just isolated to messages.
=> feat(metrics): instrument bitswap usage

.github/workflows/add-issues-and-prs-to-fs-project-board.yml
Part of https://github.com/FilOzone/github-mgmt/issues/10.  It didn't originally get created with github-mgmt because of the branch protection rule.
=> ci: create add-issues-and-prs-to-fs-project-board.yml

.github/workflows/release.yml, CHANGELOG.md, build/openrpc/full.json, build/openrpc/gateway.json, build/openrpc/miner.json, build/openrpc/v0/gateway.json, build/openrpc/v2/full.json, build/openrpc/v2/gateway.json, build/openrpc/worker.json, build/version.go, documentation/en/cli-lotus-miner.md, documentation/en/cli-lotus-worker.md, documentation/en/cli-lotus.md
https://github.com/filecoin-project/lotus/issues/13132
Prep for release of Lotus Node v1.33.1-rc1
=> build: release Lotus Node v1.33.1-rc1

blockstore/splitstore/README.md, chain/actors/aerrors/wrap.go
This PR corrects several minor typos in comments and documentation across the codebase. The changes are non-functional and purely textual to improve clarity and maintain a clean, professional codebase.
- `frequenty` → `frequently`
- `extens` → `extends`
No logic or functionality has been modified. All changes are restricted to comments or non-executable doc annotations.
=> chore: fix typos in docs

go.mod, go.sum
Backport #13236 to the `release/v1.33.1` branch, before prepping the v1.33.1 release to get shipped.
=> chore: backport #13236 to the `release/v1.33.1` branch

CHANGELOG.md, cli/spcli/actor.go, documentation/en/cli-lotus-miner.md
By default, only expired deals are processed. Prevent frequent sending of useless settlement messages.
=> feat(spcli): add `--all-deals` to `lotus-miner actor settle-deal`

chain/types/ethtypes/eth_types.go
Reviewer @rvagg
This method is helpful for printing this struct
Before
```
{0xc00116b390 <nil> <nil> false}
```
After
```
latest
```
* add ethBlockNumberOrHash.String
=> feat(ethtypes): ethBlockNumberOrHash.String

CHANGELOG.md, chain/stmgr/call.go, node/impl/eth/api.go, node/impl/eth/lookup.go
Reviewer @rvagg
Fixes #13247
I use `TipSetState` and `LoadActorRaw` instead of `ParentState` within `LoadActor`, which roughly matches the behavior of `EthCall`.
When looking for other methods that might have this problem in lookup.go, I noticed that `EthGetBalance` seems to already do `TipSetState` and `LoadActorRaw`.
Deploy a contract and await the receipt
Once receipt returns non-null, immediately kill lotus-miner
Query daemon with eth_getCode on latest
Before this change, eth_getCode outputs 0x (because ErrActorNotFound)
After this change, eth_getCode outputs the deployed bytecode
Apply a tx on the contract that sets nonzero storage from zero.
Once receipt  returns non-null, immediately kill lotus-miner
Query daemon with eth_getStorageAt on latest
Before this change, eth_getStorageAt …
=> fix(api): eth_getCode and eth_getStorageAt operate on current tipset state

CHANGELOG.md, node/impl/eth/transaction.go
Reviewer @rvagg
Similar to #13274
Run local devnet miner and daemon.
Send transaction and await receipt, then kill miner.
Query eth_getTransactionCount of sender.
Before this change it returns zero.
After this change it returns nonzero
* use LoadActorRaw to specify TipSetState cid
=> fix(api): eth_getTransactionCount operate on current tipset state

CHANGELOG.md, itests/eth_api_f3_test.go, itests/eth_api_test.go, node/modules/eth.go
As per chat with @BigLep, this is how we backport F3 finalisation rules to v1 Eth APIs if we want to go with that path. It also comes with a future clean-up task that we should open an issue for if we merge this.
---
Same rules as v2:
* "finalized" and "safe" resolve to whatever F3 has finalized
* Fall-back for "safe" is to 200 epochs behind head when F3 isn't operating
* Fall-back for "finalized" is 900 epochs behind head when F3 isn't operating
Run with LOTUS_ETH_V1_DISABLE_F3_FINALITY_RESOLUTION=1 to revert to the old resolution rules.
Future clean-up required:
* Remove LOTUS_ETH_V1_DISABLE_F3_FINALITY_RESOLUTION option
* Remove builder_chain.go split paths for v1 and v2 Eth module building - reuse same modules across v1 and v2.
* Simplify eth_api_f3_test.go to remove special rules for …
=> feat(eth): use F3 for "finalized" and "safe" resolution in v1 APIs

build/buildconstants/params_calibnet.go, build/version.go
Update Calibration NV27 height to epoch `3007294` corresponding to `2025-09-10T23:00:00Z`
Ref: https://github.com/filecoin-project/community/discussions/74#discussioncomment-14214805
=> chore: update Calibration NV27 height

Makefile
Fixes quote nesting bug in network-specific build targets when LDFLAGS is set.
Commands like `LDFLAGS=-L/usr/local/cuda/lib64 make calibnet-lotus` failed due to nested double quotes in GOFLAGS construction:
- `GOFLAGS+=-ldflags="$(ldflags)"` + `GOFLAGS="$(GOFLAGS) $(FLAGS)"`
- Result: `GOFLAGS="-ldflags="..." -tags=calibnet"` (parsing error)
Changed to single quotes to avoid nesting.
=> fix: resolve quote nesting in network-specific build targets

Makefile
Fixes quote nesting issue introduced by PR #13328.
PR #13328 changed network-specific targets to use single quotes around GOFLAGS assignments, but the base GOFLAGS definition still used double quotes around $(ldflags), causing quote nesting when LDFLAGS is set, and failure to run the make <network> commands.
=> fix: use single quotes in GOFLAGS ldflags to match network targets

CHANGELOG.md, build/buildconstants/params_calibnet.go
Proposed Changes
This PR backports critical changes from the release/v1.34.0 branch to master:
1. Calibration NV27 upgrade height (cherry-picked from #13316)
- Updates UpgradeGoldenWeekHeight from placeholder value 999999999999999 to actual epoch 3007294
- Required for Calibration network nodes running from master branch
2. v1.34.0 CHANGELOG updates (cherry-picked from #13338)
- Adds complete v1.34.0 release notes including migration information
- Ensures master branch has full release documentation
Note: Version numbers remain at v1.34.1-dev in master (not reverted to v1.34.0).
Additional Info
- Cherry-picked commits:
- f74a494ba - chore: update Calibration NV27 height (#13316)
- 56e13ccc4 - build: release Lotus Node and Miner v1.34.0 (#13338) [CHANGELOG only]
- Other changes from …
=> chore: backport Calibration NV27 height and v1.34.0 CHANGELOG to master

CHANGELOG.md, build/openrpc/full.json, build/openrpc/gateway.json, build/openrpc/miner.json, build/openrpc/v0/gateway.json, build/openrpc/v2/full.json, build/openrpc/v2/gateway.json, build/openrpc/worker.json, build/version.go, documentation/en/cli-lotus-miner.md, documentation/en/cli-lotus-worker.md, documentation/en/cli-lotus.md
The v1.34.0 release incorrectly shipped with `filecoin-ffi v1.34.0-dev` instead of the stable `filecoin-ffi v1.34.0` release. This patch release corrects this packaging error to include the proper stable version with ref-fvm v4.7.3.
https://github.com/filecoin-project/lotus/issues/13340
- Update filecoin-ffi submodule from `v1.34.0-dev` to stable `v1.34.0`
- Bump version to v1.34.1 in `build/version.go`
- Update CHANGELOG.md with v1.34.1 patch release notes
- Regenerate documentation via `make gen` and `make docsgen-cli`
All users running v1.34.0 should upgrade to v1.34.1 to ensure they have the correct stable version of filecoin-ffi.
=> build: release Lotus Node and Miner v1.34.1

node/impl/full/gas.go, node/impl/gasutils/gasutils.go
- Use the `TipSetKey` if it is provided in the API params instead of getting heaviest tipset (only use heaviest if API params doesn't have a TipSetKey)
=> fix(api): use params `tipset-key` to load the tipset for gas premium calculation

.github/workflows/release.yml, .gitignore
https://github.com/filecoin-project/lotus/issues/13262
=> ci: stop publishing x64 macos binaries

cmd/lotus-sim/simulation/stages/windowpost_stage.go
=> chore: fix typo in comment

CHANGELOG.md, cli/spcli/actor.go, cli/spcli/createminer/create_miner.go, cmd/lotus-shed/miner.go
fix #13364
Add a `deposit-margin-factor` option to `lotus-miner actor new` and `lotus-shed miner create` to ensure the sent deposit still covers the on-chain requirement (even if it rises between lookup and execution), preventing miner creation from failing due to insufficient deposit.
=> fix(cli): add `deposit-margin-factor` to the new miner commands
