- scripts/deploy-node.sh
- scripts/lotus-daemon.service
- scripts/lotus-miner.service
- scripts/setup-host.sh
> Update service names

- storage/miner.go
- storage/post.go
> Increase limity gazu

- cmd/lotus-storage-miner/init.go
> Clean up after failed storage miner init

- chain/types/keystore.go
- chain/vm/vm.go
- chain/wallet/wallet.go
- node/repo/fsrepo.go
- node/repo/interface.go
- node/repo/memrepo.go
- node/repo/repo_test.go
> handle changing default address

- README.md
> Add git version requirement

- chain/vm/vm.go
> fix annotation for vm

- Makefile
> Add Golang version check

- cli/client.go
> parse abs path for import file

- chain/sync.go
Before this, we would refetch data that we had locally. We still might do that a little bit now, but definitely much less.
> use blocks we have locally anytime we need them

- chain/vm/vm.go
> Delete TransferFunds Method

- chain/sync_test.go
- chain/vm/vm.go
- cmd/lotus/daemon.go
- cmd/lotus/main.go
- node/builder.go
- node/hello/hello.go
- node/modules/core.go
- node/modules/services.go
- node/node_test.go
- node/options.go
- peermgr/peermgr.go
Still a work in progress, looking for feedback on direction. My main goal here is to ensure that lotus daemon always has enough good peers.
> Initial pass at a peer manager

- chain/actors/actor_multisig.go
> safeguard for multisig actor

- chain/store/store.go
Was noticing a decent amount of load hitting this code. seems like a pretty simple optimization (maybe we want to make the cache bigger? idk)
> cache block message cids to make blocksync cheaper

- chain/actors/actor_miner.go
Check if from address equal work address when CommitSector
> Check if fromaddress equal workaddress when CommitSector

- chain/actors/actor_init.go
I think NextID++ should be exec when AddActor success.
> fix method:InitActorState.AddActor

- build/params.go
- chain/actors/actor_miner.go
- chain/gen/gen.go
- chain/sync.go
- chain/types/blockheader.go
- chain/vm/vm.go
- go.mod
- lotuspond/front/src/BlockLink.js
- lotuspond/front/src/ChainExplorer.js
- lotuspond/front/src/Consensus.js
- node/modules/storageminer.go
- storage/post.go
https://github.com/filecoin-project/specs/blob/cdf945e77c5ee167fe5441a888aa2476c72de6a9/src/systems/filecoin_blockchain/storage_power_consensus/storage_power_consensus_subsystem.go#L10-L17
TODO:
> Set proving params matching the spec more closely

- node/repo/fsrepo.go
Fixes https://github.com/filecoin-project/lotus/issues/475
> repo: Enable badger log truncation

- chain/types/fil.go
- cli/state.go
- cli/wallet.go
> Implment formatter on FIL to override big.Int

- chain/stmgr/call.go
This allows for the chain.Sync trace to be connected to the
entire chain sync operation, when viewing in Jaeger.
I am unsure about the usefulness of the attributes I added, though it allows you to determine if the gas price/limit was nil, which I am guessing all chain sync operations are.
> add statemanager.CallRaw span

- cmd/lotus-fountain/main.go
Rate limits needs to be ordered from specific to generic to ensure that
a single user will not exhaust the generic limiter before being limited
by the more specific.
> Invert faucet rate limiting

- lib/jsonrpc/client.go
> fix panic when close miner

- cmd/lotus-fountain/main.go
> Fix faucet ip limiting to use X-Real-IP

- cli/client.go
> fix ask price typo

- cmd/lotus-storage-miner/info.go
> add sector size info

- build/params.go
reference: https://golang.org/ref/spec#Integer_literals
> make long number param readable

- cli/params.go
> add a flag to allow only fetching verifying keys

- chain/types/blockheader.go
This one play as the same function as previous one, but it might be more direct.
> Refactor the PowerCmp function

- build/params.go
- chain/store/weight.go
1. removed obsolete `AdjustedPeriod` constant;
2. move wRatio to params.go as constants;
3. little change in Weight function accordingly.
> minor weight function change

- README.md
(going to just merge, pls still review)
> Readme: some minor updates

- chain/metrics/consensus.go
- cmd/lotus-townhall/main.go
- cmd/lotus-townhall/townhall/src/App.js
Also needs to get wired into the visuals, but this will be really helpful
> add time of block acceptance to townhall

- build/params.go
- chain/gen/gen.go
- cmd/lotus-storage-miner/init.go
- cmd/lotus-storage-miner/run.go
- cmd/lotus/daemon.go
- lib/sectorbuilder/sectorbuilder.go
- lib/sectorbuilder/sectorbuilder_test.go
- node/builder.go
- node/config/def.go
- node/node_test.go
- node/repo/fsrepo.go
- node/repo/fsrepo_test.go
- node/repo/memrepo.go
- node/repo/repo_test.go
- storage/garbage.go
Also throttling GeneratePieceCommitment on the miner (couldn't do on the client, as it doesn't have sectorbuilder instance)
> WorkerCount on storageminer config

- cli/wallet.go
Thanks @travisperson for reporting this one
> fix wallet import from a file

- build/params.go
- chain/blocksync/blocksync.go
- chain/gen/gen.go
- chain/messagepool.go
- chain/store/store.go
- chain/sync.go
- cmd/lotus/main.go
(Also seeing an issue where we mark some blocks as bad, which makes it impossible to sync the chain, but in this PR it's much easier to see - the sync just hangs)
> sync: Mark chains with bad blocks as bad too

- cmd/lotus-storage-miner/main.go
- cmd/lotus/main.go
Thanks again to @travisperson for the bug report :)
> Exit 1 on error

- chain/actors/actor_miner.go
- chain/blocksync/blocksync_client.go
- chain/stmgr/stmgr.go
- chain/store/store.go
- chain/sync.go
- chain/vm/vm.go
- lib/sectorbuilder/sectorbuilder.go
- lib/sectorbuilder/sectorbuilder_test.go
trying to figure out whats slow.
> more tracing spans

- .circleci/config.yml
- build/paramfetch.go
- cli/params.go
- cmd/lotus-storage-miner/init.go
- cmd/lotus-storage-miner/run.go
- cmd/lotus/daemon.go
- go.sum
- lib/sectorbuilder/sectorbuilder_test.go
> Add --tests-also for fetch-params

- chain/sync.go
> Fix ValidateBlock ignoring errors

- cli/auth.go
- lotuspond/front/src/NodeIndex.js
> Add parameters for creating tokens

- lib/sectorbuilder/sectorbuilder_test.go
(also some changes in how we use TipSetKey because of json serialization issues)
> Fixes for sectorbuilder issues

- chain/stmgr/stmgr.go
- go.sum
> Check if miner is included twice in tipset

- build/params.go
- chain/actors/actor_miner.go
- chain/actors/actor_paych.go
- chain/actors/actor_storagepower.go
- chain/actors/actor_storagepower_test.go
- chain/actors/cbor_gen.go
- chain/blocksync/cbor_gen.go
- chain/deals/cbor_gen.go
- chain/gen/mining.go
- chain/gen/utils.go
- chain/stmgr/stmgr.go
- chain/sync.go
- chain/types/bigint.go
- chain/types/cbor_gen.go
- gen/main.go
- go.sum
- lotuspond/front/src/State.js
- peermgr/peermgr.go
There are still some bugs around this, mostly:
* I'm not sure if power recovery logic works at all, need to test
* There is no collateral slashing at all (nor deal refunds) (can call this out-of-scope for now)
* Slashing works too well when setting up the network:
```
2019-11-14T01:01:15.008+0100    ERROR   miner   miner/miner.go:188      failed to submit newly mined block: sync to submitted block failed: failed to put synced tipset to chainstore: MaybeTakeHeavierTipSet failed in PutTipSet: All power in the net is gone. You network might be disconnected, or the net is dead!
github.com/filecoin-project/lotus/miner.(*Miner).mine
```
> Simple power slashing

- chain/messagepool.go
> Don't use pkg/errors

- datatransfer/types.go
spescified -> specified
requestor -> requester
> fix types typo

- chain/vm/vm.go
- go.mod
- go.sum
> use fast cbor-gen method for extracting links from objects

- cli/sync.go
can't exit `lotus sync wait` when running. add Ctrl+c to exit.
> add sync wait cmd ctrl+c exit

- build/paramfetch.go
> continue download param file

- build/paramfetch.go
- chain/deals/client_states.go
- chain/events/events.go
- chain/events/events_called.go
- chain/events/events_test.go
- chain/events/tscache_test.go
This can be later used to replace WaitMsg calls with something that handles confidence and reverts
> Event msg matchers

- api/api_full.go
- chain/blocksync/blocksync_client.go
- chain/sync.go
- chain/sync_manager.go
- chain/sync_manager_test.go
- chain/syncstate.go
- chain/types/mock/chain.go
- chain/types/tipset.go
- cli/sync.go
- node/builder.go
- node/impl/full/sync.go
- node/modules/chain.go
- tools/stats/rpc.go
The chain sync manager is responsible both for scheduling concurrent sync operations, and also for selecting the correct heads to sync to initially during bootstrap. 
I've still got a bit to do on this, but I wanted to open it up for some early review
> Implement chain sync manager

- chain/events/events_called.go
- chain/events/events_height.go
- chain/events/events_test.go
- chain/store/store.go
I think I got all the places where this was used, definitely could use help looking on the review
> fix ordering of block applies in reorg ops

- miner/miner.go
> Support multiple miners

- cli/client.go
> add empty slice check

- .gitignore
- Makefile
- api/api_full.go
- api/struct.go
- chain/address/address.go
- chain/messagepool.go
- chain/state/statetree.go
- chain/sync.go
- chain/types/bigint.go
- cli/mpool.go
- cli/state.go
- cmd/lotus-chainwatch/blockssub.go
- cmd/lotus-chainwatch/dot.go
- cmd/lotus-chainwatch/main.go
- cmd/lotus-chainwatch/mpool.go
- cmd/lotus-chainwatch/site/index.html
- cmd/lotus-chainwatch/site/key.html
- cmd/lotus-chainwatch/site/keys.html
- cmd/lotus-chainwatch/site/main.css
- cmd/lotus-chainwatch/storage.go
- cmd/lotus-chainwatch/sync.go
- cmd/lotus-chainwatch/templates.go
- cmd/lotus-chainwatch/utils.go
- go.mod
- go.sum
- node/impl/full/mpool.go
- node/impl/full/state.go
- node/impl/full/sync.go
A new tool for a very, very in-depth chain inspection
> ChainWatch

- lib/sectorbuilder/sectorbuilder.go
- storage/sealing.go
[need to test, but should work]
> sectors: Simple state restore

- storage/post.go
Fixes https://github.com/filecoin-project/lotus/issues/283
> Make ppe == 0 error less scary

- build/bootstrap.go
- chain/address/constants.go
- chain/store/store.go
- chain/store/weight.go
- chain/validation/message.go
- chain/validation/state.go
- cmd/lotus-chainwatch/sync.go
- go.mod
- go.sum
- lib/padreader/padreader_test.go
- lotuspond/api.go
- lotuspond/outmux.go
- miner/miner.go
- node/modules/core.go
- storage/miner.go
- storage/sector_states.go
- storage/sectorblocks/blockstore.go
> Swtich to xerrors

- documentation/api.md
- documentation/getting-started.md
- documentation/glossary.md
- documentation/hardware.md
- documentation/install-lotus-arch.md
- documentation/install-lotus-macos.md
- documentation/install-lotus-ubuntu.md
- documentation/join-devnet-cli.md
- documentation/join-devnet-gui.md
- documentation/mining.md
- documentation/retrieving-data.md
- documentation/testing-with-gui.md
- documentation/tracing.md
+ @magik6k had pointed out the copy was incorrect in some locations where it said **"Setup Devnet"**, It should say **"Join Devnet"**, I've made the change in this PR.
+ I added some links to replace some terms.
+ I added a better placeholder and title for the hardware page.
+ Misc formatting.
+ A bigger copy revision will probably follow this PR, so I wouldn't spend too much time proof reading copy that will most likely change.
Thanks everyone 🎊
> documentation: light copy adjustments before major revision

- build/params_debug.go
- build/params_devnet.go
- chain/store/store.go
- chain/sync_manager.go
- miner/miner.go
it was previously waiting 15 seconds (block time / 2). That is probably causing some issues in the devnet
> fix propagation delay to be a sane number

- storage/fpost_sched.go
> storageminer: Don't start fPoSt with every head change

- storage/fpost_sched.go
> storageminer: exit fpostScheduler loop cleanly

- cli/sync.go
- cmd/lotus-storage-miner/init.go
- cmd/lotus-storage-miner/run.go
Fixes https://github.com/filecoin-project/lotus/issues/713
> storageminer: Wait for sync

- chain/sync.go
- miner/miner.go
- miner/testminer.go
Basically, this is 'dont wait for new blocks to come in if we're already late starting to mine'
> WIP: improve timing of mining

- documentation/en/api.md
- documentation/en/getting-started.md
- documentation/en/hardware.md
- documentation/en/install-lotus-arch.md
- documentation/en/install-lotus-macos.md
- documentation/en/install-lotus-ubuntu.md
- documentation/en/join-devnet-cli.md
- documentation/en/mining.md
- documentation/en/retrieving-data.md
- documentation/en/setting-a-static-port.md
- documentation/en/storing-data.md
- documentation/en/testing-with-gui.md
- documentation/en/tracing.md
Whats in this PR?
+ Some trivial copy updates that were reflected on https://docs.lotu.sh but not in this repo.
+ @travisperson's contribution with swarm port updating. https://docs.lotu.sh/setting-a-static-port
> documentation: small copy updates

- chain/sync.go
- chain/sync_manager.go
- storage/sector_states.go
figured it probably makes sense to run some static analysis tools over the code before testnet. Working through some of it now.
> some fixes from staticcheck

- chain/actors/actor_miner.go
- go.mod
- go.sum
The previous number was picked fairly arbitrarily. This is a slightly nicer number.
> Set maximum sector ID to 2^48-1

- miner/miner.go
when the miner has power ，the hasPower  function shoud return ture;
> bugfix haspower meaning

- cmd/lotus-chainwatch/dot.go
then use `graphviz` to get images.
> add usage descript for chainwatch dot

- .circleci/config.yml
- build/paramfetch.go
- build/proof-params/parameters.json
- cli/params.go
- cmd/lotus-bench/main.go
- cmd/lotus-seed/seed/seed.go
- cmd/lotus-storage-miner/init.go
- cmd/lotus-storage-miner/run.go
- cmd/lotus/daemon.go
- lib/sectorbuilder/sectorbuilder.go
- lib/sectorbuilder/sectorbuilder_test.go
- node/builder.go
- node/modules/storageminer.go
> Params v20

- .circleci/config.yml
- chain/gen/gen.go
- cmd/lotus-seed/main.go
- cmd/lotus-seed/seed/seed.go
- lib/sectorbuilder/sectorbuilder.go
- lotuspond/spawn.go
- node/node_test.go
> Pre-sealing holes

- chain/sub/incoming.go
This will hopefully help us see why we're getting so many orphans
> flag blocks that are received too late

- chain/messagepool/messagepool.go
> Improve messagepool reorg checks

- chain/messagepool/messagepool.go
> Fix mpool sub not unsubbing

- documentation/en/api-troubleshooting.md
- documentation/en/api.md
- documentation/en/dev-tools-pond-ui.md
- documentation/en/getting-started.md
- documentation/en/install-lotus-arch.md
- documentation/en/install-lotus-macos.md
- documentation/en/install-lotus-ubuntu.md
- documentation/en/join-devnet.md
- documentation/en/mining-troubleshooting.md
- documentation/en/mining.md
- documentation/en/retrieving-data.md
- documentation/en/setting-a-static-port.md
- documentation/en/setup-troubleshooting.md
- documentation/en/storing-data-troubleshooting.md
- documentation/en/storing-data.md
- documentation/en/updating-lotus.md
*Whats in this PR?*
+ Feedback from numerous people on the team during the Filecoin TestNet wet run for our documentation.
+ New pages.
*Notes*
+ I'm merging this sooner than later so that we can get translations for these documents in time.
> documentation: latest updates from feedback across team

- .circleci/config.yml
- lib/sectorbuilder/sectorbuilder_test.go
- node/node_test.go
> Add short tests

- api/api_storage.go
- chain/actors/actor_miner.go
- chain/actors/actor_miner_test.go
- chain/actors/actor_paych_test.go
- chain/actors/cbor_gen.go
- chain/actors/harness2_test.go
- chain/types/bitfield.go
- chain/types/vmcontext.go
- chain/vm/mkactor.go
- chain/vm/syscalls.go
- chain/vm/vm.go
- gen/main.go
- storage/cbor_gen.go
- storage/sector_states.go
- storage/sector_types.go
- storage/sectors.go
I readded the faults logic here, and have started in on writing some miner actor tests to exercise it.
> Reintegrate sector faults

- chain/gen/gen.go
> Make snum cleaner

- documentation/cn/api-scripting-support.md
- documentation/cn/updating-lotus.md
- documentation/en/api-scripting-support.md
- documentation/en/api.md
- documentation/en/join-devnet.md
- documentation/en/mining.md
+ Scripting support as requested from #806 
+ Some Chinese translation placeholders.
+ Going to immediately merge since the change is non controversial.
> documentation: support for scripting auth environment variables

- Makefile
- cmd/lotus-shed/base16.go
- cmd/lotus-shed/base32.go
- cmd/lotus-shed/keyinfo.go
- cmd/lotus-shed/main.go
- cmd/lotus-shed/peerkey.go
I probably won't have time to actually make this look nice, but if someone wants to take this over and fix any issues / general code improvements it would be much appreciated <3
> A place for all the lotus tools

- cmd/lotus-bench/main.go
- cmd/lotus-seed/main.go
> Allow lotus-bench to run election post benchmark presealed sector directory

- chain/deals/client_states.go
- chain/messagepool/messagepool.go
> Smarter message rebroadcast

- documentation/en/updating-lotus.md
+ An addition to the update document.
+ Just merging this because the change is non-controversial.
> documentation: adds additional command to update instructions

- chain/blocksync/blocksync_client.go
- node/hello/hello.go
- peermgr/peermgr.go
> Collect hello message latency

- documentation/en/api-troubleshooting.md
- documentation/en/api.md
- documentation/en/hardware-mining.md
- documentation/en/join-devnet.md
- documentation/en/mining.md
- documentation/en/retrieving-data.md
- documentation/en/setup-troubleshooting.md
- documentation/en/storing-data-troubleshooting.md
- documentation/en/storing-data.md
+ Updates from testing sessions and feedback.
+ Minimal updates from https://filecoin.io/blog/filecoin-testnet-mining/
+ Skipping review because the changes are not controversial.
> documentation: updates from the testing session

- documentation/en/hardware-mining.md
- documentation/en/mining-troubleshooting.md
- documentation/en/mining.md
- documentation/en/storing-data.md
+ Some documentation updates that came in recently through testing.
+ This is one of the last times docs code will have to be committed manually.
> documentation: mining updates from recent TestNet updates

- api/api_storage.go
- build/paramfetch.go
- node/impl/storminer.go
- storage/sectorblocks/blockstore.go
Still need to investigate why clients return success after fetching no data
> Don't allow retrieval of unsealed data

- documentation/cn/join-testnet.md
- documentation/en/api.md
- documentation/en/dev-tools-pond-ui.md
- documentation/en/getting-started.md
- documentation/en/hardware-mining.md
- documentation/en/hardware.md
- documentation/en/install-lotus-arch.md
- documentation/en/install-lotus-macos.md
- documentation/en/install-lotus-ubuntu.md
- documentation/en/join-testnet.md
- documentation/en/mining-troubleshooting.md
- documentation/en/mining.md
- documentation/en/setting-a-static-port.md
- documentation/en/setup-troubleshooting.md
- documentation/en/storing-data.md
- documentation/en/updating-lotus.md
+ Last minute changes before TestNet launch.
+ Merging because most of these changes are approved outside of this PR from external conversations.
> documentation: testnet update

- node/hello/hello.go
> Fix timeoffset hello calculation

- documentation/en/hardware-mining.md
+ Some term changes in the hardware docs.
+ Merging because changes are non-controversial.
> documentation: updates terms for hardware docs

- Makefile
- build/version.go
- cmd/lotus-bench/main.go
- cmd/lotus-chainwatch/main.go
- cmd/lotus-fountain/main.go
- cmd/lotus-seal-worker/main.go
- cmd/lotus-seed/main.go
- cmd/lotus-storage-miner/main.go
- cmd/lotus/main.go
> Add version commit string

- build/forks.go
- chain/sync.go
> Fix candidate check

- go.mod
- go.sum
> chore(dep): update go-cid, go-datastore, go-ipfs-blockstore

- cli/state.go
Didn't notice https://github.com/filecoin-project/lotus/pull/868was based on this branch
> Actually merge #868 to master

- chain/validation/message.go
- chain/vm/validation_test.go
Add calls to Payment Channel tests, merge after #715
> chainval | paych tests

- chain/deals/client.go
- chain/deals/client_states.go
- chain/deals/client_storagemarket.go
- chain/deals/provider.go
- chain/deals/provider_asks.go
- chain/deals/provider_states.go
- chain/deals/provider_storagemarket.go
- chain/deals/provider_utils.go
- chain/deals/request_validation_test.go
- go.mod
- go.sum
- node/builder.go
- node/impl/client/client.go
- node/modules/services.go
- storagemarket/bigint.go
- storagemarket/types.go
- storagemarketadapter/client_adapter.go
- storagemarketadapter/provider_adapter.go
In order to extract and reuse storage market code, we need to insert some interfaces at the boundary of the Storage Market component.
Introduce and implement two interfaces as described in the [design doc](https://docs.google.com/document/d/1FfMUpW8vanR9FrXsybxBBbba7DzeyuCIN2uAXgE7J8U).  `StorageClient`, and `StorageClientNode`.
> Storage Market client interfaces

- lib/sectorbuilder/files.go
This should fix remote worker issues
Fixes #949 
Fixes #947
> sectorbuilder: Fix getpath

- chain/sync.go
This should make things a little faster. Unfortunately it only has a small impact on the overall sync slowness.
> parallelize bls message hashing for validation

- chain/sync.go
We're also calling TipSetState in main ValidateBlock flow - with this PR we're now checking BLS aggregate while that happens in background instead of after waiting for the state to be computed (which is the slowest part of the sync process currently) - and then running bls sig checks, saving a bit of time
> sync: Check bls aggregate early

- api/api_common.go
- api/test/test.go
- build/version.go
- cmd/lotus-shed/main.go
- cmd/lotus-storage-miner/init.go
- node/impl/common.go
Reverts filecoin-project/lotus#909
It appears to cause issues
> Revert "Refactor versions"

- chain/actors/aerrors/wrap.go
- chain/vm/vm.go
- go.mod
- go.sum
This is technically a fork, though if we hit any of the codepaths that this would change, it would fail block production.
> make serialization error non-fatal

- documentation/en/.glossary-english.json
- documentation/en/join-testnet.md
- documentation/en/local-dev-net.md
- documentation/en/mining-lotus-seal-worker.md
- documentation/en/mining-troubleshooting.md
- documentation/en/mining.md
+ Finally catching up on some feedback.
+ Moves the glossary over to the `documentation/en` folder.
+ Merging this PR because the changes are non-controversial.
> @jimmylee/docs update

- chain/types/bigint.go
- chain/types/bigint_test.go
> Fix SizeStr index out of band

- documentation/en/install-lotus-fedora.md
Installation packages are slightly different for fedora than ubuntu.
> adds fedora installation instructions

- extern/rleplus/rleplus_test.go
Just enhance the test for better understanding of the rleplus format.
> Enhance rleplus testing

- chain/actors/actor_miner.go
- chain/actors/actor_miner_test.go
- chain/actors/actor_storagepower.go
- chain/actors/harness2_test.go
- chain/types/bitfield.go
- chain/types/blockheader.go
- go.mod
- go.sum
Requires https://github.com/filecoin-project/go-sectorbuilder/pull/64
> Fix faults handling

- cmd/lotus-seal-worker/main.go
- cmd/lotus-storage-miner/main.go
- cmd/lotus/main.go
- lib/lotuslog/levels.go
Fixes https://github.com/filecoin-project/lotus/issues/1019
> Set logging levels in a single place

- chain/actors/actor_paych.go
- chain/actors/aerrors/wrap.go
- chain/vm/vm.go
Theres more to do here, but this is the direction i'm working towards
> reduce most vm errors to non-fatal, explicitly mark disk issues as fatal

- chain/actors/actor_storagemarket.go
- chain/deals/provider_utils.go
- storage/garbage.go
Need to check through this one very carefully, also need the specs team to give a +1 here.
> don't require signatures for self deals

- api/cbor_gen.go
- chain/blocksync/cbor_gen.go
- chain/types/blockheader.go
- chain/types/cbor_gen.go
- go.mod
- go.sum
- storage/cbor_gen.go
Depends on: https://github.com/whyrusleeping/cbor-gen/pull/4
> Add fork signaling to blockheader

- build/version.go
- chain/actors/actor_storagepower.go
Fixes https://github.com/filecoin-project/lotus/issues/1074
> Add additional checks to ACF

- Makefile
Fixes https://github.com/filecoin-project/lotus/issues/1069
> chainmatch: Append params rice box

- build/version.go
- chain/types/blockheader.go
- chain/types/signature.go
- chain/types/signature_cgo.go
We should audit for this better
> Fix nil signature verification

- Makefile
- cmd/lotus-health/main.go
- cmd/lotus-health/main_test.go
- cmd/lotus-health/systemd.go
- go.mod
- go.sum
watch if chain head changes in a given window of api polls
allows setting a threshold of how many times the chain head can remain
unchanged before failing health check
also can set interval for polling chain head
on failure, restarts systemd unit
> health agent to monitor lotus

- cmd/lotus-fountain/main.go
Ports the create miner fix to the fountain https://github.com/filecoin-project/lotus/pull/1088
> Add more collateral to CreateStorageMiner call in fountain

- storage/sector_states.go
It looks like I didnt finish this code, and didnt expect anyone to manually trigger this codepath. We can at least make it not panic for now. 
this code is going to all get reworked soon when @magik6k gets back to working on his sector failure handling code.
> fixup bitfield serialization in manual faulty sector handler

- build/forks.go
- chain/actors/actor_miner.go
- chain/actors/actor_miner2.go
otherwise we have to do  `DeclareFaults` each time we want to do fpost/epost, which is annoying
> correctly update proving set & sector set with amt2

- cmd/lotus-health/main.go
was passing wrong variable to updateWindow function argument.
also updates duplicate function comment
> fixes health agent bug

- storage/fpost_run.go
For debugging when someone hits this
> fpost: More logging

- cli/mpool.go
> mpool stat: Don't exit on StateGetActor error

- lib/jsonrpc/handler.go
- lib/jsonrpc/rpc_test.go
- lib/jsonrpc/websocket.go
> jsonrpc: Fix channel closing race

- chain/vm/invoker.go
- cmd/lotus-chainwatch/storage.go
- cmd/lotus-chainwatch/sync.go
> chainwatch: Store json states

- api/cbor_gen.go
- api/test/deals.go
- gen/main.go
- go.mod
- go.sum
- lib/statemachine/cbor_gen.go
- node/node_test.go
- storage/sealing/cbor_gen.go
- storage/sealing/fsm.go
Depends on https://github.com/whyrusleeping/cbor-gen/pull/5
> cbor-gen: Soft struct-map unmarshaling

- chain/actors/actors_test.go
- chain/actors/harness2_test.go
- chain/blocksync/blocksync.go
- chain/blocksync/blocksync_client.go
- chain/gen/utils.go
- chain/state/statetree.go
- chain/state/statetree_test.go
- chain/stmgr/forks.go
- chain/validation/state.go
- chain/vm/vm.go
- cmd/lotus/daemon.go
Working on debugging chain sync perf
> wire up tracing into state tree flush, add pprof flag

- tools/stats/chain.dashboard.json
Just updating the JSON here to match what we have on online.
> Sync dashboard to what we have on stats.testnet.filecoin.io

- documentation/en/storing-data.md
* Adds a command to check the status of a deal.
* Merging the PR because it isn't controversial.
> lotus client list-deals

- storage/sealing/garbage.go
- storage/sealing/utils.go
- storage/sealing/utils_test.go
Fixes #1156
Should shave off a few minutes from the process.
(Didn't test on a miner yet)
> sealing: Parallel CommP calc in pledge sector

- cmd/lotus-storage-miner/info.go
> fix:a bug of the power percentage in lotus-storage-miner info

- lib/rlepluslazy/bitvec.go
- lib/rlepluslazy/runs.go
> Fix small bug in RLE

- lib/rlepluslazy/bitvec.go
- lib/rlepluslazy/runs.go
This reverts commit 6ed57ede6a8aec1625f498cac5e5a75af6f45f5d.
> Revert "Fix small bug in RLE"

- build/forks.go
- build/version.go
- chain/actors/actor_miner2.go
- chain/actors/actor_storagepower.go
- chain/actors/forks.go
- chain/stmgr/forks.go
- cli/chain.go
- cmd/lotus-shed/bigint.go
- cmd/lotus-shed/main.go
> WIP, fork, fix slashing power calc

- chain/actors/actor_multisig.go
- chain/vm/invoker.go
- chain/vm/spec_shim.go
> Invoker autoshim

- cmd/lotus-storage-miner/init.go
- go.mod
- go.sum
- markets/storageadapter/provider.go
Fixing issues with go-fil-markets integration to hopefully make tests pass
Sorry for leaving head/lotus commit sha in an non-functional state.
> fix(go-fil-markets): fix integration

- chain/actors/actor_storagepower.go
- cli/state.go
a better view for cli `lotus state power` output, and
minor change of an error output
> better power show

- documentation/en/join-testnet.md
Follow up to: https://github.com/filecoin-project/lotus/issues/883#issuecomment-577364021
* Merging because its a non controversial change.
> documentation: adds file name length limit

- .circleci/config.yml
- .gitignore
- scripts/build-bundle.sh
- scripts/publish-release.sh
* creates a tarball of 'lotus', 'lotus-storage-miner' and
'lotus-seal-worker' for darwin and linux
* computes and saves IPFS CID and sha512sum for each architecture
* creates a github release and uploads all artifacts
* triggered by tags matching regex /^v\d+\.\d+\.\d+$/ ie. v0.1.0
> create and publish github release

- documentation/en/.library.json
- documentation/en/faqs.md
There's lots more that could be added, but I think this is a reasonable first version of an FAQs page.
> Docs: Add a Lotus-only FAQs section to the Lotus website.

- documentation/en/mining.md
We should be telling people what a bls wallet is, and how to create one if they don't have one.
> docs: Provide clearer instructions around bls wallets for miners

- chain/sub/incoming.go
- go.mod
- go.sum
- node/modules/services.go
Was thinking about doing more complicated things, decided this was good enough to ship for now.
Also cc @vyzo and @daviddias
> basic gossip spam protection logic

- cmd/lotus/debug_advance.go
- This was forgotten in commit 6097000
Resolves #1278 .
> Fix #1278: debug_advance should have its API calls updated

- cli/state.go
Resolves #1270
```
Owner:	t3u3w7psv5dudppp6yfiacdh6xmln44666skeylw5mun5uzv5rkkw7lgfbxnrfoeqo3ufiktwahheww6tgn6za
Worker:	t3u3w7psv5dudppp6yfiacdh6xmln44666skeylw5mun5uzv5rkkw7lgfbxnrfoeqo3ufiktwahheww6tgn6za
PeerID:	12D3KooWNFmyeVbLf6wvPrHNdiaJg5gawTuNmXyP8cKuZDEhPzXb
SectorSize:	32GiB (34359738368)
```
> cli: add state miner-info command

- .gitignore
- Makefile
> fix shed make mistake

- chain/sub/incoming.go
- go.mod
- node/modules/services.go
Someone is being annoying and spamming messages. This is a bit heavy handed, but it will definitely quell the spam.
@arajasek will be working on a better heuristic here moving forward.
> implement basic message filtering

- documentation/en/.library.json
- documentation/en/cli.md
- documentation/en/join-testnet.md
This PR makes 2 updates to the lotu.sh website:
1) As suggested by @terichadbourne, it changes some of the messaging around sync progress.
2) It adds a Command Line Interface section to describe how to use (what I think are) the most commonly used features of the CLI.
> Documentation updates

- go.mod
- go.sum
- markets/storageadapter/client.go
- markets/storageadapter/provider.go
- paychmgr/paych.go
Fix #1319 
- use sigs library for verification methods
- add signing to deal proposals
- builds on feat/more-paych-fixes so merge that first
> Fix signature verification in adapters

- build/params_shared.go
- chain/messagepool/messagepool.go
- go.sum
- node/impl/full/sync.go
- node/modules/lp2p/host.go
- node/modules/services.go
Somehow closed the previous one when trying to rebase it on top of testnet/3 branch...
> conform protocol ids to spec

- cli/client.go
- cli/net.go
- go.mod
- node/impl/common.go
some mildly broken things, there are probably more.
> fix a few libp2p related problems

- cli/chain.go
- cli/client.go
- cli/log.go
- cli/multisig.go
- cli/net.go
- cli/paych.go
- cli/send.go
- cli/state.go
- cli/sync.go
- cli/wallet.go
One commit to improve the `lotus import` UX (it currently waits for EOF and is unkillable by ^C), another to address #1307 and make minor CLI doc improvements.
> Re: #1307: Provide ArgsUsage for all CLI commands

- go.mod
- go.sum
- node/modules/lp2p/relay.go
> chore(dep): update dependencies

- cmd/lotus/debug_advance.go
My bad, I broke `make debug` in an earlier commit.
> fix make debug

- chain/stmgr/stmgr.go
this is probably what was causing block rewards to not show up
> pass ticket count into reward application message

- lib/jsonrpc/handler.go
- lib/jsonrpc/util.go
> Fix Error and Result being returne at the same time in JSON-RPC

- chain/validation/factories.go
- chain/vm/runtime.go
- chain/vm/vm.go
- go.mod
- go.sum
This PR:
- Makes address generation spec compliant
- corrects and cleans up the construction of ExecutionResults
- enables full validation of the latest chain-validation tests (and makes the tests pass).
> New Actor Addresses should be generated as per spec

- chain/state/statetree_test.go
@frrist just confirmed that this test also passes with the same value over in GFC!
> add simple test for helping to test state tree interop

- chain/gen/gen.go
- chain/sync.go
- go.sum
Afaic tell, these were the two places where the switch needed to be made.
> Use blake2b, not SHA, for VRFs

- .gitmodules
- chain/vectors/gen/main.go
- chain/vectors/vector_types.go
- chain/vectors/vectors_test.go
Still have some other things to add in here, but i wanted to get the PR up to show the integration
> Integrate updated serialization vectors as tests

- cmd/lotus-storage-miner/info.go
Just correct the number of waiting blocks.
> Correct the number of waiting blocks

- chain/store/store.go
- chain/store/store_test.go
- go.mod
- node/impl/full/chain.go
- node/impl/full/state.go
- node/impl/full/sync.go
I swear chain export worked before, But what was here was not functioning properly.
> Rewrite chain export walker function to actually do the right thing

- chain/state/statetree.go
- chain/stmgr/stmgr.go
- chain/sync.go
- chain/types/actor.go
- chain/types/vmcontext.go
- chain/vm/mkactor.go
- chain/vm/vm.go
Feel free to suggest or change anything here, the objective of this PR is to signal some places that could use a comment.
> doc: add comments related to actor code review

- chain/stmgr/stmgr.go
- chain/sync.go
- chain/validation/state.go
- chain/vm/invoker.go
- chain/vm/mkactor.go
- chain/vm/runtime.go
- chain/vm/validation_test.go
- chain/vm/vm.go
- go.mod
- go.sum
I'd like to get all the chainval tests passing here
> WIP: updating and getting chainval tests passing

- api/api_full.go
- api/apistruct/struct.go
- chain/stmgr/stmgr.go
- cli/state.go
- node/impl/full/state.go
- storage/miner.go
- storage/sealing/sealing.go
- This commit adds a new method called StateSearchMsg
- We can probably overhaul StateWaitMsg onto this new method at a later point in time
> Re: #1412: Add a non-blocking version of StateWaitMsg

- api/api_full.go
- node/impl/client/client.go
Same as #1392 but in `testnet/3`.
> Include DealID in DealInfo

- chain/events/events_called.go
- chain/events/utils.go
- chain/gen/genesis/util.go
- chain/messagepool/messagepool.go
- chain/messagepool/messagepool_test.go
- chain/state/statetree.go
- chain/stmgr/call.go
- chain/stmgr/stmgr.go
- chain/stmgr/utils.go
- chain/store/store.go
- chain/store/weight.go
- chain/types/message.go
- chain/types/signedmessage.go
- chain/validation/applier.go
- chain/validation/factories.go
- chain/validation/keymanager.go
- chain/validation/state.go
- chain/vm/mkactor.go
- chain/vm/runtime.go
- chain/vm/validation_test.go
- chain/vm/vm.go
Lots of little tweaks to get us to agree with chain-validation and go filecoin. I'd recommend reviewing commit by commit, the story won't be coherent otherwise.
Stuff around the new `ApplyImplicitMessage` probably needs the most careful review (commit 21a007f).
> Re: #1446: Enable gas tracking in validation tests

- cmd/lotus-storage-miner/run.go
@magik6k why did this get removed? I'm assuming it was an accident
> re add storage miner api flag

- cli/chain.go
This means you can now do
```
$ lotus chain get /pstate/@Ha:t01/1
[
{
"/": "bafy2bzacedxnenaw3za5i6zhyxo4i4zm5aixgpn6mxpj2ddz5gs7jggicdyzq"
},
107,
"interop"
]
```
> chain get: /pstate prefix

- api/api_full.go
- api/apistruct/struct.go
- chain/gen/gen.go
- chain/stmgr/utils.go
- chain/sync.go
- node/impl/full/state.go
Not *quite* done yet, but up here for early review
> Add GetMiningBaseInfo api and use it for mining

- chain/state/statetree.go
cuts my small benchmark from 13.5 seconds down to 10.5
> cache address resolutions in state tree

- api/api_full.go
- api/api_storage.go
- api/apistruct/struct.go
- build/params_shared.go
- chain/blocksync/cbor_gen.go
- chain/stmgr/utils.go
- chain/types/cbor_gen.go
- cli/chain.go
- cmd/lotus-storage-miner/info.go
- cmd/lotus-storage-miner/sectors.go
- node/builder.go
- node/hello/cbor_gen.go
- node/impl/full/chain.go
- node/impl/full/state.go
- node/modules/storageminer.go
- node/node_test.go
- storage/miner.go
- storage/sealing/cbor_gen.go
- storage/sealing/checks.go
- storage/sealing/fsm.go
- storage/sealing/fsm_events.go
- storage/sealing/fsm_test.go
- storage/sealing/sealing.go
- storage/sealing/states.go
- storage/sealing/states_failed.go
- storage/sealing/types.go
- storage/sealing/types_test.go
Those will break existing storage-miners
> FSM Updates

- Makefile
- cmd/lotus-storage-miner/main.go
- cmd/lotus/main.go
- scripts/README
- scripts/bash-completion/lotus
- scripts/bash-completion/lotus-storage-miner
- scripts/make-completions.sh
- scripts/zsh-completion/lotus
- scripts/zsh-completion/lotus-storage-miner
ZSH completions aren't getting picked up correctly, not sure why
> Shell completions

- cmd/lotus-storage-miner/init.go
- go.mod
- go.sum
- markets/storageadapter/provider.go
- node/impl/storminer.go
- node/modules/storageminer.go
- storage/miner.go
- storage/sealing.go
- storage/sectorblocks/blocks.go
The node needs to provide the FSM some guidance for how it should select a pre-commit expiration. It does this by providing a value of some type which satisfies `PreCommitPolicy` interface (in this case, `BasicPreCommitPolicy`).
Also, the ticket-acquiring function is expected to be passed a tipset identifier.
> provide deal scheduling info to FSM so that it can set pre-commit expiry

- cmd/lotus-fountain/main.go
Ups the general bucket size to support more users hitting the faucet at the same time, and ensure we are using the forwarded ip address.
> Rate limit fix

- cli/client.go
- markets/storageadapter/client.go
- node/modules/storageminer.go
- Resolve miner address to key address before siggy verification during query-ask
- Include max piece size info in query-ask
- Set max piece size to sector size by default
> Various improvements to deal workflow

- chain/vm/gas.go
- chain/vm/gas_v0.go
- chain/vm/mkactor.go
- chain/vm/runtime.go
- chain/vm/vm.go
Basically changes to "do what go-filecoin does"
> Remove SysErrInternal, some interop / spec changes

- chain/stmgr/forks_test.go
- chain/vm/runtime.go
- chain/vm/vm.go
This is a thing go-filecoin does.
> caller must be validated exactly once

- chain/beacon/drand/drand.go
The gfc team reports that theres been no flakiness on this endpoint. My tests locally also report that its stable, but i'm assuming that once we deploy a network, its going to get hit with a ton of traffic and be just as flaky.
We can switch to this and see what happens though.
> use other drand server for now

- build/params_shared.go
- storage/wdpost_sched.go
> Minor / irrelevant improvements go here

- chain/blocksync/cbor_gen.go
- chain/gen/genesis/miners.go
- chain/types/cbor_gen.go
- chain/types/message.go
- go.mod
- go.sum
- node/hello/cbor_gen.go
- node/impl/full/state.go
Probably could use some more checks around in different places, but this should work well enough.
The chain validation code will need to be updated, as now messages are slightly bigger and consume more gas
> add version field to message type

- chain/gen/gen.go
- chain/gen/gen_test.go
- go.mod
- go.sum
Fails with hamt commit `f354769`
> Update HAMT and cbor, test to demonstrate HAMT issue

- chain/stmgr/utils.go
- chain/types/bigint.go
- cmd/lotus-storage-miner/info.go
- cmd/lotus-storage-miner/storage.go
- cmd/lotus-storage-miner/workers.go
- go.mod
> storageminer: Improve CLI UX

- chain/stmgr/utils.go
- chain/sync.go
- miner/miner.go
discrepancy between lotus and gfc, gfc's approach seems cleaner to me, and both are effectively the same, so we're switching
> winning post wants the actual epoch of the block, not the previous

- cli/state.go
- go.mod
Example output: https://ipfs.io/ipfs/QmcWAXbRCPNUjw4e2mWfn2UwCQy4FXs4hvAuAHQBdJCcGc/exec.html
> compute-state: Add html output option

- chain/vm/vm.go
As it currently stands, we don't transfer gas out of the holder to the reward actor if we fail to charge for retValue (and may not correctly revert either).
> Bugfix: Correctly transfer gas when failing to charge for retValue

- cmd/lotus-shed/main.go
- cmd/lotus-shed/params.go
Makes deployment easier for some stuff.
> Add param fetch to lotus-shed

- chain/events/events.go
- chain/events/events_called.go
- chain/events/events_test.go
- storage/miner.go
> events: Fix revert+apply of msg execution, but not the message

- chain/gen/genesis/t06_vreg.go
The lotus team will be holding this for now...
> set verifreg root key

- chain/sync.go
- miner/miner.go
otherwise we'll run into this: https://github.com/filecoin-project/lotus/blob/master/chain/vm/vm.go#L279
> use chainmsg type instead of unsigned message for gas price checking

- documentation/en/join-testnet.md
- documentation/en/mining.md
- node/hello/hello.go
typos are bad, especially in URLs
> Fix 3 typos

- chain/events/events.go
- chain/events/events_test.go
- miner/miner.go
Previously it was taking ~30s, with this PR it takes ~1s (yes, the same mpool, I didn't restart the main node between tests)
> miner: Optimize SelectMessages

- node/impl/full/state.go
It can change a bit with time, and can course commit message to fail, this should prevent that
> state: Calculate slightly larger initial pledge

- go.mod
- go.sum
> Update sector-storage with relaxed commit2 resource numbers

- chain/sub/incoming.go
- chain/types/blockheader.go
- go.mod
- go.sum
- lib/sigs/sigs.go
- node/modules/lp2p/pubsub.go
- node/modules/services.go
Implements actual validation logic in the block validator so that we can't get bogus blocks that can simply be decoded.
Edit: also makes a modification in the behaviour of the message validator to provide a rejection signal.
> Improved pubsub block validator

- chain/types/blockheader_test.go
Written as an aid to achieve Lotus-gfc interoperability
> Add an interop test for block header serialisation

- .github/ISSUE_TEMPLATE/sealingfailed.md
That's how you auto-assign the label, right?
> Create an issue template for mining issues

- api/api_full.go
- api/docgen/docgen.go
Sample output: https://ipfs.io/ipfs/QmZqAv7Rj6rLv9EC5ho8S1JYYGZBnF3M8dnnsok2GzrSjU
> improving the autogenerated api docs

- cmd/lotus-bench/import.go
- node/modules/chain.go
has a significant perf improvement on vm.Flush calls
> add blockstore 'Has' caching

- cmd/lotus-shed/main.go
- cmd/lotus-shed/proofs.go
- go.sum
Needed to manually verify a seal proof. This should do it (havent tried it yet, missing some inputs)
> put a command for verifying seals into the shed

- storage/wdpost_run.go
> Set largest gaslimit for wdpost

- storage/wdpost_run.go
> Fix:the input sectors of wpost  must match with the minerActor

- storage/wdpost_run.go
> fix: add deadline index for wdpost

- Makefile
- documentation/en/install-systemd-services.md
- scripts/lotus-daemon.service
Add resource limits for memory and file descriptors open. Include docs for usage.
Closes #330
> Update systemd usage and docs

- documentation/en/api.md
> update struct.go github url

- node/modules/storageminer.go
fix #1857 
Eek.. there's a missing error check! something is still wrong with users setup, but it shouldn't panic.
> Add missing err check in storage ask initialization

- chain/vm/vm.go
- go.mod
- go.sum
And don't allow people to print money.
> Correctly handle transfers with sender = receiver

- miner/miner.go
Fixes: https://github.com/filecoin-project/lotus/issues/1845
> Fix block production timing to avoid mining old tipset

- api/api_worker.go
- api/apistruct/struct.go
- cmd/lotus-bench/main.go
- cmd/lotus-storage-miner/init.go
- cmd/lotus-storage-miner/storage.go
- go.mod
- go.sum
- markets/retrievaladapter/provider.go
- node/config/def.go
- node/repo/fsrepo.go
- node/repo/interface.go
- node/repo/memrepo.go
> Update sector-storage with ReadPiece impl

- Makefile
- documentation/en/.library.json
- documentation/en/install-systemd-services.md
- scripts/lotus-daemon.service
Deliver:
- https://github.com/filecoin-project/lotus/pull/1852#issuecomment-634960819
- https://github.com/filecoin-project/lotus/pull/1852#pullrequestreview-419688250
> Add systemd documention to table of contents

- cmd/lotus-shed/verifreg.go
> add commands to check individual balances for verifiers and clients

- .circleci/config.yml
- api/api_storage.go
- api/test/test.go
- api/test/window_post.go
- node/node_test.go
- storage/wdpost_run.go
* Actively report faults for the next deadline
* Skip sectors which can't be proven
(I didn't test this at all)
> wdpost: Better fault handling

- node/repo/interface.go
> error message to tell user why repo is already locked

- api/api_full.go
- api/apistruct/struct.go
- node/impl/full/state.go
Does the thing in #1602, tested on Testnet Phase 2
> Add an API method to list all faults occuring in a certain range

- Makefile
- api/test/test.go
- build/params_2k.go
- build/params_debug.go
- build/version.go
- cli/version.go
- cmd/lotus-bench/main.go
- cmd/lotus-chainwatch/main.go
- cmd/lotus-fountain/main.go
- cmd/lotus-health/main.go
- cmd/lotus-seal-worker/main.go
- cmd/lotus-seed/main.go
- cmd/lotus-storage-miner/main.go
- cmd/lotus/main.go
- node/impl/common/common.go
- node/modules/lp2p/host.go
Before:
```
0.4.0+api0.3.0
lotus version 0.4.0'+git7003960f.dirty'
```
After:
```
Daemon:  0.4.0+api0.3.0
Local: lotus version 0.4.0.debug+git.aa1a8d56.dirty
```
> Include build type in version

- go.mod
- go.sum
This should fix chain exports.
> update to fixed jsonrpc library

- cmd/lotus/daemon.go
- go.sum
fixes #1893 
Expand import-chain directory before importing.
> Expand tilde before passing file name into chain import

- chain/stmgr/stmgr.go
> search for a message should stop if we reach sender nonce of 0

- cli/params.go
- cmd/lotus-bench/main.go
- cmd/lotus-seal-worker/main.go
- cmd/lotus-shed/params.go
- cmd/lotus-storage-miner/init.go
- cmd/lotus/daemon.go
- go.mod
- go.sum
- node/modules/storageminer.go
> pass context to paramfetch.GetParams

- chain/vm/syscalls.go
> add a simple semaphore to batch verify seals

- cmd/lotus-storage-miner/proving.go
```
deadline  sectors  partitions  proven  
0         88       44          44
1         88       44          44
2         88       44          44
3         88       44          44  (current)
4         87       44          0
5         86       43          0
6         86       43          0
7         86       43          0
8         86       43          0
9         86       43          0
10        86       43          0
11        86       43          0
12        84       42          0
13        84       42          0
14        84       42          0
15        84       42          0
16        84       42          0
17        84       42          0
18        84       42          0
19        84       42          0
20        84       42          0
21        84       42 …
```
> Make lotus-storage-miner deadlines correct

- api/api_full.go
- api/apistruct/struct.go
- chain/wallet/wallet.go
- cli/wallet.go
- node/impl/full/wallet.go
It does the thing, closes 1939, which is the year World War Two began.
> Add delete functionality to the wallet

- miner/miner.go
Should address #1909, and likely other issues we've run into of this sort.
> don't update the mining base if mining fails for some reason

- api/apistruct/struct.go
- cmd/lotus-bench/main.go
- go.mod
- go.sum
- storage/wdpost_run.go
> Update sector-storage with better post faults

- go.mod
- go.sum
It restores line informations in log messages
> Update go-log to master

- build/proof-params/parameters.json
- cmd/lotus-bench/main.go
- go.mod
- go.sum
> v27 parameters

- chain/store/index.go
- chain/store/index_test.go
From https://github.com/filecoin-project/lotus/pull/1982
> chainstore index: Drop wrong check

- chain/vm/syscalls.go
> fix:the condition of time-offset mining fault

- .circleci/config.yml
- cli/params.go
- documentation/en/local-dev-net.md
> Improve UX of fetch-params

- cli/state.go
The output should be roughly the same, but the code is now a bit nicer
Closes https://github.com/filecoin-project/lotus/issues/1990
> compute-state html: Convert to templates

- chain/gen/genesis/miners.go
- cli/chain.go
- cli/state.go
Add some missing checks and fix some shadowing.
> nit: unchecked errors

- cmd/lotus-storage-miner/proving.go
I think proving command has a corresponding information description will be better.
> Add usage information for provingInfoCmd

- storage/wdpost_run.go
Caused https://ipfs.io/ipfs/QmNkPEsWkQ8c5ZstoUSBHW83zPFkugBCXNCaZzGMQS2uLe/exec.html#bafy2bzacec2r6padpt4btldv6zebr3anf2sxuztalt7ests422em63qf6en6q
> wdpost: Submit recoveries for sectors within a deadline

- go.mod
- go.sum
- node/builder.go
- node/impl/storminer.go
- node/modules/client.go
- node/modules/services.go
- node/modules/storageminer.go
Updates to latest fil markets with resumability and other new features
- update deps
- minor fixes to startup logic
- otherwise no major changes to code
> Update to fil-markets 0.3.0

- chain/gen/gen.go
- chain/sync.go
- cmd/lotus/debug_advance.go
- node/impl/full/wallet.go
We had a few issues that broke this command, works again with this PR
> Make advance-block work

- tools/stats/metrics.go
Increase the perf for looking up miner power, and reduces strain on influxdb by only writing miners with power.
> stats: increase miner power lookup perf

- go.mod
- go.sum
Those should be the last updates before the reset
* https://github.com/filecoin-project/specs-actors/compare/v0.6.0...v0.6.1
* https://github.com/filecoin-project/filecoin-ffi/blob/master/CHANGELOG.md#0300
* https://github.com/filecoin-project/rust-fil-proofs/blob/master/CHANGELOG.md#400---2020-06-15
> Pre-testnet reset updates

- go.mod
- go.sum
Fixes https://github.com/filecoin-project/lotus/issues/1968
Fixes https://github.com/filecoin-project/lotus/issues/1956
Fixes https://github.com/filecoin-project/lotus/issues/2035
> Update storage FSM with a bunch of fixes

- cmd/lotus-bench/main.go
> Spelling: s/winnnig/winning/

- go.mod
- go.sum
See https://github.com/filecoin-project/sector-storage/pull/51
> Update sector-storage with 32G checkFiles fix

- api/api_common.go
- api/api_full.go
- api/docgen/docgen.go
- build/params_testnet.go
Preview: https://gist.github.com/magik6k/cbfa2781c27a4158903c4ab7db6b98d0
> docgen improvements

- documentation/en/architecture.md
> doc: Fix architecture broken link

- Makefile
- documentation/en/.library.json
- scripts/chainwatch.service
- scripts/lotus-daemon.service
- scripts/lotus-miner.service
Add chainwatch service with make install directives. Fix documentation menu links for new item.
Unsure if we want to include documentation around this. If so, I'd be happy to add it if you let me know where the best place might be.
> Add chainwatch systemd svc config

- cmd/lotus-storage-miner/actor.go
- cmd/lotus-storage-miner/info.go
- cmd/lotus-storage-miner/main.go
This lets you set multiaddrs for your miner, but we don't use them quite yet. that needs some changes in the markets first
> add command to change registered multiaddrs for miner

- cmd/lotus-chainwatch/sync.go
Use the tipsetkey corresponding to the stateroot when fetching actor
data from the lotus api.
> fix: use tipset corresponding to stateroot

- go.mod
- go.sum
Depends on:
This should make deals get into sealed state much faster
> sealing: Give priority to sectors with deals

- chain/types/message.go
- documentation/en/block-validation.md
Rendered [here](https://github.com/filecoin-project/lotus/blob/schomatis/doc/security/block-validation/documentation/en/block-validation.md).
-------------------------
@Kubuxu I need you to finish this document about validations for incoming blocks. Please review if the listed items are correct, if there are some relevant checks missing and complete/resolve the remaining `FixMe`s in the text (most are related to randomness). The document is already 80-90% done so this shouldn't take too much of your time, ping me if you observe otherwise.
> doc: block validations

- chain/events/state/predicates_test.go
As suggested in https://github.com/filecoin-project/lotus/pull/2153#discussion_r446454405
> Add more predicate tests

- cmd/lotus-chainwatch/main.go
- cmd/lotus-chainwatch/storage.go
- cmd/lotus-chainwatch/sync.go
- makes progress towards /sentinel/issues/10
- follow on to #2140, will need a rebase after addressing feedback there
> fix: update miner_head table with new miner fields

- chain/sync.go
- Arbitrarily put a drift of 5, this should probably be some constant
- The `Syncer` is a somewhat odd place to put the function, open to hearing suggestions
Closes #1986
> Do not connect to peers with impossibly high heads

- lib/sigs/bls/bls_bench_test.go
```
goos: darwin
goarch: amd64
pkg: github.com/filecoin-project/lotus/lib/sigs/bls
Benchmark_blsSigner_Sign-12      	     469	   2558543 ns/op
Benchmark_blsSigner_Verify-12    	     188	   6223267 ns/op
PASS
ok  	github.com/filecoin-project/lotus/lib/sigs/bls	4.114s
```
> add bench mark for bls sign and verify

- chain/gen/mining.go
- go.mod
- go.sum
WIP Something about the update makes tests sad:
```
--- FAIL: TestSyncSimple (0.08s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xe20d76]
goroutine 37 [running]:
testing.tRunner.func1.1(0x2c98320, 0x54d5ac0)
/usr/lib/go/src/testing/testing.go:940 +0x4dc
testing.tRunner.func1(0xc00042e900)
/usr/lib/go/src/testing/testing.go:943 +0x317
panic(0x2c98320, 0x54d5ac0)
/usr/lib/go/src/runtime/panic.go:975 +0x41b
github.com/filecoin-project/filecoin-ffi/generated.(*FilAggregateResponse).Deref(0x0)
/home/magik6k/github.com/filecoin-project/go-lotus/extern/filecoin-ffi/generated/cgo_helpers.go:227 +0x26 …
```
> Update FFI to 0.30.1

- chain/sync.go
This breaks master build, will merge now (reviews still welcome)
> sync: Fix build

- chain/events/state/predicates.go
- chain/events/state/predicates_test.go
- go.mod
- go.sum
- markets/storageadapter/client.go
- node/impl/client/client.go
This includes https://github.com/filecoin-project/lotus/pull/2178 and latest changes to markets, as well as merge of commits from master to make sure everything is up to date. It's merged to next cause we have some protocol changes
> Markets update 0.3.2

- api/api_full.go
- cli/client.go
- node/impl/client/client.go
> CLI: add --verified-deal flag to lotus client deal

- api/api_full.go
- cli/client.go
- node/impl/client/client.go
Fixes https://github.com/filecoin-project/lotus/issues/2196
> CLI: add --fast retrieval flag to lotus client deal

- miner/miner.go
> miner: Fix mpool too-high-nonce-msgs log

- cmd/lotus-storage-miner/sectors.go
- go.sum
It does the thing, and it works.
> Add CLI command to manually start sealing a sector

- chain/badtscache.go
- chain/sync.go
Track original cause of blocks being marked as bad.
> Add better description to bad blocks

- cli/client.go
- cli/multisig.go
- cli/state.go
Been working on this for a while...
> Minor CLI improvements

- api/api_full.go
- api/apistruct/struct.go
- cli/client.go
- cmd/lotus-shed/verifreg.go
- node/impl/full/state.go
Fixes https://github.com/filecoin-project/lotus/issues/2222
> StateAPI for Verified Data Cap

- markets/storageadapter/client.go
- markets/storageadapter/provider.go
Fixes issue comment https://github.com/filecoin-project/lotus/pull/2315/files#r451432232
> Adjust OnDealExpiredOrSlashed timeout to deal expiry

- chain/events/state/ctxstore.go
- chain/events/state/diff_adt.go
- chain/events/state/diff_adt_test.go
- chain/events/state/predicates.go
- go.sum
Generalize the comparison of ADT arrays states for reuse in https://github.com/filecoin-project/lotus/pull/2322
> polish: genericize adt array diff & extract store

- cmd/lotus-storage-miner/proving.go
- node/impl/client/client.go
> correct error message

- chain/types/bigint_test.go
- chain/types/fil.go
No rush on merging this, but it would make peoples lives a bit easier.
> produce and parse FIL suffix on FIL strings

- paychmgr/paych.go
- paychmgr/paych_test.go
- paychmgr/simple.go
- paychmgr/state.go
- paychmgr/store_test.go
Fixes several bugs with payment channel manager
- Lane allocation
- Adding duplicate vouchers
- Nonce checking
> Refactor payment channel manager

- chain/gen/genesis/miners.go
- chain/gen/genesis/t02_reward.go
- chain/gen/genesis/t04_power.go
- chain/stmgr/utils.go
- chain/vm/runtime.go
- chain/vm/vm.go
- go.mod
- go.sum
- node/impl/full/state.go
> specs actors update

- api/api_full.go
- api/apistruct/struct.go
- build/version.go
- cli/multisig.go
- cli/state.go
- node/impl/full/multisig.go
- node/impl/full/state.go
- storage/adapter_storage_miner.go
- Add missing unlockDuration param to MsigCreate
- Removed redundant proposer param from MsigCancel
- Return a tipsetkey, not tipset, in MsgLookup
- Add Height to MsgLookup
> API improvements

- api/api_full.go
> api/api_full.go: fix method signature

- cli/multisig.go
discovered during a hackfs workshop
> clarify multisig create helptext

- cmd/lotus-chainwatch/storage.go
- cmd/lotus-chainwatch/sync.go
Track Deal Proposals and Deal State Changes.
> feat: add deal state and proposal tracking to cw

- api/api_full.go
- api/apistruct/struct.go
- cli/multisig.go
- cli/send.go
- node/impl/full/multisig.go
> SwapSigner API methods

- chain/gen/gen.go
- chain/vm/vm.go
- go.mod
- go.sum
- node/impl/full/chain.go
- storage/mockstorage/preseal.go
These are the final steps to get https://github.com/multiformats/multicodec/pull/161#issuecomment-618160880 implemented 
I will convert this to a proper PR once the underlying pieces are properly tagged
/cc @magik6k @whyrusleeping
> Bump fil-commcid and filecoin-ffi deps

- chain/stmgr/call.go
- chain/stmgr/stmgr.go
- chain/vm/runtime.go
> Increase cron gas

- go.mod
- go.sum
- node/modules/storageminer.go
https://github.com/filecoin-project/sector-storage/pull/67
> Update sector-storage with window based scheduler

- lib/ipfsbstore/ipfsbstore.go
Use IPFS clients in offline mode, and control `Stat` edge case without bubbling an error. 
Error string message is used since there's not sentinel nor error type solution for checking that case.
> ipfsbstore: offlinemode, and Has() fix

- api/api_full.go
- api/apistruct/struct.go
- chain/events/state/predicates_test.go
- chain/gen/genesis/genesis.go
- go.mod
- go.sum
This updates actors to this branch - https://github.com/filecoin-project/specs-actors/pull/717
> Update specs-actor with unsafa param fixes

- cli/auth.go
> only show updated env

- miner/miner.go
using crypto rand because it needs to be very unguessable, and i didnt feel like seeding math/rand.
> mitigate epoch boundary attacks by randomizing cutoff

- api/api_storage.go
- api/apistruct/struct.go
- cli/cmd.go
- cmd/lotus-storage-miner/main.go
- cmd/lotus-storage-miner/sealing.go
- go.mod
- go.sum
- node/impl/storminer.go
>  miner: sealing jobs command 

- cli/mpool.go
As requested by @magik6k (though i'm not sure if this is any better than just piping `mpool pending` through `jq`
> implement mpool find cmd

- chain/sync_test.go
this or remove the client altogether
> run VerifyWinningPoStProof test on client node

- README.md
> update devnet in readme

- node/impl/full/wallet.go
Necessitated by changes in https://github.com/filecoin-project/lotus/pull/2413
Fixes #2510
> Wallet balance should display 0 if address can't be resolved

- lib/bufbstore/buf_bstore.go
> Implement buffered blocktore GetSize()

- chain/vectors/vectors_test.go
- cmd/lotus-bench/import.go
- cmd/lotus-seed/genesis.go
- cmd/lotus-seed/main.go
- cmd/lotus-shed/import-car.go
- cmd/lotus-shed/keyinfo.go
- cmd/lotus/daemon.go
- node/impl/client/client.go
- node/repo/fsrepo.go
> close file

- cli/paych.go
Fixes https://github.com/filecoin-project/lotus/issues/2502 https://github.com/filecoin-project/go-fil-markets/issues/328
Depends on https://github.com/filecoin-project/lotus/pull/2465
> Add CLI commands to settle & collect payment channels

- api/test/window_post.go
- go.mod
- go.sum
- node/node_test.go
- storage/wdpost_run.go
Caught in https://github.com/filecoin-project/lotus/pull/2521#issuecomment-662848782
> wdpost: Correctly skip partitions with no sectors

- api/api_full.go
- go.mod
- go.sum
- node/impl/client/client.go
Upgrade to latest fil-markets with some fixes
- update to latest tagged fil -markets
- make sure we pipe all parameters through the retrieval process (this should improve reliability for retrieval as we will be specifying pieceCID)
> Update to markets 0.5.1

- cmd/lotus-seal-worker/main.go
port is required and things will break otherwise
> add port to default address flag

- chain/gen/genesis/genesis.go
A recent change in specs-actors causes genesis miners that include deals in their pre-sealed sectors
> Genesis miners need to be registered in the market actor's balance table

- cmd/lotus-seal-worker/main.go
- cmd/lotus-storage-miner/init.go
- go.mod
- go.sum
- node/config/def.go
See https://github.com/filecoin-project/sector-storage/pull/80
> Update sector-storage, parallel fetch limit

- api/api_storage.go
- api/apistruct/struct.go
- api/test/window_post.go
- cmd/lotus-storage-miner/sealing.go
- go.mod
- go.sum
- node/impl/storminer.go
- node/node_test.go
Fixes https://github.com/filecoin-project/lotus/issues/2591
Fixes https://github.com/filecoin-project/lotus/issues/2519
> Update sector-storage, sealing sched-diag

- cmd/lotus-chainwatch/processor/processor.go
- cmd/lotus-chainwatch/processor/reward.go
We need to track tipset following null rounds when calculating base block rewards in the null actor.  Until a better design is reached this will have to suffice.
> fix: Chainwatch handle null rounds

- documentation/en/join-testnet.md
New section for the docs.lotu.sh site including links to https://docs.filecoin.io/mine/connectivity/
> add connectivity configuration to the steps for joining testnet

- chain/stmgr/forks.go
- chain/stmgr/forks_test.go
- chain/stmgr/stmgr.go
- chain/stmgr/utils.go
- chain/validation/applier.go
Closes https://github.com/filecoin-project/lotus/issues/2234
> stmgr: Execute cron tick on null rounds

- cmd/lotus-storage-miner/proving.go
```
deadline  partitions  sectors (faults)  proven partitions
0         64          128 (0)           0
1         64          128 (0)           0
2         64          128 (0)           0
3         64          128 (0)           0
4         64          128 (0)           0
5         64          128 (0)           0
6         64          128 (0)           0
7         64          128 (2)           0
8         64          128 (1)           0
9         64          128 (120)         0
10        64          128 (0)           0
11        64          128 (0)           0
12        64          128 (0)           0
13        64          128 (0)           0
14        64          128 (0)           0
15        64          128 (0)           0
16        62          124 (0)           62 …
```
> Better miner proving deadlines

- go.mod
- go.sum
use 0.5.2 instead of custom commit for go-fil-markets
That's it!
> Update to tagged go-fil-markets

- api/api_full.go
- chain/stmgr/utils.go
- chain/sub/incoming.go
- chain/sync.go
- miner/miner.go
> Use specs actor's MinerNominalPowerMeetsConsensusMinimum

- build/params_shared_vals.go
- build/params_testground.go
- chain/gen/genesis/genesis.go
- chain/gen/genesis/miners.go
- chain/stmgr/call.go
- chain/stmgr/forks_test.go
- chain/stmgr/stmgr.go
- chain/stmgr/utils.go
- chain/store/weight.go
- chain/types/bigint.go
- chain/validation/applier.go
- chain/vm/runtime.go
- chain/vm/vm.go
> Correct calculation of TotalCircSupply

- cmd/lotus-storage-miner/actor.go
> Set default set-addrs gas limit to 0

- chain/messagepool/messagepool.go
Reverts filecoin-project/lotus#2667
> Revert "Prevent Pushing messages not valid for block inclusion"

- .github/labels.yml
> fix: add label for incentinet back

- README.md
Hi folks, this is just the first commit in an attempt to help support and get the work tracker up to date in light of the upcoming milestones. 
I'll document how it is setup as I get it setup and then request for your review.
> Towards an updated work tracker

- chain/market/fundmgr.go
> Fundmanager shouldn't try to add zero

- documentation/en/install-lotus-ubuntu.md
Since Interopnet is no longer there
> remove Interopnet related instructions in the documentation

- .circleci/config.yml
- chain/types/message.go
- chain/vm/runtime.go
- chain/vm/vm.go
- go.mod
- go.sum
Depends on: https://github.com/filecoin-project/chain-validation/pull/226
> Allow messages with not enough funds for transfer to apply

- chain/sub/incoming.go
Follow-up to https://github.com/filecoin-project/lotus/pull/2618.
> fix: block validator: check against heaviest tipset

- documentation/en/mining.md
This PR adds instructions for multiaddresses to the mining page.
> Multiaddress instructions added

- api/api_worker.go
- api/apistruct/struct.go
- go.mod
- go.sum
> Update sector-storage with ReadPiece fixes

- api/api_storage.go
- api/apistruct/struct.go
- cli/client.go
- cmd/lotus-shed/mpool.go
- cmd/lotus-storage-miner/main.go
- cmd/lotus-storage-miner/pieces.go
- go.sum
- markets/retrievaladapter/provider.go
- markets/storageadapter/provider.go
- node/impl/storminer.go
Working on improving retrieval.
- Expose utilities to inspect retrieval data on the miner side
- add a `lotus client info` command
- fix the output of `lotus client get-deal`
- make the default output of `lotus client list-deals` more compact
- update to version of go-fil-markets with a number of fixes
- misc other improvements
> Retrieval improvements

- markets/loggers/loggers.go
- node/modules/client.go
- node/modules/storageminer.go
Provide nice logs for what's going on with markets accross the board
Markets software will tell you when any events happen. We can produce nice logs by subscribing to those events and outputing logs for them
This may be on the chatty side -- it could be moved to DEBUG level?
> Better Event Logging For Markets

- api/api_full.go
- api/apistruct/struct.go
- cli/client.go
- go.mod
- node/impl/client/client.go
- node/modules/client.go
Definitely can do a lot more, and be a fair bit nicer, but it's a massive improvement already:
> client cli: Interactive deal command

- cmd/lotus-storage-miner/market.go
- markets/dealfilter/cli.go
- node/builder.go
- node/config/def.go
- node/modules/dtypes/miner.go
- node/modules/storageminer.go
Should mostly address https://github.com/filecoin-project/lotus/issues/1874
TODO:
> Support external deal decision logic

- api/test/ccupgrade.go
- api/test/window_post.go
- go.mod
- go.sum
- node/impl/storminer.go
- storage/wdpost_run.go
Fixes https://github.com/filecoin-project/lotus/issues/2726
>  wdpost: Fix Fault/Recovery declaration timing 

- cmd/lotus-chainwatch/processor/market.go
- cmd/lotus-chainwatch/processor/miner.go
- cmd/lotus-chainwatch/processor/processor.go
Create table `minerid_dealid_sectorid` that relates dealIDs to the sector they are contained in.
> feat(chainwatch) define relation from dealIDs to sectorID

- api/test/window_post.go
- cli/client.go
- go.mod
- go.sum
- lib/tablewriter/tablewiter_test.go
- lib/tablewriter/tablewriter.go
> client cli: Improve list-deals output 

- api/api_storage.go
- api/apistruct/struct.go
- cmd/lotus-storage-miner/retrieval-deals.go
- node/impl/storminer.go
Add `retrieval-deals list` which shows current retrieval deals:
```
% ./lotus-miner retrieval-deals list
Receiver                                              DealID  Payload      State                PricePerByte  BytesSent  Message
12D3KooWAdioKgpq7Da8FgkQsvisdtiBMSxTpwRVjLxGrau8a4pn  0       ...vobb3dca  DealStatusUnsealing  2             0
```
> Add CLI to list retrieval deals

- cli/cmd.go
- cli/net.go
- cli/version.go
- cmd/lotus-storage-miner/info.go
- cmd/lotus-storage-miner/info_all.go
- cmd/lotus-storage-miner/market.go
`lotus-miner info all` -> https://ipfs.io/ipfs/QmdcGokRQNUSEoezAmC9FgsjguL1DndLoH7xcB3dmyqMUM/allinfo
> miner: Command to dump all miner info

- cmd/lotus-storage-miner/storage.go
- go.mod
- go.sum
> Update sector-storage with fetch storage reservation

- go.mod
- go.sum
- storage/adapter_storage_miner.go
> Update FSM with sealing fixes

- paychmgr/simple.go
Supersedes https://github.com/filecoin-project/lotus/pull/2870
> Bail out if there's an error writing state to store

- chain/messagepool/selection_test.go
see bug in https://github.com/filecoin-project/lotus/pull/2882
> add regression test for selection trimming

- api/api_full.go
- api/apistruct/struct.go
- chain/messagepool/config.go
- chain/messagepool/messagepool.go
- chain/messagepool/messagepool_test.go
- chain/messagepool/pruning.go
- chain/messagepool/selection.go
- chain/types/mpool.go
- node/impl/full/mpool.go
- Adds a message pool config api, with the most notable feature the inclusion of priority actor addresses.
- Modifies selection logic so that priority actor messages are unconditionally selected first.
- Modifies pruning logic so that priority actor messages are never pruned.
> message pool config and priority addresses

- cmd/lotus-chainwatch/processor/messages.go
Part of https://github.com/filecoin-project/sentinel/issues/37
> feat(chainwatch): track message size in bytes

- cmd/lotus-chainwatch/syncer/sync.go
Part of https://github.com/filecoin-project/sentinel/issues/38
> feat(chainwatch): capture circulating fil per tipset metric

- chain/messagepool/selection_test.go
- Adds a regression test for the skip bug fixed in #2909 
- Adds a unit test for priority message selection
> Some more mpool tests

- node/impl/paych/paych.go
- paychmgr/manager.go
- paychmgr/paych.go
Fixes task 1 of https://github.com/filecoin-project/lotus/issues/2911
> Refactor: move paych collect inside manager

- api/apistruct/struct.go
- cmd/lotus-storage-miner/storage.go
- extern/sector-storage/manager.go
- extern/sector-storage/selector_existing.go
- extern/sector-storage/stores/index.go
- extern/sector-storage/stores/local.go
- extern/sector-storage/stores/remote.go
add space check in StorageFindSector when allowFetch is true
> add space check in StorageFindSector

- api/api_full.go
- api/apistruct/struct.go
- cli/chain.go
- cmd/lotus-pcr/main.go
- node/impl/full/gas.go
- node/impl/full/mpool.go
> fix spelling

- go.mod
- paychmgr/msglistener.go
- paychmgr/msglistener_test.go
- paychmgr/paych.go
- paychmgr/simple.go
Fixes task 3 of https://github.com/filecoin-project/lotus/issues/2911
> Paych refactor: replace custom pubsub impl with lib

- api/api_full.go
- api/apistruct/struct.go
- chain/messagepool/block_proba.go
- chain/messagepool/block_proba_test.go
- chain/messagepool/selection.go
- chain/messagepool/selection_test.go
- chain/types/blockheader.go
- cli/state.go
- cmd/lotus-shed/mpool.go
- cmd/lotus/debug_advance.go
- miner/miner.go
- node/builder.go
- node/impl/full/mpool.go
- node/modules/dtypes/mpool.go
Closes https://github.com/filecoin-project/lotus/issues/2948
> nearly optimal message pool seletion

- chain/store/index.go
- chain/store/store.go
(purposefully made against master as this is mainly a problem on current testnet (we havent hit this in calibration net yet)
> add env vars to configure chain store cache sizes

- chain/types/message.go
> Add checks to ValidForBlockInclusion

- chain/messagepool/config.go
- chain/messagepool/messagepool.go
- chain/types/message.go
- node/impl/full/mpool.go
don't use configured RBF for mpool
> Validate message pool config, validate GasPremium < GasFeeCap

- chain/messagepool/messagepool.go
- node/impl/full/mpool.go
~Currently on top of #2939; will rebase to next once that merges.~
The idea is that instead of having all those push/add threads hitting the lock and contenting with selection and other essential processes, we gate them with a semaphore so that only one of them contents.
Also limits the scope of lock in `PushWithNonce` to exclude the signing operation, which is potentially expensive.
> Add semaphore in push and friends to reduce lock contention

- api/api_full.go
- api/apistruct/struct.go
- api/cbor_gen.go
- gen/main.go
- node/impl/paych/paych.go
Using a special type was causing issues with marshalling / unmarshalling
> Use regular cid as paych sentinel type

- documentation/en/local-dev-net.md
- node/modules/chain.go
> Check repo's genesis against baked-in genesis

- chain/state/statetree.go
- chain/stmgr/utils.go
going to combine this with #2793 to make genesis construction a little betterer
> add function to check entire state tree balance

- go.mod
- go.sum
- paychmgr/manager.go
- paychmgr/mock_test.go
- paychmgr/paych.go
- paychmgr/paych_test.go
- paychmgr/state.go
> paych: use spec-actors paych with AMT for lane states

- api/api_common.go
- api/apistruct/struct.go
- chain/events/state/diff_adt.go
- chain/events/state/diff_adt_test.go
- chain/events/state/predicates.go
- cli/net.go
- cmd/lotus-chainwatch/processor/common_actors.go
- cmd/lotus-storage-miner/info_all.go
- node/impl/common/common.go
This command prints the AutoNAT status, and the observed public address
(should help with debugging miner connectivity issues)
Closes https://github.com/filecoin-project/lotus/issues/825
> cli: net reachability command

- api/api_full.go
- api/apistruct/struct.go
- cli/state.go
- cmd/lotus-fountain/main.go
- cmd/lotus-storage-miner/init.go
- node/impl/full/state.go
It was just an elaborate way to say `0`
> api: Remove unused StatePledgeCollateral

- chain/messagepool/selection.go
- chain/messagepool/selection_test.go
Follow up to #3023
Fixes:
- Remove noop updates from the previous dependencies
- Update all subsequent dependencies, which was the intention
- Make selection2 test less touchy
> Some optimal selection fixes

- node/impl/full/gas.go
Otherwise when all messages have the same premium message selection might get weird
> Add noise to GasPremium calculation to help out message selection

- api/api_full.go
- cli/client.go
- go.mod
- go.sum
- markets/storageadapter/client.go
- node/impl/client/client.go
Context in https://github.com/filecoin-project/go-fil-markets/pull/369
> Move estimation correction into markets adapters

- api/api_worker.go
- api/apistruct/struct.go
- api/client/client.go
- build/version.go
- cmd/lotus-seal-worker/main.go
- extern/storage-fsm/garbage.go
- extern/storage-fsm/nullreader.go
- extern/storage-fsm/sealing.go
- go.mod
- go.sum
- lib/rpcenc/reader.go
- lib/rpcenc/reader_test.go
- node/impl/remoteworker.go
- storage/wdpost_run.go
This code maybe looks a bit hacky in some places, but it works really well
(works on my setup)
> Support AddPiece on workers

- cli/state.go
- cmd/lotus-storage-miner/market.go
A few minor cli improvements. 
probably going to try and integrate: https://github.com/filecoin-project/go-fil-markets/pull/373 as well
> add a market balance command, and a verbose mode for storage-deals list

- chain/market/fundmgr.go
The short version of the issues with not having enough provider collateral or client balance in escrow is getting out of sync with the chain due to waiting for confidence.
This is a less than ideal, but (mostly?) harmless fix which just drops the confidence. Since we're just overwriting values, and a revert followed by reapply really has no effect, it's probably ok.
Everything but the change in message confidence on the events API is just to improve logging
> Temporary fix for fund manager add issues

- documentation/en/join-testnet.md
- documentation/en/mining-lotus-worker.md
- documentation/en/mining.md
> Show how to set env vars

- cli/mpool.go
- documentation/en/.library.json
- documentation/en/mpool.md
- Adds a cli command to get/set the mpool config
- Adds some documentation for the message pool. It's not yusef caliber, but it's a start.
> Mpool documentation and config cli command

- documentation/en/mpool.md
> Some small improvements in mpool docs

- chain/messagepool/messagepool.go
- chain/messagepool/repub.go
When a recently republished message has been applied, trigger early republish of subsequent messages.
> trigger early republish from head changes

- cmd/lotus-storage-miner/init.go
- extern/sector-storage/manager.go
- node/config/def.go
> make addpiece configurable

- README.md
Adds standard badges to quickly check CI, Coverage, Go Report and Golang version supported
> docs: add badgers

- api/client/client.go
- cli/cmd.go
- cli/pprof.go
- cmd/lotus-seal-worker/main.go
- cmd/lotus-storage-miner/info_all.go
- go.mod
- go.sum
Depends on https://github.com/filecoin-project/go-jsonrpc/pull/23
> Fix sealing sched hands on unclean worker disconnect

- extern/storage-sealing/states_sealing.go
> fsm: Fix panic on missing precommit info

- Makefile
- cmd/lotus-chainwatch/main.go
- cmd/lotus-chainwatch/processor/common_actors.go
- cmd/lotus-chainwatch/syncer/sync.go
Minor improvements on chainwatch:
- Plain text actor codes.
- Detailed chainwatch version string logged on startup.
- Detailed economics data per epoch (from https://github.com/filecoin-project/lotus/pull/3064/files#diff-1d6c0a2cbd8c67a8838387bf86e5e419R677-R683)
> Chainwatch Improvements

- cmd/lotus-storage-miner/actor.go
> Add a CLI method to set peerid

- cmd/lotus-storage-miner/actor.go
> strip peerid when setting on-chain addrs

- markets/storageadapter/client.go
- markets/storageadapter/provider.go
Possible fix for detection of deals going active
Remove the time limit to checking for deal activation. Not clear if it will fix it, but won't hurt.
> Remove timeouts on deal committed checks

- extern/storage-sealing/fsm.go
Maybe does the thing? Probably doesn't make the thing much worse.
Fixes #2363 i guess
> restart WaitDeals timers if miner restarts

- chain/messagepool/messagepool.go
> fix deadlock in mpool.Push

- api/api_full.go
- api/apistruct/struct.go
- api/test/deals.go
- cli/client.go
- node/impl/client/client.go
Does the thing, needed for space-race bot and probably more.
> Create eventless version of ClientRetrieve

- storage/wdpost_sched.go
> Missing error argument

- chain/stmgr/stmgr.go
Uses a hard-coded vesting schedule.
> Create a testnet version of setupGenesisActors

- chain/stmgr/stmgr.go
Minor improvement, doesn't break consensus
> Do not include the burnt funds actor as a genesis account actor

- chain/gen/gen.go
- chain/gen/genesis/genesis.go
- chain/gen/genesis/t01_init.go
- chain/stmgr/stmgr.go
- cmd/lotus-seed/genesis.go
- genesis/types.go
- node/node_test.go
Still a WIP: couldnt finish before sleep took
> place the remainder of unallocated funds in a 'remainder' account

- chain/gen/gen.go
- chain/gen/genesis/genesis.go
- chain/gen/genesis/miners.go
- chain/gen/genesis/t01_init.go
- chain/gen/genesis/util.go
- cli/multisig.go
- cli/state.go
- cmd/lotus-seed/seed/seed.go
- genesis/types.go
- node/impl/full/multisig.go
- storage/mockstorage/preseal.go
Still testing and fixing some other things, but this should do the trick
> Keyko io fix/genesis multisig

- cmd/lotus-chainwatch/processor/miner.go
- cmd/lotus-chainwatch/processor/power.go
- cmd/lotus-chainwatch/processor/processor.go
- cmd/lotus-chainwatch/processor/reward.go
> refactor(cw): add new values to sector_info table and smoothing estimate

- documentation/en/.library.json
- documentation/en/payment-channels.md
Refs: https://github.com/filecoin-project/lotus/issues/2956
> Payment channel lotu.sh docs

- extern/storage-sealing/upgrade_queue.go
https://filecoinproject.slack.com/archives/C017CCH1MHB/p1597889356006200
> Do not try to replace CC sectors with a deal-less sector

- metrics/metrics.go
- node/modules/lp2p/pubsub.go
so that we have a better idea on bandwidth usage.
> pubsub metrics for RPCs

- cmd/lotus-storage-miner/info.go
- go.sum
Example
```
Miner: t099999
Sector Size: 512 MiB
Byte Power:   3.258 TiB / 11.74 PiB (0.0271%)
Actual Power: 3.26 Ti / 12.4 Pi (0.0257%)
Committed: 3.263 TiB
Proving: 3.263 TiB (4.5 GiB Faulty, 0.13%)
Expected block win rate: 3.7008/day (every 6h29m6s)
Deals: 211, 16.17 GiB
Active: 195, 14.23 GiB (Verified: 0, 0 B)
Miner Balance: 236.048541199349973163 FIL
PreCommit:   2.944545733979087132 FIL
Pledge:      104.40624836152655872 FIL
Locked:      54.486439347722313236 FIL
Available:   74.211307756122014075 FIL
Worker Balance: 1249.497672722768263568 FIL
Market (Escrow):  0.00000773261609612 FIL
Market (Locked):  0 FIL
Expected Seal Duration: 12h0m0s
Sectors:
WaitDeals: 2
Total: 6818
Proving: 6588
PreCommit2: 16
PreCommitWait: 3
WaitSeed: 97
Committing: 10
CommitWait: 8
FinalizeSector: 93 …
```
> miner info: Fix avail calc, print aggregate deal info

- cmd/lotus-storage-miner/proving.go
Bugfix: fix some typo and correct recoveries data source
> Bugfix: fix some typo and correct recoveries datasource

- node/impl/client/client.go
There is a couple of cases where unsubscribing from retrieval events didn't happen, possibly resulting in a send on a closed channel.  Also ensure that payload cid and deal id match before logging events.
@hannahhoward
> Retrieval CLI fixes

- chain/messagepool/messagepool.go
> initialize mpool ts _before_ loading local messages

- chain/blocksync/client.go
- chain/sync.go
- documentation/en/environment-vars.md
Can be very helpful if you have a slow internet connection, makes more incremental progress
> Add some tracing and the ability to tweak message fetch window size

- api/client/client.go
- cli/cmd.go
- cmd/lotus-pcr/main.go
- cmd/lotus-stats/main.go
- go.mod
- go.sum
- lib/rpcenc/reader_test.go
- lotuspond/api.go
- lotuspond/main.go
- node/impl/remoteworker.go
- node/test/builder.go
- tools/stats/rpc.go
goes with https://github.com/filecoin-project/go-jsonrpc/pull/26 if we take it
> refactor(ctx): for go-jsonrpc/pull/26

- conformance/driver.go
- conformance/runner_test.go
Updates the `test-vectors` submodule (to get the hints) and fixes the selectors schema change.
Fixes https://github.com/filecoin-project/test-vectors/issues/72
> feat(conformance): skip incorrect tests

- api/test/mining.go
- api/test/util.go
- node/test/builder.go
Should help somewhat, Going to keep looking into this and fixing more.
> improve flakiness of a few tests

- chain/sync.go
Gotta do whatever it takes to make @karalabe happy, should hopefully close #3307
> print block 'age' when validating blocks during sync

- node/modules/core.go
Resolves https://github.com/filecoin-project/lotus/issues/3335
> Don't fail if could not resolve drand dnsaddr

- chain/sub/incoming.go
Our SQA team (aka the onions) has complained about that code, and upon inspection it seems that we might erroneously reject a block message when we can't determine power.
This remedies the situation by signalling a soft failure in that case.
> ignore, don't reject block if we can't determine power

- cmd/lotus-chainwatch/main.go
- cmd/lotus-chainwatch/run.go
- cmd/lotus-chainwatch/util/api.go
- go.sum
Completes https://github.com/filecoin-project/sentinel/issues/47. Will leave draft once manually validated.
> polish(chainwatch): accept lotus api and token

- chain/sub/incoming.go
- metrics/metrics.go
Also add metric views for new pubsub metrics.
> distinguish local message validation failures from remote

- api/api_full.go
- api/apistruct/struct.go
- cli/paych.go
- cli/paych_test.go
- documentation/en/api-methods.md
- node/impl/paych/paych.go
- paychmgr/cbor_gen.go
- paychmgr/manager.go
- paychmgr/mock_test.go
- paychmgr/paych.go
- paychmgr/paych_test.go
- paychmgr/settler/settler.go
- paychmgr/store.go
Depends on https://github.com/filecoin-project/lotus/pull/3146
Fixes https://github.com/filecoin-project/lotus/issues/2587 https://github.com/filecoin-project/lotus/issues/3193
> paych: fix issue where `voucher spendable` fails for submitted vouchers

- chain/sync.go
Additive Increase, Multiplicative Decrease -- TCP style.
It should help with chain sync in crappy networks and accelerate stuff in good ones.
> dynamic chain sync window

- api/api_full.go
- api/apistruct/struct.go
- cli/client.go
- documentation/en/api-methods.md
- node/impl/client/client.go
Add a `-watch` option to `client list-deals`
Resolves #2953
> Add watch option to list-deals

- cmd/lotus-chainwatch/processor/miner.go
There were some optimizations to make which allow miner work to be perform more in parallel. This delivered some of that delicious low-hanging fruit.
> perf(chainwatch): parallelize miner processing

- CHANGELOG.md
- build/version.go
- documentation/en/api-methods.md
> Lotus version 0.5.5

- node/modules/chain.go
- node/modules/storageminer.go
> Don't use context to close bitswap

- cmd/lotus-chainwatch/processor/processor.go
- cmd/lotus-chainwatch/syncer/blockssub.go
- cmd/lotus-chainwatch/syncer/sync.go
- Fixes https://github.com/filecoin-project/sentinel/issues/50
- Fixes https://github.com/filecoin-project/sentinel/issues/51
- Plus some logging improvements.
> Some more Chainwatch improvements

- cmd/lotus-pcr/main.go
Allows the disabling of different message processing.
Note: During processing of most `ProveCommitSector` messages I was seeing large call time to `StateMinerInitialPledgeCollateral`. I do not see these at all with the `PreCommitSector`. My naive assumption here is that there is an extensive walk of the chain involved here and due to the larger degree for which ProveCommitSector messages can cover (due to different processing times) this thrashes some cache someplace.
> lotus-pcr: add toggle for message processing

- go.mod
- go.sum
Reverts filecoin-project/lotus#3464
> Revert "adx blst"

- cli/sync.go
>  Added target height to sync wait

- cli/state.go
This probably isn't critical, but I noticed it, so I fixed it.
> [cli/state] Robust actor lookup

- extern/sector-storage/manager.go
Fixes https://github.com/filecoin-project/lotus/issues/3558
> storage manager: bail out with an error if unsealed cid is undefined

- chain/events/events.go
- chain/events/events_called.go
- chain/events/events_height.go
- chain/events/events_test.go
- chain/events/tscache.go
- chain/events/tscache_test.go
Fixes https://github.com/filecoin-project/lotus/issues/3554
> chain events: if cache best() is nil, return chain head

- api/api_full.go
- api/apistruct/struct.go
- cli/paych.go
- documentation/en/api-methods.md
- go.mod
- go.sum
- markets/retrievaladapter/client.go
- node/impl/client/client.go
- node/modules/client.go
@arajasek I thought it might be easier to work with this than trying to merge #3541 so you can include 392 from markets as well.
> Use markets master

- extern/sector-storage/manager.go
Reverts filecoin-project/lotus#3615, Seems to break a bunch of PRs on master
> Revert "storage manager: bail out with an error if unsealed cid is undefined"

- chain/stmgr/forks.go
- cmd/lotus-shed/balances.go
- cmd/lotus-shed/main.go
Implements today faucet funds realignment upgrade logic.
> Implement faucet funds reallocation logic

- markets/storageadapter/client.go
> typo fix in error message

- cli/mpool.go
Tell me how to make this more useful.
> add basic command for printing gas performance of messages in the mpool

- cmd/lotus-chainwatch/processor/miner.go
- bug was comparing current miner with current miner instead of previous :facepalm:
> fix(chainwatch): compare prev miner with cur miner

- cmd/lotus-shed/main.go
- cmd/lotus-shed/mempool-stats.go
Could probably make this spit out some prometheus metrics and graph it somewhere, but this makes me happy already.
> add a simple command to watch messages sitting in the mempool

- api/docgen/docgen.go
- api/test/test.go
- build/version.go
- cmd/lotus-seal-worker/main.go
- cmd/lotus-seal-worker/rpc.go
- cmd/lotus-storage-miner/init.go
- cmd/lotus-storage-miner/main.go
- cmd/lotus-storage-miner/run.go
- cmd/lotus/main.go
- node/impl/common/common.go
Should make some upgrades less painful
> build: Separate API versions per node type

- api/api_full.go
- api/apistruct/struct.go
- cli/multisig.go
- documentation/en/api-methods.md
- node/impl/full/multisig.go
- node/impl/full/state.go
Needs  #3589 to work correctly.
> Multisig API additions

- conformance/chaos/actor_test.go
...adds some coverage to the chaos actor
> test: add chaos actor tests

- conformance/chaos/actor_test.go
Things got moved around after the tests got written but before it merged.
> fix: chaos tests

- extern/storage-sealing/sealing.go
- markets/storageadapter/provider.go
> Retry Add Piece

- node/repo/fsrepo.go
> make nested dir

- cmd/lotus-chainwatch/syncer/sync.go
In the same parentstateroot, the one with the smallest height should be selected.
> optimize definition of state_heights

- paychmgr/paychvoucherfunds_test.go
Test that we can
- create a channel with balance 10
- add a voucher in lane 1 for 10
- fail to add a voucher in lane 2 for 5
- add funds to channel to bring balance to 15
- add a voucher in lane 2 for 5
> paych voucher funds test

- chain/messagepool/messagepool.go
- chain/messagepool/pruning.go
- chain/messagepool/repub.go
we are past the fork now and in an hour we won't have negative chains any more, so it is time to re-enable this very important check.
> re-enable baseFee lower bound check

- cmd/lotus-bench/import.go
you can't really run this anymore without running out of ram
> allow specification of repo directory in lotus-bench

- go.mod
- go.sum
Update to tagged release of markets
Update dependency -- short contain only a couple commits beyond what's already in master
> Upgrade markets v0.6.1

- cmd/lotus-storage-miner/storage.go
fix `lotus-miner storage find` error
> fix `lotus-miner storage find` error

- cli/sync.go
why  codecov/patch — Codecov Report  check fail?! @whyrusleeping @Kubuxu @magik6k
who can review,thanks!
> sync wait add heightDiff maybe useful!

- cmd/lotus-storage-miner/sectors.go
> Add an option to hide sectors in Removed from `sectors list`.

- scripts/lotus-miner.service
Prevent lotus-miner shutdown when lotus daemon restarts.
> replace Requires with Wants

- cli/state.go
gonna also add a command to diff two different json blobs and point out mismatches
> add json output to state compute

- chain/stmgr/utils.go
fixes calling StateGetPower without a miner address
> fix GetPower with no miner address

- tools/stats/metrics.go
Depends on https://github.com/filecoin-project/lotus/pull/4049
> Add back network power to stats

- chain/types/tipset.go
add height equal
cids instead of  blks
> optimize Tipset equals

- cli/wallet.go
don't die if no default is set
> Fix wallet list

- extern/sector-storage/ffiwrapper/sealer_cgo.go
Closes https://github.com/filecoin-project/lotus/pull/3629
> sectorstorage: Fix potential panic in FinalizeSector

- cmd/lotus-storage-miner/market.go
> Always use default 720h for setask duration and hide the duration param option 

- node/impl/client/client.go
> Convert ID addresses to key addresses before checking wallet

- build/params_testnet.go
- chain/wallet/wallet.go
- documentation/en/api-methods.md
- paychmgr/store_test.go
And make it the default encoding (turn all addresses into `f...`).
> Support addresses with mainnet prefixes

- go.mod
- go.sum
This change ensures the bitmap is reset on flush.
TESTING: this should be tested against a full import.
> update the AMT implementation

- cmd/lotus-shed/nonce-fix.go
the previous code effectively hardcoded the gas fee cap to 0
> fix noncefix

- build/params_2k.go
- build/params_testground.go
- build/params_testnet.go
- chain/actors/builtin/builtin.go
- chain/stmgr/forks.go
> Set actorsv2 upgrade epoch

- go.mod
- go.sum
Upgrade to latest markets release with some bug fixes.
> Update markets v0.7.1

- chain/wallet/wallet.go
Fixes #4226 
There's an edge-case where an address created with a `t` prefix, but then with deletion attempted when the address prefix is `f` won't delete the `t-`prefixed entry in the store.
> Fix deletion of addresses from wallet

- chain/sync_test.go
- node/test/builder.go
This should _maybe_ make tests slightly faster and more reliable. Slightly.
Maybe.
> cleanup tests on finish

- chain/sub/incoming.go
1. Allow duplicate blocks from bitswap. This shouldn't happen, but there's no reason to bail (just log loudly).
2. Simplify logic to very explicitly check to make sure we're fetching every block.
After making this change, I'm pretty sure it's _not_ necessary. But it's easier to understand (or at least it is for me).
> simplify message syncing logic

- node/impl/client/client.go
We'd read the deal ID without synchronizing. This could (and probably did given the history of flaky deal tests) cause us to miss events.
This patch also makes sure to always unsubscribe from events, even on error.
> fix a race when retrieving pieces

- CHANGELOG.md
- build/version.go
> Lotus version 0.10.0

- cmd/lotus-storage-miner/sealing.go
> Improve the UX for `lotus-miner sealing workers`

- cmd/tvx/stores.go
tvx only traced accessed CIDs during the execution of a message, but it did not trace puts. This caused the CAR to be missing state chunks of the postcondition state tree, making statediff comparisons impossible.
> tvx: trace puts to blockstore for inclusion in CAR.

- go.mod
- go.sum
fixes panic caused by 0.10.1 release
Should become v0.10.2
> Update to 0.9.1 bugfix release

- lib/timedbs/timedbs_test.go
Otherwise, they flake once in a while.
> give the TimeCacheBS tests a bit more time

- chain/stmgr/stmgr.go
> optimize map use struct{}

- .codecov.yml
Well, make it a bit more accurate.
> Increase code coverage!

- cmd/lotus-shed/balances.go
> Make audit balances capable of printing robust addresses

- node/impl/full/state.go
> Fix StateReplay to use provided tipset

- CHANGELOG.md
- build/version.go
> Lotus version 1.0.0

- api/api_full.go
I know, one liner pr again TAT - tho this can help avoid issues like #4446
> Add a comment to BlockMessages to address #4446.

- .circleci/config.yml
- Makefile
Mostly aiming to save time on not having to rerun flaky tests so much (yes, ideally we'd fix those..)
> circle: Run tests for some subsystems separately

- go.mod
- go.sum
Updates to latest markets for 1.1.0 lotus release
> Update markets v1.0.0

- chain/wallet/wallet.go
> Delete wallet from local wallet cache

- chain/store/store_test.go
> Fix flaky TestChainExportImportFull

- cmd/lotus-storage-miner/sectors.go
This lets easily see which sectors had.. adventures
> miner sectors list: flags for events/seal time

- chain/messagepool/messagepool.go
- cli/mpool.go
- node/builder.go
- node/config/def.go
- node/impl/full/gas.go
- node/modules/core.go
- node/modules/dtypes/mpool.go
(I really want a nicer property system)
> Config for default max gas fee

- node/modules/core.go
> bootstrap: don't return early when one drand resolution fails

- cli/state.go
> Add miner available balance and power info to state minor info

- chain/wallet/wallet.go
> Correctly delete the default wallet address

- chain/vm/runtime.go
> modify runtime gasUsed printf

- .gitmodules
https://github.com/filecoin-project/lotus/pulls#r516720444
> Use https for blst submodule

- build/params_2k.go
- build/params_mainnet.go
- build/params_testground.go
- chain/actors/policy/policy.go
- chain/actors/policy/policy_test.go
- chain/stmgr/forks.go
- go.mod
- go.sum
> Update to actors v2.3.0

- extern/storage-sealing/garbage.go
Using variables instead of calling functions twice
> optimize pledge sector

- cli/client.go
Useful to track how deals are going when making a bunch of them
```
$ lotus client deal-stats --newer-than 2h
Total: 246 deals, 61.52 GiB
StorageDealSealing: 16 deals, 7.938 GiB
StorageDealTransferring: 48 deals, 23.81 GiB
StorageDealError: 59 deals, 29.27 GiB
StorageDealClientTransferRestart: 1 deals, 508 MiB
```
> Add client deal-stats CLI

- go.mod
- go.sum
> Update to latest go-bitfield

- cmd/lotus-stats/main.go
Fixes the flags for the stats service.
> lotus-stats: fix influx flags

- lib/blockstore/badger/blockstore.go
- lib/blockstore/badger/blockstore_test_suite.go
See commit log.
---
Closes #4809.
> badger blockstore: minor improvements

- build/params_2k.go
- build/params_mainnet.go
- build/params_testground.go
- chain/sync_manager.go
> 2k sync BootstrapPeerThreshold

- api/test/blockminer.go
- cli/test/net.go
- cmd/lotus-gateway/endtoend_test.go
I'm not sure if this will fix (maybe) https://github.com/filecoin-project/lotus/issues/4812 but it should at least make it easier to read the logs
> Stop mining at the end of tests

- node/modules/storageminer.go
Should fix https://github.com/filecoin-project/lotus/issues/4833
We really need a proper property-based config
> Fix MaxSealingSectrosForDeals getting reset to 0

- node/repo/fsrepo.go
This fixes the error reported in #4921.
> fix blockstore directory not created automatically.

- go.mod
Makefile  go 1.15 
update go.mod
> update go from 1.14 to 1.15

- Makefile
now go 1.15
later go 2.1 no problem
> add go main version

- chain/stmgr/forks.go
> optimize code UpgradeTapeHeight and go fmt

- cli/state.go
> CLI to get network version

- chain/vm/invoker.go
Something that was useful when debugging butterflynet problems
> Improve error for ActorsVersionPredicate

- chain/actors/policy/policy.go
> change typeV7 make len

- node/modules/storageminer.go
Follow on to https://github.com/filecoin-project/lotus/pull/4975 -- adds logging ot data transfer on miner side
Add logging setup for data transfer for miner data transfer instance
> Add logging on data-transfer to miner

- chain/gen/genesis/f01_init.go
- chain/gen/genesis/genesis.go
Not super sure how we didn't catch this before
> Setup remainder msig signers when parsing genesis template

- chain/vm/syscalls.go
> update index to sectorNumber

- api/api_full.go
> Default StartDealParams's fast retrieval field to true over JSON

- chain/wallet/wallet.go
> fix wallet dead lock

- chain/wallet/wallet.go
> fix wallet delete address where address is default

- miner/miner.go
L361	round := base.TipSet.Height() + base.NullRounds + 1
> optimize code use existence var
