filecoin-project/lotus

chain/events/events_height.go
chain/events/events_test.go

This is part of the fix for running duplicate PoSts, the other part is cancelling post computation on revert

events: always call revert in CahinAt

---

cmd/lotus/rpc.go
lib/jsonrpc/client.go

If the websocket connection closes, expose that to the client so that new requests don't hang indefinitely

dont hang requests if websockets server shuts down

---

chain/vm/vm.go

It shoud not update the head of toactor if there is  fatal err when invoke.

fix method: VM.send

---

chain/state/statetree.go
chain/types/signature_cgo.go
chain/validation/applier.go
chain/validation/lotus_test.go
chain/validation/message.go
chain/validation/message_test.go
chain/validation/state.go
go.mod
go.sum

Sketch a simple integration with the `github.com/filecoin-project/chain-validation package`, to help surface any issues with its current design.
This PR despends on changes in https://github.com/filecoin-project/chain-validation/pull/8
A test, `TestLotusExample`, was added to creates some actors, transfers balance between them, and asserts success. This requires interaction with the Init actor and the setup required for it.
Looking for better options to:
- state tree updates: https://github.com/filecoin-project/lotus/pull/449/files#diff-173eebafb6fcc6d6702e21f1d357a334R59
- keeping state for message application: https://github.com/filecoin-project/lotus/pull/449/files#diff-117f4a49b352d3df7f1ac26284ec2f06R46

[wip] first pass at integrating the chain-validator. 

---

api/api.go
api/struct.go
build/paramfetch.go
build/params.go
chain/actors/actor_miner.go
chain/actors/actor_storagepower.go
chain/actors/actor_storagepower_test.go
chain/actors/actors_test.go
chain/actors/cbor_gen.go
chain/deals/client_states.go
chain/gen/gen.go
chain/gen/utils.go
chain/stmgr/utils.go
cli/createminer.go
cmd/lotus-storage-miner/init.go
node/impl/full/state.go
node/impl/storminer.go
node/modules/storageminer.go
storage/miner.go

Now miners can specify which sector size they want to use when initializing their miner
cc @dignifiedquire

Allow miners to create differently sized sectors

---

tools/stats/main.go

Having a height tags resulted in performance issues due to an increase in series cardinality.

Remove height tag from stats tool

---

cmd/lotus-storage-miner/main.go
cmd/lotus/main.go

It's producing lots of spam along the lines of:
```
2019-10-30T03:10:43.631+0800    INFO    swarm2  go-libp2p-swarm@v0.2.1/swarm_dial.go:420    got error on dial: dial tcp4 0.0.0.0:33055->172.16.0.139:45435: i/o timeout
2019-10-30T03:10:43.631+0800    INFO    swarm2  go-libp2p-swarm@v0.2.1/swarm_dial.go:420    got error on dial: dial tcp6 [::1]:46173: connect: network is unreachable
2019-10-30T03:10:43.631+0800    INFO    swarm2  go-libp2p-swarm@v0.2.1/swarm_dial.go:420    got error on dial: dial tcp4 127.0.0.1:43987: connect: connection refused
2019-10-30T03:10:44.367+0800    INFO    swarm2  go-libp2p-swarm@v0.2.1/swarm_dial.go:420    got error on dial: dial tcp4 0.0.0.0:33055->192.168.1.32:37003: i/o timeout
2019-10-30T03:10:44.367+0800    INFO    swarm2 …
```

Set swarm log level to WARN

---

chain/types/bigint_test.go
chain/types/fil.go

previously balances were printed incorrectly because all zeros on the right were trimmed, even to the left of the decimal point.

only trim zeros to the right of the decimal

---

chain/sync.go

Fix temporal problems in bad block cache

---

api/api.go
api/struct.go
chain/gen/gen.go
chain/store/store.go
chain/vm/vm.go
node/impl/full/chain.go
storage/miner.go
storage/post.go

`ChainGetRandomness` and `GetRandomness` functions are using int type for lookback parameters. Change it to uint64. It is for interoperability and also make it more reasonable, since it is for lookback, negative lookback is not allowed.

uint64 to replace int in GetRandomness

---

build/params.go
chain/messagepool.go

currently when there is a fork/reorg, we lose bls messages because we don't have their signatures. This should help with that.

cache bls signatures for later recovery during forks

---

datatransfer/impl/graphsync/graphsync.go
datatransfer/impl/graphsync/graphsync_test.go

This fulfills [14 Responder can respond to a push request](https://github.com/filecoin-project/go-data-transfer/issues/14) and [17 Responder can respond to a pull request](https://github.com/filecoin-project/go-data-transfer/issues/17)

Implement response to data pull/push requests

---

api/api_full.go
api/struct.go
chain/gen/gen.go
chain/types/tipset.go
chain/types/tipset_key.go
chain/types/tipset_key_test.go
cli/chain.go
go.mod
go.sum
node/impl/full/chain.go
node/modules/storageminer.go
storage/miner.go
storage/post.go
storage/sector_states.go

This key is intended as an identifier for a TipSet, e.g. to be used as the `StateID` for shared modules. It's is represented as a string so it can be used as a map key, at @whyrusleeping's suggestion, although this PR does not, in fact, use it that way. The cost, compared with a  [sorted-slice representation](https://github.com/filecoin-project/go-filecoin/blob/b926dad7ba3d5a6342d73008d465c2a56a37d04e/internal/pkg/block/tipset_key.go), is some encoding when a key is created or the CIDs extracted from it.
The encoding contains some overhead caused by the `cid` package not providing methods supporting reading raw concatenated CIDs from a stream, despite their self-describing nature (see https://github.com/ipfs/go-cid/issues/93). I opted not to re-implement parts of the CID parsing here. The …

Add TipSetKey as a concatenation of block CIDs, and use if for ChainGetTipSet, ChainGetRandomness.

---

.circleci/config.yml

and don't fallback to older parameters if parameters.json changes.

Include build/paramfetch.go in circle params checksum

---

datatransfer/impl/graphsync/graphsync.go
datatransfer/impl/graphsync/graphsync_test.go
datatransfer/impl/graphsync/graphsync_whitebox_test.go
datatransfer/types.go

This PR implements [Subscriber is notified when request not accepted](https://github.com/filecoin-project/go-data-transfer/issues/39). I also added a safety check for registering a new voucher type, to make sure that the implementer takes a receiver pointer, plus a test. Additional tests were written just for the Subscribe function. Some code is provisional and is noted below.

responses alert subscribers when request is not accepted

---

chain/sub/incoming.go
chain/sync.go
cmd/lotus-storage-miner/init.go

I suspect that this will help with the chain sync issues significantly.

persist blocks as they come in

---

datatransfer/impl/graphsync/graphsync.go
datatransfer/impl/graphsync/graphsync_test.go

This fulfills [Responder schedules Graphsync request when Push is validated](https://github.com/filecoin-project/go-data-transfer/issues/20)
Also introduces a logger and begins using real contexts.

Graphsync response is scheduled when a valid push request is received

---

cmd/lotus-storage-miner/init.go

clean up repo if miner init fail and use log

---

datatransfer/impl/graphsync/graphsync_impl.go
datatransfer/impl/graphsync/graphsync_impl_test.go
datatransfer/impl/graphsync/graphsync_receiver.go
datatransfer/message/message_test.go
go.mod
go.sum

Implements [go-data-transfer issue #22](https://github.com/filecoin-project/go-data-transfer/issues/22)
1. register push request hook with graphsync. 
1. create channels when a request is received. 
1. fix tests.
1. better NewReader instantiation

DTM sends data over graphsync for validated push requests

---

.gitmodules
Makefile
chain/actors/actor_miner.go
chain/address/address.go
chain/address/address_test.go
chain/gen/gen.go
chain/gen/mining.go
chain/stmgr/stmgr.go
chain/stmgr/utils.go
chain/sync.go
chain/types/signature_cgo.go
chain/wallet/wallet.go
go.mod
go.sum
lib/padreader/padreader.go
lib/sectorbuilder/sectorbuilder.go
storage/post.go

We are deprecating go-sectorbuilder and go-bls-sigs, consolidating their functionality into a single CGO/FFI crate for Filecoin nodes.
- remove old submodules and add new submodule
- update build tooling to consume new unified static library
- update consumers of old libs to use new package

replace go-bls-sigs and go-sectorbuilder with filecoin-ffi

---

node/modules/lp2p/discovery.go

Lotus used kad dht as discovery protocol, not mdns .

Delete died code

---

chain/blocksync/blocksync_client.go

should make the error in #677 better

print better error if no blocksync peers

---

.circleci/config.yml

- adds a new job to run build in macos and produce lotus and
lotus-storage-miner binaries
- persist linux ad darwin lotus and lotus-storage-miner binaries as
CircleCI artifacts
- create CircleCI cache for go mod and cargo

macos build and linux and darwin bin artifacts

---

miner/miner.go

I'm not sure if we should reject blocks that go over this limit (but under the encoders limit).
But in any case, i've seen blocks coming over the network that failed to decode because they had over 8000 messages in them

dont add too many messages to a block

---

chain/events/events.go
chain/events/events_called.go
chain/events/events_height.go
chain/events/events_test.go

I expect the apply trigger to not happen again unless the actual height we are registered for was reverted.

fix events double trigger issue

---

chain/deals/provider.go
datatransfer/cbor-gen/main.go
datatransfer/impl/dagservice/dagservice.go
datatransfer/impl/graphsync/cbor_gen.go
datatransfer/impl/graphsync/graphsync_impl.go
datatransfer/impl/graphsync/graphsync_impl_test.go
datatransfer/impl/graphsync/graphsync_receiver.go
datatransfer/impl/graphsync/graphsync_receiver_test.go
datatransfer/impl/graphsync/graphsync_whitebox_test.go
datatransfer/message/cbor_gen.go
datatransfer/types.go

This implements the rest of [Subscriber Is Notified When Request Completed #24](https://github.com/filecoin-project/go-data-transfer/issues/24)
* send a graphsync message within a go func and consume responses until error or transfer is complete.
* notify subscribers of results.
* Rename datatransfer.Event to EventCode. 
* `datatransfer.Event` is now a struct that includes a message and a timestamp as well as the Event.Code int, formerly Event, update all uses
* Add extension data to graphsync request hook, gsReq
* rename sendRequest to sendDtRequest, to distinguish it from sendGsRequest, where Dt = datatransfer, Gs = graphsync
* use a mutex lock for last transfer ID
* obey the linter

Feat/dt subscribe, file Xfer round trip

---

chain/sync.go

The screenshot shows the benefit of this change in the Jaeger UI, as it makes it clear which traces have errors occurring in them from the top-level.

add error status to trace

---

api/api_storage.go
api/struct.go
cmd/lotus-storage-miner/sectors.go
node/impl/storminer.go
storage/sectors.go

@magik6k I havent actually tested this out because my miner is still running on the devnet, but it seems like we want a way to manually trigger sector state changes. Automatic handling of sector failures is going to be non-trivial, and this at least lets the user make the call of what to do.

add command for power users to manually update sector state

---

datatransfer/impl/graphsync/graphsync_impl.go
datatransfer/impl/graphsync/graphsync_impl_test.go
datatransfer/impl/graphsync/graphsync_whitebox_test.go
go.mod
go.sum

Implements [Refactor to v0.0.4 of Graphsync, don't error when extension is not present](https://github.com/filecoin-project/go-data-transfer/issues/41)
* feat/dt-implementation now using real graphsync v0.0.4 
* getExtensionData calls new graphsync action hooks
* Test for same

Don't respond with error in gsReqRcdHook when we can't find the datatransfer extension.

---

chain/gen/gen.go
storage/fpost_run.go

Should address the immediate concern in #757
However, we need to scan the codebase for other places where we might be using this same pattern incorrectly.

Fix copying partial ticket arrays into slices

---

chain/deals/cbor_gen.go
chain/deals/client.go
chain/deals/client_utils.go
chain/deals/provider_utils.go
chain/deals/request_validation_test.go
datatransfer/impl/graphsync/graphsync_impl.go
datatransfer/impl/graphsync/graphsync_impl_test.go
datatransfer/impl/graphsync/graphsync_receiver.go
datatransfer/impl/graphsync/graphsync_receiver_test.go
datatransfer/impl/graphsync/graphsync_whitebox_test.go
node/builder.go
node/modules/client.go
node/modules/dtypes/storage.go
node/modules/storageminer.go

Make the lotus codebase use the real DataTransfer implementation!
- switch data transfer instances over to using graphsync implementation
- provide code for constructing graphsync instances on the client and miner
- seperate blockstore construction from dag service on the miner side so it is available to construct graphsync
- remove context parameter from data transfer construction since it is unused

feat(datatransfer): switch to graphsync implementation

---

chain/messagepool/messagepool.go
chain/sync_manager.go

This should help avoid duplicate sync jobs running in parallel for effectively the same chain

Better track related incoming sync targets

---

chain/sync_manager.go

This does better explicit bootstrap state handling, and also fixes a bug where queued up sync jobs wouldnt be started when a previous one finished.

improve bootstrap sync handling

---

chain/actors/actor_miner.go

this is just spam at this point. If we want to get the data out, we can look at the chain

don't print giant long proof in error message

---

cli/cmd.go
cmd/lotus-seal-worker/main.go
cmd/lotus-storage-miner/main.go
cmd/lotus-storage-miner/run.go
cmd/lotus/main.go

Usage: FULLNODE_API_INFO or STORAGE_API_INFO
Content of env var: `<token>:<api multiaddr>`
Example: `FULLNODE_API_INFO="$(cat ~/.lotus/token)dsds:$(cat ~/.lotus/api)"`

Add env var for API token and location

---

chain/gen/gen.go
chain/sync.go
chain/types/blockheader.go
lib/sectorbuilder/sectorbuilder.go
lib/sectorbuilder/simple.go

Fixing the `IsTicketWinner`'s target so it appropriately accounts for number of sectors in spite of sampling. 
Math is simply to replace the sampling logic in the target by `numSectors / sectorsSampled` so each ticket (ie `sectorsSampled`) is appropriately "powered"

fix `IsTicketWinner` in ePoSt

---

chain/store/store.go

this leads to increasing memory usage, as a reuslt of a huge number of unsub calls in the loop.
especially when we have many clients

fix: duplicate unsub calls when client quits

---

chain/sub/incoming.go
chain/sync.go
chain/sync_manager.go
chain/sync_manager_test.go

There is a bug in master right now where if you receive three or more blocks that could form a tipset at roughly the same time, you will sync to the first one, and bucket the others. Then when the first one finishes syncing, we pull the heaviest tipset out of that bucket (and ignore the rest). This means we only end up syncing at most two of the blocks in that tipset.
This should fix the issue, we avoid bucketing blocks if they have the same parent tipsets as active syncs (aka, could form a tipset with an active sync target).

fix incoming tipset bucketing

---

api/api_full.go
api/apistruct/struct.go
api/test/deals.go
cli/client.go
node/impl/client/client.go

Avoid forcing using the default address of the wallet in `ClientStartDeal` API.
This was marked as a `//ToDo`.
~~I'll wait for CI to check the test before making PR reviewable.~~

client: make wallet addr be a param in ClientStartDeal

---

documentation/cn/dev-tools-jaeger-tracing.md
documentation/en/dev-tools-jaeger-tracing.md

This PR is fixing the name of Jaeger, and also renaming the .md files - I am not sure how those get rendered on http://docs.lotu.sh/ , but I guess it will be fine.

rename Jaegar to Jaeger

---

build/params_shared.go
chain/sync.go

Miner t01475 was exploiting this, its a pretty good demonstration of why our allowable clock drift was wayyy too high.

dont allow submitting blocks more than a second in the future

---

cli/client.go

Name in output unit since isn't in base 10 but 2.

cli: fix name of price unit

---

chain/blocksync/blocksync.go
chain/blocksync/blocksync_client.go
chain/messagepool/messagepool.go
chain/messagepool/messagepool_test.go
chain/store/store.go
chain/store/store_test.go
chain/sync.go
chain/sync_manager.go
chain/types/tipset.go
cli/chain.go
node/hello/hello.go
node/impl/full/chain.go
tools/stats/rpc.go

Also did a bunch of refactoring to use tipsetkeys in a lot of places. The end result of the tipsetkey stuff is that the block headers parents field should be one, and we should make it cbor marshal as a cid array. (so no serialization changes)
The benchmark here goes 34x faster with this change than without it. So pretty decent IMO

cache load tipset

---

cli/chain.go

This allows rolling back to specific epoch to better debug sync perf issues

cli: chain sethead --epoch

---

cli/params.go
cmd/lotus-bench/main.go

```
// FromHumanSize returns an integer from a human-readable specification of a
// size using SI standard (eg. "44kB", "17MB").
func FromHumanSize(size string) (int64, error) {
return parseSize(size, decimalMap)
}
// RAMInBytes parses a human-readable string representing an amount of RAM
// in bytes, kibibytes, mebibytes, gibibytes, or tebibytes and
// returns the number of bytes, or -1 if the string is unparseable.
// Units are case-insensitive, and the 'b' suffix is optional.
func RAMInBytes(size string) (int64, error) {
return parseSize(size, binaryMap)
}
```

Use power of 2 sizes when parsing byte counts

---

lib/sectorbuilder/fs.go

fixes compilation issue under macos

fix(sectorbuilder): always cast fsstat.Bsize

---

cli/client.go

Fixes #810 
The GH issue has a little history of this error that has popped in Slack channel a few times.
Feels like this `peer.ID("SETME")` should be a constant somewhere. The other place that is used is in `lotus-fountain`. If there's a clear place to put it, I can change it.

cli: print nicer message when miner hasn't initialized

---

node/config/def.go

This should reduce connection churn, and make pubsub more stable

connmgr: bring low/high water values closer

---

build/params_shared.go
chain/sub/incoming.go
chain/sync.go
go.sum
miner/miner.go

Setting the limit a little low intentionally here, it should more more than enough for what we've been seeing in the testnet so far, and if the chain does reach capacity, we can write code to select messages more intelligently to take advantage of multiblock tipsets.

introduce a limit on the number of messages a block can have

---

tools/stats/main.go
tools/stats/metrics.go
tools/stats/rpc.go

Updating to golog so we can gather logs and monitor in a single place with the rest of our logs.
I've also updated the sync check. When there is a lot of volatility in block distribution we would never report stats because we were always seeing block much later than one block delay from when they were published. Also added back in the original sync code so we have better logging around the progress.

Use golog in stats tool, and better sync control

---

build/params_shared.go
chain/actors/actor_miner.go

Still TODO is to figure out what to do with a sector precommit once its hit this state. I think it makes sense to be able to precommit over an existing precommit to reuse that sector ID.

Set hard limit on maximum randomness lookback for seal proof submissions

---

cmd/lotus-seed/main.go
cmd/lotus-seed/seed/seed.go
cmd/lotus-storage-miner/init.go
node/modules/storageminer.go
node/node_test.go

Before extraction is did the prefixing internally, it now doesn't

Pass correct datastore into sectorbuilder

---

miner/miner.go
node/node_test.go

Messages like these shouldn't be able to get into mpool, but someone hit that. 
Doesn't seem harmful enough to abort block production, so this makes this error a bit softer

 miner: Don't fail on actor not found in selectMessages 

---

Makefile

When building (`make debug`), I get this log on my system (Ubuntu 20.04, go1.14beta1, Make 4.2.1):
```
rm -f lotus
go build  -mod= -ldflags="-X "github.com/filecoin-project/lotus/build".CurrentCommit=+gitbe6badc6.dirty" -tags=debug -o lotus ./cmd/lotus
go: parsing $GOFLAGS: non-flag "\"github.com/filecoin-project/lotus/build\".CurrentCommit=+gitbe6badc6.dirty\""
make: *** [Makefile:56: lotus] Error 1
```
It seems like it's having trouble parsing the shell quotes and https://github.com/filecoin-project/lotus/pull/932 didn't fix it.
My suspicion is that the go command receives these arguments
```
-mod=
-ldflags=-X
"github.com/filecoin-project/lotus/build".CurrentCommit"=+gitbe6badc6.dirty
-tags=debug
...
```
which would explain the error.
This PR uses a `'-K="V"'` style argument to fix the …

Makefile: fix $GOFLAGS

---

cmd/lotus-storage-miner/init.go

So we should pass a bit more than the minimum collateral at the time of miner creation.
Even 0.1% more would be enough.

a bit more than the minimum collateral at the time of miner creation

---

api/api_full.go
api/apistruct/struct.go
chain/store/store.go
node/impl/full/chain.go

This PR adds a new API endpoint and implementation to get a similar output of `ChainNotify` but for arbitrary `from` and `to`. 
The motivation for this is the following:
-  A client is following the chain to build up some index or view about it. 
- The client stops their service. 
- In the meantime, the chain can fork from the last known tipset for the client. 
- When the client resumes, it can't use `ChainNotify` directly since it inspects changes from the current head of the lotus node.
- The client should check if the current head is in the same chain from his last known tipset, because if that isn't the case, it will apply new blocks using (what could be described) the wrong state. 
The whole point of this API is to allow a client to provide his last known tipset, and some other new …

new api to calculate arbitrary forks revert and applys

---

chain/vm/vm.go

Adds fields to the warning in the vm ApplyMessage so we can get better log metrics around failures for messages.

Adding fields to warning in vm ApplyMessage

---

chain/messagepool/messagepool.go

Found some `message to %!s(MISSING) with nonce %!d(MISSING) already in mpool` in the logs.

Add missing fields to duplicate message error

---

build/params_debug.go

`TRUST_PARAMS` is hardcoded to 1 in the debug build configuration which causes the local devnet script (https://lotu.sh/en+setup-local-dev-net) to fail at the moment.
Credit to 0f5fa37a from Slack for finding the workaround.
Error log:
```
2020-01-07T20:46:28.852Z        ERROR   miner   miner/miner.go:178      mining block failed: computing election proof:
github.com/filecoin-project/lotus/miner.(*Miner).mineOne
/lotus/miner/miner.go:298
- failed to compute snark for election proof:
github.com/filecoin-project/lotus/chain/gen.ComputeProof
/lotus/chain/gen/gen.go:552
- No cached parameters found for proof-of-spacetime-election-a4e18190d4b4657ba1b4d08a341871b2a6f398e327cb9951b28ab141fbdbf49d
github.com/filecoin-project/filecoin-ffi.GeneratePoSt
/lotus/extern/filecoin-ffi/proofs.go:675 …
```

params_debug.go: remove $TRUST_PARAMS override

---

storage/fpost_sched.go

User sent this panic.
```
2020-01-18T12:30:45.311Z	[33mWARN[0m	storageminer	storage/fpost_sched.go:148	Aborting Fallback PoSt (EPS: 2595)
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0xec6bcf]
goroutine 308 [running]:
github.com/filecoin-project/lotus/chain/types.(*TipSet).Height(...)
/root/lotus/chain/types/tipset.go:136
github.com/filecoin-project/lotus/storage.(*fpostScheduler).shouldFallbackPost(0xc00029c070, 0x1f20b60, 0xc01de8c930, 0x0, 0x1f20b60, 0xc01de8c930, 0xc01e136800, 0xa23)
/root/lotus/storage/fpost_sched.go:160 +0x11f
github.com/filecoin-project/lotus/storage.(*fpostScheduler).update(0xc00029c070, 0x1f20b60, 0xc01de8c930, 0x0, 0x0, 0x0)
/root/lotus/storage/fpost_sched.go:114 +0x50 …
```

fpost: Don't panic with nil new tipset

---

api/api_full.go
api/apistruct/struct.go
chain/stmgr/call.go
cli/chain.go
cli/state.go
node/impl/full/state.go
storage/miner.go

Input types are a bit limited right now, but this is already pretty useful. 
Example:
```
why@sirius ~/c/lotus> ./lotus state call t0222 12
return: peerID: 12D3KooWNFmyeVbLf6wvPrHNdiaJg5gawTuNmXyP8cKuZDEhPzXb
why@sirius ~/c/lotus> ./lotus state call t02 6 t0333
return: bigint: 1374389534720
```
It also lets you run methods at any given tipset by passing the global 'tipset' flag before the 'call' command.

implement state call command for easy method calling

---

cmd/lotus-health/main.go
cmd/lotus-health/main_test.go

the test scenario 'healthyHeadCheckWindow5' was causing index out of bounds errors.
the second range function in checkWindow was iterating over the incorrect slice of cids.
should be comparing latest items in slices first.
adds more test scenarios to catch any potential index out of bounds errors.

range over right index to prevent bounds errors

---

Makefile

```
➜  lotus git:(fix/current_commit_flag) ✗
➜  lotus git:(fix/current_commit_flag) make
rm -f lotus
go build -ldflags='-X="github.com/filecoin-project/lotus/build".CurrentCommit=+git4436148f' -o lotus ./cmd/lotus
go run github.com/GeertJohan/go.rice/rice append --exec lotus -i ./build
rm -f lotus-storage-miner
go build -ldflags='-X="github.com/filecoin-project/lotus/build".CurrentCommit=+git4436148f' -o lotus-storage-miner ./cmd/lotus-storage-miner
go run github.com/GeertJohan/go.rice/rice append --exec lotus-storage-miner -i ./build
rm -f lotus-seal-worker
go build -ldflags='-X="github.com/filecoin-project/lotus/build".CurrentCommit=+git4436148f' -o lotus-seal-worker ./cmd/lotus-seal-worker
go run github.com/GeertJohan/go.rice/rice append --exec lotus-seal-worker -i ./build
Caution: you …
```

fix CurrentCommit in Makefile

---

.gitignore
cmd/lotus-health/main.go
cmd/lotus-health/main_test.go
cmd/lotus-health/notify.go

add retry logic when calls to API fail.
if API reconnects fail, restart lotus-daemon as it means lotus-daemon is likely unhealthy.
wait for lotus node's chain to sync during each check cycle, to avoid restarting lotus-daemon if needing to sync.
handle SIGTERM properly.
general cleanup and refactor of code, getting ready of unnecessary channels

refactor lotus-health agent for robustness

---

.dockerignore
Dockerfile
Makefile

1. Add Dockerfile file, mostly borrow from ipfs project
2. Add .dockerignore file
3. Modify Makefile to build extern submodule 'filecoin-ffi' from source instead of download from github release
This PR can close issue:  #594

add docker support

---

tools/dockers/docker-examples/basic-miner-busybox/Dockerfile

Minor improvements:
* Use `1.13-buster` instead of `1.13.4-buster` base image (since patch versions are not expected to break compatibility)
* `MAKE_TARGET` build argument (enables `make debug`-builds which are required for smaller sectors/devnet)
* Copy all binaries beginning with `lotus-` into light stage. e.g. `lotus-seed` and `lotus-seal-worker`. Watching out not to copy source package `lotuspond` here.

Dockerfile: more binaries

---

storage/sealing/fsm.go
storage/sealing/fsm_test.go

The `SectorCommitFailed` struct can be created [from within `Sealing#handleCommitting`](https://github.com/filecoin-project/lotus/blob/9fc5f0cd9d43c1d31bbf9a0d80dfa57ac4f84862/storage/sealing/states.go#L191), and is created if `actors.SerializeParams(params)` produces an error or if `m.api.MpoolPushMessage(ctx.Context(), msg)` produces an error. 
The `planCommitting` function [needs to handle this struct (it currently produces an error)](https://github.com/filecoin-project/lotus/blob/9fc5f0cd9d43c1d31bbf9a0d80dfa57ac4f84862/storage/sealing/fsm.go#L209).

planCommitting must handle SectorCommitFailed

---

documentation/en/.library.json

This PR adds Fedora instructions to the library schema so that the docs website can render them.
Merging because it is not a controversial change.

documentation: updates library schema with fedora instructions

---

node/modules/storageminer.go
storage/fpost_run.go
storage/fpost_sched.go
storage/miner.go

We have extracted much of the lotus storage miner into the go-storage-miner project. The go-filecoin node will consume this extracted software, and we hope that lotus will too. The go-filecoin node handles PoSt scheduling differently than lotus does; to support both consumers we have split the PoSt scheduler from the storage miner.
- export `FPoStScheduler`
- storage miner module now instantiates and runs the `FPoStScheduler` (instead of the `Miner`)

split PoSt scheduler from Miner in preparation for extraction

---

go.mod
go.sum
node/modules/client.go
node/modules/storageminer.go

Actually solve bug causing retrieval tests to fail
Bug in retrieval we believe had to do with needing to buffer io for CBOR Unmarshalling above the level of cbg.GetPeeker (i.e. pass a bufio.Reader to UnmarshalCBOR so cbg.GetPeeker does not construct one, so that successive unmarshals do not fail if for some reason there are multiple CBOR objects in buffer)
Also updates go-fil-markets to master

Update go-fil-markets to solve retrieval bug

---

chain/sync.go

the bad tipset cache was originally used to prevent nodes from accepting chains based on blocks designated as 'bad', but it didnt prevent nodes from accepting blocks that themselves were marked bad (but who otherwise had a clean history). This should prevent any incoming bad blocks from being considered as potential sync candidates.

mark bad should be respected for every incoming tipset

---

cmd/lotus-storage-miner/init.go
documentation/en/local-dev-net.md
lotuspond/spawn.go
scripts/dev/sminer-init
scripts/init-network.sh

- Added a new `pre-sealed-metadata` flag to specify the location of the metadata for the presealed sectors.
- Load storage directories from config
- Shifted the metadata loading to outside of the genesis miner condition

Support multi storage directories in miner init

---

documentation/en/join-testnet.md

Without HTTPS specified, the link fails to load in a fresh setting (try a new browser or Incognito mode to confirm).

Use HTTPS for links to the dashboard

---

cmd/lotus-shed/keyinfo.go

lotus-shed: add back support for bls and secp after sig changes

---

api/api_common.go
api/apistruct/struct.go
cli/cmd.go
cli/log.go
node/impl/common.go

Add a log command to the common api which allows for listing all initialized golog subsystems, and setting their log level during runtime.
Command description also adds golog environment variable documentation.

cmd: add log command

---

cmd/lotus-fountain/main.go

The current error message doesn't really tell miners what to do to fix the problem. C.f.: https://github.com/filecoin-project/lotus/pull/1260

Faucet: Provide more info when a user tries to create a miner with a non-BLS address

---

cmd/lotus-chainwatch/main.go
cmd/lotus-chainwatch/sync.go

Running chainwatch on a new database OOM pretty quickly. I'm pretty sure the actor map can be cleared for each batch.

chainwatch: reduce memory usage during large chain gaps

---

cmd/lotus/daemon.go
cmd/lotus/rpc.go
go.mod
go.sum

This diff does two things:
- Enables the Prometheus metrics endpoint 
- Reports the version of lotus being run in said metrics.
Confirmed it worked by spinning up the lotus node and curling the endpoint:
```
curl -s http://127.0.0.1:1234/metrics | grep lotus_info
lotus_info{version="0.2.8+gitc0ef65f4"} 1
```
Let me know if you would like to see this done differently and I can take a crack at it.

Enable Prometheus metrics endpoint and add lotus version

---

api/api_common.go
api/apistruct/struct.go
cli/net.go
go.sum
node/impl/common.go

As in commit message. Some points of discussion:
- The `CommonAPI` now has access to a `BaseIpfsRouting` router
- Tested it manually by running a node and issuing requests from the CLI and cURL

Re: #1232: Add a FindPeer RPC method

---

lib/jsonrpc/client.go
lib/jsonrpc/options.go
lib/jsonrpc/websocket.go

Closes #127
This is a continuation of https://github.com/filecoin-project/lotus/pull/1146, since the main idea of the other PR changed.
---
There's a new tag available `retry:"true"`.
e.g" 
```
ChainHead              func(context.Context) (*types.TipSet, error)                `perm:"read" retry:"true"`
```
It works the same if the return value is a chan or not.
The meaning is: the function call will not return with failure on a closed websocket channel. It will keep retrying while the connection is trying to be reestablished.
If the connection is closed before `sendRequest`; saying it differently, the method is called with a closed connection:
- if retry is true, will keep trying until the connection is resumed
- if retry is false, will fail immediately with an `err` of closed connection …

fix issue #127

---

cmd/lotus/daemon.go
cmd/lotus/rpc.go
go.mod
go.sum

Since we are already using opencensus elsewhere, it was suggested to switch to using the opencensus exporter for prometheus stats.
This has a similar end result to the prior diff, except I'm excluding the git commit hash (I can add it back easily if needed).
```
lotus_info{version="0.2.8"} 1
```

Swap to opencensus for publishing data to prometheus

---

markets/storageadapter/client.go

Fix a bug where storage deals were marked active prematurely in the StorageClient because the condition for detecting deals being active was wrong
Use DealState.SectorStartEpoch to determine if a deal is active, rather than Proposal.StartEpoch

fix(markets): detect storage deal active correctly

---

tools/stats/head_buffer.go
tools/stats/head_buffer_test.go
tools/stats/main.go
tools/stats/rpc.go

I used the `HeadChange` type instead of a tipset because it has a string field that is easy to test :man_shrugging:

stats: add small head change buffer to reduce collecting extraneous stats from small reorgs

---

go.mod
go.sum
markets/retrievaladapter/provider.go
node/impl/client/client.go
paychmgr/simple.go

Retrieval market is failing due to issues creating payment channels with specs-actors. This solves several of those issues -- it can now create the channel -- but it there is still a seperate issue creating vouchers.
1. First issue is serializing constructor params for PaymentChannel -- was missing the From field
2. Second issue is that the storage miner actor address was being passed in the call to create payment channel -- which then fails in the paych actor. The reason is cause right now we had not been translating from the storage miner actor address to the actual wallet address in retrieval in responding to queries. This is addressed in: https://github.com/filecoin-project/go-fil-markets/pull/130 and integrated here, so that the retrieval deal is initialized with the miner's actual …

Fix issues with payment channels

---

api/api_full.go
api/apistruct/struct.go
cli/cmd.go
cli/wallet.go
cmd/lotus/main.go
node/impl/full/wallet.go

Basically as in #1290. Usage is as follows:
- `lotus wallet sign <msg>` signs `<msg>` with the wallet's default account
- `lotus wallet sign --from <addr> <msg>` signs <msg> with <addr>
- `lotus waller verify <addr> <msg> <sigBytes>` prints "Valid" if <sigBytes> is a valid signature of <msg> by <addr>, else prints "Invalid"

Re: #1290: Add sign and verify CLI commands

---

node/config/def.go

The current default worker count of 5 can result in high memory usage of the lotus-storage-miner process when a user starts multiple sector pledges within a short time of each other and can result in the process being killed for OOM.
Reducing the worker count to 2 will provide a safer default.

Reduce default storage miner worker count

---

chain/store/store.go
chain/sub/incoming.go
chain/sync.go
cmd/lotus/daemon.go
lib/jsonrpc/handler.go
metrics/metrics.go
peermgr/peermgr.go

This diff adds some metrics that will be handy for establishing cluster health for the lotus nodes. Example prometheus output:
```
lotus_chain_height 84481
lotus_chain_node_height 724
lotus_info{commit="+git08678e27",version="0.2.8"} 1
lotus_peer_count 14
lotus_rpc_request_success{method="Filecoin.ChainHead"} 6
lotus_rpc_request_success{method="Filecoin.MpoolPending"} 6
lotus_rpc_request_success{method="Filecoin.StateGetActor"} 6
lotus_rpc_request_success{method="Filecoin.SyncState"} 2
lotus_rpc_response_success{method="Filecoin.ChainHead"} 6
lotus_rpc_response_success{method="Filecoin.MpoolPending"} 6
lotus_rpc_response_success{method="Filecoin.StateGetActor"} 6
lotus_rpc_response_success{method="Filecoin.SyncState"} 2
```
I'll do another pass, but this feels like a good bare-bones …

More opencensus metrics

---

go.mod
go.sum
paychmgr/paych.go

Get deal flow tests passing, verifying retrieval flow
- Load full addresses for payment channels so vouchers can be signed and verified properly
- Fixes a bug with saving vouchers and catching duplicates
- Updates to version of go-fil-markets that solves a retrieval bug (see related PR: https://github.com/filecoin-project/go-fil-markets/pull/134)
- Gets TestAPIDealFlowReal to pass

Fix issues with payment channels, pass deal flow tests

---

api/api_full.go
api/apistruct/struct.go
build/version.go
chain/stmgr/call.go
chain/stmgr/utils.go
chain/sync.go
chain/vm/vm.go
cli/client.go
cli/state.go
cmd/lotus-storage-miner/init.go
miner/miner.go
node/impl/full/state.go
paych/paych.go
storage/miner.go
storage/sealing/checks.go
storage/sealing/sealing.go

- Invoking the RPC method StateReplay now provides the total call chain, inlcuding invoked messages (internal txs)
- Returns null if chain had no invoked messages

Re: #1239: Expose information about invoked messages

---

api/api_full.go
api/apistruct/struct.go
api/test/deals.go
cli/client.go
go.mod
go.sum
lotuspond/front/src/Client.js
node/impl/client/client.go

Support easy file transfer to IPFS by importing/exporting CAR files
- Change the ClientImport and ClientRetrieve commands to take a FileRef, which specifies both Path and whether to treat the file as a CAR
- Add a "car" boolean option to the `client import` and `client retrieve` commands at the command line

Add ability to import CAR files and retrieve to a CAR file

---

api/api_full.go
api/apistruct/struct.go
api/types.go
cli/chain.go
cli/state.go
cmd/lotus-shed/main.go
cmd/lotus-shed/stateroot-stats.go
node/impl/full/chain.go

- Adds `ChainStatObj` to full node API which gathers size and ipld link stats about an object as well as provide a way to compare the difference between two objects.
- Adds `chain stat-obj` to expose `ChainStatObj` on the cli.
- Adds `stateroot-stats` command to lotus-shed to gather stateroot obj stats.

Add stat-obj to API and a few extras

---

chain/sub/incoming.go
metrics/metrics.go

Remove tags that made certain metrics have really high cardinality if that information is needed it should be provided by logs, sorry, otherwise the performance of Prometheus will rather quickly die. Also, made it so the default views isn't the only way to access the views, now someone can register single metrics if they wish.

remove high cardinality tags from metrics

---

api/api_full.go
node/impl/client/client.go

This enables, from a _proposalCid_ having the _dealID_, which is useful for calling:
`StateMarketStorageDeal(context.Context, uint64, types.TipSetKey) (*actors.OnChainDeal, error)`

Add DealID to DealInfo

---

chain/vm/vm.go

Otherwise as a miner you are able to include an invalid message forever
and get whole GasLimit of gas from it every time.

Check for correct nonce before taking gas

---

cli/chain.go

We lost the ability to get raw hex cbor when the `--as-type` as added.

cli: add cbor-hex type to chain get

---

chain/vm/vm.go

Fixes #1393 
My bad, didn't realise that the returned vmctx could be nil.

Bugfix: Check if vmctx is nil before dereferencing in ApplyMessage

---

lib/jsonrpc/server.go

I was having troubles configuring an nginx reverse-proxy when
using Websockets.
It turns out my configuration was sending a "Connection: upgrade"
header, but Lotus expected "Connection: Upgrade".
This commit converts the check to be case-insensitive.
Some of the examples on the MDN page show lower-case "upgrade",
so I think it's not unusual for the usage to vary.

Make websocket connection upgrade header check case-insensitive

---

go.mod
node/builder.go
node/modules/chain.go
node/modules/client.go
node/modules/dtypes/storage.go
node/modules/graphsync.go

Graphsync can only run a single instance on a given libp2p node. We were setting up two. This unifies the instance for chainstore and for data transfer.
- setup a single implementation of graphsync used by both chain & data transfer
- use a loader that will read from the chain blockstore and then fall back to the client blockstore if it can't read from it

unified graphsync instance

---

chain/messagepool/messagepool.go
chain/sub/incoming.go

- This commit slightly weakens the current invalid message check
- The behaviour is that if you can't add a message to your pool, you *probably* won't broadcast it to your peers
- The exceptions are that you will broadcast a message if you fail to validate it because nonce / balance lookup fails
- This commit also adds a "nonce too high" check that invalidates a message if its nonce is over 100 than the best nonce you have for the sender
- This commit also lowers the invalid message log to debug (to lessen the annoyance of several invalid messages coming in, and hopefully to prevent confusion among node operators)

Re: #1302: Refine invalid message filtering

---

chain/vm/runtime.go
chain/vm/vm.go

Probably wanna wait on [this commit](https://github.com/filecoin-project/chain-validation/commit/41580ca375ccd85d827dc0856cc352bc919e1590) entering master in chain-validation before merging this, but it's good for review.
Implements the change in point #4 here: https://github.com/filecoin-project/specs/issues/894

Calculate new actor addresses as per updated spec

---

chain/vm/vm.go
go.mod
go.sum

take snapshot after gas transfer so its not reverted on method failure

---

chain/vm/vm.go

It should charge miner but we don't have that mechanism yet.

Missmatching nonce does not charge gas

---

chain/blocksync/graphsync_client.go
node/modules/graphsync.go

This gets the TestSyncSimple test working for the chain -- though it appears other tests are still failing and it would be helpful to get insight from those who know the other tests as to why they failing
- store blocks to chain blockstore (ok for now, since storage provider runs in miner process, where storing of data transfers happens)
- simplify request fetching and processing
- use a special simplified selector for first tipset fetches
- simplify processing request results. error & results channel always close at the same time internal to graphsyncs code (neither will close until the whole request is complete -- no race), so unless you care about content, you can let a request complete by just listening to one channel till it closes.

Fixes to make graphsync work for chain fetching

---

cli/auth.go

This simplifies roughly 3 steps of remote worker config into one (cat api address, create auth token, manually combine into an env var) into one

cli: auth api-info

---

cmd/lotus-storage-miner/market.go

Why:
* It is failing if the number of arguments is the expected one.

Fix offline deal import command arguments check

---

api/test/deals.go
node/impl/client/client.go
node/node_test.go

While retrieving data with `IsCAR` flag enabled, the miner fails with messages `no such file or directory`. I extended the `TestDealFlow` test to cover this scenario, so it can be used to reproduce the problem, and check that it's working correctly too.
To reproduce the problem, take this PR branch, revert the `client.go` change and run the test. 
Output:
```bash
~/code/lotus jsign/testnet3/badfiledescriptor ❯ go test ./node -run TestAPIDealFlow$  
...
...
--- FAIL: TestAPIDealFlow (6.79s)
--- FAIL: TestAPIDealFlow/WithExportedCAR (3.31s)
deals.go:147: open /var/folders/f1/m0gxrgsx7kg53w82gndwr4mc0000gn/T/lotus-retrieve-test-360081011/ret: no such file or directory
FAIL
FAIL    github.com/filecoin-project/lotus/node  7.312s
FAIL
```
Of course, with the `client.go` fix test pass.
The …

fix ClientRetrieve with CAR exporting & add test coverage

---

api/api_full.go
cli/client.go
cmd/lotus-storage-miner/market.go
node/impl/client/client.go

Provide more useful information at the command line about Deals to folks who can't monitor the logs of their node
Client Deals:
- Pass through the Message parameter from ClientDeal all the way to the command line for `client list-deals` -- this will often contain useful information about the deal status, particularly in the case of an error -- it will show something about WHY the deal failed
- update PieceRef to PieceCID, since that's what it is now
Miner Side:
- have `lotus-storage-miner deals list` call MarketListIncompleteDeals -- this method calls the poorly named (but soon to be renamed) storageprovider.ListIncompleteDeals -- which gives you actually all LOCAL deal state info -- which is way more than storageprovider.ListDeals which provides only what is on chain. this means you can …

Better deal info at the command line

---

chain/blocksync/blocksync_client.go
chain/sync.go
lib/increadtimeout/incrt.go

Main change here is detecting if we get fewer bstips back when requesting messages than we expect, and then requesting the rest if that happens.

properly handle partial sync responses

---

chain/actors/aerrors/error.go
chain/actors/aerrors/error_test.go
chain/actors/aerrors/wrap.go
chain/blocksync/cbor_gen.go
chain/types/cbor_gen.go
chain/vm/gas_v0.go
chain/vm/invoker.go
chain/vm/invoker_test.go
chain/vm/mkactor.go
chain/vm/runtime.go
chain/vm/vm.go

We thought this was fine before, but apparently theres an exitcode in use that is outside the byte range. So this rips off the bandaid and just uses the exitcode type everywhere

use exitcode type from specs actors instead of byte

---

cmd/lotus-shed/import-car.go
cmd/lotus-shed/main.go

This allows for importing any data into chain blockstore which is handy when debugging state divergences between nodes

shed: import-car for state debugging

---

chain/state/statetree.go
chain/state/statetree_test.go
chain/vm/invoker.go
chain/vm/invoker_test.go
chain/vm/vm.go

state tree snapshots are currently the number one thing in chain validation profiles, this should improve things a bit

avoid flushing disk when doing state tree snapshots

---

.gitignore
tools/dockers/docker-examples/basic-miner-busybox/Dockerfile

The `basic-miner-busybox` Dockerfile is currently broken because of two issues.
Issue 1: missing `jq` dep now required to build `extern/filecoin-ffi`:
```bash
touch build/.update-modules
make -C extern/filecoin-ffi/ .install-filcrypto
make[1]: Entering directory '/lotus/extern/filecoin-ffi'
./install-filcrypto
+ auth_header=()
+ '[' -n '' ']'
++ dirname ./install-filcrypto
+ cd .
+ rust_sources_dir=rust
++ jq -r '.[].rustc_target_feature'
./install-filcrypto: line 23: jq: command not found
+ optimized_release_rustc_target_features=
make[1]: Leaving directory '/lotus/extern/filecoin-ffi'
make[1]: *** [Makefile:11: .install-filcrypto] Error 127
make: *** [Makefile:28: build/.filecoin-install] Error 2
The command '/bin/sh -c cd $SRC_DIR   && mkdir $SRC_DIR/build   && . $HOME/.cargo/env   && …
```

docker: fix build, upgrade Go

---

chain/blocksync/graphsync_client.go
go.mod
go.sum
markets/storageadapter/client.go
markets/storageadapter/provider.go
node/builder.go
node/impl/client/client.go
node/impl/storminer.go
node/modules/dtypes/storage.go
node/modules/graphsync.go
node/modules/storageminer.go

Updates dependencies for graphsync, fil-markets, data-transfer. Moves to new graphsync blockstore
swapping capabilities, and also locks down graphsync impl so it does not accept arbitrary requests
- Update fill markets node adapters
- Update fil markets method calls (couple renames)
- Update graphsync setup to lock down graphsync to only data transfer and chainsync requests
- Use new Graphsync multiple blockstore capabilities to swap out chain blockstore for graphsync requests
should be merged at the same time as https://github.com/filecoin-project/go-filecoin/pull/3978

Update to latest go-fil-markets w/ enhanced Graphsync

---

chain/gen/genesis/miners.go
chain/stmgr/call.go
chain/stmgr/forks_test.go
chain/stmgr/stmgr.go
chain/stmgr/utils.go
chain/store/weight.go
chain/validation/applier.go
chain/vm/syscalls.go
chain/vm/vm.go
node/impl/client/client.go

One commit removes block miner from the VM (it's unused afaic tell), and @frrist wants it GONE.
Second commit adds a validity check before proposing a storage deal (pieceSize must be < sectorSize), and also changes to passing the actual sector size to the Storage Miner client (not zero).

Two minor improvements

---

chain/types/blockheader.go
chain/vm/syscalls.go

This impl is heavily based on the structure of https://github.com/filecoin-project/go-filecoin/blob/d75e700d2b5b116a794c3da672d6379bcb24b803/internal/pkg/slashing/check.go#L40.
A few things to note:
- No check whether blocks are in chain yet. I am not sure they are needed.
- Implementing tipset operations (e.g. `Contains`) based on CIDs rather than tipsets given the headers submitted to `VerifyConsensusFault` may be invalid (and yet the faults themselves may not be).
- Should maybe use `VerifySignature` instead of making `VerifyBlockSig`

VerifyConsensusFault syscall impl

---

chain/gen/genesis/util.go

Small GasLimit here gets in the way when trying to generate a genesis with many sectors.

increase gas limit during genesis generation

---

cmd/lotus-seed/main.go

This needs to be some valid PeerId to things marshal correctly. If it's unset `lotus-storage-miner init` fails due to a failure to decode the PeerId.

lotus-seed: preserve first peerid during merge

---

go.mod
go.sum
markets/retrievaladapter/client.go
paychmgr/simple.go

Closes #1552 
Support non-blocking creation of payment channel and adding funds via implementing the new go-fil-markets API, namely:
* `GetOrCreatePaymentChannel` now should
1. If the payment channel doesn't exist:
1. initiate payment channel creation and return `address.Undef` + message CID to wait for
1. Allow a retrieval client to wait for this message CID and receive the new payment channel address when complete
1. Otherwise add the value provided to the existing payment channel
* New API methods: `WaitForPaymentChannelCreation, WaitForPaymentChannelAddFunds`

Feat/retrieval market #1552

---

api/test/deals.go
node/node_test.go

This PR has a new test for checking the issue #1455.
~Test shouldn't pass since this PR adds the test to expose failing.~
The last rebase include the fix, tests should pass.

Double Deal Flow

---

cli/client.go

A storage client that wants to use the `lotus state get-deal` commands needs to know the numerical deal id, and the existing `lotus client list-deals` output does not give them this information.
This PR adds deal id to the `lotus client list-deals` output:
```
DealCid                                                      DealId  Provider  State              PieceCID                                                       Size  Price    Duration  Message
bafyreifva6e2hn4sgwnxo26lssck6a7m42qachu56sp5wq2ioh6ajrxsne  2       t01000    StorageDealActive  bafk4chzaovmkytus7lwq3awuu2tb7txzaakeij76j4ekmanc4cydra5eiuzq  1016  1000000  2744
```

add deal identity to client list-deals output

---

cli/multisig.go

- Create was only using default address as sender (bad)
- Propose and Approve weren't actually using the "source" flag
- Approve wasn't sending the proposal hash param in `TxnIDParams`, which is not an optional param
With these changes the multisig workflow works #1084

Fixes to multisig functionality in CLI

---

node/modules/chain.go
node/modules/client.go
node/modules/storageminer.go

We are seeing `routing: operation or key not supported` quite a bit and it's making noise in the logs.

bitswap: disable provider

---

api/apistruct/struct.go
chain/vm/runtime.go
chain/vm/runtime_test.go
cmd/lotus-storage-miner/proving.go
go.mod
go.sum
node/builder.go
storage/miner.go

This should address bugs like https://github.com/filecoin-project/lotus/issues/1624
Rationale for this is that technically the serialization code is part of actor code (cbor-gen), so it failing to execute shouldn't be a fatal error (when we implement user contracts, serialization will live in user code, so it failing there wouldn't be fatal).

 vm: Don't treat actor state serialization errors as fatal 

---

cli/client.go

This PR addresses _Recommendation Z_ [here](https://github.com/filecoin-project/lotus/issues/1518).
The existing CLI does not communicate via the `lotus client list-deals` output (and when) their storage deal was slashed. It also doesn't communicate the epoch in which the sector storing their piece was committed to the network. The existing output is constructed only from local (i.e. not on-chain) deal information.
cc @terichadbourne @mishmosh 
This changeset adds two additional columns to the `lotus client list-deals` command:
- `On Chain?`, which shows either `N` (if sector commitment not yet posted), or `Y (epoch 123)` if it was
- `Slashed?`, which shows either `N` (if deal wasn't slashed), or `Y (epoch 567)` if it was
```shell
13:33 $ lotus client list-deals
DealCid …
```

add on-chain deal information to client list-deals output

---

chain/vm/vm.go

When there is not enough gas to cover the on-chain return value we should proceed as if the method execution failed (according to the [spec](https://filecoin-project.github.io/specs/#vminterpreter-implementation)). Current behaviour returns a non-zero exit code and the result of method execution, this doesn't seem right. (e.g. if executing the method `MinerControlAddresses` and there isn't enough gas to cover the return value on chain, the exitcode `SysErrOutOfGas` is returned along with `GetControlAddressesReturn`)

fix: insufficient gas remaining to cover retval

---

chain/types/blockheader.go
cmd/lotus-bench/main.go
cmd/lotus-seed/seed/seed.go

Tis what go-filecoin does...Spec says use sha, but we use blake2b everywhere else, so I'm guessing this is preferable?

Use blake2b, instead of sha256, for ticket creation and verification

---

cli/state.go

This allows linking directly to invocations by message CID, like https://ipfs.io/ipfs/QmTnnpum9XFBW34hzPSjstKQVpgTk7HhZJETsYVs1tFQae/exec.html#bafy2bzacednhgynrysnxavsjl3speafkrjcii7dhzcwnlegr4glma2wxxzovo

compute-state: html: Hash links to invocations

---

api/cbor_gen.go
chain/blocksync/cbor_gen.go
chain/types/cbor_gen.go
go.mod
go.sum
node/hello/cbor_gen.go
paychmgr/cbor_gen.go

Worth looking at the cbor_gen.go files a little bit, but this improves the situations pretty significantly:
Current testnet/3:
```
why@whynix ~/c/lotus (testnet/3)> go test ./chain/types -bench=. -run=XXX
goos: linux
goarch: amd64
pkg: github.com/filecoin-project/lotus/chain/types
BenchmarkBlockHeaderMarshal-12    	  413956	      2601 ns/op	     880 B/op	      46 allocs/op
BenchmarkSerializeMessage-12      	  801396	      1364 ns/op	     640 B/op	      19 allocs/op
PASS
ok  	github.com/filecoin-project/lotus/chain/types	2.225s
```
This branch:
```
why@whynix ~/c/lotus (deps/update-cbor-gen)> go test ./chain/types -bench=. -run=XXX
goos: linux
goarch: amd64
pkg: github.com/filecoin-project/lotus/chain/types
BenchmarkBlockHeaderMarshal-12    	 1258426	       987 ns/op	      80 B/op	      12 …
```

update to latest cbor-gen

---

chain/sub/incoming.go
go.mod
go.sum
node/builder.go
node/config/def.go
node/modules/lp2p/pubsub.go
node/modules/services.go

- Updates pubsub to the latest master
- Introduces a new configuration specific for pubsub and updates the pubsub constructor to use it.
- Filters remote tracer events to just the essentials in order to reduce bandwidth usage, enables it by default (we want those metrics to ascertain the health of the network in the painnet)
- Adds support for direct peers, which can be configured by the user
TBD:

Improved pubsub integration

---

documentation/en/getting-started.md

Adding a suggested link to the new Filecoin docs site (docs.filecoin.io) to learn about Filecoin concepts.

Add link to new conceptual docs site

---

go.mod
go.sum

proof parameters are no longer pinned to IPFS public gateways, but on collab IPFS Cluster instead
change default gateway url to proofs.filecoin.io

fetch groth parameters from proofs.filecoin.io

---

go.mod
go.sum
node/modules/client.go
node/modules/storageminer.go
node/node_test.go

Updates to the latest fil markets, which targets stream reset issues near the beginning of the deal. We originally attempted a more in depth fix in 0.2.1 but reverted to a more conservative fix in v0.2.2 to not break storage protocol -- mostly cause compatibility with GFC would have required another protocol breaking change AND protocol redesign merits more careful consideration.
- minor change in data transfer API
- make sure to actually run the StorageClient.Run method which actually does something

Update to fil-markets 0.2.1

---

api/api_full.go
api/apistruct/struct.go
cli/multisig.go
node/impl/full.go
node/impl/full/multisig.go

I added the RPC commands that correspond to the cli commands and removed duplicate code so the cli refers to the RPC API. 
- `lotus send` -> `Filecoin.Send`
- `lotus msig create` -> `Filecoin.MsigCreate`
- `lotus msig propose` -> `Filecoin.MsigPropose`
- `lotus msig approve` -> `Filecoin.MsigApprove`
The cli behavior should not be affected by this, purely a structural change.
Below I attached two bash scripts that I used to test the changes. [MsigSendExample.sh.txt](https://github.com/filecoin-project/lotus/files/4576999/MsigSendExample.sh.txt) is for cli commands to make sure this change is backwards compatible, and 
[MsigRPCSendExample.sh.txt](https://github.com/filecoin-project/lotus/files/4577013/MsigRPCSendExample.sh.txt) replaces some of the cli commands to test the new RPC calls. …

Added RPC calls for MsigCreate, MsigPropose, MsigApprove, and MsigCancel

---

go.mod
go.sum

Last update for markets (hopefully) for painnet. Adds connection manager tagging on deals, to keep the streams open.
Source PR in go-fil-markets: https://github.com/filecoin-project/go-fil-markets/pull/246

Update markets 0.2.3

---

cli/cmd.go

This makes `./lotus` look like this:
```
NAME:
lotus - Filecoin decentralized storage network client
USAGE:
lotus [global options] command [command options] [arguments...]
VERSION:
0.3.0
COMMANDS:
daemon   Start a lotus daemon process
version  Print version
help, h  Shows a list of commands or help for one command
basic:
send    Send funds between accounts
wallet  Manage wallet
client  Make deals, store data, retrieve data
msig    Interact with a multisig wallet
paych   Manage payment channels
developer:
auth          Manage RPC permissions
mpool         Manage message pool
state         Interact with and query filecoin chain state
chain         Interact with filecoin blockchain
log           Manage logging
wait-api      Wait for lotus api to come online
fetch-params  Fetch proving …
```

cli: Improve lotus helptext

---

scripts/archive-branches.sh

Add script for archiving branches outside of the main repo.
The branches will end up here: https://github.com/filecoin-project/lotus-archived

Add archive script

---

node/modules/lp2p/pubsub.go

It appears that block propagation in the testnet is slow; I have a very strong suspicion that this is because of an overly aggressive setting of the mesh delivery failure penalty which unmeshes peers quite a bit.
This turns it off for now, until the network grows.

Turn off Mesh Delivery Failure penalty

---

lib/jsonrpc/rpc_test.go
lib/jsonrpc/websocket.go

havent fixed the test yet, but this test shows the simplest failure mode

properly select channel ID to close for handleOutChans

---

.circleci/config.yml

/home/ognots/.bin not in path, causing macos test to fail
test build confirming solution https://circleci.com/gh/filecoin-project/lotus/24644

install jq in /usr/local/bin

---

cmd/lotus-storage-miner/info.go

Should hopefully resolve this:
```
lotus-storage-miner info
Miner: t01002
Sector Size: 32 GiB
Byte Power:   0 B / 563 TiB (0.0000%)
Actual Power: 0  / 518 Ti (0.0000%)
Committed: 11.2 TiB
panic: runtime error: integer divide by zero
goroutine 1 [running]:
main.glob..func1(0xc000467b90, 0x0, 0x0)
/opt/filecoin/cmd/lotus-storage-miner/info.go:108 +0x19bb
gopkg.in/urfave/cli%2ev2.(*Command).Run(0x43feee0, 0xc000467b30, 0x0, 0x0)
/go/pkg/mod/gopkg.in/urfave/cli.v2@v2.0.0-20180128182452-d3ae77c26ac8/command.go:167 +0x6cf
gopkg.in/urfave/cli%2ev2.(*App).Run(0xc000001800, 0xc0000c2020, 0x2, 0x2, 0x0, 0x0)
/go/pkg/mod/gopkg.in/urfave/cli.v2@v2.0.0-20180128182452-d3ae77c26ac8/app.go:261 +0x68c
main.main()
/opt/filecoin/cmd/lotus-storage-miner/main.go:81 +0x696
```

avoid dividing by zero if pset is empty

---

cli/client.go

having any deal that errored before it got a dealID currently causes this command to fail with 
`Index 0 not found in AMT`
Fixes #1783

Prevent client list-deals from crashing

---

cmd/lotus-storage-miner/info.go

In my case, the correct information is `Committed 21, Proving 14, 7 Faulty 33%`.
But it shows:
```
Miner: t027999
Sector Size: 64 GiB
Byte Power:   14.2 TiB / 976 TiB (1.4541%)
Actual Power: 14.2 Ti / 899 Ti (1.5780%)
Committed: 21.2 TiB
Proving: 7.12 TiB (7.06 TiB Faulty, 49.77%)
```
Faulty is not a part of Proving, it's a part of Committed.

Pset represents the proving sectors, and Sset repensents all sectors

---

node/modules/client.go

https://github.com/ipfs/go-filestore/blob/master/fsrefstore.go#L293-L295
this check fails if i run something like below:
```
IPFS_PATH=./repo lotus client generate-car ./repo/hello.txt ./repo/hello.txt.car
```
since `FileManager.root` is relative here, and `FilestoreNode.PosInfo.FullPath` is always abs

use abs path to construct FileManager

---

chain/sub/incoming.go
node/modules/lp2p/pubsub.go

@schomatis suggested that we can't really validate them (yet), so we shouldn't confer any meaningful score advantage for first message deliveries in the `msgs` topic.
This sets the cap to the minimal value of 1, so that message deliveries confer at most a tiny (0.025) score advantage.
Also adds a log for the block validation time, as this appears to be an issue.

sink message topic deliveries

---

go.mod
node/builder.go
node/modules/lp2p/relay.go

It's an attack vector for cheap eclipse attacks. Plus we really don't need relay for a storage network.

Unconditionally disable relay

---

api/api_full.go
api/apistruct/struct.go
api/test/deals.go
cli/client.go
go.mod
go.sum
lib/ipfsbstore/ipfsbstore.go
node/builder.go
node/config/def.go
node/config/load.go
node/impl/client/client.go
node/modules/ipfsclient.go
node/repo/fsrepo.go

This PR has three changes.
**Automatic environment variables wiring for .toml config file**
Currently, a user can only change configuration attributes in a .toml file. Now a `LOTUS_` prefix is wired to be considered for changing these attributes.
The env variable name respects the logical grouping, some examples of use:
- `LOTUS_API_LISTENADDRESS=...`
- `LOTUS_CLIENT_USEIPFS=...`
- `LOTUS_METRICS_NICKNAME=...`
Environment variables _takes precedence_ over configurations in the .toml file, as usually expected.
**Allow using a remote IPFS node as the underlying blockstore**
This extends the work done #1641. That meant using a local IPFS node as the underlying block storage for getting data to start deals.
This PRs adds two extra features:
- It allows to use of a remote IPFS node providing …

Allow remote IPFS node support & IPFS for data retrieval & automatic env wiring

---

go.mod
go.sum

This is a patch release, fixing a bug in outbound mesh quota maintenance.

Update go-libp2p-pubsub to v0.3.1

---

chain/validation/applier.go
chain/validation/factories.go
go.mod
go.sum

required for https://github.com/filecoin-project/chain-validation/pull/208

update chain-val syscalls interface

---

documentation/en/local-dev-net.md
documentation/en/mining-troubleshooting.md
scripts/dev/gen-daemon
scripts/devnet.bash
scripts/init-network.sh

Fixes #1174 in combination with commit `fa863595` (already in master).
Commit `fa863595` modified various CLI commands to accept a human-readable sector size. We should update docs and scripts, too.

update scripts and docs to use human-readable sector size

---

api/api_common.go
api/apistruct/struct.go
cmd/lotus-seal-worker/main.go
cmd/lotus-storage-miner/main.go
cmd/lotus-storage-miner/run.go
cmd/lotus-storage-miner/stop.go
cmd/lotus/daemon.go
cmd/lotus/rpc.go
node/builder.go
node/impl/common/common.go
node/modules/dtypes/shutdown.go

Moving down the list; fixes #1827.
We'd like to be able to stop the lotus daemon and storage miners without resorting to `CMD+C` / `SIGTERM` (if foregrounded) or `kill` (if backgrounded).
This PR adds a `lotus daemon stop` command and a `lotus-storage-miner stop` command. Both of these commands require that the RPC server be running; RPC server handles inbound message by sending a value to a channel which, when consumed, shuts down HTTP server and node (or storage miner).

add (sub)commands which shut down lotus daemon and storage miner

---

api/api_full.go
api/apistruct/struct.go
build/params_shared.go
chain/stmgr/stmgr.go
cli/multisig.go
cli/paych.go
cli/state.go
cmd/lotus-fountain/main.go
cmd/lotus-shed/verifreg.go
cmd/lotus-storage-miner/init.go
go.sum
markets/retrievaladapter/client.go
markets/storageadapter/client.go
markets/storageadapter/provider.go
node/impl/full/state.go
paychmgr/simple.go
storage/adapter_storage_miner.go
storage/miner.go
storage/wdpost_run.go

closes  #1854
`StateWaitMsg` returns as soon as a message is found on chain. This does not account for reorgs, so it is dangerous to tie critical functionality to `StateWaitMsg`. This PR adds confidence intervals and timeouts to StateWaitMsg to make it safer.
Specifically, the waiting logic has been changed to:
1. Delay returning until a message found in a new block has been on chain for the confidence interval.
2. Reset if the tipset containing the message is reverted.
3. Delay returning if a message found on the existing chain hasn't been on for the confidence interval.
4. Ignore messages found on the existing chain that have been reverted since the search started.
5. Timeout search after a given number of epochs past the head at the time the wait started.
Default parameters for …

Add confidence and timeout to message wait

---

paychmgr/simple.go

Fixes #1611 
Should have returned on error != nil, now it does.  I'm not sure what should be done about it from the caller's POV if the message never gets posted though.

fix unhandled nil return

---

cli/chain.go
node/impl/full/chain.go

Now instead of doing `./lotus chain get /pstate/@Ha:t04/1`, and getting:
```
[
"ADjmwAAAAA==",
"ADepRTL+AA==",
"ABGYBgsXYhmCbE0=",
515,
{
"/": "bafy2bzaceboonml5vyodbbod4vxyjxrrmcovmsr2djmcezxtwhxdr6lfpctyc"
},
11641,
{
"/": "bafy2bzaceb2oxxk6vc6tzangdpr7wjwnzs6pfc3i2k2jwhgldsujzlbepujpu"
},
66,
{
"/": "bafy2bzaced24ohrb5tw5mqcgsratjechwretpgpcy7mqnyzqn7y3y7qtbxj2s"
}
]
```
You can do `./lotus chain get /pstate/@Ha:t04/@state`, and get:
```
{
"Claims": {
"/": "bafy2bzaceb2oxxk6vc6tzangdpr7wjwnzs6pfc3i2k2jwhgldsujzlbepujpu"
},
"CronEventQueue": {
"/": "bafy2bzacebrjefxtl52sccb6ple6k3gzzwjvtfnqh2opbtiidr4igut3v5blq"
},
"LastEpochTick": 11641,
"MinerCount": 515,
"NumMinersMeetingMinPower": 66,
"ProofValidationBatch": {
"/": "bafy2bzaceae4sjmfoxk4qrcbim32crfdqqbnxyzxhsd56jebfkb7hbvdxurma"
}, …
```

chain get: @state selector to prettify actor state

---

chain/store/index.go
chain/store/store.go

The idea here is to effectively implement a skip list for searching back into the chain. The reason I went with this approach is that you don't have to worry about dealing with forks, the logic works the same no matter what chain swapping you do.
Still need to do a bit of testing here, but all the current tests pass, which implies its at least not blatantly broken.

implement chain index to make lookbacks faster

---

chain/store/store.go

I'm going to work on adding some caching to `GetTipsetByHeight`, as its used in a number of places throughout the codebase that are performance critical. Before doing that, I'm making GetRandomness reuse that codepath as a separate change, as its a little bit tricky and deserves independent review.

reuse GetTipsetByHeight in GetRandomness

---

go.mod
go.sum

The panic is caused by usage of internal protobuf interface.
It was changed in protobuf 1.4.0 and reluctantly fixed in 1.4.2

Fix protobuf panic by updating protobuf to 1.4.2

---

node/impl/full/state.go

Calling `UnlockVestedFunds` was mutating the state to actually unlock those funds, resulting in them being unlocked when we call `GetAvailableBalance`. We then double-count them by adding `vested` to the output of `GetAvailableBalance`.
`CheckVestedFunds` tells us what's unlockable without actually mutating this state, so this should be correct.

Correct double-counting in StateMinerAvailableBalance

---

chain/sync.go
cmd/lotus/daemon.go
metrics/metrics.go

Produces additiona output via OpenCensus and Logging:
OpenCensus
```
lotus_block_validation_ms 5547.91
...
lotus_process_cpu_cgo_calls 225
lotus_process_cpu_goroutines 629
lotus_process_heap_alloc 8.1291232e+07
lotus_process_heap_idle 4.4269568e+07
lotus_process_heap_inuse 8.5557248e+07
lotus_process_heap_objects 706433
lotus_process_heap_release 4.4138496e+07
lotus_process_memory_alloc 8.1291232e+07
lotus_process_memory_frees 1.677996e+06
lotus_process_memory_lookups 0
lotus_process_memory_malloc 2.384429e+06
lotus_process_stack_inuse 4.390912e+06
lotus_process_stack_mcache_inuse 13888
lotus_process_stack_mspan_inuse 911336
lotus_process_sys_heap 1.29826816e+08
lotus_process_sys_memory_alloc 1.43001848e+08
lotus_process_sys_stack 4.390912e+06
lotus_process_sys_stack_mcache 16384 …
```

Express block validation time via OpenCensus

---

cli/chain.go
cli/client.go
cli/state.go

Various lotus commands display quantities of bytes, which can be unwieldy. We should use the `units` package uniformly.
- client commP
- client local
- client find
- client query-ask
- client list-deals
- state sector-size

display quantities of bytes in human-readable format

---

documentation/en/.library.json

Guessing this is why the systemd section is currently blank on lotu.sh

Doc fix: use correct file name

---

documentation/en/join-testnet.md
documentation/en/setup-troubleshooting.md

When running `lotus` from scratch on my macOS laptop, I noticed a bunch a warnings in the logs about Badger not being able to run compaction, due to hitting the open files limit.
On my machine (macOS 10.15.5):
```
$ ulimit -n
256
```
So I suggest adding a note about it in the docs, maybe even worth checking it when booting up Lotus?

docs: add a note about open files limit

---

node/builder.go
node/config/load.go
node/repo/fsrepo.go
node/repo/interface.go
node/repo/memrepo.go
node/repo/repo_test.go

We want some CLI stuff which will allow an operator to fiddle with various config options (e.g. whether the storage miner is accepting storage deal proposals). 
This PR adds a `SetConfig` method, which accepts (you guessed it) a config object-mutator. The mutator is applied to the current config object which is then TOML-encodes and written to the repo. The `Config` method continues to decode these TOML bytes into a Go struct on the way out.

expose config-setting through Repo interface

---

documentation/en/setting-a-static-port.md
node/builder.go
node/config/def.go

In go-ipfs, it is possible to manually configure addresses to announce
or not announce to the swarm.
https://github.com/ipfs/go-ipfs/blob/master/docs/config.md#addressesannounce
This PR adds the same feature to Lotus. It can be configured from the [libp2p]
section of either the .lotus or .lotusstorage config.toml file. Example:
[Libp2p]
ListenAddresses = ["/ip4/0.0.0.0/tcp/34515", "/ip6/::/tcp/34515"]
AnnounceAddresses = ["/ip4/52.13.91.110/tcp/34515"]

Make libp2p swarm Announce / NoAnnounce addresses configurable

---

cli/wallet.go

Fixes #805.
1. We could write the warning to stderr instead of stdout
1. I could do something more-sophisticated and try to figure out if the chain needed synchronizing and had (or not) been synchronized.

display a little inline warning if balance is zero

---

api/api_storage.go
api/apistruct/struct.go
cmd/lotus-storage-miner/main.go
cmd/lotus-storage-miner/market.go
node/builder.go
node/config/def.go
node/impl/storminer.go
node/modules/dtypes/miner.go
node/modules/storageminer.go

This changeset makes incremental progress towards #1920.
This PR adds a `Config` get/set pair to the DI graph for the new `AcceptingStorageDealProposal` bool. The getter always loads config TOML from disk, and is called by the storage deal provider when it receives a storage deal proposal. The setter is called through two new CLI commands: `lotus-storage-miner deals disable` and `lotus-storage-miner deals enable`.
By default, a storage miner is configured to accept storage deals.

allow miner to disable/enable consideration of received storage deal proposals

---

chain/store/store.go
chain/sync.go

Avoid tipset revalidation to speed up messages synchronization, if the lotus daemon is restarted during the process. This is especially necessary if the synchronization is behind the latest height by a lot.
Resolves: https://github.com/filecoin-project/lotus/issues/1561
This is a new PR, using the approach as discussed in: https://github.com/filecoin-project/lotus/pull/1560

Cache tipset validation progress

---

documentation/en/hardware-mining.md
documentation/en/mining-lotus-seal-worker.md

Running the initial command `lotus-seal-worker run` gave an error about `--address` being a required parameter.
After setting that to `127.0.0.1:2345` the miner started to freak out and sectors broke as the mining process locked up.
It seems like in the mean time the sealing work has already been moved into the `lotus-storage-miner` and thus doesn't need to run alongside the miner. 
Changed the docs to what I think is correct now - but please check, I could be horribly wrong :)

Update documentation about Lotus Seal Worker

---

api/api_full.go
api/apistruct/struct.go
cli/client.go
node/impl/client/client.go

This PR creates a new `ClientMinerQueryOffer` API and adds support in the CLI for making retrievals for arbitrary deals for the desired miner.
Currently, `lotus client retrieval` searches for miners storing a PayloadCid in a local table. That is, we can only retrieve data if the same Lotus node had made the deals since it's how the local table is kept. When `lotus client retrieval` is executed, it looks for those locally-known miners and selects the first as the retrieval miner for the data.
Now `lotus client retrieval` accepts a `--miner` flag, which indicates that the client want's to retrieve the data from a particular miner. This means it won't rely on _local knowledge_ for the retrieval. This allows to retrieve data made by other Filecoin client, e.g: I tell a friend that my data has …

Miner QueryOffer API & non local-discovery retrieval CLI support

---

cli/client.go
node/impl/client/client.go

Consider `QueryOffer.Status` before calling `ClientRetrieve`, and be aware of non-errored `Retrieval.Query` calls that have non-success `.Status`.
Continuation of #2040
cc @whyrusleeping

Consider QueryOffer Error & Status

---

storage/wdpost_run.go

This caused panics when all sectors were faulty

wdpost: Don't return nil from checkSectors

---

api/api_common.go
api/apistruct/struct.go
cmd/lotus-seal-worker/main.go
node/impl/common/common.go

Fixes https://github.com/filecoin-project/lotus/issues/771
We don't want to finish currently executing jobs, because we won't be able to get the result to the miner anyways, so the best thing we can do, at least for now, is just to restart the whole process automatically

seal-worker: Auto-restart if miner dies

---

api/api_storage.go
api/apistruct/struct.go
cmd/lotus-storage-miner/main.go
cmd/lotus-storage-miner/market.go
go.mod
node/impl/storminer.go

Fixes #2027.
Miners need to be able to set their ask's minimum and maximum piece size in addition to price and duration.
This PR replaces the `lotus-storage-miner set-price` command with `lotus-storage-miner deals set-ask` and `lotus-storage-miner deals get-ask` commands.

add ask-manipulating (and printing) deal subcommands

---

chain/vm/runtime.go
go.mod
go.sum

Based on `lotus-0.6.1-chargegas` in specs-actors.

Update to specs actors with ChargeGas interface

---

documentation/en/hardware-mining.md

This fixes a bad link.
There's also a link to the Github issue thread for results that still works, but
is a bit stale (for proofs before v20). I didn't attempt to fix that as there
doesn't appear to be a thread for v27 proofs.

Fix bad link in hardware mining docs

---

chain/types/bigint.go
chain/types/bigint_test.go

Fixes #1993
@magik6k @arajasek - The [`SizeStr`](https://github.com/filecoin-project/lotus/blob/ffa7be86fe6ee738ab4b095469029b9fac51e090/chain/types/bigint.go#L79) function used the format string `"%.3g %s"`, so the rounding and scientific notation make sense (given the format string).
We have a few options:
1. (contained in this PR) We can bump from 3 digits to 4
1. (seems bad) We can leave things as they are
1. (seems bad) We can replace the `%g` verb with `%f` (decimal point but no exponent, e.g. `1016.000 B`)
As you might expect, this problematic behavior manifests with other values. For example `1024000` bytes displays as `1e+03 KiB`.
This PR bumps from 3 to 4 digits, and adds a test which asserts that our `SizeStr` function behaves more or less identically to the `units.BytesSize` …

bump from 3 to 4 digits in format-string used by types.SizeStr

---

documentation/en/.glossary.json

The excised entry previously rendered twice in the glossary under two different keys. This commit removes one of those KV pairs to avoid that.
See the duplicate "Filecoin Testnet" entries in the screenshot below:

Remove redundant glossary item

---

api/api_storage.go
api/apistruct/struct.go
cmd/lotus-storage-miner/market.go
node/builder.go
node/config/def.go
node/impl/storminer.go
node/modules/dtypes/miner.go
node/modules/storageminer.go

Addresses the storage provider side of [this request](https://github.com/filecoin-project/lotus/issues/1920#issuecomment-639007435) from @whyrusleeping.
This PR adds three new commands `lotus-storage-miner deals get-blocklist` (writes the piece CID blocklist to stdout, one per line, using the specified encoding), `lotus-storage-miner deals set-blocklist` (replaces the existing storage miner piece CID-blocklist with the contents of the provided file or the CIDs read from stdin), and `lotus-storage-miner deals reset-blocklist`, which wipes the storage miner's blocklist.

allow storage miners to manage a blocklist of piece CIDs

---

build/bootstrap.go
build/flags.go
node/modules/storageminer.go

Project Oni needs to make Lotus friendly to be imported as a library. The go.rice boxes get in the way, as they are appended to the executable, which makes them only accessible when running Lotus from a binary.
We _could_ embed these assets by converting them to Go source (rice embed-go mode). However, that bloats up the source tree considerably, and it's terrible for Git repo sizes over time. See an exploration of that here: https://github.com/filecoin-project/lotus/compare/feat/rice-embed.
When using Lotus as a library, it's also kinda useless to do the "magic" of loading things; this is an advanced mode of use where the developer is likely to pursue a high degree of customisation of things. 
Example: our test plans won't be hitting the public bootstrap peers, won't be using the devnet …

provide an option to disable loading of built-in assets.

---

node/impl/client/client.go

Fixes #2111 
The `lotus client retrieve` command hangs indefinitely if the retrieval proposal was rejected.
This PR handles the rejection case, which causes the now-hanging method to return (producing an error on the client).

return error if retrieval deal rejected

---

chain/beacon/drand/drand.go
chain/beacon/drand/drand_test.go
node/modules/services.go

This exposes a `DrandConfig` struct that contains the drand server URLs and chain info, so that we can override in testground to point at a test drand deployment. 
This is in service of https://github.com/filecoin-project/oni/issues/15
@Kubuxu I'm still getting up to speed with the lotus dependency injection. Is this all I need to do in order to be able to set my own `DrandConfig` with `node.Override`?  
And to actually do the override, it would be something like `node.Override(new(drand.DrandConfig), myConfigProviderFunc)` maybe?

allow overriding drand config

---

build/params_shared.go
chain/beacon/drand/drand.go
chain/beacon/drand/drand_test.go
node/builder.go
node/modules/dtypes/beacon.go
node/modules/lp2p/pubsub.go
node/modules/services.go

This is a quick follow up to #2115 that provides the `DrandConfig` using a provider function in `modules/services.go`. It also updates the pubsub constructor to use the Drand chain hash from DI instead of reading from the `build.DrandChain` var directly.

improve DrandConfig dependency injection

---

go.mod
go.sum

This pulls in https://github.com/filecoin-project/sector-storage/pull/54 and https://github.com/filecoin-project/sector-storage/pull/56
Fixes https://github.com/filecoin-project/lotus/issues/1917
Fixes https://github.com/filecoin-project/lotus/issues/2080

Update sector-storage to fix #2080 and #1917

---

api/test/deals.go
api/test/mining.go
chain/events/events_called.go
chain/events/events_height.go
go.mod
go.sum
miner/miner.go

Also race fix: depends on https://github.com/ipfs/go-blockservice/pull/65
Resolves #2092, #2099, #2108, #1930, #2110

Fix two races in events

---

api/api_storage.go
api/apistruct/struct.go
cmd/lotus-storage-miner/main.go
cmd/lotus-storage-miner/market.go
cmd/lotus-storage-miner/retrieval-deals.go
node/builder.go
node/config/def.go
node/impl/storminer.go
node/modules/dtypes/miner.go
node/modules/storageminer.go

This PR makes incremental progress on #1920 by allowing storage miners operating as retrieval miners to disable/enable consideration of retrieval deals.
This PR adds a new configuration option which gates consideration of received retrieval deal proposals. 
**It also replaces the `lotus-storage-miner deals` subcommand with `lotus-storage-miner storage-deals`, and introduces the `lotus-storage-miner retrieval-deals` subcommand.**

allow retrieval miner to enable/disable consideration of retrieval deal proposals

---

api/api_full.go
api/apistruct/struct.go
build/version.go
cli/state.go
cmd/lotus-chainwatch/sync.go
go.mod
go.sum
node/impl/full/state.go

This was causing issues for a partner since the bitfield doesn't get meaningfully encoded into the JSON return object...I think the bitfield should stay an internal type, probably shouldn't be crossing the wire.

Return sector numbers, not bitfields from API

---

miner/miner.go

Although this modification will not affect the result, logically speaking, it should not be `return`, it should be `continue`

fix: mining logic

---

go.mod
go.sum

Brings https://github.com/filecoin-project/go-bitfield/pull/17
Fixes https://github.com/filecoin-project/lotus/issues/2164

Update go-bitfield with fixed empty marshaling

---

go.mod
go.sum
markets/storageadapter/client.go
markets/utils/converters.go
node/impl/client/client.go

To support dumbo-drop/Discovery teams, publish a hotfix release for go-fil-markets with @whyrusleeping's adds for Multiaddrs on miners
- Updates markets to 0.3.1
- Implement Client adapter GetMinerInfo method
- Pass MinerInfo multiaddrs when constructing StorageProviderInfo structs

Update to markets 0.3.1

---

chain/events/events_called.go

Fixes https://github.com/filecoin-project/lotus/issues/2191
I'm actually not sure why the panic occurred, it seems that we are only accessing the map within locks. But I moved a couple of things around that should help us maintain more strict correctness in any case, so hopefully this will fix it.

Fix concurrent map access panic in event API

---

Makefile
build/params_2k.go
build/params_shared_funcs.go
build/params_shared_vals.go
build/params_testground.go
build/params_testnet.go
chain/gen/gen.go
chain/messagepool/messagepool.go
chain/sync.go
chain/sync_test.go
chain/types/fil.go
cli/sync.go
cmd/lotus-health/main.go
cmd/lotus-seed/genesis.go
cmd/lotus-storage-miner/info.go
cmd/lotus-storage-miner/market.go
cmd/lotus-storage-miner/proving.go
cmd/lotus/debug_advance.go
documentation/en/block-validation.md
go.sum
markets/storageadapter/client.go
markets/storageadapter/provider.go
miner/miner.go
node/impl/common/common.go
node/modules/services.go
node/modules/testing/beacon.go
node/node_test.go
tools/stats/rpc.go

This configurability is unlocked through the `testground` build tag, which Project Oni uses.
The reason we need to tinker with these parameters is to test scenarios like forking, chain halting, ill syncing, etc. in an accelerated manner.
Changes in the usage places of these relaxed constants were required due to the fact that Golang constants are untyped, but vars aren't.
Read https://blog.golang.org/constants for more info.

make system constants configurable as vars.

---

chain/stmgr/utils.go

This function is currently the most expensive thing showing up in traces, this should help significantly.

use bitfields to enumerate sectors for winning post

---

cmd/lotus-chainwatch/main.go
cmd/lotus-chainwatch/mpool.go
cmd/lotus-chainwatch/storage.go
cmd/lotus-chainwatch/sync.go
node/impl/full/state.go

- define a miner sector schema to store miner sector details at each tipset the miner experiences a
state change. This solution stores redundant data since a miner state change (head cid changes)
does not necessarily indicate its sectors changes.
- makes progress towards sentinel/issues/10 by implementing a schema for miner sectors (proven but not yet expired sectors) and populating it during chain syncing.

feat: define miner sector schema

---

api/api_storage.go
api/apistruct/struct.go
api/test/ccupgrade.go
cmd/lotus-storage-miner/sectors.go
go.mod
go.sum
node/impl/storminer.go
node/node_test.go
storage/sealing.go

CC upgrade

---

go.mod
go.sum

Upgrade markets to hotfix 0.3.1.1 to resolve node restarting issue. Also includes @vyzo 's fix for concurrent map access in retrieval.

Hotfix upgrade markets to 0.3.1.1 to master

---

lib/bufbstore/buf_bstore.go

This should actually significantly improve perf sync. We are seeing a lot of time spent just checking if a given object exists in the has-caching wrapped badger datastore. Doing this both means fewer objects that we need to check for, and it also means that most of the cids will likely end up in the 'has cache', making that faster in general.

check underlying datastore for objects before putting to bufbstore

---

cmd/lotus-chainwatch/storage.go
cmd/lotus-chainwatch/sync.go

A follow on to https://github.com/filecoin-project/lotus/pull/2233 that wires up the new miner predicate and uses it to update the `miner_sector_events`
`miner_sector_events` tracks the stateroot a sector is `ADDED`, `EXTENDED`, `EXPIRED` or `TERMINATED` at.

polish: wire up miner state predicate

---

api/test/deals.go
api/test/mining.go
api/test/test.go
api/test/window_post.go
cmd/lotus-seed/main.go
cmd/lotus-seed/seed/seed.go
miner/miner.go
miner/testminer.go
node/node_test.go

This adds an `error` argument to the callback returned by the mining `waitFunc`, so that we can call it when we get an error mining a block.
This is to fix our synchronized mining setup in testground - it currently gets stuck if there's a mining error because it's waiting for the callback (see https://github.com/filecoin-project/lotus/issues/2193). Adding the error argument lets us invoke the callback in the error case and inform the other end whether we're advancing to a new round or not.
This is a breaking API change for anyone currently using `NewTestMiner` from another project (I updated the call sites here). I can  add a new constructor instead that wraps the two-argument callback if we care about that, but it's a pretty easy fix and should only affect tests.
CI is complaining about …

add error argument to waitFunc callback in miner loop

---

chain/events/state/predicates.go
chain/events/state/predicates_test.go
cmd/lotus-chainwatch/storage.go
cmd/lotus-chainwatch/sync.go

For https://github.com/filecoin-project/sentinel/issues/10
Add miner predicate for calculating the changes made to a miners sector AMT. Changes that cause `true` to be returned from `OnMinerActorChange` are:
- 1 or more sectors are added to a miners sector set.
- 1 or more sectors expiration field changes. (sector extension)
- 1 or more sectors are removed from a miners sector set.
thanks @dirkmc for making me aware of this!
cc @placer14 I intend to use this in chainwatch for tracking miner changes, later we can extend this to track changes to other miner state fields we are interested in.

feat: add miner sector predicate and test

---

chain/store/store.go
journal/journal.go
node/builder.go
node/modules/core.go

implement a persistent journal for lotus node operations

---

chain/vm/syscalls.go

That's what specky-actory says we should do
Fixes #1981

VerifyConsensusFault should return an error if no fault is found

---

chain/events/events_called.go
chain/events/events_test.go
chain/events/utils.go
markets/storageadapter/client.go
markets/storageadapter/provider.go

When a sector contains multiple deals(pieces), only the first deal's state is change to StorageDealActive, and the other deal's state still keep as StorageDealSealing. Mainly because of matchEvent(markets/storageadapter/client.go:327 and markets/storageadapter/provider.go:317) returns true, cause behind deals matchEvent cannot trigger, lead to can not correctly into StorageDealActive, and can't trigger RecordPieceInfo(in: go-fil-markets/storagemarket/impl/providerstates/provider_states.go).

a sector contains multiple deals(pieces), the state of deals incorrect

---

go.mod
go.sum
node/repo/fsrepo_ds.go

It reduces badger file descriptor usage from 1900 to 140 for node synced to
testnet chain.
These options are the defults in badger `master` now.
We should update to next badger version as soon as it is stable, it has
some nice improvments.

Use mostly defaults for badger options

---

go.mod
go.sum
markets/storageadapter/provider.go
node/modules/client.go
node/modules/storageminer.go

upgrade to latest markets with fast retrieval, underlying data transfer upgrade
- Upgrade markets version
- Redo construction of data transfer instances to work with new code
- Add GetDataCap method to provider node
- Add OnDealSlashedOrExpired on provider node side (just copied @dirkmc 's client side implementation -- we may want to extract common code here in the near future)
- Attempted FastRetrieval -> KeepUnsealed handoff but had to back out cause storage-fsm dependency sector-storage has compile errors in version that implements KeepUnsealed. (and w/o panics when calling into sector-storage)

Upgrade markets with fast retrieval support

---

cmd/lotus-storage-miner/info.go
cmd/lotus-storage-miner/main.go
cmd/lotus-storage-miner/proving.go

I'd like to be able to check the state of a given miner from the perspective of another miner. For example if miner A has sealed a deal with a given client, and then disappears, I want to be able to use the `lotus-storage-miner` tools (`proving info`, `info`, etc.) to visualise that sectors are marked as faulty.
---
Currently this is enabled for:
```
lotus-storage-miner info
lotus-storage-miner proving info
lotus-storage-miner proving deadlines
lotus-storage-miner proving faults
```
Probably we will want to do something similar also for other read-only commands as well in the future.
---
cc @raulk @vyzo @yusefnapora

add `actor` flag to `lotus-storage-miner` for proving and info calls

---

api/api_storage.go
api/apistruct/struct.go
api/test/ccupgrade.go
api/test/deals.go
api/test/mining.go
cmd/lotus-bench/main.go
cmd/lotus-seed/seed/seed.go
cmd/lotus-storage-miner/storage.go
go.mod
go.sum
markets/storageadapter/provider.go
node/impl/storminer.go
node/node_test.go
node/repo/fsrepo.go
node/repo/interface.go
node/repo/memrepo.go

Support fast-retrieval deals

---

lib/lotuslog/levels.go

RtRefreshManager logs random binary strings, which somtimes might be
partial multi-byte Unicode or ASCI escape codes.

Mute RtRefreshManager logs as they break terminal emulation

---

cmd/lotus-storage-miner/init.go

Without this, if I have 3 pre-sealed sectors and then pledge a new one, my IDs go [0, 1, 2, 4...]

Correct initial setup of sector id counter

---

miner/miner.go

Still need to:
* Do a similar thing in mempool
* Select messages with 'worse' prices based on how good our ticket is
* Guess real message gas use
* Make this faster
* Make this better
But this PR should improve things

miner: Use gas price when selecting messages

---

api/api_full.go
api/apistruct/struct.go
api/test/deals.go
cli/client.go
node/impl/client/client.go

Add optional `piece *cid.Cid` parameter to `ClientFindData` and `ClientMinerQueryOffer`, to restrict offer results to miners which have the specified piece.
Resolves #2150

Add piece cid to retrieval queries

---

cmd/lotus-seal-worker/main.go

`lr.Datastore("/")` broke after the multi-blockstore refactor

Fix seal-worker init

---

node/repo/importmgr/mbstore.go

This PR fixes the
```
2020-07-10T17:39:37.697+0200    WARN    main    lotus/main.go:81        Retrieval Failed:
github.com/filecoin-project/lotus/cli.glob..func20
/home/magik6k/github.com/filecoin-project/go-lotus/cli/client.go:592
- ClientRetrieve: failed to get block for bafy...: datastore: key not found
```
retrieval issue

Fix retrieval datastore-key-not-found error

---

tools/stats/metrics.go

This API is commented out and logs an error every time it is called. I suggest we disable the call altogether, until it is implemented again.
Relevant API at: https://github.com/filecoin-project/lotus/blob/master/node/impl/full/state.go#L191

disable call to StatePledgeCollateral

---

cmd/lotus-chainwatch/main.go
cmd/lotus-chainwatch/storage.go
cmd/lotus-chainwatch/sync.go

Part of https://github.com/filecoin-project/sentinel/issues/22
This PR creates new schema that chainwatch uses to capture:
- chain baseline power from RewardActor
- miner (quality adjusted/raw bytes) power from MinerActor

chainwatch: Capture power from miner and reward actors

---

paychmgr/paych.go
paychmgr/paych_test.go
paychmgr/state.go

When adding a new voucher, check if the total channel Balance would be exceeded.
For example if a channel has
- balance: 10 
- lane 1: 3
- lane 2: 4
Add voucher for lane 1 with value 7 should fail:
- lane 1: 7 (voucher supersedes lane redeemed)
- lane 2: 4
- total: 11 (greater than account balance 10, so fail)
Add voucher for lane 1 with value 5 should succeed:
- lane 1: 5 (voucher supersedes lane redeemed)
- lane 2: 4
- total: 9 (less than account balance 10, so succeed)
Add voucher for lane 3 with value 2 should succeed:
- lane 1: 3
- lane 2: 4
- lane 3: 2
- total: 9 (less than account balance 10, so succeed)

Account for other vouchers when checking balance

---

cli/client.go

- Add a `maxPrice` option to the `client retrieve` CLI
- Use the lowest-priced offer if multiple retrieval offers are returned
Resolves #2151

Add a maxPrice option to the client retrieval CLI

---

chain/sync.go

The `from` and `to` naming always confuses me and has me spinning every time I revisit this code. This PR introduces more specificity in the naming.

rename sync variables.

---

chain/events/events_height.go

My understanding is hnd.called should be set to 'true' after handle be called.

set called 'true' after handle be called

---

chain/sync.go

From tipset bundle, you don't need to serialize and generate Cids before checking the length. Avoids extra computation on invalid block

Check message length before generating Cids

---

node/impl/full/state.go

Looks like most of these were fixed (or changed) recently, but this one was forgotten.

Fixing hamt bittreewidth

---

chain/sync.go
storage/miner.go

Standard tag to filter log. I can live with this and close https://github.com/filecoin-project/lotus/issues/2397.

debug: standard PoSt tag

---

miner/miner.go
miner/miner_test.go

This test is flaky on `next`. The reason is that the test expects to find a selected message in a given index, but whether that's true or not will be affected by underlying map access order, which is undefined in Go.
Ordering the key access is probably not how you want to solve this. We could make the test assertion laxer such that it doesn't care where the message is, as long as it's returned. But I don't know if undeterministic result ordering is what you want.
This seems like the safest option (given my lack of understanding of downstream effects that the ordering could have), and it helps me illustrate the problem.
```sh
⟩ go test -count=1000 -run=TestMessageFiltering ./miner
ok  	github.com/filecoin-project/lotus/miner	0.624s
```

fix flaky test (miner#TestMessageFiltering).

---

build/params_shared_vals.go
chain/gen/gen.go
chain/market/fundmgr.go
chain/stmgr/forks_test.go
chain/types_test.go
chain/vm/gas.go
chain/vm/gas_v0.go
chain/vm/mkactor.go
chain/vm/vm.go
cli/chain.go
cli/send.go
cmd/chain-noise/main.go
cmd/lotus-bench/import.go
cmd/lotus-fountain/main.go
cmd/lotus-shed/nonce-fix.go
cmd/lotus-shed/verifreg.go
cmd/lotus-storage-miner/init.go
go.mod
go.sum
markets/storageadapter/client.go
markets/storageadapter/provider.go
miner/miner_test.go
node/impl/full/mpool.go
node/impl/full/multisig.go
node/impl/full/state.go
node/impl/paych/paych.go
node/node_test.go
paychmgr/simple.go
storage/adapter_storage_miner.go
storage/wdpost_run.go

Make virtual gas real

---

api/api_storage.go
api/apistruct/struct.go
cmd/lotus-storage-miner/market.go
go.sum
node/builder.go
node/config/def.go
node/impl/storminer.go
node/modules/dtypes/miner.go
node/modules/storageminer.go

And reject deals that start too early.
Fixes #2048

Add expected seal duration to custom deal logic

---

cmd/lotus-chainwatch/dot.go
cmd/lotus-chainwatch/main.go
cmd/lotus-chainwatch/processor/common_actors.go
cmd/lotus-chainwatch/processor/market.go
cmd/lotus-chainwatch/processor/messages.go
cmd/lotus-chainwatch/processor/miner.go
cmd/lotus-chainwatch/processor/processor.go
cmd/lotus-chainwatch/processor/reward.go
cmd/lotus-chainwatch/run.go
cmd/lotus-chainwatch/syncer/sync.go

Part of https://github.com/filecoin-project/sentinel/issues/26
Chainwatch can now:
- capture base_block_rewards per state_root
- view top miners by base_block_reward
- wait instead of running non-stop (bug fix from https://github.com/filecoin-project/lotus/pull/2396 where chainwatch would run despite there being no work to process)
- manage its own `--log-level`

Capture base block rewards

---

chain/events/state/diff_adt.go
chain/events/state/predicates.go
cmd/lotus-chainwatch/processor/miner.go
cmd/lotus-chainwatch/processor/processor.go

Corresponding issue: https://github.com/filecoin-project/sentinel/issues/25
Chain-watch now:
- capture sector precommit information in miner_precommits 
- maintains a materialized view combining the information in miner_sectors and miner_precommits 
- renames ADDED to COMMIT in miner_sector_event table
- extend miner_sector_event table to contain a PRECOMMIT event for sector precommits (note this field will be null for genesis miners)
- populate miner_sector_events table with COMMIT events from genesis miners (required special casing)

feat: track miner precommit

---

node/impl/full/state.go

This likely caused the pledge calc for miner sectors to be waaaay off on reset butterfly

fix StateMinerInitialPledgeCollateral

---

chain/gen/genesis/miners.go

Setting the deal to end on the sector expiry ensures we get the full quality adjustment of power for the full sector.
Resolves #2404

genesis: set deals to end on sector expiry

---

lib/peermgr/peermgr.go
miner/miner.go

1. I noticed that `PeerMgr.Run` continues to run, even after calling `fx.app.Stop`, so I am adding it to the lifecycle and stopping the `pmgr.expandPeers()` on `Stop`.
2. I am attempting to fix the deadlock found at https://github.com/filecoin-project/lotus/issues/2406 - I don't see a reason to continue to hold the mutex while waiting on `stopping` or `ctx.Done()`.

Graceful shutdown of PeerMgr

---

cmd/lotus-chainwatch/processor/reward.go
cmd/lotus-chainwatch/syncer/sync.go

Part of https://github.com/filecoin-project/sentinel/issues/21 and https://github.com/filecoin-project/sentinel/issues/26
This PR:
- Updates RewardActor field names
- Includes WinCount when ElectionProof is present with BlockHeader
- updates schema:
- column names `eprof` -> `election_proof` on `blocks`
- add `win_count` on `blocks`
Mea culpa: If the schema name changes are frustrating, let me know and I'll back it out until we have a migration pattern in place. (Soon)

Restore base block reward; capture WinCount w header

---

cmd/lotus-chainwatch/processor/messages.go

fix: use bigint for gas_used in message receipt

---

cli/state.go

It'd be nice if we could use `ComputeStateHTMLTempl` from other packages, for example in Project Oni, so that we generate the state HTML on every tipset and have another tool in our toolbox when debugging test plans.
Related: https://github.com/filecoin-project/oni/pull/158

expose ComputeStateHTMLTempl

---

api/api_full.go
api/apistruct/struct.go
api/test/paych.go
chain/events/state/predicates.go
chain/gen/genesis/genesis.go
chain/gen/genesis/miners.go
chain/stmgr/forks_test.go
chain/stmgr/stmgr.go
chain/store/store.go
chain/validation/applier.go
chain/validation/factories.go
chain/vm/syscalls.go
chain/vm/vm.go
lib/adtutil/cststore.go
node/builder.go
node/impl/paych/paych.go
node/modules/chain.go
node/modules/testing/genesis.go
node/node_test.go
paychmgr/paych.go

Prove the payment channels work as intended
- use the node integration tests
- spin up to full nodes, create a payment channel between them on chain
- Allocate three lanes
- setup two vouchers on each lane (second super-seding the first)
- have the payment channel creator start settling
- Verify the receiver attempts to submit the most valuable vouchers
- When done, collect
- Various issues have been revealed here -- currently, the settlement delay is a single chain epoch, meaning the receiver has very little time to submit their vouchers before the creator can close the channel and collect their money back: https://github.com/filecoin-project/specs-actors/blob/master/actors/builtin/paych/paych_actor.go#L22
- I am getting a nil-pointer exception in the logs when I try to update the …

WIP: Payment channel end to end testing

---

cmd/lotus-chainwatch/main.go
cmd/lotus-chainwatch/run.go

Happy to throw this behind a flag but I don't believe adding the pprof http package has any performance impact when not handling a request.

chainwatch: add http server for pprof

---

api/api_full.go
api/apistruct/struct.go
api/test/paych.go
chain/events/state/predicates.go
chain/gen/genesis/genesis.go
chain/gen/genesis/miners.go
chain/stmgr/forks_test.go
chain/stmgr/stmgr.go
chain/store/store.go
chain/validation/applier.go
chain/validation/factories.go
chain/vm/syscalls.go
chain/vm/vm.go
lib/adtutil/cststore.go
node/builder.go
node/impl/paych/paych.go
node/modules/chain.go
node/modules/testing/genesis.go
node/node_test.go
paychmgr/paych.go
paychmgr/settler/settler.go

When a client (or person sending payments) settles a payment channel, a miner (or party receiving payments) needs to submit any outstanding vouchers on chain before the payment channel closes, lest they become invalid. Currently, we have no mechanism to do this. This PR adds a monitoring routine that checks for settlement messages, and if we are the party that needs to submit before the close, submits all relevant vouchers
- use events.Called API
- match all settlement messages that are also an inbound channel tracked by the payment channel manager
- assuming confidence is reached, look at all vouchers in the channel, determine the best vouchers to submit (defined as the best on each lane), and submit them

Submit vouchers automatically when payment channels settle

---

cmd/lotus-chainwatch/run.go
cmd/lotus-chainwatch/scheduler/refresh_top_miners_by_base_reward.go
cmd/lotus-chainwatch/scheduler/scheduler.go

Part of https://github.com/filecoin-project/sentinel/issues/26
Add pattern for triggering jobs independent of processing cycles. Nothing too fancy.
I imagine the processor eventually has this behavior, but decided not to over-engineer anything but still isolate the worker logic for later migration to a better home.

feat(chainwatch): Ticker triggers view refresh independent of processing

---

cmd/lotus-seal-worker/main.go

allow operators to set an unspecified address - 0.0.0.0 - when setting address flag in 'lotus-worker run'
to extract worker ip, dial the miner api.
if the dial succeeds, a valid route between miner and worker can be inferred
relates to https://github.com/filecoin-project/lotus/issues/2515

Feat/ntwk calibration: unspecified address in lotus-worker run address

---

cmd/lotus-seal-worker/main.go

fixes a bug where only IP is provided without port.
port is required

bug: default address value should include port

---

go.mod
go.sum

Should fix the testnet halt. This is fixed already in next, so this is just a specs actors commit cherry picked onto the last commit used by master.

pull in specs actors fix for testnet

---

cli/paych.go

Closes https://github.com/filecoin-project/lotus/issues/2579.
Note that with this PR `lotus paych get <from> <to> 0.5` will correctly parse the decimal argument.  Actual payment channel creation may still fail because of #2580.

Parse amount as FIL in paych get

---

cmd/lotus-chainwatch/processor/reward.go
cmd/lotus-chainwatch/scheduler/refresh_top_miners_by_base_reward.go
cmd/lotus-chainwatch/scheduler/scheduler.go

Fixes toward https://github.com/filecoin-project/sentinel/issues/26
Chainwatch now:
- properly applies WinCount when calculating `top_miners_by_base_reward` view
- provides a new view called `top_miners_by_base_reward_max_height` which indicates the height where the other view was refreshed.

Top Miner by Reward applies WinCount; Add max_height view

---

cmd/lotus-storage-miner/info.go
cmd/lotus-storage-miner/main.go
cmd/lotus-storage-miner/proving.go

The `--actor` flag was added in https://github.com/filecoin-project/lotus/pull/2252
Due to additional flags set as part of `lotus-storage-miner info` (`--color`), the `--actor` is actually ignored on `lotus-storage-miner`. So I am moving `--color` as a global flag, and also printing the miner we are querying as part of the `lotus-storage-miner proving *` commands.
---
Also fixing a bug in `getActorAddress` where we should return early when the actor address override is set.

fix --actor flag for `lotus-storage-miner info`

---

api/api_storage.go
api/apistruct/struct.go
api/test/deals.go
api/test/window_post.go
cmd/lotus-storage-miner/info.go
cmd/lotus-storage-miner/sectors.go
node/impl/storminer.go

After performing the CC sector upgrade, it seems that the upgrade result cannot be found at present. After adding the sector chain information to the sector status command, it can be found that the `OnTime` in the expiration information has changed. We can use this command to determine whether the CC sector has been upgraded, so as to avoid the launched again upgrade of the sector has been upgraded, while repeating a sector upgrades will not succeed, but is currently only after Committing an error, and before doing PreCommit seal is unnecessary.

add on-chain-info to lotus-miner sectors status command

---

cli/mpool.go

```
[....many lines...]
t3xfrtmseqylkqirpseigbjnzs274angj7odzfapiarzwqjxk2mxsm2pm6gywerqbh467aybq742lzj7y7ryea: past: 0, cur: 1, future: 0
t3xgfxy2crjg6b7l3lgvdl7p75ubucfhrpz4x55qwq5eo52yk2xkbe5ncfalc7yuodchvu3kgmk4okls5m2rhq: past: 0, cur: 0, future: 2
t3xglv457cdnxh3ec72z7ocagm2qhq56pq7wja4pqacl7r5fo3vh3qx7x5jklun2y6wubmq73zjay674gbmaaq: past: 0, cur: 0, future: 1
t3xgtbpdiqdr4a5odmsf6l5yusy6pdfebt2opvpwjj5xnjfl2xjmbitt7c7ijy5me4vqdld4vtqhpfexepqwra: past: 0, cur: 0, future: 2
-----
total: past: 0, cur: 5690, future: 193
```

Print totals in mpool stat

---

documentation/en/updating-lotus.md

Without running `make install` it is possible to have multiple versions of the binary which could cause confusion.

Update filecoin docs correction

---

chain/gen/mining.go
chain/stmgr/stmgr.go
chain/sync.go
go.mod
go.sum
lib/sigs/bls/init.go

This PR replaces the existing BLS signature library with the ‘blst’ library (https://github.com/supranational/blst). 
**About ‘blst’:** ‘blst’ is a BLS signature library focused on security and performance. It currently supports Windows, Mac, and Linux operating systems and the ARM64 and x86_64 architectures. The library is compliant with the in-progress IETF specification and is being tested and integrated by multiple Ethereum clients. The library is currently undergoing formal verification.
**Integration Testing:** This library has been tested with Lotus by creating blocks on a local devnet and has also been able to sync to the public test network. 
**Performance Testing:** Benchmarking was done by comparing the current implementation against blst using …

https://github.com/supranational/blst

---

chain/sync.go
metrics/metrics.go

@placer14 I changed this stat to a histogram as when the metric is exported to prometheus will be represented as a sum as well as a count and histogram. This allows for quantiles to graphed. The only thing you will need to change is the metric name will now have `_sum` on the end of it.

Change block validation aggregation type from sum to distribution

---

chain/messagepool/messagepool.go

The network is currently DoSing itself by rebroadcasting the entire mempool of 10000 messages every few minutes. This should help, at least a little bit

only republish the next few messages from your mempool

---

node/impl/full/state.go

This is a "solution" to some of the 
```
vm	vm/runtime.go:340	Abortf: unlocked balance does not cover pledge requirements (274822064413555114521 < 292981349853194849700)
```
we're seeing on calibnet rn.

Increase PreCommitDeposit and InitialPledgeCollateral overestimation to 1.1x

---

api/types.go
cli/net.go
node/modules/dtypes/scorekeeper.go

Adds support for the new extended pubsub score inspection; modifies the score command to accept an `--extended` flag, which will print the extended scores, including internal counters, as json.

support extended pubsub peer scores

---

go.mod
go.sum
node/modules/lp2p/pubsub.go

As discussed with @whyrusleeping, this changes the tracer behaviour to only trace messages for the blocks topic.
~Depends on https://github.com/libp2p/go-libp2p-pubsub/pull/369~

pubsub: only trace messages for the blocks topic

---

cmd/lotus-chainwatch/processor/miner.go
cmd/lotus-chainwatch/processor/processor.go
cmd/lotus-chainwatch/run.go

- Add a sector event table with the sector lifecycle tracking for:
`'PRECOMMIT_ADDED', 'PRECOMMIT_EXPIRED', 'COMMIT_CAPACITY_ADDED', 'SECTOR_ADDED', 'SECTOR_EXTENDED', 'SECTOR_EXPIRED', 'SECTOR_FAULTED', 'SECTOR_RECOVERING', 'SECTOR_RECOVERED', 'SECTOR_TERMINATED'`
- Enable the miner info code that was previously commented out
- Enable the sector info and precommit info tables that were previously commented out.

refactor(chainwatch): update to work with latest specs-actors miner changes

---

node/builder.go
node/impl/client/client.go
node/modules/client.go
node/modules/dtypes/storage.go
node/modules/ipfsclient.go
node/repo/retrievalstoremgr/retrievalstoremgr.go
node/repo/retrievalstoremgr/retrievalstoremgr_test.go

Always use the right store for retrievals:
- multistore when IPFSRetrieval is disabled
- blockstore (on top of IPFS) when IPFSRetrieval is enabled
A new RetrievalStoreManager to manage this process
Two version:
- one reads/writes directly to the blockstore
- the other reads/writes to the multistore

Retrieval Store Manager

---

api/test/mining.go
cli/chain.go
cmd/lotus-shed/nonce-fix.go
cmd/lotus-shed/verifreg.go
cmd/lotus-storage-miner/actor.go
go.sum
node/impl/client/client.go
node/impl/full/gas.go
node/impl/full/mpool.go
node/impl/full/multisig.go
storage/adapter_storage_miner.go
storage/wdpost_run.go

Definitely very far from the best, but it should make it slightly smarter now
Results for calibration network as of now:
```
$ ./lotus chain gas-price
1 blocks: 1250001 (0.000000000001250001 FIL)
2 blocks: 1250001 (0.000000000001250001 FIL)
3 blocks: 1250001 (0.000000000001250001 FIL)
5 blocks: 1250001 (0.000000000001250001 FIL)
10 blocks: 10 (0.00000000000000001 FIL)
20 blocks: 1250001 (0.000000000001250001 FIL)
50 blocks: 10 (0.00000000000000001 FIL)
100 blocks: 1 (0.000000000000000001 FIL)
300 blocks: 1 (0.000000000000000001 FIL)
```

Improve gas price estimator

---

cmd/lotus-chainwatch/processor/miner.go

Panic:
```
2020-07-31T17:22:28.635-0700    INFO    processor       processor/processor.go:354      Gathered Blocks to Process      {"start": "10071", "end": "10071"}
2020-07-31T17:22:28.916-0700    INFO    processor       processor/processor.go:132      Collected Actor Changes {"MarketChanges": 1, "MinerChanges": 1, "RewardChanges": 1, "AccountChanges": 1, "nullRounds": 0}
2020-07-31T17:22:28.947-0700    INFO    processor       processor/processor.go:161      Processed Reward Changes
2020-07-31T17:22:28.972-0700    INFO    processor       processor/processor.go:169      Processed Message Changes
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa43e03]
goroutine 132349068 [running]: …
```

fix(chainwatch): Miner partition processing panics on nil bitfiled

---

cmd/lotus-bench/import.go

The stmgr calls `GetGenesis` to setup genesis multisigs, which needs to be explicitly set using `SetGenesis`. This wasn't happening during imports.

Fix import

---

cmd/lotus-storage-miner/market.go

Fix a bug where the deal CID output in `lotus-miner storage-deals list` was incorrect.
The deal CID is the CID of the *signed* deal proposal. Previously, we were taking the CID of just the proposal itself, as opposed to the signed proposal, which, due to the additional bytes is different. We already have the CID for the signed proposal directly in the deal struct so we just use that.

Fix proposal CID in `lotus-miner storage-deals list`

---

node/hello/cbor_gen.go
node/hello/hello.go

Self-explanatory. `TArrial` should `TArrival`.

Fix misspelling in HelloMessage

---

markets/retrievaladapter/client.go

Make markets adapters work properly with new payment channel code
- Update adapter to use wait methods provided by paych adapter
This is an initial conversion -- not really optimized (we shouldn't block any more on AddFunds until neccesary) -- but seems like an MVP to get the payment channel improvements out the door. We can continue to augment and extend in future PRs

feat(markets): update for new paych logic

---

api/api_full.go
cli/client.go
go.mod
go.sum
markets/retrievaladapter/client.go
node/impl/client/client.go
node/modules/client.go

Resolve dialing errors via https://github.com/filecoin-project/go-fil-markets/pull/356
- Implement GetKnownAddresses on RetrievalClientNode adapter
- Convert to passing around the full retrieval peer in the API structs
- Sorry @arajasek it ended up not making sense to have a RetrievalProviderInfo given we already have a RetrievalPeer and it just started to get confusing with too many structs

Update markets to resolve dialing errors

---

cmd/lotus-seal-worker/main.go
documentation/en/mining-lotus-worker.md

Clarify the flag on the worker process to be the local address and port the worker will listen on, and not the address of the miner.

lotus-worker: change address flag to listen

---

chain/events/state/predicates.go
chain/events/state/predicates_test.go
chain/market/fundmgr.go
chain/market/fundmgr_test.go
node/builder.go

Match the operations of the FundMgr comprehensively with the expectations of the markets module.
The markets module is responsible for how much money is needed for deals in progress. The FundMgr now has a single responsibility: track how much is actually in the storage market actor for each address and add funds as needed when EnsureAvailable is called.
- Added a new state predicate for the StateChanged events API to track changes in market balances. This is comprised of StatePredicates.OnBalanceChanged and StatePredicate.AvailableBalanceChangedForAddresses, which compose with each other on top of StatePredicates.OnStorageMarketActorChanged. AvaialbleBalanceChangedForAddresses takes a function which returns an array of addresses to evaluate on each new change in tipset.
- Modified …

Improve Fund Manager

---

api/api_full.go
api/apistruct/struct.go
api/test/paych.go
chain/vm/runtime.go
cli/paych.go
gen/main.go
markets/retrievaladapter/client.go
node/builder.go
node/impl/paych/paych.go
paychmgr/accessorcache.go
paychmgr/cbor_gen.go
paychmgr/channellock.go
paychmgr/manager.go
paychmgr/msglistener.go
paychmgr/msglistener_test.go
paychmgr/paych.go
paychmgr/paych_test.go
paychmgr/paychget_test.go
paychmgr/settle_test.go
paychmgr/simple.go
paychmgr/state.go
paychmgr/store.go
paychmgr/store_test.go

Currently when creating a channel or adding funds to an existing channel, the payment channel manager locks up until the messages have been confirmed on chain, which can take several minutes.
This PR resolves the locking issue:
- Operations on each channel are executed sequentially
- Operations on different channels can run in parallel
This PR also manages the state of requests and restores them if lotus is shut down and restarted:
- On startup checks for pending create channel / add funds messages that have been sent to chain
- Writes state to the datastore each time there's a state change
- Keeps track of channels by from / to instead of by channel address, so that state can be written even before channel has been created
This PR also
- sets a flag on channels that are in the "settling" …

Fixes locking issues when creating channel / adding funds

---

scripts/build-bundle.sh

With the full output written to the file, users can verify the tar.gz integrity with `sha512sum -c <release>.tar.gz.sha512`

release: write full sha512sum output to file

---

paychmgr/paychget_test.go
paychmgr/settle_test.go

The payment channel manager tests were sleepy 😴 
This removes all the sleeps (and makes the tests faster as a result).
Resolves comment https://github.com/filecoin-project/lotus/pull/2640#pullrequestreview-462077927

Fix paych sleepy tests

---

cli/paych.go

Previously if a user ran
`lotus paych get <from> <to> <amt>`
the command would block until the channel was created and then output the created payment channel’s address.
Some blocking has been removed from lotus, so that now this command will return as soon as the message has been sent to chain, so the channel will not have been created and it will return "<empty>".
This PR causes the command to block until the channel is created / funds are available, then return the channel address.
An alternative solution we may want to explore would be:
- `paych get` returns immediately with the message CID of the “create channel” or "add funds" message
- there is an additional command to wait until the funds are available
Note: We now have a `PaychGetWaitReady` method on the API but it’s not exposed …

Fix CLI cmd: paych get

---

chain/sync.go
chain/types/blockheader.go

Without this, we can wind up requesting blocks from peers that we already have (and potentially failing to sync a valid block if that fails for some reason)

Fix collectHeaders when incoming is partially built on latest tipset

---

api/api_storage.go
api/apistruct/struct.go
api/test/deals.go
markets/retrievaladapter/provider.go
node/impl/storminer.go
node/node_test.go

For the moment, just replicate #2872 in test.
- Build an api for Getting Updates on a deal in the miner
- Build a test that tries retrieval at the immediate moment it becomes possible: when the test is written to the deal store
- Fix the issue by just adding a nil check -- if commD == nil, pass cid.Undef to ReadPiece. It is only used if there is no unsealed copy of the sector

Fix unseal bug, reproduce in test

---

chain/messagepool/selection.go

We need to add to the previous `last` value, as we are iterating over a sub-slice:
```
for i, chain := range chains[last:]
```
Without this we trim the same thing in an infinite loop

mpool: Fix SelectMessages hanging

---

api/api_full.go
api/apistruct/struct.go
api/test/mining.go
miner/miner.go
node/impl/full.go
node/impl/full/beacon.go

Still need to write some tests for this, but I think it does the trick, and should result in noticeably higher chain quality after a drand outage.

recheck best known tipset after waiting for random beacon entry

---

chain/messagepool/selection.go

1. We break the message accumulation the first time we see a chain with gasPerf <= 0
as it is not profitable to include them in the block
2. When trimming, we remove also trim negative performing messages to make the trimmed
chain profitable.

some small improvements in the handling of non-performing chains

---

chain/sync.go
storage/miner.go

Should be sufficient to log these once prominently at start up, as opposed to on every epoch.
cc @nonsense

rationalise annoying logs

---

Makefile
cmd/lotus-pcr/main.go

Lotus PCR will attempt to reimbursement the initial pledge collateral of the PreCommitSector miner actor method for all miners on the network.
I haven't actually tested this completely. I did a bit of testing on the calibration network, but with the new gas stuff it's not the easier to switch between networks.

add lotus-pcr command tool

---

cli/client.go

When I exec `lotus client list-deals`, I got the result: `ERROR: deal 6417 not found`, which made me unable to check my other deal.

show deal list when StateMarketStorageDeal not found deal

---

cmd/lotus-pcr/main.go

I've changed the target address of the message to the 'From' as it seems like the software may be sending pledge collateral from the worker address even if the miner as available balance. It was a bit hard to verify with small 512MiB sectors, but this seems like the safest way to do this.

lotus-pcr: initialize bigint; send refund to worker

---

paychmgr/paychget_test.go
paychmgr/simple.go
paychmgr/store.go

Fixes https://github.com/filecoin-project/lotus/issues/2912
The tricky part here is that `getPaych(ctx context.Context, from, to address.Address, amt types.BigInt)` takes a context as a parameter.
- The amount for the merged requests is the sum of the amount for each individual request
- When we merge requests, we need to monitor the context for each request in the merge
- If a request context is cancelled we remove the request amount from the total
- If all the contexts in a merge are cancelled, we cancel the merge context

Payment channels manager: merge queued add funds

---

api/api_full.go
chain/stmgr/stmgr.go
chain/types/message.go
chain/types/message_test.go
markets/storageadapter/client.go
node/impl/full/state.go

Without this doing `mpool replace` will cause mayhem in most places which care about messages executing (sealing, markets, window post sched, etc..)

stmgr: Allow replacing gas values in WaitMsg

---

api/api_full.go
api/apistruct/struct.go
api/cbor_gen.go
api/test/paych.go
cli/paych.go
gen/main.go
node/impl/paych/paych.go

Fixes point 4 of https://github.com/filecoin-project/lotus/issues/2911
Change the return value from `PaychGet` to be a special "wait sentinel" type instead of a message cid.
Motivation: We don't want API clients to call `StateWaitMsg()` on the value returned from `PaychGet()`. We want them to call `PaychGetWaitReady()` with the wait sentinel.

Paych manager: use special type for wait sentinel

---

paychmgr/manager.go
paychmgr/mock_test.go
paychmgr/paych.go
paychmgr/paych_test.go
paychmgr/paychget_test.go
paychmgr/settle_test.go
paychmgr/simple.go
paychmgr/state.go

Fixes point 2 of https://github.com/filecoin-project/lotus/issues/2911
There are no logic changes, just unifying the payment channel manager apis to make it easier to mock

Refactor paych mgr apis for easier mocking

---

chain/gen/gen.go
chain/stmgr/call.go
chain/stmgr/stmgr.go
chain/store/store.go
chain/sync_test.go
chain/validation/applier.go

**Second commit probably needs careful review.**
The buggy case is illustrated by the test added in this PR:
```
Consider a tipset with 2 blocks, A and B, with A having the better ticket.
A and B both include _different_ messages from sender X with nonce N (where N is the correct nonce for X).
Only the message in block A should be included in `MessagesForTipset`, and only that message should ever make it to the VM for execution.
```

MessagesForTipset should filter out bad nonce messages

---

chain/messagepool/messagepool.go
chain/messagepool/provider.go
chain/messagepool/repub.go

Republishes performant chains instead of blindly picking the first 5 messages.
Also does a small refactor to move the provider api out of the main messagepool file.

Update messagepool republish logic

---

api/api_full.go
api/apistruct/struct.go
api/test/deals.go
cli/client.go
markets/loggers/loggers.go
node/impl/client/client.go

Output retrieval events and status, bytes transferred, and funds spent when using the `client retrieve` command:
```
./lotus client retrieve bafk2bzacedcvkbqyzsbpth5eaf6crdumudwbyzwoawgsvdt74qfwzvobb3dca ./test.out
Retrieval Event: ClientEventOpen, State: DealStatusNew, BytesReceived: 0, PaymentSent: 0
Retrieval Event: ClientEventDealProposed, State: DealStatusWaitForAcceptance, BytesReceived: 0, PaymentSent: 0
Retrieval Event: ClientEventDealAccepted, State: DealStatusAccepted, BytesReceived: 0, PaymentSent: 0
Retrieval Event: ClientEventPaymentChannelAddingFunds, State: DealStatusPaymentChannelAddingFunds, BytesReceived: 0, PaymentSent: 0
Retrieval Event: ClientEventPaymentChannelReady, State: DealStatusOngoing, BytesReceived: 0, PaymentSent: 0
...
```

Generate more useful output during client retrieval

---

api/api_full.go
api/apistruct/struct.go
cli/client.go
node/impl/client/client.go

At present, and at least for the medium term (even with the transition to NSE) the structure of a piece (and thus commP) will remain identical for every size of sector.
The offline deal flow would benefit greatly if the `lotus client commP` interface is able to calculate commP without having access to a fully synced chain, or without even being online.
This is particularly important for filecoin-discover, as we want to allow miners to spot-check their purchased HDDs, way before they need to accept the mainnet deal proposals.
See [comment/links in node/impl/client/client.go](https://github.com/filecoin-project/lotus/compare/next...feat/offline_commp_calculation?expand=1#diff-9a3e728363a090aba64a476fe19672b5) for details on code flow

Stop requiring miner address / sector size for `lotus client commP`

---

chain/gen/genesis/genesis.go
chain/gen/genesis/miners.go
chain/stmgr/call.go
chain/stmgr/stmgr.go
chain/stmgr/utils.go
chain/validation/applier.go
chain/vm/runtime.go
chain/vm/vm.go
node/impl/full/state.go

TotalCircSupply is still calculated as `filVested + filMined - filBurnt - filLocked`, but these values are now obtained as follows:
- `filVested = multisigVested + accountVested + genesisLocked`, where `multisigVested` is the total vested funds of the genesis multisigs at a given epoch, `accountVested` is the sum over all **account** actors in the genesis state of `max(currBalance - genesisBalance, 0)`, and `genesisLocked` is the locked funds in the power and market actor at genesis.
- `filMined` is now obtained from the Reward Actor state (https://github.com/filecoin-project/lotus/pull/2605#discussion_r461976438).
- `filBurnt` is (still) just the balance of the Burnt Funds actor. We may want to change it to be the Burnt Funds currBalance - genesisBalance if there's a possibility that …

Revise TotalCircSupply

---

markets/storageadapter/provider.go

Add a check for `nil` tipsets in the storage provider adapter.  
Didn't fix the root issue (maybe a race?) as to why we are getting nils back from the `tipSetCache.best()`.
Resolves #2865

Add nil check in tipset change handler

---

go.mod
go.sum

Latest markets release for new calib-net reset
Only update since last merge is update to data transfer + graphsync (I believe spec actors update already merged)

Update markets v0.5.5

---

chain/events/state/diff_adt.go
chain/events/state/diff_adt_test.go
chain/events/state/predicates.go
cmd/lotus-chainwatch/processor/common_actors.go

This PR prevents writes to the id_address_map from conflicting by first updating the values of keys that have changed.

fix: id_address_map conflicts

---

extern/sector-storage/sched_watch.go

Occasionally when one worker drops, and at the same time another one joins, things can deadlock betweed the worker watcher goroutine and the main sealing scheduler goroutine. This should fix that
Fixes https://github.com/filecoin-project/lotus/issues/3001

sealing sched: Fix deadlock in worker watcher

---

node/impl/full/mpool.go

Reported by @marco-storswift
```
2020-08-13T19:24:08.016+0800    WARN    fullnode        full/mpool.go:196       Push from ID address (t0100), adjusting to t3wahho43llicamxbktabat6c36ekfhqwqfvqzywjatida7b5xdopwqg7kchbqj75lrea73fgxac3gpkjgmj3q
2020-08-13T19:24:08.019+0800    WARN    rpc     go-jsonrpc@v0.1.1-0.20200602181149-522144ab4e24/handler.go:226  error in RPC call to 'Filecoin.MpoolPushMessage': message will not be included in a block:
github.com/filecoin-project/lotus/chain/messagepool.(*MessagePool).verifyMsgBeforePush
/mnt/lotus/interopnet/chain/messagepool/messagepool.go:252
- 'GasFeeCap' less than 'GasPremium':
github.com/filecoin-project/lotus/chain/types.(*Message).ValidForBlockInclusion
/mnt/lotus/interopnet/chain/types/message.go:174
2020-08-13T19:24:10.044+0800
```

mpool: Fix capGasFee math again

---

chain/messagepool/block_proba.go
chain/messagepool/selection.go
chain/messagepool/selection_test.go

After discussing with kuba, we realized that we can further improve optimal selection, albeit at the cost of somewhat increasing the merge complexity.
This pr incorporates our magic sauce:
- mixin the previous chain effective performance so that we account for merging the dependencies.
- update the effective performance of subsequent chains when merging.
- resort after merging.
The result is a solid improvement:
- Without the magic sauce:
- Average Capacity Boost: 3.450251
- Average Reward Boost: 2.972417
- With the magic sauce:
- Average Capacity Boost: 4.023706
- Average Reward Boost: 3.327822
The cost is an increase in merge complexity from `O(nlogn)` to `O(n^2)`, where n is the number of chains.
However, we are operating with bounded number of messages and hence number of chains, so …

Further improvements for optimal message selection

---

paychmgr/paych_test.go
paychmgr/state.go

Fixes a bug introduced by https://github.com/filecoin-project/lotus/pull/2991:
- client calls `PaychVoucherAdd()` with an existing channel that has one voucher on lane 1
- client calls `AllocateLane()`: allocates lane 0
- client calls `AllocateLane()`: allocates lane 1 (clashing with existing lane 1)
https://github.com/filecoin-project/lotus/pull/2991 attempts to fix "holes" in lane allocation, eg if a client adds a voucher for lane 1 (leaving a hole for lane 0), it would allocate the next lane to be 0, then 2, then 3, then 4 etc.
In practice I don't think we need to worry about that because the client can just use the AllocateLane() function which should not cause any holes. If they decide to use some other scheme that creates holes, they can use their scheme to keep track of where the …

Fix bug with paych allocate lane

---

cmd/lotus-chainwatch/processor/common_actors.go

Have tried fixing this many times but have been unable to reproduce the issues locally. In the event that chainwatch is unable to to update the id_address_map it will now log an error and continue processing. This is done to keep dashboard progressing and means the id_address_map table may contain information that is incorrect due to reporgs.

fix: chainwatch id_address_map

---

cmd/lotus-chainwatch/processor/miner.go

Prevents chainwatch from hitting
```
{"level":"fatal","ts":"2020-08-13T20:48:13.185Z","logger":"processor","caller":"processor/miner.go:193","msg":"Failed to persist miner actors","error":"(get ssize) failed to load miner actor state: get
actor: actor not found"}
```

fix: chainwatch actor not found handling

---

go.mod
go.sum
node/builder.go
node/modules/client.go
node/modules/storageminer.go

Just includes previously merged fix for provider collateral, and also includes fix to avoid race condition in request validation
- one nice change here is a bunch of deleted code that moved into markets, cause it's much easier for it to live there. (just setting up and registering validators)

Update markets 0.5.6

---

cmd/lotus-chainwatch/processor/mpool.go

move sleep into the select, as it is it simply slows down the writer if there are many messages.

fix a small issue in chain watch

---

extern/storage-sealing/checks.go

Errors like
```
2020-08-16T03:09:43.178+0200	[31mERROR[0m	sectors	storage-fsm/fsm.go:26	unhandled sector error (5237): checkCommit sanity check error (*xerrors.wrapError):
github.com/filecoin-project/storage-fsm.(*Sealing).handleCommitFailed
/home/magik6k/github.com/filecoin-project/go-lotus/extern/storage-fsm/states_failed.go:190
- verify seal:
github.com/filecoin-project/storage-fsm.(*Sealing).checkCommit
/home/magik6k/github.com/filecoin-project/go-lotus/extern/storage-fsm/checks.go:158
- failed to fill whole buffer
github.com/filecoin-project/filecoin-ffi.VerifySeal
/home/magik6k/github.com/filecoin-project/go-lotus/extern/filecoin-ffi/proofs.go:52
github.com/filecoin-project/sector-storage/ffiwrapper.proofVerifier.VerifySeal …
```

fsm: Recover from errors from VerifySeal in checkCommit

---

cmd/lotus-chainwatch/processor/common_actors.go
cmd/lotus-chainwatch/processor/processor.go

A few fixes:
- temp table names were colliding and making a mess when running in parallel
- block missing from lookup shouldn't kill the whole group of metrics...let's ignore and come back later
- Attempt to capture actore names (again)

More Chainwatch Improvements

---

chain/gen/gen.go
chain/gen/genesis/genblock.go
chain/gen/genesis/genesis.go
chain/stmgr/stmgr.go
chain/store/store.go
cmd/lotus-chainwatch/syncer/sync.go
node/impl/full/gas.go

This PR adds a link to the original filecoin genesis block from the network launch block. 
The hash of this block was timestamped in [ethereum back in 2017](https://etherscan.io/tx/0xe8f51c9eefb682cd866f059462577b6dd3d2685ff4b6437f6c940ff4f4aaf067) and represents the initial state of the network.

proper genesis block history

---

chain/gen/genesis/miners.go
go.mod
go.sum

Update to specs-actors v0.9.3

---

api/types.go
cli/client.go
cmd/lotus-chainwatch/processor/miner.go
markets/storageadapter/client.go
node/impl/client/client.go

This attempts to fix reports of `2020-08-17T19:36:51.965+0200    FATAL   processor       processor/miner.go:193  Failed to persist miner actors  {"error": "RPC client error: unmarshaling result: failed to parse peer ID: cid too short"}` on Calibration net.
Unsure if this fix works until my node syncs again...
Detail of issue running `chainwatch@2570712a`:
```
2020-08-18T17:54:08.387Z        INFO    chainwatch      lotus-chainwatch/main.go:17     Starting chainwatch v0.4.6+git.9d79e619.dirty
2020-08-18T17:54:08.389Z        INFO    chainwatch      lotus-chainwatch/run.go:54      Remote version: 0.4.5+git.700bcedb.dirty
2020-08-18T17:54:09.811Z        INFO    processor       processor/processor.go:361      Gathered Blocks to Process      {"start": "1550", "end": "1587"} …
```

fix(api): Filter malformed peer ID before RPC marshaling

---

node/modules/lp2p/pubsub.go

The drad topic first message delivery cap is way too high; if we account for decay and take the geometric limit with 2 beacons/min, we get a limit of about 26.
This fixes the cap to be 25.
Thanks to @AgeManning and @blacktemplar  for pointing this out.

fix drand topic first message delivery cap

---

api/api_full.go
api/apistruct/struct.go
api/types.go
cli/client.go
go.mod
go.sum
node/impl/client/client.go

This started as helping me understand what was happening with data transfers... and turned into something that I think will be super useful for all.
It adds `lotus client list-transfers` along with `lotus client list-transfers --watch` which allows you to watch data transfers in real time.
This is a screen shot as about 6 128MB pieces are sent over the wire...
In addition to the CLI, there are two new APIs:
- ClientListDataTransfers which gets the current list of transfers
- ClientDataTransferUpdates which returns a channel of updates to data transfers
- also defines a data type api.DataTransferChannel which collects the most relevant information from the overall data transfer channel state and outputs to the channel
- voucher output will improve with a future update to go-fil-markets so …

Find out what's up with data transfers!

---

cmd/lotus-shed/jwt.go
cmd/lotus-shed/keyinfo.go
cmd/lotus-shed/main.go
node/modules/core.go

This is required for deployments to provide jwt tokens to external services. Includes minimal changes to lotus itself.

lotus-shed: add simple jwt creation support

---

chain/sub/incoming.go

we seem to have a problem with this leading to many rejected messages and negative scores for
potentially innocent peers who are republishing their messages.

ignore, don't reject messages with nonce that is too low

---

cmd/lotus-pcr/main.go

The math on this was wrong, and it was giving out 3433% instead of 103%

lotus-pcr: fix refund math

---

api/api_storage.go
api/apistruct/struct.go
api/types.go
cli/client.go
cmd/lotus-storage-miner/main.go
cmd/lotus-storage-miner/market.go
node/impl/client/client.go
node/impl/storminer.go

This is just a companion PR to https://github.com/filecoin-project/lotus/pull/3162 -- adds the equivalent command to the miner
- Add API functions to miner
- Extract common utility function to construct api.DataTransferChannel
- Use common output function for list of data transfers (may need to revise sorting later)
- Add cli command to storage miner as `lotus-miner data-transfer list`

Add data transfer list command to miner

---

cmd/lotus-chainwatch/processor/reward.go

I'd be curious to know how this is even possible, though I'm too tired to investigate tonight. This allows chainwatch to proceed instead of panicking like so:
```
Aug 20 05:19:09 sentinel-calibration chainwatch[1219]: github.com/filecoin-project/lotus/cmd/lotus-chainwatch/processor.(*Processor).storeRewardSmoothingEstimates(0xc000500980, 0xc001644000, 0x1cd, 0x266, 0x4312960, 0x0)
Aug 20 05:19:09 sentinel-calibration chainwatch[1219]:         /home/ubuntu/sentinel/lotus/cmd/lotus-chainwatch/processor/reward.go:285 +0x39b
Aug 20 05:19:09 sentinel-calibration chainwatch[1219]: github.com/filecoin-project/lotus/cmd/lotus-chainwatch/processor.(*Processor).persistRewardActors.func4(0xc0013cdd70, 0x221a628)
Aug 20 05:19:09 sentinel-calibration chainwatch[1219]: …
```

fix(chainwatch): Handle RewardState.EpochSmoothingEstimate == nil

---

go.mod
go.sum
node/modules/lp2p/pubsub.go

Adds a threshold for behaviour penalty application, and increases the gossip followup time and history length.
Rationale: It has been observed that overloaded lotus nodes sometimes fail to follow up to IWANT requests, which results in behavioural penalties and negative scores.
This sets a small threshold of 3 misbehaviours before applying the penalty so that we don't trip over this all the time.
It also increases the gossip follow up time to 5s and the gossip history length to 10 heartbeats (10s) to better support lotus nodes who are slow to respond.
Support for the threshold was just added in pubsub master in https://github.com/libp2p/go-libp2p-pubsub/pull/377

Address issues with pubsub behavioural penalties

---

go.mod
go.sum
node/modules/lp2p/pubsub.go

Bug fix in https://github.com/libp2p/go-libp2p-pubsub/pull/378, observed in my node.
The bump is for empirical observations in my node behaviourally penalized nodes rarely exceed 6.

update pubsub and bump behaviour penalty threshold to 6

---

node/config/def.go

Seems we lost control of the tracer's EIP; this fixes it to use dns instead.

Emergency fix: use DNS addr for tracer

---

extern/sector-storage/sched.go
extern/sector-storage/sched_test.go

This doesn't make it any less O(n^2), just runs the slow part in parallel, so it's acceptably fast at more scales
Before:
```
BenchmarkTrySched/200w-400q-32         	       1	21105421605 ns/op (21s)
```
After:
```
BenchmarkTrySched/200w-400q-32         	       9	 130080438 ns/op (130ms)
```

sectorstorage: Make trySched less very slow

---

cmd/lotus-chainwatch/processor/processor.go
cmd/lotus-chainwatch/run.go
go.sum

Chainwatch processor works in batches, collecting the deltas for each batch and shipping them off to sub-processing handlers which work through persisting the deltas to the DB. When any part of sub-processing fails, the `errgroup` cancels the whole batch. Instead, let's make each sub-process handler persist best-effort since they don't have schema dependencies between one another and log the failure. This should allow us to capture much more of our data despite internal state inconsistencies arising and making the whole thing bail.
Also, reduce the batch size. Smaller batches means a less efficient catchup when chainwatch lags, but the trade off is smaller gaps in data on failures.

fix(chainwatch): Make processor failures independent of each other

---

cli/paych.go
cli/paych_test.go
node/impl/full/gas.go
paychmgr/settler/settler.go
paychmgr/util.go

Depends on https://github.com/filecoin-project/lotus/pull/3043
Currently `lotus paych voucher best-spendable` only outputs a single voucher.
This PR modifies the command to output the best voucher in each lane, and also makes the output consistent with
`lotus paych voucher list`

paych: modify `lotus paych voucher best-spendable` to output _all_ best vouchers

---

paychmgr/manager.go
paychmgr/paych_test.go

Depends on https://github.com/filecoin-project/lotus/pull/3111
Currently payment channel check voucher fails if the channel does not already exist in the store.
With this PR check voucher will get the channel from state if it does not already exist and is inbound (the wallet has the channel To address)

Payment channel check voucher should get inbound channel from state

---

chain/messagepool/messagepool.go
chain/messagepool/messagepool_test.go
chain/messagepool/repub_test.go
chain/messagepool/selection_test.go

Tests to cover some of the red spots in the coverage, and lo and behold some bugs...
Bug fixes:
- the debug code with futureDebug was broken; it was deadlocking.
- the output channel was not closed when exiting the update sub goroutine.
- the sub goroutine didn't respect the closer.
- [IMPORTANT] the new `runHeadChange`, called from selection, was modifying the mpool's current ts.

More message pool tests and a couple of bug fixes

---

cli/client.go

There were certain instances of OOB errors when truncating strings in CLI output.
Add an `ellipsis(string, int)` func which checks bounds.

Use a safe string ellipsis/truncation function for client CLI output

---

cli/mpool.go
cmd/lotus-fountain/main.go

This way we can keep CI green. Otherwise, nobody looks at CI and bugs slip through.
(can we make these mandatory?)

Fix more lint warnings.

---

cli/cmd.go
cli/pprof.go
cmd/lotus-storage-miner/run.go
cmd/lotus/rpc.go
go.mod
go.sum
tools/stats/rpc.go

* updates bitswap to include _many_ perf enhancements and bug fixes.
* updates go-fs-lock because the version here is pretty old.
* updates go-libp2p
* updates bbloom _just_ in case, because the version we were depending on had bugs (looks like we're not actually using it).

update deps for bug fixes

---

.circleci/config.yml

Adds a `vectors-branch` param to the `test-conformance` job that allows it to be used multiple times in the CI workflow, once using the commit specified in the git submodule and again using the master branch of [test-vectors](https://github.com/filecoin-project/test-vectors).

feat: bleeding edge conformance

---

api/test/util.go
api/test/window_post.go
extern/sector-storage/mock/mock.go
storage/wdpost_run.go

"skipped" sectors must be replaced with a substitute "good" sector, or the entire partition must be skipped. They should not just be omitted.
This patch also fixes the test to verify the _entire_ proof instead of just verifying that the proof includes the correct sectors.

Fix PoSt with bad sectors

---

node/impl/client/client.go

Prevent lotus from ever sending event over closed channel in ClientRetrieve
This fix attempts to follow a basic principle of closing channels -- never write to a channel that your closing outside the go-routine you close it in.
Instead of writing directly to the events channel inside the data transfer subscribe -- which is where we were causing the issue, write to an intermediate channel that is never closed. Read from the intermediate channel in the same routine that closes the events channel and write to the main events channel there. The close always happens at the very end of that routine, after we've done all the reads we need to.

Resolve retrieval close event panic

---

.circleci/config.yml

When generating the custom html coverage report, #3176 removed the output that would show up in the test report tab. this should add it back.

add back junit report in conformance ci

---

cli/log.go

previously, we would always be setting the log levels on the lotus daemon, even when running `lotus-miner log set-level` because we were pulling up the api handler for the daemon. This changes it to pull up the right api info for the binary we're running

use node type agnostic api getter in log commands

---

api/test/blockminer.go
api/test/deals.go
api/test/mining.go
api/test/util.go
api/test/window_post.go
go.sum
miner/miner.go
miner/testminer.go
node/test/builder.go

This was fun to track down, but the main issue here is that the callback gets called before the block is even submitted, so we had a race condition between the callback getting called, and us hoping that we would see the block in ChainNotify/ChainHead.
We switch to now having the callback tell us what the epoch of the block it created is, and then waiting until we see that epoch in ChainHead (admittedly, maybe theres a better signal to wait on, but this works well enough)

Wait until blocks show up full nodes 'head' before claiming block has been mined

---

node/modules/lp2p/pubsub.go

- increase Bootstapp prune backoff to 5min from the default 1min to reduce PX load
- reduce opportunistic graft threshold to 3.5 to account for low peer scores observed in the live network

tweak some pubsub parameters

---

conformance/runner_test.go

Might as well check this too so nothing breaks it :) (let me know if you want the bytes in the error message formatted differently)

Add in return value check in test-vector runner

---

cmd/lotus-chainwatch/processor/power.go
cmd/lotus-chainwatch/processor/reward.go
cmd/lotus-chainwatch/scheduler/refresh_top_miners_by_base_reward.go
cmd/lotus-chainwatch/syncer/sync.go

Merge https://github.com/filecoin-project/lotus/pull/3275, this then PR.
Add full Power state metrics
```go
+       totalRawBytes                      big.Int
+       totalRawBytesCommitted             big.Int
+       totalQualityAdjustedBytes          big.Int
+       totalQualityAdjustedBytesCommitted big.Int
+       totalPledgeCollateral              big.Int
+       newRawBytes             big.Int
+       newQualityAdjustedBytes big.Int
+       newPledgeCollateral     big.Int
+       newQAPowerSmoothed      *smoothing.FilterEstimate
+       minerCount                  int64
+       minerCountAboveMinimumPower int64
```
add full Reward state metrics
```go
+       cumSumBaselinePower big.Int
+       cumSumRealizedPower big.Int
+       effectiveNetworkTime   int64
+ …
```

feat(chainwatch): Add more complete power and reward metrics

---

cmd/lotus-chainwatch/processor/market.go
cmd/lotus-chainwatch/processor/messages.go
cmd/lotus-chainwatch/processor/miner.go
cmd/lotus-chainwatch/processor/mpool.go
cmd/lotus-chainwatch/processor/power.go
cmd/lotus-chainwatch/processor/processor.go
cmd/lotus-chainwatch/processor/reward.go
cmd/lotus-chainwatch/run.go
cmd/lotus-chainwatch/scheduler/refresh_top_miners_by_base_reward.go
cmd/lotus-chainwatch/scheduler/scheduler.go
cmd/lotus-chainwatch/syncer/sync.go

We were detecting syncing problems with chainwatch which ended up being caused by race condition. This resolves the race condition and improve the sync alogrithm so last synced block is more determistically determined by height rather than by time.

fix(chainwatch): use height to determine unsynced blocks and fix deadlock in sector deal table

---

extern/storage-sealing/sealing.go

I once encountered StartPacking twice, causing the state machine to stop in error. And SectorAddPiece and SectorStartPacking are triggered simultaneously, causing the state machine to receive two events.This change should solve both of these problems.
planner for state Packing only has a plan for a single event only, got [{User:{NewPiece:{Piece:{Size:134217728 PieceCID:baga6ea4seaqc2k4bizwrswlo3l6wefxfu2ddktxnmzjv5vdpmx7qjhhgemagyfy} DealInfo:0xc0384a7740}}} {User:{FillerPieces:[{Size:268435456 PieceCID:baga6ea4seaqk2bufhfu5g7ju74eobh2wsmfevum2rhppmdf75z7b2m4byhtryny} {Size:536870912 PieceCID:baga6ea4seaqdsvqopmj2soyhujb72jza76t4wpq5fzifvm3ctz47iyytkewnubq} {Size:1073741824 PieceCID:baga6ea4seaqmzq6acl23axubdiv37xipnaz3qqtvwr57ekoaauviescphqnfwpi} {Size:2147483648 …

ignore resend SectorStartPacking event. and fix StartPacking's unsealedInfoMap lock

---

chain/messagepool/messagepool.go
chain/messagepool/messagepool_test.go
chain/messagepool/selection_test.go
chain/sub/incoming.go
node/modules/lp2p/pubsub.go

This adds tracking of required funds for pending messages so that we can stop spam attacks.
This also allows us to finally enable some score contribution from the messages topic.

Message Pool Rudimentary Spam Protection Measures

---

cmd/lotus/daemon.go

The stmgr calls GetGenesis to setup genesis multisigs, which needs to be explicitly set using SetGenesis. This wasn't happening during imports.
Very similar to #2805

Fix chain import

---

api/api_worker.go
api/apistruct/struct.go
cli/cmd.go
cmd/lotus-seal-worker/info.go
cmd/lotus-seal-worker/main.go
cmd/lotus-seal-worker/rpc.go
cmd/lotus-seal-worker/storage.go

(Works on my setup)
Closes #2129

worker: Cli to attach storage paths

---

extern/sector-storage/sched.go
extern/sector-storage/sched_resources.go
extern/sector-storage/selector_alloc.go
extern/sector-storage/selector_existing.go
extern/sector-storage/selector_task.go

More can still be done here, but that will likely be a bit bigger refactor of the scheduling logic
This makes things a fair bit better when tasks are scheduled one-by-one (so most of the time on small-medium setups)
Merge after https://github.com/filecoin-project/lotus/pull/3424

Improve worker selection a bit

---

chain/messagepool/repub.go
chain/messagepool/selection.go
documentation/en/mpool.md

as discussed on slack, this turns out to be problematic as miners fill their blocks with penalty inducing chains when the base fee gets high.

Tweak priority selection to not select negative perfoming chains

---

conformance/driver.go
conformance/runner_test.go
go.mod
go.sum

This PR adds the driver for tipset-class test vectors, which target `StateManager#ApplyBlocks`.
This vector class sits between message-class vectors and blockseq-class vectors. Amongst other things, it enables us to test:
* miner reward attribution
* global reward policy regulation
* cron ticking
* message deduplication within a tipset
* null rounds
There's currently one suite, with a [single test vector](https://github.com/filecoin-project/test-vectors/blob/master/corpus/reward/reward--ok-miners-awarded-no-premiums.json). Here's the [generation script](https://github.com/filecoin-project/test-vectors/blob/master/gen/suites/reward/miner.go). This vector verifies that the reward schedule is applied correctly, by incrementing the balances of the miners, and decreasing the system treasury. …

conformance: add driver for tipset-class vectors.

---

conformance/driver.go
conformance/runner_test.go
go.mod
go.sum

Reverts filecoin-project/lotus#3449
Latest test-vectors import non-existent lotus revision, which breaks all builds - https://github.com/filecoin-project/test-vectors/blob/master/go.mod#L9
```
go build -ldflags="-X=github.com/filecoin-project/lotus/build.CurrentCommit=+git.dd228c3a" -o lotus ./cmd/lotus
go: github.com/filecoin-project/test-vectors@v0.0.0-20200901185932-907892394dd8 requires
github.com/filecoin-project/lotus@v0.5.8-0.20200901153315-fa4000663a61: invalid version: unknown revision fa4000663a61
make: *** [Makefile:68: lotus] Error 1
```

Revert "conformance: add driver for tipset-class vectors."

---

chain/stmgr/call.go
chain/stmgr/stmgr.go
chain/stmgr/utils.go
chain/store/store.go

Assume this was planned to be used before, but this won't be used now (right?)

Remove height from chain rand

---

conformance/driver.go
conformance/runner_test.go
go.mod
go.sum

Follow-up of #3449. Merge with merge, no squashing or rebasing. test-vectors references commit 0962292, which is part of this branch.
Fixes https://github.com/filecoin-project/lotus/pull/3483.

tipset-class test vector driver (take 2)

---

api/api_full.go
api/apistruct/struct.go
chain/store/store.go
chain/store/store_test.go
chain/store/weight.go
cli/chain.go
cmd/lotus/daemon.go
documentation/en/api-methods.md
node/impl/full/chain.go

Gets us closer to being able to 'sync' faster.

allow exporting a number of recent chain state trees

---

extern/sector-storage/sched.go

The deadlock could happen between `sh.workersLk.RLock()` in runWorker (sched.go:L577) (which holds `worker.wndLk` at the time), and `trySched` in the main scheduler goroutine, which indirectly tries to acquire `worker.wndLk` through task selector while holding `sh.workersLk.RLock()`
Normally this doesn't manifest because how could you possibly deadlock when acquiring an RLock from 2 goroutines
Well
Throw in a 3rd goroutine and write-preferred RWlocks to the mix and you get the deadlock
main trySched goroutine:
```
goroutine 213 [semacquire, 245 minutes]:
sync.runtime_Semacquire(0xc01533f888)
/usr/local/go/src/runtime/sema.go:56 +0x42
sync.(*WaitGroup).Wait(0xc01533f880)
/usr/local/go/src/sync/waitgroup.go:130 +0x64
github.com/filecoin-project/lotus/extern/sector-storage.(*scheduler).trySch …
```

sealing sched: Fix deadlock between worker.wndLk / workersLk

---

extern/sector-storage/ffiwrapper/sealer_cgo.go

Closes https://github.com/filecoin-project/lotus/pull/3447

ffiwrapper: Fix ReadPiece panic

---

go.mod
go.sum

Contains some minor fixes including fixing a bug with retrievals failing when the last payment interval lands exactly at the end of the data.

Upgrade markets to v0.5.9

---

.codecov.yml

This seems to be a new, enabled by default feature of codecov, where it annotates all uncovered lines by default, which in the world of Go makes file views unusable
Exhibit A - https://github.com/filecoin-project/lotus/pull/3497/files#diff-8a8fba801c71449b9064ff7c4592a012
This PR should disable those

Disable codecov annotations

---

chain/messagepool/messagepool.go
chain/messagepool/messagepool_test.go
chain/messagepool/pruning.go
chain/messagepool/repub.go
chain/messagepool/repub_test.go
chain/messagepool/selection_test.go
chain/sub/incoming.go

All in the name of Spam Protection; implements the countermeasures we have discussed.

track expected nonce in mpool, ignore messages with large nonce gaps

---

conformance/driver.go

The puppet actor has been subsumed into the chaos actor and test-vector tests no longer use it.
Depends on:
refs https://github.com/filecoin-project/test-vectors/issues/101

refactor: remove puppet actor from conformance tests

---

api/api_full.go
api/apistruct/struct.go
api/test/paych.go
cli/paych.go
cli/paych_test.go
markets/retrievaladapter/client.go
node/impl/paych/paych.go
paychmgr/accessorcache.go
paychmgr/manager.go
paychmgr/mock_test.go
paychmgr/paych.go
paychmgr/paych_test.go
paychmgr/paychget_test.go
paychmgr/simple.go
paychmgr/store.go

Adds an API method to query the status of a channel by from / to
```go
PaychAvailableFunds(from, to address.Address) (*ChannelAvailableFunds, error)
```
```go
type ChannelAvailableFunds struct {
Channel *address.Address
// ConfirmedAmt is the amount of funds that have been confirmed on-chain
// for the channel
ConfirmedAmt types.BigInt
// PendingAmt is the amount of funds that are pending confirmation on-chain
PendingAmt types.BigInt
// PendingWaitSentinel can be used with PaychGetWaitReady to wait for
// confirmation of pending funds
PendingWaitSentinel *cid.Cid
// QueuedAmt is the amount that is queued up behind a pending request
QueuedAmt types.BigInt
// VoucherRedeemedAmt is the amount that is redeemed by vouchers on-chain
// and in the local datastore
VoucherReedeemedAmt types.BigInt …
```

paych: Add PaychAvailableFunds API method

---

cmd/lotus-chainwatch/processor/messages.go
cmd/lotus-chainwatch/processor/processor.go

Fixes https://github.com/filecoin-project/sentinel/issues/70

Stop SyncIncomingBlocks from leaking into chainwatch processing; No panics during processing

---

api/api_storage.go
api/apistruct/struct.go
api/test/deals.go
cmd/lotus-storage-miner/market.go
node/impl/storminer.go

Add an option to continuously monitor miner storage deals from the CLI.
- Add `--watch` option to `lotus-miner storage-deals list`
- `MarketGetDealUpdates` doesn't take a proposal cid any more, it returns updates for all deals
Resolves #2954

Add watch option to storage-deals list

---

conformance/driver.go
go.mod
go.sum

* Tipset-class vectors: support sending from actor addresses. This is necessary for some test cases in https://github.com/filecoin-project/test-vectors/pull/108, [that were migrated from chain-validation](https://github.com/filecoin-project/chain-validation/blob/master/suites/tipset/rewards_penalties.go#L133). We test that these sends are disallowed.
* Sign secp256k1 messages with dummy signatures.
* Deprecate the puppet actor, which has now folded (partially) into the chaos actor. The chaos actor now occupies address t98.
⚠️  Merge with merge; do not squash or rebase!

conformance: various changes

---

cli/paych.go
cli/paych_test.go

`lotus paych status`
Sample output:
```
Channel does not exist
From: t3ut43tdij45auivo7m444y3atatarsfcpslpdcxgi2avymrdiz3hmzsgwhvw2ntb74bhsn5maz4caaxtkhfeq
To:   t1rji2fhc4f5ztuv6liw22epiuy265o4zphgzapry
```
```
Creating channel
From:          t3ut43tdij45auivo7m444y3atatarsfcpslpdcxgi2avymrdiz3hmzsgwhvw2ntb74bhsn5maz4caaxtkhfeq
To:            t1rji2fhc4f5ztuv6liw22epiuy265o4zphgzapry
Pending Amt:   100000000000000000000
Wait Sentinel: bafy2bzacedyw4tc3ohiavgpmicupxevhjeft6n2vtwhyu6x7y62a7kmh55adk
```
```
Channel exists
Channel:              t2557fcwehqjkrt5lggur6ppyr3xcibf5hm2i4m6q
From:                 t3ut43tdij45auivo7m444y3atatarsfcpslpdcxgi2avymrdiz3hmzsgwhvw2ntb74bhsn5maz4caaxtkhfeq
To:                   t1rji2fhc4f5ztuv6liw22epiuy265o4zphgzapry
Confirmed Amt: …
```

paych: Create `lotus paych status` command

---

cli/paych.go
cli/paych_test.go
documentation/en/payment-channels.md

See https://github.com/filecoin-project/lotus/issues/3499

paych: rename CLI command from "paych get" to "paych add-funds"

---

api/types.go
cli/paych_test.go
node/impl/full/gas.go

Cap it just to FeeCap, there is no reason to cap it proportionally

Fix GasPremium capping logic

---

cmd/lotus-pcr/main.go

Adds a flag `--aggregate-tipsets` which allows setting the number of tipsets which will be processed before refunds are sent to reduce message congestion produced by the service.

lotus-pcr: add tipset aggregation

---

cmd/lotus-pcr/main.go

Using the tipset which is being processed might lead to incorrect gas estimations or balance checking for the wallet.

lotus-pcr: use current tipset during refund

---

chain/messagepool/messagepool_test.go
chain/messagepool/selection.go
chain/messagepool/selection_test.go

fix selection bug; priority messages were not included if other chains were negative

---

cmd/lotus-shed/main.go
cmd/lotus-shed/math.go

There are quite a few times I run into dealing with large numbers and I want to either add them all up or parse them into a more readable format. This is the start of that effort.

lotus-shed: add math command

---

chain/messagepool/messagepool.go

we are now erroring under a lot more conditions (for spam protection reasons), so this has become an issue.

reduce mpool add failure log spam

---

node/modules/lp2p/pubsub.go

Reduce from the default 0.25 to 0.1; it comes with a 10x outbound bandwidth reduction, albeit at the cost of somewhat reduced security. The security effect is that the probability of a peer receiving an IHAVE about a particular message drops from 0.57 to 0.27.
Also adjusts gossiping for bootstrappers, so that they use less bandwidth.

adjust gossipsub gossip factor

---

markets/storageadapter/client.go

The markets client node adapter is crashing in OnDealExpiredSlashed when a nil tipset is passed to check func
Just  skip checkFunc logic when nil tipset is passed -- similar to https://github.com/filecoin-project/lotus/pull/3011
We should figure out why the events_called interface is passing nil tipsets to CheckFunc. I think there may be a bug in the tipset cache logic

Fix panic in OnDealExpiredSlashed

---

api/api_full.go
api/apistruct/struct.go
cli/paych.go
cli/paych_test.go
documentation/en/api-methods.md
node/impl/paych/paych.go
paychmgr/manager.go
paychmgr/paych.go
paychmgr/paychget_test.go
paychmgr/simple.go
paychmgr/store.go

Previously we had a method to get available funds for a channel by from/to, which makes sense from CLI. However for [markets non-blocking retrieval](https://github.com/filecoin-project/go-fil-markets/pull/392) it makes more sense to get funds by channel address.
This PR adds a new API method to get available funds by channel address. So now there are two API methods to get available funds for a channel:
```go
PaychAvailableFunds(ch address.Address) (*ChannelAvailableFunds, error)
PaychAvailableFundsByFromTo(from, to address.Address) (*ChannelAvailableFunds, error)
```

paych: get available funds by address or by from/to

---

chain/stmgr/utils.go
chain/vm/invoker.go
cli/send.go
cli/state.go

Also, don't simply assume that the field order matches the method numbers in `builtin.Method*` structs.

Robustify state manager against holes in actor method numbers

---

chain/messagepool/messagepool.go
chain/types/mock/chain.go

Part of the ongoing endeavour to harden against Spam Attacks.

add defensive check for minimum GasFeeCap for inclusion within the next 20 blocks

---

chain/vm/invoker.go

I got this misleading error message today. Second argument should be a pointer, not runtime.

fix: second argument error message

---

chain/sync.go
metrics/metrics.go

Exports the expected height of the node based off of the current time, block delay and the genesis timestamp.
Between the following stats we should be able to get some pretty good information about the status of a node with regard to it's chain
```
lotus_chain_node_height 35354
lotus_chain_node_height_expected 35354
lotus_chain_node_worker_height 35354
```

metrics: add expected height metric

---

chain/messagepool/messagepool.go
chain/messagepool/repub.go

On top of #3579 and in conjunction with #3518 
Improves the publish/republish logic so that:
- local messages that are pushed to the mpool are not immediately published if they can't be included in the next 20 blocks
- we only republish messages if they can be included in the next 20 blocks
- also reduces the republish batch delay to 100ms (from 200ms)
This will reduce our bandwidth requirements and (most important for spam control) our rate of ignored messages.

Improve publish/republish logic

---

go.mod
go.sum
node/modules/lp2p/pubsub.go

Depends on https://github.com/libp2p/go-libp2p-pubsub/pull/384

integrate pubsub Random Early Drop

---

chain/messagepool/messagepool.go
chain/messagepool/repub.go
chain/messagepool/selection.go
chain/messagepool/selection_test.go

On top of #3592 
Temporarily allows negative chains and disables the base fee lower bound check until the next fork.
This mutilation will be undone in Thursday's fork, so we only have to tolerate it for a few days.

temporarily allow negative chains

---

CHANGELOG.md
build/version.go

Lotus version v.0.6.0

---

chain/store/store.go
chain/sync_test.go
node/modules/services.go
node/test/builder.go

Reverts filecoin-project/lotus#3602

Revert "only subscribe to pubsub topics once we are synced"

---

extern/sector-storage/ffiwrapper/sealer_cgo.go
extern/sector-storage/manager.go

Currently `Sealer.ReadPiece()` always returns `false`. This PR changes it to return `true` on success.

storage: return true from Sealer.ReadPiece() on success

---

chain/sub/incoming.go

Cherry-picked from #3646 where the bug was discovered.
Basically it was a check of seconds (in the timestamp) -vs- nanoseconds from the clock; gah.

fix isChainNearSync check in block validator

---

extern/sector-storage/ffiwrapper/sealer_cgo.go
extern/sector-storage/manager.go

Fixes https://github.com/filecoin-project/lotus/issues/3558
The first attempt (https://github.com/filecoin-project/lotus/pull/3615) included an extra logic change that caused some tests to fail. I'm investigating why it causes test failures.
This PR is the same but without the extra change: it just checks if the unsealed cid is undefined, and returns an error if so.

storage manager: bail out with an error if unsealed cid is undefined (redux)

---

chain/messagepool/repub.go

this bug cannot be really triggered as messages will not be accepted if the GasFeeCap is less than  minimumBaseFee, but it doesn't hurt to be correct.

fix very minor bug in repub baseFeeLowerBound

---

chain/stmgr/forks.go
chain/stmgr/forks_test.go
chain/stmgr/stmgr.go
chain/stmgr/utils.go
conformance/driver.go

Currently, syncing the chain from scratch would break because we would do a lookback into the future. This should do the trick.

pass tipset through upgrade logic

---

.github/CODEOWNERS

Feel free to edit the file to add rules/owners.
---
Fixes bullet 4 of #3666.

initial CODEOWNERS.

---

miner/miner.go

When stopping Drand with Testground on a testnet, I am getting a lot of `failed getting beacon entry` error messages, due to the `for` / `continue` loop.
I suggest we add some kind of delay if `m.api.BeaconGetEntry` fails, although I am not sure if 1 second is not too large.

add niceSleep 1 second when drand errors

---

storage/wdpost_run.go

This is no longer necessary, and doesn't really serve any purpose.

Remove hard-coded late-fee in window PoSt

---

api/api_full.go
api/apistruct/struct.go
chain/badtscache.go
chain/checkpoint.go
chain/sync.go
chain/sync_test.go
cli/chain.go
cli/sync.go
cli/util.go
documentation/en/api-methods.md
documentation/en/architecture.md
node/impl/full/sync.go
node/modules/chain.go

Such tipsets are never forked away
Fixes #3290

Allow nodes to mark tipsets as checkpointed

---

.github/CODEOWNERS

3 pairs of eyes are better than two and getting directly notified on PR is what I want (but GH notifications have no repo+PR filter).

Add Kubuxu to CODEOWNERS

---

chain/messagepool/selection.go

Also moved the random selection timer inside the if block.

warn when optimal selection fails to pack a block and we fall back to random selection

---

build/params_2k.go

The breeze state fork cannot be run at height 0, basically
Fix #3694

Fix devnets

---

chain/store/store.go
chain/sync_test.go
node/impl/full/sync.go

Added test fails before fix, works after

Fix IsAncestorOf

---

chain/messagepool/messagepool.go

So that a node can have more than 1k pending messages for its own local addresses.
FIxes #3722

relax mpool add strictness checks for local pushes

---

extern/storage-sealing/states_failed.go

Because restarting a precommit2 worker twice during sector data transfer has resulted in them being sent back to precommit1.
Ideally, there would be a subset of errors that cause this counter to increment and not things like the user restarting a worker.

Increase the number of times precommit2 is attempted before moving back to precommit1

---

api/api_full.go
api/apistruct/struct.go
build/params_shared_funcs.go
build/params_shared_vals.go
build/params_testground.go
chain/gen/genesis/genesis.go
chain/gen/genesis/miners.go
chain/stmgr/forks_test.go
chain/stmgr/stmgr.go
chain/stmgr/utils.go
chain/vm/invoker.go
chain/vm/invoker_test.go
chain/vm/runtime.go
chain/vm/vm.go
conformance/chaos/actor.go
documentation/en/api-methods.md
go.mod
go.sum
node/impl/client/client.go
node/impl/full/state.go
storage/miner.go
storage/wdpost_run.go
storage/wdpost_sched.go

This is actually fully backwards-compatible with v0.9.7, so we could just merge into master, but might as well send it into the staging branch.

Update to specs-actors v0.9.8

---

chain/gen/gen.go
chain/sync.go
cmd/lotus/debug_advance.go
miner/miner.go

This change ensures that the VRF is always a chain.
Previous behavior: previous randomness was only used when there were no drand values.
Current correct behavior: VRF ticket is generated this block's drand value and previous tipset's ticket
Fixes #2778

Fix VRF chain randomness

---

build/params_testground.go
chain/store/basefee.go
chain/store/basefee_test.go
tools/stats/metrics.go

This should increase observed network capacity by around 20%

Remove PackingEfficiency consideration from base fee in an upgrade

---

api/api_full.go
api/apistruct/struct.go
chain/store/store.go
chain/store/store_test.go
cli/chain.go
cli/state.go
cmd/lotus-shed/export.go
cmd/lotus-shed/main.go
documentation/en/api-methods.md
node/impl/full/chain.go

This command completes an export on a nodes repo directly (requires node to be offline unfortunately) and also adds a `--skip-old-msgs` flag that doesnt include messages from before the included stateroots in the snapshot. This makes the snapshots significantly smaller. The one I ran was 2.5GB and compresses down to 1.7GB.
Oh, and its a lot faster, the below command took 2 minutes.
Command:
```
./lotus-shed export --skip-old-msgs --recent-stateroots=900 snapshot.car
```

Add faster and slimmer option to chain export via lotus-shed

---

chain/messagepool/messagepool.go
chain/messagepool/pruning.go
chain/messagepool/repub.go

Also fixes clown shoes check in repub; emacs M-/ auto completed to baseFeeLowerBoundFactor... so we ended up (potentially) republishing everything, not just the near-profitable messages.

refactor getBaseFeeLowerBound, use it to prune less aggressively

---

go.mod
go.sum
markets/storageadapter/client.go
markets/storageadapter/provider.go

Updating markets adapters to use new `WaitForMessage` API in `go-fil-markets`.
Resolves #3703

Fix for PublishDeals message cid changing due to gas

---

cli/paych.go

The `paych status` command is not accessible cause while it's written it wasn't added to the list of commands for payment channels.

add paych status command to list

---

chain/messagepool/pruning.go

don't prune locally published messages

---

node/impl/full/gas.go

FeeCap will be set to 10x the current running rate

Increase the FeeCap estimation to 20 blocks in a future

---

.circleci/config.yml

Our timeout of 2 minutes is being hit, and we can avoid that if we use all compute power available to us.
This introduces a ~40% gain on wall-clock time for the lint-all target.

circleci: make lint expend all cores.

---

chain/stmgr/forks_test.go
chain/vm/invoker.go
chain/vm/runtime.go
chain/vm/runtime_test.go
chain/vm/vm.go
conformance/chaos/actor.go
conformance/chaos/actor_test.go
go.mod
go.sum

This patch changes the runtime interfaces, to make it possible to abstract over them.

Update to specs-actors 0.9.9

---

chain/events/state/diff_adt.go
chain/events/state/diff_adt_test.go
chain/events/state/predicates.go
chain/gen/genesis/t01_init.go
chain/state/statetree.go
chain/stmgr/utils.go
chain/sync.go
cli/chain.go
cmd/lotus-chainwatch/processor/miner.go
cmd/lotus-shed/verifreg.go
go.mod
go.sum
node/impl/full/chain.go
node/impl/full/state.go
storage/adapter_storage_miner.go

Moves the Keyer type (and helpers) into go-state-types.

Update specs-actors to 0.9.10

---

storage/wdpost_run.go
storage/wdpost_run_test.go

Fixes https://github.com/filecoin-project/lotus/issues/3332

storage: split window PoST submission into multiple messages

---

api/api_full.go
api/apistruct/struct.go
cli/paych.go
documentation/en/api-methods.md
markets/retrievaladapter/client.go
node/impl/paych/paych.go

Fix a couple bugs preventing the use of payment channel status commands
- add context to payment channel commands in API
- add status-from-to to commands list

Fix payment channel status commands

---

node/impl/full/state.go

I think this has just always been wrong

Fix MsigGetAvailableBalance

---

chain/sync.go
chain/sync_manager.go
chain/sync_manager_test.go
node/builder.go
node/modules/chain.go

For the blockseq test vectors, I need to use a simplified sync manager that does no scheduling or peer tracking, and directly proxies `SyncManager#SetPeerHead` calls to `Syncer#Sync`. Alternatively, I could make blockseq vectors call `Syncer#Sync` directly instead of `Syncer#InformNewHead`, but that's not correct as an entrypoint because the latter does validation that the former doesn't.

syncer: make SyncManager an interface.

---

extern/sector-storage/manager.go

When there is an unsealed copy available, due to fast retrieval, we should be able to fetch it even while the sector is sealing
Currently, retrieval during sealing is blocked because the ReadPiece command grabs a storage lock that needs:
Read on Sealed copy and Cache
Write on Unsealed
All of these are needed if an Unseal is neccesary.
However, only Read on Unsealed is needed to first attempt to read the unsealed copy, which will not conflict with the lock for sealing.
The approach here is as follows:
- Use an initial less restrictive storage lock when trying to read unsealed data
- Release and acquire a more if needed restrictive lock needed for unsealing

Allow retrievals while sealing

---

node/builder.go

func New(ctx context.Context , opts ...Option) (StopFunc, error) in builder.go,  Is a public function, should not have nodeType: repo.FullNode.

optimize Settings.nodeType

---

.gitignore
Makefile
cmd/lotus-gateway/api.go
cmd/lotus-gateway/main.go

lotus-gateway aims to be a more robust API endpoint for exposing to the public. The aim is to expose only a subset of endpoints, and take extra precautions to make sure each exposed endpoint is properly robust against DoS attacks (notably, the lotus daemon itself is not natively DoS resistant, which is why you shouldnt expose it publically)

implement initial lotus-gateway program

---

chain/store/store.go
chain/sync_test.go

This should work, relying on the validity checks in the syncer's `checkBlockMessages`. That method asserts that the messages in each _individual_ block have contiguous nonces-per-sender, AND that the lowest nonce is correct based on the parent tipset state. 
This means that the first message we encounter from a sender in the first block in a tipset (indeed, in _any_ block in a tipset) must have nonce equal to the actor's nonce in the parent state. This means the state tree read introduced in https://github.com/filecoin-project/lotus/pull/243 isn't needed (anymore?)

Sever chainstore's dependence on the state tree

---

node/builder.go

Extract will be deprecated soon: use Populate instead, which doesn't require defining a container struct.
https://godoc.org/go.uber.org/fx#Extract

Replace fx.Extract with fx.Populate

---

chain/stmgr/utils.go
chain/sync.go
cmd/lotus-bench/main.go
storage/addresses.go
storage/wdpost_run.go
storage/wdpost_sched.go

This is to make filter out window PoSt related log messages easier.

Use `window post` for window PoSt related log messages.

---

cli/client.go

Partially addresses #3858, the remainder has to happen in markets (ideally after actors exports `dealDurationBounds`).

Make interactive deal CLI reject deals shorter than minimum duration

---

chain/actors/builtin/paych/mock/mock.go
chain/actors/builtin/paych/paych.go
chain/actors/builtin/paych/v0.go
chain/events/state/predicates.go
chain/events/state/predicates_test.go
chain/stmgr/stmgr.go
cli/paych_test.go
paychmgr/manager.go
paychmgr/mock_test.go
paychmgr/msglistener_test.go
paychmgr/paych.go
paychmgr/paych_test.go
paychmgr/paychget_test.go
paychmgr/simple.go
paychmgr/state.go

Support actor upgrades -- specifically the payment channels
This covers only the state access part -- I did not attempt to address message submission cause it's not yet addressed in the larger PR. Of particular concern to pay attention to is the use of SignedVoucher -- a fairly complex data structure which is not stored on chain but appears in message submission for the payment channel state, and is tracked off chain in the payment channel manager. The number of references in the code to this data structure is large
- apply patterns for other abstracted actors to make an abstracted payment channel actor
- add a state manager method to load a payment channel actor (removes the need to have access to any ADT store in the paychmgr +1)
- fix the state predicates, but only make them abstract …

Support Network Upgrades: Payment Channel

---

tools/stats/metrics.go

When compiling with the `+testground` build flag, `build.BlockGasTarget` is `var` of type `int64`, so compilation fails (see https://app.circleci.com/pipelines/github/filecoin-project/lotus/9331/workflows/a5f2a904-452e-4853-80a2-5325b7bbc3df/jobs/60386)

make sure lotus compiles with +testground build flag

---

.circleci/config.yml
.gitmodules

This PR is adding `filecoin-project/oni` as a submodule to `lotus` and running a compilation step on every commit for `lotus-soup` test plan, so that we have the test plan in sync with the Lotus code base.
---
The idea of this PR is to make sure that `lotus-soup` test plan stays compatible with `filecoin-project/lotus` and we can run the test plan with a specific schedule (nightly, or every 6 hours, or whatever) based on `lotus` `master` branch.

add filecoin-project oni as submodule and compile lotus-soup

---

miner/miner.go

I received 4MM logs of `failed to get best mining candidate: RPC client error: sendRequest failed: websocket routine exiting` in 60 seconds after the lotus daemon died.
Probably not the correct way to handle this but we need to handle this better.

break out of mining loop when stop is called during niceSleep

---

chain/actors/adt/diff_adt.go
chain/actors/adt/diff_adt_test.go
chain/actors/builtin/market/market.go
chain/actors/builtin/market/v0.go
chain/events/state/predicates.go
chain/events/state/predicates_test.go
cmd/lotus-chainwatch/processor/market.go

Complete changes to make state predicates work for abstract types on markets
- Move the ADT diffing functions inside of the chain/actors/adt package (especially since they are abstract functions for diffing ADTs)
- Build out the abstract storage market actor to support state diffing
- Specifically leaving unaddressed for the most part how to compare states across versions -- need to get a sense of what could change first. Presumably every comparison would be a different case on a version by version basis... unfortunately. And would need to be handled inside the actors package.
- If this pattern works it can be applied to the miner diffing functions as well.

feat(market): update state diffing for market actor

---

cmd/lotus-storage-miner/retrieval-deals.go

Expose `MarketGetRetrievalAsk`, `MarketSetRetrievalAsk` APIs via the CLI.
The `set-ask` command allows you to modify any or all parameters of the current ask.
Resolves #3843

Add get-ask, set-ask retrieval commands

---

cmd/lotus-shed/bitfield.go
storage/wdpost_run.go

Fixes #3808
Fixes #3788
Basically when retrying after getting bad sectors from GeneratePoSt we'd keep the old partition entries with no skipped sectors around.

wdpost: Only add proven partitions to message params

---

README.md

Update the link since we deprecated lotus.sh and migrates it to doc.Filecoin
Fixes #3918

Update build and setup instruction link

---

cmd/lotus-shed/jwt.go
cmd/lotus-shed/keyinfo.go

Provides a way to verify that keystore objects are correctly named. This is primarily for use when the keystore is manually constructed and provides a level of safety that wallets are name what they are suppose to be.
Also adding a command to create tokens with different permissions.

Add keyinfo verify and jwt token command to lotus-shed

---

conformance/chaos/cbor_gen.go
conformance/chaos/gen/gen.go

when `make gen` . The cbor_gen.go generated in conformance folder, but it should be in chaos folder.

fix conformance gen

---

cmd/lotus-storage-miner/sectors.go
extern/storage-sealing/sector_state.go

fix #3626 
update SectorState type.

fix SectorState

---

conformance/chaos/actor.go
conformance/chaos/actor_test.go
conformance/chaos/cbor_gen.go
conformance/chaos/gen/gen.go

Cut down version of https://github.com/filecoin-project/lotus/pull/3857 with just the changes to send validation addresses and type CIDs.

refactor: chaos caller validation

---

cmd/lotus-shed/consensus.go
cmd/lotus-shed/main.go

Consensus check verifies that all nodes share a common tipset for a given height.
The height flag specifies a chain height to start a comparison from. There are two special arguments for this flag. All other expected values should be chain tipset heights.
@common   - Use the maximum common chain height between all nodes
@expected - Use the current time and the genesis timestamp to determine a height
Examples
Find the highest common tipset and look back 10 tipsets
```
lotus-shed consensus check --height @common --lookback 10
```
Calculate the expected tipset height and look back 10 tipsets
```
lotus-shed consensus check --height @expected --lookback 10
```
Check if nodes all share a common genesis
```
lotus-shed consensus check --height 0
```
Check that all nodes agree upon the tipset for …

lotus-shed: add consensus check command

---

chain/actors/builtin/init/init.go
chain/actors/builtin/init/v0.go

As discussed in https://github.com/filecoin-project/oni/pull/260 and off-band. Unfortunately there is no non-intrusive way of doing this. Reflection won't work on private types/fields, and even if we reconstructed the v0 state from scratch, we can't access `NextAddress`.

add init.State#Remove() for testing.

---

chain/exchange/client.go
chain/exchange/protocol.go
chain/exchange/server.go
chain/sync.go

Also fixes stream leaks during sync.

Parallel fetch for chain sync

---

api/api_full.go
api/apistruct/struct.go
cli/chain.go
documentation/en/api-methods.md
node/impl/full/chain.go

Delete a chain store object

---

chain/actors/builtin/miner/v0.go

fix out-of-bounds when loading all sector infos

---

cmd/lotus-storage-miner/sectors.go

So that one doesn't have to look into the code to find the valid states.

When doing `sectors update-state`, show a list of existing states if user inputs an invalid one.

---

chain/exchange/client.go
chain/exchange/interfaces.go
chain/exchange/protocol.go
chain/sync.go

On top of #3887 
stricter validation of response indicies

Validate chain sync response indices when fetching messages

---

chain/sync.go
chain/vm/vm.go

speeds up chain sync by like 30%

batch blockstore copies after block validation

---

build/params_2k.go
build/params_testnet.go
chain/actors/builtin/miner/miner.go
chain/actors/policy/policy.go
chain/gen/gen.go
chain/gen/gen_test.go
chain/stmgr/forks_test.go
chain/store/store_test.go
chain/sync_test.go
cli/paych_test.go
cmd/lotus-bench/main.go
extern/storage-sealing/checks.go
extern/storage-sealing/states_sealing.go
lotuspond/spawn.go
node/node_test.go

Addresses:
* https://github.com/filecoin-project/lotus/pull/3781/files/a307e4593a005888395db34e5af4691ee50d765d#r491966115
* https://github.com/filecoin-project/lotus/pull/3781/files/a307e4593a005888395db34e5af4691ee50d765d#r491966634

Add some actors policy setters for testing

---

miner/miner.go

break error

---

cmd/lotus-storage-miner/proving.go

- To show the current proving period deadline information of given deadline index.
- It outputs the following:
- number of partitions in this deadline
- partitions numbers has submitted PoSt since the current proving period started
- if the deadline is the current proving deadline
- for each patition, shows the amount of the sectors in this partition, and their numbers. Also, shows the number of fault sectors and corresponding sector numbers.
fixes #3941

3941: Added cmd `lotus-miner proving deadline <deadline index>`

---

api/api_full.go
chain/vm/vm.go
cli/sync.go
documentation/en/api-methods.md
node/impl/full/sync.go

Looks like this:
Fixes #919 (output is ~50 cols now)

Make sync wait nicer

---

chain/state/statetree.go
conformance/driver.go

Refer to commit log for breakdown.

small adjustments following network upgradability changes

---

cmd/lotus-storage-miner/market.go

Quick thing needed for slingshot

Correct helptext 

---

go.mod
go.sum

Markets 0.6.3 just updates go-graphsync to v0.2.1, which contains a fix for the bug introduced in v0.2.0

Update markets to 0.6.3

---

api/test/ccupgrade.go
chain/actors/builtin/miner/v0.go

Returning nil, nil is a footgun.
fix: https://github.com/filecoin-project/lotus/issues/3984

return an error when we fail to find a sector when checking sector expiration

---

build/params_shared_funcs.go
build/params_shared_vals.go
chain/types_test.go
go.mod
go.sum

Does the thing, works, seems to sync regardless of the new envvar

Add an envvar to set address network version

---

chain/store/store.go

resolves #4029
example logs https://gist.github.com/travisperson/6e62227adb6fc41599653582274055ea

add logging to chain export

---

build/bootstrap/bootstrappers.pi

To make network even more resilient we need to increase a number of trusted distributed bootstrap peers. Glif's node can become one of these peers.
CC @momack2

Add glif node to bootstrap peers

---

chain/actors/builtin/miner/miner.go
storage/wdpost_changehandler.go
storage/wdpost_changehandler_test.go
storage/wdpost_nextdl_test.go

Use abstract types for https://github.com/filecoin-project/lotus/pull/3924 instead of using specs-actors directly.
I put this in a separate PR so that it's easier to modify just this part if needs be.

Use abstract types for Dont recompute post on revert

---

chain/store/store.go

Currently the tipset block headers are fetched from the blockstore in series. This PR instead fetches them in parallel, which should improve `ChainIndex` performance.

fetch tipset blocks in parallel

---

cmd/tvx/extract.go
cmd/tvx/extract_many.go
conformance/driver.go
conformance/runner.go
go.mod
go.sum

To be merged into the `tvx` branch.
---
The `tvx extract` command now queries the circulating supply at the inclusion tipset, and records it in the vector.
The driver picks up the circulating supply from the vector (if set), and feeds it into the VM. If not set, it uses the total Filecoin ever in supply as a default fallback.

conformance: record and feed circulating supply.

---

cli/wallet.go

```
Address                                                                                 Balance                   Nonce  Default  
t1fjwd7qdzbc7dfv7uzsbuc5y7te25eiwcn6z4jni                                               0.0003 FIL                0               
t1tmsxz5gfzrvfha75or6vwr552kvdle34skw5doq                                               0.004599227037176968 FIL  4      X        
t3r6abgy4rmhzj3nbjbm5eo4pgbv3o3vfzew5sttbby3afaqi25z6zo4ecsecxdqrl7bqsq5lgq2phgfbqrduq  0.0001 FIL                0 
```

wallet list cli: Print balances/nonces

---

chain/messagepool/messagepool.go
chain/messagesigner/messagesigner.go
chain/messagesigner/messagesigner_test.go
node/builder.go
node/impl/full/mpool.go

Fixes https://github.com/filecoin-project/lotus/issues/3957

refactor: move nonce generation out of mpool

---

cmd/lotus-storage-miner/info.go

fixes #3913 (more on surface level)
Should consider implementing #4002 to fix it from root.

Added an option to show or not show sector info for `lotus-miner info`

---

cmd/lotus-shed/import-car.go
cmd/lotus-shed/main.go

Can potentially be helpful to recover mildly corrupted chainstores

add a command to import an ipld object into the chainstore

---

chain/sync.go

If this isn't done asynchronously intentionally let me know, but seemed off to me. Also the weight calculation and check could be done async as well (also not sure if that was intentionally left out)
Edit: nil pointer deref test failure is also happening on master so I won't look more into the failure

Make state transition in validation async

---

api/api_full.go
api/apistruct/struct.go
documentation/en/api-methods.md
node/impl/full/wallet.go

Add an endpoint to validate whether a string is a well-formed address

---

chain/actors/builtin/miner/miner.go
storage/wdpost_changehandler.go
storage/wdpost_changehandler_test.go
storage/wdpost_nextdl_test.go
storage/wdpost_run.go
storage/wdpost_run_test.go
storage/wdpost_sched.go

Supersedes https://github.com/filecoin-project/lotus/pull/3833
Fixes https://github.com/filecoin-project/lotus/issues/3560 https://github.com/filecoin-project/lotus/issues/3561
The previous state machine implementation has an issue whereby:
- Let's say we're in deadline 5
- We generate a proof for deadline 5 and submit it successfully
- When we reach the challenge epoch for deadline 6 (10 minutes before deadline 6 opens), we start proving for deadline 6
- The chain reorgs such that the revert goes back into deadline 4
At this point we should resubmit the proof for deadline 5. But the state machine is a single thread, so it would have to either
- Cancel proving for deadline 6
- Wait for proving for deadline 6 to complete, then try to resubmit for deadline 5 (if it hasn't already expired) …

Dont recompute post on revert <<redux>>

---

cmd/lotus-seal-worker/main.go
extern/sector-storage/localworker.go

Usage of swap will slower AMD Ryzen PC1 speed, so add flag to disable swap on worker.

Add --no-swap flag for worker

---

cmd/lotus/daemon.go
node/repo/fsrepo.go

A solution for #3674 that seems to work.

Add an option to set config

---

extern/storage-sealing/states_failed.go

I think this is correct?
Thanks to @Arctic in the Filecoin slack for the report.

Fix some failed precommit handling

---

cli/client.go
cli/util.go
cmd/lotus-storage-miner/sectors.go
go.mod
go.sum
lib/tablewriter/tablewriter.go

Made it show more relevant info
Before:
After:

Improve miner sectors list UX

---

api/test/paych.go
chain/actors/builtin/paych/mock/mock.go
paychmgr/mock_test.go
paychmgr/paych.go
paychmgr/paych_test.go
paychmgr/paychget_test.go
paychmgr/paychvoucherfunds_test.go
paychmgr/simple.go

Payment channels can be
- Outbound: the payment channel is *from* the local node’s account *to* another account.
For example when a client wants to retrieve data
- The client creates an outbound payment channel on-chain to the node that has the data
- The client creates a voucher locally
- The client checks that creating the voucher will not exceed the remaining balance in the channel
- The client sends the voucher directly to the data provider
- Inbound: the payment channel *from* a remote account *to* the local node’s account.
For example when a data provider receives a voucher on a payment channel
- The data provider fetches the payment channel for the voucher from chain state
- The data provider checks that adding the voucher will not exceed the remaining balance in the channel
- The …

paych: fix voucher amount verification

---

cli/client.go

In the interactive deal creation CLI, allow a client to make a deal verified (if the client has a sufficient `DataCap`).
Resolves #4137

Add verified flag to interactive deal creation

---

chain/stmgr/stmgr.go

Actors state migrations will take place within a fork function called from `handleStateForks`.  In general migrations need the epoch the transition is run at to work correctly.  We are assuming the epoch passed to any migration function will be the same epoch passed to `handleStateForks`, `i`.
`i` is the fork epoch.  In the common case of no null blocks it is the "previous epoch" in the sense that epoch `i`'s cron has already run as part of processing the parent tipset and state.  
If there are null blocks then for `i > parentEpoch` epoch `i`'s cron will not have run before the fork function because of the current ordering of fork function before cron.  We can't distinguish these two cases from within the migration function so the epoch we are passed in won't be well defined with respect …

Run fork function after cron for null block safety

---

chain/sub/incoming.go

1. Explicitly use a session when fetching messages for a block. Technically, GetBlocks would use an internal session so we'd only end up with two, but one per block is even better.
2. Actually cancel sessions after a timeout (threading through the context).
This should reduce the impact of the current bitswap storm a bit.
NOTE: We should seriously consider having a single session for all blocks, but we can do that in a followup as it may have unintended consequences (e.g., leaks).

use bitswap sessions when fetching messages, and cancel them

---

chain/messagesigner/messagesigner.go
chain/messagesigner/messagesigner_test.go
node/impl/full/mpool.go

Fixes two problems with nonce generation:
- nonce generation was not transactional, so if `Mpool.Push` failed, there would be a gap between nonces
- there was no lock when generating a nonce, so two messages could end up with the same nonce

fix: make message signer nonce generation transactional

---

cli/cmd.go
cmd/lotus-storage-miner/allinfo_test.go
cmd/lotus-storage-miner/info_all.go
node/impl/common/common.go

Not a great test in terms of testing output, but it at least makes sure that a decent chunk of miner CLI doesn't throw random errors

Test lotus-miner info all

---

chain/exchange/client.go
cli/chain.go

Useful for inspecting why the chain is congested.

add a command to view block space utilization

---

node/modules/storageminer.go

Reject deals that start too far in the future.  Right now, just make this 90 days, as discussed in the issue.
TODO: read from config
Resolves #3929

Reject deals that are > 90 days in the future in the BasicDealFilter

---

cli/chain.go

i wasnt ready to merge #4176, but oh well

allow usage inspection on a chain segment

---

node/modules/lp2p/pubsub.go

So that we can run calibration networks.

relax pubsub IPColocationFactorThreshold to 5

---

cli/chain.go
node/impl/full/chain.go

Fixes https://github.com/filecoin-project/lotus/issues/4098
Verified to work when the daemon dies with sigkill/sigterm/sigint

chain export: Error with unfinished exports

---

api/api_full.go
chain/actors/builtin/miner/miner.go
chain/actors/builtin/miner/v0.go
chain/actors/builtin/miner/v2.go
chain/actors/policy/policy.go
chain/stmgr/utils.go
chain/sub/incoming.go
chain/sync.go
documentation/en/api-methods.md
miner/miner.go

Fixes #3378, but reproduces the new actors methods in Lotus, since passing State objects to an actors method is super ugly with the refactor.

Update miner eligibility checks for v2 actors

---

build/params_shared_vals.go
build/params_testground.go
chain/actors/builtin/builtin.go
chain/gen/genesis/genesis.go
chain/stmgr/stmgr.go

Yields the following numbers at height 130000 (after the v2 actors upgrade)
FilVested 13429543.811411839397160646 FIL
FilCirculating 5961737.242508608156582553

Add funds that have left FilReserve to circ supply

---

cmd/lotus-storage-miner/actor.go

This is of questionable utility, since its purpose is to set miner owner addresses to a more secure key than was used on testnetnet, yet requires the new "secure" key to be imported into the Lotus wallet...
BUT, it's a req for 0.9.0, so we roll with this for now.
Tested, it does the thing.

Add a CLI command to set a miner's owner address

---

build/params_shared_vals.go
build/params_testground.go
chain/actors/policy/policy.go
chain/stmgr/utils.go

Set WinningPoStSectorSetLookback to finality post-v2 actors

---

chain/vm/runtime.go

Attempting to resolve https://github.com/filecoin-project/test-vectors/issues/87, quoting @anorth:
> If an actor implementation panics directly (rather than calling Abortf) then the evaluation is undefined. There is no exit code corresponding to this. The result should not go on chain. A panic (which could also come from some actor dependency) may indicate a transient state or error that cannot be replicated by other nodes and thus cannot form part of consensus. E.g. an out-of-memory.
I believe that returning a "fatal" `ActorError` instead of `SysErrSenderInvalid(1)` prevents the message from being recorded on chain since it's caught in [ApplyMessage here](https://github.com/filecoin-project/lotus/blob/de772bf1f9e5e2e38feaf1655a889e77c8126d74/chain/vm/vm.go#L451).

fix: error when actor panics directly

---

cmd/lotus-pcr/main.go

- Do not process pre commit sectors, and prove commit sector messages which have a fee cap larger than 0.1 nanoFIL
- Refund windowed post and publish storage deals gas fees

Limit the fee cap of messages we will process, refund gas fees for windowed post and storage deals

---

cmd/tvx/extract.go
conformance/driver.go
conformance/rand_fixed.go
conformance/runner.go
conformance/stubs.go

* make `vm.Rand` settable by the caller. Enables forthcoming `RecordingRand`, which records randomness from chain into the vector.
* simplify/encapsulate basefee and circulating supply handling.

conformance: minor driver refactors.

---

build/params_testnet.go

Defaulting to f.. addresses may break some integrations, this provides an easy workaround

build: Env var to keep test address output

---

chain/actors/version.go
chain/gen/genesis/genesis.go
chain/state/statetree.go
chain/state/statetree_test.go
chain/stmgr/forks.go
chain/types/cbor_gen.go
chain/types/state.go
gen/main.go
lotuspond/front/src/chain/methods.json

Instead of versioning the state tree along with the actors, version it separately. This structure may not upgrade every time we update actors.

introduce separate state-tree versions

---

chain/stmgr/call.go
chain/stmgr/forks.go
chain/stmgr/forks_test.go
chain/stmgr/stmgr.go
chain/stmgr/utils.go
node/impl/full/gas.go
node/impl/full/state.go

Upgrades can be slow.
1. If a nil/empty tipset, use the latest non-fork tipset.
2. If passed an explicit tipset, return an error if it would invoke a fork.
3. When estimating gas, retry on previous tipsets till we find a non-fork tipset.

reject explicit "calls" at the upgrade height

---

chain/vm/invoker.go

As far as the chain is concerned, this actor does not exist.

return an illegal actor error when we see an unsupported actor version

---

cmd/tvx/extract.go
conformance/rand_record.go
conformance/rand_replay.go
conformance/runner.go
go.mod
go.sum

This PR adds the ability to record chain and beacon randomness values when extracting a test vector via `tvx`. It does so via an implementation of `vm.Rand` that proxies over requests for randomness to the Lotus node via JSON-RPC, and then memorises the return value.
When outputting the vector, the randomness values are encoded as a series of rules that match on:
* randomness kind (chain or beacon).
* domain separation tag
* epoch
* entropy
The driver then injects a special implementation of `vm.Rand` into the VM that replays the randomness values encoded in the vector, defaulting to a placeholder 32-byte fixed value, used in vectors built through the builder DSL.

conformance: record randomness in tvx; replay in driver.

---

cli/cmd.go
cli/paych_test.go
cli/pprof.go
cmd/lotus-shed/consensus.go

Currently the payment channel CLI tests use a `--api` flag to indicate which server to create a client API against (payment channel creator or payment channel receiver).
`lotus daemon` also takes a `--api` flag that indicates the port on which to start.
This PR fixes the clash by changing the flag that the tests use to `--api-url`
It also makes it possible to specify the api using a regular url (instead of a multiaddress):
`FULLNODE_API_INFO=<token>:/ip4/127.0.0.1/tcp/1234 go run ./cmd/lotus wallet balance t01234`
`FULLNODE_API_INFO="<token>:ws://127.0.0.1:1234" go run ./cmd/lotus wallet balance t01234`
This can be useful for example if a websocket url has a path (currently not possible to represent with a multiaddress).

fix: clash between daemon --api flag and cli tests

---

go.mod
go.sum
node/modules/lp2p/pubsub.go

- Updates go-libp2p-quic-transport to v0.8.2
- Updates go-libp2p-pubsub to v0.3.6
- Adds a subscription filter in pubsub that only allows the interesting topics (blocks, messages, drand); the limit is set to 100 suubscriptions in RPCs to allow eth2/filecoin bridges to function.

Update libp2p things

---

go.mod
go.sum

Improves throughput in large and/or fast transfers and reduces syscalls when data is queued in receive buffer, by using bufio.Reader.

upgrade go-libp2p-noise to v0.1.2.

---

chain/stmgr/stmgr.go
chain/sub/incoming.go
chain/sub/incoming_test.go
chain/sync.go

Optimize SearchForMessage and GetReceipt

---

api/api_full.go
api/apistruct/struct.go
documentation/en/api-methods.md
node/impl/full/state.go

MsigGetLockedBalance is redundant, since it's always just `actor balance - MsigGetAvailableBalance`, but meaningful enough I guess.
EDIT: Killed MsigGetLockedBalance

Add some new endpoints for querying Msig info

---

miner/miner.go

If ChainTipSetWeight returns an error, waiting outside for 5 seconds to try again will still report an error, resulting in an infinite loop, the miner can not dig properly block.
the error:
2020-09-01T11:31:50.596+0800	ERROR	miner	miner/miner.go:159	failed to get best mining candidate: loading tipset {bafy2bzacebaq24x6umldnhmr5fdsbd6zd44qqehkrioxavasgkmrqyckpm7es}: get block bafy2bzacebaq24x6umldnhmr5fdsbd6zd44qqehkrioxavasgkmrqyckpm7es: blockstore: block not found

fix GetBestMiningCandidate bug

---

cli/paych_test.go

We should not be clobbering the cmd variable.

fix a race in the payment channel status test

---

chain/market/fundmgr.go
chain/market/fundmgr_test.go

In the FundMgr's `EnsureAvailable`, if the MpoolPush call fails, we have the incorrect value cached in our local map of available funds for a given address, causing subsequent calls to possibly fail.
In the case of errors after we have updated the cached values, revert the value.
Resolves #4149

Revert cached "available" amount if the AddFunds message send fails

---

extern/sector-storage/ffiwrapper/sealer_cgo.go

1. Remove an invalid error check.
2. Make sure to shadow the outer error type from within the goroutine instead or reading the outer type.
This may have been causing test issues (caught in TestMinerAllInfo with the race detector).

fix race in unseal

---

chain/events/tscache.go

This tipset cache is shared between multiple services and is called from multiple places.

fix a race in tipset cache usage

---

chain/store/store.go
cmd/lotus/daemon.go

This solves (tested on multiple runs) a problem with folks resurrecting long-out-of-sync nodes via
snapshot imports.
The interface switch to Batching is necessary: startup is too long otherwise
( 8 minutes just to clear everything on a relatively old node )

Dump the block validation cache whenever we perform an import

---

chain/sync.go
chain/sync_manager.go
chain/syncstate.go
node/modules/services.go

LifecycleCtx can _only_ be called during startup as it appends an fx hook. Worse, this was causing us to append an fx hook on every single hello message, leaking memory (and probably causing other shutdown issues...).
1. SyncerState contains a mutex and should never be copied. Honestly, this case was probably fine but it's just as easy to create a separate snapshot type and easier to reason about.
2. We need to initialize the syncStates array once at start, before accessing it. By each syncer state inside each worker, we were racing with calls to `State()`. Again, this was probably benign, but I don't trust optimizing compilers.

Fix two races

---

build/params_2k.go
build/params_shared_vals.go
build/params_testground.go
build/params_testnet.go
chain/actors/version.go
chain/stmgr/forks.go
documentation/en/api-methods.md
go.mod
go.sum

Upgrade to specs-actors v2.1 and network version 5. This fixes the bug where prove commits were not accepted.

implement tape upgrade

---

api/test/tape.go
api/test/test.go
extern/sector-storage/mock/mock.go
node/node_test.go

This modifies the sealing mock to submit seal proofs with realistic sizes, fixes tests that would otherwise break, and tests the tape upgrade.

Test the tape upgrade

---

chain/actors/builtin/miner/miner.go
cmd/lotus-storage-miner/actor.go

Some low-hanging fruit, it works.

Add a CLI tool for miner's to repay debt

---

node/modules/storageminer.go

A basic filter was added that would reject storage deals that were more than 7 days in the future from the current chain head, but didn't take into consideration the seal duration configured by the miner.
Use the seal duration + 7 days as the first cut rejection criteria.
Addresses https://github.com/filecoin-project/lotus/pull/4173/files#r503249607

Use seal-duration in calculating the earliest StartEpoch

---

api/api_full.go
api/apistruct/struct.go
chain/actors/builtin/builtin.go
chain/actors/builtin/miner/miner.go
chain/actors/builtin/miner/v0.go
chain/actors/builtin/miner/v2.go
chain/stmgr/call.go
chain/stmgr/forks.go
chain/stmgr/stmgr.go
chain/stmgr/utils.go
cli/state.go
cmd/lotus-chainwatch/syncer/sync.go
cmd/lotus-shed/balances.go
cmd/tvx/extract.go
documentation/en/api-methods.md
node/impl/full/state.go

At height 136,374, circ supply is 15579755.735329679830248779 FIL

Add a StateExactCirculatingSupply command

---

cmd/lotus-pcr/main.go

Small change to ensure we return false for any methods we don't support to stop sending zero fil messages.

lotus-pcr: ignore all other market messages

---

chain/types/message.go
chain/types/message_test.go
chain/types/signedmessage.go
documentation/en/api-methods.md

types: Add CID fields to messages in json marshalers

---

api/test/test.go
chain/stmgr/stmgr.go
chain/types/message.go
chain/types/signedmessage.go

This way we will return the tipset the message was executed in

Fix off by one tipset in searchBackForMsg

---

chain/messagepool/messagepool.go

There may be a deeper issue here, but we need to handle this more gracefully somehow. See #4358.

fix a panic on startup when we fail to load the tipset

---

chain/stmgr/forks.go
chain/stmgr/stmgr.go

The relevant changes are:
- Don't `doTransfer` 0 FIL in `UpgradeFaucetBurnRecovery`
- Use currHeight as the nonce for implicit messages (not consensus-critical, since it doesn't live on chain, and is never observed by actors)
- Don't use the same nonce for every `doTransfer` 
**Someone should compute-state 41281 before merging this (i don't have the relevant state tree).**

Avoid having the same message CID show up in execution traces

---

api/api_full.go
chain/stmgr/call.go
chain/stmgr/stmgr.go
documentation/en/api-methods.md
node/impl/full/state.go

The new `InvocResult .MsgCid` is the canonical Msg CID (includes the siggy for secp messages), which may be different than what's returned by `InvocResult.Msg.Cid()`.

Add message CID to InvocResult

---

node/modules/storageminer.go

Closes https://github.com/filecoin-project/lotus/issues/4220.

Use updated stored ask API

---

cli/util/apiinfo.go

Reverts filecoin-project/lotus#4391
This breaks lotus-miner because we set a /http multiaddr as default in the config, and lotus-miner is using some functions which require channel support

Revert "Add support for /https, /http, /wss API multiaddresses."

---

build/drand.go
chain/beacon/drand/drand_test.go

* Remove incentinet (should not be used already)
* Add cloudflare endpoint.
* Switch PL endpoints to HTTP instead of HTTPS.

Update drand endpoints

---

chain/actors/builtin/miner/diff_deadlines.go
chain/actors/builtin/miner/v0.go
chain/actors/builtin/miner/v2.go

The method name `DeadlinesChanged` suggests it will return true when the deadlines have changed when in fact it returns false. This PR addresses this by having the methods return true when the deadlines have changed. The method `DeadlinesChnaged` is called in chainwatch and in `DiffDeadlines`. Neither of these methods are called in lotus.
A similar issue exists for `PartitionsChanged` as well that has been addressed here.

fix: return true when deadlines changed

---

chain/sub/incoming.go
chain/sync.go
lib/blockstore/blockstore.go
lib/blockstore/memstore.go
lib/blockstore/syncstore.go
lib/bufbstore/buf_bstore.go
lib/timedbs/timedbs.go
lib/timedbs/timedbs_test.go
node/modules/chain.go

Avoid writing messages/blocks that may not be useful to the blockstore until we've validated them.

reduce garbage in blockstore

---

node/impl/full/gas.go

2 block default doesn't result in much room for estimates with higher GasPremium.

Change default gas premium to for 10 block inclusion

---

node/modules/storageminer.go

Allow deals to be made with interactive deal flow in local devnet (w/ 4sec block time)
Instead of constant from spec-actors which uses hardcoded epoch time, use one that factors in
possibility of different block time across builds

Use build.BlockDelaySecs for deal start buffer

---

cmd/tvx/codenames.go
cmd/tvx/codenames_test.go
cmd/tvx/exec.go
cmd/tvx/extract.go
conformance/corpus_test.go
conformance/driver.go
conformance/runner.go
go.mod
go.sum

This PR introduces support for running multi-variant vectors. Each variant targets a unique protocol version.
See https://github.com/filecoin-project/test-vectors/pull/178 and https://github.com/filecoin-project/test-vectors/issues/177 for more info on design and rationale.
The entire corpus has been regenerated, and the test-vectors submodule has been updated to point to master.
The tvx tool has been adapted to produce and parse the new version of the schema.

conformance: support multiple protocol versions.

---

api/api_gateway.go
api/apistruct/struct.go
cli/multisig.go
cli/multisig_test.go
cli/paych_test.go
cli/test/mockcli.go
cli/test/multisig.go
cmd/lotus-gateway/api.go
cmd/lotus-gateway/api_test.go
cmd/lotus-gateway/endtoend_test.go
cmd/lotus-gateway/main.go
node/impl/full/chain.go

This PR
- Creates a basic CLI test for msig create & msig inspect
- Adds hooks to run the test
- from CLI with a regular node
- from api-gateway with lite node -> gateway -> full node
Now that the framework is in place, it should be easy to add other CLI commands to the basic msig CLI test to ensure they run in regular and lite mode.

Ensure msig inspect cli works with lotus-lite

---

markets/dealfilter/cli.go
node/builder.go
node/config/def.go
node/modules/dtypes/miner.go
node/modules/storageminer.go

We would like to have custom user filters for retrieval deals, like we have for storage deals.
If a custom filter is set in `Dealmaking.Filter`, use it when deciding on both retrieval deals and storage deals.  The JSON passed to the custom filter will be augmented with `"DealType": <"storage" | "retrieval">` so that the custom filter can distinguish between the two types of deals.
Resolves #4195

Custom filters for retrieval deals

---

node/modules/storageminer.go

When constructing a new stored ask, the `MaxPieceSize` was not properly preserved.
There was leftover code that was inadvertently overwriting the provided `MaxPieceSize` with the default.
Related: https://github.com/filecoin-project/go-fil-markets/pull/438
Resolves #4440, #4458

Don't overwrite previously-configured maxPieceSize for a persisted ask

---

cmd/lotus-shed/main.go
cmd/lotus-shed/sectors.go

Add terminate sectors based on 1475's #4433 implementation in lotus-shed:
-  Moving the cmd to lotus-shed so that miners can use this right away without waiting for fsm changes.
- Note: this should only be used when the miner is 100% sure that they want to terminate the sector on chain and they will be lose the power and pay a big one-time termination penalty for the sectors.
- Only live sectors can be terminated.
- To use, run `./lotus-shed sectors terminate --really-do-it=true sectorNum1 sectorNum2`.
- A message will be sent and after the message is landed on chain, miner can run `lotus-miner sectors status --on-chain-info <terminated sector number>`, and check Expiration Info at the bottom. Both `OnTime` and `Early` are 0 indicates the sector is terminated.

Add a terminate sectors command to lotus-shed

---

cli/client.go
go.mod
go.sum

(also fixes quitting with ^C)
Demo: https://asciinema.org/a/OCihI6YNVv7dbwM5Otd5XEGr1

Miner finder for interactive client deal CLI

---

api/api_full.go
api/apistruct/struct.go
documentation/en/api-methods.md
node/impl/client/client.go

Add api for getting status given a code

---

api/api_full.go
api/apistruct/struct.go
node/impl/full/mpool.go

Pushing messages one by one causes nonce gap when there are many messages, so add this batch api to solve this problem.

add batch api for push messages

---

cmd/lotus-bench/import.go
go.mod
go.sum

Still need a way to extract the metrics for viewing. @Kubuxu any thoughts?

add measure datastore wrapper around bench chain datastore

---

chain/gen/mining.go

https://github.com/filecoin-project/lotus/blob/9c6ee802cc902b39b9a1ae10acac083bd9b31eeb/chain/stmgr/utils.go#L78
delete duplicate code

optimize mining code

---

chain/store/store.go
chain/store/store_test.go

Adds a better test for https://github.com/filecoin-project/lotus/pull/4330 (which is already approved)

Small chain export optimization

---

conformance/driver.go

Seems to not break any vectors rn, but future proof

Fix circ supply default in conformance

---

cmd/lotus-storage-miner/init.go

Fixes https://github.com/filecoin-project/lotus/issues/1536

miner: fix init --create-worker-key

---

chain/messagepool/messagepool.go

Seems there is a race where it is possible that a pushed message disappears if there is a prune before we do the addLocal dance; lock is temporarily relinquished.

make push and addLocal atomic

---

chain/stmgr/utils.go

If a miner is found in the current state, just return nil base info as the miner
cannot mine if he is not found in the lookback.
Resolves https://github.com/filecoin-project/lotus/issues/4324

MinerGetBaseInfo: if miner is not found in lookback, check current

---

api/apistruct/struct.go
build/version.go
extern/sector-storage/faults.go
extern/sector-storage/localworker.go
extern/sector-storage/manager.go
extern/sector-storage/manager_test.go
extern/sector-storage/mock/mock.go
extern/sector-storage/roprov.go
extern/sector-storage/selector_alloc.go
extern/sector-storage/selector_existing.go
extern/sector-storage/stores/filetype.go
extern/sector-storage/stores/index.go
extern/sector-storage/stores/interface.go
extern/sector-storage/stores/local.go
extern/sector-storage/stores/remote.go
storage/wdpost_run.go
storage/wdpost_run_test.go

* We may have multiple sectors with the same size and different proof types, but all these management functions stay the same.
* This simplifies PoSt logic.

Manage sectors by size instead of proof type.

---

chain/gen/mining.go
miner/miner.go

Previously, we'd use the _current_ worker key when signing blocks and computing the VRF. Now, we use the worker key from the correct lookback epoch. This now matches the behavior on the validation side.
Required for (and tested by) https://github.com/filecoin-project/lotus/pull/4513.

Use the correct lookback for the worker key when creating blocks

---

api/test/ccupgrade.go
api/test/deals.go
api/test/mining.go
api/test/paych.go
api/test/test.go
api/test/window_post.go
chain/sync.go

1. Avoid setting global variables multiple times from different tests.
2. Don't skip VRF validation in tests when "insecure post" is enable. VRFs are always calculated, so we might as well test them.

Cleanup test initialization and always validate VRFs in tests

---

cli/wallet.go

Add a `lotus wallet withdraw-market-funds` command:
```
NAME:
lotus wallet withdraw-market-funds - Withdraw funds from the Storage Market Actor
USAGE:
lotus wallet withdraw-market-funds [command options] [amount (FIL) optional, otherwise will withdraw max available]
OPTIONS:
--address value, -a value  Specify address to withdraw funds from, otherwise it will use the default wallet address
--help, -h                 show help (default: false)
```
Returns the message CID if message is sent.
Resolves #4478

Add a market WithdrawBalance CLI

---

cmd/tvx/extract.go
cmd/tvx/extract_many.go
cmd/tvx/main.go
cmd/tvx/simulate.go

This PR introduces a `tvx simulate` command that takes a raw base64-encoded CBOR message, and executes it against the provided epoch (or HEAD), generating a vector and optionally printing a statediff that displays the changes made to the state tree.
It also introduces an `--ignore-sanity-checks` flag on `tvx extract`, requested by @austinabell.
---
Closes https://github.com/filecoin-project/lotus/issues/4476.

tvx simulate command; tvx extract --ignore-sanity-checks

---

api/api_gateway.go
api/apistruct/struct.go
api/test/ccupgrade.go
api/test/deals.go
chain/stmgr/stmgr.go
chain/stmgr/utils.go
cli/client.go
cli/client_test.go
cli/helper.go
cli/test/client.go
cli/test/mockcli.go
cli/test/multisig.go
cli/test/net.go
cli/test/util.go
cli/wallet.go
cmd/lotus-gateway/api.go
cmd/lotus-gateway/api_test.go
cmd/lotus-gateway/endtoend_test.go
markets/storageadapter/client.go
node/builder.go
node/impl/client/client.go
node/impl/full/chain.go
node/impl/full/state.go
node/impl/paych/paych.go
node/modules/rpcstatemanager.go
paychmgr/manager.go

Depends on https://github.com/filecoin-project/lotus/pull/4095
Implements market storage and retrieval clients for lotus "lite" mode
TODO:

lite-mode - market storage and retrieval clients

---

chain/sync.go
miner/miner.go

If block 1 was a null block then blockSet would include genesis which
would lead to us trying to load parent of a genesis block.
Resolves #4317

Fix random test failures

---

storage/wdpost_run.go
storage/wdpost_run_test.go

After the upgrade, we're allowed to use randomness up to the challenge epoch. This safe-guards us against very large reorgs where a miner computes a PoSt very quickly.

Use older randomness for the PoSt commit on specs-actors version 2

---

chain/gen/mining.go
chain/stmgr/utils.go
chain/sub/incoming.go
chain/sync.go

When syncing (via pubsub) from peers that have recently changed their worker key, we may have the wrong version cached (and/or we may have fetched it from the wrong epoch). This could cause us to mis-validate the block in the pubsub validator (either accept/reject it).
This won't cause state mismatches or forks (everything is re-checked later), but could cause nodes to propagate invalid blocks and/or refuse to propagate valid blocks.

Fetch worker key from correct block on sync

---

chain/gen/genesis/miners.go
chain/stmgr/call.go
chain/stmgr/stmgr.go
chain/stmgr/utils.go
chain/vm/syscalls.go
chain/vm/vm.go

Handle worker key changes correctly in runtime

---

chain/wallet/wallet.go

Fixes issue #4283
Try deleting 'trash-f3*' key before backing up to-be-deleted wallet key. Ignore ErrKeyInfoNotFound.

Do not fail wallet delete because of pre-existing trashed key

---

paychmgr/paychget_test.go
paychmgr/simple.go

Fixes https://github.com/filecoin-project/lotus/issues/4585
This PR fixes a race in payment channel manager, when a payment request gets cancelled at the same time as a new request is being processed. I believe it also fixes a flaky test: TestPaychGetMergeAddFundsCtxCancelAll

fix race in paych manager add funds

---

go.mod

Currently, the go.mod has an old version of this dependency. 
For this repo isn't a problem since it has a `replace` directive, but for *any* client `go mod tidy` fails.
Minimal way to reproduce the problem now:
```main.go
package main
import (
"context"
"github.com/filecoin-project/lotus/api/apistruct"
)
func main() {
var api apistruct.FullNodeStruct
_ = api
}
```
Run `go mod tidy`:
```
go: finding module for package github.com/filecoin-project/specs-actors/actors/abi
github.com/jsign/lotusclientest imports
github.com/filecoin-project/lotus/api/apistruct imports
github.com/filecoin-project/go-fil-markets/storagemarket tested by
github.com/filecoin-project/go-fil-markets/storagemarket.test imports
github.com/filecoin-project/go-fil-markets/pieceio imports …
```

update filecoin-ffi in go mod

---

api/api_full.go
api/api_storage.go
api/apistruct/struct.go
cli/client.go
cmd/lotus-storage-miner/market.go
documentation/en/api-methods.md
node/impl/client/client.go
node/impl/storminer.go

Generally improve data transfer UI
- include a cleaned up version of https://github.com/filecoin-project/lotus/pull/4387
- add an option to filter failed data transfers from the list
- add cancel commands for data transfers for client and miner
- the cancel commands are somewhat broken in some cases till https://github.com/filecoin-project/go-data-transfer/pull/107 is merged

Flesh out data transfer features

---

cli/multisig.go

- Show account address of signers
- When a message receiver is a new account, do not lookup method name.
sample updated output
```
Jennifer@jennijuju-3.local:~/filecoin/lotusl msig inspect  t01009
Balance: 0 FIL
Spendable: 0 FIL
Threshold: 2 / 3
Signers:
ID      Address
t01001  t1m2o2btagagiovb6tjhfjailocqrvwzqilp4ib3y
t0100   t3whxa3ume3jrvmvnksuhofioehbowf3q6ma7fq5stytjl4vbebqzeouwsoz22e7nwh3ahjboiq3753zwhavya
t01005  t12hefpm6ov7jocmz3aqoc66lyxsl23odngq3raiy
Transactions:  1
ID      State    Approvals  To                                         Value   Method                          Params
0       pending  1          t1mg6ywcbkj4lupnkgskipw3dpwr22eujkwulr2ji  0 FIL   new address, unknown method(3)  a703
```
Resolves #4369

Updated msig inspect:

---

cli/paych_test.go
cli/test/client.go
cli/test/mockcli.go
cli/test/multisig.go
cli/test/net.go

Just takes care of some tech-debt, no changes to non-test code.
This PR removes some duplicate code from the payment channels CLI tests.

refactor: share code between CLI tests

---

storage/wdpost_run.go

WindowPoStScheduler will record the worker key once it starts, and never change it. When we change the worker, it will cause an error in `GasEstimateMessageGas` because the old worker key is not in the `ValidateImmediateCaller` list, here simply update s.worker and msg.From should work around this problem

worker key should change when set sender found key not equal with the value on chain

---

chain/actors/builtin/miner/miner.go
chain/actors/builtin/miner/v0.go
chain/actors/builtin/miner/v2.go

Easier comparison of MinerInfo structs
Perform a comparison by casting the interface to its underlying structure and comparing Info cids similar to what is done in `DeadlinesChanged`.

polish: add Equals method to MinerInfo shim
