filecoin-project/lotus

cli/client.go
While `ClientDealSize` is exposed via the JSON API, there are some users using the CLI that need this information to create deals (without using interactive deal creation).
```
NAME:
lotus client deal-size - Calculate size of deal piece
USAGE:
lotus client deal-size [command options] <cid>
```
```
./lotus client deal-size bafykbzaceclbis4au7xmwecpf6k2hy4uv4lpdfkm5tsn2syacn4snm2hzpdnk 
Deal sizes for data cid ...m2hzpdnk
Piece Size: 134217728
Payload Size: 101920082
```
=> Expose ClientDealSize via CLI

extern/sector-storage/sched_resources.go
GPU tracking currently is a bit broken on master because each subsequently scheduled task blindly overwrites the flag, irrelevant of what its current value is. E.g.:
- Schedule C2, mark GPU as used
- Schedule PC1, mark GPU as unused (blindly overwrite)
- Schedule C2, mark GPU as used (double usage allocated)
The second C2 should not have been permitted to be allocated onto the same GPU, but since PC1 blindly overwritten the flag, a second C2 becomes schedulable. Repeat until the GPU is overloaded and starts going OOM (PC2 cannot recover from it).
The fix is that tasks should only set the flag if they themselves requested the GPU (and have been granted). If they didn't request the GPU, they should most definitely not set the GPU as unused.
---
Funky caveat: On my system at least, …
=> extern/sector-storage: fix GPU usage overwrite bug

extern/sector-storage/manager_calltracker.go, extern/sector-storage/manager_test.go, extern/sector-storage/testworker_test.go
Fixes an issue where:
* We were running some task on the worker
* Manager would restart
* Worker would deliver the result
* Manager would start waiting for the result after it was deliver
* The task would hang ~forever
Made pretty painful by the fact that it's easy to trigger when we're restarting with a worker which is running Commit2 and has sector data on it:
* Worker is running C2
* Manager restarts
* Manager calls C1, hangs because the worker needs to finish C2
* Worker finishes C2, returns to manager
* C1 then runs on the worker, returns just fine
* C2 hangs due to this bug
=> sectorstorage: Fix manager restart edge-case

extern/storage-sealing/states_sealing.go
When we recompute PC1 after it has been precommitted, we'd fall into a loop between GetTicket and PreCommit1 states:
```
...
7992.	2020-10-29 09:42:16 +0100 CET:	[event;sealing.SectorTicket]	{"User":{"TicketValue":"JgPZnq+lJqH/mw640Jw9xRn2IeL9ZT59/fZsreFjddI=","TicketEpoch":182408}}
7993.	2020-10-29 09:42:16 +0100 CET:	[event;sealing.SectorOldTicket]	{"User":{}}
7994.	2020-10-29 09:42:16 +0100 CET:	[event;sealing.SectorTicket]	{"User":{"TicketValue":"JgPZnq+lJqH/mw640Jw9xRn2IeL9ZT59/fZsreFjddI=","TicketEpoch":182408}}
7995.	2020-10-29 09:42:16 +0100 CET:	[event;sealing.SectorOldTicket]	{"User":{}}
7996.	2020-10-29 09:42:16 +0100 CET:	[event;sealing.SectorTicket]	{"User":{"TicketValue":"JgPZnq+lJqH/mw640Jw9xRn2IeL9ZT59/fZsreFjddI=","TicketEpoch":182408}}
7997.	2020-10-29 09:42:16 +0100 …
```
=> storagefsm: Fix GetTicket loop when the sector is already precommitted

lib/ipfsbstore/ipfsbstore.go, node/builder.go, node/config/def.go, node/modules/ipfsclient.go
We have a particular deployment in which the IPFS node connected to Lotus should discover data using other IPFS nodes connected in the same network.
Make the offline mode in the underlying blockstore configurable, keeping the offline default value being the same as before.
Correct configuration for this:
```
...
[Client]
UseIpfs = true
IpfsOnlineMode = true
...
```
=> make IPFS online mode configurable

cmd/lotus-shed/datastore.go, node/repo/fsrepo_ds.go
It should significntly size of the LSM index, and thus increase the
performance with bigger datastores
=> Reduce badger ValueTreshold to 128

storage/wdpost_run.go
If we have a bunch of corrupted but not missing sectors on disk, we may need to
retry many times before we get a proof to pass. Simply giving up doesn't help anyone.
=> keep retrying the proof until we run out of sectors to skip

chain/actors/builtin/power/diff.go, chain/actors/builtin/power/power.go, chain/actors/builtin/power/v0.go, chain/actors/builtin/power/v2.go
Motivated by inspection performed in Visor.
=> polish: add ClaimsChanged and DiffClaims method to power shim

chain/events/events_called.go, chain/events/events_test.go, chain/events/utils.go, markets/storageadapter/client.go, markets/storageadapter/provider.go, paychmgr/settler/settler.go
A couple of simplifications to the chain event Called API:
1. The match function returns three parameters:
- `match once`
if true: if there are multiple listeners registered to listen for a particular message, only callback the first one
- `matched`
true if there was a match
- `error`
In practice, everywhere in the code that `Called` is used, `match once` is always false. I can't think of a reason why you would only want the first registered listener to match a method to get a callback and ignore the other listeners, so this PR removes the `match once` return value.
2. `messageEvents` has a map `map[triggerID][]MsgMatchFunc`
But there is only ever one element in the array. So just map directly to a MsgMatchFunc instead of an array:
`map[triggerID]MsgMatchFunc`
=> Simplify chain event Called API

chain/events/state/mock/api.go, chain/events/state/mock/state.go, chain/events/state/mock/tipset.go, chain/events/state/predicates_test.go, markets/storageadapter/client.go, markets/storageadapter/dealstatematcher.go, markets/storageadapter/dealstatematcher_test.go, markets/storageadapter/provider.go
Fixes caching issue with https://github.com/filecoin-project/lotus/pull/4517
=> Cache deal states for most recent old/new tipset

cmd/lotus-shed/election.go, cmd/lotus-shed/main.go
```bash
> source scripts/dev/runAPI.bash
> runAPI MinerGetBaseInfo '["t02388", 163405, [{"/": "'"$(./lotus chain head | head -1)"'"}]]' | jq .
{
"jsonrpc": "2.0",
"result": {
"MinerPower": "14156212207616",
"NetworkPower": "681826195678953472",
"Sectors": [
{
"SealProof": 3,
"SectorNumber": 179,
"SealedCID": {
"/": "bagboea4b5abcas5opeafvoqljrxfwnfbo5amnyhg6cwzyt37rch5z4not3stserq"
}
}
],
"WorkerKey": "f3rutut57upcbuzyq6si2xajhvr7d4u7exd7knqop4t6w3bpl57uqpdnfs72t2tyaz7vivwdvyc3bzvq2i37ma",
"SectorSize": 34359738368,
"PrevBeaconEntry": {
"Round": 259249,
"Data": "hQ687JZRrGV4U6QMrzac7I3evTOGnXAIY3bZagH4TLZI00+3KkclftPDtVoPbyEvFAwV474o/0G+EzoSnHf4I6Uh+uLupLBH0QVB5VdlHf0RyaBO8iYPHlNF5Hrmr0+6"
},
"BeaconEntries": null,
"EligibleForMining": true
},
"id": 2
}
> ./lotus-shed election run-dummy …
```
=> Add election run-dummy command

cmd/lotus-shed/main.go, cmd/lotus-shed/rpc.go
Example:
```
$ lotus-shed rpc
Daemon:  1.1.2+git.18baa91e3.dirty+api0.17.0
Local: lotus-shed version 1.1.2
Usage: > Method [Param1, Param2, ...]
> StateCirculatingSupply [null]
{"jsonrpc":"2.0","result":"26616805417761619647691235","id":0}
> 
```
=> sched: Interactive RPC Shell

.circleci/config.yml, .gitmodules, go.mod
- Switches `blst` to the `v0.2.0` release, to ensure it matches the version used by `blstrs` (the recursive dependency integrating `blst` into `filecoin-ffi`
- Updates to use the `filecoin-ffi` with the latest optimizations for verification and the blst backend
You can enable the `blst` backend when building from source using `FFI_USE_BLST=1`
Depends on 
Fixes #4678
=> feat: integrate new optional blst backend and verification optimizations from proofs

cmd/lotus/daemon.go, cmd/lotus/rpc.go, go.mod, node/builder.go
Some components like go-ds-measure, go-ipfs-blockstore and go-bitswap expose metrics via ipfs/go-metrics-interface, but Lotus never injects the Prometheus exporter (ipfs/go-metrics-prometheus). Therefore, those metrics never surface in instrumentation.
Instead, Lotus uses OpenCensus directly.
This commit injects the Prometheus exporter for go-metrics-interface, and instructs the OpenCensus Prometheus exporter to use the DefaultRegistry.
This has the effect of exposing blending the metrics of both metrics libraries.
With this patch, the datastore, cache utilisation, and bitswap metrics are now exported via the /debug/metrics endpoint.
This commit also fixes an issue where the metrics scope was empty, making go-metrics-interface default to "<no-scope>". Angle brackets are inadmissible …
=> fix metrics wiring.

go.mod, go.sum
We've seen heaving memory usage during large data transfers. This update fixes them on both sides.
For a more in-depth explanation of the fixes see: https://github.com/filecoin-project/go-data-transfer/pull/109
The implementation is in upstream packages and there are no changes here
Note: The PRs in Data transfer are not merged and I'd like to get them in master & a tagged release before this goes in LOTUS master.
However, this branch should be adequate for testing by folks who want to see if the issue is resolved.
Resolves #4121 #4468 and associated problems on the client side as well
=> Fix memory leaks in data transfer

Makefile, cmd/lotus-stats/chain.dashboard.json, cmd/lotus-stats/docker-compose.yml, cmd/lotus-stats/env.stats, cmd/lotus-stats/main.go, cmd/lotus-stats/setup.bash
This updates lotus stats to use urfave instead of the golang flags package. This brings with it some common features from other lotus tools such as the use of the `FULLNODE_API_INFO` env and other parts of the lotus cli package.
This also includes the latest dashboard.
=> Update lotus-stats with a richer cli

cmd/lotus-shed/sectors.go
- Usage example: `./lotus-shed sectors termation-estimate 5 8 10`.
Resolves #4616
=> Add `termination-estimate` to get an estimation for how much a termination penalty will be

chain/actors/builtin/multisig/diff.go, chain/actors/builtin/multisig/state.go, chain/actors/builtin/multisig/state0.go, chain/actors/builtin/multisig/state2.go
add diffing logic for multisig actors pending transcription HAMT
=> polish: add msig pendingtxn diffing and comp

build/params_2k.go
More evidence that we need to clean up our fork height logic, but kumquat should run in devnets (it basically improves v2 actors which are already running in devnets)
=> Run kumquat upgrade on devnets

chain/gen/gen.go, chain/gen/genesis/genesis.go, chain/store/index_test.go, chain/store/store.go, chain/store/store_test.go, cmd/lotus-bench/import.go, cmd/lotus-shed/balances.go, cmd/lotus-shed/export.go, cmd/lotus-shed/genesis-verify.go, cmd/lotus-shed/pruning.go, cmd/lotus/daemon.go, conformance/driver.go, lib/blockstore/fallbackstore.go, lib/bufbstore/buf_bstore.go, node/builder.go, node/modules/chain.go, node/modules/dtypes/storage.go
A bit messy because there's a circular dep between chainblockstore/bitswap and another one between bitswap/network/chainstore, but running this on my node I'm not seeing any warnings coming from this, which is expected.
=> Optional chain Bitswap

api/api_full.go, chain/store/store.go, chain/sync_manager.go, chain/sync_manager_test.go, chain/syncstate.go, cli/sync.go, node/impl/full/sync.go, node/test/builder.go
~Note: hasn't been yet tested in the live network.~
It is currently being tested in the live network.
=> rewrite sync manager

extern/sector-storage/worker_local.go
=> optimize code replace strings with constants

lib/peermgr/peermgr.go
If the connection of the first bootstrap peer times out, the others cannot be connected.
This can solve this problem and make the connection faster.
=> async connect to bootstrappers

extern/sector-storage/sched_worker.go, extern/sector-storage/stores/local.go
=> Fix scheduler lockups after storage is freed

cmd/lotus-storage-miner/sectors.go
activeSet should be sset
https://github.com/filecoin-project/lotus/blob/3ec25cbece63d929a8ea06b3572e429393e47f54/cmd/lotus-storage-miner/sectors.go#L213-L215
=> cmd sectors commitIDs len debug

cmd/lotus-storage-miner/sealing.go, extern/sector-storage/cbor_gen.go, extern/sector-storage/manager.go, extern/sector-storage/manager_calltracker.go, extern/sector-storage/stats.go, extern/sector-storage/storiface/worker.go
This PR adds a bunch of info to work metadata, also fixes one edge-case around returning abandoned tasks (part 1/2 of dealing with the ret-wait issues)
TODO:
(part 2 will be an 'abort' command to cleanup ret-wait tasks which can't really be cleaned up automatically, after things like nuking worker directories)
=> storage: Track worker hostnames with work

go.mod, go.sum
Let's get https://github.com/filecoin-project/go-address/pull/12 in sooner rather than later
=> Update to latest go-address

paychmgr/simple.go
This doesn't cause a problem in practice but did cause some test flakiness
Fixes https://github.com/filecoin-project/lotus/issues/4800
=> Fix race in paych manager when req context is cancelled

chain/market/fundmanager_test.go
Adds a test to verify that https://github.com/filecoin-project/lotus/pull/4808 fixes the scenario that caused the panic.
I ran this test against lotus before and after applying #4808 to verify that
- before applying #4808 the test triggers the panic
- after applying #4808 the test passes
=> test for FundManager panic to ensure it is fixed

node/modules/client.go, node/modules/storageminer.go
Don't crash on startup if funds migration fails.
I'm not 100% sure this is what we want to do. It may cause some in-progress deals to fail, but is probably better than crashing.
_Edit: The correct solution here is probably for the migration to subtract the amount of completed / failed deals from the reserved amount_
=> Fix: dont crash on startup if funds migration fails

cmd/lotus-storage-miner/storage.go
Useful for checking if we keep data in places where it shouldn't be kept
=> miner: Storage list sectors command

miner/miner.go, miner/warmup.go
Should address https://github.com/filecoin-project/rust-fil-proofs/issues/1355
=> miner: Winning PoSt Warmup

chain/exchange/server.go, chain/messagepool/messagepool.go, chain/store/store.go, chain/sub/incoming.go, chain/sync.go, node/hello/hello.go
Makes default logs ~80% quieter.
Mostly just moving logs which aren't useful for normal users to debug
=> Make some logs quieter

chain/sync_manager.go, node/hello/hello.go
=> drop a few logs down to debug

chain/store/store.go, node/modules/services.go, node/test/builder.go
Reinstates the code that got reverted, but with a couple of improvements:
- we only delay subscription to the messages topic, so that we avoid the debacle with failed syncing.
- we wait to be within 10 epochs before subscribing instead of the overly aggressive 1.
Also moves the subscription code in blocks after the validator registration, which  is the correct order of things.
Please test in your nodes!
=> delayed pubsub subscribe for messages topic

cli/chain.go
=> add chain base64 decode params

go.mod, go.sum
In rare cases, if bitswap receives a message before it finishes starting up, it
could panic. This release fixes that.
=> chore(dep): update bitswap to fix an initialization race that could panic

node/modules/testing/genesis.go
When running the daemon for a devnet it generates a genesis file.
But if there is already a genesis file from a previous run the new genesis file is corrupted, preventing restarts.
This PR truncates the genesis file before generation.
=> Truncate genesis file before generating

build/params_2k.go, build/params_mainnet.go, build/params_testground.go, chain/actors/policy/policy.go, chain/actors/policy/policy_test.go, chain/stmgr/forks.go, chain/stmgr/utils.go, chain/sync.go, go.mod, go.sum
Introduces upgrade logic to fix filecoin-project/lotus#4027
=> Don't use terminated sectors for winning PoSt

chain/actors/builtin/init/diff.go, chain/actors/builtin/init/init.go, chain/actors/builtin/init/v0.go, chain/actors/builtin/init/v2.go, chain/events/state/predicates.go
Replace init actor address map diffing with generic adt diffing logics
Optimize other diffing methods by calling Diff* iff adt CID's are different.
=> Fix init actor address map diffing

chain/actors/params.go, chain/vm/invoker.go, chain/vm/invoker_test.go, chain/vm/runtime.go, chain/vm/vm.go
Supersedes all of #3478 and #3730, and most of #3267
=> Small consensus-critical fixes in 1.2.0

build/version.go, documentation/en/api-methods-miner.md, documentation/en/api-methods-worker.md, documentation/en/api-methods.md
I assume this is safe to do, if there's any reason why it isn't close the PR :P
"Fixes" #4738
=> Bump API versions to 1.0.0

go.mod, go.sum, node/modules/client.go, node/modules/storageminer.go
fix #4856 
See corresponding dependent PR -- https://github.com/filecoin-project/go-data-transfer/pull/118
The only substantive change here is that we need to setup a directory in which to place these cid recordings, setup us as a "data-transfer" subdirectory under the repo path.
=> Fix cid recording issue

chain/stmgr/stmgr.go
There was an accounting mistake in the vesting table. It was reported but not fixed because of timeline and fixing it earlier will mean a spike in collateral for miners. This PR upgrades the vesting table to more closely match the actual multisig vesting.
Fixes #4660
=> Modify vesting schedule post-calico

api/apistruct/struct.go, api/docgen/docgen.go, documentation/en/api-methods-miner.md, extern/sector-storage/manager.go, extern/sector-storage/manager_calltracker.go, extern/sector-storage/mock/mock.go, extern/sector-storage/stores/local.go, extern/sector-storage/storiface/worker.go, extern/sector-storage/testworker_test.go, extern/sector-storage/worker_local.go
We're bumping API versions in 1.2.0 already, so getting this in now is nice because we can avoid breaking worker APIs again
This is part 1 of 2 of handling things like failing to allocate storage more gracefully. Part 2 will be handling those errors at the scheduler level, just returning tasks which got Temp errors to the scheduler instead of failing them
=> Add error codes to worker return 

chain/sub/incoming.go
1MB - some space for pubsub metadata; we should not exceed it in practice, but this adds a sanity check to make sure we don't clog the receiver ends in pubsub.
=> add sanity check for maximum block size

extern/storage-sealing/fsm.go, extern/storage-sealing/states_failed.go
If we don't do this, we can end up noticing things like deals being expired, and throw the sector away even though the sector got committed just fine
=> Check (pre)commit receipt before other checks in failed states

chain/messagepool/selection.go
=> cap maximum number of messages per block in selection

build/params_mainnet.go
Should go into `release/v1.2.0`. First upgrade epoch is midnight UTC between the 24th and 25th (4 PM PST, and 8 AM China). Second upgrade is 60 hours after first upgrade.
=> Set Calico epoch

cmd/lotus-storage-miner/actor.go, storage/addresses.go, storage/miner.go, storage/wdpost_run.go, storage/wdpost_run_test.go
=> Set lower feecap on PoSt messages with low balance

cmd/tvx/extract.go
Unfortunately `ChainGetMessage` returns a `*types.Message`, which in the case of secp messages is lacking the signature. The signature is part of the input to calculate the CID on secp messages. Therefore, calling `.Cid()` on the result of `ChainGetMessage` for this kind of message will result in an incorrect CID.
tvx was relying on that call to return the correct CID. Since this is not the case (and this is a footgun that needs to be corrected, ideally together with the `*types.{,Signed}Message` duality mess), I'm replacing the comparison.
---
cc @austinabell
=> tvx extract: make it work with secp messages.

chain/store/store.go
print multiple blocks from miner
=> print multiple blocks from miner cid

node/modules/storageminer.go
the code in `NewStorageAsk` seems to be unuseful, remove to keep the code clean. btw the second  `err != nil` always be true, there is no need to judge this condition.
=> just return storedask.NewStoredAsk to reduce unuseful code

cmd/lotus-seed/main.go
We don't currently have any way to start a network with a later version, so pre-sealing should just use version0. I think. Maybe make this configable?
=> Use version0 when pre-sealing

chain/sub/incoming.go
tag.Insert 
func (m *Map) insert(k Key, v string, md metadatas) {
if _, ok := m.m[k]; ok {
return
}
m.m[k] = tagContent{value: v, m: md}
}
should be：
func (m *Map) upsert(k Key, v string, md metadatas) {
m.m[k] = tagContent{value: v, m: md}
}
https://github.com/filecoin-project/lotus/blob/dc3d17c9eae5b9acfe587541d0e6ef3245537a33/chain/sub/incoming.go#L605-L611
=> bug:replace with func recordFailure

chain/exchange/peer_tracker.go, lib/peermgr/peermgr.go
=> emit events for peer disconnections and act upon them in the blocksync tracker

chain/messagepool/messagepool.go
=> Downgrade duplicate nonce logs to debug

markets/loggers/loggers.go, node/modules/client.go
Add debug logging for data transfer events.
This is useful for debugging issues with deals.
=> add data transfer logging

cli/state.go
This PR aims to fix a panic bug when check nonexistent sectors with the following command:
`lotus state sector [miner address] [sector number]`
=> fix get sector bug

extern/storage-sealing/states_sealing.go
=> storagefsm: Fix expired ticket retry loop

testplans/graphsync/go.mod, testplans/graphsync/go.sum, testplans/graphsync/main.go
This PR is updating the `graphsync` testplan:
1. It adds `.sec` to the tag name, which is used as a `unit` for the `y-axis` when we visualise stats.
2. It humanizes the tags / params for the test, so that they are more meaningful when visualising stats.
=> add .sec scale to measurements; humanize for metric tags

go.mod, go.sum, node/builder.go, node/config/def.go, node/modules/graphsync.go
Pick a more sensible default value for number of simultaneous graphsync requests and allow configuration of the number of simultaneous requests via config file
re #4946
require merge of https://github.com/ipfs/go-graphsync/pull/122
=> Configure simultaneous requests

go.mod, go.sum
Includes https://github.com/filecoin-project/go-jsonrpc/pull/40
Fixes #4981
=> Update go-jsonrpc to v0.1.2

api/api_gateway.go, api/apistruct/struct.go, api/test/deals.go, cli/test/client.go, cmd/lotus-gateway/api.go, documentation/en/api-methods-miner.md, go.mod, go.sum, markets/storageadapter/client.go, markets/storageadapter/ondealsectorcommitted.go, markets/storageadapter/ondealsectorcommitted_test.go, markets/storageadapter/provider.go, node/impl/full/state.go
Depends on https://github.com/filecoin-project/go-fil-markets/pull/453
Fixes https://github.com/filecoin-project/lotus/issues/4900
TODO:
=> markets - separate watching for pre-commit from prove-commit

cmd/lotus-storage-miner/info.go, extern/storage-sealing/fsm.go, extern/storage-sealing/fsm_test.go, extern/storage-sealing/sector_state.go
This fixes the issue where it's impossible to remove FailedUnrecoverable sectors
Fixes #4988
Fixes #4965
=> storagefsm: Add missing planners

cmd/lotus-shed/balances.go
=> add a tooling to make filecoin accounting a little easier

cli/state.go
This is miner info now, it really makes us confused.
=> fix: start a new line in print miner-info to avoid ambiguous display

chain/store/store.go, node/impl/full/wallet.go
It is a bit of a unortodox fix but it works.
See the comment in chainstore.
=> Fix chainstore tipset leak

cmd/lotus-shed/ledger.go
Print message and signature including secpk byte to try validating ledger signature with `lotus wallet verify`
=> Ledger signature verification

cli/client.go
Now:
```
--verified-deal              indicate that the deal counts towards verified client total (default: true if client is verified, false otherwise)
```
Fixes #5073
=> Fix helptext for verified-deal default in client deal

api/api_worker.go, api/apistruct/struct.go, api/docgen/docgen.go, cmd/lotus-seal-worker/info.go, cmd/lotus-seal-worker/main.go, cmd/lotus-seal-worker/tasks.go, documentation/en/api-methods-worker.md, extern/sector-storage/worker_local.go, go.sum
=> worker: Support setting task types at runtime

cli/client.go, cli/test/client.go, cmd/lotus-storage-miner/market.go, go.mod, go.sum
Imports https://github.com/filecoin-project/go-fil-markets/pull/457
When the user cancels a data transfer using the CLI, the local node
1. sends a "cancel" message to the remote node
2. cancels the transfer locally
Before, if sending a "cancel" message to the remote node failed, the transfer wouldn't be cancelled locally.
Now it will be, and the deal will be failed.
This PR also adds a `cancel-timeout` parameter to both `lotus client cancel-transfer` and `lotus-miner data-transfers cancel` (by default 5s)
=> Cancel transfer cancels storage deal

api/test/ccupgrade.go, api/test/deals.go, api/test/mining.go, chain/stmgr/utils.go, cli/test/client.go, cmd/lotus-gateway/endtoend_test.go, cmd/lotus-storage-miner/allinfo_test.go, markets/storageadapter/ondealsectorcommitted.go, markets/storageadapter/ondealsectorcommitted_test.go, node/node_test.go
Fixes https://github.com/filecoin-project/lotus/issues/4990
When a deal is terminated by the miner, the client can get stuck in `StorageDealSealing`.
This PR adds functionality to the functions that wait for pre-commit and prove-commit such that they will callback with an error if the chain reaches the proposed start epoch for the deal without the deal being activated.
Fixes https://github.com/filecoin-project/lotus/issues/4977
Provides a better error message for when the deal is not found.
Old: "deal 12345 not found"
New: "deal 12345 not found - deal may not have completed sealing before deal proposal start epoch, or deal may have been slashed"
=> Error out deals that are not activated by proposed deal start epoch

chain/types/fil.go, chain/types/fil_test.go, cmd/lotus-storage-miner/info.go
=> miner info cli improvements

api/api_storage.go, api/apistruct/struct.go, cmd/lotus-storage-miner/proving.go, documentation/en/api-methods-miner.md, extern/sector-storage/faults.go, extern/sector-storage/mock/mock.go, extern/sector-storage/storiface/ffi.go, node/impl/storminer.go, storage/wdpost_run.go, storage/wdpost_run_test.go
Adds a new flag to the proving check command which makes it generate a vanilla proof for each sector in a deadline (a.k.a 'actually check some data mode')
```
$ lotus-miner proving check --slow 1
deadline  partition  sector  status
1         0          496     good
1         0          793     good
1         0          88      good
1         0          111     good
1         0          197     good
1         0          269     good
1         0          707     good
1         0          751     good
1         0          122     good
1         0          141     good
1         0          244     good
1         0          590     good
```
=> miner: Add slow mode to proving check

build/params_mainnet.go, chain/sync_manager.go
This is really annoying to hit and have no information when `lotus sync status` just returns nothing. Ideally a message should be printed when this command is ran and there aren't enough peers. But at least a debug message will make it possible to track down for people.
```
$ lotus lotus sync status
sync status:
```
=> sync: log a message when there aren't enough peers

api/api_storage.go, api/apistruct/struct.go, cmd/lotus-storage-miner/actor.go, documentation/en/api-methods-miner.md, extern/storage-sealing/sealing.go, extern/storage-sealing/states_sealing.go, node/builder.go, node/config/def.go, node/impl/storminer.go, node/modules/storageminer.go, storage/addresses.go, storage/miner.go, storage/wdpost_run.go, storage/wdpost_run_test.go, storage/wdpost_sched.go
Works in pond
```
[magik6k@nexus go-lotus]$ ./lotus-miner actor control list
name       ID      key           use        balance                         
owner      t0100   t3qjeopnj...  other      4999939.999818471486715073 FIL  
worker     t0100   t3qjeopnj...  other      4999939.999818471486715073 FIL  
control-0  t01003  t1jmtyeyi...  post       19.999968525034269047 FIL       
control-1  t01002  t1ssrtzxf...  commit     19.999995140976892322 FIL       
control-2  t01001  t1yqcbo2a...  precommit  19.999998703067058983 FIL
```
=> miner: Control address config for (pre)commits

api/api_full.go, api/apistruct/struct.go, cli/wallet.go, documentation/en/api-methods.md, node/impl/market/market.go
Use the [FundManager's Withdraw](https://github.com/filecoin-project/lotus/blob/b13226bc2f8a0233b3beb9bd18ab266547bc29c7/chain/market/fundmanager.go#L128-L130) for the CLI command, `wallet market withdraw`.  This will take into account funds reserved for in-progress deals.  Also expose this FundManager method in the API.
Resolves #5100
=> Use FundManager to withdraw funds, add MarketWithdraw API

cmd/lotus-shed/cid.go
add encoding flag
add abi Cid   should be see it
./lotus-shed cid id hlaxMCqLZuSYNEy7ESmdgFEzgVBAmtCq/qE8jFGFm7IAceSignvaJbnUc7YCKrm+sRyfpQ8TFmmYu9fzkUGXaC6PMlztJoip4/1TCIHPq+2xMlCd6FGKKjP2G3LkViS9FChx5MMcLFl+KlzyBWTe59gbLFTekL5fozXbkxjPuZ1eN/lrHF/2Qak8HHDbbjgAq/fzH5Y6eKdm22720+rMDMhoiCYGT8Cq9EeXv2NE+vPFGvxNrldCaGsPcNM2KLtaufXRUfo3Fqyn1R6/L1QXQBH0WTci8634mFkSB/aBl3xNIimSuRIRBi4eZQCp8SIusQfdnsXEp+K0eTsRJIpn70cBZWeOejpThx6YMvx3fFro5uNuDRWH9oZ7uNiVE6cNA/YKptoCcj+AfH9DmKreGsi1j9tbW7KApitT978nspSACw0FKtlO93itw4ozgiUIgIVjOGxQRjE82v0VQO9naIkIUUEwPdSKZZKIsZiAWEwMH+zQLauNBp8zBHUI3gdsqgqPn9dK/bdAVyHCXG/CPjcoHE7O0mO+0FmV4rnl1WSLMpSjPXXONzZ6w9lqTRhZo3FCgxJgYMwePYKXdKDLeQBENKjrx4OlMSSQXKDn/q0SlVjowIOXfF6EM6ib6i2ODXH8dawasNMfq+x5nFwwfiOgsYGA1UyEr+WGk1L1l3AkUI4UoQV9RTeiWjWqdiMptignGTZ9M3ApRTEkC/OW+bv1szc …
=> Feat shed cid

chain/events/events.go
It was possible for NewEvents to never return, blocked on waiting for a WaitGroup to be done.
The call to Done was in a goroutine that could exit before reaching the Done call.
Replace the WaitGroup with a channel that is closed to signal that initialisation is complete.
Also, while we are waiting on the channel, wait on the context so we can exit clealy if the
context is canceled.
=> fix(events): avoid potential hang when starting event listener

chain/messagepool/messagepool.go
This makes sure the message is published and persisted for republishing.
We might want to consider an extra option to _not_ persist/republish the message, but this will fix the immediate issue which is that PushUntrusted is flat out broken.
=> fix PushUntrusted publishing -- the message is local

chain/sub/incoming.go, metrics/metrics.go
This PR introduces a metric for delayed blocks, with per-miner tags, and a histogram view so as to gather more data going forward to analyse what appear to be block propagation issues, e.g. https://github.com/filecoin-project/lotus/issues/5128.
=> add metrics for delayed blocks.

cli/mpool.go
=> add mpoolpending from to filter

build/params_2k.go, build/params_mainnet.go, build/params_testground.go, chain/vm/burn.go, chain/vm/burn_test.go, chain/vm/vm.go
Implements https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0009.md
While over-estimation fees and miner tips are still paid, gas is no longer burnt
for direct, successful window PoSt messages.
Usually, gas is burnt to prevent an attacker from spamming the network and to
allow clients to "price" messages (using the base fee cap) based on how urgently
they need them to be processed. However:
1. Window PoSt is already a "proof of work".
2. Miners need to submit WindowedPoSts on-time so all window post messages are urgent.
3. Work is already under way to move window post verification off-chain (making
it effectively free). This change simply introduces the "free" part a bit earlier.
Upgrade epoch set for Monday, Dec 21st, 18:00 PST.
=> Disable gas burning for window post messages

chain/sync.go
In `syncFork`, we currently only apply `ForkLengthThreshold` to the tipsets being fetched for the forked chain (by means of `GetBlocks`, if we walk back the fork chain without finding a common ancestor `syncFork` will fail). We do not apply the threshold for our synced chain, that is, the tipsets that would be "walked back" if the fork is selected as our new head.
This fix introduces a variable (`forkLengthInHead`) to track the tipsets walked back from our synced head to find the common ancestor with the fork. Before we allowed to freely walk back our chain (`nts.Parents()`) to match the next tipset height in the fork chain being traversed (to perform the common ancestor check).
We left the previous check in place for the fork chain (in the `GetBlocks` call) to minimize changes at this …
=> fix(sync): enforce ForkLengthThreshold for synced chain

extern/sector-storage/mock/mock.go
This is an old improvement spotted by @arajasek  when we were trying to figure out the cause of this panic:
```
2020-12-16T10:18:09.309-0300    INFO    markets loggers/loggers.go:25   retrieval event {"name": "ClientEventOpen", "deal ID": "0", "state": "DealStatusNew", "message": ""}
2020-12-16T10:18:09.313-0300    WARN    graphsync_network       network/libp2p_impl.go:65       error setting deadline: set pipe: deadline not supported
2020-12-16T10:18:09.314-0300    INFO    markets loggers/loggers.go:25   retrieval event {"name": "ClientEventDealProposed", "deal ID": "0", "state": "DealStatusWaitForAcceptance", "message": ""}
2020-12-16T10:18:09.315-0300    WARN    graphsync_network       network/libp2p_impl.go:79       error resetting deadline: set pipe: deadline not supported …
```
=> sector-storage/mock: improve mocked readpiece

cmd/tvx/exec.go, cmd/tvx/extract.go, cmd/tvx/extract_message.go, cmd/tvx/extract_tipset.go, cmd/tvx/main.go, cmd/tvx/simulate.go, cmd/tvx/stores.go, conformance/corpus_test.go, conformance/driver.go, conformance/runner.go
- ability to extract a tipset range into individual vectors.
- ability to extract a tipset range and squash into a single multi-tipset vector.
- mark statediff output deterministically, so it can be extracted by tooling.
- ability to execute callbacks between tipsets in the driver.
- implement save-balances callback.
---
This was used to validate the Claus fork introduced in https://github.com/filecoin-project/lotus/pull/5230.
=> tvx extract: more tipset extraction goodness.

cli/mpool.go
Flag usages for cmd `lotus mpool replace` are unclear or incorrect.
This PR aims to clarify them so that users of this cmd can more easily fill up the arguments.
=> correct flag usages for replace cmd

chain/exchange/server.go
**Description**
Chainxchg is slow. Requests with depth >3 are timed out (60 seconds by default). High CPU usage on server side.
We profiled chainxchg methods and found a bottleneck.
**Problem**
From profiling we found that the longest operation is response writing.
Response is marshalled by `MarshalCBOR` directly to network stream.
`MarshalCBOR` makes a lot of small writes with average size of 1 byte (because it writes each CBOR header separately).
Each of these writes is treated like network packet.
Each packet is encrypted and wrapped by underlying security and multiplexing protocols, which adds overhead to packet size.
A lot of small writes with large overhead are causing timeouts.
**Solution**
Buffered writes.
With this patch we could make requests with larger depth (e.g. 100) without …
=> Chainxchg write response timeout

cli/client.go, cmd/lotus-storage-miner/market.go
=> add verbose for list transfers

cmd/lotus-bench/main.go
add some environment variable print. Because they affect bench result.
=> add bench env print

api/api_full.go, api/apistruct/struct.go, cli/wallet.go, documentation/en/api-methods.md, node/impl/market/market.go
Fixes https://github.com/filecoin-project/lotus/issues/5125
New CLI command to add funds to the Storage Market Actor:
`./lotus wallet market add 0.05`
=> feat: lotus wallet market add (adds funds to storage market actor)

cli/state.go
when use lotus state call method, in lotus/cli/state.go 1620 line, the paramObj needs struct type not a ptr type,if use a ptr type, the program will panic in line 1621(paramObj.NumField())
=> lotus state call will panic

api/api_full.go, api/apistruct/struct.go, chain/market/fundmanager.go, cli/client.go, cli/wallet.go, documentation/en/api-methods.md, node/impl/market/market.go
Depends on https://github.com/filecoin-project/lotus/pull/5300
1. Take into account reserved funds when checking if a withdrawal can go through
FundManager already takes reserved funds into account. This just allows us to provide a nicer error message.
```
$ ./lotus wallet market withdraw 0.1
ERROR: can't withdraw more funds than available; requested: 0.1 FIL; available (0.028390768721594256 FIL) = escrow (0.030402437533428 FIL) - locked (0.001609365784995864 FIL) - reserved (0.00040230302683788 FIL)
```
2. Change `wallet market withdraw` parameter name
It was `--from`, which was confusing. Change it to `--wallet`.
```
$ ./lotus wallet market withdraw --help
NAME:
lotus wallet market withdraw - Withdraw funds from the Storage Market Actor
USAGE:
lotus wallet market withdraw [command …
```
=> Better CLI for wallet market withdraw and client info

chain/types/fil.go, chain/types/fil_test.go
=> enable parse and shorten negative FIL values

extern/storage-sealing/fsm.go, extern/storage-sealing/sealing.go
This:
```
goroutine 38357 [semacquire, 17 minutes]:
sync.runtime_SemacquireMutex(0xc01089f264, 0xc0001b9700, 0x1)
/usr/local/go/src/runtime/sema.go:71 +0x47
sync.(*Mutex).lockSlow(0xc01089f260)
/usr/local/go/src/sync/mutex.go:138 +0x105
sync.(*Mutex).Lock(...)
/usr/local/go/src/sync/mutex.go:81
github.com/filecoin-project/lotus/extern/storage-sealing.(*Sealing).restartSectors(0xc01089f1d0, 0x32c6520, 0xc01279c700, 0x0, 0x0)
/opt/lotus/extern/storage-sealing/fsm.go:412 +0x8ea
github.com/filecoin-project/lotus/extern/storage-sealing.(*Sealing).Run(0xc01089f1d0, 0x32c6520, 0xc01279c700, 0xc012312990, 0xc01278f814)
/opt/lotus/extern/storage-sealing/sealing.go:152 +0x5a
created by github.com/filecoin-project/lotus/storage.(*Miner).Run
/opt/lotus/storage/miner.go:164 +0x589
```
Could happen …
=> storagefsm: Fix unsealedInfoMap.lk init race

extern/sector-storage/ffiwrapper/sealer_cgo.go, extern/sector-storage/ffiwrapper/sealer_test.go
Before: `BenchmarkAddPiece512M-32    	       1	7034478758 ns/op	  75.72 MB/s`
After: `BenchmarkAddPiece512M-32    	       2	 916931366 ns/op	 580.93 MB/s`
(on AMD TR2950X)
=> Multicore AddPiece CommP

chain/sync.go
Just to get the conversation started and run all the tests.
Background on the removed code: https://github.com/filecoin-project/lotus/pull/17#discussion_r302359181.
=> fix(sync): remove checks bypass when we submit the block

README.md
This is a draft of the **Contribute** section in the README. The goal is to set the right expectations for contributors, and to help them submit useful PRs that have a high likelihood of being accepted.
It also removes the branch listing, and fixes some text. There is still outdated text in the README, but I'm choosing not to address it now to keep this PR simple.
=> README: Contribute section

README.md
This adds a bit more colour to prerequiste 3 to disambiguate the "subjective preferences" term. Up for discussion.
resolves https://github.com/filecoin-project/lotus/issues/5323
=> README: refine Contribute section.

chain/vm/vm.go
Required for sentinel to calculate gas outputs for each message. 
There is some noise caused by gofumpt formatting of the file.
=> chore: export vm.ShouldBurn

.circleci/config.yml, api/api_storage.go, api/apistruct/struct.go, api/test/window_post.go, build/version.go, chain/actors/builtin/miner/miner.go, cmd/lotus-storage-miner/info.go, cmd/lotus-storage-miner/sectors.go, documentation/en/api-methods-miner.md, extern/storage-sealing/cbor_gen.go, extern/storage-sealing/fsm.go, extern/storage-sealing/fsm_events.go, extern/storage-sealing/sealing.go, extern/storage-sealing/sector_state.go, extern/storage-sealing/states_failed.go, extern/storage-sealing/states_proving.go, extern/storage-sealing/terminate_batch.go, extern/storage-sealing/types.go, node/config/def.go, node/impl/storminer.go, node/node_test.go, storage/adapter_storage_miner.go, storage/addresses.go, storage/miner.go, storage/sealing.go
=> Sector termination support

chain/store/store.go
Similar to https://github.com/filecoin-project/lotus/pull/5182 this PR is theoretically protocol breaking but the only case of interest is when we are working with forks close to finality threshold (which is orders of magnitude away from normal forks observed in the chain).
---------------------------------
Most of the syncing logic seems to assume the "heaviest" tipset it receives as input is actually the head of our synced chain even if the lock is released. This is mostly innocuous and will be handled in follow-up PRs (to make this more explicit), but there are cases when we actually want to hold the lock while doing certain checks that are not related to the validity/integrity of a chain (either heaviest or not), namely how far away it is from the actual head we will be swapping it …
=> fix(sync): enforce fork len when changing head

chain/store/store.go, cmd/lotus/backup.go, cmd/lotus/daemon.go
Usage:
```
./lotus daemon 2>&1 --restore=node.cbor --restore-config=... --import-snapshot ...
```
Closes #4502
=> Implement full-node restore option

chain/actors/adt/adt.go, chain/actors/builtin/verifreg/util.go, chain/actors/builtin/verifreg/v0.go, chain/actors/builtin/verifreg/v2.go, chain/actors/builtin/verifreg/v3.go, chain/state/statetree.go, chain/stmgr/stmgr.go, chain/types/state.go, cmd/lotus-shed/datastore.go
Different maps have different parameters now so we just construct/load them manually where needed.
=> remove abstract map constructor/loader

api/api_full.go, api/api_gateway.go, api/apistruct/struct.go, chain/stmgr/stmgr.go, cmd/lotus-gateway/api.go, documentation/en/api-methods.md, node/impl/full/state.go
We need to expose StateSearchMessage on the gateway so that an upcoming PR can use it for making deals in lotus lite mode
=> expose StateSearchMessage on gateway

cmd/lotus-storage-miner/info.go
=> add color for token amount

storage/addresses.go
if owner address didn't have enough funds when precommit message, it log:
```bash
"msg":"address didn't have enough funds for window post message","address":"f0103977","required":"0.591527957531550313 FIL","balance":"0.461597663301924607 FIL"}
```
=> correct log in maybeUseAddress

node/impl/full/gas.go
The aim is to put some negative pressure on gas-premium instead of
maintining status quo.
55th percentile instead of median should not make much difference for
block inclusion timing.
Still thinking about it a bit, don't merge yet.
=> Use 55th percentile instead of median for gas-price

extern/sector-storage/fsutil/filesize_unix.go
At the moment `FileSize` is not recursive and doesn't calculate correctly the disk usage of various paths.
This PR is fixing it, by recursively walking the path and adding together all file sizes.
---
Ultimately this is fixing a bug in the `stores` package, where we iterate over all storage reservations and then check how much disk space is used per sector:
```
for id, ft := range p.reservations {
for _, fileType := range storiface.PathTypes {
if fileType&ft == 0 {
continue
}
sp := p.sectorPath(id, fileType)
used, err := ls.DiskUsage(sp)
```
`sp` in this case has the form of `./cache/s-t0127896-36` which is actually a directory with many `.dat` files, and not a single file.
---
TODO:
=> fix FileSize to return correct disk usage recursively

go.mod, go.sum, node/modules/client.go
Fixes https://github.com/filecoin-project/lotus/issues/4991 https://github.com/filecoin-project/lotus/issues/5211 https://github.com/filecoin-project/lotus/issues/5224 https://github.com/filecoin-project/lotus/issues/5268 https://github.com/filecoin-project/lotus/issues/5038
It wasn't a small task to write an integration or testground test, so this should be tested manually:
- Bring up a client and miner
- Start transferring a large file from client to miner
- While the file is transferring, restart the miner
- Ensure that the file completes transferring and the deal moves to the sealing state
=> Miner should not dial client on restart

go.mod, go.sum, node/modules/core.go
This pulls in the improvements introduced in:
- https://github.com/raulk/go-watchdog/releases/tag/v1.0.0
- https://github.com/raulk/go-watchdog/releases/tag/v1.0.1
Lotus tries to initialize the watchdog in the following order of precedence:
1. If a max heap limit has been provided, initialize a heap-driven watchdog.
2. Else, try to initialize a cgroup-driven watchdog.
3. Else, try to initialize a system-driven watchdog.
4. Else, log a warning that the system is flying solo, and return.
This PR also enabled automatic heap profile capture when memory usage surpasses 90% of the limit. Profiles are written to `<LOTUS_HOME>/heapprof`. A single heap profile is captured per episode, with a max of 10 episodes captured during the lifetime of the process. Episode = instance of usage climbing above …
=> upgrade to raulk/go-watchdog@v1.0.1

cli/chain.go, cli/multisig.go, cmd/lotus-storage-miner/actor.go
Fixes #5287
**Motivation**
Miners want to be able to set multisigs as their miner owner address. This currently fails if you use the `set-owner` command, because it assumes both the old and new owner address are accounts whose keys are in the Lotus wallet.
**Changes**
- Breaks the assumption that both the old and new owner address are accounts whose keys are in the Lotus wallet by changing the `set-owner` command to 
- take the sender of the `ChangeOwnerAddress` message as a param
- not send both `ChangeOwnerAddress` messages within a single execution. 
- Add a `chain encode` command as a util to encode params (does this not already exist somewhere? I couldn't find it?)
- Minor bugfix to `lotus msig approve` that makes it unusable when all optional params are provided.
**Usage**
- **When …
=> Allow multisigs to be set as miner owner address

chain/sync_manager_test.go
Depending on scheduling, we may see c2 before we see c1.
=> fix a flake in the sync manager edge case test

markets/loggers/loggers.go, markets/storageadapter/api.go, markets/storageadapter/client.go, markets/storageadapter/getcurrentdealinfo.go, markets/storageadapter/getcurrentdealinfo_test.go, markets/storageadapter/ondealsectorcommitted.go, markets/storageadapter/ondealsectorcommitted_test.go, markets/storageadapter/provider.go
This might fix some of the test hangs we see in CI
=> storageadapter: Look at precommits on-chain since deal publish msg

node/impl/full/gas.go
The bug is applying all messages from given From address are priors
before appling the message that we are estimating.
If user tries replacing message in the middle with gas limit estimation
then message sequence is off and user will either get an execution error
or gas mis-esimation.
Resolves #5402
Tests will come in in another PR
=> fix(gas): when estimating GasLimit only apply priors up to the nonce

api/test/window_post.go, node/node_test.go
Add a test to make sure disputing a valid window post fails.
=> ensure we can't dispute a correct window post

chain/sync.go
This is implicitly checked when verifying the miner signature, but explicitly checking it here makes it clear that this is a protocol requirement, and reduces the chances that it will be accidentally "refactored out".
cc @wadeAlexC
=> explicitly check miner address protocol

.gitmodules, chain/gen/mining.go, chain/sync.go, go.mod, lib/sigs/bls/init.go
With https://github.com/filecoin-project/filecoin-ffi/pull/159 the ffi now uses `blst` as the signature backend, matching the existing functionality. This allows us to simplify the ffi contexts, and remove the git submodule for blst in here. 
Due to the streamlining, I am seeing a nice perf increase
```
master
BenchmarkBLSVerify-64                693           1816108 ns/op
feat-refactor-bls
BenchmarkBLSVerify-64                904           1245841 ns/op
```
=> refactor: switch to filecoin-ffi bls api for bls signatures

api/api_full.go, chain/actors/builtin/miner/miner.go, chain/actors/builtin/miner/v0.go, chain/actors/builtin/miner/v2.go, chain/actors/builtin/miner/v3.go, cli/chain.go, cli/disputer.go, node/impl/full/state.go
**Motivation**
[FIP-0010](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0010.md) necessitates the creation of "auditors" that try to disprove recent WindowPoSt submissions. We need this to be something easily launched, and so it makes sense to build it within a Lotus node.
**Design considerations**
There are 2 chief designs we could go with:
- **Design 1**: Periodically audit every miner's PoSt submissions (that are in the `OptimisticPoStSubmissionsSnapshot` of their deadlines). This is fairly comprehensive, but could be slow unless we have high efficiency (never re-audit a post). We could also modify this to be random, auditing some configurable number (or percentage) of miners in every period.
- **Design 2**: Subscribe to updates to the head, and listen for WindowPoSt …
=> Build a WindowPoSt disputer

chain/gen/gen.go, chain/stmgr/forks.go, chain/stmgr/forks_test.go, chain/stmgr/stmgr.go, node/builder.go, node/modules/stmgr.go
This PR adds:
1. A PreMigrations slice to every Upgrade. This can be filled with functions that should be executed
some number of epochs before the upgrade happens.
2. A MigrationCache that's passed to both the final Migration function, and any PreMigration functions.
3. An _optional_ Start/Stop method on the StateManager that starts/stops the pre-migration scheduler.
Finally, this PR wires up pre-migrations for the actors V3 upgrade.
fixes #5415 
TODO:
=> Implement pre-migration framework

cmd/lotus-storage-miner/init.go, extern/storage-sealing/cbor_gen.go, extern/storage-sealing/checks.go, extern/storage-sealing/currentdealinfo.go, extern/storage-sealing/currentdealinfo_test.go, extern/storage-sealing/sealing.go, extern/storage-sealing/states_failed.go, extern/storage-sealing/types.go, extern/storage-sealing/types_test.go, markets/storageadapter/provider.go, storage/adapter_storage_miner.go, storage/miner.go
As part of https://github.com/filecoin-project/lotus/pull/5309, update sealing to be able to recover deal IDs where those deals were published in a batch
=> Handle batch publish storage deals message in sealing recovery

chain/stmgr/forks.go
This PR:
1. Adds some additional logging to migrations and enables progress reporting.
2. Tunes the migration job queue parameters.
=> Tune Migration

chain/types/blockheader.go
Annotate fields after a conversation with @Kubuxu
=> Better document the block-header fields

chain/messagepool/config.go, chain/messagepool/messagepool.go, chain/messagepool/pruning.go, chain/messagepool/selection.go
Since there exists a way to modify the value of mpool.cfg, it will cause a data race and create some unexpected cases.  Lock it with an RWMutex is good
=> avoid use mp.cfg directly to avoid race

cmd/lotus-bench/main.go
originally add abi.RegisteredSealProof_StackedDrg8MiBV1, abi.RegisteredSealProof_StackedDrg512MiBV1
delete policy  test ok. 
2020-11-21T10:07:25.223+0800	INFO	lotus-bench	lotus-bench/main.go:511	[0] Writing piece into sector...
2020-11-21T10:07:25.227+0800	INFO	lotus-bench	lotus-bench/main.go:511	[1] Writing piece into sector...
2020-11-21T10:07:25.238+0800	INFO	lotus-bench	lotus-bench/main.go:511	[2] Writing piece into sector...
2020-11-21T10:07:25.241+0800	INFO	lotus-bench	lotus-bench/main.go:511	[3] Writing piece into sector...
2020-11-21T10:07:25.251+0800	INFO	lotus-bench	lotus-bench/main.go:511	[4] Writing piece into sector...
2020-11-21T10:07:25.253+0800	INFO	lotus-bench	lotus-bench/main.go:511	[5] Writing piece into sector...
2020-11-21T10:07:25.256+0800	INFO	lotus-bench …
=> delete bench policy

cmd/lotus-shed/bitfield.go
optimize code
use func
add merge
=> shed bitfield: Cleanup, add merge command

lib/ipfsbstore/ipfsbstore.go
Fixes #5361
Discovered this when doing something unrelated on top of this blockstore
Basically the implementation of `blockstore.Has` would call `block/stat` on the ipfs node - doing that in online mode will obviously try to fetch that node from the network. This then compounds with the default blockservice implementation, which calls `Has` before calling `Put`, which is basically guaranteed to hang in online mode when trying to retrieve data into ipfs which can't be fetched from the ipfs network (also means that data would be fetched from ipfs first before being retrieved from filecoin..)
=> ipfsbstore: Fix has for non-existing blocks

markets/storageadapter/dealpublisher.go, markets/storageadapter/dealpublisher_test.go
@jennijuju [pointed out](https://github.com/filecoin-project/lotus/pull/5309#issuecomment-771493626) that we should not include deals in a batch publish message if the deal has already expired (the current epoch is greater than the deal proposal start epoch). This PR implements a fix.
=> Dont publish expired deals

chain/events/events.go, markets/storageadapter/client.go, markets/storageadapter/provider.go, paychmgr/settler/settler.go
Fixes some retry log spam in tests
=> Use correct contexts in storageadapter

extern/storage-sealing/sealiface/config.go, extern/storage-sealing/states_sealing.go, extern/storage-sealing/types.go, node/config/def.go, node/modules/storageminer.go
Allows miners to set
```
[Sealing]
AlwaysKeepUnsealedCopy = true
```
in lotus-miner configs, to keep copies of deals even if those deals don't have the FastRetrieval flag set. By doing this miners can avoid having to unseal sectors while still being able to provide retrieval
=> Add miner config to always keep ensealed deal copies

node/modules/storageminer.go, storage/wdpost_run.go, storage/wdpost_run_test.go, storage/wdpost_sched.go
I'm proposing this change because lotus now submits window post proofs without locally _verifying_ the proof. This isn't strictly speaking necessary, but it should take very little time and help protect against random bit flips and bugs.
=> Retry proofs if we generate an incorrect one

go.mod, go.sum
Includes better storage fsm handling: https://github.com/filecoin-project/go-fil-markets/pull/484
=> update to go-fil-markets@1.1.7

chain/actors/builtin/multisig/message.go, cmd/lotus-wallet/interactive.go, cmd/lotus-wallet/main.go
Nice for things like looking at decoded message params on a secureish device before passing to ledger
=> lotus-wallet: Add interactive mode

chain/sync.go
Is there any possible way that this genesis will ever be nil and it would otherwise load from store?
=> Remove unnecessary database reads in validation check

api/api_storage.go, api/apistruct/struct.go, cmd/lotus-storage-miner/market.go, documentation/en/api-methods-miner.md, markets/storageadapter/dealpublisher.go, markets/storageadapter/dealpublisher_test.go, node/impl/storminer.go
Fixes https://github.com/filecoin-project/lotus/issues/5491
=> add commands to list pending deals and force publish

.circleci/config.yml
Currently `ci/build-and-push-image` is failing on PRs from external contributors, this PR disables this job gracefully for those PRs.
=> circleci: halt step gracefully

cmd/lotus-storage-miner/market.go
```
$ ./lotus-miner storage-deals pending-publish
Publish period:             1h0m0s (ends in 55m11s)
First deal queued at:       2021-02-08 11:08:39.222417 +0100 CET
Deals will be published at: 2021-02-08 12:08:39.222417 +0100 CET
2 deals queued to be published:
ProposalCID                                                  Client                                                                                  Size
bafyreickthq7mv2lr2lyeigyle2gpihw63cga5rmiecnigic6zepq4vjja  t3udoamurqpl2e6yac6bvm2dzq2cxpu26rurt2vph3xowcegplslxx6zkfcw2u4l7k2lpo4n25lbr3diuqxwcq  2KiB
bafyreigmvme6a3eoctzhpjt3dc7jexv2qacn25mk6dhwyezcizamfcw5oa  t3udoamurqpl2e6yac6bvm2dzq2cxpu26rurt2vph3xowcegplslxx6zkfcw2u4l7k2lpo4n25lbr3diuqxwcq  2KiB
$ ./lotus-miner storage-deals pending-publish --publish-now
triggered …
```
=> Output more info in pending-publish CLI

go.mod, go.sum
This PR is upgrading `github.com/whyrusleeping/pubsub` where the difference in commits is just that the tests are disabled, so that we don't depend on `launchpad.net/gocheck`.
`launchpad.net/gocheck` is annoying because in order to fetch it, one needs to have `bzr` installed, which requires changes to various tools (such as `goproxy` in Testground).
Related: https://github.com/filecoin-project/lotus/issues/5548
cc @adlrocha
=> go.mod: do not depend on gocheck

cli/cmd.go
This PR is making `categories` uppercase for all binaries. Feel free to close if you don't like this UI/UX suggestion.
I think uppercase help differentiate actual commands and other text on the screen, otherwise I always get confused when I see `lotus-miner chain actor` (which is not a command, `lotus-miner info` is) vs `lotus chain`.
```
COMMANDS:
init     Initialize a lotus miner repo
run      Start a lotus miner process
stop     Stop a running lotus miner
config   Output default configuration
backup   Create node metadata backup
version  Print version
help, h  Shows a list of commands or help for one command
CHAIN:
actor  manipulate the miner actor
info   Print miner info
DEVELOPER:
auth          Manage RPC permissions
log           Manage logging
wait-api      Wait for lotus api to …
```
=> ux/ui suggestion: make categories uppercase

testplans/lotus-soup/go.mod, testplans/lotus-soup/go.sum, testplans/lotus-soup/testkit/role_miner.go
`NewDealPublisher` actor was added to Lotus, which has a default wait time of 1h.
This PR is updating the miner node with more reasonable configs for test plans that exercise the deals end-to-end flow.
cc @adlrocha
=> lotus-soup testplan: add storageadapter.PublishMsgConfig to miner in testkit

cmd/lotus-seed/genesis.go
Currently devnet deployment requires spinning up a full daemon.
This would move the daemon `lotus-make-genesis` logic to lotus-seed
so it can be more easily executed in scripts, etc.
=> lotus-seed command to generate lotus block

api/api_full.go, cli/client.go, cli/test/client.go, documentation/en/api-methods-miner.md, documentation/en/api-methods.md, go.mod, go.sum, node/impl/client/client.go
This reverts commit b6c9ddccfff30a47b3cb1d29f1d99b7a29dd01b4
PR: https://github.com/filecoin-project/lotus/pull/5553
Adding the `RawBlockSize` field to the `DataRef` created a backwards-incompatibile unmarshalling issue: https://github.com/filecoin-project/lotus/issues/5601
=> Revert "feat: deals - show data transfer %"

api/cbor_gen.go, chain/exchange/cbor_gen.go, chain/market/cbor_gen.go, chain/types/cbor_gen.go, conformance/chaos/cbor_gen.go, documentation/en/api-methods-miner.md, documentation/en/api-methods.md, extern/sector-storage/cbor_gen.go, extern/sector-storage/storiface/cbor_gen.go, extern/storage-sealing/cbor_gen.go, go.mod, go.sum, node/hello/cbor_gen.go, paychmgr/cbor_gen.go
(https://github.com/filecoin-project/go-fil-markets/pull/492, whyrusleeping/cbor-gen#50)
TODO:
Results are in https://github.com/filecoin-project/lotus/pull/5655
=> Update markets, cbor-gen with soft map decoding

build/params_mainnet.go
Just a safety measure in case the v3 migration goes bad. The remediation will be to set `LOTUS_DISABLE_V3_ACTOR_MIGRATION = 1` and (potentially) set head back.
Fixes #5451
=> Add a LOTUS_DISABLE_V3_ACTOR_MIGRATION envvar

build/tools.go, go.sum
Go 1.16 elides dependencies from go.sum when you don't use a package
which has these dependencies.
This means dependencies for the `rice` command were not in our
`go.sum`.
=> Fix riceing by importing the main package

cmd/lotus/daemon.go
Without this commit the error message does not provide much value as it
lacks context.
=> Improve error message with importing a chain

api/api_storage.go, api/apistruct/struct.go, api/test/tape.go, api/test/window_post.go, cmd/lotus-storage-miner/sectors.go, documentation/en/api-methods-miner.md, extern/storage-sealing/fsm_events.go, extern/storage-sealing/garbage.go, extern/storage-sealing/sealing.go, extern/storage-sealing/states_sealing.go, node/impl/storminer.go, storage/sealing.go
On top of #5375
With this calling `lotus-miner sectors pledge` in a loop with very short interval should respect the `MaxSealingSectors` config.
Fixes #3896
=> storagefsm: Cleanup CC sector creation

cli/chain.go
Add tipset capacity display to `chain list`
=> chain list --gas-stats display capacity

cli/disputer.go
Fixes the format of the log so that we can correctly parse out the data when logging as json.
=> Correctly format disputer log

api/api_common.go, api/apistruct/struct.go, api/mocks/mock_full.go, api/types.go, build/tools.go, cli/net.go, documentation/en/api-methods-miner.md, documentation/en/api-methods.md, node/impl/common/common.go
This provides extended information for connected peers, aggregating all known addresses, agent, and protocols supported.
=> Implement net peers --extended

cmd/lotus-storage-miner/sectors.go
=> Command to extend sector expiration

blockstore/badger/blockstore.go, blockstore/splitstore/splitstore.go
so that we reclaim space, otherwise the hotstore keeps balooning despite the deletions.
=> garbage collect hotstore after compaction

go.mod, go.sum
This fixes a bunch of bugs and should improve deal reliability.
=> chore: update go-graphsync to 0.6.0

cmd/lotus/daemon.go
node.Online()->LibP2P would override it again, setting it to false - https://github.com/filecoin-project/lotus/blob/master/node/builder.go#L194
=> Fix bootstrapper profile setting

extern/storage-sealing/terminate_batch.go
`lzusaga` somehow ran into this problem on Slack: https://filecoinproject.slack.com/archives/CPFTWMY7N/p1615315583105100.
I'm not entirely sure how this happened, since the liveness check [here](https://github.com/filecoin-project/lotus/blob/32885e1129178582fbf75711b249f5b8d99663c3/extern/storage-sealing/states_proving.go#L48-L65) should be preventing putting such sectors into the termination queue. Maybe that liveness check isn't 100% correct? I'm not sure.
But, regardless, re-checking liveness and removing out any not-live sectors should be a fine thing to do?
=> Check liveness of sectors when processing termination batches

cmd/lotus-seal-worker/storage.go, cmd/lotus-storage-miner/storage.go, documentation/en/api-methods-miner.md, extern/sector-storage/fsutil/statfs.go, extern/sector-storage/fsutil/statfs_unix.go, extern/sector-storage/fsutil/statfs_windows.go, extern/sector-storage/sched_test.go, extern/sector-storage/stores/index.go, extern/sector-storage/stores/local.go, extern/sector-storage/stores/local_test.go
This adds a new `MaxStorage` field to sectorstore.json files, which allows setting maximum number of bytes to use in a storage path.
TODO:
```
$ lotus-miner storage list
09b4f94d-b548-4382-92d1-551676289e3e:
[###################################               ] 38.92 TiB/54.57 TiB 71%
Unsealed: 180; Sealed: 867; Caches: 867; Reserved: 0 B
Weight: 10; Use: Store
Local: /data/1/store
URL: http://[...]:2345/remote
92da064d-c2ee-4be1-802f-adbbabf1a06b:
[#####################################             ] 1.367 TiB/1.818 TiB 75% (filesystem)
[####################                              ] 64 GiB/153.6 GiB 41% (limit)
Unsealed: 2; Sealed: 0; Caches: 0; Reserved: 0 B
Weight: 10; Use: Seal 
Local: /data/nvme/store
URL: http://[...]:2345/remote
```
=> Configurable storage path storage limit

api/api_storage.go, cmd/lotus-storage-miner/actor.go, documentation/en/api-methods-miner.md, node/config/def.go, node/modules/storageminer.go, storage/addresses.go
=> miner: Config to disable owner/worker address fallback

extern/sector-storage/fr32/readers_test.go
UnpadReader can't deal with small reads right now, and `ioutil.ReadAll` in Go 1.16 starts with some tiny reads
=> Fix TestUnpadReader on Go 1.16

storage/wdpost_changehandler.go, storage/wdpost_changehandler_test.go, storage/wdpost_run.go, storage/wdpost_run_test.go
Due to a (now consensus critical) bug in randomness selection, "beacon" randomness depends on whether the epoch in which the beacon occurred was a null block. Unfortunately, this means:
1. If a challenge lands on a non-null round but that non-null round gets re-orged to a null round, the randomness will change to the beacon in the first preceding non-null block.
2. If a challenge lands on a null round but that null round gets re-orged to a non-null round, the randomness will change to the beacon in the new non-null round.
The correct solution is to change the way the beacon is selected:
1. Wait until a non-null round.
2. The block in this round will contain all beacons from the null rounds, select the beacon from the target epoch.
Unfortunately, this requires a mandatory network upgrade. …
=> fix: wait a bit before starting to compute window post proofs

storage/wdpost_run.go
GenerateWindowPoSt func will modifies the value of rand (randomness[31] &= 0x3f), this will result in false in the bytes.Equal(checkRand, rand)
=> fix window post rand check

storage/wdpost_run.go
We're running the randomness check with the head tipset, but if it failed, we'd loop back and still use the wrong one
=> wdpost: Always use head tipset to get randomness

extern/storage-sealing/input.go
We would double-unlock the `inputLk` when the miner had a sector in WaitDeals state become ready for sealing while the node wasn't running
Somehow those unlocks got left there when this was refactored, and would cause double unlock with the unlock here -> https://github.com/filecoin-project/lotus/blob/master/extern/storage-sealing/input.go#L33
Looked at other usages of this lock, and it seems like we don't have more cases of this
(manually reproduced and verified the fix on my node)
=> storagefsm: Fix double unlock with ready WaitDeals sectors

blockstore/badger/blockstore.go
In theory, Delete/Put could fail. If it does, we'll return the buffers to the pool before we're really done with them.
In practice, this is almost certainly not an issue as badger shouldn't _use_ the buffer unless we flush. But I feel slightly safer this way.
=> fix: return buffers after canceling badger operation

chain/stmgr/rpc/rpcstatemanager.go, node/builder.go, node/modules/paych.go, paychmgr/manager.go, paychmgr/store.go
This makes it easier to use the paychmgr package outside of lotus.
=> move DI stuff for paychmgr into modules

blockstore/badger/blockstore.go, blockstore/splitstore/splitstore.go
Makes garbage collection more efficient at reclaiming space.
In one of the nodes, there was a performance effect for an interval of 1-2min, where block validation time jumped up to 30s. Note that this node had been running compaction every 15min for a while, so there was a lot of garbage sst files.
The other two test nodes showed no ill effect in block validation time.
All 3 nodes reclaimed some 10G of space thanks to the compaction.
=> splitstore: compact hotstore prior to garbage collection

blockstore/timed.go
Interleaved puts/views could get really slow and there's no real reason
to use view under the covers here because the underlying blockstore is
always a "memstore".
=> fix: avoid holding a lock while calling the View callback

extern/sector-storage/mock/mock.go
Ideally we would change the ffiwrapper to not have sideeffects, but we need to make sure that we don't use this randomness anywhere after it's modified by the ffi calls.
This at least makes the mock and ffiwrapper do the same thing
=> mock sealer: Simulate randomness sideeffects

api/test/deals.go, extern/storage-sealing/fsm.go, extern/storage-sealing/garbage.go, extern/storage-sealing/input.go, extern/storage-sealing/stats.go, node/node_test.go
Currently when a miner starts processing more deals in parallel than the configured sealing limits, we wouldn't start processing more deals after the first batch of sectors got sealed.
This should fix that case
=> storagefsm: Trigger input processing when below limits

cmd/lotus-shed/main.go, cmd/lotus-shed/miner.go, cmd/lotus-storage-miner/info_all.go
(also makes the `info all` a bit more robust)
=> shed command to unpack miner info dumps

node/repo/fsrepo.go
=> Aftering importing a previously deleted key, be able to delete it again.

api/api_full.go, api/apistruct/struct.go, api/mocks/mock_full.go, api/types.go, cli/cmd.go, cli/status.go, documentation/en/api-methods.md, node/impl/full.go, node/modules/lp2p/pubsub.go
=> node status api

api/api_full.go, documentation/en/api-methods.md
This is a fairly sharp edge which we should fix in the v1 API, but for now it should at least get better docs
=> api: Document StateSearchMsg replaced message behavior

Makefile
@arajasek without doing this I need to manually build shed, which is super annoying
=> Build more binaries by default when a devnet tag is active

markets/retrievaladapter/provider.go
This should help miners identify the underlying cause of errors during unsealing. See https://github.com/filecoin-project/lotus/issues/5829
=> better logging when unsealing fails

chain/events/events.go, node/builder.go
- Implement TipSetObserver interface for observing tipset events (apply/revert)
- Implement Settings opts for 3rd party dep injection (allows Visor to instantiate a Lotus node)
=> Implement Event observer and Settings for 3rd party dep injection

api/api_full.go, api/apistruct/struct.go, api/mocks/mock_full.go, chain/messagepool/check.go, documentation/en/api-methods.md, node/impl/full/mpool.go
For performing message replacement with logical set in the set of pending messages.
=> MpoolCheckReplaceMessages API

cmd/lotus-shed/base64.go, cmd/lotus-shed/main.go, cmd/lotus-shed/signatures.go
- The first is to help with base64 inputs
- The second can be used to validate signed votes for FILPolls, so that users can be confident that they have not been tricked into signing something other than a ballot. To use it for the FIP-0014 poll, run 
```
lotus-shed signatures verify-vote 14 <signingAddress> <signature (hex string)>
```
Example:
```
lotus-shed signatures verify-vote 14 f1vstk2dncjlimtmbcmu7tjxwekaurhvvma3joqea 01c109f5c39d6792e991a6f8d74f081f98850bdcdb1c0432608e9d30dcaeaf030a5e9c7101bb12ffa7a4c0b311308462763b928edc7828d6563e1e2b8562aa3d8b00
valid vote for rejecting FIP-0014
```
=> Add two utils to Lotus-shed

cmd/lotus-shed/datastore.go, lib/backupds/log.go, lib/backupds/read.go
The log files grow slowly over time, this adds a way to compact them. Online compaction is a bit more tricky to do safely, so it doesn't do that yet.
(Tested both on my chain node and my miner)
=> backupds: Compact log on restart

chain/stmgr/call.go
in the `statemanager.replay` method, 
after get the msg(specified by 'mcid' param) execution result,
the callback function returns an 'errHaltExecution' to break  out the loop in `computeTipSetState`
but some times `computeTipsetstate`  warps the `errHaltExecution` with `xerrors`
that would cause following expression:
(err != errHaltExecution)  to be `true` .
which  causes `StateManager.Replay` returns an error with following message: 
`unexpected error during execution: callback failed on reward message: halt`
=> fix: StateManager.Replay

blockstore/badger/blockstore.go
Otherwise, this won't work on 32bit ARM.
See https://golang.org/pkg/sync/atomic/#pkg-note-BUG
=> fix: make sure atomic 64bit fields are 64bit aligned

cli/auth.go
This PR adds more information on the auth CLI error. My flow to use the auth command was:
```sh
$ lotus auth
NAME:
lotus auth - Manage RPC permissions
USAGE:
lotus auth command [command options] [arguments...]
COMMANDS:
create-token  Create token
api-info      Get token with API info required to connect to this node
help, h       Shows a list of commands or help for one command
OPTIONS:
--help, -h     show help (default: false)
--version, -v  print the version (default: false)
$ lotus auth api-info
ERROR: --perm flag not set
```
This PR suggests the enhancement of the error to: 
```sh
$ lotus auth api-info
ERROR: --perm flag not set, use with one of: read, write, sign, admin
```
We can also use `lotus auth api-info --help`, but I think that creates some confusion as commandOptions seem …
=> chore: add available options for perm on error

cmd/lotus-shed/sectors.go
Can specify miner actor address when terminate sectors,
so that you can terminate sectors without miner api.
=> Add --actor flag in lotus-shed sectors terminate

paychmgr/paych_test.go
When running those tests directly, secp sigs wouldn't be imported, and some of the paych tests would fail
=> Import secp sigs in paych tests

go.mod, go.sum
Includes https://github.com/filecoin-project/go-commp-utils/pull/2
(and https://github.com/filecoin-project/go-statestore/pull/9 while here, just a tiny bugfix)
=> Update go-commp-utils for >10x faster client commp calculation

build/params_2k.go, build/params_butterfly.go, build/params_calibnet.go, build/params_mainnet.go, build/params_nerpanet.go, build/params_testground.go, chain/actors/version.go, chain/stmgr/forks.go, go.mod, go.sum
=> Introduce the v11 network upgrade

build/params_2k.go
Makes testing easier for integ partners, use LOTUS_NORWEGIAN_HEIGHT
=> Debug mode: Make upgrade heights controllable by an envvar

chain/actors/builtin/miner/miner.go, chain/actors/policy/policy.go, cmd/lotus-storage-miner/info.go, cmd/lotus-storage-miner/main.go, cmd/lotus-storage-miner/proving.go, cmd/lotus-storage-miner/sectors.go
Run `lotus-miner sectors extend --v1-sectors`. 
- The `tolerance` flag can be passed to indicate what durations aren't "worth" extending. It defaults to one week, which means that sectors whose current lifetime's are within one week of the maximum possible lifetime will not be extended.
- The `expiration-cutoff` flag can be passed to skip sectors whose expiration is past a certain point from the current head. It defaults to infinity (no cutoff), but if, say, `28800` was specified, then only sectors expiring in the next 10 days would be extended (2880 epochs in 1 day).
=> Util for miners to extend all v1 sectors

chain/store/store.go
High read-API concurrency facilitates multiple calls to GetHeaviestTipSet
which in turn could slow down chainsync.
=> Convert the chainstore lock to RW

chain/beacon/beacon.go, chain/beacon/drand/drand.go, chain/exchange/protocol.go, chain/market/fundmanager.go, chain/messagepool/selection_test.go, chain/stmgr/forks_test.go, chain/wallet/ledger/ledger.go, cmd/lotus-gateway/main.go, cmd/lotus-health/main.go, cmd/lotus-shed/datastore.go, cmd/lotus-shed/mempool-stats.go, extern/sector-storage/ffiwrapper/sealer_test.go, extern/sector-storage/manager_test.go, extern/sector-storage/mock/mock.go, go.mod, journal/types.go, lib/ulimit/ulimit.go, node/builder.go, node/impl/full/chain.go
I am not entirely sure this is right, but everything seems to build...
@Stebalien I didn't manage to find anything substantially different between v1 and v2, even the zap-frame-skip seems to be the same. Is there anything I am missing?
=> Centralize everything on ipfs/go-log/v2

extern/sector-storage/stores/local.go
This can be a bit spammy, and can happen normally, for example when finalizing the sector:
* We'll reserve space for the sealed sector and cache, 
* We'll start fetching sealed data
* Cache will not start to be fetched until we fetch the sealed sector file
* Since that takes a while, we'll spam this error when periodically checking storage health / getting disk usage when scheduling tasks
=> localstorage: Demote reservation stat error to debug

cmd/lotus-storage-miner/actor.go
=> fix 4857: show help for set-addrs

build/params_2k.go, build/params_butterfly.go, build/params_calibnet.go, build/params_mainnet.go, build/params_nerpanet.go, build/params_shared_funcs.go, build/params_testground.go, chain/sync.go, cmd/lotus-shed/signatures.go
We need to test the whitelisted block thing. 
bafy2bzaceapyg2uyzk7vueh3xccxkuwbz3nxewjyguoxvhx77malc2lzn2ybi 
bafy2bzaced5qjsl2jp4rlxjrwsxovyvayswsufxbst6yan7tijd27cktznxl6 
bafy2bzaceb7syjfrkoy4yujiumrdvw23kchm2ilvjyul4yst3tkl7ce62royk 
bafy2bzacebruywjijmeqyrwsv7m3mtokjkibhgsoymsbopet4f7qzb2dkikkg 
bafy2bzaceber4ccef75m4ufhq27cxshtuj552c2g5e3psx62557b45it7d6qk`. Should successfully validate.
- _(optional)_ Run a full chain validation (it's okay if it takes weeks, we just need to know).
=> Update to latest proofs

node/config/def.go
The original value is too conservative for the current state of mainnet
Resolves (temporarily) #5543
=> Raise client MaxFee default

chain/messagepool/messagepool.go, chain/messagepool/messagepool_test.go, chain/messagesigner/messagesigner.go, chain/messagesigner/messagesigner_test.go, node/impl/full/mpool.go, node/modules/mpoolnonceapi.go
=> Fix nonce getting on Lotus lite

node/impl/client/client.go
fix: full node painc  when calling  RPC  Filecoin.ClientRetrieve without the order.Total specified.
request:
```json
{
"jsonrpc": "2.0",
"method": "Filecoin.ClientRetrieve",
"params": [
{
"Root":{"/":"bafk2bzacecjclkq7dnfr2hcwqvrkvtbwmbx2zh7ygsixlmbh7hbkxm74x7a5m"},
"Miner":"t01000",
"Client":"t3wefnh7256b65hya4xnaskm63zqjkhjjtv3ty5nixtu7iv445eiwrtwsv4lyc2opawwabg2daq54omvcbixzq",
"Size": 1024
},
{
"Path":"/tmp/123.txt",
"IsCAR":false
}
],
"id": 3
}
```
=> fix full node painc

extern/sector-storage/manager.go, markets/retrievaladapter/provider.go
Adding some logging to help track down issue with retrieval unsealing
=> Add more debug logging for unsealing

cmd/lotus-shed/balances.go
`lotus-shed audits chain-balance-sanity` does the trick.
=> Shed util to sanity-check total balance is FilBase

cli/client.go
This is a one-line change that adds an "expected duration" label to the `lotus client inspect-deal` command output, since there was some confusion about what the times referred to in our user testing. The confusion was based on the output showing states that had already passed, so we though it might be "time elapsed" instead of an estimate.
=> add "expected duration" label to inspect-deals output

testplans/Makefile, testplans/docker-images/Dockerfile.oni-buildbase, testplans/docker-images/Dockerfile.oni-runtime, testplans/docker-images/Dockerfile.oni-runtime-debug, testplans/lotus-soup/_compositions/baseline-k8s-3-1.toml, testplans/lotus-soup/deals_e2e.go, testplans/lotus-soup/init.go, testplans/lotus-soup/manifest.toml
This PR is bumping up Go to 1.16.3 for all docker images used in Testground test plans.
It is also reduce concurrency for deals towards a single miner, until we fix the underlying issues with deals being blocked in `StorageDealAwaitingPreCommit` stage.
=> upgrade `lotus-soup` testplans and reduce deals concurrency to a single miner

cmd/lotus-shed/balances.go
Modification of #5841.
This one:
1. Let's you specify a start/stop height.
2. Prints out ndjson to stdout, and status/errors to stderr.
3. Prints one entry per set of duplicates.
4. Allows filtering messages by method number.
5. Allows configuring the number of threads.
Usage:
```bash
> cd cmd/lotus-shed
> go build
> ./lotus-shed audits duplicate-messages --start=148888 | tee output.ndjson
```
That will walk back to the mainnet epoch and write the results to stdout and output.ndjson.
**TODO**
=> shed: command to list duplicate messages in tipsets (steb)

blockstore/splitstore/splitstore.go, blockstore/splitstore/splitstore_test.go
Calling, e.g., `lotus chain sethead` on an ancestor tipset won't apply any new blocks, it'll just revert a bunch. This will lead to HeadChange calls with no new blocks to apply.
fixes #6125
=> fix(splitstore): fix a panic on revert-only head changes

chain/stmgr/utils.go
This is correcter, and means we don't clumsily fail on commands like `lotus state power <maddr>` when `maddr` isn't found in claims.
=> Return total power when GetPowerRaw doesn't find miner claim

chain/stmgr/stmgr.go
To be consistent with other commands. Otherwise, two API calls with the same tipset can return inconsistent results.
=> fix: use the parent state when listing actors

testplans/lotus-soup/_compositions/paych-stress-k8s.toml
This PR is updating the configuration for the payment channel tests - in order to start only 1 miner, and not a network of 2 miners.
---
This is a work-around to https://github.com/filecoin-project/lotus/issues/6127 so that we get stable Testground tests as part of the Lotus release cycle. Once the underlying issue is fixed, we can fix this composition to start a larger network.
=> fix testground payment channel tests: use 1 miner

cli/chain.go, cli/state.go, cmd/lotus-shed/frozen-miners.go, cmd/lotus-shed/postfind.go, cmd/lotus-shed/stateroot-stats.go
It's very easy to write an incorrect command that operates over different heads by using the "empty" tipset. This change makes the `LoadTipSet` command helper get the latest head from the lotus daemon if its unset.
The cost is an extra call to get the head. That should be trivial in most cases.
=> fix: use a consistent tipset in commands

cli/state.go
`lotus state miner-proving-deadline <maddr>`.
I find myself wanting this all the time, especially so there's an easy way to look back in time (doing so over the RPC is a pain).
=> Add a CLI tool for miner proving deadline

chain/actors/builtin/market/market.go, cmd/lotus-shed/main.go, cmd/lotus-shed/market.go
=> Add a command to get the fees of a deal

chain/checkpoint.go, chain/store/checkpoint_test.go, chain/store/store.go, chain/sync.go, chain/sync_test.go, node/impl/full/sync.go
Previously, `lotus sync checkpoint` would only checkpoint on the current
chain. Now, it can switch to a new fork.
Alternatives considered:
1. Follow a peer: sketchy.
2. Mess with the sync manager to only sync this chain: very
invasive. (but I have a WIP patch if desired).
3. Introduce a new `lotus sync fetch` command to fetch a chain (to be
paired with `lotus chain sethead` followed by a `lotus sync checkpoint`. 
Changes:
1. Move the checkpointing logic into the chainstore so setting a checkpoint and syncing a different head can't race.
2. Re-enable checkpoint tests, fix, and expand them.
3. Rename `Sync.SetCheckpoint` to `Sync.SyncCheckpoint` and allow it to sync to a new fork.
4. Make `Chain.SetHead` unset any set checkpoints.
5. Reject checkpoints more than the fork limit in the past. …
=> feat: allow checkpointing to forks

.circleci/config.yml, Makefile, build/version.go, documentation/en/cli-lotus-miner.md, documentation/en/cli-lotus-worker.md, documentation/en/cli-lotus.md, scripts/generate-lotus-cli.py
Based on https://github.com/filecoin-project/lotus/pull/2467
=> Generate CLI docs

chain/actors/policy/policy.go, chain/gen/gen.go, miner/miner.go
Make the mining round chattier ( it should be ok: one extra message per epoch )
=> Add a mining-heartbeat INFO line at every epoch

.circleci/config.yml
Enables test, build, publish for all OS and network targets for release candidate tags in CI.
Re: #6030
=> chore(ci): Enable build on RC tags

.circleci/config.yml, scripts/publish-release.sh
- updates build environment to latest Ubuntu LTS (20.04).
- creates discussion in "announcements" category when tag doesn't contain `-rc[0-9]+$`
- only marks tags which do have `-rc[0-9]+$` as pre-release releases
- includes more output in build during release posting for future troubleshooting
Contributions toward #6030
=> fix(ci): Updates to lotus CI build process

cli/wait.go
=> fix: wait-api should use GetAPI to acquire binary specific API

node/modules/client.go
Fixes https://github.com/filecoin-project/lotus/issues/6265
=> Increase data transfer timeouts

extern/sector-storage/stores/index.go, extern/sector-storage/storiface/filetype.go
Addresses: https://github.com/filecoin-project/lotus/issues/6182
When a sector gets to the `FinalizeSector` state, currently Lotus tries to acquire ~500GB of storage on the location for storage, while it needs much less for the sector.
This code was proposed by @moremorefun (Thank you!!) and I think it is solving the issue.
=> consider storiface.PathStorage when calculating storage requirements

cli/cmd.go, cli/verifreg.go, documentation/en/cli-lotus.md
Addresses #5151 , though v5 actors integration is needed to close it.
=> Move verifreg shed utils to CLI

build/params_2k.go
This allows us to run a local devnet with 8MB sectors:
```
make debug && rm -rf ~/.devLotus && export LOTUS_PATH=~/.devLotus && rm -rf localnet.json &&  ./lotus-seed genesis new localnet.json  && ./lotus-seed pre-seal --sector-size 8388608 --num-sectors 2 && ./lotus-seed genesis add-miner localnet.json ~/.genesis-sectors/pre-seal-t01000.json && clear && ./lotus daemon --lotus-make-genesis=dev.gen --genesis-template=localnet.json --bootstrap=false
```
```
rm -rf ~/.lotusminer && export LOTUS_PATH=~/.devLotus && ./lotus wallet import ~/.genesis-sectors/pre-seal-t01000.key && ./lotus-miner init --genesis-miner --actor=t01000 --sector-size=8388608 --pre-sealed-sectors=~/.genesis-sectors --pre-sealed-metadata=~/.genesis-sectors/pre-seal-t01000.json --nosync && ./lotus-miner run --nosync
```
=> Allow 8MB sectors in devnet

chain/gen/gen.go, miner/miner.go
- A nil MiningBaseInfo is *NOT* unexpected: it happens when one is in penalty
https://github.com/filecoin-project/lotus/blob/v1.9.0/chain/stmgr/utils.go#L500-L502
- Remove the log from IsRoundWinner(): all we care about is the randbase epoch
Addresses https://github.com/filecoin-project/lotus/issues/6260
=> Fix logging around mineOne

documentation/en/jaeger-tracing.md, lib/tracing/setup.go
The reason for this PR is to make it easier to setup metrics in kubernetes environments.
in kubernetes, the IP address of the agent is not known until the pod starts, after which it can be made available as an environment variable. By that time, it is too late to append the port number.  When the agent endpoint is read in with a single environment variable, the best you can do is combine the host and port numbers as a bash script prior to starting lotus.
With this PR, the agent host and port can be read in with two environment variables without any bash shenanigans. 
Also, I added environment variables to support jaeger authentication, or sending directly to the collector.
=> separate tracing environment variables

lib/tracing/setup.go
This line was printed for commands where it was not relevant. This way, logs about tracing will only appear when they are enabled.
=> Remove log line when tracing is not configured

chain/gen/gen.go, chain/gen/genesis/miners.go, chain/store/index.go, chain/store/store.go, chain/store/store_test.go, chain/sync_test.go, chain/vm/runtime.go, chain/vm/vm.go, conformance/rand_fixed.go, conformance/rand_record.go, conformance/rand_replay.go, node/impl/full/chain.go
This is the larger but "better" fix to the critical portion of #3613.
=> Fix randomness fetching around null blocks

chain/events/events_called.go, chain/events/events_test.go
Got a reliable repro for the deals getting stuck in StorageDealAwaitingPreCommit issue when trying to debug https://github.com/filecoin-project/lotus/pull/6041 with rr (which runs with one thread, and makes everything slower).
Basically, we would ignore (Pre)Commit messages if there was more than one matching message from a miner in a given epoch. Normally we wouldn't hit this very often, but it was pretty common case of test flakiness. 
Fixes #6123
Fixes #5890
Fixes #5377
Fixes #2249 (probably)
=> events: Fix handling of multiple matched events per epoch

node/hello/hello.go
After the unification of all networks behind a build-tag, the amount of these
warnings has risen sharply. Reduce it to a debug-level, since it isn't actionable
to an operator.
=> Reduce noise from 'peer has different genesis' messages

miner/miner.go
Lots of cruft in this routine...
Tested on a block-producing nerpa miner that I didn't upset anything
=> Remove few useless variable assignments

api/test/deals.go, api/test/mining.go, chain/events/events_called.go, chain/events/events_test.go, cli/test/client.go, extern/storage-sealing/fsm.go, extern/storage-sealing/input.go, extern/storage-sealing/sealing.go, extern/storage-sealing/states_sealing.go, markets/storageadapter/ondealsectorcommitted.go, node/impl/storminer.go, node/node_test.go
Fixes #6013
Fixes #5077
Fixes #6010
=> storagefsm: Fix batch deal packing behavior

miner/miner.go
One extra piece missed in https://github.com/filecoin-project/lotus/pull/6310
=> Upscale mineOne message to a WARN on unexpected ineligibility

cli/cmd.go, cli/filplus.go, cmd/lotus-shed/verifreg.go, documentation/en/cli-lotus.md
=> Add verifreg utils to CLI

cli/state.go, documentation/en/cli-lotus.md
`./lotus state call` is currently unusable for most actor methods, as parameter parsing does not support many types.
This PR changes the `call` command to accept parameters as base64 or hex strings, as these formats are used extensively in other CLI commands.
Additionally, `call` has been changed to support multiple formats for message return:
* `decoded` (default): Returns JSON based on the return type of the method called
* `raw`: Returns the raw `[]byte` found in the receipt
* `hex`: Converts the returned data to hex
* `base64` Converts the returned data to base64
Here's an example:
```
alex-pc$ lotus state call --from f0127573 f0127595 23 RACipzE=
Call receipt:
Exit code: 0
Gas Used: 0
Return:
{}
alex-pc$ lotus state call f04 9
Call receipt:
Exit code: 0
Gas Used: 0
Return:
{ …
```
=> Improve the cli state call command 

chain/messagepool/messagepool.go, chain/messagepool/messagepool_test.go, chain/messagepool/provider.go, chain/messagepool/pruning.go, chain/messagepool/repub.go, chain/messagepool/repub_test.go, chain/messagepool/selection.go, chain/messagepool/selection_test.go, chain/messagesigner/messagesigner.go, chain/messagesigner/messagesigner_test.go, chain/stmgr/stmgr.go, chain/store/store.go, chain/sub/incoming.go, chain/sync.go, chain/sync_test.go, documentation/misc/actors_version_checklist.md, node/impl/full/gas.go, node/impl/full/mpool.go, node/modules/chain.go, node/modules/mpoolnonceapi.go
Basically changes various subcomponents to only think in terms of ID addresses (or key addresses).
Only open question is about Gateway:
- Will renaming mpool provider's `StateAccountKey` to `StateAccountKeyAtFinality` break the gateway?
- I guess there's no way to get it to use the stmgr's new finality lookback resolver without adding an explicit API call for it (urgh)
=> Improve address resolution for messages

api/test/verifreg.go, node/node_test.go, node/test/builder.go
In preparation of https://github.com/filecoin-project/lotus/issues/5151#issuecomment-841416830 for v5
=> Add test for AddVerifiedClient

cmd/lotus-gateway/main.go
The check command provides a quick way to try out different transports and verify that a connection can be made to a running gateway.
=> lotus-gateway: add check command

documentation/misc/gas_balancing.md
Resolves https://github.com/filecoin-project/lotus/issues/6186
I'll keep adding into there.
=> Add doc on gas balancing

.circleci/config.yml, AppImageBuilder.yml, scripts/build-bundle.sh, scripts/publish-release.sh
Build appimage and include it in the release.
The CI executor now is 20.04 so I updated the AppImage yaml to work  there.
I updated the release scripts to include the appimage. I have not run through the release to verify that the bundle and release scripts work so be extra cautious reviewing that.
EDIT:
I ran a dry run for the release step; looks like it will succeed.
=> build appimage in CI

api/test/deadlines.go, chain/stmgr/call.go, chain/sync_test.go, chain/vm/runtime.go, extern/sector-storage/mock/mock.go
This is the first part extracted from https://github.com/filecoin-project/lotus/pull/6386 so that we can have fixes for at least some of the flakiness in master.
=> Fix some flaky tests

cli/client.go
For https://github.com/filecoin-project/lotus/issues/5895.
=> Fix success handling in Retreival

testplans/Makefile, testplans/docker-images/Dockerfile.oni-buildbase, testplans/docker-images/Dockerfile.oni-runtime-debug, testplans/lotus-soup/init.go, testplans/lotus-soup/manifest.toml
This PR is:
1. Updating `lotus-soup` initialisation to not scale down the `WPoStChallengeWindow` - this results in preseal sectors in the bootstrapper node to fail the minimum deal duration validation (see https://github.com/filecoin-project/lotus/pull/6379). Given that we don't test PoSt faults at the moment, we don't really need to scale this window down at this stage. As soon as we introduce tests for faults, we will need to decide how to speed up the tests - either by using a fake clock, or by reducing these windows.
2. Updating the base and runtime docker images, that include the latest `filecoin-ffi` lib.
---
Tests are passing at: https://ci.testground.ipfs.team/tasks#taskID_c2uu7gt5p7ae493pkipg
=> testplans: lotus-soup: use default WPoStChallengeWindow

.github/workflows/testground-on-push.yml
github action v1.0 is not including the --metadata flags so the version information is displayed in testground. Upgrading the github action to a version that does.
=> upgrade testground action version

chain/stmgr/call.go, chain/stmgr/forks.go, chain/stmgr/forks_test.go, chain/stmgr/stmgr.go, chain/stmgr/tracers.go, chain/stmgr/utils.go, conformance/driver.go
Changes here are mostly mechanical -- moving things around to accommodate the new interface, `ExecMonitor`. `ExecMonitor` replaces the `ExecCallback` function in the stmgr. The motivation for this change is allowing a custom `ExecMonitor` interface to be injected for details message tracking while monitoring lotus.
=> polish(stmgr): define ExecMonitor for message application callback

extern/storage-sealing/commit_batch.go, extern/storage-sealing/precommit_batch.go, extern/storage-sealing/sealing.go, extern/storage-sealing/states_sealing.go, extern/storage-sealing/terminate_batch.go, node/config/def.go, storage/miner.go
Fixes https://github.com/filecoin-project/lotus/issues/6407
=> Fee config for sector batching

build/params_nerpanet.go, extern/storage-sealing/commit_batch.go, extern/storage-sealing/precommit_batch.go
Fixes #6412 
Two commits:
- Rename "deadlines" as requested by @jennijuju to avoid confusion with window post deadlines
- Split the `getSectorCutoff` methods between precommit and commit batchers
=> Commit and Precommit batcher cannot share a getSectorDeadline method

cmd/lotus-shed/export-car.go, cmd/lotus-shed/main.go
Add a lotus-shed command for exporting a car of an arbitrary dag.
Currently, we allow exporting tipsets, etc. But we don't have any convenient commands for simply exporting an arbitrary dag for analysis. This is useful for, e.g., analyzing bad actor states.
=> implement a command to export a car

chain/messagepool/messagepool.go, chain/sub/incoming.go, metrics/metrics.go
Should help with understanding if https://github.com/filecoin-project/lotus/issues/6396 is an issue outside network initialization
=> mpool: Add more metrics

cli/chain.go
Fixes #6293, changes the help text from (Default: 0) to (Default: current head)
=> Update chain list with correct help instructions

extern/storage-sealing/fsm.go, extern/storage-sealing/garbage.go, extern/storage-sealing/input.go, extern/storage-sealing/sealing.go
This caused TestDeadlineToggling (and likely other tests which pledged a bunch of sectors just after startup) to hang.
What happened was that before `Sealing.restartSectors` would run, some other place would start pledging a new sector, which would result in `restartSectors` sending a `SectorRestart` event, which would cause us to execute the sectors state planer twice, which then would result in the state planner getting duplicate events in wrong states.
=> sealing: Fix restartSectors race

.circleci/config.yml, extern/sector-storage/ffiwrapper/sealer_test.go
This test works when run individually, but broken when it runs with any other tests as proofs expect the call to FilInitLogFd to be the very first proofs call.
Probably acceptable to work around by just running this test individually in a separate step on Circle
=> Test multicore SDR support

api/v0api/full.go, cmd/lotus-shed/main.go, cmd/lotus-shed/miner-multisig.go, documentation/en/api-v0-methods.md
=> Add utils to use multisigs as miner owners

itests/ccupgrade_test.go, itests/kit2/node_opts_nv.go
=> Refactor ccupgrade test to use kit2

chain/sync_test.go
=> Expand on Drand change testing

chain/types/bigint.go, cli/state.go, cmd/lotus-shed/sync.go, cmd/lotus-storage-miner/info.go, cmd/lotus-storage-miner/proving.go, testplans/lotus-soup/rfwp/chain_state.go
Originally the deviations from using float64 were insignificant, but at
exabyte scale they start to show up. Cleanup all displays, and clarify
the expectation text, adding an extra 99.9% probability calculator to
`lotus-miner info`
Before:
After:
/cc @Kubuxu @nikkolasg
=> Adjust various CLI display ratios to arbitrary precision

itests/deadlines_test.go, itests/kit2/ensemble_opts.go, itests/kit2/node_opts.go, itests/kit2/node_opts_nv.go
Fails with
```
2021-06-17T14:56:17.610+0200	WARN	vm	vm/runtime.go:350	Abortf: failed to construct initial miner info: invalid partition sectors: unsupported proof type: 0
```
I'm not sure why because proof type 0 is RegisteredSealProof_StackedDrg2KiBV1, which is registered in the init method:
https://github.com/filecoin-project/lotus/blob/2c30ac394daa1706a1c75fcedeea4df90556dd95/itests/kit2/init.go#L17
=> Refactor deadline toggling test to kit2

chain/store/store.go
This likely was the cause of many tests hanging on CI for no apparent reason. Not sure if this can happen on real nodes, maybe with A LOT of deals (which use event handlers, which use reorg notifs).
There probably are better (but much more involved) ways to do this with more channels / goroutines, this is the simple fix.
=> chainstore: Don't take heaviestLk with backlogged reorgCh

README.md
Inital draft for basic build instructions on the Readme page. Issue: #6348
=> Initial draft: basic build instructions on Readme

cli/client.go, documentation/en/cli-lotus.md
I'm pretty sure this is correct based on current markets. The helptext was introduced in a PR accompanied by a markets change (https://github.com/filecoin-project/go-fil-markets/pull/491), but that change was then reverted for breaking backwards compatibility.
=> Fix helptext

extern/storage-sealing/commit_batch.go, extern/storage-sealing/precommit_batch.go, extern/storage-sealing/sealiface/config.go, node/config/def.go, node/modules/storageminer.go
Might add a test, but here's a PR.
Fixes #6541
=> Always flush when timer goes off

node/builder.go, node/config/def.go, node/modules/dtypes/miner.go, node/modules/storageminer.go
Fixes https://github.com/filecoin-project/lotus/issues/6575
=> Add miner-side MaxDealStartDelay config

cli/multisig.go
Only 5 parameters are needed to call lock-cancel command, which can be seen in line 1432
=> Fix an error in msigLockCancel

extern/storage-sealing/states_sealing.go
Here, 10 epoch is no longer satisfied because it mostly will sleep more than 10 epochs in batch submit pre-commit, so I suggested it should scale up to the longest time that pre-commit ticket expired at
=> scale up sector expiration to avoid sector expire in batch-pre-commit waitting

extern/storage-sealing/commit_batch.go, extern/storage-sealing/precommit_batch.go
The original batchwait would cause a timer instance to be created for each round of the for loop。
=> Reuse timers in sealing batch logic

extern/storage-sealing/states_failed.go
it makes no sense to check pre-commit info in`handleCommitFailed`, in the test we find that `checkPrecommit` will throw an `ErrExpiredTicket` easily because the expiration of proveCommit change to 30, that will cause the good sector to be removed. 
I've noticed these are old codes. Is there any other reason to check pre-commit now?
=> remove precommit check in handleCommitFailed

extern/storage-sealing/states_sealing.go
fix ticket expiration check, otherwise it may cause a large number of loops to retry GetTicket when retrying PreCommit1；
Because there may be C1 and C2 execution failures, and after they retries more than a certain number of times,  will cause PreCommit1 to be re-executed, and now it is the submission period of 30, so it will cause an endless loop of repeated execution of GetTicket.
=> fix ticket expiration check

.circleci/config.yml, cmd/lotus-seal-worker/storage.go, cmd/lotus-storage-miner/storage.go, extern/sector-storage/manager.go, itests/deals_test.go, itests/kit/node_miner.go, itests/sector_finalize_early_test.go, node/modules/storageminer.go
This fixes the case where sectors could be moved in one call to Finalize to a long-term storage, and then fail in second call to Finalize because we expected to find those files still in sealing storage
Related to https://github.com/filecoin-project/lotus/pull/6651 and https://github.com/filecoin-project/lotus/pull/6649
=> storage: Fix FinalizeSector with sectors in stoage paths

go.mod
This is no longer used anywhere in lotus
=> Remove leftover from the great de-submoduling

markets/retrievaladapter/provider.go, markets/retrievaladapter/provider_test.go
Closes https://github.com/filecoin-project/lotus/issues/6678.
We iterate over all storage deals for a payload to see if we have a verified storage deal with the required PieceCID to fetch the input for the retrieval pricing function. This PR introduces a fix so we don't error out in we fail to look up a deal state and just continue iterating over the other deals.
=> Get retrieval pricing input should not error out on a deal state fetch

chain/state/statetree.go, node/impl/full/state.go
- this operation can take a while, this change gives users the option
to abort if it takes "too long".
Motivation: this operation takes a while for sentinel to perform, we'd like to abort if it takes too long.
@iand if this looks alright to you I'll tag lotus devs for a second look
=> polish(statetree): accept a context in statetree diff for timeouts

cmd/lotus-seed/genesis.go
`actor.code` cids of type `v1 - raw - identity` were breaking car generation.
=> fix "lotus-seed genesis car" error "merkledag: not found"

go.mod, go.sum
No more stuff like: https://circleci.com/gh/filecoin-project/lotus/189136
=> Stop outputing ANSI color on non-TTY

miner/miner.go
Maybe we merge this? Maybe we don't.
=> Envvar to disable slash filter

cmd/lotus-shed/election.go
./lotus-shed election backtest t01000
height, winCount
223, 5
222, 10
221, 5
220, 7
219, 5
... ...
./lotus-shed election backtest -h
NAME:
lotus-shed election backtest - Backtest elections with given miner
USAGE:
lotus-shed election backtest [command options] [minerAddress]
OPTIONS:
--height value  blockchain head height (default: 0)
--count value   blockchain count (default: 120)
--help, -h      show help (default: false)
=> add election backtest

cmd/lotus-storage-miner/sectors.go
Fix bugs described in #6027 
Based on the work of #6033
=> Fix bugs in sectors extend --v1-sectors

node/impl/client/client.go
fix #6738
Check for deal status cancelled when inspecting deal events in ClientRetrieve and ClientRetrieveWithEvents, and close channel when that happens.
=> ClientRetrieve stops on cancel

.circleci/config.yml, extern/storage-sealing/commit_batch.go, extern/storage-sealing/mocks/mock_commit_batcher.go, extern/storage-sealing/mocks/mock_precommit_batcher.go, extern/storage-sealing/precommit_batch.go, extern/storage-sealing/sealiface/config.go, extern/storage-sealing/sealing.go, extern/storage-sealing/states_sealing.go, extern/storage-sealing/utils.go, itests/deals_pricing_test.go, itests/sector_miner_collateral_test.go, node/config/def.go, node/modules/storageminer.go, storage/adapter_storage_miner.go, storage/miner.go
=> Config for collateral from miner available balance

cmd/lotus-shed/storage-stats.go
This is the backend feeding storage.filecoin.io , we might get to use this soon
=> Add current power to the stats

blockstore/badger/blockstore.go, blockstore/blockstore.go, blockstore/splitstore/splitstore.go, blockstore/splitstore/splitstore_gc.go
Cherry-picked from #6728 
- Fixes a couple of inconsistencies identified post merge
- Introduces BlockstoreGC and BlockstoreMover interfaces in preparation for moving GC in #6728
- Adds a compactionIndex state variable to use as decision for moving gc (where applicable) and also a warmup indicator for splitstore v0 upgrades.
=> Splitstore: Some small fixes

chain/stmgr/forks_test.go
Otherwise, this fails on rare occasions.
=> test: handle null blocks in TestForkRefuseCall

go.mod, go.sum
We were somewhere in between, and this includes a couple of important bug fixes and improvements.
Let's give it some burn in v1.11.1!
=> update go-libp2p-pubsub to v0.5.0

.github/CODEOWNERS
Per updated CR policies for this repo, we want non-draft PRs to be assigned to the filecoin-project/lotus-maintainers team.
=> Resurrect CODEOWNERS, but for maintainers group

lib/rpcenc/reader.go
Closes https://github.com/filecoin-project/lotus/issues/6792
---
Fixes the panic described in the issue. Clients are reading up until EOF error, and at that point if `Close()` is called, the process was crashing.
=> wrap close(wait) with sync.Once to avoid panic

itests/wdpost_test.go
Wait until the network upgrade is finished. If we try to seal while it's happening, we have a few annoying edge cases that can fail if we try to submit some messages right on the upgrade epoch (which is why everyone turns that kind of stuff off for the upgrade epoch).
=> test: fix flaky window post tests

node/impl/client/client.go
This PR is fixing `ClientFindData` when data about peers in the local store of a node is out-dated.
---
If a client makes a deal with a miner, it keeps the miner's peer id in a local store. In the future if the miner changes its peer id, and the client tries to retrieve the content (datacid), `ClientFindData` would still be trying to reach the miner on its old peer id, ultimately failing.
This is manifested with `Failed to find file` error in the CLI:
```
➜  lotus git:(master) lotus client retrieve $datacid /tmp/file1234
Failed to find file
```
=> ClientFindData: always fetch peer id from chain

cli/state.go, cmd/tvx/extract_message.go, itests/api_test.go
It returns nil on "not found".
Fixes the cases not covered in: https://github.com/filecoin-project/lotus/pull/6787
=> fix: always check if StateSearchMessage returns nil

go.mod, go.sum, markets/dagstore/wrapper.go, markets/dagstore/wrapper_test.go
DAGStore PR at https://github.com/filecoin-project/dagstore/pull/81.
- Run GC and trace logging in separate go-routines to avoid blocking the dag store event loop.
- Solve the (recover -> failure -> recover) infinite loop by using the dagstore utility that caps maximum recover attempts.
Also, we no longer do failure recovery in the wrapper. The dagstore utlility will take care of it .
- When the DAG Store starts-up, ask it to schedule lazy recovery for all shards in the error state. These shards will be recovered/indexed when they are first accessed.
- Add some logging. Can never have enough logging.
=> Fix bugs in the DAGStore wrapper

markets/retrievaladapter/provider.go, storage/miner_sealing.go
This PR is fixing a bug introduced in https://github.com/filecoin-project/lotus/pull/6356
---
As part of MRA, we modified `UnsealSector` to use `SectorBuilder.SectorsStatus` API (RPC from `markets` node to `sealing/proving` node), instead of a local call `rpn.miner.GetSectorInfo(sectorID)`
Given that we always call `sectorsStatus` with `onChainInfo == true`, we currently get an error for all sectors that are not yet on-chain (i.e. currently in PreCommit1 phase for example).
This results in a regression - a failure of all retrievals for deals on sectors that are not yet on chain.
---
With this PR, I am modifying the call to `sectorsStatus` to not use on-chain data, but also making sure that `SealProof` is initialised correctly based on data from the local store, and not just to 0.
=> add SealProof in SectorBuilder

node/repo/fsrepo.go
This is a redux of https://github.com/filecoin-project/lotus/pull/5050
Allows the user to control the opts.SyncWrites option of BadgerDs, with the tri-state environment variable `LOTUS_CHAIN_BADGERSTORE_DISABLE_FSYNC`
- unset == the default (currently fsync enabled)
- set with a false-y value ( `""`, `"0"`, `"no"`, `"false"` ) == fsync enabled no matter what a future default is
- set with any other value == fsync is disabled ignored defaults (recommended for day-to-day use)
Applying this brought @whyrusleeping's average chain validation times from "impossible to sync" ( > 30s ) down to 1~3s/tipset
=> Introduce the LOTUS_CHAIN_BADGERSTORE_DISABLE_FSYNC envvar

chain/events/events_called.go, chain/events/events_test.go
GetBlockMessages Is a high-load API, use cache to reduce network traffic
=> cache loaded block messages

blockstore/splitstore/splitstore_compact.go, blockstore/splitstore/splitstore_warmup.go
this was accidentally broken in #6775.
=> fix warmup by decoupling state from message receipt walk

chain/sync.go, chain/sync_test.go
Thanks to @zgfzgf for the fix! Overhauls #4091.
=> ValidateBlock: Assert that block header height's are greater than parents

blockstore/splitstore/splitstore_test.go, blockstore/splitstore/splitstore_warmup.go
While testing the `check` command in #6811 it was observed (to my great surprise) that my discard node actually has some cold references, dating back to the original snapshot.
So it appears that the warmup is not capturing all references that it should.
This improves the situation by traversing a full finality worth of state during warmup.
=> Improve splitstore warmup

itests/batch_deal_test.go, itests/deals_offline_test.go, itests/deals_power_test.go, itests/deals_publish_test.go, itests/kit/deals.go
This allows one to use the harness for much more versatile deal conditions
=> Rewire itest's StartDeal to take the full API struct

chain/events/state/predicates_test.go, go.mod, go.sum
Snake through a fix for a subtle test failure. Incorporates https://github.com/filecoin-project/specs-actors/pull/1463#issue-680772451
=> Bump go-multihash, adjust test for supported version

cmd/lotus-shed/market.go
This PR is adding commands to `lotus-shed` so that miners can rollback from a multi-process architecture - one where part of the repo metadata datastore is located on the `markets` node, and part of it on the sealing/proving node.
During rollback, we need to copy back all the relevant metadata keys/values back to the monolith repo metadata datastore.
---
TODO:
=> lotus-shed: initial export cmd for markets related metadata

chain/state/statetree.go, chain/stmgr/stmgr.go, chain/store/messages.go
StateTree is failing to load for Lily is processing the chain. Make these errors more informative.
=> polish(errors): better state tree errors

cli/mpool.go, documentation/en/cli-lotus.md
Do suggested fix for #5109 author @wenzhenxiang
=> PR #5109 + suggested fix

node/impl/full/mpool.go
This was discovered while reviewing the mysterious pr #4462; the intent of the code is to exclude messages that have already been included in blocks at the same height. Unfortunately, the code used `ts` instead of `mpts` rendering it effectively a noop.
This fixes the bug and adds a comment.
Note: the bug is not correctness critical, as selection is more intelleigent at picking pending messages.
Closes #4462.
=> fix bug in MpoolPending message exclusion

build/params_butterfly.go, build/params_nerpanet.go, build/version.go
Add "Build Type" to nerpanet and butterfly.
I am not sure if these were intentionally left out. If they were, we can just close this.
The impetus of this PR is to allow people doing tests on nerpanet to be able to see what network they are on by running `lotus version`
This includes all the networks in our docs https://network.filecoin.io/
=> set buildtype in nerpa and butterfly

go.mod, go.sum
=> update go-libp2p-pubsub to v0.5.4

cli/util/api.go
This PR is adding an explicit error in case someone tries to run CLI pointed at incorrect repo location. We had a lot of confusion with this yesterday, given that miners are now running multiple miner instances on one host.
```
➜  lotus git:(nonsense/better-error-on-wrong-repo-location) ./lotus-miner info
ERROR: could not get API info: could not get api endpoint: API not running (no endpoint)
➜  lotus git:(nonsense/better-error-on-wrong-repo-location) LOTUS_MINER_PATH=~/smthwrong ./lotus-miner info
ERROR: could not get API info: repo directory does not exist. Make sure your configuration is correct.
```
=> add explicit error msg if repo dir does not exist

blockstore/splitstore/README.md, cmd/lotus-shed/splitstore.go
This is very useful when the splitstore/chain is linked in volatile storage and the user wants to restart from a new snapshot.
=> lotus-shed splitstore clear command

go.mod, go.sum, markets/dagstore/wrapper.go, markets/dagstore/wrapper_migration_test.go, markets/dagstore/wrapper_test.go, node/config/def.go, node/config/doc_gen.go, node/config/types.go, node/modules/storageminer.go, node/modules/storageminer_dagstore.go
Migration registers all shards with lazy init.
Shards are then initialized as they are retrieved for the first time, or in bulk through a lotus-shed tool that will be provided separately.
=> pull dagstore migration into Lotus and simplify.

markets/storageadapter/dealpublisher.go, markets/storageadapter/dealpublisher_test.go, markets/storageadapter/provider.go
fixes #6799
(wanted to see if the issues were related to event handling, but they aren't)
=> fix flaky TestDealPublisher and re-enable

extern/storage-sealing/commit_batch.go
When I lost proof file，Cannot locate the problem due to insufficient error info
=> fix: more logging in maybeStartBatch error

chain/actors/policy/policy.go, chain/actors/policy/policy.go.template, chain/actors/version.go, chain/gen/genesis/genesis.go, chain/gen/genesis/miners.go, chain/vm/invoker.go, chain/vm/mkactor.go, cmd/lotus-miner/sectors.go, cmd/lotus-sim/simulation/blockbuilder/blockbuilder.go, cmd/lotus-sim/simulation/stages/funding_stage.go, cmd/lotus-sim/simulation/stages/provecommit_stage.go, extern/storage-sealing/commit_batch.go, extern/storage-sealing/states_sealing.go, node/impl/full/multisig.go, node/impl/full/state.go, paychmgr/paych.go, storage/wdpost_run.go
Will mostly fix #6898 when it compiles. (at least, will prevent things from panicking and give the user more of an idea of what is going wrong).
=> Dont panic if input is bad

cli/cmd.go, cmd/lotus-miner/main.go
The libp2p host on the miner is now only started where the markets subsystem runs. This PR makes `lotus-miner net` commands hit the node where the markets subsystem is running.
Honestly, `Net` no longer belongs in the `Common` commands, nor should the endpoint be resolved through `GetCommonAPI`/`GetAPI`, but there is some larger untangling to do to tidy this up, and it's associated with pre-existing tech debt.
Choosing not to do it now, as there are other decisions to make first with regards to providing the optimal UX experience for miners, now and as we introduce more miner services.
---
Testing: unfortunately we don't have a decent framework/suite for CLI testing. All itests hit the JSON-RPC API or the native API. So I can't add a test for this. Instead, I performed manual testing and …
=> make `lotus-miner net` commands hit markets subsystem.

cli/util/api.go, itests/kit/client.go, itests/kit/mockcli.go, itests/multisig/suite.go, itests/paych_cli_test.go
Related to #7012 #7020 I've been thinking that a step in the right direction is to enforce that new nodes are talking to the same API version both v0 and v1.  This won't help the problem of needing to support backwards compatibility for the v0 api for older coder versions but it will prevent nodes from this point onwards from getting too far and erroring in confusing ways when attempting to work against different api versions.
I put this up (1) to see if it breaks CI in interesting ways (2) to get the opinion of @filecoin-project/lotus-maintainers @whyrusleeping and @raulk.
=> Strict major minor version checking on v0 and v1 apis

cli/auth.go, cli/pprof.go, cli/util/api.go
This PR is adding the RepoType for the node we are trying to get endpoint to.
This is helpful because with MRA and https://github.com/filecoin-project/lotus/pull/6936 we now have some CLI commands (such as `lotus-miner info`) needing to connect to 3 different API endpoints, and it'd be easier to know which connection out of the 3 cannot be established.
Related: https://github.com/filecoin-project/lotus/issues/7072
=> improve get api error messages

cmd/lotus-miner/sectors.go, documentation/en/cli-lotus-miner.md
New cli tools for managing sectors expiration:
- `check-expire`, facilitates insepection of expiring sectors
- `renew`, a more practical alternative to `extend` with the following features:
- can automatically extend sectors of all kinds of seal proof, not just v1 ones
- can mannully provide sector numbers in a file
- can choose from 2 extending schemes: a relative extension or an uniform new expiration
- will take care of `SectorMaxLifetime` and `MaxSectorExpirationExtension`
- fast search of sector location
- can specify max-fee to avoid message congestion
=> Extending sectors: more practical and flexible tools

cmd/lotus-miner/init.go, node/modules/storageminer.go, node/repo/memrepo.go
Closes https://github.com/filecoin-project/lotus/issues/5291
=> feat(miner deals): create subdir to miner repo for staged deals

go.mod, go.sum
Upgrading dagstore to v0.4.3, and transitives.
=> upgrade upstream dependencies.

node/impl/storminer.go
A value+error can get routed there from https://github.com/filecoin-project/lotus/blob/master/extern/storage-sealing/input.go#L214, which will make go-jsonrpc hide the real error, and instead it will complain about value+error being returned
=> Fix error handling in SectorAddPieceToAny api impl

lib/rpcenc/reader.go, lib/rpcenc/reader_test.go
Includes docs and tests!
This should allow market processes to send piece bytes directly to workers
---
Closes https://github.com/filecoin-project/lotus/issues/7107
=> rpcenc: Support reader redirect 

.codecov.yml
=> Codecov Projects

go.mod, go.sum
- Use `go-graphsync` [v0.6.9](https://github.com/ipfs/go-graphsync/releases/tag/v0.6.9) -> has the [Graphsync OOM fixes](https://github.com/ipfs/go-graphsync/commit/2532859c3ef0b9912265fba1671f14dd7b87231f).
- Use `go-data-transfer `  [v1.7.6](https://github.com/filecoin-project/go-data-transfer/releases/tag/v1.7.6) -> has logging for the transfer Complete messages.
- Use `go-fil-markets` [v1.8.1](https://github.com/filecoin-project/go-fil-markets/releases/tag/v1.8.1).
=>  Update markets, dt and graphsync

itests/deals_concurrent_test.go
See https://github.com/filecoin-project/lotus/issues/7152 for details.
=> test: disable flaky TestSimultaneousTransferLimit

node/impl/storminer.go
=> Ignore nil throttler

chain/actors/builtin/miner/actor.go.template, chain/actors/builtin/miner/miner.go, cmd/lotus-miner/sectors.go, documentation/en/cli-lotus-miner.md
We should make this automatic at some point, but this is at least a good tool to manage expired sectors
`--show-removed` output:
The 'actually remove things' output:
=> miner: Command to list/remove expired sectors

.circleci/config.yml, itests/api_test.go, itests/deals_512mb_test.go, itests/kit/ensemble.go, itests/kit/ensemble_opts.go, itests/kit/init.go, itests/kit/node_opts.go, itests/kit/sectors.go
Up until now, itests has been limited by the 2KiB sector size. It has been impractical to use larger sizes because we would go download the proof parameters, even if using mock proofs.
This PR:
1. introduces the ability to specify the sector size as a `Miner` `NodeOpt`.
2. introduces sugar to enable large sectors in the policy (concretely 512MiB sectors).
3. adds a test that performs a 64MiB deal.
4. allows us to specify arbitrary sector sizes on genesis (before, we would ignore the relevant NodeOpt).
Now that we can perform deals with more interesting sizes, we should look into the following:
- performing deals without writing files on disk (constructing a random DAG in memoroy, for example)
- adjusting the test kit to introduce deal size as a first-class parameter -- right now it's not …
=> itests: support larger sector sizes; add large deal test.

itests/batch_deal_test.go
=> test: disable flaky TestBatchDealInput

markets/storageadapter/dealpublisher.go
This test _should_ be mostly deterministic, but is still failing. I _believe_ this is because:
1. We record the "start" time before starting the timer.
2. In the test, we increment the clock till right after the timer should fire, if the timer start time matches the recorded start time.
3. If we happen to advance the mock clock between recording the time and starting the timer, the timer will never fire.
Unfortunately, I can't reproduce this locally (at all) so I'm mostly just guessing.
=> fix TestDealPublisher

node/impl/storminer.go
Address https://github.com/filecoin-project/lotus/pull/7169#discussion_r695597163.
=> dagstore/InitializeAll: Fix throttling bug for concurrency=0

cmd/lotus-miner/sealing.go
We have a report for a panic at:
```
panic: strings: negative Repeat count
goroutine 1 [running]:
strings.Repeat(0x37e2a10, 0x1, 0xffffffffffffffdf, 0x0, 0x0)
/usr/local/go/src/strings/strings.go:529 +0x5e5
main.glob..func55(0xc000a51bc0, 0x0, 0x0)
/home/reiers/lotus/cmd/lotus-miner/sealing.go:103 +0xa08
github.com/urfave/cli/v2.(*Command).Run(0x4c210a0, 0xc000a51ac0, 0x0, 0x0)
/home/reiers/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/command.go:164 +0x4dd
github.com/urfave/cli/v2.(*App).RunAsSubcommand(0xc000702f00, 0xc000a518c0, 0x0, 0x0)
/home/reiers/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:427 +0xa49
github.com/urfave/cli/v2.(*Command).startApp(0x4c21520, 0xc000a518c0, 0x7ffe9a138055, 0x7)
/home/reiers/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/command.go:279 +0x6bb …
```
=> call string.Repeat always with positive int

chain/types/electionproof_test.go, chain/vectors/vectors_test.go
1. Rewrite VRF test to actually test win counts, and enable it.
2. Stop skipping some tests that now pass.
=> test: re-enable disabled tests

extern/sector-storage/stores/local.go
(also upgrade the log to Warn when we see real errors)
=> stores: Fix reserved disk usage log spam

chain/actors/builtin/miner/actor.go.template, chain/actors/builtin/miner/miner.go, chain/actors/builtin/miner/state.go.template, chain/actors/builtin/miner/v0.go, chain/actors/builtin/miner/v2.go, chain/actors/builtin/miner/v3.go, chain/actors/builtin/miner/v4.go, chain/actors/builtin/miner/v5.go, cmd/lotus-miner/sectors.go
Without this we'd say that sectors which were not PoSt-ed yet were already expired.
=> sectors expired: Handle precomitted and unproven sectors correctly

chain/stmgr/call.go, chain/stmgr/execute.go, chain/stmgr/forks.go, chain/stmgr/forks_test.go, chain/stmgr/utils.go
Also improve/fix documentation to reflect the _actual_ tipset that's passed into upgrades.
And update some comments.
fixes #7192
=> fix: correctly handle null blocks when detecting an expensive fork

extern/storage-sealing/fsm.go, extern/storage-sealing/fsm_test.go, extern/storage-sealing/states_sealing.go
Without this if something about the sector would be broken in a way which caused `m.commiter.AddCommit` to instantly error (e.g. sector expired), we'd blindly retry with no delay, causing tons of log spam and fsm io.
Fixes #7057
=> sealing: Fix retry loop in SubmitCommitAggregate

extern/storage-sealing/sector_state.go, extern/storage-sealing/stats.go
=> sealing: Fix sector state accounting with FinalizeEarly

go.mod, go.sum
Fixes in this version of markets:
- go-fil-markets [Reject storage deals where the end epoch is too far in the future](https://github.com/filecoin-project/go-fil-markets/pull/612)
- go-data-transfer [Ensure graphsync transport only closes complete channel once](https://github.com/filecoin-project/go-data-transfer/pull/250)
=> update to go-fil-markets v1.11.0

cmd/lotus-miner/sectors.go, documentation/en/cli-lotus-miner.md
Depends on https://github.com/filecoin-project/lotus/pull/7261
This PR adds an `--unproven` flag to `lotus-miner sectors list`, which makes it print only sectors which are being sealed. It also is a lot faster than printing all sectors.
=> Add --unproven flag to the sectors list command

.circleci/config.yml, itests/deals_max_staging_deals_test.go, itests/kit/deals.go, itests/kit/ensemble.go, itests/kit/node_opts.go, node/builder_miner.go, node/config/doc_gen.go, node/config/types.go, node/modules/storageminer.go
This PR is introducing a `MaxStagingDealsBytes` config - if the markets repository `deals-staging` directory gets too large, the markets node can now be configured to reject new incoming deals.
A stopgap for https://github.com/filecoin-project/lotus/issues/7241
---
TODO:
=> introduce MaxStagingDealsBytes - reject new deals if our staging deals area is full

markets/storageadapter/dealpublisher.go, markets/storageadapter/dealpublisher_test.go
Should fix https://github.com/filecoin-project/lotus/issues/7206
=> dealpublisher: Fully validate deals before publishing

itests/deals_max_staging_deals_test.go
Fixes flaky test introduced in https://github.com/filecoin-project/lotus/pull/7276
In-memory repo is using the MapDatastore, which doesn't return sorted CIDs list for imported files into Filecoin, hence we got a flaky test for the second comparison for the second deal.
I am removing the CID comparison here altogether, as this is somewhat independent from what this test is testing.
=> itests: remove cid equality comparison

go.mod, go.sum
This is simply a graphsync bug fix release, but the bug fix is fairly critical. You can see how it manifests over in go-data-transfer, which we added a test to to demonstrate the issue and fix
=> Update go-graphsync v0.9.1

cmd/lotus-seed/main.go
Also change to a Uint since that's what we parse in the body
=> Seed: improve helptext

.circleci/config.yml, .circleci/template.yml
jq is already installed now in either a newer version of CircleCI's MacOS VMs or in a previous CI step.
I ran a failing macos job with ssh enabled, and inspected '/usr/local/bin' and found found the following output
lrwxr-xr-x    1 distiller  admin    23 Jun 22 14:50 jq -> ../Cellar/jq/1.6/bin/jq
the existing symlink causes the 'Install jq' job to fail.
removing this job should resolve the issue
=> remove job to install jq

go.mod, go.sum
closes #6640 
See change in https://github.com/filecoin-project/go-paramfetch/pull/17 for details.
=> fix: Enforce verification key integrity check regardless of TRUST_PARAMS=1

extern/storage-sealing/states_failed.go
The check below is new, but apparently could cause a panic
=> fix a panic in HandleRecoverDealIDs

extern/sector-storage/sched.go, extern/sector-storage/sched_worker.go, extern/sector-storage/stats.go
Mostly just untangling some tech debt to make it easier to add better smarts around starting work.
=> storagemgr: Cleanup workerLk around worker resources

.circleci/config.yml, .circleci/template.yml, scripts/version-check.sh
=> feat(ci): include version/cli checks in tagged releases

extern/storage-sealing/states_failed.go, extern/storage-sealing/states_failed_test.go
Fixes: https://github.com/filecoin-project/lotus/issues/7345
---
When `GetCurrentDealInfo` returns an error, such as:
```
return nil, xerrors.Errorf(
"deal %d not found "+
"- deal may not have completed sealing before deal proposal "+
"start epoch, or deal may have been slashed",
dealID)
```
we should just note that we can't recover that deal, mark it as failed, and later remove the sector.
At the moment when `GetCurrentDealInfo` returns an error, we continue below the if-condition check for err and we throw a nil pointer exception and crash.
=> GetCurrentDealInfo err: handle correctly err case

node/modules/storageminer.go
This PR is fixing the OS specific separator that was introduced in https://github.com/filecoin-project/lotus/pull/7276 and properly building up the deals staging area path.
=> fix staging area path buildup

.github/workflows/sync-master-main.yaml
This will forcefully update the branch `main` to the git ref that triggered the workflow. This will keep the branch `main` in sync with the branch `master` at all times.
This requires that workflows have write permissions (which I believe they already do).
---
_address the first item in #7356_
=> sync branch main with master on updates

scripts/version-check.sh
Noticed the CI check delivered in https://github.com/filecoin-project/lotus/pull/7331 had [a bug](https://app.circleci.com/pipelines/github/filecoin-project/lotus/17357/workflows/841481df-6e0c-497f-ad75-4015c9d81126/jobs/271837). This is the fix.
=> fix: escape periods to match actual periods in version 

cmd/lotus-miner/market.go, documentation/en/cli-lotus-miner.md
This PR is updating the `lotus-miner storage-deals list` cmd to print out storage deals together with their respective transfers, for easier debugging - only when using `--format=json`. At the moment fetching storage deals and transfers is done via two separate commands and somewhat cumbersome to use given the tab-delimited tables.
`--format=json` prints out results in line-delimited JSON, which I think is much easier to read than the `table` approach we use in many commands, because:
1. Field type is right next to every value (given that we generally have 100s-1000s of deals):
```
{"datetime":"2021-09-10T00:57:41+03:00","verified-deal":true,"proposal-cid":"bafyreif5yiywi6njej3nz2uwrj6yo2dnrc7mnokk3qhhfc6m46efpurmay","deal-id":0,"deal-status":"StorageDealTransferring","client":"f3vnq2cmwig …
```
=> add `lotus-miner storage-deals list --format=json` with transfers

chain/store/store.go
See https://github.com/filecoin-project/FIPs/pull/156
Closes #2981
=> ChainStore: Add a tiebreaker rule for tipsets of equal weight

build/panic_reporter.go, build/version.go, cli/helper.go, cmd/lotus-miner/main.go, cmd/lotus-seal-worker/main.go, cmd/lotus/main.go, go.mod, go.sum
an attempt at #7315
Room for improvement?
- ~expose [journal lookback param](https://github.com/filecoin-project/lotus/pull/7341/files#diff-3c77b768688af24630531611dce1d0271ad9f14cbbb2b4fc893ffaa5fec406a4R25) as envvar~ done
- report rotation param and exposing as envvar?
- dump more things?
- maybe don't catch such a broad surface and find more narrow scopes to recover from?
- make each report optional (similar to GOLOG_LOG_LEVEL_NAMED)?
=> feat: Catch panic to generate report and reraise

documentation/en/default-lotus-miner-config.toml, extern/storage-sealing/input.go, extern/storage-sealing/sealiface/config.go, markets/storageadapter/dealpublisher.go, node/builder_miner.go, node/config/def.go, node/config/doc_gen.go, node/config/types.go, node/modules/storageminer.go
Should fix: https://github.com/filecoin-project/lotus/issues/5137
---
This PR is:
1. Adding a check for deal start epoch in `SectorAddPieceToAny`.
2. Adding an epoch buffer `StartEpochSealingBuffer` to both `SectorAddPieceToAny`, as well as to `validateDeal` prior to sending a `PublishStorageDeals` message, to account for some time necessary to seal a sector.
At the moment I have added `StartEpochSealingBuffer` to be 480 by default == which is 4 hours, and I think this is reasonable. I am not sure if there are miners out there that go from `PublishStorageDeals` to a sealed sector faster than 4 hours...
=> check for deal start epoch on SectorAddPieceToAny

extern/sector-storage/ffiwrapper/sealer_test.go
See https://github.com/filecoin-project/rust-fil-proofs/blob/master/CHANGELOG.md#1000---2021-09-30
This release should make computing proofs a lot faster, especially when using the new CUDA feature (`FFI_USE_CUDA=1 FFI_BUILD_FROM_SOURCE=1 ...`)
=> Update proofs to v10.0.0

node/config/def.go, node/impl/client/client.go, node/modules/client.go, node/modules/graphsync.go, node/modules/storageminer.go
Set reasonable limits on number of links traversed while calculating commP & doing go-graphsync transfers
Blockers:
- update go-graphsync and go-car and go-fil-markets
- set a config.MaxTraversalLinks
- allow it to be overridden via ENV
- pass to initialization code for markets & go-graphsync
=> Limit maximum number of DAG links to traverse

chain/gen/gen.go, chain/stmgr/searchwait.go, chain/stmgr/searchwait_test.go
Fixes #7009 
Also fixes all uses of `StateSearchMsg` with `allowReplaced` set to false.
=> StateSearchMsg: Correct usage of the allowReplaced flag

cmd/lotus-shed/main.go, cmd/lotus-shed/miner-peerid.go
For @dkkapur 
Usage: `lotus-shed miner-peerid <peerId> <stateRoot>`
=> Shed: Add a util to find miner based on peerid

go.mod, go.sum
release notes: 
- https://github.com/libp2p/go-libp2p-pubsub/releases/tag/v0.5.6
- https://github.com/libp2p/go-libp2p-pubsub/releases/tag/v0.5.5
=> update go-libp2p-pubsub to v0.5.6

cli/wait.go, documentation/en/cli-lotus-miner.md, documentation/en/cli-lotus.md
This should maintain the same behavior, except with a change that an error `ERROR: context canceled` will be printed when the command is killed with ctrl-c, as opposed to no error prior.
=> add timeout flag to wait-api command

cmd/lotus-shed/msg.go
Very useful when viewing msig propose messages which call methods on other things
=> lotus-shed msg: Decode submessages/msig proposals

Dockerfile.lotus
This was causing excessive logging when jaeger wasn't available.
When it is available, you can add these env vars on your own, but usually best to leave them unset.
fixes: https://github.com/filecoin-project/lotus/issues/7502
=> remove jaeger envvars

Dockerfile.lotus, docker-compose.yaml
Having `MINER_API_INFO` and `FULLNODE_API_INFO` set by default force read-only mode and restricted the ability for broader usage of the docker files produced for general consumption
=> remove api and jaeger env from docker file

storage/wdpost_changehandler.go
This confidence was introduced in https://github.com/filecoin-project/lotus/pull/5764 as a stopgap until https://github.com/filecoin-project/lotus/issues/3613 was fixed, which happened in the chocolate upgrade.
It is now strictly unnecessary and the 5 minutes can be spent on PoSt computation. We could kill it entirely, or leave it at 1 epoch.
=> Wdpost worker: Reduce challenge confidence to 1 epoch

cmd/lotus-shed/balancer.go, cmd/lotus-shed/main.go
Small util to automatically manage balances in multiple wallets. Useful with multiple control addresses.
Maybe someday this will become it's own thing / live in lotus, but for now shed seems to be a good enough place.
=> shed: simple wallet balancer util

extern/sector-storage/stores/http_handler.go, extern/sector-storage/stores/remote.go, extern/sector-storage/tarutil/systar.go
Should make cross-worker transfers use slightly less CPU (and potentially be faster on 10G+ networks)
=> storage: Use 1M buffers for Tar transfers

api/types.go, node/impl/client/client.go
- Adjust the ExportRef comment to reflect change from #7673
- Simplify control flow in parseDagSpec() ( read diff under -w )
=> Cleanup partial retrieval codepaths ( zero functional changes )

go.mod, go.sum, node/builder.go, node/modules/lp2p/smux.go
Compatibility considerations: The reason we have mplex in IPFS is that js-libp2p doesn't support yamux, so mplex is the fallback stream muxer there. We don't care about js-libp2p in lotus. As far as I know (someone with more ecosystem insight please double check!), all Filecoin implementations support yamux (at least Venus does), so there's no need for a fallback.
=> disable mplex stream muxer

.circleci/config.yml, chain/vm/runtime.go, chain/vm/vm.go, itests/self_sent_txn_test.go
=> reorder `transfer` checks so as to ensure sending 2B FIL to yourself fails if you don't have that amount

go.mod, go.sum
=> Update go-graphsync v0.10.6

scripts/docker-lotus-miner-entrypoint.sh
obviously, we want to run the init if the gate file **doesn't** exist.
=> fix logic error

extern/sector-storage/ffiwrapper/sealer_cgo.go
This lets lotus detect compute errors in PC1/PC2 early, before precomitting to sectors which can't be proven (and can't be recovered because the CommR on chain is bad)
Closes #7702
=> ffiwrapper: Validate PC2 by calling C1 with random seeds

.circleci/config.yml, .circleci/template.yml
It appears recently something has changed in circleci and we no longer have access to the /dev/snd device which is causing the appimage tests to fail during setup.
=> Disable appimage

blockstore/splitstore/splitstore.go, blockstore/splitstore/splitstore_compact.go, blockstore/splitstore/splitstore_test.go, node/modules/chain.go
This adds the necessary logic to suppress compaction near upgrades and avoid issues with garbage collection of migrated state; see #7565
=> SplitStore: supress compaction near upgrades

go.mod, go.sum, markets/dagstore/mount_test.go, markets/dagstore/piecereader.go, metrics/metrics.go
=> dagstore pieceReader: Always read full in ReadAt

extern/sector-storage/fr32/fr32.go, extern/sector-storage/fr32/readers.go, extern/sector-storage/mock/mock.go, extern/sector-storage/piece_provider.go, extern/sector-storage/piece_provider_test.go, extern/sector-storage/piece_reader.go, extern/sector-storage/stores/http_handler.go, extern/sector-storage/stores/remote.go, extern/sector-storage/stores/remote_test.go, markets/dagstore/miner_api.go, markets/dagstore/miner_api_test.go, markets/dagstore/mocks/mock_lotus_accessor.go, markets/dagstore/mount.go, markets/dagstore/mount_test.go, markets/dagstore/wrapper_migration_test.go, markets/dagstore/wrapper_test.go, markets/sectoraccessor/sectoraccessor.go
https://github.com/filecoin-project/lotus/pull/7693 made retrieval quite fast, but we can do better
=> Make retrieval even faster

chain/vm/runtime.go
=> Expose EnableGasTracing as an env_var

chain/gen/genesis/genesis.go, chain/vm/vm.go, conformance/driver.go
The current behaviour violates the spec (see [here](https://github.com/filecoin-project/specs-actors/blob/master/actors/runtime/runtime.go#L116))
=> VM: Circ supply should be constant per epoch

cmd/lotus-shed/main.go, cmd/lotus-shed/terminations.go
And another to calc burnt funds given a list of msgs
=> Shed: Add a util to list terminated deals

documentation/en/default-lotus-miner-config.toml, itests/deals_concurrent_test.go, node/builder_miner.go, node/config/def.go, node/config/doc_gen.go, node/config/types.go, node/modules/storageminer.go, tools/packer/repo/config.toml
@jennijuju to get this started. Exposes graphsync 0.10.3's `MaxInProgressIncomingRequestsPerPeer` as `SimultaneousTransfersForStoragePerClient` for storage providers only (the other gs options are exposed for fullnodes/clients too, I'm assuming this is appropriate behaviour).
Will need @hannahhoward's eye, and tests would be nice but I have no idea what that might look like.
=> feat(graphsync): allow setting of per-peer incoming requests for miners

chain/gen/genesis/miners.go, chain/rand/rand.go, chain/stmgr/stmgr.go, chain/vm/runtime.go, chain/vm/vm.go, conformance/rand_fixed.go, conformance/rand_record.go, conformance/rand_replay.go, testplans/lotus-soup/go.mod, testplans/lotus-soup/go.sum
The rand versioning in the VM is currently bloated, and in the wrong place -- the VM shouldn't be reasoning about how randomness is versioned.
Moves the randomness versioning logic out of the VM and into the Rand module.
=> refactor: state: Move randomness versioning out of the VM

cmd/lotus-miner/sectors.go
=> sectors update-state checks if sector exists before changing its state

extern/sector-storage/partialfile/partialfile.go
No related issues; motivation is grammatically correct log warnings.
This pull request fixes a typographical error in a log warning message.
=> misc: n/a sealing: Fix grammatical error in a log warning message

go.mod, go.sum, markets/storageadapter/provider.go
Fixes https://github.com/filecoin-project/lotus/issues/7577
Depends on https://github.com/filecoin-project/lotus/pull/7646
Includes fixes https://github.com/filecoin-project/go-fil-markets/pull/657 https://github.com/filecoin-project/go-fil-markets/pull/656
Change the markets process to ensure that each time it retries add piece, it seeks to the beginning of the data source.
Note: Tests are in https://github.com/filecoin-project/go-fil-markets/pull/656
Note that there are a lot of updates to dependencies because of https://github.com/filecoin-project/go-fil-markets/pull/653
=> fix: #7577 markets: When retrying Add Piece, first seek to start of reader

chain/consensus/filcns/compute_state.go, chain/consensus/filcns/filecoin.go, chain/gen/genesis/genesis.go, chain/gen/genesis/miners.go, chain/rand/rand.go, chain/stmgr/actors.go, chain/stmgr/call.go, chain/stmgr/stmgr.go, chain/stmgr/utils.go, chain/vm/invoker_test.go, chain/vm/runtime.go, chain/vm/vm.go, cmd/lotus-sim/simulation/blockbuilder/blockbuilder.go, cmd/lotus-sim/simulation/simulation.go, cmd/lotus-sim/simulation/step.go, conformance/driver.go, conformance/rand_fixed.go, conformance/rand_record.go, conformance/rand_replay.go, node/impl/full/state.go
The primary motivation for this is to support FVM integration, because we don't want to be piping a network version getter across the FFI boundary.
The actual Runtime interface only ever reports the network version at the current epoch to actors. Within the VM too, all but one of the invocations of the version getter is for the current epoch. These can all be satisfied by simply providing the current network version on VM construction.
The exception is the randomness getters, which provide the network version at an arbitrary epoch as input. This PR gets around this by allowing the randomness module to query the network version.
- `PR type`: _fix_, …
=> Refactor: VM: Remove the NetworkVersionGetter

.github/pull_request_template.md
issue number in PR title is not that useful because reader cannot click it and need to mention the issue in the body for auto close either way.
remove issue number from the pr title
=> misc: docs: remove issue number from the pr title

.circleci/config.yml, .circleci/template.yml
I've noticed conformance bleeding edge is failing on all PRs.  I think this is because master points to v7 actors but vectors assume latest actors version is v6.  Solution is to point bleeding edge at a test-vectors branch with v7 vectors.  Ideally we can merge that into test-vector master soon but if it gets in the way of fvm stuff I don't see a problem with keeping a non-master test-vector branch tied to bleeding edge.
- `area`: _api_, _chain_, _state_, _vm_, _data transfer_, _market_, …
=> FIX: #7904 CI: generated vectors from v7 for bleeding edge

chain/vm/gas.go, chain/vm/gas_v0.go
=> feat: #7880 gas: add gas charge for VerifyReplicaUpdate

go.mod, go.sum, testplans/lotus-soup/go.sum
=> chore: deps: Update go-paramfetch

blockstore/autobatch.go
=> fix: blockstore: Add missing locks to autobatch::Get()

extern/storage-sealing/checks.go, extern/storage-sealing/states_replica_update.go
resolves #7869 
add more deal error handling during PRU pipeline so that we can fail early without  wasting too much work 
=> fix: #7869 sealing: Add more deal expiration checks during PRU pipeline

blockstore/autobatch.go
1. Simplify shutdown and make it idempotent by using a context.
2. Make sure `Flush` actually _fully_ flushes if the previous flush failed.
3. Don't clear the flush batch if flushing fails.
=> correctness fixes for the autobatch blockstore

go.mod, go.sum
=> Use go-libp2p-connmgr v0.3.1

chain/consensus/filcns/compute_state.go, chain/consensus/filcns/filecoin.go, chain/vm/vm.go
Fixes bug introduced in #7818. The VM's network version was always being determined based on `epoch`, the input to the `ApplyBlocks` method, even though the vm executes (potentially) multiple epochs worth of messages. The result is that if there was a null epoch before the upgrade epoch, the VM used the wrong network version (the new version) for running cron before the migration.
Although this was a fairly specific case, I think this issue shows the risks of trying to hamfistedly reuse the VM for multiple epochs of execution (see #7890 for a similar issue). This PR changes behaviour to make VMs one-per-epoch. We remove the old `SetBlockHeight` method entirely, and always create a new VM when moving between epochs. The result is that fields that need updating between epochs (like network …
=> Fix: chain: create a new VM for each epoch

go.mod, go.sum
Purely a go.mod update, fixes a couple of bugs in go-libp2p v0.18.0-rc1.
=> update go-libp2p to v0.18.0-rc2

extern/sector-storage/sealtasks/task.go
=> chore: remove inaccurate comment in sealtasks

cmd/tvx/codenames.go, cmd/tvx/extract_message.go, cmd/tvx/simulate.go
This PR fixes the `tvx` tool to pass in the relevant network version when extracting test vectors.
=> tvx: supply network version when extracting messages.

build/params_2k.go
=> chore: build: make the OhSnap epoch configurable by an envvar for devnets

chain/messagepool/messagepool.go
This PR adds a simple `address:tipset -> nonce` cache for state nonces to mpool nonce getter. This massively speeds up lite node startup when the node has sent a lot of messages over its life (in my case node startup time went down from 13 minutes to 2.5 seconds)
=> feat: mpool: Cache state nonces

blockstore/splitstore/markset.go, blockstore/splitstore/markset_badger.go, blockstore/splitstore/markset_map.go, blockstore/splitstore/markset_test.go, blockstore/splitstore/splitstore.go, blockstore/splitstore/splitstore_check.go, blockstore/splitstore/splitstore_compact.go, blockstore/splitstore/splitstore_warmup.go, blockstore/splitstore/visitor.go
Preliminaries for implementing additional functionality on top (sortless compaction, gc, etc), this performs some basic refactoring to avoid polluting ballooning subsequent prs:
- The distinction between MarkSet and MarkSetVisitor is removed.
- SetConcurrent is removed from MarkSet interface; all mark sets must be concurrent, because ...
- Chain walking is now parallelized
=> some basic splitstore refactors

go.mod, go.sum
Fixes a potential panic in yamux.
=> update go-libp2p to v0.18.0-rc3

build/params_shared_funcs.go, chain/sub/incoming.go, metrics/metrics.go, node/builder.go, node/builder_chain.go, node/modules/lp2p/pubsub.go, node/modules/services.go
Content providers announce the availability of indexer data using gossip pubsub.  The content providers are not connected directly to indexers, so the pubsub messages are relayed to indexers via chain nodes. This PR makes chain nodes relay gossip pubsub messages, on the /indexer/ingest/<netname> topic.
See https://github.com/filecoin-project/lotus/pull/7313
- New service for chain nodes to relay pubsub for /indexer/ingest/<netname> topic
- New validator for indexer messages
- New metrics for message validation failure and success
- `PR type`: _fix_, _feat_, _INTERFACE BREAKING CHANGE_, _CONSENSUS BREAKING_, _build_, _chore_, _ci_, _docs_,_perf_, _refactor_, …
=> Lotus chain nodes relay indexer pubsub messages

blockstore/splitstore/README.md, documentation/en/default-lotus-config.toml, node/config/def.go, node/config/doc_gen.go, node/config/types.go
On top of #8008.
Sets badger as the default markset type, so that we can work out of the box if we have <40G of RAM.
=> splitstore: set badger as the default default markset type

go.mod, go.sum
fixes a race condition in quic transport and removes the (now unnecessary) hard stream limit from yamux.
=> update libp2p to v0.18.0-rc4

go.mod, go.sum, node/modules/storageminer_idxprov.go
Upgrade to the latest `index-provider` which upgrades the go-legs
protocol to allow the inclusion of extra gossip data that may be used
for gossip validation purposes. In the case of lotus gossip message
validators the miner ID is used to verify the sender's peer ID on chain.
Relates to:
- https://github.com/filecoin-project/lotus/pull/8045
=> Upgrade to latest `index-provider` and set miner ID as extra gossip data

extern/storage-sealing/states_failed.go, extern/storage-sealing/states_replica_update.go, extern/storage-sealing/upgrade_queue.go
#8011
This addresses the major concern behind #8011 -- too many resources being used when retrying submission of a replica update message after fault.  
The best solution available now is to check for the fault condition after submit replica update has failed.  
It is understandable to want to stop including faulty sectors at deal inclusion as the name of 8011 suggests.   But that is less good.  Faulting could happen immediately after the last deal was included and the scheduler would be in the same bad state.
The totally correct thing that we should work towards in the future is interrupting the scheduler with an fsm event triggered by listening to the chain for faults (and expirations extensions, etc) happening.  But that is too much refactor for right now.
Fun alternate idea: [this …
=> fix: sealing: Stop recovery attempts after fault

extern/storage-sealing/states_failed.go, extern/storage-sealing/states_replica_update.go, extern/storage-sealing/upgrade_queue.go
Check sector is active before PRU
Fix log
nit: edit a comment
=> Stop recovery attempts after fault

cmd/lotus-shed/storage-stats.go
=> chore: shed: storage stats 2.0

chain/beacon/drand/drand.go
Makes logs less noisy
Changes log level for drand fetching from `info` to `debug`
Nothing special.
=> perf: chain: Make drand logs in daemon less noisy

blockstore/splitstore/README.md, blockstore/splitstore/checkpoint.go, blockstore/splitstore/checkpoint_test.go, blockstore/splitstore/coldset.go, blockstore/splitstore/coldset_test.go, blockstore/splitstore/markset.go, blockstore/splitstore/markset_badger.go, blockstore/splitstore/markset_map.go, blockstore/splitstore/markset_test.go, blockstore/splitstore/splitstore.go, blockstore/splitstore/splitstore_check.go, blockstore/splitstore/splitstore_compact.go, blockstore/splitstore/splitstore_test.go, blockstore/splitstore/splitstore_warmup.go, documentation/en/default-lotus-config.toml, node/config/def.go, node/config/doc_gen.go, node/config/types.go
This implements sortless compaction, as outlined in #7137.
Closes #7137 
The compaction algorithm is modified to store the coldset on disk and checkpoint deletions. Once the critical section starts, the markset is consulted on reads and an object is considered as missing from the hotstore if it is not in the markset, while write synchronously update the markset.
This results in significantly faster compaciton (40% of time was spent in sorting).
In addition, coupled with the badger markset, compaction now uses very little memory independent of coldset size, which makes it possible to use the splitstore in memory constrained systems.
=> splitstore sortless compaction

testplans/docker-images/proof-parameters.json
=> feat: build: update the snap proofs in testplans

chain/sub/incoming.go, chain/sub/ratelimit/queue.go, chain/sub/ratelimit/window.go, chain/sub/ratelimit/window_test.go, go.mod, go.sum, node/modules/lp2p/pubsub.go, node/modules/services.go
This PR authenticates indexer pubsub messages against the blockchain and does rate-limiting of these messages.
- Authenticate that peer that sent the message is the peer that appears in the miner info.
- Rate limit overall messages
- Rate limit repeated announcements
=> Add indexer pubsub message authentication and rate limiting

chain/sub/incoming.go, chain/sub/incoming_test.go
The type of extra data in go-legs gossip is bytes. But when it is parsed
as miner ID, it is cast to string then parsed. Instead, it should be
decoded from bytes.
=> Decode gossip extra data as `[]bytes` 

build/params_shared_funcs.go
Override `testnetnet` to `mainnet` when constructing indexer ingestion
topic.
Relates to: https://github.com/filecoin-project/lotus/pull/7313
=> Override `testnetnet` to `mainnet` in indexer ingest topic

cmd/lotus-shed/diff.go, cmd/lotus-shed/main.go
This makes it easier to debug state mismatches by providing a nice way to figure out which actors differ between two state-trees and how (balance, nonce, state, etc.).
It doesn't provide a way to actually _diff_ those state-trees, but one can use `lotus chain get` to figure that out (although it would be _nice_ to provide something a bit smarter).
- `area`: _api_, _chain_, _state_, _vm_, _data transfer_, _market_, _mempool_, _message_, _block production_, _multisig_, _networking_, _paychan_, _proving_, …
=> add a state-tree diff command to lotus shed

blockstore/context.go, blockstore/splitstore/splitstore.go, blockstore/splitstore/splitstore_reify.go, blockstore/splitstore/splitstore_test.go, chain/consensus/filcns/compute_state.go
Implements cold object reification in the splitstore for VM access, as described in #6726; on top of #8008, cherry picked and adapted from #6914.
Closes #6726
=> splistore cold object reification redux

cmd/lotus-miner/init.go, cmd/lotus-seal-worker/main.go, cmd/lotus-seal-worker/tasks.go, documentation/en/cli-lotus-worker.md, documentation/en/default-lotus-miner-config.toml, extern/sector-storage/manager.go, node/config/def.go
Noticed by BenjaminH on Slack.
I think we want _at least_ these tasks, not sure exactly which. @Reiers @ZenGround0 @magik6k may know better.
=> fix: worker: allow enable/disabling ReplicaUpdate tasks

go.mod, go.sum
Update to the head of the PR that introduces indexing integration in
`go-fil-markets` so that failure to connect to full node is logged only
instead of crashing markets process.
Relates to:
- https://github.com/filecoin-project/go-fil-markets/pull/673
- https://github.com/filecoin-project/index-provider/issues/177
=> Update to the head of go-fil-markets#673

go.mod, go.sum, metrics/metrics.go, node/modules/lp2p/rcmgr.go
This adds support for resource manager action metrics, providing visibility into the operation of the resource manager.
=> Resource Manager Metrics

itests/kit/blockminer.go, itests/paych_api_test.go
1. Improve MineBlocksMustPost, a testing helper I first made to remove flakes from cc upgrade itest
2. Use in paych api test
@TheDivic brought my attention to flaky behavior in a few tests.  Looking at the logs [here](https://app.circleci.com/pipelines/github/filecoin-project/lotus/19402/workflows/6105c7d3-6df9-4f38-b5a4-f49dbfe2ed78/jobs/373079) I saw the same error message from the cc upgrade itest: 
```
2022-02-13T16:16:46.332Z	WARN	vm	vm/runtime.go:350	Abortf: invalid deadline 0 at epoch 718, expected 1
2022-02-13T16:16:46.332Z	WARN	vm	vm/runtime.go:161	VM.Call failure in call from: f0102 to f01000: invalid deadline 0 at epoch 718, expected 1 (RetCode=16):   
```
I had previously debugged this and tracked it down to the behavior of post.  The post scheduler returns no errors so post …
=> fix:paychan:deflake integration test

node/modules/lp2p/rcmgr.go
follow up from #8089 -- don't track things that come from the network, as the metrics subsystem is not exactly bulletproof and can end up using uncontrolled memory because of spam under high load conditions.
=> don't track peer ids in rcmgr metrics

cmd/lotus-miner/sectors.go, documentation/en/cli-lotus-miner.md
=> feat: lotus-miner sectors list --initial-pledge

cmd/lotus-miner/init.go, cmd/lotus-seal-worker/main.go, cmd/lotus-seal-worker/tasks.go, documentation/en/cli-lotus-worker.md, documentation/en/default-lotus-miner-config.toml, extern/sector-storage/manager.go, node/config/def.go
=> fix: sealer: allow enable/disabling ReplicaUpdate tasks

documentation/en/default-lotus-miner-config.toml, markets/idxprov/host.go, markets/idxprov/mesh.go, node/builder_miner.go, node/config/def.go, node/config/doc_gen.go, node/config/types.go, node/modules/storageminer_idxprov.go
Remove the bespoke instantiation of libp2p host and datatransfer manager
for index provider and reuse the existing instances used by markets.
The rationale for reuse is the following:
1. Separation of host introduces a discovery problem, where without
gossipsub the index provider endpoint will not be discoverable.
Using the same host as markets would mean the chain can be used to
discover addresses, putting less empassis on criticality of
gossipsub considering its set-up cost and lack of message delivery
guarantees.
2. Only a single instance of graphsync/datatransfer can be instantiated
per libp2p host; therefore, if the host is shared, so should be
datatransfer manager.
3. it is not clear if the assumptions under which separation was
decided still hold.
=> Use the same host and datatransfer as markets for index provider

chain/consensus/filcns/upgrades.go
Two changes:
- Reduce the number of premigrations from 2 to 1, and increase the amount of time it has to run. This is because we're not observing that much of a speedup from the second premigration, but we _really_ want at least one to run (if not you're looking at being out of sync for a half hour).
- Reduce the autobatch buffer capacity to 256 MiB. This gives us a solid pre-migration time of < 20 mins (migration time of a minute or so), without using too much memory.
- `area`: _api_, _chain_, _state_, …
=> feat: tweak v15 migration params

cmd/lotus-seed/genesis.go
allows automation to correctly set the network version for the currently built network with no variable inputs.
When creating a network, by default, the latest network version (`NewestNetworkVersion`) is used in the genesis network template file. If the network does not start on the default latest network version (eg has upgrade epochs set / `GenesisNetworkVersion` is smaller), the network will fail to startup due to invalid network versions.
Add a flag that will use the build param `GenesisNetworkVersion` to set the network version. This ensures that the genesis network version always matches the network being built (if lotus-seed is built with the network flags).
- example: ` fix: mempool: Introduce a cache for valid …
=> feat: cli: set current network version from params

blockstore/splitstore/splitstore_reify.go
some of these are ok (eg missing receipts in a block) and this could spam the log repeatedly, so use incomplete walk.
=> don't fail reification on missing references

blockstore/splitstore/splitstore_reify.go, blockstore/splitstore/splitstore_test.go
big reifications can use a lot of memory during sync apparently.
Temporarily disabling reification until I can sort out the memory usage during sync.
=> temporarily disable reification

cmd/lotus-miner/info_all.go, cmd/lotus-miner/storage.go
(also adding some useful things to `lotus-miner info all`)
=> feat: Snapdeals support in `storage find` CLI

chain/vm/fvm.go
Needs https://github.com/filecoin-project/ref-fvm/pull/330 and https://github.com/filecoin-project/filecoin-ffi/pull/235
=> Fvm: impl VerifyConsensusFault

CHANGELOG.md, build/params_mainnet.go, extern/storage-sealing/upgrade_queue.go, testplans/lotus-soup/go.sum
See [here](https://github.com/filecoin-project/lotus/compare/master..asr/releases-master?expand=1) for the actual diff
=> chore: Merge releases into master

go.mod
Probably worth backporting to the 1.14.x branch if it continues
cc @arajasek @jennijuju @Kubuxu
=> Retract force-pushed v1.14.0 to work around stale gomod caches

itests/kit/ensemble.go
We want FilClient to use itests ensemble for tests. It requires access to the mocknet object inside of ensemble, so that it can hook into the offline network, which is currently private.
Add a public getter for itests ensemble mocknet.
=> feat: itests: add itests ensemble mocknet getter

blockstore/splitstore/splitstore_reify.go, blockstore/splitstore/splitstore_test.go, blockstore/splitstore/visitor.go
It was observed that during sync from snapshot some very large reification walks would trigger, consuming excessive memory.
This introduces a limit to reification mass, and aborts if the visited object count is exceeded.
=> fix: limit reification sizes

cli/client.go
Fixes #8100
If no valid value are filled in "Deals to make (1)", display an error message and continue to ask 
(instead of return error to make the CLI crash)
Maybe we can force a default value to 1, instead of asking in loop for a valid value ?
=> fix:cli:Continue instead of return error if no valid value is filled

go.mod, go.sum
Fixes a goroutine leak in the swarm.
=> deps: update go-libp2p to v0.18.0-rc5

cli/util/api.go, itests/sector_finalize_early_test.go, node/config/doc_gen.go, node/config/types.go, node/modules/storageminer.go
This PR is extracting `DealmakingConfig` and `Sealing` config, so that we can inherit the dynamic types dependencies from Lotus in Boost.
=> config: extract DealmakingConfig and Sealing config from Lotus for Boost

go.mod, markets/utils/selectors.go
This adds support for UnixFS ADLs in client parts of lotus.
Client-side only. Providers already have support for those through Graphsync - https://github.com/ipfs/go-graphsync/blob/8c66ab9e2f562386c59fba2700bb1fcf8c743675/storeutil/storeutil.go#L46
=> feat: market utils: Support unixfsnode in TraverseDag

chain/actors/builtin/verifreg/actor.go.template, chain/actors/builtin/verifreg/state.go.template, chain/actors/builtin/verifreg/util.go, chain/actors/builtin/verifreg/v0.go, chain/actors/builtin/verifreg/v2.go, chain/actors/builtin/verifreg/v3.go, chain/actors/builtin/verifreg/v4.go, chain/actors/builtin/verifreg/v5.go, chain/actors/builtin/verifreg/v6.go, chain/actors/builtin/verifreg/v7.go, chain/actors/builtin/verifreg/verifreg.go, cli/filplus.go, cmd/lotus-shed/verifreg.go, documentation/en/cli-lotus.md
Closes Issue #7863 
Added the following cli commands:
lotus filplus sign-remove-data-cap-proposal 
lotus-shed verifreg remove-verified-client-data-cap
Tested on devnet. Works as expected.
=> Feat: cli: Remove verified data cap

extern/sector-storage/stores/http_handler.go
=> fix: sealing: missing file type

cmd/lotus-miner/sectors.go
=> fix:sealing:really-do-it flag for abort upgrade

chain/consensus/filcns/filecoin.go, chain/messagepool/check.go, chain/messagepool/messagepool.go
Partially fixes #6652.
Bring the gas epoch used in chain validation in-line with the gas epoch used in message execution.
This change should only affect the one gas repricing we had (Calico). It should only affect consensus if the blocks _at_ the upgrade height included a message without enough gas to cover the message's execution. In the old code:
- The message pool and chain sync logic would have allowed this message.
- The VM itself would have penalized the miner.
Looking at the relevant blocks around 265200 (the Calico upgrade height), I'm not seeing any miner penalties so I have to assume that this didn't happen.
- `PR type`: _fix_, _feat_, _INTERFACE …
=> Fix the epoch used for gas in the message pool & validation

cmd/lotus-miner/sectors.go, documentation/en/cli-lotus-miner.md
fixes https://github.com/filecoin-project/lotus/issues/8106#issuecomment-1050934658
=> fix: sealing: add flag usage

CHANGELOG.md, extern/sector-storage/stores/http_handler.go
=> chore: build: backport releases

cmd/lotus-miner/sealing.go
I found that many users panicked when using **lotus-miner sealing workers**,The reason is that previous versions have checked the value of **eBar** ,But it's ignored here
Worker 8afb3048-9bf5-4927-a380-f2ec13410f36, host  (disabled)
panic: strings: negative Repeat count
```
goroutine 1 [running]:
strings.Repeat(0x39b3742, 0x1, 0x8000000000000000, 0xc0004ee000, 0xc00109efc0)
/mnt/build/go/src/strings/strings.go:529 +0x5e5
main.barString(0x0, 0x0, 0x0, 0x15, 0xc00109f2b8)
/home/fc01/compile-quantum/lotus/cmd/lotus-miner/sealing.go:45 +0x126
main.glob..func56(0xc000354cc0, 0x0, 0x0)
/home/fc01/compile-quantum/lotus/cmd/lotus-miner/sealing.go:132 +0xdca
github.com/urfave/cli/v2.(*Command).Run(0x54f9780, 0xc000354bc0, 0x0, 0x0)
/home/fc01/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/command.go:16 …
```
=> avoid panic

extern/sector-storage/manager.go
=> fix:sealing:Less verbose sector manager logging

cmd/lotus/daemon.go, documentation/en/cli-lotus.md
Makes the --lite option visibile in the lotus daemon help text. Fixes https://github.com/filecoin-project/lotus/issues/7442. If it´s desired to keep the `--lite` option hidden in the lotus daemon helptext, then this PR can be discarded and issue [7442](https://github.com/filecoin-project/lotus/issues/7442) can be closed.
=> Make `--lite` option visible in the lotus daemon help text 

extern/storage-sealing/states_replica_update.go
=> fix: sealing: PRU insufficient collateral 

.circleci/config.yml, .circleci/template.yml, AppImageBuilder.yml
fix: https://github.com/filecoin-project/lotus/issues/7733
This was disabled due to a bug in https://github.com/filecoin-project/lotus/pull/7707
=> ci: appimage: re-install appimage CI

extern/sector-storage/worker_local.go
https://github.com/filecoin-project/lotus/issues/6147
When a sector is executed incorrectly(delete sc-02-data-layer-2.dat and produce an error),  can see which worker name (hostname) executed it in `lotus-miner sectors status --log`: 
```
SectorID:	2
Status:		ComputeProofFailed
CIDcommD:	baga6ea4seaqpy7usqklokfx2vxuynmupslkeutzexe2uqurdg5vhtebhxqmpqmy
CIDcommR:	bagboea4b5abcaanfg4ensvrat6mxojxn3v6qhvar5xayh7jv2ca3a3h777xwzall
Ticket:		7759ed6454fdf1a162971fb98343c0e88f09c581a09865f515207255f0155e8c
TicketH:	-852
Seed:		fe0a25949d1f48cce6c213895d60cca2fb5460f32c2cc3202bb44e8ef8e6604f
SeedH:		123
Precommit:	bafy2bzacebgaxlgralo4ypndahpsdllgd7ublxdk7hdd4mbtwz5r7yc62paqa
Commit:		<nil>
Deals:		[0]
Retries:	0
--------
Event Log:
0.	2021-12-23 17:27:05 +0800 CST:	[event;sealing.SectorStartCC] …
```
=> feat: #6147: Include worker name in sealing errors

extern/storage-sealing/input.go, extern/storage-sealing/sealing.go
A very common deal making error we encounter is that Boost/Markets makes a call to `AddPiece` and then restarts.
If it restarts before it's able to persist the fact that it's already called AddPiece, it will call `AddPiece` again for the same piece. In this case, the existing API returns an error as it's not idempotent.
This PR allows the user to call `AddPiece` multiple times for the same piece but ensures that it's handed off to the sealing subsystem only once. 
It also makes the method respect the given context.
=> feat: Make add piece idempotent

extern/storage-sealing/fsm.go
normal shutdown of state machine error will be logged but it won't kill the ability to update sector state from lotus-miner cli
=> fix:sealing:Log instead of error normal shutdown of state machine

CHANGELOG.md, extern/storage-sealing/fsm.go
=> chore: backport: release

cli/state.go, miner/warmup.go
Resolves #8237 
Also makes state sector command print out sector key info for upgraded sectors
=> fix:proving:winning post warmup works on snapped up sectors

cmd/lotus-shed/itestd.go, cmd/lotus-shed/main.go, itests/kit/itestd.go, itests/kit/rpc.go
ItestD is a lotus-shed command which starts a local daemon, and gives you an env var, which can be passed into itests. When an itest runs with that env var set, ItestD will allow you to open a shell with `lotus*` commands pointed at the running integration test.
=> feat: shed: ItestD

extern/sector-storage/piece_provider.go
=> fix: piece provider: Don't log CIDs as binary

documentation/en/default-lotus-config.toml, documentation/en/default-lotus-miner-config.toml, lib/lotuslog/config.go, node/builder.go, node/config/def.go, node/config/def_test.go, node/config/doc_gen.go, node/config/doc_util.go, node/config/load.go, node/config/types.go
=> feat: config: Persistent subsystem log level config

node/impl/client/client.go
Make `ClientCalcCommP` a lot faster
=> feat: api: Make ClientCalcCommP multithreaded

go.mod, go.sum
- go-libp2p at v0.18.0-rc6, which includes fixes for some severe bugs in mplex
- go-libp2p-resource-manager at v0.1.5, which improves debug logging
=> deps: update go-libp2p and go-libp2p-resource-manager

extern/sector-storage/mock/mock.go, extern/storage-sealing/input.go, itests/batch_deal_test.go, itests/sector_miner_collateral_test.go
=> fix: sealing fsm: Handle inputLk correctly

node/builder.go, node/modules/lp2p/rcmgr.go
- add opt-in env var to control instantiation, until we are comfortable with testing to enable by default.
- adjust default limits if the connection manager high mark is higher than the default inbound conn limit.
=> improve resource manager integration

cmd/lotus-miner/storage.go
=> fix: storage cli: Output primary sector status correctly

api/api_storage.go, cmd/lotus-miner/sectors.go, documentation/en/cli-lotus-miner.md, extern/storage-sealing/sealing.go, extern/storage-sealing/states_sealing.go, extern/storage-sealing/upgrade_queue.go, storage/miner_sealing.go
#7934
Remove mark-for-upgrade cli command and underlying sealer methods
I'm not yet removing the upgrade field from the FSM's sector info because afaik this would cause failure to reload old sector infos.  @magik6k what's the best way to do this?  Have we migrated fsm sector info data before?
=> chore:sealing:remove endpoint from cli

api/version.go, extern/sector-storage/manager.go, extern/sector-storage/stores/http_handler.go, extern/sector-storage/stores/index.go, extern/sector-storage/stores/remote.go, extern/sector-storage/worker_local.go
Fixes #8227
Closes #8298 (This PR achieves the same thing in a slightly different way)
=> fix: sealing: Remove sector copies from workers after snapdeals

api/version.go, extern/sector-storage/manager.go, extern/sector-storage/stores/http_handler.go, extern/sector-storage/stores/index.go, extern/sector-storage/stores/remote.go, extern/sector-storage/worker_local.go
Backports https://github.com/filecoin-project/lotus/pull/8329 to v1.15.1
=> backport: v1.15.1: feat: sealing: Sector upgrade queue

cmd/lotus-miner/info.go, cmd/lotus-miner/sectors.go, documentation/en/default-lotus-miner-config.toml, extern/storage-sealing/fsm.go, extern/storage-sealing/fsm_events.go, extern/storage-sealing/input.go, extern/storage-sealing/mocks/api.go, extern/storage-sealing/sealiface/config.go, extern/storage-sealing/sealing.go, extern/storage-sealing/sector_state.go, extern/storage-sealing/states_failed.go, extern/storage-sealing/states_proving.go, extern/storage-sealing/states_replica_update.go, extern/storage-sealing/states_sealing.go, extern/storage-sealing/upgrade_queue.go, itests/ccupgrade_test.go, itests/kit/log.go, node/config/doc_gen.go, node/config/types.go, node/modules/storageminer.go, storage/adapter_storage_miner.go
Closes #8231
* Add a new `Available` sector state for CC sectors available for upgrading ('available storage')
* After sectors are marked for upgrade, they go into the `Available` state instead of `SnapDealsWaitDeals`
* When a deal arrives to the sealing pipeline, and it can't be matched to any sectors:
* We'll try to see if any `Available` sectors can accept it - we'll select a candidate with lowest initial pledge (most rational to upgrade?)
* If we don't find any good available sectors, we'll just create a new CC sector if that's not disabled in the config
TODO:
- `PR type`: _fix_, _feat_, _INTERFACE BREAKING CHANGE_, _CONSENSUS BREAKING_, _build_, _chore_, …
=> feat: sealing: Sector upgrade queue

cmd/lotus-shed/miner-multisig.go
[lotus-shed miner-multisig add change-worker command](https://github.com/filecoin-project/lotus/issues/8280)
Added two subcommands, propose-change-worker and Confirm-change-worker.
lotus-shed miner-multisig --from <sigle-address> --miner <miner-actor> --multisig <multisigAddress messageId> propose-change-worker <new-worker>
lotus msig approve --from <approve-account> <multisigAddress messageId> <proposerAddress destination value>
lotus-shed miner-multisig --from <sigle-address> --miner <miner-actor> --multisig <multisigAddress messageId> Confirm-change-worker <new-worker>
lotus msig approve --from <approve-account> <multisigAddress messageId> <proposerAddress destination value>
- example: ` fix: mempool: Introduce a cache for …
=> feat:  multisig: lotus-sheed miner-multisig change-worker command.

extern/sector-storage/manager.go
Probably fixes some of the "stuck in finalize" issues
FinalizeSector doesn't touch the `sealed` sector file, so requiring it to exist on the worker next to the cache can only cause issues - for example when a sector was in the middle of being finalized, the `sealed` file might have been moved off the worker just before it restarted - causing Finalize to restart, and get stuck on the early stage which expects sealed/cache files to still be on the worker - where we only really need the cache
- `area`: _api_, …
=> fix: sealing: FinalizeSector doesn't need sealed replica access

itests/kit/blockminer.go
`MineBlocksMustPost` could hang during test cleanup, causing tests to randomly time out. The issue seems to be that we're waiting for a block to be mined, but the block mining logic has already shut down (this is quite racy, but happens a lot more it tests with very low block delays).
Happened in https://app.circleci.com/pipelines/github/filecoin-project/lotus/20105/workflows/1c498222-3542-4b64-bb14-5667927379e6/jobs/409257
Relevant goroutines:
```
goroutine 85 [semacquire, 28 minutes]:
sync.runtime_Semacquire(0xc0038ad250)
/usr/local/go/src/runtime/sema.go:56 +0x45
sync.(*WaitGroup).Wait(0xc0038ad248)
/usr/local/go/src/sync/waitgroup.go:130 +0x65
github.com/filecoin-project/lotus/itests/kit.(*BlockMiner).Stop(0xc0038ad230)
/home/circleci/project/itests/kit/blockminer.go:324 +0x9a …
```
=> fix: itests: Don't hang on exit in MineBlocksMustPost

.circleci/config.yml, .circleci/template.yml, Dockerfile.lotus
This PR is:
1. Adding a `lotus-test` Docker target to `Dockerfile.lotus`
2. Build step to produce `lotus-test` image on commit to `master`.
We need this, because we are using the `--tags=debug` lotus binaries as part of the integration tests for Boost -- https://github.com/filecoin-project/boost/blob/main/.circleci/config.yml#L67
Ideally these images should be produced by `filecoin-project/lotus` build system.
---
TODO:
=> feat: infra/ci: add `lotus-test` image as CI build step

lib/unixfs/filestore.go, lib/unixfs/filestore_test.go, node/impl/client/client.go
This PR is extracting and exporting the function which creates a UnixFS Filestore - I'd like to be able to use it from other packages, and right now it is private.
=> lib: extract unixfs filestore into lib

chain/stmgr/call.go
We've noticed some uncertainty when estimating gas with the new memstore introduced to the `CallWithGas` method in https://github.com/filecoin-project/lotus/pull/8293. 
We can investigate and fix later, but this PR just removes the buffered store for now.
=> fix: avoid racy memstores when estimating gas

cmd/lotus-wallet/main.go
Apparently this doesn't matter as neither wallet nor worker repos have config, but this is more correct.
=> fix: lotus-wallet: pass correct repo type to repo.Init

chain/stmgr/call.go
This is the  correcter solution to #8351
Use a concurrent-access memory blockstore for the LegacyVM
=> feat: stmgr: call: use a buffered concurrent-access blockstore

cmd/lotus-miner/market.go
=> --max-piece-size in set-ask is no longer required

cli/multisig.go
Prints an additional "waiting for confirmation.." when running `lotus msig create [address1 address2]` to indicate that the command is waiting for the msg to be mined into a block, and not just hanging.
Should fix #4053
=> fix: multisig: Print "waiting for confirmation.."

extern/storage-sealing/upgrade_queue.go
Renaming the the error-message you get if you try to snap-up the same sector twice, to better reflect that you are snapping a sector, and not mark-for-upgrade, which now has been deprecated.
=> fix:snapup: Rename error message

cmd/lotus-miner/proving.go, cmd/lotus-miner/storage.go, documentation/en/cli-lotus-miner.md
* Print faults in `lotus-miner storage list sectors` so it's easy to spot where the faulty sectors are
* Add a `--faulty` flag to `lotus-miner proving check`, so that it only checks faulty sectors, which is much, much faster
=> feat: miner cli: proving check --faulty, faults in storage list sectors

chain/consensus/filcns/filecoin.go, chain/messagepool/check.go, chain/messagepool/messagepool.go, chain/messagepool/selection.go, chain/stmgr/forks.go, chain/vm/fvm.go, chain/vm/gas.go, chain/vm/mkactor.go, chain/vm/vm.go, conformance/runner.go
Partially addresses #6652 
This was motivated by trying to sync the new FVM-based caterpillarnet using the LegacyVM. The 2 VMs are expected to interoperate, but don't, because the LegacyVM expects to use the "old" (genesis) pricelist, which is wrong for network v15.
The proposed change is to make pricelist selection based on both epoch _and_ network version. For anything after network v8, we can select the pricelist based on the version.
The epoch-based selection is preserved for backwards compatibility alone.
- `PR type`: _fix_, _feat_, _INTERFACE BREAKING CHANGE_, _CONSENSUS BREAKING_, _build_, _chore_, _ci_, _docs_,_perf_, _refactor_, _revert_, _style_, …
=> VM: Refactor pricelist to be based on network versions

cmd/lotus-shed/chain.go
=> feat: lotus-shed: add command to compute state over a range of tipsets.

cli/client.go
Fixes #8095 
Clear the list of miners addresses set on the first attempt, because without clearing the list, on the next attempt, faulty miner is always in the list, so error is throw again.
Also, clear the list of all successfull get-ask before asking new addresses, because :
- First attempt : first miner in the list is good miner and the second one faulty ;
- Second attempt : only good miner in the list : summary will show two miner (because the first successfull one isn't removed)
=> fix: cli: Reset miner/ask lists in interactive deal 'miner' step

cmd/lotus-miner/info_all.go, cmd/lotus-miner/proving.go, cmd/lotus-miner/sealing.go, documentation/en/cli-lotus-miner.md
This PR creates a separate `lotus-miner proving workers` command which only lists PoSt workers.
=> feat: miner cli: Separate proving workers command

extern/storage-sealing/fsm.go
to remove a sector would cause the fsm(state machine) stuck in dead loop
use following cmd to remove a sector:
```shell
./lotus-miner sectors remove --really-do-it <sid> 
```
the sector state would change from 'any' to 'Removed', and there is a 'plan' in `fsmPlanners` for 'Removed' state:
https://github.com/filecoin-project/lotus/blob/b8b33c4f0666189142d1d9f948f92807c5796ae8/extern/storage-sealing/fsm.go#L309-L312
https://github.com/filecoin-project/lotus/blob/b8b33c4f0666189142d1d9f948f92807c5796ae8/extern/storage-sealing/fsm.go#L323
that is a  function named `final`, defined as following: 
https://github.com/filecoin-project/lotus/blob/b8b33c4f0666189142d1d9f948f92807c5796ae8/extern/storage-sealing/fsm.go#L697-L706
when `plan` above `final` on `SectorRemoved{}` event, the `final` would …
=> fix: miner: dead loop on removing sector

cmd/lotus-worker/main.go
Closes https://github.com/filecoin-project/lotus/issues/8387
=> feat: worker: check fd limit on startup

extern/sector-storage/piece_reader.go
Piecereader in it's current form is NOT thread-safe and we need concurrent access for Bitswap support.
=> Thread safe piecereader

cmd/lotus-miner/init.go, cmd/lotus-worker/main.go, documentation/en/cli-lotus-worker.md, documentation/en/default-lotus-miner-config.toml, extern/sector-storage/faults.go, extern/sector-storage/manager.go, extern/sector-storage/piece_provider_test.go, itests/kit/ensemble.go, node/builder_miner.go, node/config/def.go, node/config/doc_gen.go, node/config/storage.go, node/config/types.go, node/modules/storageminer.go
This PR makes pre-PoSt sector checks go fast.
=> feat: storage: Parallel proving checks

extern/sector-storage/manager.go
=> fix: sealing: Added error checking

go.mod, go.sum
Bringing https://github.com/filecoin-project/lotus/pull/8403 to master
=> chore(deps): update go-data-transfer with fixes (master edition)

extern/sector-storage/manager.go
=> fix: sealing: Fix PR1 worker selection

.circleci/config.yml, .circleci/template.yml
Fix issues related to timeouts, such as this one: https://app.circleci.com/pipelines/github/filecoin-project/lotus/20333/workflows/2abedb1c-9230-4032-95cf-3a4f41c4b3f8/jobs/422469/steps
This copies the source of the packer orb into our config https://circleci.com/developer/orbs/orb/salaxander/packer
and updates the build command so it includes the option to increase the no-output timeout.
I ran this in circleci to make sure it worked here https://app.circleci.com/pipelines/github/filecoin-project/lotus/20354/workflows/1ba6abc5-c7f4-4ac5-be89-e00ca277cc8b/jobs/423465
- `PR type`: _fix_, _feat_, _INTERFACE BREAKING CHANGE_, _CONSENSUS BREAKING_, _build_, …
=> Packer publish copy orb

chain/vm/vm.go, go.mod, go.sum, testplans/lotus-soup/go.mod, testplans/lotus-soup/go.sum
Closes #7954
Makes use of the skip option introduced in https://github.com/ipfs/go-log/pull/132
=> Update to go-log 2.5.1

node/impl/storminer.go
Got broken in the [window-post API/CLI PR](https://github.com/filecoin-project/lotus/pull/8389)
On startup market nodes get:
```
ERROR: creating node: starting node: missing dependencies for function "reflect".makeFuncStub (/usr/lib/go/src/reflect/asm_amd64.s:30): missing type: *storage.WindowPoStScheduler
```
=> fix: node: Fix market node startup

extern/sector-storage/worker_tracked.go
release worker tracker lock when call cb func, so that miner can call the worker api concurrently.
=> release worker tracker lock when call cb func

extern/sector-storage/manager.go, extern/storage-sealing/states_failed.go, extern/storage-sealing/states_proving.go, extern/storage-sealing/states_replica_update.go, extern/storage-sealing/states_sealing.go, extern/storage-sealing/types.go
=> fix: sealing: Release unsealed sector files after snapdeals abort

node/modules/storageminer_idxprov.go
N/A
Hook up the missing lotus-specific index provider config with engine options. Looks like the engine was missing some options populated from the corresponding lotus config.
N/A
=> fix: market: set all index provider options based on lotus config

node/builder_miner.go, node/modules/storageminer_idxprov.go
N/A
* The markets process instantiates its own `PubSub` instance with all validators, peer scoring, etc. set up. Use that instance to join the indexing topic, otherwise the default topic instantiated by index-provider internally (via go-legs) has no validators.
* Fixes the construction of `PubSub` via dependency injection mechanism in markets by binding its dependencies: bootstrap peers, drand related config.
~**Looks like DI for `PubSub` in markets is broken since it seems it was never used in markets before; waiting for confirmation that we indeed want validators for the gossipsub used by provider engine before spending time on fixing it.**~
N/A
- `PR type`: …
=> fix: market: Reuse the market `PubSub` in index provider

chain/events/events_test.go, chain/events/observer.go
- guarded with test
Lily schedles jobs that use the events system to observe head changes. When these jobs exit their observer needs to be deregistered from the events system. Currently this is not possible, this PR addresses this. 
Allow event observers to be deregistered
=> chore: events: implement event observer deregister method

.circleci/config.yml, .circleci/template.yml
This disables the publish-packer jobs, except for the snap package. This job frequently took too long and was over the timeout.
=> chore: ci: disable publish-packer

chain/vm/fvm.go
This caused a state mismatch on _some_ FVM nodes on mainnet when executing message `bafy2bzacedvprfrgzze2fvqutxl5za3jtwaqzgq7nwzlewf6e3q7pk7fuh3e6`. While the fix is easy, we should try to understand why only some nodes lost consensus -- my guess is that those nodes that _stayed_ in consensus were using snaphots that did not have the state root in question, and so failed with a different error, but the same gas usage.
Add the missing fix.
- `area`: _api_, _chain_, _state_, _vm_, _data transfer_, _market_, …
=> fix: FVM: add finality check for consensus faults

extern/sector-storage/sched.go, extern/sector-storage/sched_resources.go, extern/sector-storage/selector_alloc.go, extern/sector-storage/selector_existing.go, extern/sector-storage/selector_task.go
Should fix things like https://github.com/filecoin-project/lotus/issues/7607
Currently when the scheduler is assigning tasks to workers, it creates a list of `task->[]worker`. This list is sorted by worker utilization at the start of scheduling cycle, but it isn't re-sorted when assigning many tasks to many workers in one cycle. 
We could simply run the scheduling algorithm for each task in the queue separately, but this is unfortunately way too slow, so we have to do scheduling in batches, at least if we want to avoid rewriting it in a bigger way.
This PR aims to fix this issue by tracking change in worker utilization while processing the `acceptableWindows` array, which should result in much better scheduling decisions with only small increase of compute cost in scheduling.
Before you …
=> feat: sched: Improve worker assigning logic

extern/sector-storage/manager.go
Can happen after aborting upgrade of a snap sector with no deals added to it.
=> sealing: Don't panic in ReleaseUnsealed with no ranges

scripts/build-bundle.sh, scripts/publish-release.sh
this reverts two commits that were used to remove the appimage from release bundles.
https://github.com/filecoin-project/lotus/commit/6b0868089bf43fa5d2dc22784ad36e48b6fe6ec8
https://github.com/filecoin-project/lotus/commit/7d65a2664d795aee6eb0d811eddd4bd6b30cc26b
=> Revert appimage removal

documentation/en/default-lotus-config.toml, documentation/en/default-lotus-miner-config.toml, node/config/def.go
KVLog in its current form isn't generated correctly, and so far we didn't see any metadata corruption which couldn't be repaired with normal leveldb repair tools;
At some point it may be worth implementing a v2 of kvlog, but for now I think it's better to disable it by default as it seems to be a constant source of problems.
=> chore: config: default-disable kvlog

extern/storage-sealing/precommit_batch.go
#6572
The current practice of returning "now" as the cutoff for expired precommits doesn't make sense -- we should just say "it's too late" and fail.
This should send us through the "fail" pipeline into [this check](https://github.com/filecoin-project/lotus/blob/68f3e4483ffe3ac7b7da8c726ea91f1865494158/extern/storage-sealing/states_sealing.go#L230), at which point we'll redo PC.
- `area`: _api_, _chain_, _state_, _vm_, _data transfer_, _market_, _mempool_, _message_, _block production_, _multisig_, …
=> Fail to add expired precommits to a batch

build/bootstrap/mainnet.pi
add 1475 bootstarp node
> /dns4/bootstarp-0.1475.io/tcp/61256/p2p/12D3KooWQjaNmbz9b1XmheQB3RWsRjKSzuRLfjeiDZHyX7Y5RcBr
=> add 1475 bootstrapper

chain/actors/builtin/market/actor.go.template, chain/actors/builtin/market/market.go, chain/actors/builtin/market/state.go.template, chain/actors/builtin/market/v0.go, chain/actors/builtin/market/v2.go, chain/actors/builtin/market/v3.go, chain/actors/builtin/market/v4.go, chain/actors/builtin/market/v5.go, chain/actors/builtin/market/v6.go, chain/actors/builtin/market/v7.go, extern/storage-sealing/currentdealinfo.go, extern/storage-sealing/currentdealinfo_test.go, markets/storageadapter/client.go
=> fix:sealing:check index out of bounds against correct param length not return length

documentation/en/default-lotus-miner-config.toml, node/config/def.go, node/config/def_test.go, node/config/doc_gen.go, node/config/types.go, node/modules/storageminer_idxprov.go, node/modules/storageminer_idxprov_test.go
Fixes #8510
Instead of a fixed default, the changes here infer the allowed indexer
topic name from network name automatically if the topic configuration is
left empty.
Index provider integration uses a gossipsub topic to announce changes to
the advertised content. The topic name was fixed to the default topic
which is `/indexer/ingest/mainnet`.
In the case of lotus, the gossipsub validators enforce a list of topics
the instance is permitted to join by setting subscription filter option
when `PubSub` instance is constructed via DI.
Having the fixed topic name meant that any SP starting up a node on a
network other than `mainnet` would have to override the default config
to avoid the node crashing when index provider is enabled.
Before you mark the PR ready for review, please make sure …
=> fix: market: Infer index provider topic from network name by default

cmd/lotus-wallet/main.go
Update the `lotus-wallet run` description to include that a `FULLNODE_API_INFO` env variable needs to be set before running. Should address 5. in #8459 
=> fix: ux: update `lotus-wallet run` description

chain/vm/fvm.go
=> feat: vm: add actor error backtraces to FVM

extern/storage-sealing/fsm.go
Might help with the issue raised in https://filecoinproject.slack.com/archives/C038C47NWAE/p1651270743875089
Move snapdeals sectors to proving storage before submitting the proof to the chain.
=> fix: sealing: Finalize snap sectors before submitting proofs

api/types.go
=> chore:chore:chore

.circleci/config.yml, .circleci/template.yml
#8580
Remove `install-deps` step from macos builds
I also removed the filtering from `build-macos` and `build-all` so that these tasks run for all PRs to avoid build breaking only being detected during a release.
=> ci: deps: macos build deps

cmd/lotus-worker/main.go
The lotus-worker does not check or download the params if Prove Replica Update tasks are enabled, meaning that you get an param-error if you for example a run a new 'PC1 / RU / PRU2' worker and a SnapDeal gets assigned to it. Reported in #8549.
=> fix: worker: Download proofs if PRU2 is enabled

.gitignore
=> chore: .gitignore: ignore built in actor bundles

cli/chain.go, cli/net.go, cli/state.go, cmd/lotus-miner/actor.go, cmd/lotus-miner/proving.go, cmd/lotus-shed/blockmsgid.go, cmd/lotus-shed/keyinfo.go, cmd/lotus-shed/miner.go, cmd/lotus-shed/mpool.go, cmd/lotus-shed/msg.go, cmd/lotus-sim/info_message.go, documentation/en/cli-lotus-miner.md, documentation/en/cli-lotus.md
=> chore: cli: Alias cli commands for uniformity

Makefile
Adding $(GOFLAGS) so that when compiling `lotus-wallet` on calibnet, the correct network is shown, instead of showing just `lotus-wallet version x.xx.x+mainnet`. Should address 2. in #8459
=> fix: lotus-wallet: correct network in version

.codecov.yml
Couldn't figure out threshold so just made codecov not fail things which really shouldn't change our workflows
=> chore:ci:make codecov quiet

markets/loggers/loggers.go
Logging each block causes a lot of useless information in the logs
Log all events as info, except for block transfers, which will be debug
=> fix: Make markets logger less noisy when doing retrievals

extern/sector-storage/stores/remote.go
Results;
```
2  0  2374  good
2  0  2409  good
2  0  2282  bad (generating vanilla proof: non-200 code from http://10.224.3.83:1123/remote/vanilla/single: 'fsstat: path not found
')
2  0  2579  good
2  0  2338  good
```
This PR should change that to;
```
2  0  2374  good
2  0  2409  good
2  0  2282  bad (generating vanilla proof: non-200 code from http://10.224.3.83:1123/remote/vanilla/single: 'fsstat: path not found')
2  0  2579  good
2  0  2338  good
```
- `area`: _api_, _chain_, _state_, _vm_, _data …
=> fix: Clean up vanilla proof fetching errors for proper display

.circleci/config.yml, .circleci/template.yml, .codecov.yml
#8594
Add back the explicit call to build on tags that was removed in #8581
=> fix: ci: build macos and linux assets on tagged releases

chain/vm/fvm.go
=> fix: update StatApplied when fvm apply message

node/impl/full/gas.go
Resolves #8417
Have few unique multipleirs apart from the base multipleir
=> Gas estimation: Overestimate based on (actor, method) tuples

extern/storage-sealing/input.go
For each upgrade-marked sector, for each deal, this "info" log comes along but its not really "info" imho
none
Changes simple info log down to debug log
-
=> fix: Make deal making logs much less noisy

build/README-bundle.md, build/bundle.go, build/bundles.toml, node/bundle/bundle.go, node/bundle/manifest.go, node/modules/builtin_actors.go
On top of #8658.
Adds flexibility for bundle fetching, which can use an env var or explicit URL to avoid downloading from github.
cc @travisperson
=> [nv16] flexible bundle loading

Makefile, build/README-bundle.md, build/builtin_actors.go, build/bundle.go, build/bundles.toml, node/bundle/bundle.go, node/bundle/manifest.go, node/modules/builtin_actors.go
This adds some niceties for development bundle loading; see the README.
See #8625
=> [nv16] niceties for development bundle loading

extern/sector-storage/fsutil/filesize_unix.go, extern/sector-storage/stores/local.go, extern/sector-storage/stores/localstorage_cached.go, extern/sector-storage/stores/remote.go
No longer work in progress, trying to fix scheduler hangs when getting storage stats
=> stores: Deduplicate parallel stat requests

node/modules/builtin_actors.go
fixes issues with running with the wrong network name.
=> [nv16] add the network name to the bundle key in the datastore

cmd/lotus-miner/precommits-info.go, cmd/lotus-miner/sectors.go, documentation/en/cli-lotus-miner.md
https://github.com/filecoin-project/community/issues/522
=> feat: precommits info

chain/store/snapshot.go
Support raw blocks in chain export. We now visit them, we just don't recurs on them.
We need this for NV16 to include code in chain snapshots.
NOTE: I've also checked the splitstore, and we appear to be doing the right thing there already.
=> fix: vm: support raw blocks in chain export

documentation/en/default-lotus-miner-config.toml, node/config/doc_gen.go, node/config/types.go
Change text in default miner config to be more accurate
=> docs:sealing:fix default miner config comments

cmd/lotus-worker/main.go, documentation/en/cli-lotus-worker.md
lotus-worker has gained quite a lot of task-type flags, most of which are opt-out, which is a bit annoying, especially when creating storage-only workers. This PR adds a new flag which makes compute tasks opt-in instead of opt-out:
PreCommit1 worker before:
```
./lotus-worker run --precommit2=false --commit=false --prove-replica-update2=false --replica-update=false
```
PreCommit1 worker after:
```
./lotus-worker run --no-default --precommit1
```
- `area`: _api_, _chain_, _state_, _vm_, _data transfer_, …
=> feat: worker: lotus-worker run --no-default

.github/workflows/testground-on-push.yml
Start using `testground-github-action` from `testground` organisation - https://github.com/testground/testground-github-action. 
I copied the action to testground organisation and released it in there - https://github.com/testground/testground-github-action/releases/tag/v1.0.0
The action development is going to continue there.
- `area`: _api_, _chain_, _state_, _vm_, _data transfer_, _market_, _mempool_, _message_, _block production_, _multisig_, _networking_, _paychan_, _proving_, _sealing_, _wallet_, …
=> ci: deps: Use testground-github-action from testground org

api/cbor_gen.go, chain/exchange/cbor_gen.go, chain/market/cbor_gen.go, chain/types/cbor_gen.go, chain/vm/cbor_gen.go, cmd/lotus-shed/shedgen/cbor_gen.go, conformance/chaos/cbor_gen.go, extern/sector-storage/cbor_gen.go, extern/sector-storage/storiface/cbor_gen.go, extern/storage-sealing/cbor_gen.go, go.mod, go.sum, node/hello/cbor_gen.go, paychmgr/cbor_gen.go
=> deps: libp2p: update to the latest golibp2p tag

Makefile, build/bundle.go, build/params_2k.go, build/params_butterfly.go, build/params_calibnet.go, build/params_interop.go, build/params_mainnet.go, build/params_testground.go, node/bundle/manifest.go, node/modules/builtin_actors.go
fixes #8684
Set `NetworkBundle` in params file instead of in the Makefile. Otherwise, we end up overriding the
ldflags.
=> build: set NetworkBundle in params file

chain/actors/manifest.go, chain/consensus/filcns/upgrades.go
Strictly speaking not necessary, but just to be safe on the defensive programming side.
Also removes a stale TODO comment from the beginning of time.
=> [nv16] Ensure v8 bundle is loaded during migration

build/params_2k.go, build/params_butterfly.go, build/params_calibnet.go, build/params_interop.go, build/params_mainnet.go, node/modules/builtin_actors.go
The bundle preload during migration clobbers testing bundles and results in using the mainnet bundles if the migration happens during a test; not what we want.
This fixes by making NetworkBundle a variable, set by the test DI contraption, to work around this problem.
=> [nv16] don't clobber test bundles during migration

cmd/lotus-miner/sectors.go, cmd/lotus-shed/miner.go, cmd/lotus-shed/verifreg.go, documentation/en/cli-lotus-miner.md
Implements 3 new cli commands.
`compact-paritions` for general use. We never had a way to call this before.
`send-invalid-windowed-post` and `generate-and-send-consensus-fault` for testing purposes.
=> feat: cli: New commands for testing.

documentation/en/default-lotus-miner-config.toml, extern/sector-storage/manager.go, extern/sector-storage/manager_test.go, extern/sector-storage/request_queue.go, extern/sector-storage/request_queue_test.go, extern/sector-storage/sched.go, extern/sector-storage/sched_assigner_common.go, extern/sector-storage/sched_assigner_spread.go, extern/sector-storage/sched_assigner_util.go, extern/sector-storage/sched_assigner_utilization.go, extern/sector-storage/sched_post.go, extern/sector-storage/sched_resources.go, extern/sector-storage/sched_test.go, extern/sector-storage/sched_worker.go, extern/sector-storage/selector_alloc.go, extern/sector-storage/selector_existing.go, extern/sector-storage/selector_task.go, extern/sector-storage/stats.go, itests/kit/ensemble.go, itests/kit/node_opts.go, itests/worker_test.go, node/config/def.go, node/config/doc_gen.go, node/config/storage.go, node/config/types.go
* Add some more interfaces to the scheduling logic, which should make it easier to customize scheduling logic
* Add config allowing selection of worker assigners.
* Introduce new, simpler worker assigning logic - when enabled, the "spread" assigner will ignore worker utilization, and will attempt to assign tasks to as many workers as possible
To use the new assigner:
```toml
[Storage]
#
Assigner = "spread"
```
=> feat: sched: Add scheduler interfaces, configurable assigner

documentation/en/default-lotus-miner-config.toml, extern/sector-storage/manager.go, extern/sector-storage/sched.go, extern/sector-storage/sched_assigner_common.go, extern/sector-storage/sched_test.go, extern/sector-storage/selector_alloc.go, extern/sector-storage/selector_existing.go, extern/sector-storage/selector_move.go, extern/sector-storage/selector_task.go, itests/kit/ensemble.go, itests/kit/node_opts.go, itests/worker_test.go, node/config/doc_gen.go, node/config/storage.go, node/config/types.go
On top of https://github.com/filecoin-project/lotus/pull/8700 (to avoid conflicts and for easier testing - those PRs make most sense together)
* Add new mechanism to worker selectors which lets them decide that some workers are so much better than others, that other workers aren't even worth considering, even if that means that the task might be queued a bit longer
* Add a new `move` worker selector, which will strongly prefer workers which can perform a local move of data (they either have both storage paths locally, or already have the sector in the correct local path)
* Add a new config which makes it possible Finalize* to perform local-storage moves
```toml
[Storage]
#
DisallowRemoteFinalize = true
```
=> feat: sched: Finalize* move selectors

cmd/lotus-miner/run.go, cmd/lotus-miner/sealing.go, cmd/lotus-worker/main.go, extern/sector-storage/sched.go, extern/sector-storage/sched_test.go, extern/sector-storage/sched_worker.go, extern/sector-storage/storiface/worker.go, extern/sector-storage/worker_local.go
Add the --parallel-p1-limit parameter when the worker starts to set the maximum number of PreCommit1 tasks it can accept. When the miner schedules the PreCommit1 task to the worker, it will record the
The number assigned to it, when the number of assigned tasks is equal to the set maximum number of tasks, no new PreCommit1 tasks will be assigned to it, and will not be assigned again until a PreCommit1 task is executed.
The default value of the --parallel-p1-limit parameter is -1, which means no limit, and if the value of --parallel-p1-limit exceeds the maximum number of tasks that the worker hardware configuration can receive
won't work either.
When viewing worker information through lotus-miner sealing workers, the task number information of PreCommit1 will be displayed, as follows: …
=> scheduling optimization

chain/vm/fvm.go
Resolves #8463
This is not strictly needed, since all existing callsites of `ApplyImplicitMessage` check for a non-zero exit code and fail anyway. But nice to make it _explicit_!
=> fvm: fail if implicit message fails

extern/sector-storage/stores/local.go
Currently we print logs like
```
2022-05-27T19:46:05.586+0200    INFO    stores  stores/local.go:160     storage stat    {"took": 0.000045108, "reservations": 0}
2022-05-27T19:46:05.586+0200    INFO    stores  stores/local.go:160     storage stat    {"took": 0.000022857, "reservations": 0}
2022-05-27T19:46:05.586+0200    INFO    stores  stores/local.go:160     storage stat    {"took": 0.000016145, "reservations": 0}
2022-05-27T19:46:05.586+0200    INFO    stores  stores/local.go:160     storage stat    {"took": 0.000016495, "reservations": 0}
```
On all workers for each storage path every ~10s. This is extremely spammy, especially in larger setups with many workers and many storage paths
=> fix: worker: don't log normal storage stat calls

cmd/lotus-gateway/main.go, gateway/handler.go, itests/gateway_test.go, node/health.go, node/rpc.go
* New endpoints healthz and livez, this is helpful for kubernetes readiness and liveness probes.
* not included in this change, we will want to add an additional readiness probe to the gateway
see https://kubernetes.io/docs/reference/using-api/health-checks/
On k8s, health endpoints like this are used to move nodes into and out of service and load balancer pools.
- `area`: _api_, _chain_, _state_, _vm_, _data transfer_, _market_, _mempool_, _message_, _block production_, _multisig_, _networking_, _paychan_, …
=> feat: networking: add healthz and livez endpoints

cmd/lotus-bench/main.go, cmd/lotus-bench/simple.go
This is (eventually going to be) adding new lotus bench commands, mostly aimed to make new PoSt methods in https://github.com/filecoin-project/lotus/pull/7971 benchmarkable.
This PR adds a bunch of new commands to lotus-bench which make it possible to execute individual sealing operations on sector files manually
Todo:
=> feat: bench: simple sealing operations commands

build/params_2k.go, chain/actors/manifest.go, cli/state.go, documentation/en/cli-lotus.md
=> chore: state: add cli to get the manifest & actor cid for network v16 & up
