chain/gen/gen.go
https://github.com/filecoin-project/lotus/blob/3196b2cfd577907d871cd5de662206407d906577/chain/stmgr/utils.go#L462
=> delete repeat call func

.gitignore, Makefile, cmd/lotus-keygen/main.go
=> add keygen outfile

api/api_full.go, cli/client.go, cmd/lotus-storage-miner/market.go, documentation/en/api-methods.md, go.mod, go.sum, node/impl/client/client.go
Fixes https://github.com/filecoin-project/lotus/issues/5006
=> show data transfer ID in list-deals

api/api_storage.go, api/apistruct/struct.go, api/docgen/docgen.go, cmd/lotus-storage-miner/info.go, cmd/lotus-storage-miner/sectors.go, documentation/en/api-methods-miner.md, extern/storage-sealing/garbage.go, node/impl/storminer.go
https://github.com/filecoin-project/lotus/pull/5135 with some cleanup
=> Shaodan miner sectors info

cli/client.go
=> Print MinPieceSize when querying ask

extern/sector-storage/stores/remote.go
Simplified https://github.com/filecoin-project/lotus/pull/5167
=> stores: Bigger copy buffer size

markets/storageadapter/ondealsectorcommitted.go, markets/storageadapter/ondealsectorcommitted_test.go, paychmgr/settler/settler.go
Fixes https://github.com/filecoin-project/lotus/issues/5188
=> When waiting for deal commit messages, ignore unsuccessful messages

cmd/lotus-shed/blockmsgid.go, cmd/lotus-shed/main.go
=> lotus-shed blockmsgid command

cmd/tvx/exec.go, cmd/tvx/extract.go, cmd/tvx/extract_many.go, cmd/tvx/extract_message.go, cmd/tvx/extract_tipset.go, cmd/tvx/main.go, conformance/driver.go, conformance/runner.go
This PR introduces support for extracting tipset vectors from live chains.
```
$ tvx extract --class=tipset --tsk @324724
```
^^ This command will extract the tipset for height 324724.
=> tvx command to extract tipset vectors.

cli/multisig.go
=> fix lock propose

markets/storageadapter/client.go, markets/storageadapter/provider.go
Fixes https://github.com/filecoin-project/lotus/issues/5212
=> markets: Fix deal expired panic

build/isnearupgrade.go, build/params_2k.go, build/params_mainnet.go, build/params_testground.go, chain/actors/version.go, chain/gen/slashfilter/slashfilter.go, chain/stmgr/forks.go, chain/vm/syscalls.go, go.mod, go.sum
Brings in the fix for network halt around epoch 336459
TODO update actors with the actual fix
=> V9 Upgrade

extern/sector-storage/stores/index.go
update  weight canSeal and canStore when attach storage
=> update  weight canSeal and canStore when attach

extern/sector-storage/sched_worker.go
Avoid possible deadlock by sh.workersLk
=> Fix deadlock in runWorker in sched_worker.go 

build/params_2k.go, build/params_mainnet.go, cmd/tvx/codenames_test.go
Don't need this anymore, subsumes #4912.
=> Remove LOTUS_DISABLE_V2_ACTOR_MIGRATION envvar

chain/market/fundmanager.go
Fixes https://github.com/filecoin-project/lotus/issues/5257
=> Better error message when withdrawing funds

build/bootstrap.go
=> Skip bootstrapping if no peers specified

cli/chain.go
=> delete slash-consensus miner

cli/send.go
add fund sufficient check in send to avoid SysErrInsufficientFunds send. like https://filfox.info/zh/address/f1o2bwv33mqejxeqmh7qtb7wob4pjdho6rgvjp5la from 2020-12-23 14:40:30.
=> add fund sufficient check in send

extern/storage-sealing/states_failed.go
Fixes https://github.com/filecoin-project/lotus/issues/5097
=> storagefsm: Send correct event on ErrExpiredTicket in CommitFailed

cli/chain.go
add  from flag in lotus chian  slash-consensus cmd
=> add slash-consensus from flag

cmd/lotus-storage-miner/market.go
=> add verified indicator for storage-deals list

api/test/deals.go
This PR moves common code for the deals API tests into one place.
This will make it easier to merge some upcoming PRs
=> refactor deals API tests

extern/sector-storage/manager.go
Should make non-fast retrieval a bit faster in some cases
=> storagemgr: Always unseal full sectors

cmd/lotus-storage-miner/sectors.go
=> Show verified power in miner sector list

cmd/lotus-storage-miner/init.go, cmd/lotus-storage-miner/sectors.go, extern/storage-sealing/cbor_gen.go, extern/storage-sealing/checks.go, extern/storage-sealing/currentdealinfo.go, extern/storage-sealing/currentdealinfo_test.go, extern/storage-sealing/sealing.go, extern/storage-sealing/states_failed.go, extern/storage-sealing/types.go, extern/storage-sealing/types_test.go, markets/storageadapter/provider.go, storage/adapter_storage_miner.go, storage/miner.go
Branch for features which can land on master after the v3 actor upgrade epoch
=> 1.5.x staging branch

api/test/deals.go, go.mod, go.sum, node/node_test.go
Fixes https://github.com/filecoin-project/lotus/issues/5140 https://github.com/filecoin-project/lotus/issues/5409#issuecomment-766818577
Depends on:
TODO:
=> Fix zero price-per-byte retrieval

api/apistruct/struct.go
you get a not found error if you try to run StateReadState on a gateway
=> properly wire up StateReadState on gateway api

node/builder.go
This should make it easier to see what does what. It can also be a good starting point for modularizing things more
=> node builder: Cleanup and add some docstrings

api/api_full.go, documentation/en/api-methods.md, node/impl/full/state.go
This saves me an extra api call every time i use StateReadState. I pretty much always want the code CID too
=> add code cid to stateReadState output

api/api_full.go, cli/client.go, cli/test/client.go, documentation/en/api-methods-miner.md, documentation/en/api-methods.md, go.mod, go.sum, node/impl/client/client.go
Fixes https://github.com/filecoin-project/lotus/issues/5121 https://github.com/filecoin-project/lotus/issues/4381
Depends on https://github.com/filecoin-project/go-fil-markets/pull/487
=> show data transfer % for storage deals

Makefile
=> Verify FFI version before building

build/params_nerpanet.go
=> Set nerpanet's upgrade epochs up to v3 actors

go.mod, go.sum
Fixes #3099
Fixes #3221
Fixes #3242
Fixes #3599
Fixes #3830
Fixes #3940
Fixes #4674
Fixes #4972
Fixes #4983
Fixes #5113
Fixes #5130
Fixes #5585
=> Update go-jsonrpc fixing websocket reconnecting

cmd/lotus-fountain/main.go, cmd/lotus-fountain/recaptcha.go, cmd/lotus-fountain/site/funds.html, go.mod, go.sum
Uses reCAPTCHAv3, `RECAPTCHA_SITE_KEY` and `RECAPTCHA_SECRET_KEY` need to be
set in env.
=> Add spam protection to fountain

cli/disputer.go
This PR primarily moves all print statements to log statements, and changes the logger. Using the cli logger will make it much harder to monitor what is happening inside of the disputer. Some logs messages have been changed to errors were things seem to be an error. I've also made sure that we log an error if we are exiting due to an error.
=> Disputer logs to its own logger

api/test/tape.go, extern/sector-storage/mock/mock.go, go.mod, go.sum
=> Update actors to v3.0.2

build/params_calibnet.go, build/params_mainnet.go
=> Set nv10 upgrade epochs

CHANGELOG.md, build/version.go
=> Lotus version 1.5.0

extern/storage-sealing/states_failed.go
Fixes #3446
Fixes #4665
Fixes #3566
Fixes #4557
=> Remove sectors with all deals expired in RecoverDealIDs

blockstore/badger/blockstore.go
just some tuning, to free maximal space on GC -- idea from @Stebalien.
=> tune badger gc to repeatedly gc the value log until there is no rewrite

api/api_full.go, api/apistruct/struct.go, api/mocks/mock_full.go, api/types.go, chain/messagepool/check.go, documentation/en/api-methods.md, node/impl/full/mpool.go
=> mpool message check api

build/params_nerpanet.go, chain/stmgr/forks.go, cmd/lotus-seed/genesis.go
@liviudm please try to reset based on this branch, let's see how that goes...
Should address https://github.com/filecoin-project/lotus/issues/5782
=> Fix nerpa heights for a reset, swapout proof types

build/version.go
In line with the release process being prepared in https://github.com/filecoin-project/lotus/pull/5826/files
=> Bump master to 1.6.0-dev

cli/client.go
In manual testing this results in drastically higher success rate for me.
After setting max 150ms latency, making 20 deals, 12 got rejected immediately, 8 started transferring with decent speed right away.
=> Take latency into account when making interactive deals

miner/miner.go
I went on a trip to figure out what "catch-up/rush mining" is, and I found it hard to get a high-level description of what the miner does, so I looked at the code and documented it. Please check if my understanding is correct!
__More commits to follow__
=> add godocs to miner objects.

chain/actors/builtin/market/market.go, chain/actors/builtin/market/v0.go, chain/actors/builtin/market/v2.go, chain/actors/builtin/market/v3.go
=> expose NextID from nice market actor interface

chain/actors/policy/policy.go, extern/storage-sealing/checks.go, extern/storage-sealing/states_sealing.go
=> fix precommit ticket expiration handling

cmd/lotus-shed/election.go
lotus-shed election estimate  --network-power 1170 --miner-power 1 --seed 1
winInHour, winInDay, winInMonth, winInYear
0, 12, 364, 4438
=> add shed election estimate command 

extern/sector-storage/stores/http_handler.go
Fixes lint errors in https://github.com/filecoin-project/lotus/pull/5261
=> fix: stores.FetchHandler: defer close file and increase buffer size

cli/state.go
=> State CLI improvements

cli/mpool.go, cmd/lotus-shed/mpool.go
=> chore: Move lotus mpool clear to lotus-shed

CHANGELOG.md, build/version.go
=> Lotus v1.6.0

extern/storage-sealing/fsm.go, extern/storage-sealing/fsm_test.go
=> storagefsm: Apply global events even in broken states

chain/sync_test.go
=> Disable flaky checkpoint tests

markets/storageadapter/client.go
Fixes https://github.com/filecoin-project/lotus/issues/5952
=> Adjust client deal collateral overestimation to 1.2

lotuspond/spawn.go
Remove the usless commented code
=> Remove the usless commented code

api/client/client.go, api/v0api/gateway.go, api/v0api/latest.go, api/v0api/proxy_gen.go, cli/util/api.go
=> gateway: Fix api getter

scripts/generate-lotus-cli.py
Generate lotus command lines documents as text and markdown in folder "lotus/documentation/en".
=> Add script to generate lotus cli document.

chain/actors/policy/policy.go, chain/gen/gen.go, miner/miner.go
https://github.com/filecoin-project/lotus/pull/6183
=> This is a 1:1 forward-port of PR#6183 from 1.9.x to master

.circleci/config.yml
=> chore(ci): Enable build on RC tags

extern/storage-sealing/commit_batch.go, extern/storage-sealing/sealiface/config.go, extern/storage-sealing/sealing.go, extern/storage-sealing/terminate_batch.go, node/config/def.go
=> FIP 0013 addenda

node/impl/client/client.go
=> Extend the default deal start epoch delay

chain/actors/policy/policy.go, chain/actors/policy/policy.go.template, chain/vm/runtime.go, extern/storage-sealing/precommit_batch.go, go.mod, go.sum
=> Update to latest actors

chain/messagepool/messagepool.go, chain/messagepool/messagepool_test.go
Adds test for it
Resolves https://github.com/filecoin-project/lotus/issues/6338
Needs to be picked up by feat/nv13
=> Increase message size limit

chain/messagepool/check.go, chain/sub/incoming.go
the change of MaxMessageSize should take effect in all place you used
=> Fix: correct the change of message size limit

chain/actors/policy/policy.go, chain/actors/policy/policy.go.template, extern/storage-sealing/commit_batch.go, extern/storage-sealing/precommit_batch.go, extern/storage-sealing/sealing.go, storage/adapter_storage_miner.go
Excluding the changelog and version such
=> Merge v1.10 release branch into master

extern/storage-sealing/commit_batch.go
solve the problem https://github.com/filecoin-project/lotus/issues/6390
=> clean failed sectors in batch commit

extern/storage-sealing/commit_batch.go
Lifts #6451 into v1.10 release branch
=> failed sectors should be added into res correctly

go.mod, go.sum
https://github.com/filecoin-project/go-paramfetch/pull/14
=> Update to go-praamfetch with fslocks

itests/kit2/ensemble.go, itests/kit2/ensemble_opts.go, itests/kit2/funds.go, itests/kit2/log.go, itests/paych_api_test.go
=> convert paych tests to kit2

go.mod, go.sum
This is https://github.com/filecoin-project/lotus/pull/6482, but with conflicts resolved, and on a different branch so the release one doesn't get auto-closed
=> Merge 1.10 into master

itests/cli_test.go, itests/kit2/client.go, itests/kit2/ensemble.go, itests/kit2/ensemble_opts.go, itests/kit2/mockcli.go
- Copied client.go and mockcli.go from kit to kit2
- Modified cli_test.go to use kit2 primitives
=> Refactor cli test to kit2

cmd/lotus-sim/info.go, cmd/lotus-sim/info_message.go
Resolves https://github.com/filecoin-project/lotus/issues/6513
=> Add histogram and quantiles for message sizes

node/config/def.go
=> Update default fees for aggregates

build/params_mainnet.go
Time should be 2021-06-30T22:00:00Z
=> Set HyperDrive upgrade epoch

.circleci/config.yml
=> fix circleci being out of sync.

cli/client.go
=> Make query-ask CLI more graceful

.circleci/template.yml
=> Fix CircleCI gen

extern/storage-sealing/fsm.go, extern/storage-sealing/states_sealing.go
This is cherry-pick of one of the commits from https://github.com/filecoin-project/lotus/pull/6593
=> Fast-path retry submitting commit aggregate if commit is still valid 

extern/storage-sealing/commit_batch.go
Fixes https://github.com/filecoin-project/lotus/issues/6641
=> commit batch: Initialize the FailedSectors map

cli/filplus.go
Redo of https://github.com/filecoin-project/lotus/pull/6662
=> Fix tiny error in check-client-datacap

.circleci/config.yml, itests/nonce_test.go
I used this during a demo, and thought I'd add it to the corpus as a regression test.
=> add an incremental nonce itest.

cli/chain.go, documentation/en/cli-lotus.md
Fixes  #6266, using #6523. Thanks @rjan90 for the contribution!
=> Add helptext to lotus chain export

cli/state.go, documentation/en/cli-lotus.md
=> get-actor cli spelling fix

tools/packer/scripts/butterflynet/lotus-init.sh, tools/packer/scripts/calibrationnet/lotus-init.sh, tools/packer/scripts/mainnet/lotus-init.sh, tools/packer/scripts/nerpanet/lotus-init.sh
fixes: https://github.com/filecoin-project/lotus-infra/issues/378
=> add dollar sign

documentation/misc/RELEASE_ISSUE_TEMPLATE.md
=> Release Template: remove binary validation step

blockstore/splitstore/splitstore_expose.go, node/builder.go, node/modules/blockstore.go
=> Implement exposed splitstore

extern/storage-sealing/currentdealinfo.go, extern/storage-sealing/currentdealinfo_test.go
I don't know the code, but given I needed this to bring my node back up, here's a pull request.
=> fixes #6786 segfault

extern/storage-sealing/states_sealing.go
This is addressing review on https://github.com/filecoin-project/lotus/pull/6581
=> sealing: Handle preCommitParams errors more correctly

Makefile
support use `sudo make install-app APP=lotus-shed` to install special command.
=> easy way to make install app

go.mod, go.sum
=> update to go-fil-market v1.6.0

Makefile
Fixes https://github.com/filecoin-project/lotus/issues/6931
=> make: set default GOCC earlier

go.mod, go.sum
- Depends on:
https://github.com/filecoin-project/go-fil-markets/pull/595.
https://github.com/filecoin-project/go-data-transfer/pull/226.
=> Update deps for more logging in data transfer and markets

go.mod, go.sum
State machine PR at https://github.com/filecoin-project/go-statemachine/pull/28.
=> Update state machine deps for logging

cmd/lotus-miner/sealing.go
=> Improve formatting of workers CLI

cli/util/api.go
this includes:
And will be the code freeze for v1.11.1-rc2
=> Backport master -> v1.11.1

chain/actors/builtin/miner/state.go.template, chain/actors/builtin/miner/v0.go, chain/actors/builtin/miner/v2.go, chain/actors/builtin/miner/v3.go, chain/actors/builtin/miner/v4.go, chain/actors/builtin/miner/v5.go
1. Check error in EraseAllUnproven
2. Avoid dead code.
=> fix: vet actors shims

cmd/lotus-shed/genesis-verify.go
Slightly expands this useful command
=> Shed: Include network name in genesis-verify

.codecov.yml
Unfortunately, these changes don't apply till they hit master.
=> codecov: fix regexes

LOTUS_RELEASE_FLOW.md, documentation/Lotus release flow
Lotus release philosophy explained
=> Lotus release process  - how we make releases

cmd/lotus-miner/sectors.go
=> fix build after merging #6097.

cmd/lotus-miner/init.go, node/modules/storageminer.go
This is work done for my tribute work. I have **not** tested this with any miner.
- fixes #7097
=> fix(miner): always create miner deal staging directory

cmd/lotus-shed/cid.go
Useful for encoding actor code IDs
=> shed: Support raw encoding in cid id

.codecov.yml
Codecov randomly goes down more than 1% for PRs that don't change any code
=> Increase threshold from 0.5% to 1%

scripts/archive-branches.sh
Branches were archived to https://github.com/filecoin-project/lotus-archived
=> Update archive script

go.mod, go.sum
=> dep/fix 7701 Dependency: update to ipld-legacy to v0.1.1

cmd/lotus-miner/retrieval-deals.go
=> Sort lotus-miner retrieval-deals by dealId

lib/tracing/setup.go
Minor QOL improvement for open telemetry. Make sure to always sample (was setup that way as part of open census) and also add a big of logging assistance if anything goes wrong.
=> Minor improvement for OpenTelemetry

CHANGELOG.md, scripts/build-bundle.sh, scripts/publish-release.sh
=> misc: build: v1.13.2 back to master

build/proof-params/parameters.json, testplans/docker-images/proof-parameters.json
resolves #7887 
This is merged to v1.14.0 branch to prevent user use the temp params upon mainnet
=> feat: param: add temp snap params

extern/storage-sealing/checks.go, extern/storage-sealing/states_failed.go
=> fix: checkReplica incorrectly returns ErrBadPR

extern/sector-storage/ffiwrapper/basicfs/fs.go, extern/sector-storage/ffiwrapper/sealer_cgo.go
=> create replica update paths in acquireSectors

extern/sector-storage/manager.go
Definitely bugs, likely resolves #7968 
=> Fix: sealer: ReplicaUpdate should fetch the correct files

extern/sector-storage/ffiwrapper/sealer_cgo.go, extern/sector-storage/manager.go
=> fix: sealer: manager should lock Unsealed for ReplicaUpdate

extern/sector-storage/manager.go
We may wanna quiet down a few more of these
=> chore: sealer: quieten a log

.circleci/config.yml, .circleci/template.yml, build/proof-params/parameters.json
- update to the final  proof params for snap deals
- integrate the rust proof v11.0.1
- 
=> dep: proof: rust proof v11.0.1

build/params_calibnet.go
calib upgrade ~ Feb 9th 19:23 UTC
=> Set Calib OhSnap upgrade epoch

blockstore/autobatch_test.go
=> fix: test: remove unneeded ctx

build/params_butterfly.go
=> chore: butterfly: reset SnapNet

build/proof-params/parameters.json
=> fix: params: remove experimental params that's not used for production mainnet

go.mod, go.sum, testplans/lotus-soup/go.sum
=> deps: update go-paramfetch to v0.0.4

cli/net.go
Add CLI commands under `lotus net` to add/ remove/list protected peers.
Relates to: #7313
=> Add `lotus net` CLI command to add/remove/list protected peers

markets/idxprov/mesh.go
Add the peer ID of index provider host to the list of protected peers
before connecting to full node. Otherwise, it is possible for the
connection to be reset by full node before we reach the line that adds
the ID to list of protected peers via JsonRPC API.
Relates to:
- https://github.com/filecoin-project/index-provider/issues/177
=> Protect index provider peer ID before connecting to full node

cmd/lotus-miner/init.go, cmd/lotus-seal-worker/main.go, cmd/lotus-seal-worker/tasks.go, documentation/en/cli-lotus-worker.md, documentation/en/default-lotus-miner-config.toml, extern/sector-storage/manager.go, node/config/def.go
=> fix: sealer: allow enable/disabling ReplicaUpdate tasks

go.mod, go.sum, markets/retrievaladapter/client.go
Uses updated markets to simplify changes to the retrieval client adapter
=> feat(markets): update markets to simplify client adapter

chain/consensus/filcns/upgrades.go
=> feat: tweak v15 migration params

cmd/lotus-seal-worker/main.go
=> typo in  variable name

extern/storage-sealing/checks.go
=> sealer: fix error message

build/params_mainnet.go
Upgrade date and epoch mismatch
=> chore: comment: fix mainnet upgrade date typo, epoch is correct

go.mod, go.sum
get actor v7 (same commit as v7-rc1)
=> dep: actor: get v7

lotuspond/front/package-lock.json
node-fetch is to an unauthorised Actor
upgrade to node-fetch npm package
=> A package is vulnerable to Exposure of Sensitive Information 

extern/storage-sealing/states_replica_update.go
=> pay for the collateral difference needed if the miner available balance is insufficient

documentation/en/default-lotus-miner-config.toml, node/config/def.go, node/config/def_test.go
=> feat: config: enable indexer providing by default

cmd/lotus-shed/deal-label.go, cmd/lotus-shed/main.go
=> Shed: Add a tool to check UTF-8 validity of labels

go.mod, go.sum
=> deps: update go-libp2p to v0.18 release

cmd/lotus-worker/main.go
=> fix: worker: Fix default value handling

chain/vm/fvm.go
=> chore: ffi: the latest fvm release

cmd/lotus-sim/info_commit.go, cmd/lotus-sim/info_message.go, go.mod, go.sum
=> modify quantile imports error (go-v1.18.0)

cmd/lotus-shed/datastore-vlog.go
This PR makes the vlog2car command create car files with multiple vlog files
=> feat: shed: Multi-file vlog2car

.circleci/config.yml, .circleci/template.yml, node/builder_miner.go, node/modules/storageminer_idxprov.go
=> chore: backport: #8443 #8444 #8446

node/modules/lp2p/rcmgr.go
on top of #8469; merge that first.
=> enable rcmgr by default

extern/sector-storage/storiface/filetype.go
Should bring those numbers closer to reality
=> fix: storiface: Make FSOverhead numbers more accurate

.circleci/config.yml, .circleci/template.yml, .gitignore, build/builtin-actors/bundles.env, build/builtin-actors/fetch-bundles.sh, build/builtin_actors_2k.go, build/builtin_actors_butterfly.go, build/builtin_actors_calibnet.go, build/builtin_actors_interop.go, build/builtin_actors_mainnet.go, cmd/lotus-seed/genesis.go, node/builder.go, node/modules/builtin_actors.go, node/modules/testing/genesis.go
This ingests the bundles produced at release and selects the appropriate bundle based on build tags.
TBD:
=> [nv16] actor bundle integration

chain/actors/builtin/multisig/message.go.template, chain/actors/builtin/multisig/message0.go, chain/actors/builtin/multisig/message2.go, chain/actors/builtin/multisig/message3.go, chain/actors/builtin/multisig/message4.go, chain/actors/builtin/multisig/message5.go, chain/actors/builtin/multisig/message6.go, chain/actors/builtin/multisig/message7.go, chain/actors/builtin/multisig/message8.go
=> fix multisig for nv16

.golangci.yml
dear linter, using xerrors is what we want to do.
=> chore: fix lint issue

api/api_full.go, api/api_storage.go, api/mocks/mock_full.go, api/proxy_gen.go, api/v0api/full.go, api/v0api/proxy_gen.go, api/v0api/v0mocks/mock_full.go, node/impl/full/state.go, node/impl/storminer.go
https://github.com/filecoin-project/lotus/issues/8535#issuecomment-1106837421
Return pointer values to `MarketDeal` structs from `StateMarketDeals` and `MarketListDeals`.
I do not know what impact this will have down stream. Changing from a value to a pointer type could result in bugs down stream.
=> fix: api: Make MarketListDeals and DealsList return pointers for MarketDeal

itests/gateway_test.go
Test was creating msig wallet with a vesting schedule. Test was checking if total funds were strictly less than the total amount to be vested, which created a race condition. We now check if funds are equal or less than total vesting funds.
=> fix: test: Fix flaky TestGatewayWalletMsig

chain/consensus/filcns/upgrades.go
=> fix: upgrades: correct error message for v16 migration

Makefile, build/bundle.go, node/bundle/manifest.go, node/modules/builtin_actors.go
=> [nv16] use network bundle names consistent with the network name

Makefile, build/bundle.go
=> chore: bundle: make devnet get the right bundle

cmd/lotus-miner/sectors.go, documentation/en/cli-lotus-miner.md
=> Implement cli command for compactPartitions

chain/store/snapshot.go
Backports #8691
We need this for NV16 to include code in chain snapshots.
NOTE: I've also checked the splitstore, and we appear to be doing the
right thing there already.
=> fix: vm: support raw blocks in chain export

go.mod, go.sum
=> deps: libp2p: update to the latest golibp2p tag

build/bundle.go, build/bundles.toml, itests/wdpost_dispute_test.go, node/bundle/manifest.go
With both https://github.com/filecoin-project/builtin-actors/pull/372 and https://github.com/filecoin-project/builtin-actors/pull/373, this should make tests green on `feat/nv16`!
=> fix wdpost_dispute tests

build/params_2k.go, build/params_butterfly.go, build/params_calibnet.go, build/params_interop.go, build/params_mainnet.go, build/params_testground.go, chain/consensus/filcns/upgrades.go, node/impl/full/gas.go
=> Add disable flag for Skyr upgrade

build/params_interop.go
=> chore: bundle: update caterpillar cid

Makefile
Solved [Issues #8748 ](https://github.com/filecoin-project/lotus/issues/8748)
=> fix: lotus-bench make command

build/params_butterfly.go
=> chore: bundle: butterfly manifest cid & epoch

chain/consensus/filcns/filecoin.go, chain/messagepool/check.go, chain/messagepool/messagepool.go, chain/messagepool/selection.go, chain/vm/fvm.go, chain/vm/gas.go, chain/vm/mkactor.go, chain/vm/vm.go, conformance/runner.go
=> Revert "VM: Refactor pricelist to be based on network versions"

go.mod, go.sum
=> chore: deps: Use tagged version of specs-storage

node/bundle/manifest.go
=> Cleanup LoadBundle

go.mod, go.sum
=> chore: deps: update to go-libp2p v0.19.4

build/params_2k.go, cmd/lotus-seed/genesis.go, cmd/lotus-seed/main.go
=> fix: build: use the genesis network version when creating a network

build/params_2k.go, cmd/lotus-seed/genesis.go, cmd/lotus-seed/main.go
=> fix: build: genesis miner network version

build/params_2k.go
Fix the 2k build params so that everything builds.
=> fix: build: fix 2k build params

go.mod, go.sum
Reverts filecoin-project/lotus#8770
as its making things panicy
=> Revert "deps: update go-libp2p-pubsub to v0.7.0"

extern/sector-storage/manager_test.go, extern/storage-sealing/commit_batch.go, extern/storage-sealing/commit_batch_test.go, go.sum, testplans/lotus-soup/go.sum
=> Add new proofs version type

build/actors/pack.sh
=> fix: build: really make macos compatible

chain/rand/rand.go
=> fix: format error log

chain/vm/vmi.go
=> chore: refactor:  rename var name for syncing mainnet v15 using FVM

go.mod, go.sum, testplans/lotus-soup/go.mod, testplans/lotus-soup/go.sum
=> chore: deps: Update to go-state-types v0.1.10

itests/multisig_test.go
Relevant to an ongoing discussion: https://github.com/filecoin-project/builtin-actors/issues/426
This test examines behaviour when someone tries to send an infinitely recursive message.
=> Add a reentrant multisig test

chain/vm/fvm.go
=> fix: fvm: make exectraces match legacyVM some more

documentation/en/README.md
This PR fixes broken links in `./documentation/en/README.md`, 
pointing drive-by readers at useful resources.
=> docs: update ./documentation/en/README.md

chain/types/state.go
Flagged by @frrist that this info is missing.
=> chore: state: clarify state tree versioning in comment

go.mod, go.sum
=> fix:deps:bring in libp2p pubsub fix

cli/net.go, documentation/en/cli-lotus-miner.md, documentation/en/cli-lotus.md, go.mod, go.sum
=> chore:networking:disconnect cmd 

go.mod, go.sum
=> fix:deps:bring in libp2p pubsub fix to v17 release branch

cmd/lotus-miner/proving.go, documentation/en/cli-lotus-miner.md
Add description to the `lotus-miner proving compute` command.
resolves #8961 
=> ux: cli: add compute description

CHANGELOG.md, node/modules/storageminer.go, storage/wdpost/wdpost_run_faults.go, storage/wdpost/wdpost_sched.go
=> build: merge: v1.16.1 to master

.circleci/config.yml, itests/wdpost_config_test.go, storage/wdpost/wdpost_run_faults.go
=> chore: backport 9111

extern/sector-storage/worker_local.go
TODO comment indicates an intention to allow overriding the worker hostname.
Allows overriding worker hostname via an environment variable. This is in line with most worker configuration, which is all done via environment variables.
=> feat: sealing: Allow overriding worker hostname

README.md
=> chore:docs:remove readme reference to deprecated specs-actors

tools/packer/setup-snap.sh
=> Use lotus snap (and fix typo) for packer builds

storage/sealer/sched_worker.go
More detailed logs
Add the worker hostname into the assignment logs
=> fix: sealing: Add information on what worker a job was assigned to in logs

.circleci/config.yml, .circleci/template.yml
=> chore: ci: Update xcode version for macos builds

storage/sealer/cgroups_linux.go
=> fix: cgroupV1: memory.memsw.usage_in_bytes: no such file or directory

cmd/lotus-shed/datastore-vlog.go
=> feat: shed: add a --max-size flag to vlog2car

cmd/lotus-miner/actor.go
Adds the option to specify the account to send the message from in the `lotus-miner actor set-addrs` cmd.
Resolves #9221
=> fix: cli: Option to specify --from msg sender

CHANGELOG.md
=> chore: merge releases into master after v1.17.1 release

storage/pipeline/states_replica_update.go
Fixes https://github.com/filecoin-project/lotus/issues/9329
=> sealing: Avoid panicking in handleUpdateActivating on startup

chain/vm/cbor_gen.go, cli/state.go, go.mod, go.sum
Fixes https://github.com/filecoin-project/lotus/issues/9332
=> deps: Use latest cbor-gen

documentation/misc/RELEASE_ISSUE_TEMPLATE.md
Something that was needed for the 1.17.2 release.
clarify docs 
=> docs: release template: clarify location of version.go

.circleci/config.yml, .circleci/template.yml, build/params_calibnet.go, build/params_mainnet.go, cmd/lotus-miner/init.go, documentation/en/cli-lotus-miner.md
https://github.com/filecoin-project/lotus/pull/9364
https://github.com/filecoin-project/lotus/pull/9358
https://github.com/filecoin-project/lotus/pull/9350
=> v1.17.2 backports

.circleci/config.yml, .circleci/template.yml
https://github.com/filecoin-project/lotus/pull/9386
=> [v1.17.2 backport] Use golang 1.18.1 to build appimage

cli/state.go, cmd/lotus-shed/export.go, cmd/lotus-sim/create.go
N/A
Make `lotus-shed export --tipset=@1234` work
cc @magik6k @frrist
=> chore:shed: Teach shed/sim to understand --tipset=@nnn notation

chain/actors/builtin/miner/state.go.template, chain/actors/builtin/miner/v9.go
Miner actor state.Info() now returns information about beneficiaries.
=> fix: state: Return beneficiary info from miner state Info()

CHANGELOG.md
https://github.com/filecoin-project/lotus/issues/9336
=> chore: merge releases (v1.17.2) into master

build/bootstrap/butterflynet.pi
=> chore: butterfly: add artifacts

chain/messagepool/messagepool.go
=> fix: not multiplied by the number of seconds

build/bootstrap/butterflynet.pi
=> chore: butterfly: update assets

.github/pull_request_template.md
I'm opening quite a lot of PRs so I see it a lot and have some observations.
* Avoid line wraps in the 'write' mode
* Don't be as verbose with checklist areas
* Don't use `_` in the checklist
* Drop a (` `) prefix in the PR title example
* Make the first one/two words of each checklist item relay what the item is for
Before:
After:
=> misc: github: Cleanup PR template

.circleci/config.yml, .circleci/template.yml, tools/packer/lotus-snap.pkr.hcl, tools/packer/setup-snap.sh
https://github.com/filecoin-project/lotus/issues/9423
=> _ci_: Fix failing Digital Ocean and Amazon Machine Image release process

CHANGELOG.md
This is the last step before we cut the first RC of v1.18.0, which supports network v17. The version has already been updated in the destination branch.
Add the changelog produced by @jennijuju 
Supersedes #9487 
=> chore: add changelog to v1.18.0

go.mod, go.sum
=> chore:deps:Update to go-state-types v0.9.5 for migration fixes 

go.mod, go.sum
=> deps: go-state-type: update to go state type v0.9.6 with market migration fix

build/params_butterfly.go
Butterfly upgrade to nv17 will be 5 hours after deployment.
=> chore: butterfly: set new upgrade height for butterflynet

build/bootstrap/butterflynet.pi
butterfly reset , updated artifacts
=> chore: butterfly: artifacts

go.mod, go.sum
* Brings in the fix for https://github.com/filecoin-project/go-fil-markets/issues/753
* Fixes some identity CID handling issues
https://github.com/filecoin-project/go-fil-markets/compare/v1.24.0-v17...v1.25.0
=> deps: Update go-fil-markets to v1.25.0

build/params_mainnet.go
#9268 
Wednesday, Nov. 30th, 1400 UTC.
=> build: set shark mainnet epoch

chain/events/filter/event.go, itests/eth_filter_test.go, node/builder_chain.go, node/impl/full/eth.go, node/modules/actorevent.go
Based on feat/nv18-events branch
Fixes for EthSubscripton:
- don't reject subscriptions that have no min height
- buffer subscription output channel 
Refactoring:
- Make newEthBlockFromFilecoinTipSet, newEthTxReceipt, newEthTxFromFilecoinMessageLookup and lookupEthAddress free standing utility functions
=> feat: add test and fixes for EthSubscribe

.goreleaser.yaml
Backports https://github.com/filecoin-project/lotus/pull/9663
=> backport: Forgot to include linux binaries in goreleaser

CHANGELOG.md
=> chore: Update changelog for v1.19.0-rc1

cmd/tvx/extract_message.go
https://github.com/filecoin-project/ref-fvm/issues/944#issuecomment-1315245773
=> fix: tvx: missing parentheses

.gitattributes
=> feat: Use gitattributes to ignore generated files in diffs

documentation/misc/RELEASE_ISSUE_TEMPLATE.md
Adding additional steps we need to execute as part of the release process
=> docs: Update RELEASE_ISSUE_TEMPLATE.md

documentation/en/default-lotus-miner-config.toml, go.mod, go.sum, node/config/def.go, node/config/doc_gen.go, node/config/types.go, storage/sealer/faults.go, storage/sealer/manager.go
PRs backported:
https://github.com/filecoin-project/lotus/pull/9679
https://github.com/filecoin-project/lotus/pull/9680
=> backport: configurable pre check timeouts and zondax hid update

cmd/lotus-miner/actor.go
#9596
We can return the msg CID in error without panicking here.
=> fix: cli: correctly return error panic-less-ly

cmd/lotus-miner/sealing.go
A typo caused only one task count to be shown.
=> fix: cli: show task counts correctly

chain/actors/builtin/datacap/util.go
Thanks @frrist for pointing this out. This call should never error anyway, as long as the datacap actor keeps a correct state, but adding this check for safety.
=> fix: Add missing check in datacap for-each

chain/store/snapshot.go, cmd/lotus/daemon.go
The new snapshot service has .zst compressed snapshots at `https://snapshots.mainnet.filops.net/minimal/latest.zst` that are ~50% of the size of a non-compressed snapshot. This PR adds support for .zst imports, so it's possible to just do
`./lotus daemon --import-snapshot https://snapshots.mainnet.filops.net/minimal/latest.zst`
It also increases loading parallelism, which makes data import ~2x faster for me, going at ~200MiB/s, which makes snapshot import take ~4 min.
=> feat: chain: Faster snapshot imports, zstd import

chain/store/store_test.go, cmd/lotus-shed/genesis-verify.go
https://github.com/filecoin-project/lotus/pull/9741 made chain import parallel
Use thread-safe blockstores in tests.
=> fix: chain: Fix flaky TestChainExportImport

node/modules/storageminer.go
=> fix: don't log sp address in binary on node startup

cmd/lotus-miner/info.go
=> fix: miner info: Output correct StartTime

storage/pipeline/input.go, storage/pipeline/sealing.go
=> chore: backport: panic fix

cmd/lotus-shed/actor.go, go.mod, go.sum
https://github.com/filecoin-project/lotus/issues/9818
=> cli: Add lotus-shed cli for computing frc42 method num

.goreleaser.yaml
=> fix: ci: release title fix 

CHANGELOG.md
=> chore: merge releases back into master

chain/actors/builtin/datacap/actor.go.template, chain/actors/builtin/datacap/datacap.go, chain/actors/builtin/datacap/state.go.template, chain/actors/builtin/datacap/v10.go, chain/actors/builtin/datacap/v9.go, chain/actors/builtin/registry.go, chain/actors/builtin/registry.go.template, chain/gen/genesis/f07_dcap.go, cmd/lotus-miner/actor.go, cmd/lotus-shed/actor.go, cmd/lotus-shed/miner-multisig.go, go.mod, go.sum
Integrates https://github.com/filecoin-project/go-state-types/pull/131
=> chore: Update go-state-types

.circleci/config.yml, chain/actors/builtin/builtin.go, chain/actors/builtin/builtin.go.template, chain/types/ethtypes/eth_types.go, cli/eth.go, documentation/en/cli-lotus.md, itests/fevm_address_test.go
https://github.com/filecoin-project/lotus/issues/9848
https://github.com/filecoin-project/lotus/issues/9783
Add integration test to demonstrate f4 address capabilities
Also add tooling to generate eth address from code
`➜  lotus git:(sbansal/f4-integration-test) ✗ ./lotus eth contract-address 0xff00000000000000000000000000000000000064 0000000000000020000000000000000000000000000000000000000000000000 itests/contracts/SimpleCoin.bin
Contract Eth address:  0x350a98790ec55440aff3c05bce93cd0eec8abd85`
- `area`, e.g. api, chain, state, market, mempool, multisig, networking, paych, …
=> test: Add f4 address integration test and cli to generate eth address from code

chain/vm/fvm.go
This doesn't need to be exported, and I don't want anything else relying on it.
Restrict it.
=> chore: VM: don't export Extern::VerifyBlockSig

.circleci/config.yml, chain/types/ethtypes/eth_transactions_test.go, itests/eth_balance_test.go, itests/eth_transactions_test.go
https://github.com/filecoin-project/lotus/issues/9849
=> itests: Add tests for eth get balance and transaction submits

itests/eth_account_abstraction_test.go
https://github.com/filecoin-project/ref-fvm/issues/1327
Adds the test cases described in the issue.
Needs https://github.com/filecoin-project/ref-fvm/pull/1355 in an FVM release (and introduced in FFI) for one of the new test cases to 💚 
=> feat: more ethaccount abstraction tests

build/params_hyperspace.go
=> fix: hyperspace build

build/params_hyperspace.go
=> misc: align the network name

build/params_hyperspace.go, build/params_wallaby.go
=> chore: turn off actor debug fro wallaby and hyperspace

build/params_hyperspace.go
network genesis  6:00 UTC, Jan 16th, 
upgrade at 15:00 UTC, 10:00 EST, jan 18th
=> chore: hyperspace nv19 upgrade epoch

node/rpc.go
=> fix: should not serve non v0 api in v0

node/rpc.go
=> fix: should not serve non v0 apis in v0

.circleci/config.yml, .circleci/template.yml
Backports https://github.com/filecoin-project/lotus/pull/10088
=> backport: fix: ci: Properly balance <<?>> in circleci docker config

cli/client.go
This "worked" on mainnet because there are so many SPs there that with 50x parallelism we still got most of them.
=> fix: cli: Wait for all results in GetAsks

.circleci/config.yml, .circleci/template.yml
Backports https://github.com/filecoin-project/lotus/pull/10096
=> Backport: fix: ci: Add back <<network>> parameter for docker push

cmd/lotus-shed/address.go
=> chore:shed:encode address to bytes

node/impl/full/eth.go
Fixes #10108 
Drop a horrendous hack that should never have been merged.
=> fix: EthAPI: Drop hack in GetStorageAt

node/impl/full/eth.go
Fixes #10107 
We were expecting a CBOR-byte string on all returns, which is not the case for contract deployments. I'm still not sure what we should _actually_ return in this case, Slack discussion [here](https://filecoinproject.slack.com/archives/C0370V3JTPB/p1674586600736189)
=> fix: EthAPI: Handle EthCall return correctly

.github/workflows/codeql-analysis.yml
Code QL v1 was discontinued last week. Runs are now failing. This should fix it. https://github.blog/changelog/2023-01-18-code-scanning-codeql-action-v1-is-now-deprecated/
We will also run Code QL on release branches because we have checks for it...
I couldn't find a way to get the `ci` check to be required. Github doesn't pick up the result of the whole workflow. I tried enabling GitHub Check on CircleCI but that literally made things worse, with the individual tests not showing up in the list in PRs
- `area`, e.g. api, chain, state, market, mempool, multisig, networking, …
=> chore: ci: Update codeql to v2

.github/workflows/codeql-analysis.yml
backports https://github.com/filecoin-project/lotus/pull/10120
=> backport: chore: ci: Update codeql to v2

node/impl/full/eth.go
This will just cause signature validation to fail.
=> fix: don't replace the method in EthSendRawTransaction

node/rpc.go
Reimplements https://github.com/filecoin-project/lotus/pull/10065/files which was reverted
=> fix: api: should not serve non v0 apis in v0

go.mod, go.sum
Pulls in https://github.com/filecoin-project/go-jsonrpc/pull/94
This fixes handling of the `params` object when it's not present.
=> deps: Update go-jsonrpc to v0.2.1

documentation/en/WIP-arch-complementary-notes.md, documentation/en/about.md, documentation/en/architecture/architecture.md, documentation/en/block-validation.md, documentation/en/create-miner.md, documentation/en/dev-tools-pond-ui.md, documentation/en/jaeger-tracing.md
=> Fix: typos

cmd/lotus-miner/sectors.go
=> fix: cli: extend cmd to get the right sector number

itests/kit/evm.go
-  https://github.com/filecoin-project/ref-fvm/issues/1491
- quality of life improvement for evm tests - print evm error and bubble up evm error in a helper
=> tests: itests: log evm errors

chain/types/ethtypes/eth_types.go, itests/eth_filter_test.go, node/impl/full/eth.go
Fixes https://github.com/filecoin-project/lotus/issues/10196
=> fix: ethrpc: emit correct bloom filters

itests/eth_filter_test.go, node/impl/full/eth.go
Fixes https://github.com/filecoin-project/lotus/issues/10207
=> fix: ethrpc: Don't send sub notifs in array

build/bootstrap/butterflynet.pi
* bootstrap node multiaddr
* new genesis file
these files are necessary for others to build lotus and join the new butterflynet, reset on February 08, 2023
=> updates butterflynet reset artifacts

go.mod, go.sum
=> backport: deps: update ipld prime

.circleci/config.yml, itests/eth_bytecode_test.go, itests/kit/evm.go, node/impl/full/eth.go
fixes https://github.com/filecoin-project/ref-fvm/issues/1641
1. If the actor is a non-evm actor, return "nothing".
2. Correctly handle missing actors.
3. Handle self-destructed actors (they'll return "null").
=> fix: eth: correctly handle ethGetCode ege-cases

build/params_hyperspace.go
(1677510000-1673848800)/30 = 122040
=> Hyperespace: Upgrade epoch for nv21

.github/ISSUE_TEMPLATE/enhancement.yml, .github/ISSUE_TEMPLATE/feature_request.yml
Part of #10242 
Update enhancement.yml and feature_request.yml templates:
- Removing unnecessary checklist options.
- These have been move to the Github New Issue UI to reduce text overhead: #10268
- Remove deprecated component options
- Add FVM/FEVM component
=> chore: github: update enhancement and feature templates

api/api_gateway.go
Simple code comment update around gateway patch
`make gen` didn't work with me. Then @jennijuju proposed to use `make clean && make all` first, which helped. I think it would be great to have full command here
=> docs: API Gateway: patch documentation note about make gen command

build/drand.go
#10473 
This is a regression introduced by [this hack](https://github.com/filecoin-project/lotus/pull/9654/files/62fedfbce3feb078cff785b8550d97c3bcb7eafe#r1024148908) that we never got a good answer for why it was needed.
Drop the hack. I'm unclear as to what breaks, so we need to understand that.
=> fix: build: drop drand incentinet servers

blockstore/splitstore/splitstore_compact.go
=> Don't enforce walking receipt tree during compaction

blockstore/splitstore/splitstore_compact.go
Now that receipts have events tipsets being protected commonly have missing references.  So add missing refs to debug logs from warning
=> fix:splitstore:Demote now common logs

cmd/lotus-miner/sectors.go
=> backport: fix: miner: correctly count sector extensions

build/params_testground.go
This was missing from #9858 
Add missing variable to params_testground.
=> fix: build: add CBDeliveryDelay to testground

blockstore/badger/blockstore.go, blockstore/blockstore.go, blockstore/splitstore/splitstore.go, blockstore/splitstore/splitstore_compact.go, blockstore/splitstore/splitstore_gc.go
=> Backport #10392 into v1.21.0

chain/consensus/filcns/upgrades.go
Forgot to actually schedule the migration
=> chore:migration:actually schedule migration

chain/sub/bcast/consistent.go
Also hold the lock when checking the length of the blocks in the bcastDict.
=> fix: check for nil bcastDict

CHANGELOG.md
=> actor cids in changelog

go.sum, itests/wdpost_test.go
Updates to tagged FFI release.
=> chore: deps: update to FFI v1.23.0

itests/wdpost_test.go
=> feat: Update FFI, test disputing nv20 window posts fails

documentation/en/default-lotus-miner-config.toml, node/config/def.go
https://github.com/filecoin-project/lotus/issues/10708
=> Set default for MaxSectorProveCommitsSubmittedPerEpoch

blockstore/splitstore/splitstore_compact.go
=> fix:splitstore:Don't block when potentially holding txnLk as writer

go.mod, go.sum
* Pulls in https://github.com/filecoin-project/go-jsonrpc/pull/101 
* Also pulls in https://github.com/filecoin-project/go-jsonrpc/pull/99
=> deps: Update go-jsonrpc to v0.3.1

cmd/lotus-fountain/site/funds.html, cmd/lotus-fountain/site/index.html, cmd/lotus-fountain/site/main.css
=> Make lotus-fountain UI slightly friendlier

chain/store/store.go
=> Check if epoch is negative in GetTipsetByHeight

cmd/lotus-fountain/site/datacap.html, cmd/lotus-fountain/site/funds.html, cmd/lotus-fountain/site/main.css
- change button color on hover over so it doesn't look disabled
-  clearer form title and explanation
- hint about addresses
=> Calibration faucet UI improvements

cli/state.go
=> opt: cli: If present, print Events Root

chain/messagepool/check.go
fix https://github.com/filecoin-project/lotus/pull/10693
=> fix: not call RUnlock

go.mod, go.sum
=> chore: deps: update to go-libp2p 0.27.5

Makefile
=> Small improvement to make gen output

CHANGELOG.md
=> chore: update changelog title and comments

documentation/en/default-lotus-config.toml, node/config/doc_gen.go, node/config/types.go
=> Add comment stating msgIndex is an experimental feature

cmd/lotus-shed/block.go, cmd/lotus-shed/main.go
=> feat: shed: command for decoding block headers

chain/events/filter/index.go
The 1.23.3-rc1 release candidate is experiencing a slow startup problem on some nodes, caused by #11056. This has been fixed in #11064 
We're backporting this fix into the 1.23.3 branch as it's needed for a healthy release.
=> Add tmp indices to events table while performing migration to V2

cmd/lotus/daemon.go
=> feat: daemon: improvemens to the consensus slasher

itests/api_test.go, itests/msgindex_test.go
These tests have been observed to deflake due to calculating real proofs, eg. https://app.circleci.com/pipelines/github/filecoin-project/lotus/29379/workflows/1c40c501-fbdd-4bc7-90ae-5aacba085c2d/jobs/1001935
Use MockProofs for tests that don't need to be using real ones.
=> feat: deflake: Use MockProofs

CHANGELOG.md
Addresses a request from @jennijuju made [here](https://www.notion.so/Write-explainer-doc-for-SPs-183a7775406d451a8b19e3cdc2cdf5c3?d=d8df4e142b78427ab470db68877da1ba&pvs=4#abba19208e3b4420a6388df7a3a48b62).
Add details of the tracer experiment to the 1.23.3 release notes.
=> feat: changelog: add details of tracer experiment

chain/vm/syscalls.go, itests/deals_test.go
Closes https://github.com/filecoin-project/lotus/issues/3322
(just a quick fix closing a random issue while I'm waiting for CI on another PR)
=> chore: legacy syscalls: Cleanup ComputeUnsealedSectorCID

go.mod, go.sum
New release from the go-libp2p team
Update the deps
=> chore: deps: update go-libp2p to v0.27.8

storage/sealer/ffiwrapper/sealer_cgo.go
=> fix: downgrade harmless warning to debug

storage/sealer/ffiwrapper/sealer_test.go
Enable testing of TestSealAndVerify3 on a MacOS machine.
=> mac seal test

storage/sealer/ffiwrapper/sealer_test.go
This test has flaked:
- https://app.circleci.com/pipelines/github/filecoin-project/lotus/29861/workflows/777252d0-9f09-4759-a125-5f897e9c7c5c/jobs/1027921
- https://app.circleci.com/pipelines/github/filecoin-project/lotus/29882/workflows/78217c69-2a36-4917-92b3-2b0f9565ed60/jobs/1029105
- https://app.circleci.com/pipelines/github/filecoin-project/lotus/29887/workflows/778022b1-45b3-4f18-a163-c288f639a3f4/jobs/1029374
- https://app.circleci.com/pipelines/github/filecoin-project/lotus/29519/workflows/577e2a52-2ad6-4675-9d22-2f4f2cc72f36/jobs/1008539
- https://app.circleci.com/pipelines/github/filecoin-project/lotus/30163/workflows/e834851d-9e8f-4fa0-b7e8-bd16d9f83b9e/jobs/1043798
We've been talking about it for [a while now](https://filecoinproject.slack.com/archives/CP50PPW2X/p1689432930181 …
=> feat: skip TestSealAndVerify3 until it's fixed

node/modules/services.go
Backports #11262 
This improves some sync issues first reported by @rjan90 
=> chore: backport #11262

chain/consensus/compute_state.go, chain/consensus/filcns/filecoin.go
Double check exitcode: https://github.com/filecoin-project/lotus/blob/master/chain/consensus/compute_state.go#L138-L151
=> opt: fix duplicate check exitcode

cmd/lotus-worker/main.go
Backport https://github.com/filecoin-project/lotus/pull/11294 to `release/v1.23.4`
=> chore: backport #11294 into `release/v1.23.4`

LOTUS_RELEASE_FLOW.md
Completed the "TODO" in the code.
Added the proper link as proposed in the TODO.
=> docs: Link the release section in the release flow doc

build/bootstrap/butterflynet.pi
Add the new Butterfly assets after the recent reset.
=> chore: butterfly: Update Butterfly Assets

documentation/en/default-lotus-miner-config.toml, node/config/doc_gen.go, node/config/types.go
Update SectorLifetime duration comment to be in line with FIP-0052: https://fips.filecoin.io/FIPS/fip-0052.html which is scheduled for the nv21 upgrade.
=> fix: docs: Update SectorLifetime to be in line with FIP-0052

chain/store/messages.go, chain/store/snapshot.go
=> chore: slice loop replace

cli/state.go
@Reiers has a script displaying this every second, and it's hard to read because the order keeps changing.
Sort alphabetically by actor "key" name before printing.
=> feat: cli: sort actor CIDs alphabetically before printing

miner/miner.go
=> feat: miner: defensive check for equivocation

itests/eth_transactions_test.go, node/impl/full/eth_utils.go
fixes #11252
Use the correct base-fee when computing the "effective gas cost" in Eth transaction receipts. Thanks to @wanyvic for pointing this out.
=> fix: api: compute the effective gas cost with the correct base-fee

cmd/lotus-gateway/main.go
Fix a minor typo in the `rate-limit` flag
=> fix: typo in rate-limit flag description

cmd/lotus-shed/invariants.go
add support for v12 check invariants and also a default case to reduce future confusion
currently merging this into master, not sure what branch it needs to be on - the cherry pick commit is fefd851569d4dad5d3ff0efeb8056c2779e152f9
=> fix: check invariants: v12 check

build/params_calibnet.go, build/params_mainnet.go
=> chore: watermelon: upgrade epoch

documentation/en/default-lotus-miner-config.toml, node/builder.go, node/builder_miner.go, node/config/doc_gen.go, node/config/types.go
=> feat: lotus miner config to entirely disable WindowPoSt

cmd/lotus-miner/actor.go, documentation/en/cli-lotus-miner.md
backport #11408 to release/v1.24.0
=> chore: backport #11408 to release/v1.24.0

cmd/lotus-provider/migrate.go
getInfo() implemented
I implemented this as requested, but I'm still seeing the repo lock fail, so I think the migrator needs some different handling there. 
=> migrate-fix

metrics/metrics.go
=> style : metric : metric milliseconds computation with golang original method

go.mod, go.sum
fix the go state type release for nv21
=> deps: gostatetype

.circleci/config.yml, .circleci/template.yml
In #11212, we added the necessary logic to download the params automatically. However, we're not taking advantage of CI caching.
Here, we configure CI to cache these params.
=> fix: ci: fetch params for the storage unit tests

storage/paths/db_index.go
Bug found starting lotus-miner in 1.25.1 with sector index.
=> Fix sector filetype

provider/lpmessage/sender.go
Backports #11480 to the `release/v1.25.1` branch
=> chore: backport: lotus-provider msg sending fix

provider/lpwinning/winning_task.go
=> fix: lotus-provider: Fix winning PoSt

cmd/lotus-provider/migrate.go
Avoid saying on the migrator output the redundant line
--layer="base"
=> do not suggest the default layer

storage/sealer/worker_local.go
* Read proofs into an array at fixed indexes instead of appending to a list
* Appending wasn't deterministic because challenges are read in parallel
* Then compact skipped vanilla proofs, keeping the correct order
* Testing:
*  [ ] Compute a PoSt with a bunch of sectors per partition (one partition is enough)
*  [ ] Compute a PoSt with skipped sectors (disable PoSt pre-checks so that this logic catches bad sectors)
=> fix: wdpost: fix vanilla proof indexes

go.mod, go.sum
=> deps: multiaddress

go.mod, go.sum
See https://github.com/filecoin-project/lotus/pull/11185.
Switch to the upstream poseidon library.
The upstream PR was merged https://github.com/triplewz/poseidon/pull/1.
=> chore: mod: use upstream poseidon

cmd/lotus-miner/init.go, cmd/lotus-miner/init_restore.go, cmd/lotus-miner/init_service.go, documentation/en/cli-lotus-miner.md
fast storage miner init for my integration test
=> feat: add confidence for init miner

Makefile
Docker has lotus-provider build failure
=> fix: docker

Makefile
Backports #11559 to release/v1.25.2
=> backport: docker build fix for v1.25.2

node/impl/full/state.go
=> fix: add UpgradePhoenixHeight to StateGetNetworkParams

build/bootstrap/calibnet.pi
Update the Bootstrap peer list in the calibration network.
=> Chore: calibnet: Update bootstrap peer list

chain/consensus/filcns/upgrades.go
=> chore: fix two typo

chain/consensus/filcns/filecoin.go, chain/consensus/filcns/upgrades.go
=> chore: docs: Fix two typos

chain/messagepool/provider.go
Mpool startup in lite mode for some reason requests the same actor head 1000s of times (probably for each message ever sent)
This makes my node start in ~2 seconds instead of roughly 20min when backed by a lite node
Likely there is a better fix to the underlying issue like cleaning up messages in mpool after finality, but this is way simpler and also solves the issue.
=> feat: mpool: Cache actors in lite mode

storage/pipeline/commit_batch.go, storage/sealer/partialfile/partialfile.go, storage/sealer/sched_worker.go
=> chore: fix typos

api/api_gateway.go, api/proxy_gen.go, build/openrpc/full.json, build/openrpc/gateway.json, build/openrpc/miner.json, build/openrpc/worker.json
Add StateMinerDeadlines to gateway.
https://github.com/filecoin-project/lotus/discussions/11693
=> feat: add StateMinerDeadlines to gateway

CHANGELOG.md, chain/events/state/predicates.go, chain/messagepool/selection_test.go, chain/sync_manager.go, cmd/lotus-sim/simulation/simulation.go, conformance/driver.go
=> chore: remove repetitive words

api/api_gateway.go, api/proxy_gen.go, build/openrpc/full.json, build/openrpc/gateway.json, build/openrpc/miner.json, build/openrpc/worker.json, gateway/node.go, gateway/proxy_fil.go
#11722 
Adds `ChainGetEvents` to the gateway API, rate limited under the "chain" operations.
=> feat: add ChainGetEvents to the gateway API

go.mod, go.sum
Update GST to v0.13.0-rc3 which includes https://github.com/filecoin-project/go-state-types/pull/254
=> chore: deps: update GST to v0.13.0-rc3

cmd/curio/cli.go
One change missed in LP->Curio refactor
=> fix: curio: Fix env name in cli.go

lib/harmony/harmonydb/harmonydb.go
This is a correct-er version of https://github.com/filecoin-project/lotus/pull/11765
Resets code to f11a6058b5f2c267266ee9e6c2161055830fb031
=> chore: revert accidental direct commits to master

documentation/misc/RELEASE_ISSUE_TEMPLATE.md
Update the `release_issue_template.md`, removing some outdated checks
=> fix: docs: Update release_issue_template.md

.github/workflows/sync-master-main.yaml
https://github.com/filecoin-project/lotus/pull/11762
Gives write access to the repository to the master main sync workflow.
Follow up to https://github.com/filecoin-project/lotus/pull/11762
=> fix: ci: allow master main sync to write to the repository

cmd/curio/cli.go, cmd/curio/config.go, cmd/curio/config_test.go, cmd/curio/storage.go, cmd/lotus-shed/deal.go, curiosrc/ffi/sdr_funcs.go, curiosrc/market/fakelm/iface.go, curiosrc/seal/README.md, documentation/en/cli-curio.md, documentation/en/default-curio-config.toml, node/config/doc_gen.go, node/config/types.go
=> fix: curio: rename remaining lotus-provider references

chain/types/tipset_key_test.go
Sanity checking and making it easier for alternative implementation compatibility.
Came from wanting to do an alternative implementation and wanting some fixed forms to tests.
=> test(tipsetkey): add tests for derived CID forms

chain/vm/execution.go
This is showing up in profiles so I figured I'd optimize it a bit:
1. Avoid holding locks while recording metrics.
2. Slightly reduce allocations by re-using the metrics "mutators".
Also, use the passed context for better tracing.
This is unlikely to make a huge difference, but it may help RPC providers a _tiny_ bit and doesn't really move the complexity needle.
=> feat: fvm: optimize FVM lanes a bit

documentation/misc/RELEASE_ISSUE_TEMPLATE.md
From the experience of doing 1.26.2 and making some mistakes.
=> doc(release): minor doc updates to release process

api/api_curio.go, api/proxy_gen.go, build/openrpc/full.json, build/openrpc/gateway.json, build/openrpc/miner.json, build/openrpc/worker.json, cmd/curio/cli.go, cmd/curio/log.go, cmd/curio/main.go, cmd/curio/rpc/rpc.go, cmd/curio/tasks/tasks.go, documentation/en/api-v0-methods-curio.md, documentation/en/cli-curio.md
Only following common commands were retained
- Version
- Log - list, set-level (nested in cli)
- FetchParams
- Wait-api (nested in cli)
Rest of the commands are not really required in Curio.
=> fix: curio: common commands

chain/sub/ratelimit/window.go, cmd/tvx/extract_tipset.go, node/config/load_test.go, storage/pipeline/fsm_events.go, tools/stats/sync/sync.go
=> chore: fix some typos in comments

chain/stmgr/supply.go, chain/sync_test.go, cmd/lotus-sim/simulation/blockbuilder/blockbuilder.go
=> Fix function names in comment

conformance/driver.go
https://github.com/filecoin-project/lotus/issues/11890
Pass `timestamp` through the `ExecuteMessageParams` type 
=> Fix:conformance driver:pass timestamp through `ExecuteMessageParams`

curiosrc/gc/storage_endpoint_gc.go, lib/harmony/harmonytask/singleton_task.go
This PR fixes some bugs found when testing https://github.com/filecoin-project/lotus/pull/11884
=> fix: curio: sectorindex gc fixes

scripts/snap-lotus-entrypoint.sh
The url [https://fil-chain-snapshots-fallback.s3.amazonaws.com/mainnet/minimal_finality_stateroots_latest.car](https://fil-chain-snapshots-fallback.s3.amazonaws.com/mainnet/minimal_finality_stateroots_latest.car), so replacing it with forest snapshot link.
- [X ] Commits have a clear commit message.
=> fix: docs: Replacing deadlink

cmd/lotus/daemon.go
Don't bother consulting the config and just try to delete splitstore directory.  This avoids an annoying failure if there is no config directly in the fs repo.  
Bug reported by @Ezequiel on slack.  Thanks!
=> fix:cmds:Allow remove of repos without configs 

cmd/lotus-sim/simulation/mock/mock.go, cmd/lotus-sim/simulation/stages/commit_queue.go, cmd/lotus-sim/simulation/stages/precommit_stage.go, itests/eth_hash_lookup_test.go
Fix mismatched method names in comments
=> fix: comments: Fix mismatched method names in comments

lib/harmony/harmonydb/sql/20240317-web-summary-index.sql, lib/harmony/harmonydb/sql/20240420-web-task-indexes.sql
* clusterMachineSummary is a few % faster, not much impact on that query (takes 1.5s, so probably will warrant more optimizations at some point)
* clusterTaskHistorySummary went down to 100ms from waay-too-slow 5s+
clusterMachineSummary
```sql
EXPLAIN (ANALYZE, BUFFERS)
SELECT hist.completed_by_host_and_port, hist.name, hist.result, count(1)
FROM harmony_task_history hist
WHERE hist.work_end > now() - INTERVAL '1 day'
GROUP BY hist.completed_by_host_and_port, hist.name, hist.result
ORDER BY completed_by_host_and_port ASC;
Sort  (cost=16296.23..16296.98 rows=300 width=575) (actual time=1611.633..1611.634 rows=14 loops=1)
Sort Key: completed_by_host_and_port
Sort Method: quicksort  Memory: 26kB
->  HashAggregate  (cost=16280.88..16283.88 rows=300 width=575) (actual time=1611.601..1611.605 …
```
=> feat: curioweb: Improve task_history indexes

storage/paths/local.go
make it easier to reason about by breaking-up the parts
=> simpler release logic

build/openrpc/full.json, build/openrpc/gateway.json, build/openrpc/miner.json, build/openrpc/worker.json, build/version.go, documentation/en/cli-curio.md, documentation/en/cli-lotus-miner.md, documentation/en/cli-lotus-worker.md, documentation/en/cli-lotus.md, documentation/en/cli-sptool.md
Bump version in master in preparation for cutting v1.27.0-rc1
=> chore: bump build version in master

CHANGELOG.md, build/openrpc/full.json, build/openrpc/gateway.json, build/openrpc/miner.json, build/openrpc/worker.json, build/version.go, documentation/en/cli-curio.md, documentation/en/cli-lotus-miner.md, documentation/en/cli-lotus-worker.md, documentation/en/cli-lotus.md, documentation/en/cli-sptool.md, go.mod, go.sum
Prepping the second release candidate of v1.27.0
=> build: release: v1.27.0-rc2

api/api_gateway.go, api/proxy_gen.go, build/openrpc/full.json, build/openrpc/gateway.json, build/openrpc/miner.json, build/openrpc/worker.json, gateway/proxy_eth.go
Closes https://github.com/filecoin-project/lotus/issues/11974.
=> feat: Gateway API: Add ETH -> FIL and FIL -> ETH address conversion APIs to the Gateway

go.mod, go.sum
This PR updates `go-jsonrpc` to `v0.3.2` so that JSON-RPC results are conformant with the spec when empty, e.g., `Filecoin.WalletSetDefault`.
https://github.com/filecoin-project/go-jsonrpc/issues/102
=> fix: update go-jsonrpc to v0.3.2

CHANGELOG.md
Just a changelog entry. Coupled with https://github.com/filecoin-project/lotus/pull/11978
=> docs: rpc: document go-jsonrpc behaviour change

build/bootstrap/mainnet.pi
Remove unmaintained bootstrappers 
As noted in this [thread on Slack](https://filecoinproject.slack.com/archives/C039RBG3RPC/p1715255422205499), these three bootstrappers has been confirmed to no longer be maintained.
=> chore: remove unmaintained bootstrappers

cli/spcli/sectors.go
=> fix: curio: handle non existent sector for sector status

curiosrc/web/hapi/simpleinfo_pipeline_porep.go
=> fix: curio: sector 0 on chain status in PoRep Pipeline page in UI

curiosrc/web/hapi/simpleinfo.go
=> fix: curio: UI home page PoRep Pipeline actor string

node/impl/full/eth_events.go, node/impl/full/state.go
=> chore: fix some function names

curiosrc/alertmanager/alerts.go, curiosrc/alertmanager/task_alert.go
=> feat: curio: wdPost and wnPost alerts

blockstore/splitstore/splitstore_prune.go, chain/market/fundmanager_test.go, itests/fevm_test.go, lib/harmony/harmonydb/harmonydb.go, storage/pipeline/numassign.go
=> chore: fix function names

itests/kit/node_unmanaged.go
This fixes a bug in the Manual Onboarding Snapdeals itest where we used to submit Snapdeals messages during immutable deadlines.
See https://github.com/filecoin-project/builtin-actors/blob/6d0725aabbb3ecc35e02cbcd20036901924411e2/actors/miner/src/lib.rs#L3759.
And https://github.com/filecoin-project/lotus/blob/730c96ecafe28cfdffa46c13a64ed98e053fc24f/storage/pipeline/states_replica_update.go#L254
=> fix: manual onbaording itest: do not sumit replica update messages during immutable deadlines 

metrics/metrics.go, node/builder.go
Leftover metrics from https://github.com/filecoin-project/lotus/pull/12005
cc @aarshkshah1992
=> (chore) Remove forgotten graphsync references

build/openrpc/full.json, build/openrpc/gateway.json, build/openrpc/miner.json, build/openrpc/worker.json, build/version.go, documentation/en/cli-lotus-miner.md, documentation/en/cli-lotus-worker.md, documentation/en/cli-lotus.md
#12073 
Bump Lotus Client and Lotus-Miner version in master in preparation for cutting v1.27.1-rc1
=> chore: bump version in master

.github/workflows/release.yml
https://github.com/filecoin-project/lotus/actions/runs/9466679084
Remove the --debug flag
I also pinned the goreleaser version so that we're not surprised by sudden deprecations again
=> fix: ci: do not use deprecated --debug goreleaser flag

build/bootstrap/calibnet.pi, build/bootstrap/mainnet.pi
This PR updates the bootstrap list in the mainnet.pi file to support IPv6 connectivity. Previously, all bootstrap nodes were listed under /dns4, which restricted connections to IPv4 only. By changing the multiaddrs to /dns, we enable libp2p to connect over both IPv4 and IPv6
- Replace `/dns4` with `/dns` in the bootstrap list to support both IPv4 and IPv6 connections.
- ChainSafe has enabled IPv6 on their bootstrap nodes and confirmed connectivity over IPv6. This change ensures that new nodes can connect over IPv6 if available, improving network robustness and connectivity options.
For the Mainnet bootstrap peers:
```
- lotus net connect /dns/node.glif.io/tcp/1235/p2p/12D3KooWBF8cpp65hp2u9LK5mh19x67ftAam84z9LsfaquTDSBpt
connect 12D3KooWBF8cpp65hp2u9LK5mh19x67ftAam84z9LsfaquTDSBpt: success …
```
=> fix: bootstrap: Update list to support both IPv4 and IPv6

node/modules/lp2p/host.go
see https://github.com/ipfs/boxo/pull/621
=> chore: deps: prep for upstream removing ConstructNilRouting()

.goreleaser.yaml, CHANGELOG.md, build/openrpc/full.json, build/openrpc/gateway.json, build/openrpc/miner.json, build/openrpc/worker.json, build/version.go, documentation/en/cli-lotus-miner.md, documentation/en/cli-lotus-worker.md, documentation/en/cli-lotus.md
backport go releaser fix and see if it works
=> build: v1.27.1-rc3

.github/workflows/sorted-pr-checks.yml
n/a
Upgrade the Sorted PR Checks reusable workflow used in lotus.
The v2 of the reusable workflow adds support for posting sorted PR checks comments under PRs from forks. Previously, we didn't have access to those.
=> fix: ci: post sorted pr checks comments under PRs from forks

CHANGELOG.md
I don't think it's worth saying "migration means you can't go back without some manual hacking" since we haven't said that previously I think.
=> doc: events: note events db migration impact

go.sum, itests/migration_test.go
#12102
Its not going to build until the lotus seed stuff is fixed but I tested it out cherrypicked on fix/preseal-cspv and it works
=> Rough draft

build/params_butterfly.go, build/params_interop.go
=> chore: testnet: update genesis network version for dev testnets

build/version.go
Testing https://github.com/filecoin-project/lotus/pull/12096
=> WIP: testing release automation

go.mod, go.sum
Backports https://github.com/filecoin-project/lotus/pull/12166.
=> backport: NV23: Calibnet faucet fix

api/api_full.go, api/docgen/docgen.go, api/mocks/mock_full.go, api/proxy_gen.go, build/openrpc/full.json, build/openrpc/gateway.json, build/openrpc/miner.json, build/openrpc/worker.json, build/params_2k.go, build/params_butterfly.go, build/params_calibnet.go, build/params_interop.go, build/params_mainnet.go, build/params_testground.go, chain/lf3/ec.go, chain/lf3/f3.go, chain/lf3/signer.go, documentation/en/api-v1-unstable-methods.md, go.mod, go.sum, node/builder.go, node/builder_chain.go, node/builder_miner.go, node/impl/full.go, node/impl/full/f3.go, node/modules/lp2p/pubsub.go, node/modules/storageminer.go
Backports https://github.com/filecoin-project/lotus/pull/12119 to v1.28
=> chore: NV23: backport F3 PR

itests/mempool_test.go, node/impl/full/mpool.go, node/impl/full/mpool_test.go
Backports https://github.com/filecoin-project/lotus/pull/12135.
=> chore: NV23: backport delegated address fix 

node/impl/full/eth.go
Slack discussion: https://filecoinproject.slack.com/archives/CP50PPW2X/p1719998253245349
=> fix: rpc: missing re-assignment of baseFee in EthFeeHistory

build/params_testground.go
#12188
Fix renamed `f3Enabled` flag and while at it, add place holder for manifest server ID.
None.
=> fix: f3: Fix F3 build parameters for `testground` target

CHANGELOG.md, build/openrpc/full.json, build/openrpc/gateway.json, build/openrpc/miner.json, build/openrpc/worker.json, build/params_testground.go, build/version.go, documentation/en/cli-lotus-miner.md, documentation/en/cli-lotus-worker.md, documentation/en/cli-lotus.md
Cut v1.28.0-rc4 so we can docker builds out.
Diff with Lotus v1.28.0-rc3: 
- https://github.com/filecoin-project/lotus/pull/12189
=> build: release: v1.28.0-rc4

node/impl/full/chain.go
=> fix: Remove unnecessary error check

CHANGELOG.md, build/openrpc/full.json, build/openrpc/gateway.json, build/openrpc/miner.json, build/openrpc/worker.json, build/version.go, documentation/en/cli-lotus-miner.md, documentation/en/cli-lotus-worker.md, documentation/en/cli-lotus.md
=> build: release: v1.28.0-rc5

blockstore/badger/blockstore.go, chain/beacon/mock.go, cli/util/api.go, cmd/lotus-sim/simulation/node.go, node/builder.go
fix the function names in comments to keep it consistent with the function name.
- [] CI is green
=> chore: all: fix comment

.github/workflows/build-pulse.yml
https://ipdx-workspace.slack.com/archives/C06CY12V83S/p1721259405544859
Use the template expansion properly in the buildpulse workflow.
- [ 
=> fix: ci: fix configuration variables retrieval in buildpulse workflow

api/api_full.go, api/mocks/mock_full.go, api/proxy_gen.go, build/bootstrap/butterflynet.pi, build/openrpc/full.json, build/openrpc/gateway.json, build/openrpc/miner.json, build/openrpc/worker.json, chain/lf3/f3.go, documentation/en/api-v1-unstable-methods.md, node/impl/full/f3.go
add F3GetF3PowerTable to get the f3 power table w/  active f3 participants
=> feat: api: F3GetF3PowerTable

chain/consensus/filcns/upgrades.go
https://github.com/filecoin-project/lotus/pull/12247#discussion_r1680407936
=> chore: ui: add a terminal check

cli/wallet.go, documentation/en/cli-lotus.md
I wanted to make a delegated address with wallet new but cli docs didn't show it as an option so I went looking online.  It turns out it is supported so adding docs.
=> fix:cli:Add delegated to cli docs

blockstore/badger/blockstore.go
Forgotten patch requested by @Stebalien as discussed here: https://filecoinproject.slack.com/archives/CP50PPW2X/p1712157255332899?thread_ts=1712153919.186149&cid=CP50PPW2X
=> [skip changelog] chore: blockstore: proxy Put/Delete to the *Many variants

go.mod, go.sum
Has some minor perf improvements coming from cbor-gen.
=> chore: deps: update hamt to latest

.github/pull_request_template.md, CONTRIBUTING.md, README.md
Closes: #12360
- Expanded `CONTRIBUTING.md` with detailed guidelines that was previously in `README.md`
- Removed the detailed contribution guidelines in `README.md` and instead link to the `CONTRIBUTING.md`
- Update links in `pull_request_template.md`
=> docs: expand `CONTRIBUTING.md` and update `README.md`

api/api_full.go, api/v0api/full.go, build/openrpc/full.json, documentation/en/api-v0-methods.md, documentation/en/api-v1-unstable-methods.md, storage/pipeline/precommit_policy.go, storage/pipeline/states_sealing.go
This pulls in:
https://github.com/filecoin-project/lotus/pull/11348
https://github.com/filecoin-project/lotus/pull/12241
=> [skip changelog] chore: apply couple approved-yet-abandoned PRs:

CHANGELOG.md, itests/api_test.go, node/modules/storageminer.go, storage/pipeline/commit_batch.go, storage/pipeline/mocks/mock_commit_batcher.go, storage/pipeline/pledge.go, storage/pipeline/precommit_batch.go, storage/pipeline/sealing.go, storage/pipeline/states_replica_update.go, storage/pipeline/states_sealing.go
Similar to @rvagg PR: https://github.com/filecoin-project/lotus/pull/12386, but now targeted towards @jennijuju branch here: https://github.com/filecoin-project/lotus/pull/12392
Includes https://github.com/filecoin-project/lotus/pull/12238, https://github.com/filecoin-project/lotus/pull/12244, and the desired https://github.com/filecoin-project/lotus/pull/12341.
=> chore: backport pledge fixes to 1.28.2-prep branch

storage/pipeline/pledge.go
=> [skip changelog] fix: error check

chain/messagepool/messagepool_test.go, go.mod, go.sum
Pulls in https://github.com/filecoin-project/go-crypto/pull/5
=> [skip changelog] chore: deps: update to CGO-free go-crypto

storage/sealer/ffiwrapper/sealer_test.go
On modern darwin `os.ReadDir("/dev/fd")` always results in an error. Because of this storage/sealer/ffiwrapper/sealer_test.go invariably fails.
Instead of fixing the FD enumerator, remove the check entirely, as it has been disabled since https://github.com/filecoin-project/lotus/pull/7420/files
=> [skip changelog] chore: tests: fix failures on recent macos

documentation/misc/RELEASE_ISSUE_TEMPLATE.md
This is accumulating improvements based on lessons learned from executing https://github.com/filecoin-project/lotus/issues/12379 and https://github.com/filecoin-project/lotus/issues/12343
Additional items to fix/address that are part of the release process but not specifically in the release template itself:
=> docs(release): v1.28.2 and v1.29.0 release template improvements

documentation/misc/RELEASE_ISSUE_TEMPLATE.md
missing `.` and I thought I'd add a tiny bit more clarity while I was there
=> fix(doc): minor fix to release docs

itests/kit/ensemble.go, itests/kit/node_miner.go, itests/kit/node_opts.go, lib/harmony/harmonydb/harmonydb.go, node/builder_miner.go, node/config/def_test.go
https://github.com/filecoin-project/lotus/pull/12407
=> chore: itests: cleanup parts forgotten in #12407

.github/workflows/test.yml, chain/actors/builtin/multisig/multisig.go
another go at https://github.com/filecoin-project/lotus/pull/12423
=> chore(ci): maximally portable ffi

CHANGELOG.md, build/openrpc/full.json, build/openrpc/gateway.json, build/openrpc/miner.json, build/openrpc/worker.json, build/version.go, documentation/en/cli-lotus-miner.md, documentation/en/cli-lotus-worker.md, documentation/en/cli-lotus.md, go.mod, go.sum
fix https://github.com/filecoin-project/lotus/issues/12467 for v1.28.x
=> deps: bls: downgrade bls library

CHANGELOG.md, build/openrpc/full.json, build/openrpc/gateway.json, build/openrpc/miner.json, build/openrpc/worker.json, build/version.go, documentation/en/cli-lotus.md, go.mod, go.sum
=> chore: prep v1.29.1

CHANGELOG.md, build/openrpc/full.json, build/openrpc/gateway.json, build/openrpc/miner.json, build/openrpc/worker.json, build/version.go, documentation/en/cli-lotus.md
https://github.com/filecoin-project/lotus/issues/12464
Bump version to v1.29.3-dev
=> chore: bump version to v1.29.3-dev

SECURITY.md
=> chore: update Security.md

CHANGELOG.md, build/openrpc/full.json, build/openrpc/gateway.json, build/openrpc/miner.json, build/openrpc/worker.json, build/version.go, documentation/en/cli-lotus.md
#12464
Prep for shipping v1.29.2-rc1
=> build: release Lotus node v1.29.2-rc1

CHANGELOG.md, cmd/lotus-miner/init_restore.go, cmd/lotus-shed/sectors.go, cmd/lotus/backup.go, cmd/lotus/daemon.go, go.mod, go.sum
Closes #12433
Updated the version for Cheggaaa's pb from `v1` to `v3`.
=> feat(PB): update Cheggaaa's version

CHANGELOG.md
=> chore: docs: Update CHANGELOG.md

documentation/misc/RELEASE_ISSUE_TEMPLATE.md
Closes: https://github.com/filecoin-project/lotus/issues/12464
Adds some release issue templates from running through the template with the v1.29.2 release.
=> docs(release): v1.29.2 release template improvements

CHANGELOG.md, build/openrpc/full.json, build/openrpc/gateway.json, build/openrpc/miner.json, build/openrpc/worker.json, build/version.go, documentation/en/cli-lotus-miner.md, documentation/en/cli-lotus-worker.md, documentation/en/cli-lotus.md
Prepping the first release candidate for v1.30.0
=> build: release Lotus node and miner v1.30.0-rc1

itests/f3_test.go
=> fix(f3): use the correct context in tests

CHANGELOG.md, build/openrpc/full.json, build/openrpc/gateway.json, build/openrpc/miner.json, build/openrpc/worker.json, build/version.go, documentation/en/cli-lotus-miner.md, documentation/en/cli-lotus-worker.md, documentation/en/cli-lotus.md
Update Node and Miner version to v1.30.1-dev in master
=> build: update Node and Miner version to v1.30.1-dev in master

itests/kit/log.go
=> chore: reduce verbosity of F3 logs during itest

CHANGELOG.md, build/openrpc/full.json, build/openrpc/gateway.json, build/openrpc/miner.json, build/openrpc/worker.json, build/version.go, documentation/en/cli-lotus-miner.md, documentation/en/cli-lotus-worker.md, documentation/en/cli-lotus.md
Bump version to v1.30.0-rc2 and prep the changelog for v1.30.0-rc2.
=> build: release Lotus node and miner v1.30.0-rc2

cli/spcli/sectors.go
Came up on [Slack](https://filecoinproject.slack.com/archives/CPFTWMY7N/p1729054724496389) and this info message was too unhelpful to not just jump in and make better.
=> chore(spcli): improve sectors extend sector skipping info logging

documentation/en/chain-indexer-overview-for-operators.md
Worked through what it would look like to do this regularly. Assumes: 
* https://github.com/filecoin-project/lotus/pull/12609
* https://github.com/filecoin-project/lotus/pull/12611
=> chore(doc): "regular checks" section for chainindexer docs

cli/f3.go
Correctly construct the manifest template when displaying the manifest.
=> fix(f3): correctly construct the manifest template

cmd/lotus-shed/f3.go, cmd/lotus-shed/main.go
=> feat(f3): lotus shed command to delete all f3 state

CHANGELOG.md, chain/lf3/config.go
As for https://github.com/filecoin-project/go-f3/issues/716
Resolves https://github.com/filecoin-project/go-f3/issues/716
=> feat(f3): change F3 HeadLookback to 4

CHANGELOG.md, build/openrpc/full.json, build/openrpc/gateway.json, build/openrpc/miner.json, build/openrpc/worker.json, build/version.go, documentation/en/cli-lotus-miner.md, documentation/en/cli-lotus-worker.md, documentation/en/cli-lotus.md
Bump version to v1.30.0-rc3 and prep the changelog.
=> build: release Lotus node|miner v1.30.0-rc3

build/buildconstants/params_mainnet.go
See message in the [fil-implementers](https://filecoinproject.slack.com/archives/C05P37R9KQD/p1730882866939809?thread_ts=1730128669.893169&cid=C05P37R9KQD) channel.
Change `F3BootstrapEpoch to -1`
=> chore: change F3BootstrapEpoch to -1

go.mod, go.sum
Upgrade to the latest go-f3 in prep for lotus release.
=> chore: upgrade to go-f3 `v0.7.2`

cmd/lotus/main.go
just a test, 🤞 merging should hopefully fix up the docsgen-cli changes
=> test: bogus cli change for testing purposes

CHANGELOG.md
chore(release): cherry-pick v1.30.0 changelog back to master
=> chore(release): cherry-pick v1.30.0 changelog back to master

cli/index.go, documentation/en/chain-indexer-overview-for-operators.md, documentation/en/cli-lotus.md
Closes #12654
Update references for `lotus-shed chainindex` to `lotus index`
=> docs: update references for lotus-shed chainindex to lotus index

CHANGELOG.md, build/openrpc/full.json, build/openrpc/gateway.json, build/openrpc/miner.json, build/openrpc/worker.json, build/version.go, documentation/en/cli-lotus-miner.md, documentation/en/cli-lotus-worker.md, documentation/en/cli-lotus.md
https://github.com/filecoin-project/lotus/issues/12344
- Update Lotus Node & Miner version to v1.31.1-dev in master
- Update changlog
=> build: update Lotus Node & Miner version to v1.31.1-dev in master

storage/sealer/storiface/index.go
=> chore: fix struct name in comment

documentation/en/chain-indexer-overview-for-operators.md
Ref: https://github.com/filecoin-project/lotus/issues/12654
Just noticed a couple more references that needed dealing with.
=> docs: replace more references to lotus-shed with lotus in ChainIndexer docs

api/api_storage.go, build/openrpc/miner.json, documentation/en/api-v0-methods-miner.md
=> chore: fix function name

CHANGELOG.md, chain/events/filter/event.go, chain/events/filter/event_test.go, node/modules/actorevent.go
https://github.com/filecoin-project/lotus/issues/12344
Backports #12603 to the `release/v1.31.0` branch
=> chore: backport #12603 to `release/v1.31.0` branch

CHANGELOG.md, documentation/en/cli-lotus.md
https://github.com/filecoin-project/lotus/issues/12344
Cherry-pick v1.31.0 changelog back to master branch.
=> chore(release): cherry-pick v1.31.0 changelog back to master

api/docgen/docgen.go, build/openrpc/full.json, documentation/en/api-v1-unstable-methods.md, go.mod, go.sum
* https://github.com/filecoin-project/go-f3/issues/773
Upgrade to go-f3 `v0.7.3`
=> chore: upgrade to go-f3 `v0.7.3`

CHANGELOG.md, build/openrpc/full.json, build/openrpc/gateway.json, build/openrpc/miner.json, build/openrpc/worker.json, build/version.go, documentation/en/cli-lotus-miner.md, documentation/en/cli-lotus-worker.md, documentation/en/cli-lotus.md
https://github.com/filecoin-project/lotus/issues/12750
Release v1.32.0-rc1
=> build: release Lotus Node and Miner v1.32.0-rc1

.github/workflows/create-release-issue.yml, cmd/release/main.go
#12821
This PR fixes how arguments are passed between the create issue workflow and the underlying Go tool. 
=> ci(release): fix the create release issue workflow

Makefile
https://github.com/filecoin-project/lotus/pull/12812 undid a change that we made in https://github.com/filecoin-project/lotus/pull/12717, this commit restores it
=> fix(make): restore docsgen-cli target

chain/index/events.go, chain/index/events_test.go
I accidentally merged #12808 because it was marked as auto-merge, but it had review items which I was ticking off as I resolved them. This PR is the resolution of those review items so should have been in that PR.
=> fix(eth): minor improvements to event range checking

cli/wallet.go
=> fix(wallet): allow delegated wallet import

.github/workflows/check.yml, Makefile
Sick of looking up the command manually... Also good to be able to tell contributors about this, e.g. https://github.com/filecoin-project/lotus/pull/12883
I started looking at upgrading the version, but there's dragons in there that are best left for another PR.
=> feat(build): add `make lint` target

documentation/en/architecture/mpool.md
=> docs(mpool): fix typos in documentation

CHANGELOG.md, api/types.go, build/openrpc/full.json, build/openrpc/gateway.json, documentation/en/api-v0-methods.md, documentation/en/api-v1-unstable-methods.md, node/impl/full/state.go
Closes #12872
Add `GenesisTimestamp` to NetworkParams
Testing on a node running with this change:
```
curl -X POST -H "Content-Type: application/json" --data '{"method":"Filecoin.StateGetNetworkParams", "params":[], "id":1,"jsonrpc":"2.0"}' http://localhost:34421/rpc/v0
{"id":1,"jsonrpc":"2.0","result":{"NetworkName":"mainnet","BlockDelaySecs":30,"ConsensusMinerMinPower":"10995116277760","PreCommitChallengeDelay":150,"ForkUpgradeParams":{"UpgradeSmokeHeight":51000,"UpgradeBreezeHeight":41280,"UpgradeIgnitionHeight":94000,"UpgradeLiftoffHeight":148888,"UpgradeAssemblyHeight":138720,"UpgradeRefuelHeight":130800,"UpgradeTapeHeight":140760,"UpgradeKumquatHeight":170000,"BreezeGasTampingDuration":120,"UpgradeCalicoHeight":265200,"UpgradePersianHeight":272400,"UpgradeOrangeHeight":336458,"Upgrad …
```
=> feat: add `GenesisTimestamp` to NetworkParams

chain/lf3/manifest.go
Resolves: https://github.com/filecoin-project/go-f3/issues/916
=> fix: f3: use F3InitialPowerTableCID in contract provided manifests

chain/index/indexer.go
See the test failure in #12942.
Avoid a deadlock when closing the indexer.
We can't hold the write lock while waiting on close because `isClosed` was taking the read lock (and called while closing).
Instead, I just got rid of the locks entirely. Now, we just check the context. Really, I'm not sure why we even have such an "is closed" check. I _think_ what we actually want is to lock to prevent closing until we've finished all atomic operations, but that's a larger change and I don't have enough understanding of this code to easily make that change.
=> fix(index): avoid deadlock on close

itests/fevm_test.go
make function comment match function name
=> chore: make function comment match function name

CHANGELOG.md, build/openrpc/full.json, build/openrpc/gateway.json, build/openrpc/miner.json, build/openrpc/worker.json, build/version.go, documentation/en/cli-lotus-miner.md, documentation/en/cli-lotus-worker.md, documentation/en/cli-lotus.md
#12750
- Update version string + make gen && make docsgen-cli
- Update changelog
=> build: release Lotus Node and Miner v1.32.0

chain/actors/policy/policy.go, chain/actors/policy/policy.go.template
=> refactor: use the built-in max/min to simplify the code

CHANGELOG.md, build/buildconstants/params_mainnet.go
https://github.com/filecoin-project/FIPs/blob/master/FRCs/frc-0099.md#implementation
=> feat: set F3 activation contract address as specified in the FRC

CHANGELOG.md, build/buildconstants/params_mainnet.go
https://github.com/filecoin-project/FIPs/blob/master/FRCs/frc-0099.md#implementation
=> feat: set F3 activation contract address as specified in the FRC (#12994)

CHANGELOG.md, build/openrpc/full.json, build/openrpc/gateway.json, build/openrpc/miner.json, build/openrpc/worker.json, build/version.go, documentation/en/cli-lotus-miner.md, documentation/en/cli-lotus-worker.md, documentation/en/cli-lotus.md
Publish the Lotus v1.32.1 patch release which correctly sets the F3 activation contract address.
=> build: release Lotus Node and Miner v1.32.1

build/openrpc/full.json, build/openrpc/gateway.json, build/openrpc/miner.json, build/openrpc/worker.json, build/version.go, documentation/en/cli-lotus-miner.md, documentation/en/cli-lotus-worker.md, documentation/en/cli-lotus.md
=> chore: bump version to v1.32.2-dev

LOTUS_RELEASE_FLOW.md, cmd/release/main.go, documentation/misc/RELEASE_ISSUE_TEMPLATE.md
Accumulate release template improvements from shipping the v1.32.0 release: https://github.com/filecoin-project/lotus/issues/12750
=> docs(release): v1.32.0 release template improvements

CHANGELOG.md, build/openrpc/full.json, build/openrpc/gateway.json, build/openrpc/miner.json, build/openrpc/worker.json, build/version.go, documentation/en/cli-lotus-miner.md, documentation/en/cli-lotus-worker.md, documentation/en/cli-lotus.md
build: release Lotus Node and Miner v1.32.2 
=> build: release Lotus Node and Miner v1.32.2 

cmd/lotus-shed/migrations.go
Some special strings will be able to run non-numbered migrations, starting with "tock-fix"
Calibnet build & repo:
```
$ lotus-shed migrate-state tock-fix bafy2bzacechhidnu456zy67y53nbe7skhy2qvels2w7tgscv5uqzuqpwfs6za
REMINDER: If you are running this, you likely want to ALSO run the continuity testing tool!
2025-04-05T20:40:28.437+1100    INFO    bundle  bundle/bundle.go:60     manifest cid: bafy2bzacecqtwq6hjhj2zy5gwjp76a4tpcg2lt7dps5ycenvynk2ijqqyo65e
migration height  2549600
old cid  bafy2bzacec3pu6oh4fbqnjkifqjt6nssgdto2mdo6bcd5gy5ftdsstfrj2bsw
new cid  bafy2bzaced24uwbgfgixq2n3s2tcpysjtz75k5onku2w44krznj6qccnpruai
completed round actual (without cache), took  2m10.989943604s
skipping pre-migration, no pre-migration function
```
=> feat(shed): migrate-state tock-fix

CHANGELOG.md, build/openrpc/full.json, build/openrpc/gateway.json, build/openrpc/miner.json, build/openrpc/worker.json, build/version.go, documentation/en/cli-lotus-miner.md, documentation/en/cli-lotus-worker.md, documentation/en/cli-lotus.md
Post release steps for v1.32.2: cherry-pick v1.32.2 changelog back to master
=> chore(release): cherry-pick v1.32.2 changelog back to master

cli/f3.go, documentation/en/cli-lotus.md
Adding a usage description to the `lotus f3 powertable` command.
=> docs(cli): add usage description for f3 powertable command

build/openrpc/v2/full.json, documentation/en/api-v2-unstable-methods.md
Fix doc generation inconsistency on master caused by CI workflow queueing issue.
=> chore: fix generated docs on `master`

itests/f3_test.go
=> chore: fix wrong comment

cmd/lotus-sim/simulation/stages/windowpost_stage.go
=> chore: fix function name in comment

metrics/README.md, metrics/grafana/F3Dashboard.json
Closes: #12500
Adding a F3 Grafana Dashboard Template, and updating the documentation. It consists of these panels / metrics.
- The Validation section/metric is only applicable/shown if a SP is connected to the node. The title has been updated to make that clearer [here](https://github.com/filecoin-project/lotus/pull/12934/commits/321030d34c4916311822f43b70afaace48211c6f).
=> feat: add F3 Grafana Dashboard Template

cmd/lotus-fountain/site/index.html
Closes #13053 
1. Added language attribute to HTML tag
2. Updated the page title to be more descriptive
3. Added a meta description for SEO
4. Added charset declaration
=> chore(fountain): improve SEO and accessibility metadata

CHANGELOG.md, build/buildconstants/params_mainnet.go
* feat(f3): set initial power table for mainnet
Backport of #13077
=> feat(f3): set initial power table for mainnet (#13077)

CHANGELOG.md, build/openrpc/full.json, build/openrpc/gateway.json, build/openrpc/miner.json, build/openrpc/v2/full.json, build/openrpc/v2/gateway.json, build/openrpc/worker.json, build/version.go, documentation/en/cli-lotus-miner.md, documentation/en/cli-lotus-worker.md, documentation/en/cli-lotus.md
https://github.com/filecoin-project/lotus/issues/13004
- update Lotus Node and Miner version to v1.33.1-dev in master
- update Changelog
=> build: update Lotus Node and Miner version to v1.33.1-dev in master

cmd/lotus-fountain/site/datacap.html, cmd/lotus-fountain/site/faucet-components.css, cmd/lotus-fountain/site/funds.html
https://github.com/filecoin-project/lotus/issues/13004
- Backports https://github.com/filecoin-project/lotus/pull/13108 to the release/v1.33.0 branch, as https://github.com/filecoin-project/lotus/pull/13056 is in that release train
=> build: backport changes for Node v1.33.0

CHANGELOG.md
chore(release): cherry-pick v1.33.0 changelog back to master
=> chore(release): cherry-pick v1.33.0 changelog back to master

cmd/lotus-fountain/site/index.html, cmd/lotus-fountain/site/main.css
* Added a new footer section with resource links for the Filecoin ecosystem, other testnet faucets, and development resources to improve user accessibility.
* Updated CSS to style the new footer layout, including a responsive grid for resource cards and list resets for better presentation.
* Ensured the footer is visually appealing and maintains a consistent design with the rest of the site.
This update enhances the user experience by providing quick access to important resources and improving the overall layout of the footer.
=> feat: enhance footer with resource links and improve styling

documentation/en/architecture/architecture.md
After investigating the way bitswap is used in Lotus with the help of @ZenGround0, this is the summary of what we _think_ is going on based on what we see. But I'd like to have other eyes on this to confirm it's correct.
I'm also going to follow up with some additional instrumentation because I'd like to see how much bitswap is actually used in practice.
=> chore(docs): update architecture doc with pubsub & bitswap details

go.mod, go.sum
=> chore: bump go-f3 to v0.8.9

CHANGELOG.md
https://github.com/filecoin-project/lotus/issues/13132
- Cherry-pick v1.33.1 changelog back to master
- Update unreleased section in changelog
=> chore(release): cherry-pick v1.33.1 changelog back to master

cmd/lotus-fountain/site/index.html
Fix the incorrect link address
=> chore: fix the incorrect link address

storage/sealer/ffiwrapper/sealer_cgo.go
base on #13267
Fix breakages coming because of the bump FFI to v1.34.0-dev.
=> chore: fix breakages

chain/sync.go, cmd/lotus-sim/simulation/stages/windowpost_stage.go, itests/eth_account_abstraction_test.go
=> chore(docs): fix minor typos

cmd/lotus-fountain/main.go
=> fix: open site/send_success.html: no such file or directory error

documentation/en/actor-events-api.md
=> chore: fix 404 URL

api/docgen-openrpc/openrpc.go, api/docgen/docgen.go, chain/vm/invoker.go, cli/worker/worker.go, cmd/lotus-shed/state-stats.go
=> refactor: using reflect.TypeFor

blockstore/badger/blockstore.go, blockstore/splitstore/markset_badger.go
=> chore: fix some typos in comment
