chain/consensus/filcns/filecoin.go, chain/messagepool/check.go, chain/messagepool/messagepool.go, chain/messagepool/selection.go, chain/vm/fvm.go, chain/vm/gas.go, chain/vm/mkactor.go, chain/vm/vm.go, conformance/runner.go
This reverts commit 25b2e144b8f60ac4152e0958c39714174b17972d.
While the commit was useful for getting the LegacyVM to interoperate with FVM-based networks (caterpillarnet), it causes issues with syncing our existing non-FVM-based testnets (butterflynet and calibrationnet). The improvement is no longer needed, since v16 switches to the FVM at which point we will not have epoch-based pricelists anymore.
=> Revert "VM: Refactor pricelist to be based on network versions"

node/modules/lp2p/rcmgr.go, node/repo/fsrepo.go, node/repo/interface.go, node/repo/memrepo.go
opt-in with envvar for other nodes, as there are still some issues with markets related protocols
=> feat: only enable rcmgr by default in full nodes

cli/chain.go
This fiexes issue #8771 (https://github.com/filecoin-project/lotus/issues/8771)
https://github.com/filecoin-project/lotus/issues/8771
If after calling the constructor the returned bytes length is not null, the command line will show a base64 of the returned bytes.
=> feat:Client: CLI Display returned value from actor constructor

go.mod, go.sum
Full changelog at https://github.com/libp2p/go-libp2p-pubsub/releases/tag/v0.7.0
Most pertinent for lotus is the fix in https://github.com/libp2p/go-libp2p-pubsub/pull/483 which is a pathology that has appeared in lotus logs (the respawning rewriter loop pathology).
Needs backport to the nv16 branch for v1.16.0.
=> deps: update go-libp2p-pubsub to v0.7.0

cmd/lotus-bench/simple.go
Changing `/tmp/sl` and `/tmp/cac` to `/tmp/sealed` and `/tmp/cache` for consistency with the rest of the description
=> fix: bench: consistency in description

chain/vm/runtime.go
I don't think the rename will break any setups, but if that's a concern, we can add it as an alias.
=> chore: vm: Rename tracing envvar to LOTUS_VM_ENABLE_TRACING

cli/net.go, cmd/lotus-shed/hello.go, cmd/lotus-shed/main.go
https://github.com/filecoin-project/lotus/issues/8711
=> feat: lotus-shed get remote peer hello message

go.mod, go.sum
This is a _patch_ release, fixing a bug in yamux that resulted in too much memory released in rcmgr and the "BUG: too much memory released" log.
*Should be ported to feat/nv16 as well*
=> deps: update go-libp2p@v0.19.4

chain/vm/fvm.go
Change exec trace subcalls to be nil instead of empty array to preserve backwards compatibility.
=> Fix: state:  Set exec trace subcalls to nil when appropriate

cli/paych.go
Prints an "waiting for confirmation.." when running `lotus paych [fromAddress toAddress amount]` to indicate that the command is waiting for the msg to be confirmed and not just hanging.
Resolves #4138
Add a "waiting for confirmation.." print to improve the UX a tiny bit.
=> fix: paych: Print "waiting for confirmation.."

paychmgr/manager.go, paychmgr/mock_test.go, paychmgr/paychget_test.go, paychmgr/simple.go
as following state diagram shows:
```mermaid
stateDiagram-v2
state "pm.store.WithPendingAddFunds"  as queryMsgFromStore
Test: TestPaychGetRestartAfterAddFundsMsg
state "_, mcid2, err := : mgr.GetPaych(ctx, from, to, amt2)"as GetPaych
waitForAddFundsMsg:channelAccessor.waitForAddFundsMsg
state "mockPaychAPI.WaitMsg(mcid2..." as WaitMsg
state "receipt := <- response " as waitReceiptResponse
concurrency: concurrency operations
state  "mgr2, err := newManager(...)" as Mgr2
state "done := make(chan struct{})
pchapi.waitingResponses[mcid] = &waitingResponse{receipt: receipt, done: done}
pchapi.lk.Unlock()
<-done
" as WaitCode
Test --> GetPaych
GetPaych --> channelAccessor.GetPaych
channelAccessor.GetPaych --> channelAccessor.addFunds: this is started by mgr1, in another go-routine …
```
=> Fix: PaychGetRestartAfterAddFundsMsg may stuck in forever waiting

cli/client_retr.go
During a launchpad session we tried to create a retrieval request and got an error because we didn't set the `maxPrice` option and it defaulted to 0. 
The error message was a bit confusing and we thought it would be helpful if the error would provide an action – especially when the user doesn't know that it was set to 0 by default.
- Improve error message
- `area`: _api_, _chain_, _state_, _vm_, _data transfer_, _market_, _mempool_, _message_, _block production_, _multisig_, _networking_, _paychan_, …
=> chore: improve error message when maxPrice is too low

chain/vm/vmi.go
Users have been failing to sync testnets using the FVM for v15 and earlier, which is not supported. It’s fine for mainnet v15, and obviously does nothing after v16, because everything uses FVM anyway.
We still want to be syncing mainnet using the FVM for our own testing purposes, so I propose renaming the variable.
=> refactor: rename LOTUS_USE_FVM_EXPERIMENTAL

build/params_2k.go
Starting from v16 (having GenesisNetworkVersion=v16) and having the upgrade set is broken.
disable the Skyr upgrade
=> fix: build: params_2k should not have the v16 upgrade set

go.mod, go.sum, testplans/lotus-soup/go.mod, testplans/lotus-soup/go.sum
This bump of go-address enforces a standard for trailing bits, to avoid confusion like  f1xpbyy4tkdx5si2bgo37dubc2xwv6fum5tk57mid and f1xpbyy4tkdx5si2bgo37dubc2xwv6fum5tk57mia "actually" being the same address. See https://github.com/filecoin-project/go-address/issues/22 for more.
=> chore: deps: Update to go-address v1.0.0

extern/sector-storage/manager_test.go, extern/storage-sealing/commit_batch.go, extern/storage-sealing/commit_batch_test.go, go.sum, testplans/lotus-soup/go.sum
CI failure is because FFI artefacts aren't up yet, should be good soon.
=> Add new proofs version type

build/params_2k.go
This fixes gen check on master after merging https://github.com/filecoin-project/lotus/pull/8855 and https://github.com/filecoin-project/lotus/pull/8859 at the same time
=> chore: fix imports conflict

cmd/lotus-shed/main.go
Report the "user version" in `lotus-shed`. This version includes the network name and commit, for easier debugging.
=> feat: shed: report the "user version"

go.mod, go.sum
This PR is intended to bring the latest version of go-fil-markets into the v1.17 release of lotus.
We need to wait until there is a v1.17 RC available to test against.
TODO:
=> feat: update go-fil-markets to v1.21.0

cli/client.go
Checks if the address used in `lotus client deal` is "initialized" on-chain before running the `uiLoop`.
Resolves #8817
Adds a check to see if the actor (address in this case) is on chain before starting the `lotus client deal` - interactiveDeal uiLoop
=> fix: ux: Check for client deal addrs on-chain

Makefile
cc @walkerlj0
Closes #8812 
The `uninstall` make target deletes all the binaries and directories mentioned here: https://github.com/filecoin-project/lotus/issues/5416#issuecomment-770111683
Run `sudo make uninstall` to uninstall lotus from your computer. You can then remove the entire `lotus` directory.
I have this error when running it:
```
bash: line 1: go: command not found
expr: syntax error: unexpected argument ‘1016000’
```
I don't know why - but I already get the _same_ error when running `sudo make install`.
Also not sure if the `deps` area makes sense. Didn't find one related to chore.
I still need to update documentations in `lotus-docs` repo.
- [x ] All commits have a clear commit message.
- example: ` fix: …
=> build: deps: add uninstall make target

chain/vm/fvm.go
@jennijuju pointed out that the top-level message in the FVM exectrace deviates from the LegacyVM -- it uses resolved (ID) addresses, and excludes some of the information packaged in the message receipt.
Match LegacyVM behaviour by setting the top-level message & rct from the receipt itself, not the exectrace.
=> fix: fvm: make exectraces match legacyVM some more

cli/client.go
Closes https://github.com/filecoin-project/lotus/issues/7674
The deal making cli was using mainnet parameters for block time, disallowing any deals shorter than 180 days, but for a devnet with a block time of 4s this is over the maximum lifetime of a deal. This led to the cli not being able to make deals for devnets.
=> Make cli deal command get Block Delay specific to build

cmd/lotus-shed/cid.go
@jennijuju wanted this to double-check the actual code cids (not just the manifest cid).
=> feat: shed: print out actor code CIDs in manifest cid checker

cli/client_retr.go
Miner can send a `Cancelled` message if they are unable to unseal data. There is currently no return value for this case, so the client will hang. Client will now exit if they receive a `Cancelled` message.
=> Fix: cli: Break out of retrieval if provider cancels

README.md
find the link is fault, modify https://docs.filecoin.io/get-started/lotus to https://lotus.filecoin.io
=> fix: readme: Update install instructions link

.circleci/config.yml, AppImageBuilder.yml
https://filecoinproject.slack.com/archives/CP50PPW2X/p1656368533715659?thread_ts=1656365814.692489&cid=CP50PPW2X
This removes lines in the Appimage.yaml file that was causing appimage not to correctly build.
=> fix appimage build

cmd/lotus-miner/proving.go, documentation/en/cli-lotus-miner.md
Make the `lotus-miner proving deadline [num]` command not print 1000s of numbers by default.
=> feat: cli: Hide sector nums in 'proving deadline' by default

tools/stats/points/collect.go
#8973
Used the builtin actor code lookup function
=> fix: lotus-stats: actor code string

go.mod, go.sum, node/impl/client/client.go, node/impl/client/client_test.go
=> deps: update go-fil-markets to v1.23.0

documentation/en/default-lotus-miner-config.toml, node/config/doc_gen.go, node/config/types.go, storage/wdpost/wdpost_run.go, storage/wdpost/wdpost_run_test.go, storage/wdpost/wdpost_sched.go
Some users see windowPoSt messages exceed block gas limit.
Add a new config value which allows limiting the number of partitions per deadline to values lower that the network limit
```toml
[Proving]
#
#MaxPartitionsPerMessage = 0
```
I don't have good data to suggest safe values, but this gas use in a few random messages which landed recently on mainnet:
[1 partition with 1.1B limit](https://filfox.info/en/message/bafy2bzaceajr2wjixilw2ercbiqf2o2g5dkrqkyj6242wvttosokzcoh2vaco)
[2 partitions with 2.1B limit](https://filfox.info/en/message/bafy2bzacednavdl47lxytx74cx3ktbdj4wp4njjbwul6nrnfraghmqy4ute7e)
[2 partitions with 2.9B limit](https://filfox.info/en/message/bafy2bzaceazfmisc3rit5jauovh33qbhl2betxtqkzwy4lgn3xnitncm4anze)
[2 partitions with 4.1B …
=> feat: wdpost: Config for maximum partition count per message

documentation/en/default-lotus-miner-config.toml, node/builder_miner.go, node/config/doc_gen.go, node/config/types.go, node/modules/storageminer.go, storage/wdpost_run.go, storage/wdpost_run_test.go, storage/wdpost_sched.go
These are the PRs wanted in the patch release of 1.16.1
=> Backports: 8986, 8982

go.mod, go.sum, node/modules/lp2p/libp2p.go, node/modules/lp2p/transport.go
1. This pulls in a multistream fix that should fix that fixes a few tests (and probably a few actual bugs).
2. This deduplicates dependencies that have been merged into the monorepo.
fixes https://github.com/filecoin-project/lotus/issues/8953
=> chore: update and fix libp2p

README.md
Probably it was a copy-paste from Debian-based system, fixed it to reflect the actual Fedora package name.
=> Docs: readme: use proper hwloc dependency for Fedora

go.mod, go.sum
None
Upgrade to the latest `go-car` to roll out a fix to the minimum index
width, where it could cause a validation error when CAR data payload
contains identity CIDs with empty data.
`go-fil-markets` is also upgraded to the latest.
Follow up from: https://github.com/filecoin-project/lotus/pull/8976#issuecomment-1177457300
=> chore: market: Upgrade to `go-car` `2.4.1`

markets/dagstore/wrapper.go, markets/dagstore/wrapper_test.go
https://github.com/filecoin-project/lotus/issues/9009
Add a new function DestroyShard in markets/dagstore/wrapper.go
=> feat: dagstore: Add DestroyShard() in dagstore wrapper

build/bootstrap/mainnet.pi
we have lost the peer private key.
change to 12D3KooWRzCVDwHUkgdK7eRgnoXbjDAELhxPErjHzbRLguSV1aRt.
=> change 1475 bootstrap peer

.circleci/config.yml, chain/stmgr/call.go, itests/deals_retry_deal_no_funds_test.go, itests/gas_estimation_test.go, node/impl/full/gas.go, node/impl/full/mpool.go
https://github.com/filecoin-project/lotus/issues/8697
Estimate gas with a zero base-fee. Otherwise, an account will need funds to estimate the max possible gas a message could take (which is usually the block gas limit).
This does mean gas estimation no longer checks if the sending account has enough funds to cover the message cost, but MpoolPush will now do this. Furthermore, subsystems like the window post worker will carefully pick an account with funds to cover the message. Previously, the fact that gas estimation would fail up-front caused this code to be less useful.
- `PR type`: _fix_, _feat_, _INTERFACE BREAKING CHANGE_, _CONSENSUS BREAKING_, _build_, …
=> fix: gas: estimate gas with a zero base-fee

.circleci/config.yml, itests/api_test.go, itests/kit/ensemble.go, itests/net_test.go
-
This PR adds network integration tests specifically from node net and conngater files.
It has annotations that system test matrix uses (//stm comments) 
-
=> test: net: net and conngater tests

chain/consensus/filcns/compute_state.go, chain/stmgr/call.go, chain/stmgr/execute.go, chain/stmgr/stmgr.go, chain/stmgr/utils.go, chain/vm/fvm.go, chain/vm/runtime.go, chain/vm/vm.go, chain/vm/vmi.go, conformance/driver.go, itests/multisig_test.go
Closes #8926 
- If `LOTUS_VM_ENABLE_TRACING` is set to 1, the FVM always produces execution traces.
- If `LOTUS_VM_ENABLE_TRACING` is not set to 1, the FVM produces execution traces on calls from `StateCompute`, `StateReplay`, and `StateCall`. It does not do so during regular execution.
=> feat: FVM: always enable tracing for user-triggered executions

chain/vm/fvm.go
We never want these to run out of gas.
So use the biggest possible number.
=> FVM: Use MaxInt64 for Implicit Message gas limits

storage/pipeline/checks.go
This is a fix to the sealing checks for what seems to be a compiler bug affecting ARM processors. Follow https://filecoinproject.slack.com/archives/C03F5LF3LLU/p1657814113161839 for details
=> fix: sealing: Workaround for sealing bug

chain/vm/fvm.go, chain/vm/vm.go, chain/vm/vmi.go
#9050 
The stat counters that things like the CLI's "validated X messages" was missing for the FVM. This PR moves the counters themselves to the VM interface, and mutates them in the FVM as appropriate.
Note: We do NOT mutate them in the Dual execution VM / Debug VM, because the Dual Exec VM calls into the FVM::ApplyMessage(), which mutates the counter. This avoids double / triple counting.
Thanks @rjan90 for the nudge!
- `area`: _api_, _chain_, _state_, _vm_, _data transfer_, _market_, _mempool_, …
=> fix: FVM: record message applied metrics

storage/pipeline/checks.go
Backports https://github.com/filecoin-project/lotus/pull/9043
=> Fix: sealing: hacky sealing fix backport

.circleci/config.yml, .circleci/template.yml, scripts/build-appimage-bundle.sh, scripts/build-arch-bundle, scripts/publish-arch-release.sh
https://app.circleci.com/pipelines/github/filecoin-project/lotus/21961/workflows/3bb820f2-4f7a-43d9-880f-7fe4dfecdc72/jobs/513420
Snap builds were previously failing due to an authentication issue. I think it was likely caused by outdated credentials, but snapcraft has also changed their auth method to use an env variable recently and deprecated the old value. So I set that new env var in CircleCI project settings, meaning we should be able to remove this section of CI where we write the old auth file.
I also tweaked the jobs for snapcraft and dockerhub to do trial-runs on all release branches, but still only publish on release tags. While it wouldn't have caught this issue, since it was publish related, I think it's still good practice to add this as a small sanity check.
=> _ci_: update snapcraft and release flow logic

itests/deals_pricing_test.go
This test failed flakily [here](https://app.circleci.com/pipelines/github/filecoin-project/lotus/22311/workflows/6c730f91-23cb-4123-8ffd-16ba2abce120/jobs/533522).
The underlying issue is that the (only) miner on the network was busy sealing a sector, and so missed its PoSt. That led to it being slashed, which halts the network since the power is 0. The test eventually times out.
The bad news is that this issue affects many tests. The good news is that @ZenGround0 already has a fix, which is the `BeginMiningMustPost` method. We just need to use this method!
- `PR type`: _fix_, _feat_, _INTERFACE BREAKING CHANGE_, _CONSENSUS BREAKING_, _build_, _chore_, _ci_, …
=> fix: test: deflake TestQuotePriceForUnsealedRetrieval

.circleci/config.yml, .circleci/template.yml
Even after merging my previous PR, snapcraft publish failed again on the 1.17.0-rc4 release with ```ZeroDivisionError: integer division or modulo by zero```.
1. We shouldn't be publishing to `stable` on RC tags, so instead publish to the `candidate` channel for RC releases.
2. When I ssh in the CircleCI build environment and run the exact same publish command, it works. So the only thing I can think might be the cause is the *.snap isn't matching the built file for some reason. So add extra verbose logging to the snap deploy job to figure out why it keeps erroring. 
- `PR type`: _fix_, _feat_, _INTERFACE BREAKING CHANGE_, _CONSENSUS BREAKING_, _build_, …
=> _ci_: More tweaks to snapcraft release process

.circleci/config.yml, .circleci/template.yml, .gitignore, .goreleaser.yaml, scripts/generate-checksums.sh, scripts/publish-checksums.sh
This is a much needed change that creates a universal MacOS binary, including support for M1 based macs. We also automatically update the homebrew package repo to use the new universal binary.
I also used this opportunity to refactor the workflow slightly so we can test out `goreleaser`, a yaml based tool for building, packaging, and releasing go binaries on multiple platforms. It supports building binaries for to most of the platforms we care about, including Linux and  MacOS, and also supports publishing those binaries automatically as releases in Github, Homebrew, Snap, and Apt.
If this trial goes well, I think we should eventually replace the entire release workflow with `goreleaser`. For now, this test is more tightly scoped to only change the MacOS release process, since that is the …
=> _ci_: Use goreleaser to build macos universal binaries (including M1 macs)

storage/wdpost/wdpost_run_faults.go
I don't think #9106 is quite right.
=> fix: sector counter for recovery

chain/types/message.go, storage/wdpost/wdpost_run_faults.go
=> chore: backport: #9106

chain/types/message.go, storage/wdpost/wdpost_run_faults.go
https://github.com/filecoin-project/lotus/issues/9103
This PR adds a new envvar - `LOTUS_RECOVERING_SECTOR_LIMIT=123` which will limit the number of sectors declared in the recover message.
=> feat: wdpost: Envvar for limiting recovering sectors

itests/wdpost_config_test.go, storage/wdpost/wdpost_run_faults.go
#9106 only enforced the limit when examining a new partition for recoveries -- if the number of faults in a single partition was greater than the limit (the case we're interested in), it would just add all the faults anyway.
Enforce the limit strictly -- we should never go over the limit now, and instead will trim a recovery bitfield for only those sectors that can still fit.
Please review this PR carefully, its impact is high!
- `area`: _api_, _chain_, _state_, _vm_, _data transfer_, _market_, _mempool_, …
=> fix: post: restrict recoveries per deadline

cmd/lotus-miner/proving.go, documentation/en/cli-lotus-miner.md
Merges https://github.com/filecoin-project/lotus/pull/8721
This is https://github.com/filecoin-project/lotus/pull/8721 with some more changes on top, mostly more detailed partition stats in the `proving deadlines` command to aid with debugging issues like https://github.com/filecoin-project/lotus/issues/9103
Example `proving deadlines` output:
```
Deadline Index:           1
Partitions:               1
Proven Partitions:        0
Current:                  false
Partition Index:          0
All Sectors:               2183 (bitfield - runs 77+77=154 - 2718 0s 2183 1s - 0 inv - 108 B 108B)
Live Sectors:              2157 (bitfield - runs 56+56=112 - 2744 0s 2157 1s - 0 inv - 83 B 83B)
Active Sectors:            2157 (bitfield - runs 56+56=112 - 2744 0s 2157 1s - 0 inv - 83 B 83B)
Faulty …
```
=> feat: miner cli: proving deadline command enchantments

cmd/lotus-miner/proving.go
=> feat: add proving deadline option view live sectors information

.circleci/config.yml, .circleci/template.yml
We recently got the access required from Canonical to publish to the Snap package store as `lotus` instead of `filecoin-lotus`. This one line change updates the snapcraft config to use the new package name.
=> _ci_: Publish to both `lotus` and `lotus-filecoin` for snap

cmd/lotus-worker/main.go, documentation/en/cli-lotus-worker.md, documentation/en/default-lotus-miner-config.toml, itests/kit/ensemble.go, itests/kit/node_opts.go, itests/worker_test.go, node/config/doc_gen.go, node/config/storage.go, node/config/types.go, storage/sealer/manager.go, storage/sealer/worker_local.go
This PR expands https://github.com/filecoin-project/lotus/pull/7937 a bit
* Add a new config field to lotus-miner - `Storage.LocalWorkerName`
* Add a new flag/envvar to lotus-worker - `--name`/`LOTUS_WORKER_NAME`
* When set, use that name instead of the worker hostname in places where worker names are visible
=> feat: sealing: Allow overriding worker hostname

.goreleaser.yaml
I tried out goreleaser manually on the 1.17.0 release, and it appended a huge changelog that included duplicates of what was already there. This changes goreleaser so it will leave the existing release notes as-is if it finds them.
=> _ci_: Switches goreleaser notes back to default (keep-existing)

.circleci/config.yml, .circleci/template.yml
The builds were erroring only in CircleCI, when run manually the same
command worked fine. I reached out to CircleCI support, and got the
following message:
> The reason you are seeing this error when running in CircleCI and not while debugging with SSH is due to the -e set in #!/bin/bash -eo pipefail at the beginning of the shell while the debugging shell would just be #!/bin/bash. The -e sets to exit to the shell when any non zero [0] exit code status.
>
> Since you say the command works when debugging with SSH you can set the shell to use /bin/bash -o pipefail using a default shell options. Here is an example:
>
>       - run:
>          name: <<command name>>
>          shell: /bin/bash -o pipefail
>          command: |
>            << some commands>>
>
> Notice that I still added -o …
=> _ci_ : Change default shell options for snapcraft publish

Makefile
lotus-fountain's building command should use `$(GOCC)` instead of raw `go` command.
=> fix: build: use GOCC when building lotus-fountain

cmd/lotus-miner/actor.go
fix, if a miner's owner is a multisig,
command `./lotus-miner actor control list` get failed.
=> fix: cli: `./lotus-miner actor control list`, if the `owner` is not account

documentation/en/api-v0-methods.md, documentation/en/api-v1-unstable-methods.md
There is description error in documentation about method StateReplay
fix description error in below files:
api-v0-methods.md
api-v1-unstable-methods.md
=> fix: documentation: fix description error in documentation about method StateReplay

blockstore/splitstore/splitstore.go, blockstore/splitstore/splitstore_compact.go, blockstore/splitstore/splitstore_prune.go, documentation/en/default-lotus-config.toml, itests/kit/ensemble.go, itests/kit/node_opts.go, itests/splitstore_test.go, node/config/def.go, node/config/doc_gen.go, node/config/types.go, node/modules/blockstore.go
Auto prune of coldstore
1) Add logic to trigger chain prune on head events
2) Add config options to support this
=> feat:chain:splitstore auto prune

.circleci/config.yml, .circleci/template.yml
This fixes a typo in my snapcraft config that causes it to fail after publishing the first snap but before building the second:
https://app.circleci.com/pipelines/github/filecoin-project/lotus/22519/workflows/7727083f-3fdf-45da-bb2d-ca2c7ff30d37/jobs/549504
While fixing it, I also tweaked it so we can run the two snap jobs in parallel. We still need to publish under both the new `lotus` snap name and the legacy `lotus-filecoin` snap name until all our users have migrated to the `lotus` one.
- `area`: _api_, …
=> _ci_: Run snap builds for lotus and lotus-filecoin in parallel

storage/pipeline/commit_batch.go
When a sector is added to a commit batcher, and it's precommit info isn't on chain (expired or somehow was never there), lotus-miner will panic with
```
[signal SIGSEGV: segmentation violation code=0x1 addr=0x70 pc=0x1a39e61]
goroutine 171115825 [running]:
github.com/filecoin-project/lotus/storage/pipeline.(*CommitBatcher).getCommitCutoff(_, {{0x3e1b4a5, 0x15}, 0x137c, 0x8, 0x62f0729>
/home/magik6k/github.com/filecoin-project/go-lotus/storage/pipeline/commit_batch.go:587 +0x3a1
github.com/filecoin-project/lotus/storage/pipeline.(*CommitBatcher).AddCommit(_, {_, _}, {{0x3e1b4a5, 0x15}, 0x137c, 0x8, 0x62f07>
/home/magik6k/github.com/filecoin-project/go-lotus/storage/pipeline/commit_batch.go:478 +0x98 …
```
=> fix: storage: don't panic in getCommitCutoff when precommit is not found

cmd/lotus-miner/actor.go
Resolves #9154 
Prints the message receipt when withdrawing from the miner-actor. Also highlights that the command is waiting for the message to be included in  a block.
=> fix: ux: msg receipt for actor withdrawal

.circleci/config.yml, .circleci/template.yml
https://github.com/filecoin-project/lotus/pull/9164
Updates the xcode version in our build files so that releases can build properly.
Already backported to v1.17.1
=> Update xcode version for macos builds

cmd/lotus-miner/sectors.go, documentation/en/cli-lotus-miner.md
Useful when extending available sectors for snapdeals
=> feat: sectors renew --only-cc

cmd/lotus-miner/info.go
=> fix: ux: exclude negative available balance from spendable amount

cli/client.go
Resolves #9188
Adds an additional line that outputs bytes in the `lotus client commP` cmd to make it easier to add the `--manual-piece-size` in an offline-deal.
=> fix: ux: Output bytes in `lotus client commP` cmd

storage/sealer/mock/mock.go
Fixes #9205 
Lock acquisition is missing here.
=> fix: mock sealer: grab lock in ReadPiece

snap/snapcraft.yaml, tools/packer/setup-snap.sh
Right now, we automatically start the lotus daemon when someone installs lotus via snapcraft, which in turn automatically starts downloading state snapshots. This changes the workflow so that the lotus daemon snap service is still installed, but is disabled by default in order to allow users who only need a lite node to avoid this resource intensive process.
This should not affect users who already have the snap installed, only users who install the snap fresh.
- `area`: _api_, _chain_, _state_, _vm_, _data …
=> _ci_ / _build_ : Snap daemon autorun disable

cli/client_retr.go
Should address some gateway test flakiness like https://app.circleci.com/pipelines/github/filecoin-project/lotus/22805/workflows/2907bba9-2f9b-420b-9309-1078350bb9bb/jobs/564691
```
--- FAIL: TestGatewayCLIDealFlow (5.40s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1a941e2]
goroutine 25183 [running]:
testing.tRunner.func1.2({0x3a279a0, 0x5eebe00})
/usr/local/go/src/testing/testing.go:1389 +0x24e
testing.tRunner.func1()
/usr/local/go/src/testing/testing.go:1392 +0x39f
panic({0x3a279a0, 0x5eebe00})
/usr/local/go/src/runtime/panic.go:838 +0x207
github.com/filecoin-project/lotus/cli.glob..func41(0xc0024542c0) …
```
=> cli: Don't panic with no providers in client retrieve

cli/send.go
Print a more understandable error message when signing a transaction is being rejected on ledger.
resolves #5335
Prints out a more understandable error message.
```
./lotus send --from=t1ybav9myh3cb6ltslejecasegosgnggcx6ld2nwi t3qcixsxivj5ygpqhi2ima526btslwexuzwl2urlto4wweszdkb4cs6bq65bwcsw7uvfpvmhxbn4norpne6zza 0.01
ERROR: transaction rejected on ledger: publishing message: failed to sign message: [APDU_CODE_COMMAND_NOT_ALLOWED] Command not allowed (no current EF)
```
- `area`: _api_, _chain_, _state_, …
=> fix: ux: better ledger rejection error

cli/cmd.go, cli/info.go, documentation/en/cli-lotus.md
Implements most of the metrics listed in #5766.
Add a `lotus info`  command that prints info about the lotus node:
```
Network: butterflynet
Chain: [sync ok] [basefee 100 aFIL] [epoch 194446]
Peers to: [publish messages 13] [publish blocks 13]
Chain health: 68% [unhealthy]
Default address: 
t1p34z3ex72fa3v7h7thkwl6n3ggqzgne3sz5ls3y [22.869 FIL]
Wallet: 12 addresses
Total balance: 748.537 FIL
Market locked: 166.638 μFIL
Market available: 1.5 FIL
Payment Channels: 2 channels
Deals: 6, 762 MiB
StorageDealActive: 5 deals, 635 MiB
StorageDealSealing: 1 deals, 127 MiB
Bandwidth:
TotalIn  TotalOut  RateIn  RateOut
4.9 MB   4.2 MB    0 B/s   0 B/s
```
- `PR type`: …
=> feat: cli: lotus info cmd

cmd/lotus-miner/info.go
Call SyncBasefeeCheck from `lotus info` to not duplicate logic. Also switches to V1 api.
Follow up of https://github.com/filecoin-project/lotus/pull/9233#discussion_r958461092
=> fix: miner: Call SyncBasefeeCheck from `lotus info`

go.mod, go.sum
This removes some deprecated packages from the build tree.
=> chore: update bitswap and some libp2p packages

.github/ISSUE_TEMPLATE/bug_report.yml, CHANGELOG.md, README.md, docker-compose.yaml, documentation/en/README.md, documentation/en/about.md, documentation/en/default-lotus-miner-config.toml, node/config/doc_gen.go, node/config/types.go, snap/snapcraft.yaml, tools/dockers/docker-examples/README.md, tools/packer/etc/motd
https://github.com/filecoin-project/lotus/pull/8729
This PR updates all dead links within the Lotus repository -  `docs.filecoin.io` to `lotus.filecoin.io`
Replaces https://github.com/filecoin-project/lotus/pull/8729 & https://github.com/filecoin-project/lotus/pull/8966
=> chore: Fix dead links to docs.filecoin.io

cmd/lotus-shed/sectors.go
Closes https://github.com/filecoin-project/lotus/issues/8664
Adds a flag to allow either owner address or worker address to send terminate sectors message.
=> feat: cli: Add option to terminate sectors from worker address

.circleci/config.yml, itests/mpool_msg_uuid_test.go, node/impl/full/mpool.go
https://github.com/filecoin-project/lotus/issues/9299
Enhances the existing uuid to check to also check for non nil spec but with MsgUuid not set
=> fix: api: Ignore uuid check for messages with uuid not set

node/config/cfgdocgen/gen.go, node/config/doc_gen.go, node/config/doc_util.go
This was an accidental rename caused by an overzealous IDE refactor in #9267
Revert the reanem.
Thank you @magik6k for the catch
=> fix: docsgen: revert rename of API Name to Num

cmd/lotus-miner/actor.go, cmd/lotus-shed/miner-multisig.go, documentation/en/cli-lotus-miner.md
Closes https://github.com/filecoin-project/lotus/issues/9254 and https://github.com/filecoin-project/lotus/issues/9253
=> feat: api/cli: change beneficiary propose and confirm for actors and multisigs.

cli/state.go, cmd/lotus-miner/info.go
=> feat: cli: print beneficiary info in state miner-info

cli/state.go, documentation/en/cli-lotus.md
closes https://github.com/filecoin-project/lotus/issues/9320
Cli command not uses current network version instead of "newest", which causes problems around network upgrades.
=> fix: cli: actor-cids cli command now defaults to current network

cmd/lotus-miner/storage.go
=> feat: miner: display updated & update-cache for storage list

cmd/lotus-miner/actor.go, cmd/lotus-shed/actor.go
Tuning down slice to only 6 characters to avoid panics if the multisig-actor is of a really low character length.
fixes #9239 
```
lotus-miner actor control list
name    ID      key        use    balance                   
owner   t01044  t01044...         2 FIL                     
worker  t01041  t3wxxc...  other  7.999999626974119012 FIL  
```
- `area`: _api_, _chain_, _state_, _vm_, _data transfer_, _market_, _mempool_, _message_, _block production_, _multisig_, _networking_, _paychan_, _proving_, …
=> fix: cli: fix panic in `lotus-miner actor control list`

storage/pipeline/cbor_gen.go, storage/pipeline/fsm_events.go, storage/pipeline/states_failed.go, storage/pipeline/types.go
?
Remove `PreCommitInfo` (which is changing in actors v9) from `pipeline.SectorInfo`. All places which use PreCommitInfo in the sealing pipeline get that from the chain with `StateSectorPreCommitInfo`
This caused `decoding state for key '/872': unmarshaling t.PreCommitInfo pointer: cbor input had wrong number of fields` on startup on existing miners
=> fix: sealing: Drop unused PreCommitInfo from pipeline.SectorInfo

chain/events/events_called.go, markets/storageadapter/ondealsectorcommitted.go, markets/storageadapter/ondealsectorcommitted_test.go
I was investigating an issue for the Boost team, and the absence of this info was making it hard.
Mostly just makes error messages more descriptive, and chained.
=> feat: add descriptive errors to markets event handler

documentation/en/default-lotus-miner-config.toml, node/config/doc_gen.go, node/config/types.go, node/modules/storageminer.go, storage/pipeline/input.go, storage/pipeline/sealiface/config.go, storage/pipeline/states_replica_update.go, storage/pipeline/states_sealing.go
Fixes #8686 (will need some testing)
* Auto-abort upgrading sectors which didn't get any deals assigned
* In calcTargetExpiration, don't pick the lowest possible deal duration as minExpiration when there isn't an entire sector worth of deals in the input queue - use the expiration from lowest-expiration deal in the queue (note that in this case the _target_ expiration will be max deal duration, so we'll still try to find sectors with longer expiration in that case; but in case there are no better upgradable sectors we could pick one with way too low expiration to be useful)
* Add 2 config fields to configure minimums for minimumExpiration and targetExpiration
When testing it will be really useful to see debug logs from the `sectors` subsystem - `lotus-miner log set-level --system sectors …
=> fix: sealing: Abort upgrades in sectors with no deals

storage/sealer/ffiwrapper/sealer_cgo.go, storage/sealer/ffiwrapper/sealer_test.go
Closes https://github.com/filecoin-project/lotus/issues/9263
Might fix https://github.com/filecoin-project/lotus/issues/9327
Close readers in AddPiece
- [x[ The PR title is in the form of of `<PR type>: <area>: <change being made>`
=> fix: ffiwrapper: Close readers in AddPiece

build/params_calibnet.go, build/params_mainnet.go
- add an env var for setting propagation delay
- increasing the default delay from 6 to 10 sec (base on https://github.com/filecoin-project/lotus/discussions/8891 the computation is faster and should be safe to wait longer for parent blocks)
@filecoin-project/lotus-tse should test the new default out 
=> feat: env: propagation delay

README.md
Update Go-badge in readme to reflect that go-version 1.18.1 or higher is needed.
=> fix: docs: update Go-badge in readme

chain/actors/builtin/registry.go, chain/actors/builtin/registry.go.template, chain/consensus/filcns/compute_state.go, chain/stmgr/forks_test.go, chain/vm/invoker.go, chain/vm/invoker_test.go, conformance/driver.go, go.mod, go.sum
This PR integrates https://github.com/filecoin-project/go-state-types/pull/77 into lotus.
=> chore: actors: Allow builtin-actors to return a map of methods

api/docgen/docgen.go, build/params_shared_vals.go, chain/messagepool/messagepool.go, chain/messagepool/messagepool_test.go, chain/messagepool/provider.go, chain/state/statetree_test.go, cmd/lotus-bench/main.go, cmd/lotus-seed/genesis.go, itests/kit/ensemble_opts.go, paychmgr/mock_test.go, storage/pipeline/precommit_policy_test.go, storage/wdpost/wdpost_run_test.go
This field has always been terrible (see TODO above it), and is potentially confusing to users (see https://github.com/filecoin-project/lotus/pull/9319#issuecomment-1248182478).
Remove its only usage in source code, which is in the messagepool -- just query for the NetworkVersion when needed. If we have concerns that this is slow, we could just set it once at startup, and use that -- it is very rare for this to matter (hasn't mattered since nv7).
Rename remaining usages to TestNetworkVersion.
- `area`: …
=> feat: refactor: remove NewestNetworkVersion

node/impl/client/client.go
Someone opened a PR with this fix [here](https://github.com/filecoin-project/lotus/pull/9219). They were unresponsive to the code change so just filing it here.
Total price includes unseal price, so when unseal price is non-zero this calculation for price-per-byte will be wrong.
=> fix: retrievals: price-per-byte calculation fix

build/builtin_actors_test.go, chain/actors/actor_cids.go, chain/actors/agen/main.go, chain/actors/builtin/datacap/actor.go.template, chain/actors/builtin/datacap/datacap.go, chain/actors/builtin/datacap/state.go.template, chain/actors/builtin/datacap/v9.go, chain/actors/manifest.go, chain/consensus/filcns/upgrades.go, chain/vm/fvm.go, go.mod, go.sum, itests/lite_migration_test.go
Integrates https://github.com/filecoin-project/go-state-types/pull/70 into lotus. Add new datacap actor and also versions the list of actor names based on actors version
=> feat: actors: Integrate datacap actor into lotus

itests/deadlines_test.go
Fixes #7809
Okay, here's the flaky failure that motivated this: https://app.circleci.com/pipelines/github/filecoin-project/lotus/23151/workflows/058fcc2a-e606-4407-93f6-5050b6b8ab32/jobs/587417.
A miner has just terminated all their sectors. We expect them to have power 0, but still have Cron active -- cron should deactivated upon the next deadline close. The test asserts that cron should be active (true) unless the tipset that executes the TerminateSectors message (one after the tipset that includes the message) is exactly equal to a deadline.Open, in which case the test asserts that cron should be inactive.
BUT, if the TerminateSectors message is included at height X, and the deadline opens at height X+1, BUT X+1 was null, then this doesn't work! The tipset that executed the …
=> fix: test: flaky TestDeadlineToggling around nulls

build/params_calibnet.go, build/params_mainnet.go
The global field wasn't actually being set (just a local variable).
Set the field correctly.
=> fix: build: set PropagationDelaySecs correctly

itests/deadlines_test.go
#7809
See #9354 for background. It isn't worth trying to perfect this around cron, let's just simplify the test.
=> fix: test: simplify TestDeadlineToggling

cmd/lotus-shed/main.go, cmd/lotus-shed/msig.go
=> shed: util: get all msig

cmd/lotus-miner/init.go, documentation/en/cli-lotus-miner.md
Fixes #9359 
We had per-network defaults before, but that got removed in #9267. That's fine, but let's default to a mainnet-friendly size. 
We could also have a DefaultMinerInit build var that we set differently across the networks, but I'd rather not.
=> fix: miner: init miner's with 32GiB sectors by default

itests/deals_retry_deal_no_funds_test.go, markets/storageadapter/dealpublisher.go
TestDealsRetryLackOfFunds fails flakily (see eg here https://app.circleci.com/pipelines/github/filecoin-project/lotus/23264/workflows/87a70d59-974d-46d8-971a-54e1bba3afd3/jobs/595498)
This test sets up a SP with insufficient $$ to publish a deal (with the expectation, but not an assertion that the first try will fail), then after 3 seconds funds the publish key and triggers MarketRetryPublishDeal, and waits for the deal to succeed.
The cause of the flakiness is that the funding of the publish key and triggering MarketRetryPublishDeal can happen at a few different points wrt the first attempt to publish the deal (which involves adding to the publisher, waiting a second, and then validating and pushing to mempool). 
There seem to be a few different things at play here:
- 3 seconds doesn't …
=> feat: dealpublisher: check for duplicate deals before adding

.circleci/config.yml, .circleci/template.yml
https://github.com/filecoin-project/homebrew-lotus/issues/16
No longer updates the homebrew tap for RC builds, only for stable releases.
=> _ci_: Don't publish new homebrew releases for RC builds

.circleci/config.yml, .circleci/template.yml
Updating golang to 1.18.1 broke the AppImage build: https://app.circleci.com/pipelines/github/filecoin-project/lotus/23339/workflows/0d8285e1-5977-4b8e-aa25-45d55ac61ac3/jobs/600644
It seems we were relying on an implicitly installed go version in the underlying ubuntu-2004 machine image. This should be backported to the 1.17.2 release branch , or else it will not include an AppImage release artifact.
This explicitly downloads and installs a specific golang version (in this case, 1.18.1) onto the machine image before running the app image builder. This should allow us to easily update the version in the future, and will hopefully make it clear when upgrading the go version that the app image builder needs to be updated too.
- …
=> _ci_: Use golang 1.18.1 to build appimage

documentation/misc/RELEASE_ISSUE_TEMPLATE.md
Updates the release_issue_template with some improvements:
- Changed some wrong links (links pointed to version.go in IPFS-repo)
- Removed `Create a discussion for this release`
- Removed "Prep the changelog using `scripts/mkreleaselog`, and add it to `CHANGELOG.md`" since this already has been captured in the first pre-release/release-candiadte step. Left that you should make sure that the CHANGELOG is up to date.
- Changed the `Cut the release`-link to be `prerelease=false` in the Stable Release step.
- …
=> chore: release: Update `release_issue_template`

node/builder_miner.go, node/modules/storageminer.go
On lotus-miner nodes with disabled local PoSt / C2 / PR2 no snarks are ever computed, which means that we don't need .param files for anything. This makes node startup much faster, reducing downtime by a lot when restarts are needed.
=> feat: miner paramfetch: Don't fetch param files when not needed

cmd/lotus-miner/sectors.go
During testing of the v1.17.2-rc1/2 [it was uncovered](https://github.com/filecoin-project/lotus/discussions/9349#discussioncomment-3768518) that the --only-cc option does not apply when specifying sectors with a sector-file.
Add the ability to extend/renew only CC-sectors with the `--only-cc` when using a sector-file.
=> fix: cli: renew --only-cc with sectorfile

documentation/en/default-lotus-miner-config.toml, node/config/doc_gen.go, node/config/types.go, storage/wdpost/wdpost_run.go, storage/wdpost/wdpost_run_test.go, storage/wdpost/wdpost_sched.go
https://github.com/filecoin-project/lotus/issues/9041
Add a user config which allows partitions with recovery sectors to be the only partition in a PoST message. This helps in keeping the message gas limit lower for messages with recovery sectors which can exceed the default network limit and resulting in PoST failures
=> feat: wdpost: Add ability to only have single partition per msg for partitions with recovery sectors

cmd/lotus-shed/migrations.go
Adds a check to the `lotus-shed` `migrate-nv17` command.
=> Check datacaps for v8 verifreg match v9 datacap actor

cli/wallet.go
Adding command outputs to `lotus wallet set-default` and `lotus wallet delete`
=> fix: ux: Add outputs to wallet commands

cli/net.go, documentation/en/cli-lotus-miner.md, documentation/en/cli-lotus.md
Specify that you need to ping the `peerMultiaddrs` with the `lotus net ping` and `lotus-miner net ping` commands.
=> fix: ux: specify arg in `net ping` cmd

api/v0api/full.go, api/v0api/proxy_gen.go, documentation/en/api-v0-methods.md, genesis/types.go
=> fix: missing permissions tag

blockstore/mem.go, blockstore/mem_test.go
Initially fixed in https://github.com/filecoin-project/lotus/pull/9382, pulling this out into a smaller PR with a test
=> fix: bstore: Handle codecs correctly in membstore Get

build/bootstrap/butterflynet.pi
Updates artifacts for Butterfly network. Network was reset to the following commit https://github.com/filecoin-project/lotus/tree/e838a86df9a5d945a9181c0ae1f5383b72590cc2
=> chore: update butterfly artifacts

go.mod, go.sum
See discussion here https://filecoinproject.slack.com/archives/CP50PPW2X/p1663707244492419
This undoes 2 untested commits from go-fil-markets that were not needed for the upgrade.
=> Deps: Update go-fil-markets to 1.24.0-v17

chain/actors/builtin/verifreg/util.go, itests/verifreg_test.go
New datacap actor uses actorID keys instead of ID addresses. This was erroneously duplicated in verifreg actor which has no change to HAMT keys.
=> fix: actors: fix verifreg checking notary balance

go.mod, go.sum
=> deps: backport: #9455

chain/consensus/filcns/upgrades.go
Removes splash banner from nv17 which was accidentally copied from nv16.
=> fix: upgrade: no splash banner for nv17 :(

cmd/lotus-shed/fip-0036.go, cmd/lotus-shed/main.go, cmd/lotus-shed/msig.go
This is a shed command that tabulates the results of FIP-0036. It is fed in votes from FilPoll, along with the state root and height (for this poll bafy2bzacebdnzh43hw66bmvguk65wiwr5ssaejlq44fpdei2ysfh3eefpdlqs and 2162760). See #9375 for more, this is a slight reworking of that.
`lotus-shed fip36poll results --repo=/mnt/oldnet bafy2bzacebdnzh43hw66bmvguk65wiwr5ssaejlq44fpdei2ysfh3eefpdlqs 2162760 ~/Downloads/votes.json`
Sample output:
```
Total acceptance token:  3641447073483215769868470
Total rejection token:  4546494321191196771637925
Total acceptance SP deal power:  20666424631525888
Total rejection SP deal power:  141508413655663360
Total acceptance SP rb power:  3486069098389962752
Total rejection SP rb power:  2454514779633483776
Total acceptance Client rb power: …
```
=> feat: shed: FIP0036 post poll result processing 

chain/actors/builtin/miner/state.go.template, chain/actors/builtin/miner/v9.go, cmd/lotus-shed/migrations.go, itests/pending_deal_allocation_test.go
Implements part of https://github.com/filecoin-project/lotus/issues/9246
Tests the following invariants for the v17 migration:
- that for each pending, verified deal in v8 market, there is a corresponding allocation in v9 verifreg Allocations
- that nextAllocationID is equal to the number of pending, verified deals in v8 market
- that for each pending, verified deal in v8 market, there is a corresponding entry in v9 market PendingDealAllocationIds
- that all miners that have PreCommits with deals in them have non-nil UnsealedCid, and this CID is correctly calculated:
- `PR type`: _fix_, _feat_, _INTERFACE BREAKING CHANGE_, _CONSENSUS BREAKING_, _build_, …
=> test: Add invariance checks to v17 migration test

cli/filplus.go, documentation/en/cli-lotus.md
Closes https://github.com/filecoin-project/lotus/issues/9272
This should get some testing from TSEs before merging.
=> feat: cli: Add commands for listing allocations and removing expired allocations

storage/sealer/sched_post.go
Should help with https://github.com/filecoin-project/lotus/issues/8362
On master the PoSt worker scheduler would check worker session at some interval, but the way the logic is implemented, it only sleeps if the check has failed. This results it a flood of requests between lotus-miner<->lotus-worker, which may lead to exhausting resources needed to make those http requests, leading to all sorts of random RPC-related issues.
=> fix: post worker sched: Don't check worker session in a busy loop

api/eth_types.go
Specifically, check if we have the expected prefix and return a sane error.
=> fix(api): eth/id address conversion

blockstore/autobatch.go, chain/consensus/filcns/upgrades.go
The migration is taking significantly longer on machines with 64 GiB RAM or less. 
Use the autobatch blockstore that we created in https://github.com/filecoin-project/lotus/pull/7933 for this purpose.
Also includes a bugfix from @Kubuxu to the autobatch bs itself.
=> Migration: Use autobatch bs

chain/actors/builtin/registry.go, chain/actors/builtin/registry.go.template, chain/stmgr/utils.go, chain/vm/invoker.go, chain/vm/invoker_test.go, cli/chain.go, cli/chain_test.go, cli/multisig.go, cli/state.go, cmd/lotus-shed/msg.go, cmd/lotus-wallet/interactive.go, cmd/tvx/extract_many.go, go.mod, go.sum
This resolves a UX degredation in #9267 where the method name became unavailable.
Update to go-state-types v0.9.2.
Set the registry's method's names with this info.
=> feat: Invoker: Use MethodMeta from go-state-types

chain/consensus/filcns/upgrades.go, cmd/lotus-shed/diff.go, cmd/lotus-shed/migrations.go
More work towards optimizing the migration
We move the first premigration back to be 2 hours before the upgrade.
- Motivation: This is the part we _really_ care about. We do not want any users entering the upgrade without at least one premigration, if possible.
We add a second premigration 7.5 minutes before the upgrade.
- Motivation: This covers any state that's changed since the first premigration, and seems to give a 20% speed up to the actual migration time. If this doesn't complete on time, it isn't important.
This PR also adds more functionality to the lotus-shed tools around migrations and state diffs.
- `PR type`: fix, feat, build, chore, ci, docs, …
=> feat: state: add a second premigration for nv17

api/eth_transactions.go, api/eth_transactions_test.go, api/eth_types.go, cli/chain.go, go.mod, go.sum, node/impl/full/eth.go
This fixes several issues with Ethereum tx encoding:
- Encode/decode tx params as CBOR (matching a similar change in the EVM).
- Fix a bunch of issues with decoding contract deployment params/returns.
=> Eth TX Encoding

api/eth_transactions.go, api/eth_types.go, api/eth_types_test.go, node/impl/full/eth.go
Previously, we'd use embedded ID addresses.
=> feat: use f4 eth addresses wherever possible

tools/packer/setup-snap.sh
I've been debugging issues with the packer builds for a bit, and this is the next PR in that line. The digital ocean build was previously failing because it couldn't get an apt-get lock, I think because of some ubuntu auto-update functionality. 
This has the packer build wait for 3 seconds and then try to get the lock again.
=> _ci_: Have apt-get wait until it can get a lock in packer builds

api/eth_transactions.go, api/eth_types.go, go.mod, go.sum, lib/sigs/delegated/init.go, node/impl/full/eth.go
Fixes https://github.com/filecoin-project/ref-fvm/issues/983
Interprets addresses as Eth delegated addresses when the ID mask doesn't match.
TODO depends on release of go-address.
=> Eth JSON-RPC API: support f4 addresses.

go.mod, go.sum
update go-state-types to v0.9.7 to includes changes to invariant checks
=> chore: deps: update go-state-types to v0.9.7

Makefile
Many people have complained that building devnets is slow.
Drop the external wallet, the gateway, stats, and fountain (faucet) from always being built when building devnets.
=> Makefile: Drop rarely used binaries from build-devnets

cmd/lotus-shed/migrations.go
Towards #9246
You can now run, eg., `lotus-shed migrate-nv17 --check-invariants bafy2bzacedbxlti4ol2ipyd7nqhl5x6242xl4lt6twibwtnqmyt3ivfbub3y6`, which will invoke the full suite of invariant checks (see [here](https://github.com/filecoin-project/go-state-types/pull/100)).
Note that the checks will likely take 2-3 hours to complete, and there are currently some minor invariant failures in the power actor (inherited from v8).
=> shed: include invariant checks as part of migration testing

cli/chain.go
We now deploy with Create when deploying from an f4 account, and Create2 for f1/f3. We can revisit this later if we change how the actors work, but this fixes the CLI.
=> fix: allow deploying from f1/f3 accounts

chain/vm/invoker.go
We need to add full FEVM state support, but that will require merging
master. This is enough for now.
fixes https://github.com/filecoin-project/ref-fvm/issues/1022
=> fix: avoid returning an error when getting embryo state

.circleci/config.yml, itests/migration_nv17_test.go
#9524, #9246 
Covers all the cases in #9524 , and a few more
=> test: nv17 migration

.goreleaser.yaml
We don't need these homebrew deps now that we install a prebuilt binary rather than building from source.
Additionally, the bzr package was disabled.
=> _ci_ Remove unneeded homebrew deps

.circleci/config.yml, chain/stmgr/call.go, itests/remove_verifreg_datacap_test.go
Tests the fix implemented [here](https://github.com/filecoin-project/builtin-actors/pull/784). Verifreg notaries should not be able to remove datacap from the verifreg actor, because the verifreg's datacap balance should always equal the datacap of all pending allocations.
=> test: verifreg: Test notaries cannot remove datacap from verifreg

chain/stmgr/call.go
@simlecode pointed out that the change in https://github.com/filecoin-project/lotus/pull/9557 does not properly bubble up some errors because ret can be nil.
Bubbles up real errors but allows us to return the call information when the call itself errors.
=> fix: stmgr: bubble up errors properly from ApplyImplicitMessage

build/params_calibnet.go
Change calibnet upgrade schedule. We will quickly upgrade up to nv16. The nv17 upgrade will be one week later, on Tuesday November 8.
=> chore: calibnet: update calibnet upgrade heights

cmd/lotus-shed/invariants.go, cmd/lotus-shed/main.go, cmd/lotus-shed/migrations.go
Adds an offline test to lotus shed for state invariants mirroring those in `builtin-actors`. The main purpose is to test the migration before we release it.
=> feat: shed: Add invariance tests for v9

chain/vm/fvm.go
We could set an envar for FVM debug bundles for V8, but no other version. It is now extensible to all versions.
=> fix: fvm: Allow setting local bundles for Debug FVM for av 9+

cli/chain.go, documentation/en/cli-lotus.md
`lotus chain prune` does not execute
Added `ChainPruneCmd` to file
=> fix: chain: Update chain.go

cmd/lotus-shed/export-car.go
Make lotus-shed export-car work on online nodes
```
$ ./lotus state get-actor f05
Address:        f05
Balance:        134827.875759811187127269 FIL
Nonce:          0
Code:           bafk2bzacediohrxkp2fbsl4yj4jlupjdkgsiwqb4zuezvinhdo2j5hrxco62q (fil/8/storagemarket)
Head:           bafy2bzacecqryedsccndhepiovpm7somjzblvwbb5gdeq2wqy6tbi52yhyejg
$ ./lotus-shed export-car actor.car bafy2bzacecqryedsccndhepiovpm7somjzblvwbb5gdeq2wqy6tbi52yhyejg
done 1.907 GiB
```
=> feat: shed: Online export-car

chain/vm/fvm.go
Backports https://github.com/filecoin-project/lotus/pull/9509
=> backport: fix: Allow setting local bundles for Debug FVM for AV9+

cmd/lotus-shed/actor.go
Helps (but does NOT close) #9563
Right now, the Filecoin protocol only allows the owner address to set control addresses. Changing this requires a FIP & network upgrade.
Since some owner keys are maintained by folks that don't run Lotus nodes, it might be useful to share the raw bytes of such messages with them, for them to sign offline, and return to someone capable of pushing the signed message to the network. This is imperfect for a few reasons:
- the entity that has the owner key should confirm the bytes are in fact the message they intend to send
- the gas estimation is performed at the time this command is run, and may be poor estimation for the time when the message is sent out
- the worker really should be able to do this.
Before you mark the PR ready for review, please make sure …
=> shed: set control address: add dump bytes option

api/eth_types.go
`EthNonce` needs to have an `UnmarshalJSON` method, otherwise deserializing json will report an error:
```
unmarshaling result: json: cannot unmarshal string into Go struct field EthBlock.nonce of type api.EthNonce
```
=> fix:add UnmarshalJSON for EthNonce

node/impl/full/eth.go
fix a potential panic when querying block info
=> api: ethrpc: fix a potential panic when querying block info

blockstore/autobatch.go, blockstore/autobatch_test.go, blockstore/union_test.go
Check the _underlying_ blockstore instead of recursing. Also, drop the
lock before we do that.
=> fix: autobatch: remove potential deadlock when a block is missing

blockstore/splitstore/splitstore.go, blockstore/splitstore/splitstore_check.go, blockstore/splitstore/splitstore_compact.go, blockstore/splitstore/splitstore_prune.go, blockstore/splitstore/splitstore_test.go, blockstore/splitstore/splitstore_warmup.go, documentation/en/default-lotus-config.toml, itests/kit/node_opts.go, itests/splitstore_test.go, node/builder_chain.go, node/config/def.go, node/config/doc_gen.go, node/config/types.go, node/modules/blockstore.go
Discussion kicked off here: https://github.com/filecoin-project/lotus/discussions/9128
Prune mode is now just a 3rd mode next to `discard` and `universal`.  There is only ever one compaction running so no need to add 3 new knobs to splitstore config.  
A quick conversation with @TippyFlitsUK supports the hypothesis that this minimal configuration strategy is a better all around approach.
=> feat:splitstore:single compaction that can handle prune aka two marksets one compaction

chain/vm/vm.go, cmd/tvx/stores.go, conformance/driver.go
#944
- fixup VM creation to use FVM if appropriate for the network
- implement View() for the tvx's Stores, which is needed by the FVM
=> fix: tvx: make it work with the FVM

.circleci/config.yml, .circleci/template.yml, .goreleaser.yaml
If possible, I would like to merge this in before the 1.18.0 release, otherwise I will have to manually build and update the binaries for that release myself. I know it's kinda big and last minute though, so I understand if you want to wait until 1.18.1-rc1 to put this in action.
Right now, our m1 builds are broken, and don't generate working universal binaries during releases. On pre-releases, they aren't built at all.
This does a few things:
- Uses a custom m1 mac runner running in aws to build darwin-arm64 binaries
- Prebuilds binaries for darwin-arm64, darwin-amd64, and linux-amd64 in three separate build jobs
- Pull those binaries together in a release job which makes a release using goreleaser, pubishing that to the Github Release
- It will now successfully publish the binaries on …
=> _ci_ Refactor release pipeline to better support m1 builds

chain/types/message.go, chain/vm/syscalls.go, go.mod, go.sum
This lets us add new address protocols to go-address without implicitly accepting them in messages on the network.
=> feat: chain: future proof the from & to address protocols

storage/sealer/manager.go
I was investigating #9396, and ran into this confusing piece of code. This PR doesn't actually solve 9396, though.
State the condition when we _want_ to move unsealed files more clearly.
I'm still a little unsure of this method. We might want to refresh the value of `moveUnsealed` after we've called into `FinalizeReplicaUpdate`, since that call might delete the unsealed files. But it should only do that when `keepUnsealed == 0`, so I guess it's fine.
=> refactor: sealing: minor refactor of FinalizeReplicaUpdate

storage/pipeline/states_failed.go, storage/pipeline/states_proving.go, storage/pipeline/states_sealing.go
=> fix: sealing pipeine: Release assigned deals on snapdeals abort

storage/pipeline/fsm_events.go, storage/pipeline/fsm_test.go, storage/pipeline/input.go
Fixes https://github.com/filecoin-project/lotus/issues/9478
Clear sector.CreationTime when starting sector upgrade
The sector state has a `CreationTime` field which holds the time of the first AddPiece performed on a sector.
Initially when a sector is created, this field will be 0, but after the first deal is inserted into the sector, we set that field to `now`.
If the sector isn't 100% full after `AddPiece`, it will return to `WaitDeals` to wait for more date, and use `CreationTime+WaitDealsDelay` to decide how long to wait for:
* This is fine for new sectors because they have just been created
* This is also fine for SnapDeals on CC sectors
* But it is not fine when doing SnapDeals on a sector which previously accepted deal data, for example aborted SnapDeals sector - because …
=> fix: sealing pipeline: Clear CreationTime when starting sector upgrade

lib/result/result.go, storage/paths/local.go, storage/wdpost/wdpost_run.go
* Add some more logs to wdpost cycle logic
* Respect context in local GenerateSingleVanillaProof
* before it could block forever if underlying storage reads blocked, e.g. with disconnected NFS, which would lead to the entire PoSt failing
* Now we'll return context error, which should result in only the slow-to-read sectors being skipped; There will also be a big, detailed log message printed.
=> feat: storage: Force exit GenerateSingleVanillaProof on cancelled context

.goreleaser.yaml
Original PR: filecoin-project/lotus#9600
I accidentally forgot to include linux in the list of platfroms we should release for. This should be backported into 1.19 as early as possible to ensure linux binaries get published.
=> _ci_ Forgot to include linux binaries in goreleaser

chain/actors/builtin/init/actor.go.template, chain/actors/builtin/init/init.go, chain/actors/builtin/init/state.go.template, chain/actors/builtin/init/v0.go, chain/actors/builtin/init/v2.go, chain/actors/builtin/init/v3.go, chain/actors/builtin/init/v4.go, chain/actors/builtin/init/v5.go, chain/actors/builtin/init/v6.go, chain/actors/builtin/init/v7.go, chain/actors/builtin/init/v8.go, chain/actors/builtin/init/v9.go
exposes the init actors address map's BitWidth and Hash function on the init actor api
=> refactor: chain/actors: expose address map bitwidth and hash function

chain/gen/genesis/fevm.go, chain/gen/genesis/genesis.go, go.mod, go.sum, itests/api_test.go, itests/fevm_test.go
we need this for wallaby and devnets, will be created by migration normally.
=> NV18: FEVM: setup FEVM during genesis: create ETH0 actor

go.mod, go.sum
I previously updated us to an intermediate version based on a git sha. That version removed a deprecation warning, but caused issues on older versions of MacOs (Big Sur and lower). That change just shipped with the most recent release. This release of Zondax/hid fixes things in a way that both removes the deprecation warning and works on older MacOS versions.
https://filecoinproject.slack.com/archives/CP50PPW2X/p1668426761104489
=> fix/build: Update Zondax/hid to 0.9.1

documentation/en/default-lotus-miner-config.toml, node/config/def.go, node/config/doc_gen.go, node/config/types.go, storage/sealer/faults.go, storage/sealer/manager.go
After https://github.com/filecoin-project/lotus/pull/9613 made timeouts enforced more correctly we see that on some setups the default hard-coded timeout is too tight
This PR adds two new config knobs which make the previously hard-coded pre-check timeouts configurable. It also bumps the default timeout to 10min from 160sec
```toml
#
SingleCheckTimeout = "10m0s"
#
PartitionCheckTimeout = "20m0s"
```
=> feat: wdpost: Configurable pre-check timeouts

.circleci/config.yml, .circleci/template.yml, .goreleaser.yaml, scripts/build-appimage-bundle.sh
The 1.19.0-rc1 release had a host of minor issues that happened because of some differences between the environment I tested stuff in and CircleCI.
https://app.circleci.com/pipelines/github/filecoin-project/lotus/24401/workflows/bcfbd26f-aebf-41d0-bb48-426f14d12111
This is a series of small fixes:
1. Use the `filecoin-goreleaser-key` CircleCI context, which has the GORELEASER_KEY env variable set (necessary for using the pro version of goreleaser). I also set this in the project env vars, but the context is a more reliable place to find the key, since it's used organization wide.
2. I moved the workspace directly to `/tmp/workspace`, but forgot to update one of the scripts which was using the old directory. This is now fixed.
3. Goreleaser checks to make sure the git state is clean before …
=> _build_: Fix issues with new goreleaser flow

.circleci/config.yml, .circleci/template.yml, .goreleaser.yaml, scripts/build-appimage-bundle.sh
Backports https://github.com/filecoin-project/lotus/pull/9684
=> baackport: ci: Fix issues with new goreleaser flow

chain/consensus/filcns/compute_state.go, chain/stmgr/call.go, chain/stmgr/utils.go, chain/types/tipset_key.go, chain/vm/fvm.go, chain/vm/vm.go, conformance/driver.go
We do this by adding yet another "getter" to the VM that resolves an epoch into a TipSetKey.
Alternatively, we could stick this functionality on `Rand`, but then it wouldn't really be "rand" but something else...
Depends on https://github.com/filecoin-project/filecoin-ffi/pull/339
Merge plan:
1. Merge https://github.com/filecoin-project/filecoin-ffi/pull/339.
2. Rebase this PR on _master_.
3. Merge this PR to master.
4. Port this change to the nv18 branches.
Unfortunately, it needs to land on master because it bubbles a breaking change in the FFI (where the FVM now needs the ability to lookup tipset CIDs).
Alternatively, we could make this _optional_ with a runtime type assertion. That is, if we find that we're using "v3" inside the FFI, we could type-assert that the "externs" supports …
=> feat: fvm: add support for looking up past tipset CIDs

markets/idxprov/mesh.go
https://github.com/filecoin-project/lotus/issues/9626
We need to change the direction of libp2p connection init. Rather than dialling from market to fullNode, we should dial from fullNode to market. Thus removing the requirement to have libp2p exposed.
=> fix: index-provider: change connection initiation direction between daemon and market

go.mod, go.sum
Brings in v10 actors and fixes params for `UniversalReceiverHook` for `Account` and `Multisig` Actors.
=> chore: deps: Update go-state-types to v0.10.0-alpha-2

go.mod, go.sum
Backports https://github.com/filecoin-project/lotus/pull/9714
=> chore: deps: update go-state-types backport

storage/pipeline/states_replica_update.go
Discovered while investigating #8415 
The event handler [already factors in the provided confidence](https://github.com/filecoin-project/lotus/blob/e65fae28de2a44947dd24af8c7dafcade29af1a4/chain/events/events_height.go#L64), so the current code has the effect of waiting for it twice -- seems wrong to me.
=> fix: sealer: Tweak confidence for handleUpdateActivating

.circleci/config.yml, itests/kit/ensemble.go, itests/sector_unseal_test.go, storage/sealer/ffiwrapper/sealer_cgo.go, storage/sealer/manager.go
https://github.com/filecoin-project/lotus/issues/9159
Currently when unsealing a sector, its expected that the unsealing worker has access to long term storage and stores the unsealed data there. We need to be able to unseal data and deliver it to the miner without having access to long term storage for retrievals.
Instead of using long term storage, use sealing storage to in the unsealing pipeline
=> fix: sealing: Set all path types for Unseal pipeline to sealing storage

metrics/metrics.go, storage/sealer/manager.go, storage/sealer/manager_test.go, storage/sealer/sched.go, storage/sealer/sched_assigner_common.go, storage/sealer/sched_test.go
This is for AB testing https://github.com/filecoin-project/lotus/pull/9737
Add 4 new duration-distribution metrics to the prometheus endpoint around scheduling cycle duration.
Those are in `http://127.0.0.1:2345/debug/metrics` (or whatever the miner api address), and look this like:
```
lotus_sched_assigner_cycle_candidates_ms_bucket{le="0.01"} 0
lotus_sched_assigner_cycle_candidates_ms_bucket{le="0.05"} 0
lotus_sched_assigner_cycle_candidates_ms_bucket{le="0.1"} 0
lotus_sched_assigner_cycle_candidates_ms_bucket{le="0.3"} 0
lotus_sched_assigner_cycle_candidates_ms_bucket{le="0.6"} 0
lotus_sched_assigner_cycle_candidates_ms_bucket{le="0.8"} 0
lotus_sched_assigner_cycle_candidates_ms_bucket{le="1"} 0
lotus_sched_assigner_cycle_candidates_ms_bucket{le="2"} 0 …
```
=> feat: sched: Add metrics around sched cycle

lib/lazy/getonce.go, storage/sealer/sched.go, storage/sealer/sched_assigner_common.go, storage/sealer/sched_resources.go, storage/sealer/sched_test.go, storage/sealer/sched_worker_cache.go, storage/sealer/selector_alloc.go, storage/sealer/selector_existing.go, storage/sealer/selector_move.go, storage/sealer/selector_task.go
Based on on https://github.com/filecoin-project/lotus/pull/9738
I've re-read the scheduler code today, and realized that all calls to workers in the scheduling loop are perfectly cachable. This PR adds some caching in the scheduling loop, theoretically reducing the number of workers calls in a scheduling cycle from `tasksToSchedule*candidateOpenWindows` to `unique(candidateOpenWindows.Worker)`
Benchmark on 400 deep queue with 200 workers (tldr ~700x faster when network roundtrips are ~100us)
Before:
```
BenchmarkTrySched/200w-400q
BenchmarkTrySched/200w-400q-32         	       1	79 854 360 185 ns/op
```
After:
```
BenchmarkTrySched/200w-400q
BenchmarkTrySched/200w-400q-32         	       9	 114 381 511 ns/op
```
- example: ` …
=> feat: sched: Cache worker calls

itests/sector_unseal_test.go
https://github.com/filecoin-project/lotus/pull/9648 added a new task type, and https://github.com/filecoin-project/lotus/pull/9694 was opened before it was in master, but landed after breaking tests
=> fix: itests: Add missing task type in TestUnsealPiece

.circleci/config.yml, .circleci/template.yml
We have this env varible set in the project settings as well as the CircleCI context. Due to what seems like a bug on CircleCI's eng, the using the context causes our release flow to halt when some member of the team initiate releases, but not others. So for now, it's safest to rely on the project settings, which definitely won't cause this issue.
Specifically, if we don't merge this if @shrenujbansal creates the release tag again it will likely not work, but if that happens any other member of the filecoin-project or should be able to rebuild and have it work.
- `area`, e.g. …
=> _ci_: Rely on local env varibale instead of context

chain/messagepool/messagepool.go, chain/messagepool/messagepool_test.go
in current CapGasFee, skipp gaspremium check when fee is enough
- [ x] Commits have a clear commit message.
- [x ] PR title is in the form of of `<PR type>: <area>: <change being made>`
=> fix:mpool add gaspremium check when less than maxfee

node/impl/full/eth.go
We were sending them from a blank EVM contract deployed at 0x0, but the
FVM was rejecting those sends because that's not a real account.
NOTE: this only affects local gas estimation, not network operations.
=> hack: send eth messages from an existing account when estimating gas

node/impl/full/eth.go
Some clients may explicitly set the system address, which won't work.
NOTE: this only affects local gas estimation, not network operations.
=> hack: replace an explicit "evm-system" from address with an account

go.mod, go.sum
Per @vyzo has nice memory usage improvements :)
=> chore: deps: update go-libp2p-pubsub

cli/util/apiinfo.go
Regression from https://github.com/filecoin-project/lotus/pull/9294
Without this fix `FULLNODE_API_INFO=wss://api.chain.love ./lotus daemon --lite` wouldn't work
=> fix: cliutil: Fix URL-based API endpoint parsing

Makefile, scripts/generate-lotus-cli.py
`make docsgen-cli` was failing on mac
changing Makefile to explicitly call python3 
we're discussing rewriting ./scripts/generate-lotus-cli.py into go to not require python. However since we already are compatible with python3 and python 2 is not supported anymore, the explicit change to python3 is good. Simialrly once we rewrite generate lotus cli in GO, it's not bad that we've accepted this change, we can then still rip out python, but in the meantime having it supported on more. machines is good.
- `area`, e.g. api, chain, state, market, mempool, multisig, networking, paych, …
=> fix make docsgen-cli use python3

chain/consensus/filcns/upgrades.go
Allow the maximum number of workers for state migrations to be specified via an environment variable LOTUS_MIGRATION_MAX_WORKER_COUNT
Limits the number of actors being migrated simultaneously, thus reducing the overall memory footprint required by migrations. Motivated by experience in production where nodes with high CPU count exhaust all available memory due to a high number of workers loading actor states into memory to perform migration.
=> chain/migrations refactor: optionally set max migration workers

cli/chain.go, documentation/en/cli-lotus.md
Remove unused flag
Thanks to @sectrgt  for asking a bunch of questions on slack and flushing this issue out
=> fix: docs: remove unused flag from chain prune

.goreleaser.yaml
This is a very simple change that updates the default name for releases to no longer include the word `Release`, only the version `vX.X.X`. This has been the practice when manually naming releases, but when I created the automated release workflow I included the extra word by accident. This removes it.
=> _ci_ Switch release name template from "Release vX.X.X" to "vX.X.X"

cli/chain.go, documentation/en/cli-lotus.md
=> feat: ux: add value option to message invocation cli

node/impl/full/eth.go
Fixes https://github.com/filecoin-project/ref-fvm/issues/1206
In EthGetLogs when `toBlock` contained an epoch the code was incorrectly taking the epoch from `fromBlock` leading to the bizarre behaviour detailed in the linked issue
=> Use correct field for upper epoch range in EthGetLogs

chain/events/filter/index.go, chain/types/event.go, itests/eth_filter_test.go, itests/fevm_events_test.go
Fixes  https://github.com/filecoin-project/ref-fvm/issues/1207
Finding event logs in the historical index by topic was broken for a few separate reasons:
1. sometime between original implementation and FIP-0049 landing the indexable flag was split into 2 distinct flags - this PR adds these as constants in the types package
2. decoding the cbor encoded byte array values was added as a fix in the api but didn't find its way into the database code which was recording cbor encoded versions of the entry values
3. the query code was not accounting for zero padding of the topic byte arrays
Points 1+2 result in bad data in the database so any existing indexed events will not be retrievable by topic even after this PR is merged. They are still retrievable via other criteria. New events logged …
=> Fix getting event logs by topic

.circleci/config.yml, .circleci/template.yml, go.mod, node/modules/tracer/tracer.go, node/modules/tracer/tracer_test.go
**This is a p0 update**
When I refactored the docker image publishing process earlier, I forgot two critical pieces which broke our docker releases. We haven't pushed any images in the last 11 days as a result, since `1.18.1`
1. I used `echo` in the publish jobs to sanity check that they were working without publishing new images, and forgot to remove those `echo` calls when it was merged, meaning none of our docker publish jobs were actually publishing images.
2. I forgot to also create build / publish jobs for the `lotus` image, instead only building `lotus-all-in-one`.
In addition to fixing the two issues above, this PR:
1. Builds and pushes a container on every master merge to the `master` branch.
2. Pushes containers to immutable SHA tags in additional to the mutable channel tags …
=> _build_: Fix docker deployments

node/modules/tracer/tracer.go, node/modules/tracer/tracer_test.go, storage/pipeline/input.go, storage/pipeline/sealing.go
Fixes https://github.com/filecoin-project/lotus/issues/9769
Don't panic, also improve assigner debug logs
Before the Shark upgrade `checkDealAssignable` would only ever return `false` if the sector was an upgrade sector.
When that happened we'd try to get sector expiration for the `CC update sector %d cannot fit deal...` debug log, which would panic when we try that on non-upgrade sectors - which can now happen due to the new TermMax handling logic in `checkDealAssignable` when the sector has some deals assigned, and we have an incoming deal which can't fit into the sector.
- …
=> fix: sealing: Avoid nil dereference in debug log

cli/client.go
Deal cli wasn't checking upper limit for deals, which was easy to mess up on devnets because of the lower block time.
=> fix: cli: Check upper bound for deal duration

chain/actors/builtin/miner/actor.go.template, chain/actors/builtin/miner/miner.go, chain/actors/builtin/miner/state.go.template, chain/actors/builtin/miner/v0.go, chain/actors/builtin/miner/v10.go, chain/actors/builtin/miner/v2.go, chain/actors/builtin/miner/v3.go, chain/actors/builtin/miner/v4.go, chain/actors/builtin/miner/v5.go, chain/actors/builtin/miner/v6.go, chain/actors/builtin/miner/v7.go, chain/actors/builtin/miner/v8.go, chain/actors/builtin/miner/v9.go, chain/stmgr/actors.go, itests/ccupgrade_test.go, itests/sector_make_cc_avail_test.go, itests/sector_prefer_no_upgrade_test.go, itests/sector_revert_available_test.go, miner/warmup.go, node/impl/full/state.go, storage/pipeline/states_replica_update.go, storage/pipeline/upgrade_queue.go
`StateSectorGetInfo()` returns `nil, nil` in the case that the given sector number isn't found. Many functions that call `StateSectorGetInfo()` do not check if the resulting `SectorOnChainInfo` is nil or not, so this PR adds those checks. This was originally discovered because of https://github.com/filecoin-project/lotus/pull/9822/files
The API is designed this way to allow for indicating that the sector is not found. We don't want to break the current functionality of the API, but in the future we could probably send a typed error instead of returning `nil, nil`.
- `area`, …
=> fix: miner: Check for nil returns from StateSectorGetInfo

chain/actors/builtin/registry.go, chain/actors/builtin/registry.go.template, chain/vm/invoker.go, go.mod, go.sum
Integrates https://github.com/filecoin-project/go-state-types/pull/133
Makes method metadata much cleaner :)
=> Chore: Use abi.MethodNum instead of uint64 for method nums

.circleci/config.yml, .circleci/template.yml, .goreleaser.yaml
This fixes a bug in the new MacOs release process. I accidentally downloaded installed the amd64 go in the new arm64 / Mac M1 environment, which means that it produced a very confused build that was trying to build and amd64 binary linked against arm64 libraries which didn't work. I already updated the 1.19.0 release with the correct binaries, but they will keep breaking until this released.
=> _build_: Fix Macos M1 and universal binary builds

chain/wallet/multi.go, chain/wallet/wallet.go
Would be useful for debugging when a message might be "sent" by an address the user doesn't expect. Inspired by https://github.com/filecoin-project/lotus/issues/9856
=> feat: wallet: Print addr when key not found

cli/helper.go, node/shutdown.go
Closes https://github.com/filecoin-project/lotus/issues/9862
Right now we set up a listener for SIGINT and SIGTERM once we start the node, but there are some cases where we do *a lot* of work before this happens, such as calling `lotus daemon --import-snapshot' where we import the entire snapshot before starting the node.
Now we install a listener before we start running the cli app. We remove this listener in favour of a more graceful shutdown once we start the node.
=> fix: daemon: listen for SIGINT and SIGTERM even before node starts

itests/kit/log.go, itests/multisig_test.go
Probably helps https://github.com/filecoin-project/lotus/issues/9880
Quiet wdpost logs so logs are actually readable. Add a log for when the trace isn't the right depth that should print the trace.
=> fix: test: Maybe help with TestMultisigReentrant flakes

snap/snapcraft.yaml
We're currently failing the automated security review on snapcraft because the lotus binary has the execstack value set:
https://linux.die.net/man/8/execstack
This commit passes the appropriate flags to ld to disable the execstack flag when building the binaries for snapcraft:
https://linux.die.net/man/1/ld
We may want to consider disabling this as part of the main build. Research seems to indicate that allow the executable stack can lead to security issues, but I am not enough of a security expert to know for sure what the right call here is:
https://f0rm2l1n.github.io/2022-04-02-What-is-happended-to-execstack/
https://app.circleci.com/pipelines/github/filecoin-project/lotus/24812/workflows/caf64d82-58af-4985-85ad-8a8e838fd174
https://filecoinproject.slack.com/archives/C029MT4PQB1/p167097 …
=> _build_ Set noexecstack on snapcraft builds

chain/types/ethtypes/eth_types.go, chain/wallet/key/key.go, lib/sigs/delegated/init.go
Not having this functionality was making testing EthAccount abstraction difficult.
Support creating Eth keys, and generating signatures with them. Assumes all Delegated keytypes are Ethereum Account senders.
=> Support creation and signing of Eth keys

itests/raft_messagesigner_test.go
Skips the flaky test until the underlying issue can be fixed. https://github.com/filecoin-project/lotus/issues/9888
=> chore: Skip TestGoRPCAuth until Raft is fixed

.circleci/config.yml, .circleci/template.yml
I accidentally left in a parameter in this docker push that will cause it to error. The image generated for Mainnet doesn't use the `mainnet` suffix, but I left it in there for the SHA publish. This removes it.
=> Don't include network when publishing mainnet sha image

chain/messagepool/messagepool.go, node/modules/chain.go
Addresses https://github.com/filecoin-project/lotus/issues/9846
Don't deadlock in splitstore compaction when applying mpool protector; Bail from compaction when mpool is busy.
A better fix would be to maybe drop the splitstore lock while applying protectors, and re-get the lock in protector callback.
My node has hit this 4 times in a row now, and it's very annoying, so I have fixed it.
=> fix: splitstore: Don't deadlock in mpool protector

chain/types/ethtypes/eth_types.go, cli/cmd.go, cli/eth.go, documentation/en/cli-lotus.md, node/impl/full/eth.go
https://github.com/filecoin-project/lotus/issues/9778
> ➜  lotus git:(sbansal/eth-state-cli) ✗ ./lotus eth stat --filaddr t410fiux3jxq5bcdb3ctzgghvxt25ss3zgos2ifm3qki
> Filecoin address:  f410fiux3jxq5bcdb3ctzgghvxt25ss3zgos2ifm3qki
> Eth address:  0x452fb4de1d08861d8a79318f5bcf5d94b7933a5a
> Code cid:  bafk2bzacednmsvivt6tszxgnn3xy3iuwqqlhn5uif6mf4gj2du6ec4m6emble
=> feat: cli: Add cli to inspect Eth addresses and simulate calls

chain/messagepool/messagepool.go, chain/types/ethtypes/eth_transactions.go
Signature cache entry was constructed with the wrong cache key which did not cover the signature.
Plus, a little bit of gofmt on touched files.
Cover the signature by relying on the CID from the SignedMessage, which for the Delegated signature type covers the signature.
=> fix: FEVM: signature validation cache for messages with Delegated signatures.

itests/wdpost_no_miner_storage_test.go
Increases block time from 2ms to 10ms. The failure I've seen has the miner missing the windowed post. https://app.circleci.com/pipelines/github/filecoin-project/lotus/25199/workflows/f17d0062-e0c2-4a0c-995c-a0f1f338332e/jobs/731895
=> fix: test: Increase blocktime in TestWindowPostNoMinerStorage

chain/consensus/filcns/filecoin.go
https://github.com/filecoin-project/ref-fvm/issues/1354
Embryo nonces must be 0 if they are acting as top-level sender.
Note that if the protocol is correctly enforced, we should never have an embryo actor with non-zero nonce _anyway_, which means top-level sends from embryos with non-zero nonce are already invalid because they should always be the incorrect nonce.
But this is an extra check that intentionally freezes such actors if something funky has happened.
=> feat: consensus: only embryos with nonce 0 are valid senders

.circleci/config.yml, chain/consensus/filcns/filecoin.go, chain/messagepool/messagepool.go, chain/types/ethtypes/eth_transactions.go, chain/types/ethtypes/eth_transactions_test.go, chain/wallet/key/key.go, itests/eth/deploy_test.go, itests/eth_account_abstraction_test.go, itests/eth_deploy_test.go, itests/kit/evm.go, itests/kit/state.go, lib/sigs/delegated/eth.go, node/impl/full/eth.go
Adds a basic FEVM integration test that exercises:
- Ethereum JSON-RPC API, including filters, transaction submission, and various methods.
- f4 addresses
- placeholder/embryo creation
- placeholder/embryo promotion to Ethereum account
- instantiation of the EVM smart contract
- nonce update
It adds the following to the itest kit:
- New reusable utilities to the EVM namespace to make future test development faster/easier. Concretely:
- NewAccount
- AssertAddressBalanceConsistent
- SignTransaction
- SubmitTransaction
- ComputeContractAddress
- New reusable utility:
- AssertActorType
We also conduct some minor refactors to tidy things up.
=> add a basic FEVM integration test.

node/impl/full/eth.go
Hardhat users are having troubles deploying contracts to Wallaby via Hardhat.
The problem was introduced in 20f27af97ef721f1782bd0b4b9a9576c39dcebe8. That commit introduced the ability to resolve transactions pending in the mpool, but incorrectly returned an error when the transaction was not found. Eth clients expect a nil here, and Hardhat will send a tx and then poll the endpoint. But it will fail if an error is returned.
And one would think: if Wallaby users are deploying via Glif endpoints, then surely the Glif endpoint should be able to find the transaction within its mpool, right? Where this likely goes sideways is with load balancing.
1. The contract is deployed through origin node A (eth_sendRawTransaction).
2. The call to fetch the tx is routed to node B …
=> fix: Eth JSON-RPC API: eth_getTransactionByHash should return nil when not found

node/impl/full/eth.go
eth_blockNumber blindly returned the HEAD height - 1. This makes the method aware of null rounds, so it will give the appearance that the chain has paused while null rounds are being produced, and will keep clients from querying for null rounds when blocks don't exist.
=> fix: eth_blockNumber: make it aware of null rounds.

chain/gen/gen.go, chain/store/store.go, chain/sync.go, chain/sync_test.go, cmd/lotus-sim/simulation/block.go
https://github.com/filecoin-project/ref-fvm/issues/1053
- Introduce a new `PersistTipset` method that replacs `PersistBlockHeaders` at all callsites (it's what we always want to do)
- Store the TSK in the `PersistTipset` method
- Drop unused `AddBlock` method
=> fix: chainstore: store tipsetkeys in the blockstore

snap/snapcraft.yaml
Reverts filecoin-project/lotus#9868
Ok, passing LDFLAGS in that way didn't work, I did some more experimentation, and couldn't get it to work at all. So just revert it for now, and I'll chat with the Snapcraft folks to see if we can get an exception.
=> Revert "_build_ Set noexecstack on snapcraft builds"

cmd/lotus-bench/main.go
Remove the unused `FIL_PROOFS_MAXIMIZE_CACHING` enviroment variable from the bench-code as it isn´t a thing anymore. Ref: https://filecoinproject.slack.com/archives/CEGB67XJ8/p1653639710341169?thread_ts=1653555880.864929&cid=CEGB67XJ8
=> fix: bench: remove unused env

cmd/lotus-miner/sectors.go, documentation/en/cli-lotus-miner.md
https://github.com/filecoin-project/lotus/issues/9940
=> add renew max-sectors flag

blockstore/splitstore/splitstore_compact.go, itests/splitstore_test.go
#9799
FEVM is introducing H(TipSetKey) to get a single blockhash to return in places where ethereum wants a single hash.  This PR ensures that splitstore compaction will keep these cids pinned in the hotstore.
WIP as this still needs tests
Also I don't think we're actually writing tipset references to the chain store yet if I'm right about this we'll need to do that to actually test this out.
=> feat:splitstore:retain tipset references in hot store

chain/actors/builtin/registry.go, chain/actors/builtin/registry.go.template, chain/vm/invoker.go, go.mod, go.sum
Should fix https://github.com/filecoin-project/ref-fvm/issues/1022
- Add the missing actors to the registry
- Skip actors with nil state
- Stop special-casing the account actor -- I don't think we ever should have been doing this?
Needs https://github.com/filecoin-project/go-state-types/pull/143 in a release
=> Add new FEVM actors to the registry

api/docgen/docgen.go, chain/types/ethtypes/eth_types.go, chain/types/ethtypes/eth_types_test.go, itests/eth_deploy_test.go, itests/eth_filter_test.go
https://github.com/filecoin-project/lotus/issues/9849
=> itests: Eth JSON-RPC: EthGetBlockByHash and EthGetBlockByNumber

cli/filplus.go, documentation/en/cli-lotus.md
Closes https://github.com/filecoin-project/lotus/issues/9271
Adds a cli command to list all claims for a given provider.
Adds a cli command to remove expired claims for a given provider.
=> feat: cli: list claims and remove expired claims

storage/pipeline/checks.go
Closes https://github.com/filecoin-project/lotus/issues/9053
Removed workaround. The issue was fixed by golang v1.18.6
Now that we're building using 1.18.8 as the minimum version, the workaround is no longer needed.
=> fix: Remove workaround that is no longer needed

.circleci/config.yml, .circleci/template.yml
- Creates an initial build step that all commands can share so they don't all have to build themselves.
- Uses medium+ sized containers for most things. Some jobs are kept on 2xl executors because of parallelism/RAM requirements. Medium+ uses 15 credits/min compared to 80/min for 2xl, and barely causes a slowdown in many of our tests. [More info on executors here](https://circleci.com/product/features/resource-classes/#docker).
- Did some general cleanup and refactoring.
You can look at the stats for a run of master as it is currently [here](https://app.circleci.com/insights/github/filecoin-project/lotus/workflows/ci/overview?branch=gstuart%2Fci-bench-old).
You can look at the stats for this brach [here](https://app.circleci.com/insights/github/filecoin-project/lotus/workflows/ci/overview? …
=> feat: ci: make ci more efficient

chain/signatures.go, chain/types/ethtypes/eth_transactions.go, itests/eth_account_abstraction_test.go
https://github.com/filecoin-project/ref-fvm/issues/1433
- Make EthTxArgsFromMessage much stricter
- Roundtrip Eth <-> FIL messages during siggy validation
=> fix: delegated signatures: check every field of txs and roundtrip eth <-> FIL

cmd/lotus/main.go, documentation/en/cli-lotus.md
I believe this addresses https://github.com/filecoin-project/lotus/issues/9611
Master seems to be red on ci
=> feat: lotus-cli: Add global color flag

cmd/lotus-miner/sectors.go, documentation/en/cli-lotus-miner.md
Closes https://github.com/filecoin-project/lotus/issues/9501
Removes `extend`. Renames `renew` to `extend`. Allows the remaining function to accept command line parameters as a list of sector numbers. Also includes some minor refactoring.
=> feat: cli: Refactor renew and remove extend

cmd/lotus-shed/cid.go
=> feat:shed:add cid to cbor serialization command

.circleci/config.yml, chain/store/snapshot.go, chain/store/store.go, chain/store/store_test.go
https://github.com/filecoin-project/lotus/issues/9977
On snapshot import, persist the tipset key cids in the chain blockstore
=> feat: snapshot: Store tipset key cids in chain store during snapshot import

chain/consensus/filcns/compute_state.go
This was missed in #10040. Impact is functionality like `lotus state read-state` is broken.
- Add the missing registration
- Will open a PR either auto-generating them, or adding a note to the `actors_version_checklist.md`
=> fix: invoker: setup v11 in the registry

cmd/lotus-shed/actor.go
Adding the `ProposeChangeBeneficiary` and `ConfirmChangeBeneficiary` commands to lotus-shed.
Having these commands in the `lotus-shed` makes it possible to propose and confirm beneficiary address changes without the need to import the keys into the lotus-node that the `lotus-miner` is connected to.
=> feat: shed: Add beneficiary commands

cli/state.go, cmd/lotus-shed/main.go, cmd/lotus-shed/state-stats.go
https://github.com/filecoin-project/lotus/issues/9793
Add two commands `stat-actor` and `stat-obj` that work with an offline lotus repo which report dag size stats.
=> feat: add toolshed commands to inspect statetree size

cli/evm.go
=> fix:cli:make the evm invoke command work again

.circleci/config.yml, itests/deals_padding_test.go, itests/deals_power_test.go, itests/eth_block_hash_test.go, itests/eth_deploy_test.go, itests/kit/node_full.go
Add a test to reproduce https://github.com/filecoin-project/lotus/issues/10061.
=> add integration test to catch tipset CID flakiness.

documentation/en/default-lotus-config.toml, itests/eth_deploy_test.go, itests/eth_filter_test.go, itests/eth_hash_lookup_test.go, itests/eth_transactions_test.go, itests/fevm_test.go, itests/kit/node_opts.go, node/builder_chain.go, node/config/def.go, node/config/doc_gen.go, node/config/types.go, node/impl/full/dummy.go, node/impl/full/eth.go, node/modules/ethmodule.go
Closes https://github.com/filecoin-project/lotus/issues/10067
=> config: Fevm.EnableEthPRC

.circleci/config.yml, chain/store/store.go, itests/deals_padding_test.go, itests/deals_power_test.go, itests/eth_block_hash_test.go, itests/eth_deploy_test.go, itests/kit/node_full.go
Fixes #10061
The bug, introduced in #9904, caused us to not put the "expanded" tipsetkey in our blockstore. We're now putting the expanded TSK.
I'm a little confused about how things were working _before_ 9904. AFAIC tell we had the opposite bug before 9904 -- we _only_ put the TSK when we were taking a new heaviest tipset, which does _not_ happen during "catch-up" sync. I suspect we were missing all TSKs during catch-up sync in the previous version.
=> fix: chain: put tipsetkey upon expansion of tipset

documentation/en/default-lotus-config.toml, itests/fevm_test.go, itests/kit/node_opts.go, node/builder_chain.go, node/config/def.go, node/config/doc_gen.go, node/config/types.go, node/impl/full/dummy.go
Fixes a typo in https://github.com/filecoin-project/lotus/pull/10072
```
[Fevm]
#
EnableEthRPC = false
```
=> fix: config: Fix eth rpc typo

node/rpc.go
will introduce later until chainlist , docs and operators fully tranisted to v1 -> eth api
=> Revert "fix: should not serve non v0 apis in v0"

chain/events/filter/event.go
We were putting the unsigned/VM message through the pipeline. The events index was storing the _unsigned_ message CID.
However, the Eth tx hash index maps signed Delegated-signature message CIDs to transaction hashes, i.e. it uses the _signed_ message CID.
As a result, eth_getLogs and other log-related methods were unable to resolve the transaction hash from the index properly, and would end up returning 0x00..00 in the transactionHash field.
Use the correct message.
=> fix: events: put the _signed_ message through the pipeline.

documentation/en/default-lotus-config.toml, itests/eth_deploy_test.go, itests/eth_filter_test.go, itests/kit/node_opts.go, node/builder_chain.go, node/config/def.go, node/config/doc_gen.go, node/config/types.go, node/modules/actorevent.go, node/modules/ethmodule.go
Sets a default path for the Events Database to be in the same directory as the tx hash database.
Enables all event API functionality if EnableEthRPC is set to true, otherwise it is always disabled.
Changes the Event Config to allow opt-out of these event APIs
=> feat: Events API enabled by default if EnableEthRPC is true

build/params_testground.go, chain/store/snapshot.go
Fixes a build error when running `go build -tags testground -o /dev/null ./cmd/lotus`
Ci all-in-one builds have been broken for a little bit https://app.circleci.com/pipelines/github/filecoin-project/lotus/25802/workflows/0f7450bf-aced-4485-b633-20c61ae515a1/jobs/778931
=> fix: testground build was broken

.circleci/config.yml, .circleci/template.yml
Builds that we're supposed to push docker images were sometimes failing during the push step, because of a bug in the circleci config. Once this is merged, the push step should be skipped when it's not needed, and we'll no longer experience errors like the following: 
https://app.circleci.com/pipelines/github/filecoin-project/lotus/25558/workflows/9b0c0540-8321-486c-b164-90fe76d5f177/jobs/759269
=> Properly balance <<?>> in circleci docker config

.circleci/config.yml, .circleci/template.yml
This commit reverts a change with the previous fix for this flow:
- https://github.com/filecoin-project/lotus/pull/10088
=> Add back <<network>> parameter for docker push

go.mod, go.sum, itests/deals_concurrent_test.go, markets/dagstore/miner_api_test.go, node/builder_miner.go, node/modules/storageminer.go, node/modules/storageminer_idxprov.go, node/modules/storageminer_idxprov_test.go
None.
Upgrade to the latest index-provider and as a result also upgrade go-fil-markets.
Note that the index-provider go module is renamed and moved to `ipni` GitHub org.
=> chore: market: Upgrade to index-provider 0.10.0

chain/events/filter/event.go, chain/events/filter/index.go, node/impl/full/eth.go
Fixes https://github.com/filecoin-project/ref-fvm/issues/1345
All cbor decoding/encoding of event log values by filters is now handled in the Eth API. Internally all values are kept as cbor encoded byte arrays.
*NOTE: this invalidates previous data stored in the event log sqlite database so events indexed before this change will not be discoverable. Advise removing the database to start indexing to a new one.*
This is currently based on https://github.com/filecoin-project/lotus/pull/10083 which contains comprehensive itests for this area.
- `area`, e.g. api, chain, state, …
=> fix: event filters use cbor encoding internally

itests/paych_api_test.go
Did we really not have an issue for this?
Fix the test
The test was failing likely due to it running on two nodes, and in some cases when a message creating a channel landed on one node, we'd query state from the other node - which isn't the block miner, and could fall behind in sync (block time was 5ms, so that could happen quite easily). The fix is to wait for the nodes to be in sync at certain points.
=> fix: itests: Fix flaky paych test

itests/fevm_test.go
On top of https://github.com/filecoin-project/lotus/pull/10010
Closes https://github.com/filecoin-project/ref-fvm/issues/1322
Add 2 itests:
* One with a function which calls itself recursively
* One with a function which calls itself recursively, then calls the contract recursively
=> itests: Test FEVM recursive calls

chain/vm/invoker.go
Resolves a TODO in code.
We have certain actors that have no state. We register these actors as having `nil` states in the actor registry. When dumping an actor's state, we currently just skip these actors (return nil).
In Filecoin today, however, the Head for these actors must always be the EmptyObjectCID. This PR changes DumpActorState behaviour to actually assert that and fail if the Head is something else -- this is only a UX change, but is still correcter.
=> feat: vm: Assert empty object CID when dumping state

cli/chain.go, cli/client.go, cli/disputer.go, cli/params.go, cli/state.go, cli/wallet.go, documentation/en/cli-lotus.md
Standarize cli/code functions similar to: https://github.com/filecoin-project/lotus/pull/9317
- Change to cctx.NArg() instead of cctx.Args().xxx
- Add ArgsUsage to commands that was missing it
- Add check for args and print help on functions that did not have it
=> chore: cli: cleanup cli 

chain/actors/builtin/builtin.go, chain/actors/builtin/builtin.go.template, chain/stmgr/supply.go
Fixes https://github.com/filecoin-project/lotus/issues/10103
- Consider funds to EAM as locked
- Add evm, placeholder and ethaccount actors to circ supply
On Hyperspace you currently encounter:
```
lotus state circulating-supply 
ERROR: unexpected actor: t02188
```
With this fix you should not encounter any errors
```
lotus state circulating-supply
Exact circulating supply:  100277222.576725446405532536 FIL
```
=> fix: stmgr: Add nv18-actors to CircSupply

build/params_2k.go
@maciejwitowski reported that devnets were failing with
```
failed to create block: failed to load tipset state: error handling state forks: migrating actors v10 state: expected state root version 4 for actors v9 upgrade, got 5
```
This makes sense because the current default is to start from nv18, but also include the nv17 -> nv18 upgrade at epoch 30, which obviously doesn't work.
Start from v17, upgrade to v18 at epoch 30.
=> fix: devnets: default to starting from nv17

storage/pipeline/input.go, storage/pipeline/mocks/mock_precommit_batcher.go, storage/pipeline/precommit_batch.go
Closes https://github.com/filecoin-project/lotus/issues/9368
Checks for allocation expirations to make sure we don't wait too long before sealing. This is slightly tricky because allocations are allowed to expire, the miner will just not get the increased power for the verified deal.
This could use some testing. 
=> feat: Check for allocation expiry when waiting to seal sectors

go.mod, go.sum
@frrist noticed that `DelegateCallParams` weren't decoding correctly, fix in https://github.com/filecoin-project/go-state-types/pull/157
Just update to latest GST.
=> chore: deps: Update to go-state-types v0.10.0-alpha-11

go.mod, go.sum
=> chore: deps: Update to latest hyperspace branch of go-state-types

go.mod, go.sum, node/modules/chain.go
This was migrated in https://github.com/ipfs/go-libipfs/pull/63.
- https://github.com/ipfs/go-libipfs/pull/63
**None:** the code was just copied over.
Similar as https://github.com/filecoin-project/lotus/pull/10126
=> chore: node: migrate go-bitswap to go-libipfs/bitswap

lib/rpcenc/reader.go, lib/rpcenc/reader_test.go
Couldn't find anything about "AddPiece stuck" where it wasn't showing up in either `sealig sched-diag` or `sealing jobs`, but maybe there is an issue about that
Fixes https://github.com/filecoin-project/lotus/issues/10115
=> fix: rpcenc: Don't hang when source dies

cli/client.go, cmd/lotus-miner/actor.go, cmd/lotus-miner/dagstore.go, cmd/lotus-miner/index_provider.go, cmd/lotus-miner/market.go, cmd/lotus-miner/sealing.go, cmd/lotus-miner/sectors.go, cmd/lotus-miner/storage.go, documentation/en/cli-lotus-miner.md, documentation/en/cli-lotus.md
Thanks to @FlattestWhite for https://github.com/filecoin-project/lotus/pull/10022
We now have global color flags for all functions in lotus and lotus-miner cli. 
https://github.com/filecoin-project/lotus/blob/00a73fd88f1a2622105ae88495e293a16c14579b/cmd/lotus/main.go#L56
https://github.com/filecoin-project/lotus/blob/00a73fd88f1a2622105ae88495e293a16c14579b/cmd/lotus-miner/main.go#L74
I've removed all the redundant individual flags.
=> chore: cli: Remove unneeded individual color flags

cmd/lotus-miner/actor.go, cmd/lotus-miner/sectors.go, cmd/lotus-miner/storage.go, documentation/en/cli-lotus-miner.md
- Add ArgsUsage to commands that where missing it
- Move check for bool flag after NArgs check on `actorSetPeeridCmd` and `sectorsTerminateCmd`
- Change to cctx.NArg() instead of cctx.Args().xxx in a couple of places
=> fix: cli: add ArgsUsage

node/builder.go, node/modules/lp2p/host.go
Partially addresses: https://github.com/filecoin-project/lily/issues/692
1. Adding a special option for configuring the UserAgent
2. Adding a function callable by 3rd parties to override the user agent
=> feat: Allow libp2p user agent to be overriden

cmd/lotus-shed/eth.go, cmd/lotus-shed/main.go
This checks Eth API consistency by walking the chain backwards from HEAD and verifying that all data returned from eth_getBlockByNumber is consistent with eth_getBlockByHash. This helps us debug Eth JSON-RPC endpoint inconsistencies re: tipset CID.
=> add a lotus-shed eth check-tipsets command.

itests/kit/evm.go
We no longer use the nonce here.
=> itests: remove dead code from DeployContract

chain/types/ethtypes/eth_types.go, lib/must/must.go, node/impl/full/eth.go
Fixes https://github.com/filecoin-project/lotus/issues/10176
Fixes https://github.com/filecoin-project/lotus/issues/10183
=> fix: ethtypes: Correct 'no uncles' hash in NewEthBlock

itests/fevm_test.go
=> style: test: clean fevm recursive delegate call count test

blockstore/splitstore/markset_badger.go, node/repo/fsrepo.go, system/io.go
Without doing this a badger markset on a non-nvme gets into so much I/O wait that it knocks a node hopelessly out of sync.
=> fix: extend LOTUS_CHAIN_BADGERSTORE_DISABLE_FSYNC to the markset

chain/types/message.go
This is a no-op, since we already compare against minGas, but we might as well make it explicit.
=> chain: explicitly check that gasLimit is above zero

cmd/lotus-miner/sectors.go, documentation/en/cli-lotus-miner.md
Fix https://github.com/filecoin-project/lotus/issues/5349
Add the option to specify set-seal-delay in seconds
=> fix: cli: option to set-seal-delay in seconds

cmd/lotus-shed/balances.go, cmd/lotus-shed/datastore.go, cmd/lotus-shed/deal-label.go, cmd/lotus-shed/diff.go, cmd/lotus-shed/export-car.go, cmd/lotus-shed/export.go, cmd/lotus-shed/fip-0036.go, cmd/lotus-shed/gas-estimation.go, cmd/lotus-shed/import-car.go, cmd/lotus-shed/invariants.go, cmd/lotus-shed/keyinfo.go, cmd/lotus-shed/main.go, cmd/lotus-shed/market.go, cmd/lotus-shed/migrations.go, cmd/lotus-shed/miner-peerid.go, cmd/lotus-shed/miner-types.go, cmd/lotus-shed/msig.go, cmd/lotus-shed/nonce-fix.go, cmd/lotus-shed/pruning.go, cmd/lotus-shed/splitstore.go, cmd/lotus-shed/terminations.go
Standardize how we pass in "path". Removes top-level env var, which could be overwritten by the default in the path variable declared in the individual functions. 
=> fix: shed: Standardize use of path flag

cli/backup.go
fix https://github.com/filecoin-project/lotus/issues/7028
Calling `lotus-miner backup` or `lotus backup` on a backup file which already exists corrupts the file.
Added check to see if a file with the same name already exists, and if it does error out explaining that another file name should be used. 
=> fix: cli: error if backup file already exists

cli/send.go
If f4 address is not sending to f4 or f0, tries to resolve the `to` address to and ID address. Otherwise the call will fail, because a message coming from an f4 address will get converted to an eth transaction, and f1, f2, f3 will not fit in 20 bytes.
=> feat: cli: allow value send from f4 to any address type

chain/store/messages.go, node/impl/full/eth.go, node/modules/ethmodule.go
Closes https://github.com/filecoin-project/lotus/issues/10044
Checks all messages from the top of the chain down to a specified height (no lower than the v10 upgrade) and adds any relevant transaction hash mappings to the database. This will allow us to get transaction hash mappings when we import snapshots, or when users enable the feature for the first time.
=> feat: eth: populate tx hash database on startup

chain/types/ethtypes/eth_types.go, cli/evm.go
Closes https://github.com/filecoin-project/lotus/issues/9803
=> feat: eth cli: Strip out empty spaces around contract bytes

node/repo/blockstore_opts.go
This is a proposal for closing #9972. Happy to add docs or tests as needed.
- Include envvar `LOTUS_CHAIN_BADGERSTORE_COMPACTIONWORKERNUM` which accepts a non-negative int that configures the number of compaction workers for the badger blockstore
project/lotus/discussions/categories/tutorials)
=> feat: blockstore: Envvar can adjust badger compaction worker poolsize

cmd/lotus-worker/tasks.go, documentation/en/cli-lotus-worker.md
Reopening of: https://github.com/filecoin-project/lotus/pull/10203
CircleCI failed with `There was an infrastructure problem while running your tests` in some tests due to our settings changes earlier this week, and re-running the CI from start fail with the same error - so reopening the PR to mitigate it.
Add a all flag for the `lotus-worker tasks enable/disable` cmds.
=> fix: worker: add all tasks flag

chain/vm/gas.go, itests/fevm_test.go, itests/gas_estimation_test.go
https://github.com/filecoin-project/lotus/issues/10226
This fixes two issues:
1. We need to charge an additional 475,000 gas to update the sending actor.
2. We needed to update the FVM as it was miscalculating the inclusion cost.
I've also removed all the other fees from the price list as they don't make sense anymore.
=> fix: gas: update ffi & correct the message inclusion cost in nv18

chain/messagesigner/messagesigner.go, node/impl/full/wallet.go
Don't call WalletExport just to get key type
Calls to WalletExport breaks remote wallets, looks really bad in interactive wallets, and probably also breaks ledger wallet.
=> fix: Don't call WalletExport in msg signing flows

chain/stmgr/call.go, itests/wdpost_dispute_test.go
Should fix https://github.com/filecoin-project/ref-fvm/issues/1648.
Specifically re-execute all messages in the current tipset, tacking the new message onto the end. That way, the epoch is the epoch of the current tipset.
We could try to "make" a fake block and use that, but that's unlikely to work well.
=> fix: stmgr: make the tipset and height agree when estimating gas

chain/types/ethtypes/eth_transactions.go, itests/eth_account_abstraction_test.go, itests/fevm_test.go, itests/kit/evm.go, node/impl/full/eth.go
We now only accept two methods on delegated signatures:
- `EAM#CreateExternal` on contract deployment.
- `EVM#InvokeContract` otherwise.
Support for bare sends (method 0) via Eth messages has been dropped, so as to always trigger smart contract logic via `EVM#InvokeContract`.
This PR also adds a test to verify that's the case.
Next week, we should look at cleaning up and consolidating EVM tests. They have grown organically, many private utility functions have sprouted here and there that belong in the itests kit, and I'm not happy with how we're using time to poll for transaction receipts (even though that's how Ethereum tools do it, so in theory it's the most realistic way of testing).
- example: ` fix: mempool: Introduce a …
=> eth: FIP-0055: implement final version of transitory delegated signature.

chain/types/ethtypes/eth_transactions.go, itests/eth_fee_history_test.go, node/impl/full/eth.go, node/impl/full/eth_test.go
https://github.com/filecoin-project/lotus/issues/10236
=> Eth JSON-RPC: populate reward in eth_feeHistory

chain/stmgr/call.go
Otherwise we may, e.g., try to estimate gas on a message to an f4 address before the nv18 migration.
I'm _not_ checking the "prior messages" here as this is just a sanity check.
=> fix: stmgr: check message validity before invoking vm

chain/stmgr/call.go
Reverts https://github.com/filecoin-project/lotus/commit/2bbd1fbbb610645650bc439abb2984f8c38ded61 which introduced a regression:
```
Error: Returned error: failed to estimate gas: gas estimation failed: CallWithGas failed: message not valid for network version 19: 'Value' cannot be nil
```
=> Revert "fix: stmgr: check message validity before invoking vm"

itests/eth_filter_test.go, node/impl/full/eth.go
=> feat: ethrpc: Support newPendingTransactions in eth_subscribe

chain/events/filter/index.go
We merged https://github.com/filecoin-project/lotus/pull/10085 without a migration, so the event database will contain both cbor and non-cbor values. We need to handle that.
=> fix: events: handle pre-decoded events in migration

chain/events/filter/index.go
This fixes the slow event index v1=>v2 migration by:
* Adding temporary indices on the value and the event_id.
* Matching on value, event_id, and key when updating entries.
It also warns and moves on when we fail to update an entry.
~5 seconds to migrate 230k entries from an event database that has accumulated events since genesis over various network versions.
```
2023-02-15T13:03:40.585Z	WARN	event_index	filter/index.go:495	[migration v1=>v2] processing values
2023-02-15T13:03:40.597Z	WARN	event_index	filter/index.go:538	[migration v1=>v2] processed values	{"count": 500}
2023-02-15T13:03:40.607Z	WARN	event_index	filter/index.go:538	[migration v1=>v2] processed values	{"count": 1000}
2023-02-15T13:03:40.618Z	WARN	event_index	filter/index.go:538	[migration v1=>v2] processed values …
```
=> hyperspace: event index v1=>v2 speed up migration.

cmd/lotus-shed/balances.go, cmd/lotus-shed/datastore.go, cmd/lotus-shed/deal-label.go, cmd/lotus-shed/diff.go, cmd/lotus-shed/export-car.go, cmd/lotus-shed/export.go, cmd/lotus-shed/fip-0036.go, cmd/lotus-shed/gas-estimation.go, cmd/lotus-shed/import-car.go, cmd/lotus-shed/invariants.go, cmd/lotus-shed/keyinfo.go, cmd/lotus-shed/main.go, cmd/lotus-shed/market.go, cmd/lotus-shed/migrations.go, cmd/lotus-shed/miner-peerid.go, cmd/lotus-shed/miner-types.go, cmd/lotus-shed/msig.go, cmd/lotus-shed/nonce-fix.go, cmd/lotus-shed/pruning.go, cmd/lotus-shed/splitstore.go, cmd/lotus-shed/terminations.go
@rjan90 reported that many shed commands weren't working. The issue is the repo flag not being set.
Revert #10134. We can cleanup the omnipresent --repo flags later.
=> fix: shed: default to LOTUS_PATH for repo

cmd/lotus-miner/sectors.go, documentation/en/cli-lotus-miner.md
Make sector checks run in parallel
```
pre
./lotus-miner sectors list  31.82s user 1.64s system 59% cpu **56.525 total**
./lotus-miner sectors list --fast  34.44s user 1.97s system 329% cpu **11.060 total**
post
./lsm sectors list  15.59s user 1.72s system 248% cpu **6.971 total**
./lsm sectors list --fast  11.24s user 2.76s system 784% cpu **1.785 total**
```
=> sp cli: make sectors list much faster

cmd/lotus-shed/sectors.go
Adds a tool to extract data from sectors from a running lotus-miner deployment. This connects to the storage subsystem much like boost would for retrievals and reads raw pieces.
I wanted to debug why some of my deals failed to get indexed by dagstore, but extracting data from sectors was not easy, so I built this tool.
Apparently my deal was all null bytes somehow
=> feat: shed: Add a tool to read data from sectors

itests/fevm_test.go, node/impl/full/eth.go
fixes https://github.com/filecoin-project/ref-fvm/issues/1621
(probably)
Correctly decode actor output in EthGetStorageAt, and test it.
Also:
1. Actually use the passed block param.
2. Check if the target actor is an EVM actor to avoid nonsense outputs.
=> fix: eth: correctly decode EthGetStorageAt output

itests/fevm_test.go, node/impl/full/eth.go
Return revert data on failed gas estimation.
Unfortunately, we need to execute the message twice to get this (unless we want to change some APIs). But it's unlikely to be a performance issue and will definitely help people debug failures.
=> feat: eth: return revert data on failed gas estimation

Makefile, build/actors/pack.sh, gen/bundle/bundle.go
https://github.com/filecoin-project/lotus/issues/10185#issuecomment-1422864836
add support for overrides 
=> fix: pack: support network name overrides in bundle git tags

chain/actors/builtin/evm/actor.go.template, chain/actors/builtin/evm/evm.go, chain/actors/builtin/evm/state.go.template, chain/actors/builtin/evm/v10.go, itests/eth_bytecode_test.go, node/impl/full/eth.go
fixes https://github.com/filecoin-project/lotus/issues/10255
In EthGetTransactionCount, get the "correct" nonce for EVM contracts in case someone is using this method to, e.g., predict CREATE addresses.
EVM contracts track this number internally.
=> fix: eth: return the correct nonce from EthGetTransactionCount

itests/specs/eth_openrpc.json
Ethereum JSON-RPC responses should not include leading zero in hex #10170
change Filter in the eth json rpc spec from int to hash
=> fix: test: change Filter rpc type from uint to hash to match fevm implementation

cli/evm.go
ACTOR not found is a scary message we dont wanna show people for a util cli 😉
=> chore: ux: avoid actor not found

node/impl/full/eth.go
Cleanup some error cases:
1. Return an error on gas estimation failure instead of logging.
2. Return early when processing signed messages on failure instead of
continuing.
@travisperson any reason to not return an error when `ethGasSearch` fails?
=> fix: eth: cleanup error cases

chain/consensus/filcns/upgrades.go, cmd/lotus-shed/migrations.go
Updates the shed tester to work on the nv18 migration.
- Update shed
- Move the pre-migration up to start 30 minutes before the upgrade 
=> feat: shed: test the nv18 migration

itests/fevm_test.go, itests/kit/evm.go
fixes https://github.com/filecoin-project/ref-fvm/issues/1670
We have a test that triggers smart-contract logic on "transfers", but nothing that tries to create a new actor as a side-effect of a transfer.
=> test: eth: make sure we can deploy a new placeholder on transfer

api/proxy_gen.go, gen/api/proxygen.go, itests/deals_partial_retrieval_dm-level_test.go
This fixes some errors caught by `go vet`.
1. Fixes some lints that were previously being ignored (because `go vet` doesn't actually have a built-in way to ignore errors).
2. Fixes the formatting of multiple JSON-RPC API struct tags.
However, I'm not sure why this matters and/or why we even have this tag.
=> fix: eth: eth_subscribe tag

chain/stmgr/forks.go, chain/stmgr/forks_test.go
Setting the environment variable `LOTUS_DISABLE_PRE_MIGRATIONS=1` will discard premigrations for all upgrade.
#10048
- Add environment variable `LOTUS_DISABLE_PRE_MIGRATIONS` which when set to `1` stops pre-migrations from being executed.
- Migrations are still scheduled and part of the statement managers' migration table.
=> feat: stmgr: add env to disable premigrations

cmd/lotus-miner/allinfo_test.go, cmd/lotus-miner/info_all.go
=> fix: tests: Fix TestMinerAllInfo test

node/impl/full/gas.go
#10329
Overestimate gas around the Hygge upgrade based on the projected increases in https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0057.md#product-considerations.
We don't underestimate where costs have decreased in order to be safe (this is only a 10 minute window).
=> feat: gas: overestimate around the Hygge upgrade

chain/types/ethtypes/eth_types.go, cli/send.go, cli/send_test.go
In the `lotus send` cli, replace method 0 with InvokeEVM when the sender is an ethereum-style account.
This will make `lotus send` "work", mostly. However, there are some
caveats:
1. Sending to, e.g., a storage provider will still fail (doesn't implement InvokeEVM).
2. We're changing the method number specified by the user.
3. This will end up running code.
=> fix: cli: send with InvokeEVM when sending from an eth account

itests/eth_balance_test.go, node/impl/full/eth.go
@raulk observed that some tooling was taken longer than expected to update balance. This is because the current EthBalance implementation uses the _parent_ state of the input tipset, which is inconsistent with the Tipset <-> blockParam mapping we have.
- Use the `TipsetState` of the input param
- I considered extracting this into some helper, but there isn't any other use case of it (nor is it needed anywhere else in the EthAPI), and I think it'll confuse usage with the existing `LoadActor` methods.
- Add a test
- `area`, e.g. api, chain, state, market, mempool, multisig, …
=> fix: EthGetBalance: lookup balance at correct state

cmd/lotus-worker/main.go, documentation/en/cli-lotus-worker.md, documentation/en/default-lotus-miner-config.toml, node/config/def.go
fixes #9074
Tuning down the default post-parallel-reads to a conservative number. Seems more beneficial to be conservative here, and not cause any network timeouts, ending up in sectors being skipped. SPs can fine tune this value higher if their architectures can handle it.
=> fix: post: Tune down default post-parallel-reads

cmd/lotus-worker/cli.go, documentation/en/cli-lotus-worker.md
Based on the discussion in #10210
Hide the `lotus-worker wait-quiet` cmd from the lotus-worker cli to prevent user confusion around its functionality, and print that the cmd will be deprecated in the future.
=> fix: worker: Hide `wait-quiet` cmd

cmd/lotus-miner/info.go
Closes https://github.com/filecoin-project/lotus/issues/10362
=> chore: Remove legacy market info from lotus-miner info

chain/actors/builtin/verifreg/actor.go.template, chain/actors/builtin/verifreg/state.go.template, chain/actors/builtin/verifreg/v0.go, chain/actors/builtin/verifreg/v10.go, chain/actors/builtin/verifreg/v2.go, chain/actors/builtin/verifreg/v3.go, chain/actors/builtin/verifreg/v4.go, chain/actors/builtin/verifreg/v5.go, chain/actors/builtin/verifreg/v6.go, chain/actors/builtin/verifreg/v7.go, chain/actors/builtin/verifreg/v8.go, chain/actors/builtin/verifreg/v9.go, chain/actors/builtin/verifreg/verifreg.go, cmd/lotus-miner/sectors.go, documentation/en/cli-lotus-miner.md
#9369 
As described in https://github.com/filecoin-project/lotus/issues/9369#issuecomment-1434759702
=> feat: update renew-sectors with FIP-0045 logic

node/impl/full/eth.go
Wany on Slack reported that trying to eth_getBlockByNumber on hyperspace #124390 incorrectly returned empty values. This was because we have silent failures in `newEthBlockFromFilecoinTipSet`, which gives up and returns empty blocks with no errors if message lookups fail.
- Use `StateCompute` on the relevant tipset, instead of `StateSearchMsg`ing every message which would be very slow and potentially fail
- Stop silently succeeding on any error case
=> fix: EthAPI: Make newEthBlockFromFilecoinTipSet faster and correct

cmd/lotus-worker/cli.go, documentation/en/cli-lotus-worker.md
Fixes #10210, Fixes #7866
Based on the discussion in #10210 and in #7866, I propose to hide this command and start the deprecation process of this function.
The desired feature from our users point of view will be fulfilled by the `lotus-worker tasks enable/disable`, which allows SPs to gracefully shutdown the lotus-worker even with incoming sealing tasks:
1. SP have a lot of incoming sealing tasks in the pipeline, but want/need to shut down worker nr.124 for maintainence/upgrade
2. Issue the `lotus-worker tasks disable --all`, and let the remaining sealing tasks finish and let other workers fetch the finished sectors.
3. `lotus-worker stop` to detach it and do maintenance/upgrades.
A follow up here is to document how to gracefully shutdown a lotus-worker to our users: …
=> fix: cli: Hide `lotus-worker set` command

itests/eth_api_test.go, node/impl/full/eth.go
#10385 
The previous implementation was trying to _load_ the tipset that is the genesis's parents, which is both wrong and unnecessary. Simplifing fixes #10385.
=> fix: EthAPI: Correctly get parent hash

itests/kit/ensemble.go, itests/kit/rpc.go, itests/worker_test.go, storage/sealer/manager_post.go, storage/sealer/sched_post.go
Fixes https://github.com/filecoin-project/lotus/issues/9854
* Add an itest reproducing 9854
* Don't schedule PoSt on disabled workers
* If there is an RPC connection error coming from a call to a worker, retry on another worker instead of failing the whole PoSt
Could use testing on a real setup
=> fix: wdpost: disabled post worker handling

chain/consensus/compute_state.go, chain/stmgr/execute.go
@magik6k observed that the recently added TestEthGetGenesis is flaky. The cause is that our state computation of the first epoch needs short-circuiting to handle certain special-casing (eg. a WinCount of 0).
This special-casing already exists, but lived one level too high for tooling like `StateCompute`. Moving it down one level fixes the issue.
=> fix: state: short-circuit genesis state computation

.github/ISSUE_TEMPLATE/config.yml
Part of https://github.com/filecoin-project/lotus/issues/10242
In our current issue flow, we ask a lot checklist questions in our bug reports:
```
- This is not a question or a support request. If you have any lotus related questions, please ask in the lotus forum.
- This is not a new feature or an enhancement to the Filecoin protocol. If it is, please open an FIP issue. *
```
While they are there to guide people to the right place for troubleshooting/questions, they make our Issue template very text dense and complex. 
This information can instead be displayed in the `New Issue` chooser which has better UI, and will link users to the relevant place for posting. This file will add two new entries in the issue chooser:
- A entry that links to the Lotus Github Discussion page for Lotus …
=> fix: github: Discussion and FIP links in `New Issue`

.github/ISSUE_TEMPLATE/bug_report.yml
Part of #10242 
Update bug_report template:
- Removing unnecessary checklist options.
- These have been move to the Github `New Issue` UI to reduce text overhead #10268 
- Remove deprecated components options
- Add FVM/FEVM component
=> chore: github: Update bug_report template

.github/ISSUE_TEMPLATE/service_developer_bug_report.yml
Closes #10242 
Adds a service provider / FEVM-developer bug report template in preperation for network version 18. The template is requesting more relevant information regarding their tooling, etc, compared to the general bug report.
=> chore: github: Service-provider/dev bug template

lib/rpcenc/reader.go, lib/rpcenc/reader_test.go
Fixes https://github.com/filecoin-project/lotus/issues/10201
* Make the test reproduce the original issue with near ~100% reliability
* Fix the edge-case
* Update the test to deal with racy behavior correctly
* `beginPost` "transforms" the virtual reader into a real one after the first call to Read
* `TestReaderRedirectDrop` tests what happens when the connection from the client to the redirecting node drops juuust before the redirecting node attempts to call a target node with a redirected reader
* There appears to be a race between the redirected stream being accepted/consumed on the decoding end, and the redirect logic noticing that the stream that we have just tried to redirect was closed.
* Fixing that would require a lot of hacky instrumentation, so for now the test accepts both, …
=> fix: rpcenc: deflake TestReaderRedirectDrop

storage/pipeline/fsm.go
Fixes https://github.com/filecoin-project/lotus/issues/9968
* Don't log stuff to removed sectors logs
* Shutdown statemachines for removed sectors
* Add an envvar to keep removed sector FSMs running - `LOTUS_KEEP_REMOVED_FSM_ACTIVE`, this makes it possible to move sectors out of the Removed state with update-state in the extremely unlikely case when that's needed.
Could use testing
=> fix: fsm: shutdown removed sectors FSMs

itests/eth_fee_history_test.go, node/impl/full/eth.go, node/impl/full/eth_test.go
https://github.com/filecoin-project/lotus/issues/10393
https://github.com/filecoin-project/lotus/issues/10414
1. use StateCompute instead of StateSearchMsg for feeHistory
2. return MinGasPremium when there's no tx in the block
=> fix: EthAPI: use StateCompute for feeHistory; apply minimum gas premium

storage/sealer/manager.go, storage/sealer/sched.go, storage/sealer/sched_assigner_common.go, storage/sealer/sched_assigner_darts.go, storage/sealer/sched_assigner_spread_tasks.go, storage/sealer/sched_assigner_utilization.go, storage/sealer/sched_resources.go, storage/sealer/sched_test.go, storage/sealer/sched_worker.go, storage/sealer/sealtasks/task.go, storage/sealer/stats.go, storage/sealer/storiface/worker.go
Currently lotus-miner can be configured with one of two assigners:
* `utilization` (default) - For each task pick a worker with a lowest 'utilization factor', which is based on ratios of compute resources
* `spread` - In each assign loop try to assign to a worker with least tasks assigned so far
This PR adds a few experimental assigners:
* `experiment-spread-qcount` - Like spread, but also takes into account task counts which are running/preparing/queued
* `experiment-spread-tasks` -  Like spread, but counts running tasks on a per-task-type basis
* `experiment-spread-tasks-qcount` - The two above combined - count running tasks grouped by task type, also takes into account tasks which are running/preparing/queued
* `experiment-random` - In each schedule loop figure a set of all workers …
=> feat: sched: Assigner experiments

cmd/lotus-miner/proving.go
https://github.com/filecoin-project/lotus/issues/8561
=> chore: make debugging windowPoSt-failures human readable

node/impl/full/eth.go
#10403 , thanks to @wanyvic for the report!
We're skipping system messages from the list of transactions returned, but not adjusting the txIdx accordingly. This is only noticed when the previous round was a null tipset.
Adjust for skipped system messages.
Bug introduced in #10380.
=> fix: eth API: return correct txIdx around null blocks

documentation/en/default-lotus-config.toml, node/config/def.go
Enable splitstore discard mode as default node configuration
=> feat:splitstore:Splitstore enabled by default

blockstore/splitstore/splitstore.go, blockstore/splitstore/splitstore_check.go, blockstore/splitstore/splitstore_compact.go, blockstore/splitstore/splitstore_gc.go, blockstore/splitstore/splitstore_reify.go, documentation/en/default-lotus-config.toml, node/config/def.go, node/config/doc_gen.go, node/config/types.go, node/modules/blockstore.go
#10388 
* Add size reporting to chain walking subfunctions
* Record sizes of the different DAGs walked during compaction
* New config value for targeting max total space used by hotstore
* GC logic to trigger moving GC adaptively based on hotstore size 
* Most importantly: splitstore refuses to do moving GC if disk usage would overflow the targetted max
=> feat:splitstore:Configure max space used by hotstore and GC makes best effort to respect

chain/gen/gen.go, chain/stmgr/forks.go, chain/stmgr/forks_test.go, chain/stmgr/stmgr.go, chain/store/store_test.go, cmd/lotus-bench/import.go, cmd/lotus-shed/balances.go, cmd/lotus-shed/gas-estimation.go, cmd/lotus-shed/invariants.go, cmd/lotus-shed/migrations.go, cmd/lotus-shed/state-stats.go, cmd/lotus-sim/simulation/node.go, cmd/lotus-sim/simulation/simulation.go, cmd/lotus/daemon.go, conformance/driver.go, node/modules/chain.go, node/modules/stmgr.go
#10048
- Cache migration results to avoid running migrations twice when making calls that execute an upgrade epoch
=> feat: stmgr: cache migrated stateroots

chain/store/index.go
@jennijuju   flagged that we need faster fetching of tipsets by height for Eth tooling support.
- Increase the skipcache size to 2^20 entries
- Drop the tipset itself from the skipcache entries. This is a lot of information to hold in memory that we don't actually need.
- Drop the parentHeight from the skipcache entries. This is just 8 bytes, but I don't think we need it.
- With that, we can easily rely on the skip cache to load 20 million epochs (so good until 2040).
- Each cache entry itself is ~308 bytes (an int64 + a TSK, using ~5 CIDs per TSK, which is aggressive), which means the total cache size when we get to 20M epochs will be ~0.3 GiB.
- `PR type`: …
=> feat: chain: make chain tipset fetching 1000x faster

cli/evm.go, documentation/en/cli-lotus.md
Add a CLI command to fetch a contract's bytecode:
```
lotus evm bytecode 0x....
```
Happy to rename to `get-bytecode`, or something else.
=> feat: cli: Add an EVM command to fetch a contract's bytecode

chain/types/ethtypes/eth_types.go, chain/types/ethtypes/eth_types_test.go
We'll never get an actor/account deployed to one of these addresses (although we might get a placeholder). However, converting such an address to an f4 address is definitely wrong.
=> feat: eth API: reject masked ID addresses embedded in f410f payloads

chain/stmgr/execute.go, chain/types/tipset.go
Instead of always executing the tipset inside `StateManager.TipSetState`, try to find a successor tipset and return the parent state & receipts as recorded.
=> feat: state: skip tipset execution when possible

chain/store/messages.go, chain/types/ethtypes/eth_transactions.go, chain/types/message.go, itests/eth_block_hash_test.go, itests/eth_conformance_test.go, node/impl/full/chain.go, node/impl/full/eth.go, node/impl/full/eth_test.go
The current implementations of eth_getBlock* and eth_feeHistory have proven computationally expensive due to their usage of full tipset computations (`StateCompute`). This PR replaces the expensive logic with receipt lookups.
For eth_getBlock* and eth_feeHistory, instead of replaying the tipset:
1. Lookup the tipset receipts.
2. Load the receipts.
3. Calculate everything from there (we have the gas used, etc.)
This also removes support for the `pending` block parameter as it's impossible to handle it without forcing state computes, which are prohibitively expensive. The Eth community is evaluating a proposal to also remove it in their next fork, given its limited applications due to MEV and other reasons.
We've gone down from 10 seconds to various minutes (depending on the method and …
=> feat: eth: optimize eth block loading + eth_feeHistory

itests/eth_api_test.go, node/impl/full/eth.go
Fixes #10408.
Makes `net_version` return the chain ID in decimal string. Also, sdds a test.
=> fix: Eth API: make net_version return the chain ID.

gateway/proxy_fil.go
Folks were trying to use the chain.love gateway to get info about a msig's vesting funds, starting from genesis. This didn't work, because we guard on the start tipset (making sure it's within the last 24 hours).
There's no actual reason to guard on the start tipset, though -- we're not actually loading its state, just its height. We could honestly change this API to take a start height, it'd be better.
But the quick solution is just to drop the guard on the start tipset for the gateway.
- `area`, e.g. api, chain, state, market, mempool, multisig, networking, paych, proving, …
=> gateway: fix: drop overzealous guard on MsigGetVested

node/impl/full/eth.go
fixes #10418
Instead:
1. Use the receipt from the message search.
2. Re-compute the gas fees that would have been charged.
=> feat: eth: Avoid StateCompute in EthTxnReceipt lookup

itests/kit/blockminer.go
I've been seeing quite a few tests failing here, so I'm hoping this will deflake them a bit.
=> fix: itest: avoid failing the test when we race the miner

chain/badtscache.go, chain/beacon/drand/drand.go, chain/block_receipt_tracker.go, chain/events/message_cache.go, chain/messagepool/messagepool.go, chain/store/messages.go, chain/store/store.go, chain/sub/incoming.go, cmd/lotus-shed/state-stats.go, go.mod, go.sum, miner/miner.go, miner/testminer.go, node/impl/full/gas.go, storage/paths/localstorage_cached.go, tools/stats/ipldstore/ipldstore.go, tools/stats/points/collect.go
- Adds type safety.
- Reduces allocations.
- ~Fixes the drand cache (was storing by value, but retrieving by pointer)~ (steven can't read)
=> refactor: update cache to the new generic version

chain/stmgr/execute.go
Fixes a regression introduced in https://github.com/filecoin-project/lotus/pull/10445
Don't attempt to get genesis state by walking back to it.
I've noticed that with latest master my mainnet nodes are taking a really long time to start syncing after startup. One splitstore node took 2 hours (!) to begin the process.
This appears to have been caused by trying to get genesis state for the vesting schedule:
```
goroutine 13001085 [semacquire]:
sync.runtime_Semacquire(0xc0164e8680?)
/usr/lib/go/src/runtime/sema.go:62 +0x25
sync.(*WaitGroup).Wait(0xc015ed0501?)
/usr/lib/go/src/sync/waitgroup.go:139 +0x52
golang.org/x/sync/errgroup.(*Group).Wait(0xc01bee3e40)
/home/magik6k/.opt/go/pkg/mod/golang.org/x/sync@v0.0.0-20220907140024-f12130a52804/errgroup/errgroup.go:53 +0x27 …
```
=> fix: stmgr: don't attempt to lookup genesis state

chain/consensus/compute_state.go, metrics/metrics.go
Log applyblock stats
Those metrics can be very useful for more detailed gas / block time analysis. Today we only have prometheus metrics, which are bucketed, and not too accurate due to that, and the "block validation" log, which usually doesn't include state compute, which most of the time is pre-computed.
```
2023-03-14T10:16:59.748+0100    INFO    consensus-common        consensus/compute_state.go:496  ApplyBlocks stats       {"early": 0.00008036, "earlyCronGas": 0, "vmMsg": 2.428463637, "msgGas": 18247427215, "vmCron": 6.90146274, "cronGas": 126278836788, "vmFlush": 0.472160843, "epoch": "2682071", "tsk": "{bafy2bzacebyx3aten2gih4rokwrzg5qocalnllqslyu4xqvyqbu33hskjknos,bafy2bzacedvjoqkoj2utw3d5cyhb4bw4csrrkftdaf5mc3my54g3j77ots6oe,bafy2bzacedvr6fw3ctyiwrfdt65l65s3ybqf6t …
```
=> feat: consensus: log ApplyBlock timing/gas stats

blockstore/badger/blockstore.go, blockstore/blockstore.go, blockstore/buffered.go, blockstore/discard.go, blockstore/idstore.go, blockstore/mem.go, blockstore/net.go, blockstore/splitstore/splitstore.go, blockstore/splitstore/splitstore_expose.go, blockstore/splitstore/splitstore_test.go, blockstore/sync.go, blockstore/timed.go, blockstore/union.go
Allow any blockstore to induce a `Flush()`/`fsync()` on any underlying storage regardless of amount of indirection.
=> chore: blockstore: Plumb through a proper Flush() method on all blockstores

gateway/node.go, gateway/proxy_eth.go
Related to #10412. This issue wasn't mentioned there because it's technically restricted already, just not as restricted.
This fix ensures that the full fee-history range falls into the allowable lookback rang.
=> fix: gateway: correctly apply the fee history lookback max

go.mod, go.sum
Fixes a memory leak; see https://github.com/libp2p/go-libp2p-pubsub/releases/tag/v0.9.3
=> deps: update go-libp2p-pubsub to v0.9.3

chain/stmgr/execute.go
Backports https://github.com/filecoin-project/lotus/pull/10472 into v1.21.0
=> backport #10472 to v1.21.0 

go.mod, go.sum, node/impl/full/eth.go
Fixes https://github.com/filecoin-project/lotus/issues/10484
Brings in https://github.com/filecoin-project/go-jsonrpc/pull/98
* Bring a fix for jsonrpc reverse client hang on closed connections
* Buffer eth_subscribe messages if the subscriber is slow
* Always uninstall sub-related filters when the sub dies, not only when it's explicitly cancelled
=> fix: ethrpc: Don't lock up when eth subscriber goes away

node/impl/full/eth.go
This reverts commit 9412753ba33c4bba7dd5df34a1cd5f9a34464e4f.
Some tools require `pending` support on some RPCs, concretely `eth_getTransactionCount`. This backs out the patch that generally dropped such support, in case we want to restore master to working condition while https://github.com/filecoin-project/lotus/pull/10462 is being reviewed.
Re-introduce `pending` block support.
=> fix: revert "Eth API: drop support for 'pending' block parameter."

node/impl/full/eth.go
fixes #10471
This isn't really possible to hit on-chain at this piont (message won't be accepted) but we might as well be extra careful.
- Kind of annoying to test as lotus will reject the message.
=> fix: eth: handle a potential divide by zero in receipt handling

blockstore/splitstore/splitstore_compact.go
#10492 also breaks compaction since we were enforcing full receipt tree walk
For now walk object incomplete on receipts always 
thanks @ribasushi for brining this one up
=> fix:splitstore:Don't enforce walking receipt tree during compaction

cmd/lotus-miner/config.go, cmd/lotus-miner/init_restore.go, cmd/lotus/backup.go, cmd/lotus/config.go, documentation/en/default-lotus-config.toml, node/config/load.go, node/config/load_test.go, node/repo/fsrepo.go, node/repo/fsrepo_test.go
This is the change to 1) force users to explicitly set splitstore config by uncommenting the default, 2) for new nodes do the uncommenting automatically so they will opt into the default automatically 
- Add a notion of uncommenting filters to config update.  Then apply a filter on EnableSplitstore in the default full node config
- Add a notion of loadability checks to the lotus config.  Then apply a check ensuring `#EnableSplitstore =` is not in the config to ensure that users with old configs will reset their config explicity.
- The patterns introduced here can hopefully be used in other sensative default change situations
- We can probably revert the splitstore specific filters and loadability checks in a few months when the community is adjusted to the new defaults 
Before you mark …
=> feat:config:force existing users to opt into new defaults

cmd/lotus-miner/info.go
`lotus-miner info` currently does not show deals info without admin permission.  This is similar issue to #8057.
Instead of return in `infoCmdAct()` when `WorkerStats()` fails, just print error and continue.
=> fix: state: lotus-miner info should show deals info without admin permission

node/modules/tracer/tracer.go, node/modules/tracer/tracer_test.go
The pubsub tracer emits traces in JSON format or posts JSON documents to an opensearch endpoint. The traces are a combination of libp2p-pubsub traces and a custom LotusTraceEvent, intermixed in the JSON stream. The libp2p traces use `[]byte` as the type for peer IDs which, in JSON, is base64 encoded. 
The LotusTraceEvent type uses a `string` for peer IDs (prettified) which is emitted as-is in the JSON.
However clients have no sensible way to distinguish the two encodings, the stream consists of a mix of the two representations:
```
{"type":11,"peerID":"ACQIARIgTM4a29NqIGdalfumxVWLOB6hZ4xm0ybAT4giXOe8/G4=","timestamp":1676302327478329014,"graft": ... 
{"type":100,"peerID":"12D3KooWEzBS8UbFGKaHGcksuteyq363zdfHCNB9ZrEzuHbWTyQy","timestamp":1676302331378019221,"peerScore ...
```
If a client …
=> fix: tracer: emit raw peer ids for compatibility with libp2p tracer

chain/stmgr/stmgr.go, chain/stmgr/supply.go
@jennijuju's goroutines reported that when trying to send many messages (or just create a lot of FVMs), this lock becomes contended for.
- Drop the check on `genesisMarketFunds`, which is zero on mainnet (confirmed)
- Only take the lock over the genesis multisigs when actually calculating vesting schedules, which _should_ happen once, but _was_ happening every time because `genesisMarketFunds` was equal to 0
=> feat: stmgr: speed up calculation of genesis circ supply

cmd/lotus-shed/chainwatch.go, cmd/lotus-shed/main.go
This just imports an extremely stripped down version of the lotus-chainwatch tool from testnet days, which makes it possible to look at block graphs including blocks which weren't synced.
Usage:
```bash
$ ./lotus-shed chainwatch run
$ ./lotus-chainwatch-simple dot > blocks.dot 2057234 2000 && dot blocks.dot -Tsvg -Grankdir=TB > blocks.svg
```
=> feat: shed: incoming block-sub chainwatch tool

chain/stmgr/call.go, chain/stmgr/forks_test.go, cmd/lotus-shed/gas-estimation.go, node/impl/full/eth.go, node/impl/full/gas.go
for optimization of eth rpc api calls, change CallWithGas to accept a parameter applyTsMessages that is passed to callInternal  with the same name. for gasEstimateCallWithGas change applyTsMessages = false and leave other invocations of callInternal with applyTsMessages = true
=> perf: eth: gas estimate set applyTsMessages false

cmd/lotus-miner/proving.go
Fixes #10564
Initialize the postParam.Partitions slice with the same length as i.Partitions before iterating over it in the loop.
Tested on a local net, and now it does not panic:
```
lotus-miner proving compute window-post 0
Took 1.781950251s
[
{
"Deadline": 0,
"Partitions": [
{
"Index": 0,
"Skipped": []
}
],
"Proofs": [
{
"PoStProof": 5,
"ProofBytes": "jTEZNQZRWjBRcpnOjyae10RtXnN0k8ALGYeenRLVpzdtBKTQiC+BdVlWdk1qehfarXYYWNE+ib9arhYRj4bmVnyA1xAOlLTzs81lEgW64g1tUOxTVaoBWj0sTPBQGEgbFsMB1vKrVkzBRkTUZU9ZWgaZYb59znxB7/ZrARVJw93hLwd3NRjZQvWNhj/JxfyVgaTuW9Uid2Hc2qIpoDrgKY9HRIQmmKTR9sSjYA3seX6B/6uBDI+/BoqaGJkOcOJc"
}
],
"ChainCommitEpoch": 0,
"ChainCommitRand": null
}
]
```
- example: ` fix: mempool: Introduce a cache for valid …
=> fix: proving: Initialize slice with with same length as partition

chain/stmgr/execute.go, chain/stmgr/stmgr.go
https://github.com/filecoin-project/lotus/issues/10504
This PR adds a small cache to calls to `ExecutionTrace` which helps improve performance for node operators like exchanges and block explorers.
If items is in cache calls to this function will be 2-3x faster. 
I ran a local test for 30minutes where I called `lotus state compute-state --json` in a loop from two threads. 
- Before this cache, each query took close to 8-10 seconds to run, but with this change it goes down to under 3 seconds.
- Cache hit rate was 82% (671/816)
NOTE: Stress testing this over an hour resulted in Lotus process residual memory taking almost 30GB, I am kind concerned that it grew this large and GC didn't kick in, so will continue to stress test this for longer. 
EDIT: Ran longer stress test, memory stayed flat …
=> feat: Add small cache to execution traces

chain/index/msgindex.go, cmd/lotus/daemon.go
Fixes: https://github.com/filecoin-project/lotus/issues/10537
After importing from snapshot this PR creates and populates the sqlite message index introduced in https://github.com/filecoin-project/lotus/pull/10452 from the 2k tipsets in the snapshot.
When loading from snapshot from mainnet, populating the message index takex approx 30 seconds. We should be able to lower this somewhat with bulk inserts (though doing it inside a transaction is at least an order of magnitude faster than not).
- `area`, e.g. api, chain, state, market, mempool, multisig, networking, paych, proving, …
=> feat: populate the index on snapshot import

chain/store/snapshot.go
#10492 
These commits improve error reporting during export-range so that users can easily pinpoint in which epoch and in which part of the export an error happens (particularly getting an error when reading a block to export).
Additionally, given there are references to never-written CIDs in Receipts (see linked issue), rather than aborting the export, it will just print a warning when these are found.  This is less strict than decoding receipts and only skipping EventRoot CIDs, but possibly achieves the same result without the complexity.
- `area`, e.g. api, chain, state, …
=> Fix: export-range: Ignore ipld Blocks not found in Receipts.

itests/batch_deal_test.go, itests/kit/blockminer.go
This is a probable cause for <s>a lot</s> maybe some of flakiness in all itests - https://github.com/filecoin-project/lotus/issues?q=is%3Aissue+is%3Aopen+label%3Aimpact%2Ftest-flakiness
When `miner.MineOne` returns an error, which can occasionally happen on normal test shutdown with unlucky timing (e.g. chain blockstore closed during a call to MinerGetBaseInfo while it is computing state), just log the error and quit.
Previously the call to t.Error could make the failure look very random as it is called in a goroutine, and may be called after the original calling (sub)test has already finished.
- `PR type`: fix, feat, build, chore, ci, docs, perf, refactor, …
=> fix: itests: Don't call t.Error in MineBlocks goroutine

Dockerfile, Dockerfile.lotus, README.md
Should fix #10578 
- Update Go-version in dockerfile
- Update Go-version in readme
=> build: docker: Update GO-version

chain/stmgr/searchwait.go
This commit fixes the `searchForIndexedMsg` so on success it returns a `nil` error value
See https://github.com/filecoin-project/lotus/issues/10326
=> fix: searchForIndexedMsg always returns an error

chain/stmgr/searchwait.go
https://github.com/filecoin-project/lotus/issues/10583
This commit enables the use for MessageIndex in StateWaitForMessage 
Start lotus node using calibration net
```
make clean calibnet
lotus daemon --import-snapshot /Users/fridrik/Downloads/calibnet/425760_2023_03_29T14_13_00Z.car --halt-after-import
lotus daemon
```
Printed out some messages in sqlite/messageindx.db
```
sqlite3 ~/.lotus/sqlite/msgindex.db
select * from messages order by epoch desc limit 10;
bafy2bzacedqe7fiaxloruetqxf2kfqsorvuhf27llu73vcwolfzfxtotmn2fk|bafy2bzacedioozngzfwlm6qojrqmrbke4evwrsvemeompjttl24gasclvkeqw|425855
bafy2bzacedjhywgkxclwvpbsn7alabrdrhif46bpdvzjyq3yywg7hk3rinfww|bafy2bzacea553srf777sxkkm4vl7fatmsvay3mftw734kxlygem2gsr4jhx2o|425854
bafy2bzacebmbn7syj65duanfehangmj2me6oi2h4fdv6353sg2fs5t5zzyq3g|bafy2b …
```
=> feat: Use MessageIndex in WaitForMessage

chain/consensus/compute_state.go, chain/gen/genesis/genesis.go, chain/gen/genesis/miners.go, chain/stmgr/call.go, chain/stmgr/forks_test.go, chain/stmgr/stmgr.go, chain/stmgr/utils.go, chain/vm/execution.go, chain/vm/vmi.go, conformance/driver.go
On top of https://github.com/filecoin-project/lotus/pull/10551
This implements the finegrained lock suggested by @Stebalien 
Honestly, I don't think finegrained locking is actually advantageous with our usage patterns, but not having to call `Done`  is a definite improvement safety-wise.
=> VM Execution Lanes Part II: Hide the lock

chain/messagepool/check.go, chain/messagepool/messagepool.go, chain/messagepool/repub.go, chain/messagepool/selection.go
should effect https://github.com/filecoin-project/lotus/issues/10538 because of message pool locks
message pool has two locks - change mp.lk and mp.curTsLk to RW locks for API efficiency 
=> perf: message pool: change locks to RWMutexes for performance

storage/paths/localstorage_cached.go
fixes: #9073 
Do not log 'file does not exist' errors when retrieving disk usage information. These errors are expected, as storage can be reserved before any files are written, and they were cluttering the logs unnecessarily.
=> fix: log: Stop logging `file does not exists`

cli/net.go
The error needs to be ignored if we successfully get the address from a miner actor. Looking at git blame I'm really unsure how this ever worked, or why it broke.
=> fix: cli: Make `net connect` to miner address work

go.mod, go.sum
=> chore: deps: update to go-state-types v0.11.0-alpha-3

go.mod, go.sum
Backports #10606 to v1.21.0
The claims loading methods were failing if the relevant SP wasn't found (fixed in https://github.com/filecoin-project/go-state-types/pull/181). This backport simply bumps the deps in v1.21.0
=> Backport #10606 to v1.21.0

cmd/lotus-miner/sectors.go
fixes: #6344 
Check if the sector exists before running `SectorRemove`, and error out if the SectorID has not been created to prevent issues where the user removes the state for a non existing sectors
=> fix: cli: Check if the sectorID exists before removing

cli/state.go
Fixes https://github.com/filecoin-project/lotus/issues/10617
Likely a regression after https://github.com/filecoin-project/lotus/pull/10372, plus there was another regression around error handling
=> fix: make state compute --html work with unknown methods

documentation/en/default-lotus-config.toml, node/config/def.go
Backports https://github.com/filecoin-project/lotus/pull/10605 to v1.21.0
Set splitstore max space config as default
=> Backport #10605 to v1.21.0

blockstore/badger/blockstore.go
Backports https://github.com/filecoin-project/lotus/pull/10621 to v1.21.0
The backported PR is a small subset of https://github.com/filecoin-project/lotus/pull/10392 which should make moving gc less likely to cause out of sync that is really safe without more testing time.
=> Backport #10621 to v1.21.0

blockstore/badger/blockstore.go
After recent fix #10392 *should* be fine but we just had a bug report that wasn't caught during test so let's let that change sit a little before incorporating in a release. 
However we do want to add configuration that makes moving GC more common to the release for better disk management.  This PR is a small subset of #10392 which should make moving gc less likely to cause out of sync that is really safe without more testing time.
=> feat:splitstore:limit moving gc threads

node/impl/full/gas.go
May fix @shrenujbansal's issue.
Technically, if a message is near the block gas limit, this method could over-estimate past the block gas limit. Instead, cap at the block gas limit.
=> fix: cap the message gas limit at the block gas limit

documentation/en/default-lotus-config.toml, node/config/def.go
#10580 
Set splitstore max space config as default 
This config value will bound total lotus hotstore space during moves between 500 - 650 GiB by default 
Reviewers should advise if this is too small / the resources needed for frequent moves is expected to be too burdensome 
We should probably land this alongside #10392 so that more frequent moving GCs have less impact on chain sync
=> feat:splitstore:Update config default value

chain/messagepool/selection.go
We have observed some very high buildup in the mpool, which cannot be cleared fast enough due to pruning cooldown.
This apparently results in messages selection taking too long (10-20s).
This attempts to resolve the issue by eagerly pruning (regardless of cooldown) before selecting, when we have excess messages.
=> fix:mpool: prune excess messages before selection

build/bootstrap/butterflynet.pi, build/params_calibnet.go, chain/consensus/filcns/upgrades.go
=> chore:release:update butterfly artifacts and set calibration upgrade heights

build/bootstrap/butterflynet.pi, build/params_2k.go, build/params_butterfly.go, chain/consensus/filcns/upgrades.go
=> Quick butterfly upgrade to sanity check

build/bootstrap/butterflynet.pi, build/params_calibnet.go, chain/consensus/filcns/compute_state.go, cmd/lotus-shed/market.go, cmd/lotus-shed/miner.go
RC3
- Register v11 actors so state read-state commands will work among other things
- Update calibration to happen 4-20 16:30 UTC
- Add shed inspection commands of SI and market cron used to confirm butterfly state and useful for calibration 
=> chore:releasepolish v1.22 release

go.sum
I incorrectly pinned an FFI dependency that relies on non-stable FFI master.  This would likely cause trouble for v1.20.x nodes to update to v1.22.x.  This PR pins the correct FIP 0061 changes on top of stable ffi.
=> fix:deps:stable ffi for stable release 

storage/sealer/manager.go
fixes: #10222 
Check if `storiface.FTSealed` or `storiface.FTUpdate` sector exists when `SectorsUnsealPiece` is called, and fail if they are not present.
```
lotus-miner storage find 111
In 94f8a49e-1208-442d-b960-9c6fca5ec2a0 (Cache)
Sealing: true; Storage: true
Local (/root/.lotus-miner-local-net)
URL: http://127.0.0.1:2345/remote/cache/s-t01000-111
```
```
lotus-miner sectors unseal 111
ERROR: sealed or updated sector file not found for sector {1000 111}
```
=> fix: unseal: check if sealed/update sector exists

chain/consensus/iface.go
Technically, the block validator caught this panic. But it's pointless because we have a _real_ mechanism to return the validation reason, which we should have been using.
In general, panicing like this is a very bad idea because it's non-obvious and, in this case, completely undocumented.
=> fix: remove pointless panic

node/impl/full/gas.go, storage/pipeline/commit_batch.go, storage/pipeline/commit_batch_test.go, storage/pipeline/mocks/api.go, storage/pipeline/mocks/mock_commit_batcher.go, storage/pipeline/mocks/mock_precommit_batcher.go, storage/pipeline/precommit_batch.go, storage/pipeline/precommit_batch_test.go, storage/pipeline/sealing.go, storage/pipeline/utils.go
https://github.com/filecoin-project/lotus/issues/10612
=> feat: sealing: Split PCA/PCB batches if gas used exceeds block limit

go.mod, go.sum
Towards #10717
Update to the final version of go-state-types we want to use.
=> chore: deps: update to go-state-types v0.11.1

chain/messagepool/messagepool.go, chain/messagepool/messagepool_test.go, chain/messagepool/provider.go
Fixes: https://github.com/filecoin-project/lotus/issues/10538
**Context**
We have observed that `EthGetTransactionCount` is one of the hotspots on Glif production notes, and we are seeing regular 10-20 second latencies when calling this rpc method. We have also been able to replicate this issue on local nodes on our devboxes on mainnet when calling this method repeatedly.
**The fix**
I tracked the high latency spikes and they were correlated when we were running ExecuteTipSet while following the chain.
To address this, we should not rely on tipset computation to get nounce and instead look at the parent tipset and then count the messages sent from the 'addr' as suggested by steb.
**Test plan**
I started and synced my lotus node on mainnet and started calling  `EthGetTransactionCount` rpc …
=> perf: Address performance of EthGetTransactionCount 

chain/store/snapshot.go
We have to save raw blocks to the snapshot, but we should not be scanning them for additional links as if they were CBOR blocks.
This cleans the logic a bit (we were checking that the parent was a CBOR block before queueing up the children, but then scanning the children... it was weird).
Additionally, more verbose logging is added for the next time ScanForLinks fails (currently very little info was given).
Our ScanForLinks callback should only enqueue CBOR for further processing.
#10672 
Fixes raw blocks being scanned for links as if they were CBOR.
- `area`, e.g. api, chain, …
=> chainstore: Fix raw blocks getting scanned for links during snapshots

chain/consensus/filcns/filecoin.go, chain/consensus/iface.go, chain/sync.go
This will reject blocks in pubsub validation if they're either:
1. Too far into the future (5 blocks beyond the expected head).
2. Too far into the past (before finality).
Specifically:
1. We were previously rejecting future blocks in the sync logic, but not in pubsub itself.
2. We never used to check if a block was too _old_.
Motivation: Blocks that are too new/too old can cause us to perform quite a bit of unnecessary work.
We should carefully consider that second check as we may need to tweak it (e.g., to handle network issues?). We may want to base this check on the latest synced head, not the _expected_ epoch.
- `PR type`: fix, feat, build, chore, ci, …
=> feat: sync: validate (early) that blocks fall within range

itests/wdpost_test.go
=> feat: Update FFI, test disputing nv20 window posts fails 

chain/types/message.go, node/impl/full/eth_test.go
https://github.com/filecoin-project/lotus/issues/10604
Use 0 as reward if gasFeeCap is less than baseFee
=> fix: Eth JSON-RPC api: handle messages with gasFeeCap less than baseFee

cmd/lotus-shed/market.go
This command isn't the Lotus-y-est way to do this.
Refactor to be a bit more canonical (mostly intended as a demontstartion).
=> feat: shed: refactor market cron-state command

cmd/lotus/daemon.go, lib/httpreader/resumable.go
Closes https://github.com/filecoin-project/lotus/issues/10618
Happens a lot on my internet, and was starting to get really annoying
=> feat: daemon: Auto-resume interrupted snapshot imports

storage/paths/remote.go
This fixes an issue where partially fetched files would be left in fetching directories when the fetch operation failed, with logs like this:
```
fetch error http://10.99.16.4:3456/remote/cache/s-t02620-5917 (storage 86f06f35-dee0-405b-8c60-e508a35b5a2e) -> /data/3/store/cache/fetching/s-t02620-5917: write /data/3/store/cache/fetching/s-t02620-5917/sc-02-data-layer-7.dat: no space left on device
```
Should result with far less garbage data after fetch operations fail. Should also make the experience of running out of disk space while sealing much better.
- `area`, e.g. api, …
=> fix: storage: Remove temp fetching files after failed fetch

storage/pipeline/states_proving.go
If a sector is already terminated, and enters Terminate, it will be saved with a nil terminate message. This PR handles this case more correctly.
=> fix: sealing pipeline: Allow nil message in TerminateWait

chain/sync.go
And fix the message to account for the fact that we now reject _old_ blocks along with new ones.
We frequently receive "out of date" blocks in hello messages from syncing and/or out of sync nodes. This isn't an error.
=> fix: sync: reduce log from error to info

chain/events/events.go, node/modules/actorevent.go, node/modules/ethmodule.go
- Make `NewEventsWithConfidence` private, and rename to `newEventsWithGCConfidence`.
- Use the default GC confidence everywhere.
The function/parameter were poorly named and should never have been exposed. "GC" confidence should always be the same, this parameter doesn't let us actually set the _confidence_, just the point before which we no longer support reverts.
fixes #10706
- [ x PR title is in the form of of `<PR type>: <area>: <change being made>`
=> fix: events: don't set GC confidence to 1

blockstore/badger/blockstore.go
fixes #10457
Check if we have blocks before writing them (in badger, only). By default, badger just appends the block which will grow the size of the datastore until garbage collected. Worse, badger garbage collection is expensive and not fully effective.
Downsides:
1. This code is racy. I.e., if we write the same block multiple times in parallel, we'll end up with multiple versions. We could prevent this with transactions, but that has other performance implications.
2. This adds a serial read before every write, reducing performance.
However, the average block sync time (on my machine) is 10.5s before and after this patch, so it shouldn't matter.
- `PR …
=> feat: badger: add a has check before writing to reduce duplicates

cmd/tvx/extract_many.go, conformance/driver.go
1. Fix flushing to handle the case where the VM is an FVM.
2. Fix extract-multiple's code CID conversion.
=> fix: tvx: make extract-multiple support the FVM

chain/sync.go
This makes two changes:
1. Write headers in chain order, not reverse order. This shouldn't matter, but it may help if badger crashes.
2. Force `collectChain` to collect the correct chain. This shouldn't matter, but we might as well (as long as it's safe).
WRT 1, I'm worried about the following:
1. Attempt to sync a chain from epochs 3-7.
2. Write tipsets 7, 6, 5.
3. Badger realizes that the current vlog is "full", so it creates a new one.
4. Write tipsets 4, 3.
My concern is that, while badger will write _synchronously_, it doesn't call `fsync `on the file itself, and the directory containing the file. That means, if the machine crashes, the new vlog might just disappear.
Of course, the _right_ solution would be to fix badger to sync the file/directory metadata, but that's not likely to …
=> feat: sync: harden chain sync

itests/eth_block_hash_test.go
- Increase epoch times to give the miners a chance to see each other's blocks.
- Wait longer for a multi-block tipset.
- Reduce the initial wait (we're increasing the block times and I don't really feel like waiting around).
This isn't exactly a fix, but it should (hopefully) reduce the chances of a flake. If it doesn't.... well, we'll have to try something else.
=> test: eth: deflake multiblock lookup test

itests/sector_finalize_early_test.go, itests/sector_import_full_test.go
These tests fail quite often, and it's always because the PoSt process doesn't kick off, causing the network to halt eventually (because no blocks can be produced).
Run the network with two miners, in the hope that the second miner (that isn't being actively tested) will keep the blockchain going. If that doesn't work, we can try using the `BeginMiningMustPoSt` mode.
=> fix: deflake: use 2 miners for flaky tests

cmd/lotus-shed/main.go, cmd/lotus-shed/mismatches.go
This allows nodes to sync the entirety of calibnet again.
- Update to FVM 3.3.1
- Add a shed command that reports on recent consensus breaks over the API
=> chore: deps: update to FVM 3.3.1

cmd/lotus-worker/main.go
This is something I occasionally run into in my setup when starting workers with custom TMPDIR, which on some of my systems disappears after reboot.
If not caught this would cause tasks like AddPiece to fail with a somewhat crypic error like
```
Caused by:
0: failed to create data store
1: No such file or directory (os error 2)
``` 
Make UX slightly better when the tempdir doesn't exist.
=> feat: worker: Ensure tempdir exists on startup

cli/chain.go
Change args check in `lotus chain set` cmd to make it possible to actually use the --epoch option and --genesis options. Regression from  #10114.
=> Change args check

chain/messagepool/check.go, chain/messagepool/messagepool.go, chain/messagepool/repub.go, chain/messagepool/selection.go
https://github.com/filecoin-project/lotus/issues/10597
1. https://github.com/filecoin-project/lotus/pull/10561/files#r1148322934 in chain/messagepool/check.go pre-allocate the size of the array msgs array using msgs = make([]*types.Message, 0, len(mset.msgs))
2. https://github.com/filecoin-project/lotus/pull/10561/files#r1152024072 remove the requirement of mp.keyCache.Add(ka, ka) by checking that the address is a robust address
3. https://github.com/filecoin-project/lotus/pull/10561/files#r1150875872 chain/messagepool/repub.go - optimize the Lock timing and confirm if all tests pass with a read lock -- also ensure that mp.curTsLk.RLock() is not held during mp.api.ChainComputeBaseFee
4. https://github.com/filecoin-project/lotus/pull/10561/files#r1150137317 chain/messagepool/selection.go …
=> perf: mempool: lower priority optimizations

documentation/en/default-lotus-miner-config.toml, node/config/def.go
https://github.com/filecoin-project/lotus/issues/10529
=> Disable lotus markets by default

chain/messagepool/check.go
https://github.com/filecoin-project/lotus/pull/10693#discussion_r1183927064
This PR contains a resolution to the requestion from @arajasek 
`Can we please chain these errors (return nil, xerrors.Errorf("....%w", err)?`
=> refactor: mempool: streamline error handling in CheckPendingMessages

cmd/lotus-miner/actor.go, cmd/lotus-shed/actor.go, documentation/en/cli-lotus-miner.md
Change arg wording from `minerAddress` to `minerID` in the `lotus-miner actor confirm-change-beneficiary` and `lotus-shed actor confirm-change-beneficiary` cmds.
A user encountered some confusion when using the `lotus-miner actor confirm-change-beneficiary` cmd, as the args (minerAddress) input in the helptext can easily be confused with the owner address/key/.
=> fix: cli: Change arg wording in change-beneficiary cmd

chain/stmgr/execute.go, chain/stmgr/stmgr.go
https://github.com/filecoin-project/lotus/issues/10584
https://github.com/filecoin-project/lotus/issues/10504
We want to make the execution trace cache size configurable as SPs may want to disable it while exchanges may want to crank it up.
We were also are going with intuition for this value, so having ability to change it without a new build would help.
=> feat: Make execution trace configurable via env variable

itests/kit/client.go
This test flakily fails, and I'm _pretty sure_ it's because the deals fail for some reason. Unfortunately, we can't tell, because that information isn't included in the output logs.
Include failed deals in the output so that we can see what's going wrong.
=> feat: make RunClientTest louder when deals fail

itests/eth_fee_history_test.go
This test has been observed to flake, eg. [here](https://app.circleci.com/pipelines/github/filecoin-project/lotus/28509/workflows/82949f35-6daa-479a-98d7-46223cf253b7/jobs/957928).
This particular failure arose because the test as currently written always expects the oldest non-genesis height to be 1. It IS possible for the first round to be null, though, which is what happened in the failure linked above.
Construct the heights based on the actual chain, not by hard-coding a first height of 1 and then observing chain head changes.
Happily, I was able to reproduce the flake by forcing the first tipset to be null, and confirmed that the change made here fixes the failure.
It would not surprise me if this test continues to flake for other reasons, but I am confident in this improvement. …
=> feat: deflake TestEthFeeHistory

chain/messagepool/check.go, chain/messagepool/messagepool.go
https://github.com/filecoin-project/lotus/pull/10818/files
refactor log.Warnf to returning xerrors.Errorf 
=> style: mempool: chain errors using xerrors.Errorf

itests/eth_deploy_test.go
fixes #10824
This fixes the TestDeployment flakiness by:
1. Pause mining before submitting the message. That way, we force it to get stuck in the message pool.
2. Removing the logic that asks lotus for the "latest" block. We have other tests that exercise "latest".
=> fix: itest: fix eth deploy test flake

chain/events/observer.go, chain/store/store.go
I've noticed multiple test failures* resulting from the observer system getting confused because it's asked to "apply" the same tipset as its current head. I'm not entirely sure why this happens, and I'm pretty sure there's an underlying issue (because the tipset question later can't be found in the blockstore for some reason).
BUT, regardless, we can just shortcut if we're ever asked to `MaybeTakeHeavierTipset`, which looks possible given that sync workers as well as `SyncSubmitBlock` can lead here.
*[example 1](https://circleci.com/api/v1.1/project/github/filecoin-project/lotus/962701/output/104/0?file=true&allocation-id=6454d26c6d28d7391af7b45b-0-build%2F3DD38584), [example 2](https://circleci.com/api/v1.1/project/github/filecoin-project/lotus/963331/output/104/0?file=true&allocation-id …
=> feat: chainstore: exit early in MaybeTakeHeavierTipset

cmd/lotus-miner/sectors.go
Add a easier way to publish with `lotus-miner sectors batching precommit` and `lotus-miner sectors batching commit` cmd´s. Currently its not clear that you need to add the --publish-now flag to manually send the batch.
Current output with these commands:
```
lotus-miner sectors batching commit 
7
8
9
10
```
Proposed change is to prompt the user if they want to publish the sectors/messages now and automatically do it for them:
```
lotus-miner sectors batching commit
7
8
9
10
Do you want to publish these sectors? (yes/no): yes
Batch 0:
Message: bafy2bzacedbitvc6hkp463lehfut6di3iqrbwlhn2z7fe2qmprpy7dxapuidg
Sectors:
9       OK
Batch 1:
Message: bafy2bzacec7jpltlldcdv6r5n6vjd2gvmgytgs6ovj7va325ddcp37lptjhem
Sectors:
10      OK
Batch 2:
Message: …
```
=> feat: cli: More ux-friendly batching cmds

node/impl/full/eth.go
RPC methods do not relay the error returned from `parseBlkParam`. This behaviour loses information and complicates debugging.
Wrap the error and make the error string more general since the problem may not be caused by parsing only.
- [] New features have usage guidelines and / or documentation updates in
=> fix: Eth RPC: do not occlude block param errors.

itests/paych_api_test.go
This test has been observed to flake a lot, example https://app.circleci.com/pipelines/github/filecoin-project/lotus/28643/workflows/32a2f145-5cac-492b-a00e-3ce566d50691/jobs/965295.
The problem is that we try to inject a lot of nulls in order to fast-forward the Paych Settle Delay (which is 12 hours on mainnet). This is nice to speed up the test, but just leads to missed PoSts, especially because we fast-forward entire deadlines at a time.
Just wait for the PaychSettleDelay to "normally" pass -- this is only 14 seconds, we don't need to risk flakiness. We could consider skipping fewer epochs at a time, but I honestly don't think it's worth it.
- `PR type`: …
=> feat: deflake paych_api_test

cmd/lotus-worker/main.go, documentation/en/cli-lotus-worker.md
https://github.com/filecoin-project/lotus/issues/10351
data_cid flag that workers can use to enable/disable that task irrespective of addpiece. Backwards compat is maintained (addpiece starts data_cid)
CLI description of usage added.
=> feat: sealing: flag to run data_cid untied from addpiece

.gitignore
The Dockerfile would not build on my local machine 
By adding this submodule to the !gitignore list (which is symlinked to dockerignore), it ensures it is still copied from the local machine into the Docker context before building. Without this, the Docker build will fail in order to prevent the dirty git state from ending up in the go version tag.
=> _build_ Add checked in file to dockerignore ignore list

api/api_full.go, api/proxy_gen.go, documentation/en/api-v1-unstable-methods.md
Fixes: https://github.com/filecoin-project/lotus/issues/10682
**Context**
This PR changes the API permission of eth_subscribe/eth_unsubscribe and all eth filter methods to only require read permission instead of write permission. 
**Test Plan**
Build generated files:
```
make gen
```
Pick eth_subscribe to test, replicated the perm error before applying this PR:
```
wscat --connect ws://localhost:1234/rpc/v1 
Connected (press CTRL+C to quit)
> {"jsonrpc":  "2.0",  "id":  1,  "method":  "eth_subscribe",  "params":  ["newHeads"]}
< {"jsonrpc":"2.0","id":1,"error":{"code":1,"message":"missing permission to invoke 'EthSubscribe' (need 'write')"}}
```
After applying this PR, then it goes through:
```
wscat --connect ws://localhost:1234/rpc/v1 
Connected (press CTRL+C to quit)
> {"jsonrpc": …
```
=> Make (un)subscribe and filter RPC methods require only read perm

storage/sealer/manager_test.go
Should fix a flake from https://app.circleci.com/pipelines/github/filecoin-project/lotus/28667/workflows/ae7a8156-78d0-48c2-852f-e203ea10e251/jobs/966677
```
fatal error: concurrent map read and map write
goroutine 103 [running]:
github.com/ipfs/go-datastore.(*MapDatastore).Has(0xc000046420?, {0x37e6f28?, 0xc00054be20?}, {{0xc00003a420?, 0x2c?}})
/home/circleci/go/pkg/mod/github.com/ipfs/go-datastore@v0.6.0/basic_ds.go:51 +0x2e
github.com/filecoin-project/go-statestore.(*StoredState).End(0xc00054be68)
/home/circleci/go/pkg/mod/github.com/filecoin-project/go-statestore@v0.2.0/state.go:20 +0x43
github.com/filecoin-project/lotus/storage/sealer.(*workerCallTracker).onReturned(0x37d9f58?, {{0x3e8, 0x1}, {0xce, 0xc, 0x8, 0x2b, 0x5a, 0x7a, 0x4c, ...}}) …
```
=> fix: tests: Use mutex-wrapped datastore in storage tests

itests/eth_balance_test.go
This test has been observed to flake, eg: https://app.circleci.com/pipelines/github/filecoin-project/lotus/28677/workflows/bf05c79a-62cf-46ee-b4f7-1aeeeeae02ed/jobs/967190
The test has a faulty assumption that the message lookup height - 2 will always get you a tipset before the relevant message has been included. This is not the case when the tipset after the inclusion tipset is null.
The correct way to make this assertion is to actually get heights from the blockchain itself: execution height, inclusion height, "most recent before inclusion height"
- `area`, e.g. api, chain, …
=> feat: deflake eth_balance_test

chain/types/ethtypes/eth_types.go, itests/eth_filter_test.go, node/impl/full/eth.go
**Context**
When calling ETH rpc method `eth_getLogs` and giving it a `fromBlock`/`toBlock` as epoch then return an error if its not in a hexadecimal format (instead of silently passing through and returning nothing or even worse potentially giving incorrect results)
**Test plan**
Verify that giving epoch ("2812200") as decimal returns a nice error:
```
curl -s http://localhost:1234/rpc/v1  -X POST -H "Content-Type: application/json" --data '{"method":"eth_getLogs","params":[{"fromBlock": "2812200"}],"id":1,"jsonrpc":"2.0"}'
{"jsonrpc":"2.0","id":1,"error":{"code":1,"message":"FromBlock is not a hex"}}
```
And that giving the same epoch in hex ("0x2AE928") works:
```
curl -s http://localhost:1234/rpc/v1  -X POST -H "Content-Type: application/json" --data …
```
=> Validate that FromBlock/ToBlock epoch is indeed a hex value

.circleci/config.yml, .circleci/template.yml
=> fix: ci: Debugging m1 build

documentation/en/default-lotus-config.toml, documentation/en/default-lotus-miner-config.toml, itests/net_test.go, node/config/def.go
=> libp2p: add QUIC and WebTransport to default listen addresses

blockstore/splitstore/splitstore.go, blockstore/splitstore/splitstore_check.go, blockstore/splitstore/splitstore_test.go, blockstore/splitstore/splitstore_warmup.go, chain/messagepool/messagepool.go, node/modules/chain.go
Fixes #9846.
This deadlock was being caused by attempting to access the warmupepoch variable, which was behind the splitstore.mx lock. We can just access this variable atomically.
- Access warmupEpoch atomically
- Revert #9903: The deadlock reported in #9846 should be fixed by this PR. We _might_ emerge other deadlocks by reverting 9903, but we really shouldn't be locking the entire splitstore to access -- any other deadlocks that emerge can be considered bugs we fix.
- Supersedes #10831, which should no longer be needed if we land this
- `area`, e.g. api, chain, state, market, …
=> feat: fix deadlock in splitstore-mpool interaction

.circleci/config.yml, itests/sealing_resources_test.go, storage/sealer/sched_assigner_common.go, storage/sealer/sched_assigner_darts.go, storage/sealer/sched_assigner_spread.go, storage/sealer/sched_assigner_spread_tasks.go, storage/sealer/sched_assigner_utilization.go, storage/sealer/sched_post.go, storage/sealer/sched_resources.go, storage/sealer/sched_test.go, storage/sealer/sched_worker.go
Fixes up https://github.com/filecoin-project/lotus/pull/10633
=> fix: sched: Address GET_32G_MAX_CONCURRENT regression

documentation/en/default-lotus-config.toml, documentation/en/default-lotus-miner-config.toml, itests/net_test.go, node/config/def.go
This reverts commit 0a064c1b3d845d4c7e4abf27d40f5bdb003f8c40.
=> Revert "libp2p: add QUIC and WebTransport to default listen addresses"

blockstore/splitstore/splitstore_compact.go
Note: GitHub is VERY confused on PR #10855, so this replaces it with an updated commit
#10788?
#10641 introduced the possibility of a deadlock, because `Put` might sleep waiting on sync to catch up while holding the all-important `txnLk`. This is definitely wrong, we also just don't want `Put`s to be yielding and sleeping.
Add a non-yielding version of `walkObjectIncomplete` that gets called by `Put` and `PutMany`.
I checked thoroughly, but am still not _confident_ that other methods more directly involved in compaction don't have the same problem. This entire locking mechanism is...tricky.
- `PR type`: fix, feat, build, chore, ci, docs, perf, refactor, …
=> fix: splitstore: remove deadlock around waiting for sync

itests/sector_import_simple_test.go
This test has been observed to flake, eg. [here](https://app.circleci.com/pipelines/github/filecoin-project/lotus/28749/workflows/32662994-991f-47d6-b7bc-6c3af046edbb/jobs/971223), due to missed PoSts.
Use 2 miners instead of one for this test. We made the identical change to sector_import_full_test.go in #10764, and it hasn't flaked once since then (afaic tell).
=> feat: deflake sector_import_simple

cmd/lotus-fountain/main.go
Closes https://github.com/filecoin-project/lotus/issues/10560
Check if address starts with `Ox`. If so, parse it as Eth address. Otherwise, use the previous logic.
=> lotus-fountain: make compatible with 0x addresses #10560

node/impl/full/eth.go
Fixes: #10781 
**Context**
When working on https://github.com/filecoin-project/lotus/pull/10780 I noticed we currently did not support the `blockHash` param for the `eth_getLogs` rpc method. If it was specified by user he got confusing results (fromBlock/toBlock were both 0). This PR therefore adds this feature as described in the [eth docs](https://docs.infura.io/infura/networks/ethereum/json-rpc-methods/eth_getlogs)
**Test plan**
Lets consider the tipset 2848101 (hex: 0x2B7565) and get the logs for only that tipset (using fromBlock/toBlock). Since the log output it long lets just count the lines and compute the sha1sum:
```
curl -s http://localhost:1234/rpc/v1 -X POST -H "Content-Type: application/json" --data '{"method":"eth_getLogs","params":[{"fromBlock": "0x2B7565", "toBlock": …
```
=> feat: eth: Add support for blockHash param in eth_getLogs

itests/kit/blockminer.go
example failure that's hard to investigate due to missing info: https://circleci.com/api/v1.1/project/github/filecoin-project/lotus/970891/output/104/0?file=true&allocation-id=645c52859e67117b20aa0012-0-build%2F4A3521EB
Spell out which block height was missed by the  node, and what height the node is at instead
=> feat: itests: add logs to blockminer.go failure case

node/builder.go, node/builder_miner.go, node/modules/alerts.go
Add alert if a storage provider is still using the lotus-miner legacy-markets.
**Lotus-miner info:**
```
Enabled subsystems: [Mining Sealing SectorStorage Markets]
StartTime: 48s (started at 2023-05-15 06:59:10 -0400 EDT)
Chain: [sync ok] [basefee 100 aFIL]
⚠ 2 Active alerts (check lotus-miner log alerts)
```
And checking the alert with `lotus-miner log alerts`:
```
active   system:EOL
last raised at 2023-05-15 06:59:10.141 -0400 EDT; reason: {"message":"The lotus-miner legacy markets subsystem is deprecated and will be removed in a future release. Please migrate to [Boost](https://boost.filecoin.io) or similar markets subsystems."}
```
- `PR type`: fix, feat, …
=> feat: alerts: Add lotus-miner legacy-markets alert

go.mod, go.sum
Supersedes https://github.com/filecoin-project/lotus/pull/10808
=> chore: update go-fil-markets

cmd/lotus-shed/verifreg.go
reported [here](https://filecoinproject.slack.com/archives/CPFTWMY7N/p1682613089521759 ) publish message will hit `Filecoin.MpoolPushMessage': failed to sign message: Unexpected number of items`
use interactive send instead 
tested by using ledger and was able to successfully sign the desired message
=> fix: shed remove datacap not working with ledger

cmd/lotus-miner/storage.go, cmd/lotus-worker/storage.go, documentation/en/cli-lotus-miner.md, documentation/en/cli-lotus-worker.md
Fix: #10859
- Fix issue where `lotus-miner storage redeclare --all` required an argument
- Set value of --drop-missing to `true`
- Implement the logic to redeclare sectors in a single storage path.
=> fix: cli: make redeclare cmd work properly

chain/sub/incoming.go, chain/sub/incoming_test.go, go.mod, go.sum, node/modules/storageminer_idxprov.go
Replace dependencies on packages in storetheindex with equivalents in go-libipni.
- [N/A] New features have usage guidelines and / or documentation updates in
=> chore: chain: replace storetheindex with go-libipni

chain/store/store.go
Node operators reported this method hanging if called with negative values
this backports the fix in #10878
=> Check if epoch is negative in GetTipsetByHeight

cmd/lotus-fountain/main.go
set the default data-cap size same as the MinVerifiedDealSize
=> fix:lotus-fountain:set default data-cap same as MinVerifiedDealSize

cmd/lotus-shed/main.go
**Context**
Currently, `lotus-shed` runs all commands with `app.Run`. This makes handling  handle interrupts difficult or even impossible from the client side (https://github.com/urfave/cli/issues/945). We would like to be able to interrupt (CTRL+C) all our commands such that they can gracefully exit, or if that fails force them to stop (right now we need to do a manual SIGKILL)
**This diff**
Updates  `lotus-shed` to run all commands with `app.RunContext()` and pass it a context that we cancel on interrupt from `main()`. This allows each command to simply check for `ctx.Done()` and gracefully exit (we can add that incrementally later).
Implementation notes:
- Calling `cancel()` does not in all cases gracefully exit as it seems that we not thoroughly check for Done in all codepaths. …
=> feat: run lotus-shed commands in context that is cancelled on sigterm

chain/sub/incoming.go
Currently, ErrGasFeeCapTooLow results in a ValidationReject, that lowers peer scores. I _think_ this is too extreme, as it can happen for somewhat benign reasons such as the base fee changing, a node briefly falling out of sync etc. 
I'm proposing treating this as an Ignore, similar to how we treat errors around message nonces, not-enough-funds, etc. 
I _think_ we should do this, because otherwise we risk dropping good peers when _we_ are out of sync. However, this might require some careful thought, so please feel free to disagree.
- `area`, e.g. api, chain, state, market, …
=> feat: pubsub: treat ErrGasFeeCapTooLow as ignore, not reject

cmd/lotus-miner/sectors.go
More work towards #9041 
Implements 2 improvements to the compact partitions command:
- Auto split into smaller messages as needed, if a single message wouldn't fit in a block
- Simulate if `really-do-it` isn't passed, reporting on the gas costs
- Needs #9061 
=> feat: cli: Make compact partitions cmd better

itests/worker_test.go
Just wanted to make sure this is covered, sector skipping logic may change after nv20 (tho the current one should still work, but better to have that covered explicitly)
=> itests: Test PoSt V1_1 on workers

chain/types/blockmsg.go, chain/types/blockmsg_test.go
This fixes the OSS-fuzz finding [48208: lotus:fuzz_block_msg](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=48208).
The error being that invalid CBOR encoding of BlockMsg can lead to decoded values that do not re-serialize as is. Not necessarily a security issue, but making sure we're not decoding invalid representations shouldn't hurt and prevents us from having to worry about having multiple CBOR representation of the same thing (our CBOR decoder requires canonical CBOR).
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=48208
This reads the remaining bytes in the reader provided to `UnmarshalCBOR` and if it still contains data, errors out. 
The oss-fuzz testcase boils down to:
`0x83F6808020`
which contains an extra byte after the data items: …
=> fix: types: error out on decoding BlockMsg with extraneous data

chain/messagepool/messagepool_test.go
We weren't sure whether or not this case was correctly handled when pruning messages.
Add a test that confirms these costs are negative, and sorted correctly.
=> test: messagepool: gas rewards are negative if GasFeeCap too low

itests/kit/blockminer.go
A class of tests have been flaking due to PoSts not getting in during a deadline, leading to all power in the network disappearing (example [here](https://app.circleci.com/pipelines/github/filecoin-project/lotus/28945/workflows/082d3a9f-f4f8-470f-bb65-cd95e6e3d8c6/jobs/981096)). This occurs despite the "force post" functionality that is intended to avoid this.
More aggressively block and force post (within 5 epochs of the deadline closing).
=> feat: itest: force PoSt more aggressively around deadline closure

chain/gen/slashfilter/slashfilter.go
This hasn't been necessary since we passed the Orange upgrade
Drop the check
=> feat: slashfilter: drop outdated near-upgrade check

documentation/en/default-lotus-miner-config.toml, node/config/doc_gen.go, node/config/types.go, node/modules/storageminer.go, storage/pipeline/input.go, storage/pipeline/sealiface/config.go
* Attempt to improve upgrade sector selection logic
* Deprecate the MinTargetUpgradeSectorExpiration config, it makes no sense after nv17
* Add better logging about upgrade sector selection decisions
=> sealing: Improve upgrade sector selection

documentation/en/default-lotus-config.toml, documentation/en/default-lotus-miner-config.toml, go.mod, go.sum, itests/net_test.go, node/config/def.go
Reverts filecoin-project/lotus#10852, fixes tests
=> Revert "Revert "libp2p: add QUIC and WebTransport to default listen addresses""

cmd/lotus-bench/main.go, cmd/lotus-bench/rpc.go
Fixes: https://github.com/filecoin-project/lotus/issues/10752
Fixes: https://github.com/filecoin-project/fvm-pm/issues/494.
We need a more elaborate tool to stress test our RPC methods in order address and fix the reported performance issues (example https://github.com/filecoin-project/lotus/issues/10670, https://github.com/filecoin-project/lotus/issues/10539, https://github.com/filecoin-project/lotus/issues/10540, https://github.com/filecoin-project/lotus/issues/10541, https://github.com/filecoin-project/lotus/issues/10663). 
This PR implements such tool (`lotus-bench rpc`) and has the following features:
* Can query each method both sequentially and concurrently
* Supports rate limiting
* Can query multiple different endpoints at once (supporting different concurrency level and rate …
=> Add new RPC stress testing tool (lotus-bench rpc) with rich reporting

chain/actors/policy/policy.go, chain/actors/policy/policy.go.template, cmd/lotus-miner/sectors.go, documentation/en/cli-lotus-miner.md
(Mostly?) Addresses https://github.com/filecoin-project/lotus/issues/10908
* Output without `--deal-terms` just shows sectors bucketed by expiration
* Output with `--deal-terms` shows how many sectors worth of deals with a given expiration could be accepted into available sectors
=> feat: miner cli: sectors list upgrade-bounds tool

chain/store/index.go, go.mod, go.sum, lib/shardedmutex/shardedmutex.go, lib/shardedmutex/shardedmutex_test.go
=> feat: chainstore: sharded mutex for filling chain height index 

node/builder.go, node/modules/alerts.go
Inspired by #10710
Raise an alert in the alert system if the `LOTUS_FVM_CONCURRENCY` enviroment variable is set higher then 24. Alert the user that this can cause chain sync panics when going over network upgrades/migrations.
Alert will show up in **lotus info**
```
Network: localnet-3de9f2f7-de34-41cc-a5fe-0893f2b6e707
StartTime: 4m18s (started at 2023-05-31 09:41:36 -0400 EDT)
Chain: [sync ok] [basefee 100 aFIL] [epoch 328606]
Peers to: [publish messages 0] [publish blocks 0]
⚠ 1 Active alerts (check lotus log alerts)
```
**lotus log alerts**
```
active   process:fvm-concurrency
last raised at 2023-05-31 09:41:36.969 -0400 EDT; reason: {"message":"LOTUS_FVM_CONCURRENCY is set to a high value that can cause chain sync panics on network migrations/upgrades","recommended":"23 or less …
```
=> feat: alert: Add FVM_CONCURRENCY alert

chain/index/msgindex.go, cmd/lotus-shed/msgindex.go
**Context**
When `EnableMsgIndex` is set we maintain a separate sqlite database in `.lotus/sqlite/msgindex.db` which maps message cid to the tipset and epoch its stored in. This allows us faster lookup and optimizes several RPC calls.
Currently the message index `msgindex.db` uses default journal mode which causes the database to be locked, especially when backfilling this database (using `lotus-shed msgindex backfill` ) over multiple epochs (like a FEVM arvhical node). When backfilling, the lotus node will soon lock the database and disable the msgindex logic until next lotus restart which also fails the backfilling itself.
This PR addresses these issues by:
- switching this database to use the WAL journal mode. This will make writes at least an order of magnitude faster
- updating the …
=> fix: improve perf of msgindex backfill

node/modules/ethmodule.go
**Context**
The `GetTipsetByHeight` method internally maintains a skiplist to more efficiently lookup a tipsets at a given height. 
When users call a RPC method that call this method (for example `eth_getBlockByNumber`) then if this skiplist is not already cached then the user needs to wait until this skiplist is populated in the background which can take 10 minutes or longer.
Instead, lets just always populate and fully prefill this skiplist in the background as soon as lotus starts up (only when EnableEthRPC is set). This will not fix the issue, but it will be more likely to give better user experience.
**Test plan**
Compiled and restarted Lotus and observed the skiplist was generated on startup
```
2023-06-05T17:43:59.757-0500	INFO	modules	modules/ethmodule.go:61	Start prefilling …
```
=> Prefill GetTipsetByHeight skiplist cache on lotus startup

cmd/lotus-shed/eth.go
**Context**
I needed a quick way to compute the eth hash for a given message cid so I could use that for constructing options to RPC calls like `eth_getTransactionReceipt`.
**Test plan**
Looked up a random message `bafy2bzaceduvlffwumoq6j7rmx5evgsyl2fa3nh7oaqbzt7t4n3r75f2vqqpy` on filfox and used that as an example:
```
./lotus-shed eth compute-eth-hash bafy2bzaceduvlffwumoq6j7rmx5evgsyl2fa3nh7oaqbzt7t4n3r75f2vqqpy
0xbc7c5ebdada305ea6922e5644fba5ecb283ce3f2f4cfe58a786eed744df70042
```
Confirmed that the returned eth hash is valid:
```
curl -s  http://localhost:1234/rpc/v1  -X POST -H "Content-Type: application/json" --data '{"method":"eth_getTransactionReceipt","params":["0xbc7c5ebdada305ea6922e5644fba5ecb283ce3f2f4cfe58a786eed744df70042"],"id":1,"jsonrpc":"2.0"}'|jq
{
"jsonrpc": "2.0", …
```
=> Add new lotus-shed command for computing eth hash for a given mcid

cli/state.go
Default to the using tipset at the specified epoch. Otherwise, specifying an epoch without a tipset would lead to computing the _latest_ tipset with at the specified epoch.
Previously, we'd use the current head if not otherwise specified, even when the user specified a epoch. Now:
1. If the user specifies nothing, we use head head's epoch.
2. If the user specifies a tipset and no epoch, we use that tipset and the epoch of that tipset.
3. If the user specifies an epoch and no tipset, use the tipset at that epoch (based on the current head).
4. Finally, if the user species both, use both (allowing the epoch/tipset to disagree).
This is a significant breaking change that should, in most cases, simply fix buggy code. _Most_ of the time, the user _doesn't_ want to execute a tipset at a …
=> feat: cli(compute-state) default to the tipset at the given epoch

node/impl/full/eth.go, node/impl/full/eth_test.go
fixes #10910
Ensure event topics are non-nil, even when empty. Go treats them as equivalent, but JSON distinguishes between `null` and `[]`.
=> fix: eth: ensure that the event topics are non-nil

itests/deals_partial_retrieval_dm-level_test.go
This test has been observed to flake, eg https://app.circleci.com/pipelines/github/filecoin-project/lotus/29090/workflows/fe74620b-a665-43e1-baab-aaa31a98c9c7/jobs/988362
The failure in the linked build is simply because a PoSt was never submitted for the miner
Use the `MustPost` version of mining loop for itests 
=> feat: deflake TestDMLevelPartialRetrieval

chain/sub/incoming.go
This might help with #10906.
The `ErrExistingNonce` error is thrown when [we already have the exact message we're trying to add ](https://github.com/filecoin-project/lotus/blob/fb228ebbff5b2e3bbb6a51f2b2cfe232f2f16f94/chain/messagepool/messagepool.go#L284-L285)in our pending mset. It is an error to try and add this message, but it is not wrong for us to _receive_ a message multiple times, and try to add it. We should definitely not penalize peers who inform us of messages we've already added.
What's not clear to me is whether something earlier in the pipeline should be realizing that we've already processed this message. Regardless, however, I think we should be treating this case as an Ignore, not a Reject. 
Lower the pubsub handling of this particular failure to Ignore.
Before you mark …
=> fix: pubsub: do not treat ErrExistingNonce as Reject

itests/sector_finalize_early_test.go
This test has been observed to flake, eg https://app.circleci.com/pipelines/github/filecoin-project/lotus/29148/workflows/9be15326-5b82-4c13-943b-f38e229bb37e/jobs/990528
The failure in the linked build is simply because a PoSt was never submitted for the miner
Use the `MustPost` version of mining loop for itests 
=> feat: deflake TestDealsWithFinalizeEarly

CHANGELOG.md
=> chore: merge releases back into master

cmd/lotus-shed/invariants.go
This commit refactors the code in `invariants.go` to support state invariant checks for different actor versions. The code now includes checks for versions 10 and 11 of the actors. The `CheckStateInvariants` function is invoked based on the actor version, passing the appropriate parameters. This change ensures that state invariant checks are performed correctly for different actor versions.
The changes made are as follows:
- Added imports for actor versions 10 and 11.
- Added `case` statements for versions 10 and 11 in the switch statement.
- Invoked `CheckStateInvariants` function with the correct parameters for each version.
- Handled errors returned by the `CheckStateInvariants` function.
These changes enhance the flexibility and compatibility of the code with different actor versions, …
=> chore: shed: update actor version

cli/wallet.go, go.mod
Let the user's private key no longer be displayed in the terminal to prevent malicious monitoring of the screen and stealing the private key.
```bash
$ ./lotus wallet import
Enter private key(not display in the terminal): 
imported key f1xxxxxxx successfully!
$ ./lotus wallet import
Enter private key(not display in the terminal): 
ERROR: saving to keystore: checking key before put 'wallet-f1xxxxxxx': key already exists
$ echo 7bxxxxxxx | ./lotus wallet import
imported key f1xxxxxxx successfully!
$ echo 7bxxxxxxx | ./lotus wallet import
ERROR: saving to keystore: checking key before put 'wallet-f1xxxxxxx': key already exists
```
- `PR type`: fix, feat, build, …
=> chore: not display privatekey

storage/pipeline/input.go
Likely fixes https://github.com/filecoin-project/lotus/issues/10914
Thanks to added logging in https://github.com/filecoin-project/lotus/pull/10915
The sealing pipeline keeps pending piece references for a while after deals are assigned/added to sectors. When selecting what sector to upgrade, we calculate a list which says "at Y epoch there are X deals waiting to be inserted into a sector". That logic only cares about deals/pieces which weren't added/assigned to any sector, which we didn't check, causing us to potentially select sectors which couldn't accept any deals, which would cause the pipeline to fill up with waiting sectors, just waiting for a timeout.. …
=> sealing: Use only non-assigned deals when selecting snap sectors

chain/events/filter/index.go, chain/events/filter/index_test.go, node/modules/actorevent.go
Fixes: https://github.com/filecoin-project/ref-fvm/issues/1350
When lotus is configured to enable indexing of actor events (when EnableEthRPC=true and DisableHistoricFilterAPI=false) then Lotus will observe for new tipset and store all the actor events in a sqlite table stored at sqlite/events.db.
However, users have been reporting that these events are duplicated and hard to understand (see https://github.com/filecoin-project/ref-fvm/issues/1350).
To address this, I originally implemented a quick fix (https://github.com/filecoin-project/lotus/pull/10897) which addressed this in the API level but the team decided that we instead want a less hacky fix where we do not store duplicate events in the database to start with. 
This PR implements this on the DB level where depending on whether we …
=> feat: Make sure we don't store duplidate actor events caused to reorgs in events.db

documentation/misc/RELEASE_ISSUE_TEMPLATE.md
These steps are missing from the Release Issue docs, and have been missed in previous releases.
Mention the steps that Lotus devs have to take in order to update FFI before starting a release train.
=> feat: docs: include FFI steps in lotus RELEASE_ISSUE_TEMPLATE

storage/paths/index.go
Closes: #10901
Tune down the log-level on `StorageDeclareSector` to debug. 
Boost added an index integrity check in [Boost 1.7.0](https://github.com/filecoin-project/boost/releases/tag/v1.7.0) which causes users to see logs like these more often:
```
2023-05-22T13:51:13.217Z	WARN	stores	paths/index.go:369	sector {1278 997} redeclared in d8cfac01-4999-45d5-8231-8aa9423224e2
```
The WARN level here seems wrong as these are expected, and the interval of how often this gets called can be tuned in the configs on Boost.
I have added a KB-article explaining why users might see these logs as well here: https://lotus.filecoin.io/kb/redeclared-sector-log/
- `PR type`: …
=> fix: stores: Tune down StorageDeclareSector` log-lvl

chain/gen/slashfilter/slashfilter.go, cmd/lotus/daemon.go, miner/miner.go, node/impl/full/sync.go
Improvements to the new consensus slasher that was created in #10871 
- Log failures
- Return a bool to indicate any faults, separate from other errors
- Perform some additional checks before reporting faults 
Run `lotus daemon --slash-consensus=true --slashdb-dir="/mnt/data/.slasher" >> /mnt/data/slash.log 2>&1 &` to run the consensus slasher.
`--slashdb-dir` is used to supply the path to the slasher database.
`--slasher-sender` can optionally be used to specify the account to send the `ReportConsensusFault` message from.
- `area`, e.g. api, chain, state, market, mempool, …
=> feat: daemon: improvemens to the consensus slasher

metrics/metrics.go, node/modules/lp2p/pubsub.go
#11044 
Add a metric to display when external peers are pruning your libp2p peer
=> feat: Add a metric to display pruning of the node's peer

chain/types/event.go, chain/vm/fvm.go, chain/vm/fvm_util.go
A security report pointed out the unbounded allocation here, which could be problematic. In practice, this is not a problem, since we can trust the FVM not too return dangerously large data, which can in turn trust gas costs to not allow several GiBs of events.
Despite that, we might as well apply some limit here. I settled on 6 million, since it seems like a good theoretical limit, given that a single message can't use more than 10 Billion gas (block gas limit), and a single event must cost at least 1750 gas, leading to a theoretical max of 5.7 Million entries.
I'm happy to use something bigger or smaller, this number is only consensus critical for folks actually decoding events, which Lotus doesn't do by default.
- example: …
=> feat: types: apply a max length when decoding events

documentation/misc/RELEASE_ISSUE_TEMPLATE.md
=> chore: Extract stable release and post release portion outside of RC testing in template

CHANGELOG.md
Minor issues in the 1.23.3 CHANGELOG:
- Wrong link for PR 10815
- Sharded mutex change was backported into 1.23.2, and therefore not a new highlight
Fix them
=> fix: docs: correct 1.23.3 CHANGELOG

chain/events/filter/index.go
Fixes: https://github.com/filecoin-project/lotus/issues/11056
Added a few temporary indices to help speed up the migration.
Also, after the migration finishes successfully, I perform some manually DB administration to free up disk space (reducing size on disk from 3GB to 0.5GB).
I used the large events DB that @TippyFlitsUK had generated and shared with me ([link](https://drive.google.com/drive/folders/10In-8EAZxbEF5GZL_02kc36lgqlsU88R)) as a benchmark when testing out this PR. Ths db contained 5.9mio entries and 21.6mio event entries. 
Using this events DB and starting lotus resulted in migration from V1 to V2 in about 55 seconds:
```
./lotus daemon
...
2023-07-11T10:17:53.644Z        INFO    filter  filter/index.go:166     Migrating events from head to 2683360
2023-07-11T10:17:53.652Z …
```
=> fix: events: Improve performance of event migration from V1 to V2

chain/messagepool/messagepool.go, chain/sub/incoming.go
- Make all validation error actions explicit in the switch check
- Move ErrNotEnoughFunds to return pubsub IGNORE since this can be possible from an innocent actor if a set of transactions gets executed out of order leaving no funds for one of them
- Add a comment when adding new errors to also include the error in the switch check
=> refactor: Make all validation error actions explicit

.gitmodules, chain/actors/builtin/miner/actor.go.template, chain/actors/builtin/miner/miner.go, chain/actors/builtin/miner/utils.go, chain/gen/genesis/genesis.go, chain/gen/genesis/miners.go, cmd/lotus-bench/main.go, cmd/lotus-miner/sectors.go, cmd/lotus-seed/main.go, cmd/lotus-sim/simulation/stages/precommit_stage.go, documentation/en/default-lotus-miner-config.toml, go.mod, go.sum, itests/kit/ensemble.go, itests/migration_test.go, itests/sector_import_full_test.go, itests/sector_import_simple_test.go, markets/storageadapter/provider.go, node/config/def.go, node/config/doc_gen.go, node/config/types.go, node/impl/client/client.go, node/modules/storageminer.go, storage/pipeline/sealiface/config.go, storage/pipeline/sealing.go, storage/sealer/ffiwrapper/sealer_cgo.go
Synthetic PoRep Sealing Implementation for considerable reduction in disk usage by sealing machines during the network proof epochs. 
This including Rust Proofs, FFI, and Lotus Sealing Scheduler but lacks Network/Protocol code.
https://docs.google.com/document/d/1Ug4uC89Kkwhn3vcbiHETxToIUQ4zXEPa4QcQMPcvRxI/edit#heading=h.277tjch7w86w
https://www.notion.so/pl-strflt/FIP-0059-Synthetic-PoRep-180d995a027647198f6bffebc3eca932
https://www.notion.so/pl-strflt/Synthetic-PoRep-c15c9005f6284a9b9b3adeb6a3cecff1
https://github.com/filecoin-project/FIPs/discussions/245
- `area`, e.g. api, …
=> feat: Synthetic-porep

chain/types/ethtypes/rlp.go, chain/types/ethtypes/rlp_test.go
Fixes: https://github.com/filecoin-project/lotus/issues/11053
It was possible to pass to `DecodeRLP` a certain byte slices that resulted in a panic caused by unchecked decode length. This PR adds a check for this condition and adds a test case to make sure this check is triggered. 
=> fix: DecodeRLP can panic

chain/beacon/drand/drand.go, cmd/lotus-shed/gas-estimation.go, cmd/lotus/daemon.go, node/modules/services.go
#11041 
- Unify the code that creates beacon schedules from drand config
- Actually set the beacon schedule when running import-chain
Syncs mainnet :heavy_check_mark: 
Repro in #11041 no longer panics :heavy_check_mark: 
=> fix: daemon: set real beacon schedule when importing chain

chain/store/snapshot.go, chain/vm/vm.go, go.mod
1. Switch to go-multicodec as the source of multicodec code information. This gives us a central, generated source of multicodec codes.
2. Use this library inside the VM and shapshot logic to consistently allow CBOR, in addition to DagCBOR.
3. Remove the hard-coded CBOR constant.
This doesn't add any functionality in practice, it's just a post FEVM cleanup.
=> feat: vm: allow raw "cbor" in state and use the new go-multicodec

cmd/lotus/daemon.go
@snissn reported that when running `lotus daemon --halt-after-import --import-snapshot  /mnt/latest.zst`, he was getting the following error:
```
2023-07-17T20:27:58.025Z        INFO    drand   drand/drand.go:114      drand beacon without pubsub
2023-07-17T20:27:58.025Z        WARN    chainstore      store/store.go:634      reorgWorker quit
2023-07-17T20:27:58.356Z        INFO    badgerbs        v2@v2.2007.4/db.go:1027 Storing value log head: {Fid:98 Len:33 Offset:255692644}
2023-07-17T20:27:58.649Z        INFO    badgerbs        v2@v2.2007.4/levels.go:1000     [Compactor: 173] Running compaction: {level:0 score:1.73 dropPrefixes:[]} for level: 0
2023-07-17T20:28:00.533Z        INFO    badgerbs        v2@v2.2007.4/levels.go:962      LOG Compact 0->1, del 8 tables, add 6 tables, took …
```
=> feat: daemon: import: only setup stmgr if validating chain

cmd/lotus/daemon.go, documentation/en/cli-lotus.md
Closes: https://github.com/filecoin-project/lotus/issues/10958
Add a flag (`remove-existing-chain`) to remove the existing chain data on import of a snapshot, reducing manual operation needed when node operators want to prune their current chain.
**Some open questions:**
- Do we only want the removal of the chain data to be possible when importing a snapshot?
- Do we want it to default to true when importing a snapshot?
- Do we want to clear the chain data dirs, or delete it?
- Are there any edge-cases where deleting the chain data dir is bad before importing a snapshot? 
**Testing:**
**Docs (todo):**
- `PR type`: fix, feat, build, chore, ci, docs, perf, …
=> feat: snapshot: remove existing chain

chain/types/ethtypes/rlp.go, chain/types/ethtypes/rlp_test.go
Similar to #11053 
The string length field can overflow and turn negative here, leading to a panic
=> fix: ethtypes: handle length overflow case

cmd/lotus-shed/indexes.go
Related issue: https://github.com/filecoin-project/lotus/issues/10807
Replaces previous PR: https://github.com/filecoin-project/lotus/pull/10939
When lotus is configured to enable indexing of actor events (when `EnableEthRPC=true` and `DisableHistoricFilterAPI=false`) then Lotus will observe for new tipset and store all the actor events in a sqlite table stored at `sqlite/events.db`. 
We however, don't have any way to backfill these actor events. This PR therefore implements this backfilling using a new lotus-shed` command.
Note that this implementation does not compute state (it only looks up the receipts so they need to exist on chain).
**Backfill active node that is already storing events**
As expected, backfilling should not have any side effects on a node that is already saving actor …
=> Add new lotus-shed command for backfillling actor events

chain/consensus/compute_state.go, chain/consensus/filcns/filecoin.go, chain/vm/fvm.go, itests/remove_verifreg_datacap_test.go
#11061
The FVM currently errors on unsuccessful `Implicit` messages -- that is, a failure exit code is treated as an error. This essentially assumes that all callers of `ApplyImplicitMessage` wants to treat a non-zero code as an error. While this is generally true, some callers (eg. when simulating messages) might not want to handle non-zero exit codes as errors.
- Change the FVM to NOT treat non-zero exit codes as errors
- Change the core state computation pipeline to explicitly check exit codes for Cron and Reward actors, and fail if unsuccessful
- `area`, e.g. api, chain, …
=> feat: FVM: do not error on unsuccessful implicit messages

cmd/lotus-shed/cron-count.go
One part of work in 
#11034 
Add a shed command that takes in a miner actor and an epoch of processing and returns metadata concerning the partitions of that miner at that deadline 
=> feat:shed:gather partition metadata

itests/wdpost_test.go
CI on master currently failing due to a missed test fixup needed in #11120. GitHub auto-merge merged the PR even though CI hadn't completed?
Tweak the test condition
=> fix: failing test: Tweak TestWindowPostV1P1NV20 test condition

storage/pipeline/receive.go
Fixes #11122 
`SectorReceive` API mistakenly expects RandomnessFromTicket as a result of WaitSeed. However, we should be using RandomnessFromBeacon instead.  Hence, I have changed a call of `StateGetRandomnessFromTickets` with `StateGetRandomnessFromBeacon`. 
Info about this issue discussed on [Filecoin slack, #fil-lotus-dev, ID p1690821347448089](https://filecoinproject.slack.com/archives/CP50PPW2X/p1690821347448089)
=> sector import: fix evaluating randomness when importing a sector

chain/gen/slashfilter/slashfilter.go, chain/gen/slashfilter/slashsvc/slashservice.go, cmd/lotus/daemon.go, documentation/en/cli-lotus.md, documentation/en/default-lotus-config.toml, miner/miner.go, node/builder.go, node/builder_chain.go, node/config/doc_gen.go, node/config/types.go, node/impl/full/sync.go, node/modules/faultreport.go
These are two PRs that improve the consensus slasher, which we wish to announce as production ready in 1.23.3. Hence, the backport.
Backports #10979 and #11126
=> chore: backport improvements to the consensus slasher

itests/kit/deals.go, itests/kit/log.go, itests/kit/node_opts.go, itests/worker_test.go, storage/pipeline/states_failed.go
Fixes https://github.com/filecoin-project/lotus/issues/9841
In the CommitFailed state handler, if we see a successful commit message still check if the sector is visible on chain. If it's not run full checks, which will catch things like expired deals, and most likely will remove the sector.
Testing:
=> fix: sealing: Fix RetryCommitWait loop when sector cron activation fails

go.mod, go.sum
#11137 updated us to 0.27.8, but there's a 0.27.9 we can be updating to instead.
Update to 0.27.9
=> chore: deps: update to go-libp2p 0.27.9

.circleci/config.yml, .circleci/gen.go
unit-rest is supposed to be a catch-all suite for all remaining tests. We currently run all the tests in unit-node, unit-storage, and unit-cli a second time in unit-rest, because we populate the exclusion map with absolute paths, but `WalkDir` checks against relative paths.
Populate the map with both absolute and relative paths, thus avoiding all this duplicated work
=> fix: CI: make test-unit-rest actually be the rest of the tests

gateway/proxy_eth.go
Reported on slack.
In the gateway, return an error when an Eth filter is not found instead of returning "nil".
=> fix: gateway: return an error when an Eth filter is not found

chain/gen/gen.go, chain/store/checkpoint_test.go, chain/store/index_test.go, chain/store/store.go, chain/store/store_test.go, chain/sync.go, chain/sync_manager.go, chain/sync_test.go
#10793 
As discussed in #10793, we now reject ALL blocks with the same miner and same height (irrespective of other details like common parents, common ticket, etc.).  Further, when asked to consider taking a new tipset as head, we first refresh our `heaviest` tipset in order to check whether it's weight has DECREASED as a result of equivocation.
This PR also refactors / simplifies much of the "taking heavier tipset" logic. We now simply:
- `PersistTipsets` as we receive them, which also writes the tipset keys to the blockstore
- `AddToTipsetTracker` as we validate tipsets (blocks)
- When a new "head" is synced to / new block comes in, we simply notify the chainstore of its existence by calling `RefreshHeaviestTipSet` with the height of the new tipset.
- `RefreshHeaviestTipSet` works by: …
=> feat: chainstore: FRC-0051: Remove all equivocated blocks from tipsets

itests/eth_transactions_test.go
This test has been observed to flake, eg. https://app.circleci.com/pipelines/github/filecoin-project/lotus/29804/workflows/e8335521-f9ab-49c3-adea-5c2252ceb830/jobs/1024823. The source of the flake is that `afterNullHeight - 1` may not necessarily be a null round.
I'm a little surprised this is flaky, but it's easy enough to just check and be confident we've hit a null round.
Walk up until we are confident we've identified a null round, use that for the test's assertions.
- `area`, e.g. api, chain, state, market, mempool, multisig, networking, paych, proving, sealing, wallet, …
=> feat: deflake: TestGetBlockByNumber

chain/gen/gen.go, cmd/lotus-shed/election.go, miner/miner.go
Towards #10793 
- Drop the unused tipset param from IsRoundWinner
- Only pass the information needed to computeTicket -- the specific round, and the previous Ticket being used (instead of the entire base tipset)
=> feat: miner: 2 minor refactors

cmd/lotus-shed/main.go, cmd/lotus-shed/migrations.go, go.mod, go.sum, itests/migration_test.go
https://github.com/filecoin-project/lotus/issues/11071
- Imported v12 of the filecoin state types in migrations.go. This allows the system to interpret and operate on the latest structure of filecoin state information, ensuring compatibility with the latest version of the Filecoin network.
- Updated the 'getMigrationFuncsForNetwork' function to include a case for network.Version21, enabling the use of the UpgradeActorsV12 and PreUpgradeActorsV12 functions for network migration. These changes ensure the system correctly handles migrations when the network upgrades to version 21.
- Include latest version of go-state-types module which includes optimizations for AMT diffing, allowing this migration to happen swiftly
- Added a new 'pprof' flag to the command-line arguments in main.go. This …
=> Feat/nv21 migrations optimized tree diff algorithm 

chain/store/store.go, chain/store/store_test.go
I was doing some manual testing / code inspection of #11104, and realized there's an unfortunate case here where we can get stuck, especially immediately after startup when the `tipsets` cache isn't populated
When refreshing our current head, try to find something within 5 epochs. If we find NOTHING (due to equivocation, or due to the `tipsets` cache being unpopulated), just stick with your equivocated head.
=> fix: chainstore: do not get stuck in unhappy equivocation cases

cmd/lotus-worker/main.go
Closes: #11138
Add support for IPv6 formatted API keys in the lotus-worker.
Testing plan:
=> fix: worker: Support IPv6 formatted API-keys

cli/sync.go, cli/wallet.go, cli/wallet_test.go
Closes #11134
Only display the `warning: may display 0 if chain sync in progress` if behind sync and balance is 0 in the `lotus wallet balance <f....>`
Tested on the butterfly-network. Address with a balance of 1000 FIL at a later epoch, deleted the chain data, and synced from scratch:
When sync in progress:
```
lotus sync wait
Worker: 0; Base: 0; Target: 2104 (diff: 2104)
State: message sync; Current Epoch: 1983; Todo: 121
Validated 648 messages (115 per second)
```
Wallet balance displays the error:
```
lotus wallet balance t1yhrjgfj6lknqbdbe2px2vgljltgxbwyt6em3r6q
0 FIL (warning: may display 0 if chain sync in progress)
```
After syncing past the epoch where it got funds, not displaying the warning:
```
lotus wallet balance t1yhrjgfj6lknqbdbe2px2vgljltgxbwyt6em3r6q
1000 FIL
```
On a …
=> fix: cli: Only display `warning` if behind sync

itests/migration_test.go
This builds on #11149 to add a few more "vanilla" sanity checks that always apply
Check that:
- system actor is now v12
- the Manifest stored in the system actor state matches what Lotus expects
=> feat: test: Add more post-migration sanity checks

go.mod, go.sum, itests/verifreg_test.go
@jennijuju requested this on Slack, just to confirm our expectation that verified clients can today create allocations themselves by transferring datacap to the verifreg actor with the appropriate params.
Add a test showing this is, in fact, the case.
Needs https://github.com/filecoin-project/go-state-types/pull/201 in a tagged release.
=> feat: test: Test that verified clients can directly transfer datacap, creating allocations

Makefile
Fixes: #11186 
Add BUILD_DEPS to lotus-wallet
Tested to work on a clean Lotus-repo
=> fix: build: Allow lotus-wallet to be built independently

node/impl/storminer.go
#11133 
Run the unsealing task in a background context so the unseal cmd doesn't hang while the process runs for multiple hours
=> fix: sealing: Run unsealing in the background for better ux

cmd/lotus-shed/msg.go
#10254
Adds receipts and exec-traces to the `lotus-shed msg` cmd
Tested in a local-devnet, the `./lotus-shed msg baf...x5u` now prints:
```
/lotus-shed msg bafy2bzaceaa7xynhzusr2erwhfx6y27eael77i2rfvplwsucj3jkn5cakgx5u       
Execution trace:
{
"Msg": {
"From": "f0100",
"To": "f01000",
"Value": "0",
"Method": 16,
"Params": "gUoABWvHXi1jEAAA",
"ParamsCodec": 81
},
"MsgRct": {
"ExitCode": 0,
"Return": "SgAFa8deLWMQAAA=",
"ReturnCodec": 81
},
"GasCharges": [
{
"Name": "OnChainMessage",
"tg": 675063,
"cg": 38863,
"sg": 636200,
"tt": 0
},
{
.....
......
........
"Subcalls": [
{
"Msg": {
"From": "f01000",
"To": "f0100",
"Value": "100000000000000000000",
"Method": 0,
"Params": null,
"ParamsCodec": 0
},
"MsgRct": {
"ExitCode": 0,
"Return": null,
"ReturnCodec": 0
},
"GasCharges": [
{
"Name": …
```
=> feat: shed: Add exec traces to `lotus-shed msg`

go.mod, go.sum
These dependencies were based on branches which no longer exist.
=> fix: build: use tagged releases

go.mod, go.sum
Update the test-vectors repo to the "last" release. This release deletes most of the code (that depended on an ancient version of lotus anyways) as we now rely on the "fvm" test vectors for all but historical tests.
=> chore: test-vectors: update

storage/pipeline/cbor_gen.go, storage/pipeline/fsm_events.go, storage/pipeline/fsm_test.go, storage/pipeline/states_failed.go, storage/pipeline/states_sealing.go, storage/pipeline/types.go, storage/sealer/storiface/worker.go
* Any issue which refers PC1 loops
Instead of retrying PC1 forever, only retry PC1 up to 3 times
This fixes the issue where PC1 will be retried e.g. in cases where for whatever reason unsealed data doesn't match what should have come from deals:
```
seal pre commit(1) failed: storage call error 0: presealing sector 6705 (/data/4/store/unsealed/s-t02620-6705): pieces and comm_d do not match [name: okonomiyaki]: presealing sector 6705 (/data/4/store/unsealed/s-t02620-6705): pieces and comm_d do not match
7928.	2023-07-18 21:52:31 +0200 CEST:	[event;sealing.SectorRetrySealPreCommit1]	{"User":{}}
7929.	2023-07-18 21:54:09 +0200 CEST:	[event;sealing.SectorSealPreCommit1Failed]	{"User":{}}
seal pre commit(1) failed: storage call error 0: presealing sector 6705 …
```
=> fix: sealing pipeline: Fix PC1 retry loop

chain/sub/incoming.go, chain/sub/incoming_test.go
The sequence number used for replay detection was being updated before message validation confirmed that the message originated from the correct host. This would allow one host A to create a message with the ID of another host B that could then update the cached sequence number for B. While the message from A would fail validation and be ignored, the cached sequence number for B would get updated. This would lead to a temporary DoS for host B as its messages were incorrectly rejected as replays.
Host A would need to be authorized to send messages on the network, so this issue could only be caused by an authorized host.
This fixes the issue by setting the cached sequence number after message validation.
A unit test is included that demonstrates the issue is fixed. It fails with the …
=> fix: chain: Do not update message info cache until after message validation

storage/sealer/ffiwrapper/sealer_test.go
Downloading a 1GB file during a unit test is bad enough, but doing it in serial with a 600mb file followed by a lot of work is too much. 
A patch sent to Orjan downloads those in parallel. 
This takes the download out of the 30s timer and into a 1m30m (all test targets) window.
This will buy more time for the test to complete no matter what the delay is (if the problem is a timeout).
IF this fixes CI, we should discuss why we are having repeated, enormous downloads from filecoin websites as part of unit testing.
=> Take Download out of Sealer time

Dockerfile
Should fix failing master build
=> fix: dockerfile: Bump to Go 1.20.7 image

node/impl/client/client.go
Drive-by error message improvement having just received this error message many layers removed from this source.
I also wonder what it would take to remove this constraint finally? We've been relaxing the len(Roots)==1 constraint everywhere else.
=> fix(client): single-root error message

build/params_2k.go, build/params_butterfly.go, build/params_calibnet.go, build/params_interop.go, build/params_mainnet.go, build/params_testground.go, itests/kit/ensemble.go, miner/miner.go
#11104 
- Add a (currently unconfigurable) EquivocationDelaySecs build parameter set to 2 seconds for all networks besides devnets
- In the `mineOne` process, at the _very end_, refresh the base we're mining on
- If the base has changed, we "refresh" our base to be the _intersection_ of the old base and new base. The only effect this should have is to _remove_ any blocks from miners that have equivocated.
- If we do this, we need to re-select messages (since some might no longer be valid), and re-compute ticket if the MinTicket has changed
- If the base hasn't changed, proceed as always
- `PR type`: fix, feat, build, chore, ci, docs, perf, refactor, revert, …
=> feat: miner: implement FRC-0051

.github/pull_request_template.md
[Slack discussion](https://filecoinproject.slack.com/archives/C03EUC3RS15/p1693587120930849?thread_ts=1693583837.050009&cid=C03EUC3RS15)
Updating the PR template so remind us that PR which may affect users should be included in the Changelog
=> docs: Update PR template to callout remembering to update CHANGELOG

cmd/lotus-worker/main.go
Closes #11223 
Check if `DC_[SectorSize]_[ResourceRestriction]` enviroment variable is set and convert it to `DC_[ResourceRestriction]` to make sure its enforced as DC is a sector-size independent job.
- export `DC_512MiB_MAX_CONCURRENT=1`
- export `DC_512MiB_MAX_PARALLELISM=1`
On startup of the worker, check that the env-variables are being converted:
```
lotus-worker run --data-cid=true --addpiece=false --precommit1=false --unseal=false --precommit2=false --commit=false --replica-update=false --prove-replica-update2=false --regen-sector-key=false --sector-download=false 
2023-08-30T05:18:50.118-0400    INFO    main    lotus-worker/main.go:297        Starting lotus worker
2023-08-30T05:18:50.118-0400    WARN    main    lotus-worker/main.go:343        Converted DC_512MiB_MAX_PARALLELISM …
```
=> fix: worker: Convert `DC_[SectorSize]_[ResourceRestriction]` if set

cmd/lotus-bench/simple.go, storage/paths/fetch.go, storage/paths/local.go, storage/paths/remote.go, storage/paths/util_unix.go, storage/sealer/ffiwrapper/basicfs/fs.go, storage/sealer/ffiwrapper/sealer_cgo.go, storage/sealer/ffiwrapper/sealer_test.go, storage/sealer/ffiwrapper/types.go, storage/sealer/manager.go, storage/sealer/manager_test.go, storage/sealer/proofpaths/cachefiles.go, storage/sealer/proofpaths/cachefiles_test.go, storage/sealer/roprov.go, storage/sealer/worker_local.go
Depends on https://github.com/filecoin-project/go-state-types/pull/191
Depends on https://github.com/filecoin-project/filecoin-ffi/pull/402
(todo link relevant issues)
Testing:
=> Snapdeals unsealing fixes

miner/miner.go
We're looking into reports of missed blocks due to mining taking too long. It's currently hard to analyze what the cause might be, because we only log the detailed breakdown of timing if the entire process was longer than 30s. However, we also want this information if by the time we're done producing the block, we've already reached the block's timestamp
Log the detailed breakdown more liberally
=> feat: miner: log detailed timing breakdown when mining takes longer than the block's timestamp

miner/miner.go
The calculation of these durations was rendered incorrect by #11157 
Correct the logging metrics, and add more fine-grained ones for equivocation.
=> fix: miner: correct duration logs in mineOne

storage/sealer/proofpaths/cachefiles_test.go
TestSDRLayersDefined has been failing on master, it's new in #11011. This is because it tests over all SealProofInfos as defined in go-state-types, which includes synth porep stuff. 
- Explicitly skip this check for the synth porep range for now
- We should remove this when `feat/nv21` is merged into master (will open issue for it)
- The real solution is that we're gonna need to start having integration branches in go-state-types for stuff like this
=> fix: test: temporarily exempt SynthPorep constants from test

cmd/lotus-shed/mpool.go
Used when investigating #11233
- Add timing to the MpoolSelect function in `lotus-shed mpool miner-select-messages` cmd.
- Print amount of message in the mpool at the time of selection
`./lotus-shed mpool miner-select-messages` now outputs:
```
0: ...7pujnqji -> ...vmfvetfq, method 3844450837, gasFeecap 46289400, gasPremium 40492000, gasLimit 10000000, val 8.27 FIL
1: ...kg3xciiq -> ...s2ocur4i, method 0, gasFeecap 182943, gasPremium 182943, gasLimit 6045518, val 2.480098894014800526 FIL
2: ...r7bysmqa -> ...02246008, method 7, gasFeecap 398186, gasPremium 125034, gasLimit 84979263, val 4.072569871868727119 FIL
3: ...zzdz67wq -> f062937, method 5, gasFeecap 10000000000, gasPremium 120603, gasLimit 41479801, val 0 FIL
4: ...zzdz67wq -> f062937, method 5, gasFeecap 10000000000, gasPremium …
```
=> fix: shed: additional metrics in `mpool miner-select-messages`

node/modules/services.go
Avoid dialing when trying to handshake peers. We're trying to handshake with _connected_ peers, but that doesn't mean we want to re-connect if the connection was transient. Also, avoid handshaking with peers that don't support the handshake protocol.
Reported in slack https://filecoinproject.slack.com/archives/C03K82MU486/p1694181455279969
=> fix: networking: avoid dialing when trying to handshake peers

cli/sync.go, cli/util/eta.go
none
This PR adds a ETA indicator to `lotus sync wait` command which I felt was missing when waiting for my node to finish syncing
=> feat: Add ETA to lotus sync wait

cmd/lotus-miner/sectors.go
Add a `Unsealing sector XX` print to `lotus-miner sectors unseal` cmd
=> fix: cli: Add print to unseal cmd

itests/eth_filter_test.go, node/impl/full/eth_utils.go
Attempting to debug the rare flake of eth_filter_test.go's TestTxReceiptBloom 5 instead of 6
=> eth_filter flake debug

CHANGELOG.md, blockstore/splitstore/splitstore_compact.go
See https://github.com/filecoin-project/lotus/issues/11251
When splitstore is enabled we perform compaction every 7h30m. During this compaction (which takes several minutes on my fast SSD) there is  relatively small purging step which takes approx 15sec. The purging step chunks the cids which should be purged and operates on them in blocks. In each block it acquires an exclusive lock which it shares with other I/O operation (for example FVM when applying messages). 
So when purging happens, other operations like MpoolSelect block for the whole 15sec duration when it needs to compute tipset state (TipSetState).
I added a simple time slicing to the purging step which only tries to purge for 1 sec, while pausing for 1 sec until it is done. This effectively makes the purge 2x slower, but I …
=> fix: Add time slicing to splitstore purging to reduce lock congestion

.gitignore
None
Although we can configure this globally, we should just always ignore .vscode directory to make sure it doesn't get accidentally included in future PRs
None
=> fix: Add .vscode to gitignore

cli/wallet.go
Closes: #7919
Wrap error when a msig is trying to sign a msg, explaining that msig messages needs to propose & approve.
When trying to sign with a msig, error is now wrapped as:
```
lotus wallet sign t2pgqal7cetyqb6thbkb6s4nlbx3to5mm4azc43si 3fa85f6457174562b3fc2c963f66afa6
ERROR: multisig is an actor account that doesn’t have keys to sign transactions. To send a message with a multisig, signers of the multisig need to propose and approve transactions.
```
=> fix: cli: Wrap error in wallet sign

CHANGELOG.md, cmd/lotus/daemon.go
Based on the discussion https://filecoinproject.slack.com/archives/CP50PPW2X/p1695108301930859
When user wants to import chain file or snapshot, we will by default remove the local chain data, unless the user says otherwise.
None.
=> Feat: Lotus Daemon CLI: Auto remove existing chain if importing chain file or snapshot

chain/exchange/client.go, cli/net.go, itests/api_test.go, lib/consensus/raft/consensus.go, node/impl/net/rcmgr.go, node/modules/lp2p/host.go
The `go-libp2p` peerID Pretty method is already deprecated, switch it to call String method.
Signed-off-by: Icarus9913 [icaruswu66@qq.com](mailto:icaruswu66@qq.com)
=> fix: deps: stop using go-libp2p deprecated peer.ID.Pretty

storage/sealer/manager.go
=> fix: sealing: typo in FinalizeReplicaUpdate

build/bootstrap/butterflynet.pi
Add the new Butterfly assets after the recent reset.
=> chore: butterfly: Add preliminary nv21 assets

cmd/lotus-worker/main.go
Fix regression introduces in https://github.com/filecoin-project/lotus/pull/11141, where a remote lotus-worker was unable to connect, unless the --listen flag was specified.
Should be backported to the `release/v1.23.4` branch.
Starting the lotus-worker on a remote server w/different IP-address, failed unless the `--listen` was set after adding https://github.com/filecoin-project/lotus/pull/11141.
Testing cases:
```
./lotus-worker run --no-default=true --unseal=true
2023-09-23T07:41:22.600Z        INFO    main    lotus-worker/main.go:298        Starting lotus worker
2023-09-23T07:41:22.604Z        INFO    main    lotus-worker/main.go:384        Remote version 1.23.4-rc1+mainnet+git.c7b3d84cc.dirty+api1.5.0
----
2023-09-23T07:41:22.627Z        INFO    main    lotus-worker/main.go:725 …
```
=> fix: worker: Connect when --listen is not set

CHANGELOG.md, README.md, metrics/README.md, metrics/grafana/MessageExecution.json, metrics/prometheus.yml
https://github.com/filecoin-project/lotus/issues/10888
This PR adds documentation for how to installation and setting up [`Prometheus`](https://prometheus.io/), [`Grafana`](https://grafana.com/) and [`node_exporter`](https://github.com/prometheus/node_exporter) to get a fully working monitoring system running against a local running lotus node. 
Currently the instructions have been tested on Mac M1 and Ubuntu linux.
This PR includes a pre-configured Prometheus configuration as well as an initial dashboard I created for investigating where time is spent in ApplyBlocks which is executed as part of ExecuteTipSet. We should aim to have dashboards targeted for each individual users (miners, rpc providers, core devs, etc) and maintain them inside the Lotus codebase (currently using …
=> feat: Instructions for setting up Grafana/Prometheus for monitoring local lotus node

cmd/lotus-bench/cli.go, cmd/lotus-bench/main.go, cmd/lotus-bench/reporter.go, cmd/lotus-bench/rpc.go
Written to help with solving https://github.com/filecoin-project/lotus/issues/11251
Extension to the RPC benchmark introduced in https://github.com/filecoin-project/lotus/pull/10761
This PR extends the RPC benchmark to support running any binary and analyze their latency and histogram distribution, track most common errors, perform stress testing under different concurrency levels and see how it works under different QPS. 
Lets say you want to understand how `lotus-shed mpool miner-select-messages` behaves over time. 
You can use this new `lotus-bench cli` tool to achieve this, for example the following command runs the command using a single thread (concurrency=1) at 1 qps and provides a realtime updated latency/histogram UI and it runs for 24 hours. 
`lotus-bench cli  --cmd='lotus-shed …
=> feat: Add lotus-bench cli option to stress test any binary

CHANGELOG.md, cmd/lotus-miner/actor.go, documentation/en/cli-lotus-miner.md, go.mod, go.sum
https://github.com/filecoin-project/lotus/issues/11272
Add `move-partition` subcommand to `lotus-miner actor` command.
Still waiting for corresponding actor changes to merge https://github.com/filecoin-project/builtin-actors/pull/1326/files
Before
```
$ ./lotus-miner proving deadlines
Miner: t01000
deadline  partitions  sectors (faults)  proven partitions
0         0           0 (0)             0
1         0           0 (0)             0
2         0           0 (0) …
```
=> Feat: Lotus cli: actor: Support move partition command to move partitions' deadline

build/bootstrap/mainnet.pi
Remove Protocol Labs's EU bootstrap nodes, as they've been decommissioned as
part of a cost reduction project.
=> Remove PL's european bootstrap nodes from mainnet.pi

miner/miner.go
@Stebalien was concerned that this could cause miners to fail to produce blocks when if they see a reorg of height > 1 partway through the mining loop. The issue is that if the tipset at the height of the base's parent changes, the intersection between old and new base MUST be null, and the miner will fail.
Weaken the check against equivocation a little -- if the intersection is null, just use the old base (even though it risks "allowing" some equivocation.).
=> feat: miner: defensive check for equivocation

chain/actors/policy/policy.go, chain/actors/policy/policy.go.template, chain/actors/policy/policy_test.go, documentation/en/default-lotus-miner-config.toml, go.mod, go.sum, node/config/doc_gen.go, node/config/types.go, node/impl/full/state.go, storage/wdpost/wdpost_run_test.go
Integrates https://github.com/filecoin-project/builtin-actors/pull/1436
=> feat: limit PoSted partitions to 3

build/params_calibnet.go
Set the calibration upgrade height to `epoch 1013200`. Which should be equal to:
- 13:00 UTC on October 19th, 2023
- 6:00 AM in Los Angeles - 2:00 PM in London - 9:00 PM in Beijing
=> chore: release: Set calibration upgrade height

build/bootstrap/butterflynet.pi
Butterfly-network has been reset with lotus v1.24.0-rc1, for a last round of regression testing. No need to merge this PR, opened it to make it easier to cherry-pick the assets.
=> chore: build: Butterfly assets

go.mod, go.sum
go-state-types 0.12.4 was missing one of the proofs mappings, fixed in https://github.com/filecoin-project/go-state-types/pull/227
Pull in new, correct-er GST.
=> chore: deps: update to go-state-types v0.12.5

storage/sealer/proofpaths/cachefiles.go
Backport commit 864eef3e4c8f9d3fef4e4c55bed2524c07e6a7ff to release/v1.25.0, dropping the exemptions in cachefiles test as highlighted in: https://github.com/filecoin-project/lotus/issues/11260 which caused test-unit-storage to fail in https://github.com/filecoin-project/lotus/pull/11343
=> backport: fix: cachefiles: add SynthPorep layers

storage/paths/local.go, storage/pipeline/states_sealing.go
#11087 is missing one case making it possible that some sectors will get removed when SP pipelines are under heavy load
Example logs before
```
3.	2023-10-17 03:04:43 +0200 CEST:	[event;sealing.SectorStartPacking]	{"User":{}}
4.	2023-10-17 03:04:43 +0200 CEST:	[event;sealing.SectorPacked]	{"User":{"FillerPieces":null}}
5.	2023-10-17 03:04:43 +0200 CEST:	[event;sealing.SectorTicket]	{"User":{"TicketValue":"ai7dVU55W2rBSUfblw+o8f81YfGyIWKjQu8eSV1KibA=","TicketEpoch":3305709}}
6.	2023-10-17 03:16:38 +0200 CEST:	[event;sealing.SectorSealPreCommit1Failed]	{"User":{}}
seal pre commit(1) failed: storage call error 0: acquiring sector paths: local acquire error: couldn't find a suitable path for a sector [name: okonomiyaki]: acquiring sector paths: local acquire error: couldn't find a suitable …
```
=> storage: Return soft err when sector alloc fails in acquire

CHANGELOG.md, chain/events/filter/event.go, chain/events/filter/index.go, chain/events/filter/index_test.go
In Ethereum it is expected that the `eth_getLogs` endpoint will only return results for canonical blocks. Non-canonical logs are already being marked correctly in the events.db sqlite database as "reverted", and this adds a missing conditional check on that column when selecting logs from the database. 
Adds a missing conditional check on the "reverted" column when selecting logs from the events index sqlite database. 
Necessary for proper subgraph functionality.
=> fix: api: exclude reverted events in `eth_getLogs` results

storage/paths/local.go, storage/pipeline/states_sealing.go
#11338 
https://github.com/filecoin-project/lotus/pull/11087 (currently in release/v1.25.0) was missing one error-case, making it possible that some sectors will get removed when SP pipelines are under heavy load. This backport ensures that a soft err  is returned when sector alloc fails in acquire.
Testing: https://github.com/filecoin-project/lotus/pull/11338#issuecomment-1768583993
=> chore: backport 11338 onto release/v1.25.0

node/impl/full/eth.go
Part of #11325.
Return errors on failure to lookup an eth txn receipt.
All these cases here are actually errors and returning `nil` makes this hard to debug. We likely returned nil in the past to be "best effort" but, as far as I can tell, we should only hit these error cases if something is actually wrong.
=> fix: api: return errors on failure to lookup an eth txn receipt

node/impl/full/eth.go
fixes #10515
When computing the `gasUsedRatio` in the Ethereum JSON-RPC APIs use `MaxBlockGas * len(TipSet)`, instead of the max block gas. Otherwise, we get ratios over 1.
The new value isn't entirely correct either (we should probably compute an average of the gas used in each block in the tipset?), but it's good enough.
=> fix: api: compute gasUsedRatio based on max gas in the tipset

storage/sealer/ffiwrapper/sealer_cgo.go
API surface reduction.
The `ClearLayerData` FFI call was accidentally introduced with the Synthetic PoRep. The call does under the hood exactly what `ClearCache` is doing. This is a first step to remove `ClearLayerData`t also from the FFI again, in order to reduce the API surface.
=> refactor:ffi: replace ClearLayerData with ClearCache

blockstore/idstore.go, cmd/lotus-shed/pruning.go
1. Implement a pass-through for garbage collection on the idstore.
2. Fix the `lotus-shed state-prune` command.
NOTE: the new performance of running a full prune will be significantly less as this version doesn't batch. However, it should now actually _work_ and most users will be using the splitstore anyways.
- x ] PR title is in the form of of `<PR type>: <area>: <change being made>`
=> feat: shed: fix blockstore prune

chain/beacon/drand/drand_test.go
switch tests to drand testnet (from devnet)
At the request of the drand team (@CluEleSsUK, specifically).
=> test: drand: switch tests to drand testnet (from devnet)

chain/sync.go
Every now and then my node seems to get "stuck" syncing, and stays that way for a long while (or until restart).
This PR changes our `fetchMessages` logic to directly process the fetched messages, and request any additional ones needed.
=> fix: sync: iterate over returned messages directly

README.md
Updating README to ask for Go version 1.20.x instead of 1.19.x
=> readme: bump up golang version
